description: 'This is a test for Google Vault playbooks. It calls all search commands:
  Google Vault - Search Drive, Google Vault - Search Groups, Google Vault - Search
  Mail. In addition it uses: Google Vault - Search And Display Results with 3 different
  variations.'
id: Google_Vault-Search_And_Display_Results_test
inputs: []
name: Google Vault - Search And Display Results test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 9c2fe40d-d707-4069-8ad3-bd28ae4b06c3
      iscommand: false
      name: ''
      version: -1
    taskid: 9c2fe40d-d707-4069-8ad3-bd28ae4b06c3
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      dataScope:
        simple: All Data
      downloadFile:
        simple: 'true'
      emails:
        simple: admin@demistodev.com
      endTime: {}
      exportMBOX:
        simple: 'false'
      exportName:
        complex:
          root: NEW_PASSWORD
          transformers:
          - args:
              dt:
                value:
                  simple: .='Mail_Export_' + val +'_Time_' + Date.now()
            operator: DT
      exportPST:
        simple: 'true'
      includeDrafts:
        simple: 'true'
      matterID:
        simple: ${GoogleVault.Matter.MatterID}
      maxResultForDisplay: {}
      ou: {}
      pollInterval:
        simple: '1'
      pollTimeout:
        simple: '5'
      searchMethod:
        simple: Specific Accounts(requires emails argument)
      startTime:
        simple: 2019-07-10 00:00:00+00:00
      terms:
        simple: test*
      timeFrame: {}
    separatecontext: true
    task:
      brand: ''
      description: This is a playbook for performing Google Vault search in Mail accounts
        and display the results.
      id: 9854eeba-3e06-4fff-861c-cae45e659a81
      iscommand: false
      name: Google Vault - Search Mail
      playbookName: Google Vault - Search Mail
      type: playbook
      version: -1
    taskid: 9854eeba-3e06-4fff-861c-cae45e659a81
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: 51f2cead-2bb0-492d-8194-05f0b0d0a4cb
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 51f2cead-2bb0-492d-8194-05f0b0d0a4cb
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1945\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      debug: {}
      max_digits:
        simple: '2'
      max_lcase:
        simple: '2'
      max_symbols:
        simple: '0'
      max_ucase:
        simple: '2'
      min_digits:
        simple: '2'
      min_lcase:
        simple: '2'
      min_symbols: {}
      min_ucase:
        simple: '2'
    separatecontext: false
    task:
      brand: ''
      id: 8bbb6e7a-9762-46ee-897c-ca48a414d16e
      iscommand: false
      name: Generate ID
      scriptName: GeneratePassword
      type: regular
      version: -1
    taskid: 8bbb6e7a-9762-46ee-897c-ca48a414d16e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      debug: {}
      max_digits:
        simple: '2'
      max_lcase:
        simple: '2'
      max_symbols:
        simple: '0'
      max_ucase:
        simple: '2'
      min_digits:
        simple: '2'
      min_lcase:
        simple: '2'
      min_symbols: {}
      min_ucase:
        simple: '2'
    separatecontext: false
    task:
      brand: ''
      id: 217e1b05-52d9-443b-8638-a6919d3fa96c
      iscommand: false
      name: Generate ID
      scriptName: GeneratePassword
      type: regular
      version: -1
    taskid: 217e1b05-52d9-443b-8638-a6919d3fa96c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2295\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      description:
        simple: search_and_display_results_
      name:
        simple: ${.= 'search_and_display_results_' + new Date()}
    separatecontext: false
    task:
      brand: ''
      description: Creates a new matter with the specified name and description. The
        initial state is open, and the owner is the method caller. First, checks if
        a matter with the same name already exists.
      id: 98bd894a-101f-49e4-8524-247c902fcc89
      iscommand: true
      name: gvault-create-matter
      script: '|||gvault-create-matter'
      type: regular
      version: -1
    taskid: 98bd894a-101f-49e4-8524-247c902fcc89
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      description:
        simple: search_and_display_results_
      name:
        simple: ${.= 'search_and_display_results_' + new Date()}
    separatecontext: false
    task:
      brand: ''
      description: Creates a new matter with the specified name and description. The
        initial state is open, and the owner is the method caller. First, checks if
        a matter with the same name already exists.
      id: 007af3fb-4ea7-42fc-8ea7-0ae9f26cab1e
      iscommand: true
      name: gvault-create-matter
      script: '|||gvault-create-matter'
      type: regular
      version: -1
    taskid: 007af3fb-4ea7-42fc-8ea7-0ae9f26cab1e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      description:
        simple: search_and_display_results_
      name:
        simple: ${.= 'search_and_display_results_' + new Date()}
    separatecontext: false
    task:
      brand: ''
      description: Creates a new matter with the specified name and description. The
        initial state is open, and the owner is the method caller. First, checks if
        a matter with the same name already exists.
      id: c71047a5-24b2-4cd6-8902-dfa182b5502d
      iscommand: true
      name: gvault-create-matter
      script: '|||gvault-create-matter'
      type: regular
      version: -1
    taskid: c71047a5-24b2-4cd6-8902-dfa182b5502d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2120\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      dataScope:
        simple: All Data
      downloadFile:
        simple: 'true'
      endTime: {}
      exportMBOX:
        simple: 'false'
      exportName:
        complex:
          root: NEW_PASSWORD
          transformers:
          - args:
              dt:
                value:
                  simple: .='Groups_Export_' + val +'_Time_' + Date.now()
            operator: DT
      exportPST:
        simple: 'true'
      groups:
        simple: maya-group-test@demistodev.com,ido-group-test@demistodev.com
      matterID:
        simple: ${GoogleVault.Matter.MatterID}
      maxResultForDisplay:
        simple: '30'
      pollInterval:
        simple: '1'
      pollTimeout:
        simple: '5'
      startTime: {}
      terms: {}
      timeFrame: {}
    separatecontext: true
    task:
      brand: ''
      description: This is a playbook for performing Google Vault search in Groups
        and display the results.
      id: 402b61a6-8fa3-431e-8839-c193bc644302
      iscommand: false
      name: Google Vault - Search Groups
      playbookName: Google Vault - Search Groups
      type: playbook
      version: -1
    taskid: 402b61a6-8fa3-431e-8839-c193bc644302
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      dataScope:
        simple: All Data
      downloadFile:
        simple: 'true'
      emails:
        simple: test@demistodev.com,maya@demistodev.com
      endTime: {}
      exportMBOX:
        simple: 'false'
      exportName:
        complex:
          root: NEW_PASSWORD
          transformers:
          - args:
              dt:
                value:
                  simple: .='Drive_Export_' + val +'_Time_' + Date.now()
            operator: DT
      exportPST:
        simple: 'true'
      includeTeamDrives:
        simple: 'false'
      matterID:
        simple: ${GoogleVault.Matter.MatterID}
      maxResultForDisplay:
        simple: '30'
      ou: {}
      pollInterval:
        simple: '2'
      pollTimeout:
        simple: '30'
      searchMethod:
        simple: Team Drive
      startTime: {}
      teamDrive:
        simple: 0ANbMMsaWJNw2Uk9PVA,0AOM4L2G2JU4NUk9PVA
      terms: {}
      timeFrame: {}
    separatecontext: true
    task:
      brand: ''
      description: This is a playbook for performing Google Vault search in Drive
        accounts and display the results.
      id: 82c88e57-cc16-43a1-888b-9fef09e55781
      iscommand: false
      name: Google Vault - Search Drive
      playbookName: Google Vault - Search Drive
      type: playbook
      version: -1
    taskid: 82c88e57-cc16-43a1-888b-9fef09e55781
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2470\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      debug: {}
      max_digits:
        simple: '2'
      max_lcase:
        simple: '2'
      max_symbols:
        simple: '0'
      max_ucase:
        simple: '2'
      min_digits:
        simple: '2'
      min_lcase:
        simple: '2'
      min_symbols: {}
      min_ucase:
        simple: '2'
    separatecontext: false
    task:
      brand: ''
      id: fa81357a-793b-4575-8e5e-80ae3bcfccc9
      iscommand: false
      name: Generate ID
      scriptName: GeneratePassword
      type: regular
      version: -1
    taskid: fa81357a-793b-4575-8e5e-80ae3bcfccc9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: 66884289-d722-40fc-8799-fed9cde01580
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 66884289-d722-40fc-8799-fed9cde01580
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      ExportID:
        simple: ${GoogleVault.Matter.Export.ExportID}
      MatterID:
        simple: ${GoogleVault.Matter.MatterID}
      SearchtType:
        simple: Groups
      downloadFile:
        simple: 'false'
      maxResultForDisplay:
        simple: '30'
      pollInterval:
        simple: '2'
      pollTimeout:
        simple: '30'
    separatecontext: true
    task:
      brand: ''
      description: This is a playbook for queuing and displaying vault search result
      id: 58ca6734-0715-4d9f-80e4-e2fa049cf60b
      iscommand: false
      name: Google Vault - Display Results
      playbookName: Google Vault - Display Results
      type: playbook
      version: -1
    taskid: 58ca6734-0715-4d9f-80e4-e2fa049cf60b
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      ExportID:
        simple: ${GoogleVault.Matter.Export.ExportID}
      MatterID:
        simple: ${GoogleVault.Matter.MatterID}
      SearchtType:
        simple: Mail
      downloadFile:
        simple: 'false'
      maxResultForDisplay:
        simple: '30'
      pollInterval:
        simple: '2'
      pollTimeout:
        simple: '30'
    separatecontext: true
    task:
      brand: ''
      id: ee2f949d-c277-4fd4-8523-0f70603e3d1c
      iscommand: false
      name: Google Vault - Display Results
      playbookName: Google Vault - Display Results
      type: playbook
      version: -1
    taskid: ee2f949d-c277-4fd4-8523-0f70603e3d1c
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    note: false
    scriptarguments:
      ExportID:
        simple: ${GoogleVault.Matter.Export.ExportID}
      MatterID:
        simple: ${GoogleVault.Matter.Export.MatterID}
      SearchtType:
        simple: Drive
      downloadFile:
        simple: 'false'
      maxResultForDisplay:
        simple: '30'
      pollInterval:
        simple: '2'
      pollTimeout:
        simple: '30'
    separatecontext: true
    task:
      brand: ''
      id: 112f3b9d-e39d-4d0a-81a9-0c90f1d11670
      iscommand: false
      name: Google Vault - Display Results
      playbookName: Google Vault - Display Results
      type: playbook
      version: -1
    taskid: 112f3b9d-e39d-4d0a-81a9-0c90f1d11670
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2645\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: 56d68919-7802-4aa3-8b3f-a5ab6045f477
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 56d68919-7802-4aa3-8b3f-a5ab6045f477
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2690,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
