id: SNDBOX_Test
inputs: []
name: SNDBOX_Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 1f76b2c6-56b4-492b-8f01-fef26d30580b
      iscommand: false
      name: ''
      version: -1
    taskid: 1f76b2c6-56b4-492b-8f01-fef26d30580b
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: bb8a9eaa-b13d-4b92-8844-db60143a19a4
      iscommand: false
      name: Start Clean
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: bb8a9eaa-b13d-4b92-8844-db60143a19a4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - '15'
    note: false
    quietmode: 0
    scriptarguments:
      AdditionalPollingCommandArgNames: {}
      AdditionalPollingCommandArgValues: {}
      Ids:
        complex:
          accessor: Analysis.ID
          root: SNDBOX
      Interval:
        simple: '1'
      PollingCommandArgName:
        simple: analysis_id
      PollingCommandName:
        simple: sndbox-analysis-info
      Timeout:
        simple: '10'
      dt:
        simple: SNDBOX.Analysis(val.Status !== 'finished').ID
    separatecontext: true
    skipunavailable: false
    task:
      brand: ''
      description: 'Use this playbook as a sub-playbook to block execution of the
        master playbook until a remote action is complete.

        This playbook implements polling by continuously running the command in Step
        \#2 until the operation completes.

        The remote action should have the following structure:


        1. Initiate the operation.

        2. Poll to check if the operation completed.

        3. (optional) Get the results of the operation.'
      id: 7667863b-8a21-4a02-858d-3d78c9ddad50
      iscommand: false
      name: GenericPolling - Get Info
      playbookName: GenericPolling
      type: playbook
      version: -1
    taskid: 7667863b-8a21-4a02-858d-3d78c9ddad50
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1070\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      analysis_id:
        simple: ${SNDBOX.Analysis.ID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 0e396be1-ad3e-40a8-875b-f8422f36210d
      iscommand: true
      name: Get Info
      script: '|||sndbox-analysis-info'
      type: regular
      version: -1
    taskid: 0e396be1-ad3e-40a8-875b-f8422f36210d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1245\n  }\n}"
  '17':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Analysis.Status
                root: SNDBOX
          operator: isEqualString
          right:
            value:
              simple: pending
      label: still pending
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Analysis.Status
                root: SNDBOX
          operator: isEqualString
          right:
            value:
              simple: error
      label: is error
    id: '17'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '7'
      is error:
      - '18'
      still pending:
      - '9'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 377ef394-7ce1-4396-83db-a614ed322ae7
      iscommand: false
      name: If the analysis is still pending or is a SNDBOX error then don't try and
        download the report
      type: condition
      version: -1
    taskid: 377ef394-7ce1-4396-83db-a614ed322ae7
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1595\n  }\n}"
  '18':
    id: '18'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: d998e639-3821-4e43-833d-75f7ebf9e313
      iscommand: false
      name: End Test
      type: title
      version: -1
    taskid: d998e639-3821-4e43-833d-75f7ebf9e313
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 1785\n  }\n}"
  '19':
    id: '19'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 8a3750c1-b80b-4039-8fc1-a9cd7f637475
      iscommand: false
      name: End Test
      type: title
      version: -1
    taskid: 8a3750c1-b80b-4039-8fc1-a9cd7f637475
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1945\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 5e8202af-7c64-44da-8e40-6be815c7cfb9
      iscommand: true
      name: Is Integration Online
      script: '|||sndbox-is-online'
      type: regular
      version: -1
    taskid: 5e8202af-7c64-44da-8e40-6be815c7cfb9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quietmode: 0
    scriptarguments:
      body: {}
      filename:
        simple: file.pdf
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://raw.githubusercontent.com/demisto/content/master/TestData/pdfworking.pdf
      username: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 793976c0-cba3-4e2e-80a5-02930f48a358
      iscommand: false
      name: Get Test File
      scriptName: http
      type: regular
      version: -1
    taskid: 793976c0-cba3-4e2e-80a5-02930f48a358
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      file_id:
        simple: ${File.EntryID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 9878e6c3-b82d-4bb2-8e3e-cc41cbfdb58e
      iscommand: true
      name: Submit
      script: '|||sndbox-analysis-submit-sample'
      type: regular
      version: -1
    taskid: 9878e6c3-b82d-4bb2-8e3e-cc41cbfdb58e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    quietmode: 0
    scriptarguments:
      analysis_id:
        simple: ${SNDBOX.Analysis.ID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: e7ce29ea-9cb5-40f1-8296-29048818b7f5
      iscommand: true
      name: Get Info
      script: '|||sndbox-analysis-info'
      type: regular
      version: -1
    taskid: e7ce29ea-9cb5-40f1-8296-29048818b7f5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 895\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    quietmode: 0
    scriptarguments:
      analysis_id:
        simple: ${SNDBOX.Analysis.ID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: ef7207bd-274c-4de5-8952-c38c73b0dfa2
      iscommand: true
      name: Download Sample
      script: '|||sndbox-download-sample'
      type: regular
      version: -1
    taskid: ef7207bd-274c-4de5-8952-c38c73b0dfa2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1420\n  }\n}"
  '7':
    continueonerror: true
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '19'
    note: false
    quietmode: 0
    scriptarguments:
      analysis_id:
        complex:
          accessor: Analysis.ID
          root: SNDBOX
      type: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 20302088-47c1-4acf-81a3-a7c46d8f4c03
      iscommand: true
      name: Download Report
      script: '|||sndbox-download-report'
      type: regular
      version: -1
    taskid: 20302088-47c1-4acf-81a3-a7c46d8f4c03
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 0985e709-3217-4d93-8353-a6938c435486
      iscommand: false
      name: End Test
      type: title
      version: -1
    taskid: 0985e709-3217-4d93-8353-a6938c435486
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1785\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1960,\n      \"width\": 1240,\n      \"x\": 50,\n      \"y\":\
  \ 50\n    }\n  }\n}"
