id: Detonate File - SNDBOX - Test
inputs: []
name: Detonate File - SNDBOX - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 78c271cb-d8af-41fd-8fda-a63ffdb3a88e
      iscommand: false
      name: ''
      version: -1
    taskid: 78c271cb-d8af-41fd-8fda-a63ffdb3a88e
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      id: 3e175f62-728f-4863-809e-08c04f75646d
      iscommand: false
      name: Start fresh
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 3e175f62-728f-4863-809e-08c04f75646d
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    note: false
    scriptarguments:
      File:
        complex:
          root: File
      Interval:
        simple: '1'
      Timeout:
        simple: '15'
    separatecontext: true
    task:
      brand: ''
      id: 2c00b69d-0bb7-4d37-876d-5c654c740ab6
      iscommand: false
      name: SNDBOX - Detonate File
      playbookName: Detonate File - SNDBOX
      type: playbook
      version: -1
    taskid: 2c00b69d-0bb7-4d37-876d-5c654c740ab6
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '9':
    id: '9'
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      body: {}
      filename:
        simple: test_file.pdf
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://raw.githubusercontent.com/demisto/content/master/TestData/pdfworking.pdf
      username: {}
    separatecontext: false
    task:
      brand: ''
      id: e4d803ff-4a96-40dd-8f12-d88707123dc5
      iscommand: false
      name: Create sample file
      scriptName: http
      type: regular
      version: -1
    taskid: e4d803ff-4a96-40dd-8f12-d88707123dc5
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 590,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
