id: ACM-Test
inputs: []
name: ACM-Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 5d116c67-5ca8-4ec0-8026-590fb5260179
      iscommand: false
      name: ''
      version: -1
    taskid: 5d116c67-5ca8-4ec0-8026-590fb5260179
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      certificateStatuses: {}
      extendedKeyUsage: {}
      keyTypes: {}
      keyUsage: {}
      region:
        simple: us-west-2
      roleArn: {}
      roleSessionDuration: {}
      roleSessionName: {}
    separatecontext: false
    task:
      brand: AWS - ACM
      description: Retrieves a list of certificate ARNs and domain names. You can
        request that only certificates that match a specific status be listed. You
        can also filter by specific attributes of the certificate.
      id: e7836897-a59e-4ec1-8a54-ea9528e23e7d
      iscommand: true
      name: aws-acm-list-certificates
      script: AWS - ACM|||aws-acm-list-certificates
      type: regular
      version: -1
    taskid: e7836897-a59e-4ec1-8a54-ea9528e23e7d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 190\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    note: false
    scriptarguments:
      certificateArn:
        simple: ${AWS.ACM.Certificates.CertificateArn}
      region: {}
      roleArn: {}
      roleSessionDuration: {}
      roleSessionName: {}
    separatecontext: false
    task:
      brand: AWS - ACM
      description: Returns detailed metadata about the specified ACM certificate.
      id: d2cc05e9-740e-4dc9-82e0-b0805b77bbc2
      iscommand: true
      name: aws-acm-describe-certificate
      script: AWS - ACM|||aws-acm-describe-certificate
      type: regular
      version: -1
    taskid: d2cc05e9-740e-4dc9-82e0-b0805b77bbc2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 370\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 415,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\": 50\n\
  \    }\n  }\n}"
