id: PagerDuty Test
inputs: []
name: PagerDuty Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 7d81fe1a-b9e7-4b39-8781-1cd41d351394
      iscommand: false
      name: ''
      version: -1
    taskid: 7d81fe1a-b9e7-4b39-8781-1cd41d351394
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      query: {}
    separatecontext: false
    task:
      brand: ''
      id: 0fa77151-6efb-4c01-8b2e-e038eef5f707
      iscommand: true
      name: Get on call users
      script: '|||PagerDuty-get-users-on-call-now'
      type: regular
      version: -1
    taskid: 0fa77151-6efb-4c01-8b2e-e038eef5f707
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 865\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      escalation_policy_ids: {}
      limit: {}
      query: {}
      schedule_ids:
        simple: PFE1I5O,PO93R76
    separatecontext: false
    task:
      brand: ''
      id: 6d293021-89d8-4f74-89ea-38fae70b9bab
      iscommand: true
      name: Get on call users- schedule_ids
      script: '|||PagerDuty-get-users-on-call-now'
      type: regular
      version: -1
    taskid: 6d293021-89d8-4f74-89ea-38fae70b9bab
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1390\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 93dc62a3-0833-4e0c-860f-268133e69889
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 93dc62a3-0833-4e0c-860f-268133e69889
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1215\n  }\n}"
  '12':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Email
                root: PagerDutyUser
          operator: containsGeneral
          right:
            value:
              simple: meir@demisto.com
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Email
                root: PagerDutyUser
          operator: containsGeneral
          right:
            value:
              simple: rony@demisto.com
      label: 'yes'
    id: '12'
    ignoreworker: false
    nexttasks:
      'yes':
      - '13'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 7353e653-17ad-4303-8f3b-20dc69a94fd6
      iscommand: false
      name: Verify context
      type: condition
      version: -1
    taskid: 7353e653-17ad-4303-8f3b-20dc69a94fd6
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1565\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    scriptarguments:
      escalation_policy_ids:
        simple: PJUYEWG
      limit: {}
      schedule_ids: {}
    separatecontext: false
    task:
      brand: ''
      description: Returns the names and details of current on call personnel
      id: 6a306912-cbf5-4b8d-86cc-355ea5cf6f0e
      iscommand: true
      name: Get on call users-escalation_policy_ids
      script: '|||PagerDuty-get-users-on-call-now'
      type: regular
      version: -1
    taskid: 6a306912-cbf5-4b8d-86cc-355ea5cf6f0e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1740\n  }\n}"
  '14':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Email
                root: PagerDutyUser
          operator: containsGeneral
          right:
            value:
              simple: dan@demisto.com
      label: 'yes'
    id: '14'
    ignoreworker: false
    nexttasks:
      'yes':
      - '15'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 7d024e4e-695f-4c6e-8a08-f5a89dc46db7
      iscommand: false
      name: Verify context
      type: condition
      version: -1
    taskid: 7d024e4e-695f-4c6e-8a08-f5a89dc46db7
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1915\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: b3b8304a-969a-4a94-86b9-32db986aa37d
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: b3b8304a-969a-4a94-86b9-32db986aa37d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2090\n  }\n}"
  '16':
    id: '16'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    scriptarguments:
      append: {}
      key:
        simple: escalation_policy_ids
      value:
        simple: '["P4J5L11","PJUYEWG"]'
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 50ac163a-041f-4c84-8abd-138acec6c853
      iscommand: false
      name: Set escalation_policy_ids in context
      scriptName: Set
      type: regular
      version: -1
    taskid: 50ac163a-041f-4c84-8abd-138acec6c853
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2265\n  }\n}"
  '17':
    id: '17'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '18'
    note: false
    scriptarguments:
      escalation_policy_ids:
        simple: ${escalation_policy_ids}
      limit: {}
      schedule_ids: {}
    separatecontext: false
    task:
      brand: ''
      description: Returns the names and details of current on call personnel
      id: 361cd2e3-89e6-4c51-804c-7b5db7d6188b
      iscommand: true
      name: Get on call users-escalation_policy_ids
      script: '|||PagerDuty-get-users-on-call-now'
      type: regular
      version: -1
    taskid: 361cd2e3-89e6-4c51-804c-7b5db7d6188b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2440\n  }\n}"
  '18':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Email
                root: PagerDutyUser
          operator: containsGeneral
          right:
            value:
              simple: dan@demisto.com
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Email
                root: PagerDutyUser
          operator: containsGeneral
          right:
            value:
              simple: meir@demisto.com
      label: 'yes'
    id: '18'
    ignoreworker: false
    nexttasks:
      'yes':
      - '9'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 04f312ce-bcbc-4010-8f90-694fec5ed81d
      iscommand: false
      name: Verify context
      type: condition
      version: -1
    taskid: 04f312ce-bcbc-4010-8f90-694fec5ed81d
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2615\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: PagerDutyUser.ID
    separatecontext: false
    task:
      brand: ''
      id: eb6f57a1-02fa-4d90-8fad-b6fe878fbad4
      iscommand: false
      name: Verify context
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: eb6f57a1-02fa-4d90-8fad-b6fe878fbad4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1040\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      query: {}
      requesterID: {}
    separatecontext: false
    task:
      brand: ''
      id: 4da31dfb-f411-4ff4-861c-316ce63b5501
      iscommand: true
      name: Get schedules
      script: '|||PagerDuty-get-all-schedules'
      type: regular
      version: -1
    taskid: 4da31dfb-f411-4ff4-861c-316ce63b5501
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 340\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: PagerDuty.Schedules
    separatecontext: false
    task:
      brand: ''
      id: 71eff7d1-30a4-441e-898f-d96fff862dfc
      iscommand: false
      name: Verify Context
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 71eff7d1-30a4-441e-898f-d96fff862dfc
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 515\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      since: {}
      sortBy: {}
      status: {}
      until: {}
    separatecontext: false
    task:
      brand: ''
      id: 12579f84-18d9-4b55-8d05-a0e6d184f312
      iscommand: true
      name: 'Get Incidents '
      script: '|||PagerDuty-incidents'
      type: regular
      version: -1
    taskid: 12579f84-18d9-4b55-8d05-a0e6d184f312
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 690\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: c58f7088-121c-4c60-8898-3b21d4f05a0b
      iscommand: false
      name: PagerDuty Commands
      type: title
      version: -1
    taskid: c58f7088-121c-4c60-8898-3b21d4f05a0b
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: f023b851-5819-4d83-8d96-82b7b48e0cb2
      iscommand: false
      name: End of test
      type: title
      version: -1
    taskid: f023b851-5819-4d83-8d96-82b7b48e0cb2
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2790\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2805,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
