id: Archer-Test-Playbook
inputs: []
name: Archer-Test-Playbook
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '7'
    separatecontext: false
    task:
      brand: ''
      id: f0e69132-f55d-4ae5-8b52-778e55acd7a7
      iscommand: false
      name: ''
      version: -1
    taskid: f0e69132-f55d-4ae5-8b52-778e55acd7a7
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '3'
    scriptarguments:
      applicationId:
        simple: ${Archer.Applications.Id}
      fieldsToValues:
        simple: '{"Title":"${incident.name}","Incident Summary":"Something"}'
    separatecontext: false
    task:
      brand: RSA Archer
      description: Creates a new content record in the given application.
      id: 284fbdb2-b08a-4b7d-8247-d2d990df0996
      iscommand: true
      name: archer-create-record
      script: RSA Archer|||archer-create-record
      type: regular
      version: -1
    taskid: 284fbdb2-b08a-4b7d-8247-d2d990df0996
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 719\n  }\n}"
  '10':
    id: '10'
    nexttasks:
      '#none#':
      - '8'
    scriptarguments:
      field1:
        simple: Archer.Record.Id
      field2:
        simple: Archer.Record.Fields.Title
      field3: {}
      field4: {}
      value1:
        simple: ${Archer.Record.Id}
      value2:
        simple: Update!!!
      value3: {}
      value4: {}
    separatecontext: false
    task:
      brand: ''
      id: c5e32912-c4a0-4dd0-8302-8593e18ff271
      iscommand: false
      name: VerifyContextFields
      scriptName: VerifyContextFields
      type: regular
      version: -1
    taskid: c5e32912-c4a0-4dd0-8302-8593e18ff271
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
  '11':
    id: '11'
    nexttasks:
      '#none#':
      - '5'
    scriptarguments:
      field1:
        simple: Archer.Record.Id
      field2:
        simple: Archer.Record.Fields.Title
      field3: {}
      field4: {}
      value1:
        simple: ${Archer.Record.Id}
      value2:
        simple: ${incident.name}
      value3: {}
      value4: {}
    separatecontext: false
    task:
      brand: ''
      id: 04a41628-1783-4341-8d62-68c882a607bb
      iscommand: false
      name: VerifyContextFields
      scriptName: VerifyContextFields
      type: regular
      version: -1
    taskid: 04a41628-1783-4341-8d62-68c882a607bb
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '4'
    scriptarguments:
      findById: {}
      findByName:
        simple: Security Incidents
    separatecontext: false
    task:
      brand: RSA Archer
      description: Gets application details or list of all applications.
      id: 0e1d0876-0e0e-48d3-8f7e-72da418a0970
      iscommand: true
      name: archer-search-applications
      script: RSA Archer|||archer-search-applications
      type: regular
      version: -1
    taskid: 0e1d0876-0e0e-48d3-8f7e-72da418a0970
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 368\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '11'
    scriptarguments:
      applicationId:
        simple: ${Archer.Applications.Id}
      contentId:
        simple: ${Archer.Record.Id}
    separatecontext: false
    task:
      brand: RSA Archer
      description: Gets information about a content record in the given application.
      id: eb9afe2d-9340-407e-8e32-0df27389874f
      iscommand: true
      name: archer-get-record
      script: RSA Archer|||archer-get-record
      type: regular
      version: -1
    taskid: eb9afe2d-9340-407e-8e32-0df27389874f
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '1'
    scriptarguments:
      applicationId:
        simple: ${Archer.Applications.Id}
    separatecontext: false
    task:
      brand: RSA Archer
      description: Gets all application fields by application ID
      id: 85b667c6-3140-4710-8f77-937ef4074ee0
      iscommand: true
      name: archer-get-application-fields
      script: RSA Archer|||archer-get-application-fields
      type: regular
      version: -1
    taskid: 85b667c6-3140-4710-8f77-937ef4074ee0
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '6'
    scriptarguments:
      applicationId:
        simple: ${Archer.Applications.Id}
      contentId:
        simple: ${Archer.Record.Id}
      fieldsToValues:
        simple: '{"Title":"Update!!!"}'
    separatecontext: false
    task:
      brand: RSA Archer
      description: Updates existing content record in the given application.
      id: f35780e5-84d8-4c84-80ad-68f180532f5f
      iscommand: true
      name: archer-update-record
      script: RSA Archer|||archer-update-record
      type: regular
      version: -1
    taskid: f35780e5-84d8-4c84-80ad-68f180532f5f
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '10'
    scriptarguments:
      applicationId:
        simple: ${Archer.Applications.Id}
      dateOperator: {}
      fieldToSearchOn:
        simple: Incident ID (KPI)
      fieldsToDisplay:
        simple: Incident ID,Title,Date Created
      maxResults:
        simple: '1'
      numericOperator: {}
      searchValue:
        simple: ${Archer.Record.Id}
    separatecontext: false
    task:
      brand: RSA Archer
      description: Search for records inside the given application
      id: 3af106d8-91a9-4307-85f9-d6e0b87d29db
      iscommand: true
      name: archer-search-records
      script: RSA Archer|||archer-search-records
      type: regular
      version: -1
    taskid: 3af106d8-91a9-4307-85f9-d6e0b87d29db
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1418\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: eecdd672-f139-4df2-8431-70ec8968d19b
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: eecdd672-f139-4df2-8431-70ec8968d19b
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '9'
    scriptarguments:
      applicationId:
        simple: ${Archer.Applications.Id}
      contentId:
        simple: ${Archer.Record.Id}
    separatecontext: false
    task:
      brand: RSA Archer
      description: Delete existing content record in the given application.
      id: 247a903e-adfc-439e-894b-cbcedeb9fb36
      iscommand: true
      name: archer-delete-record
      script: RSA Archer|||archer-delete-record
      type: regular
      version: -1
    taskid: 247a903e-adfc-439e-894b-cbcedeb9fb36
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '9':
    id: '9'
    scriptarguments:
      applicationId:
        simple: ${Archer.Applications.Id}
      dateOperator: {}
      fieldToSearchOn:
        simple: Incident ID (KPI)
      fieldsToDisplay:
        simple: Incident ID,Title,Date Created
      maxResults:
        simple: '1'
      numericOperator: {}
      searchValue:
        simple: ${Archer.Record.Id}
    separatecontext: false
    task:
      brand: RSA Archer
      description: Search for records inside the given application
      id: 5db409eb-e253-4ec5-8d96-580b4e6c8fab
      iscommand: true
      name: archer-search-records
      script: RSA Archer|||archer-search-records
      type: regular
      version: -1
    taskid: 5db409eb-e253-4ec5-8d96-580b4e6c8fab
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1952\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1997,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
