id: Test IP Indicator Fields
inputs: []
name: Test IP Indicator Fields
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 840e9af7-bd61-487b-86ff-8ab283b84ce0
      iscommand: false
      name: ''
      version: -1
    taskid: 840e9af7-bd61-487b-86ff-8ab283b84ce0
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      accounttype: {}
      actor: {}
      address: {}
      admincountry: {}
      adminemail: {}
      adminname: {}
      adminphone: {}
      asn:
        simple: test
      associatedfilenames: {}
      biosversion: {}
      comment: {}
      country: {}
      creationdate: {}
      customFields: {}
      cvedescription: {}
      cvss: {}
      detectionengines:
        simple: '5'
      devicemodel: {}
      dhcpserver: {}
      displayname: {}
      dns: {}
      domainname:
        simple: TestName
      domainstatus: {}
      emailaddress:
        simple: test@demisto.com
      entryid: {}
      expirationdate: {}
      fileextension: {}
      filetype: {}
      geocountry: {}
      geolocation: {}
      groups: {}
      hostname: {}
      id: {}
      internal:
        simple: 'true'
      ipaddress: {}
      macaddress: {}
      malwarefamily:
        simple: test
      md5: {}
      memory: {}
      merge: {}
      modified: {}
      name: {}
      nameservers: {}
      operatingsystem: {}
      operatingsystemversion: {}
      organization: {}
      organizationalunitou: {}
      path: {}
      positivedetections:
        simple: '1'
      processor: {}
      processors: {}
      published: {}
      registrantcountry: {}
      registrantemail: {}
      registrantname: {}
      registrantphone: {}
      registrarabuseemail: {}
      registrarabusephone: {}
      registrarname: {}
      relatedIncidents: {}
      reputation: {}
      seenNow: {}
      sha1: {}
      sha256: {}
      sha512: {}
      signatureauthentihash: {}
      signaturecopyright: {}
      signaturedescription: {}
      signaturefileversion: {}
      signatureinternalname: {}
      signed: {}
      size: {}
      source: {}
      sourceTimeStamp: {}
      ssdeep: {}
      subdomains: {}
      tags: {}
      type:
        simple: IP
      updateddate: {}
      username: {}
      value:
        simple: 5.6.4.1
    separatecontext: false
    task:
      brand: Builtin
      description: commands.local.cmd.new.indicator
      id: 7e471176-b33d-4e40-8641-35293e602811
      iscommand: true
      name: Create new IP Indicator (5.6.4.1)
      script: Builtin|||createNewIndicator
      type: regular
      version: -1
    taskid: 7e471176-b33d-4e40-8641-35293e602811
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 230\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      value:
        simple: 5.6.4.1
    separatecontext: false
    task:
      brand: ''
      description: Gets the created indicator
      id: 0248968f-b8f4-47e5-8d89-743b3cb8d5c0
      iscommand: false
      name: Get Created Indicator
      scriptName: GetIndicator
      type: regular
      version: -1
    taskid: 0248968f-b8f4-47e5-8d89-743b3cb8d5c0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 420\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: CustomFields.asn
                root: Indicator
          operator: isEqualString
          right:
            value:
              simple: test
      - - left:
            iscontext: true
            value:
              complex:
                accessor: CustomFields.detectionengines
                root: Indicator
          operator: isEqualNumber
          right:
            value:
              simple: '5'
      - - left:
            iscontext: true
            value:
              complex:
                accessor: CustomFields.domainname
                root: Indicator
          operator: isEqualString
          right:
            value:
              simple: TestName
      - - left:
            iscontext: true
            value:
              complex:
                accessor: CustomFields.emailaddress
                root: Indicator
          operator: isEqualString
          right:
            value:
              simple: test@demisto.com
      - - left:
            iscontext: true
            value:
              complex:
                accessor: CustomFields.internal
                root: Indicator
          operator: isTrue
      - - left:
            iscontext: true
            value:
              complex:
                accessor: CustomFields.malwarefamily.[0]
                root: Indicator
          operator: isEqualString
          right:
            value:
              simple: test
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Asserts custom fields were populated correctly
      id: e325aea4-599a-43cc-88cb-f831331ecc5b
      iscommand: false
      name: Assert custom fields were populated
      type: condition
      version: -1
    taskid: e325aea4-599a-43cc-88cb-f831331ecc5b
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 610\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: b390bc91-a3ee-4183-8066-40a23f49656c
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: b390bc91-a3ee-4183-8066-40a23f49656c
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 800\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 815,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\": 50\n\
  \    }\n  }\n}"
