id: TestExtractHTMLTables
inputs: []
name: TestExtractHTMLTables
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 6f985d96-565d-4836-84a8-5c64a6f0f054
      iscommand: false
      name: ''
      version: -1
    taskid: 6f985d96-565d-4836-84a8-5c64a6f0f054
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 245,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: fdb233ee-250f-4e76-8a44-5c8cb60e3742
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: fdb233ee-250f-4e76-8a44-5c8cb60e3742
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 245,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    quietmode: 0
    scriptarguments:
      html:
        simple: <html><body><table><tr><td>a</td><td>1</td></tr><tr><td>b</td><td>2</td></tr></table></body></html>
      indexes: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: 'Find tables inside HTML and extract the contents into objects
        using the following logic:

        - If table has a single column, just create an array of strings from the values

        - If table has 2 columns and has no header row, treat the first column as
        key and second as value and create a table of key/value

        - If table has a header row, create a table of objects where attribute names
        are the headers

        - If table does not have a header row, create table of objects where attribute
        names are cell1, cell2, cell3...'
      id: f5d4fc0b-beb5-4b65-8c45-b1064e4489d0
      iscommand: false
      name: ExtractHTMLTables with two columns and no headers
      scriptName: ExtractHTMLTables
      type: regular
      version: -1
    taskid: f5d4fc0b-beb5-4b65-8c45-b1064e4489d0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 470,\n    \"y\": 1420\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '5'
      'yes':
      - '12'
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${HTMLTables(val.a == '1' && val.b == '2')}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: b3a182f9-c634-4c36-83c4-b11ac4e08bd1
      iscommand: false
      name: Both objects exist
      scriptName: Exists
      type: condition
      version: -1
    taskid: b3a182f9-c634-4c36-83c4-b11ac4e08bd1
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 470,\n    \"y\": 1595\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 923566c3-69e7-4c6b-8ac6-4a4fbd008647
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 923566c3-69e7-4c6b-8ac6-4a4fbd008647
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 582.5,\n    \"y\": 1770\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    quietmode: 0
    scriptarguments:
      html:
        simple: <html><body><table><tr><th>kuku</th><th>kaka</th></tr><tr><td>a</td><td>1</td></tr><tr><td>b</td><td>2</td></tr></table></body></html>
      indexes: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: 'Find tables inside HTML and extract the contents into objects
        using the following logic:

        - If table has a single column, just create an array of strings from the values

        - If table has 2 columns and has no header row, treat the first column as
        key and second as value and create a table of key/value

        - If table has a header row, create a table of objects where attribute names
        are the headers

        - If table does not have a header row, create table of objects where attribute
        names are cell1, cell2, cell3...'
      id: 9be54c10-3781-4902-8064-fc4f5be5ba2f
      iscommand: false
      name: ExtractHTMLTables with two columns and headers
      scriptName: ExtractHTMLTables
      type: regular
      version: -1
    taskid: 9be54c10-3781-4902-8064-fc4f5be5ba2f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 582.5,\n    \"y\": 1945\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '5'
      'yes':
      - '15'
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${HTMLTables(val.kuku == 'a' && val.kaka == '1' || val.kuku == 'b'
          && val.kaka == '2')}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: df03d00f-21d2-4ced-8aff-aa87a5375244
      iscommand: false
      name: All objects exist
      scriptName: Exists
      type: condition
      version: -1
    taskid: df03d00f-21d2-4ced-8aff-aa87a5375244
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 582.5,\n    \"y\": 2120\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 3e903ef7-74e2-4a3e-8fa8-ba69ef2260a9
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 3e903ef7-74e2-4a3e-8fa8-ba69ef2260a9
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 592.5,\n    \"y\": 2310\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      html:
        simple: <html><body><table><tr><th>kuku</th></tr><tr><td>a</td></tr><tr><td>1</td></tr></table></body></html>
      indexes: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: 'Find tables inside HTML and extract the contents into objects
        using the following logic:

        - If table has a single column, just create an array of strings from the values

        - If table has 2 columns and has no header row, treat the first column as
        key and second as value and create a table of key/value

        - If table has a header row, create a table of objects where attribute names
        are the headers

        - If table does not have a header row, create table of objects where attribute
        names are cell1, cell2, cell3...'
      id: 84b8ce61-dbf9-44f5-81ea-cb36210a6a96
      iscommand: false
      name: ExtractHTMLTables with single one column table with header
      scriptName: ExtractHTMLTables
      type: regular
      version: -1
    taskid: 84b8ce61-dbf9-44f5-81ea-cb36210a6a96
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 245,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '5'
      'yes':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: '${HTMLTables=>val[0] == ''a'' && val[1] == ''1'' ? ''x'' : ''''}'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 69356d1f-4850-4f81-8cc8-a0c337ff3a81
      iscommand: false
      name: Both values exist in array
      scriptName: Exists
      type: condition
      version: -1
    taskid: 69356d1f-4850-4f81-8cc8-a0c337ff3a81
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 245,\n    \"y\": 545\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      value: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 46e4b665-56cd-4025-8dc6-b6e5c29b4e4f
      iscommand: false
      name: Bad
      scriptName: Print
      type: regular
      version: -1
    taskid: 46e4b665-56cd-4025-8dc6-b6e5c29b4e4f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2295\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 5cdcb58d-4398-4cb2-84c0-ec4c138e80a9
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 5cdcb58d-4398-4cb2-84c0-ec4c138e80a9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 357.5,\n    \"y\": 720\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      html:
        simple: <html><body><table><tr><td>a</td></tr><tr><td>1</td></tr></table></body></html>
      indexes: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: 'Find tables inside HTML and extract the contents into objects
        using the following logic:

        - If table has a single column, just create an array of strings from the values

        - If table has 2 columns and has no header row, treat the first column as
        key and second as value and create a table of key/value

        - If table has a header row, create a table of objects where attribute names
        are the headers

        - If table does not have a header row, create table of objects where attribute
        names are cell1, cell2, cell3...'
      id: 0edabdca-e319-4746-8ec1-f996259aa82e
      iscommand: false
      name: ExtractHTMLTables with single one column table without header
      scriptName: ExtractHTMLTables
      type: regular
      version: -1
    taskid: 0edabdca-e319-4746-8ec1-f996259aa82e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 357.5,\n    \"y\": 895\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '5'
      'yes':
      - '9'
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: '${HTMLTables=>val[0] == ''a'' && val[1] == ''1'' ? ''x'' : ''''}'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 583d4e43-5d38-423d-8a93-24623e778876
      iscommand: false
      name: Both values exist in array
      scriptName: Exists
      type: condition
      version: -1
    taskid: 583d4e43-5d38-423d-8a93-24623e778876
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 357.5,\n    \"y\": 1070\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 5fd0ceec-578d-4695-8469-c37084e34433
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 5fd0ceec-578d-4695-8469-c37084e34433
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 470,\n    \"y\": 1245\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2340,\n      \"width\": 922.5,\n      \"x\": 50,\n      \"y\"\
  : 50\n    }\n  }\n}"
