id: CompareIncidentsLabels-test-playbook
inputs: []
name: CompareIncidentsLabels test playbook
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 9daed4bd-f446-4009-8626-73581bfd6060
      iscommand: false
      name: ''
      version: -1
    taskid: 9daed4bd-f446-4009-8626-73581bfd6060
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      affecteddata: {}
      affecteddatatype: {}
      affectedindividualscontactinformation: {}
      app: {}
      approximatenumberofaffecteddatasubjects: {}
      assetid: {}
      attachmentcount: {}
      attachmentextension: {}
      attachmenthash: {}
      attachmentid: {}
      attachmentname: {}
      attachmentsize: {}
      attachmenttype: {}
      bugtraq: {}
      city: {}
      companyaddress: {}
      companycity: {}
      companycountry: {}
      companyhasinsuranceforthebreach: {}
      companyname: {}
      companypostalcode: {}
      contactaddress: {}
      contactname: {}
      country: {}
      countrywherebusinesshasitsmainestablishment: {}
      countrywherethebreachtookplace: {}
      customFields: {}
      cve: {}
      cvss: {}
      dataencryptionstatus: {}
      datetimeofthebreach: {}
      dest: {}
      destntdomain: {}
      details: {}
      dpoemailaddress: {}
      duration: {}
      emailaddress: {}
      emailbcc: {}
      emailbody: {}
      emailbodyformat: {}
      emailbodyhtml: {}
      emailcc: {}
      emailclientname: {}
      emailfrom: {}
      emailinreplyto: {}
      emailkeywords: {}
      emailmessageid: {}
      emailreceived: {}
      emailreplyto: {}
      emailreturnpath: {}
      emailsenderip: {}
      emailsize: {}
      emailsource: {}
      emailsubject: {}
      emailto: {}
      emailtocount: {}
      emailurlclicked: {}
      entryIDs: {}
      filehash: {}
      filename: {}
      filepath: {}
      isthedatasubjecttodpia: {}
      labels:
        simple: '[{"id":"1234"},{"type":"new incident"}]'
      likelyimpact: {}
      maliciouscauseifthecauseisamaliciousattack: {}
      malwarefamily: {}
      measurestomitigate: {}
      name:
        simple: new incident
      occurred: {}
      owner: {}
      phase: {}
      possiblecauseofthebreach: {}
      postalcode: {}
      roles: {}
      sectorofaffectedparty: {}
      severity: {}
      signature: {}
      sizenumberofemployees: {}
      sizeturnover: {}
      sla: {}
      slaField: {}
      src: {}
      srcntdomain: {}
      srcuser: {}
      systems: {}
      telephoneno: {}
      type: {}
      user: {}
      vendorid: {}
      vendorproduct: {}
      vulnerabilitycategory: {}
      whereisdatahosted: {}
    separatecontext: false
    task:
      brand: Builtin
      description: commands.local.cmd.create.inc
      id: db9958e9-ea8e-4b39-86ee-ccb32636d11e
      iscommand: true
      name: Create incident
      script: Builtin|||createNewIncident
      type: regular
      version: -1
    taskid: db9958e9-ea8e-4b39-86ee-ccb32636d11e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      affecteddata: {}
      affecteddatatype: {}
      affectedindividualscontactinformation: {}
      app: {}
      approximatenumberofaffecteddatasubjects: {}
      assetid: {}
      attachmentcount: {}
      attachmentextension: {}
      attachmenthash: {}
      attachmentid: {}
      attachmentname: {}
      attachmentsize: {}
      attachmenttype: {}
      bugtraq: {}
      city: {}
      companyaddress: {}
      companycity: {}
      companycountry: {}
      companyhasinsuranceforthebreach: {}
      companyname: {}
      companypostalcode: {}
      contactaddress: {}
      contactname: {}
      country: {}
      countrywherebusinesshasitsmainestablishment: {}
      countrywherethebreachtookplace: {}
      customFields: {}
      cve: {}
      cvss: {}
      dataencryptionstatus: {}
      datetimeofthebreach: {}
      dest: {}
      destntdomain: {}
      details: {}
      dpoemailaddress: {}
      duration: {}
      emailaddress: {}
      emailbcc: {}
      emailbody: {}
      emailbodyformat: {}
      emailbodyhtml: {}
      emailcc: {}
      emailclientname: {}
      emailfrom: {}
      emailinreplyto: {}
      emailkeywords: {}
      emailmessageid: {}
      emailreceived: {}
      emailreplyto: {}
      emailreturnpath: {}
      emailsenderip: {}
      emailsize: {}
      emailsource: {}
      emailsubject: {}
      emailto: {}
      emailtocount: {}
      emailurlclicked: {}
      entryIDs: {}
      filehash: {}
      filename: {}
      filepath: {}
      isthedatasubjecttodpia: {}
      labels:
        simple: '[{"id":"1234"},{"type":"new incident"}]'
      likelyimpact: {}
      maliciouscauseifthecauseisamaliciousattack: {}
      malwarefamily: {}
      measurestomitigate: {}
      name:
        simple: New Incident
      occurred: {}
      owner: {}
      phase: {}
      possiblecauseofthebreach: {}
      postalcode: {}
      roles: {}
      sectorofaffectedparty: {}
      severity: {}
      signature: {}
      sizenumberofemployees: {}
      sizeturnover: {}
      sla: {}
      slaField: {}
      src: {}
      srcntdomain: {}
      srcuser: {}
      systems: {}
      telephoneno: {}
      type: {}
      user: {}
      vendorid: {}
      vendorproduct: {}
      vulnerabilitycategory: {}
      whereisdatahosted: {}
    separatecontext: false
    task:
      brand: Builtin
      description: commands.local.cmd.create.inc
      id: f406e101-d395-4d92-8387-39d4a4dd85d9
      iscommand: true
      name: Create the same incident
      script: Builtin|||createNewIncident
      type: regular
      version: -1
    taskid: f406e101-d395-4d92-8387-39d4a4dd85d9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      affecteddata: {}
      affecteddatatype: {}
      affectedindividualscontactinformation: {}
      app: {}
      approximatenumberofaffecteddatasubjects: {}
      assetid: {}
      attachmentcount: {}
      attachmentextension: {}
      attachmenthash: {}
      attachmentid: {}
      attachmentname: {}
      attachmentsize: {}
      attachmenttype: {}
      bugtraq: {}
      city: {}
      companyaddress: {}
      companycity: {}
      companycountry: {}
      companyhasinsuranceforthebreach: {}
      companyname: {}
      companypostalcode: {}
      contactaddress: {}
      contactname: {}
      country: {}
      countrywherebusinesshasitsmainestablishment: {}
      countrywherethebreachtookplace: {}
      customFields: {}
      cve: {}
      cvss: {}
      dataencryptionstatus: {}
      datetimeofthebreach: {}
      dest: {}
      destntdomain: {}
      details: {}
      dpoemailaddress: {}
      duration: {}
      emailaddress: {}
      emailbcc: {}
      emailbody: {}
      emailbodyformat: {}
      emailbodyhtml: {}
      emailcc: {}
      emailclientname: {}
      emailfrom: {}
      emailinreplyto: {}
      emailkeywords: {}
      emailmessageid: {}
      emailreceived: {}
      emailreplyto: {}
      emailreturnpath: {}
      emailsenderip: {}
      emailsize: {}
      emailsource: {}
      emailsubject: {}
      emailto: {}
      emailtocount: {}
      emailurlclicked: {}
      entryIDs: {}
      filehash: {}
      filename: {}
      filepath: {}
      isthedatasubjecttodpia: {}
      labels:
        simple: '[{"id":"1234"},{"name":"different name"}]'
      likelyimpact: {}
      maliciouscauseifthecauseisamaliciousattack: {}
      malwarefamily: {}
      measurestomitigate: {}
      name:
        simple: another incident
      occurred: {}
      owner: {}
      phase: {}
      possiblecauseofthebreach: {}
      postalcode: {}
      roles: {}
      sectorofaffectedparty: {}
      severity: {}
      signature: {}
      sizenumberofemployees: {}
      sizeturnover: {}
      sla: {}
      slaField: {}
      src: {}
      srcntdomain: {}
      srcuser: {}
      systems: {}
      telephoneno: {}
      type: {}
      user: {}
      vendorid: {}
      vendorproduct: {}
      vulnerabilitycategory: {}
      whereisdatahosted: {}
    separatecontext: false
    task:
      brand: Builtin
      description: commands.local.cmd.create.inc
      id: 76a36dd5-1f52-461a-80f9-722ca2e2575b
      iscommand: true
      name: Create different incident
      script: Builtin|||createNewIncident
      type: regular
      version: -1
    taskid: 76a36dd5-1f52-461a-80f9-722ca2e2575b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      inc1:
        complex:
          root: CreatedIncidentID
          transformers:
          - args:
              index:
                value:
                  simple: '1'
            operator: atIndex
      inc2:
        complex:
          root: CreatedIncidentID
          transformers:
          - args:
              index:
                value:
                  simple: '0'
            operator: atIndex
      incident_id_1:
        complex:
          root: CreatedIncidentID
          transformers:
          - args:
              index:
                value:
                  simple: '1'
            operator: atIndex
      incident_id_2:
        complex:
          root: CreatedIncidentID
          transformers:
          - args:
              index:
                value:
                  simple: '0'
            operator: atIndex
    separatecontext: false
    task:
      brand: ''
      description: Compares the labels of two incidents. Returns the different labels
        in them.
      id: 931254fd-55df-43ef-82ee-737d158ecdcf
      iscommand: false
      name: Check the first 2 labels
      scriptName: CompareIncidentsLabels
      type: regular
      version: -1
    taskid: 931254fd-55df-43ef-82ee-737d158ecdcf
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    note: false
    scriptarguments:
      inc1:
        complex:
          root: CreatedIncidentID
          transformers:
          - args:
              index:
                value:
                  simple: '1'
            operator: atIndex
      inc2:
        complex:
          root: CreatedIncidentID
          transformers:
          - args:
              index:
                value:
                  simple: '2'
            operator: atIndex
      incident_id_1:
        complex:
          root: CreatedIncidentID
          transformers:
          - args:
              index:
                value:
                  simple: '1'
            operator: atIndex
      incident_id_2:
        complex:
          root: CreatedIncidentID
          transformers:
          - args:
              index:
                value:
                  simple: '2'
            operator: atIndex
    separatecontext: false
    task:
      brand: ''
      description: Compares the labels of two incidents. Returns the different labels
        in them.
      id: aa681551-105e-4adc-8756-d4b0f992523a
      iscommand: false
      name: Check the last 2 labels
      scriptName: CompareIncidentsLabels
      type: regular
      version: -1
    taskid: aa681551-105e-4adc-8756-d4b0f992523a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      seconds:
        simple: '5'
    separatecontext: false
    task:
      brand: ''
      description: Sleep for X seconds
      id: bb607639-6535-4d21-830e-8f2a651d933c
      iscommand: false
      name: Sleep
      scriptName: Sleep
      type: regular
      version: -1
    taskid: bb607639-6535-4d21-830e-8f2a651d933c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1115,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
