description: ''
id: ssdeepreputationtest
inputs: []
name: SsdeepReputationTest
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: dbec59ec-e05d-45e6-8825-b057869f3e26
      iscommand: false
      name: ''
      version: -1
    taskid: dbec59ec-e05d-45e6-8825-b057869f3e26
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '5'
    note: false
    results:
    - File
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 964eb74c-c5de-4b89-8ee6-00b69086aaee
      iscommand: false
      name: Ssdeep test
      scriptName: SsdeepReputationTest
      type: regular
      version: -1
    taskid: 964eb74c-c5de-4b89-8ee6-00b69086aaee
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    note: false
    scriptarguments:
      expectedValue:
        simple: '3'
      fields: {}
      path:
        simple: DBotScore.Score
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 1431aa83-164d-4968-8f15-36a3c37231a6
      iscommand: false
      name: Check score
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 1431aa83-164d-4968-8f15-36a3c37231a6
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 9f0c0bb9-6f10-4b60-8141-68188243c4a9
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 9f0c0bb9-6f10-4b60-8141-68188243c4a9
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      input:
        simple: ${expectBadSsdeepValue}
      threshold: {}
      timeFrameDays: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 15c90ae8-5fda-42c4-8c16-5df92587a7c6
      iscommand: false
      name: Check ssdeep reputation
      scriptName: SSDeepReputation
      type: regular
      version: -1
    taskid: 15c90ae8-5fda-42c4-8c16-5df92587a7c6
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      seconds:
        simple: '3'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: e6d478e1-17a7-451f-89c9-1fb33c4c40b7
      iscommand: false
      name: Sleep
      scriptName: Sleep
      type: regular
      version: -1
    taskid: e6d478e1-17a7-451f-89c9-1fb33c4c40b7
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 940,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
