id: HTTPListRedirects Basic Test
inputs: []
name: HTTPListRedirects Basic Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: c9a1c1c7-85c2-4270-8fc9-48e9235d1be1
      iscommand: false
      name: ''
      version: -1
    taskid: c9a1c1c7-85c2-4270-8fc9-48e9235d1be1
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      extend-context: {}
      url:
        simple: http://httpbin.org/redirect/3
      useHead:
        simple: 'true'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: List the redirects for a given URL
      id: 8423b0b5-829e-4ac1-88cc-c247fc291887
      iscommand: false
      name: HTTPListRedirects
      scriptName: HTTPListRedirects
      type: regular
      version: -1
    taskid: 8423b0b5-829e-4ac1-88cc-c247fc291887
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      'yes':
      - '3'
    note: false
    quietmode: 0
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        simple: ${.=val.URL.length}
      right:
        simple: '4'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Check whether the values provided in arguments are equal.
      id: 0e0a70e6-71f5-49b6-885f-b1e992a35a7b
      iscommand: false
      name: AreValuesEqual
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: 0e0a70e6-71f5-49b6-885f-b1e992a35a7b
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 6539bd08-2588-4d1f-8c02-52afe1e4b7c3
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 6539bd08-2588-4d1f-8c02-52afe1e4b7c3
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 560,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
