description: A test for the Set command. Tests the Stringify parameter too. Don't
  know why nobody ever made a test for this before.
id: Set - Test
inputs: []
name: Set - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 7c36eb3f-9942-48e8-807f-6d9ba95aaa49
      iscommand: false
      name: ''
      version: -1
    taskid: 7c36eb3f-9942-48e8-807f-6d9ba95aaa49
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    reputationcalc: 1
    scriptarguments:
      append: {}
      key:
        simple: NumberSavedAsNumber
      stringify: {}
      value:
        simple: '14444444444444444444'
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: a895badc-f535-4b02-8bda-dc723d980c6a
      iscommand: false
      name: Set number as number
      scriptName: Set
      type: regular
      version: -1
    taskid: a895badc-f535-4b02-8bda-dc723d980c6a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 750,\n    \"y\": 350\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    reputationcalc: 1
    scriptarguments:
      append: {}
      key:
        simple: NumberSavedAsString
      stringify:
        simple: 'true'
      value:
        simple: '14444444444444444444'
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: ed6bb94f-52b0-4658-83aa-ff1418fc6413
      iscommand: false
      name: Set number as string
      scriptName: Set
      type: regular
      version: -1
    taskid: ed6bb94f-52b0-4658-83aa-ff1418fc6413
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 150,\n    \"y\": 350\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: NumberSavedAsString
          operator: isEqualString
          right:
            value:
              simple: '14444444444444444444'
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '5'
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 73c819ed-b4dd-4b21-8a79-7966dcc981fe
      iscommand: false
      name: Was the number saved as string?
      type: condition
      version: -1
    taskid: 73c819ed-b4dd-4b21-8a79-7966dcc981fe
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 150,\n    \"y\": 520\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d3702fee-a4f5-4489-8de9-121cab4e9943
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d3702fee-a4f5-4489-8de9-121cab4e9943
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 440,\n    \"y\": 1040\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    reputationcalc: 1
    scriptarguments:
      message:
        simple: The number was not saved as string, or the number was saved as string
          instead of a number. Does your PR change the Stringify parameter of the
          Set command? Or was Demisto suddenly able to save the number 14444444444444444444
          as the actual number it is?
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: 9323b469-3922-41fc-8a1a-2faa26a165ad
      iscommand: false
      name: Fail the playbook
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 9323b469-3922-41fc-8a1a-2faa26a165ad
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 440,\n    \"y\": 750\n  }\n}"
  '6':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: NumberSavedAsNumber
          operator: isEqualNumber
          right:
            value:
              simple: '14444444444444444444'
      label: 'Yes'
    id: '6'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '5'
      'Yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 614f707c-fb36-485a-8b84-30452496f1f6
      iscommand: false
      name: Was the number saved as number?
      type: condition
      version: -1
    taskid: 614f707c-fb36-485a-8b84-30452496f1f6
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 750,\n    \"y\": 530\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
      - '2'
    note: false
    reputationcalc: 1
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: dd9ceaf2-f2fe-4c04-8d45-85690d2d19a9
      iscommand: false
      name: Clear the context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: dd9ceaf2-f2fe-4c04-8d45-85690d2d19a9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 180\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"3_4_yes\": 0.12,\n    \"6_4_Yes\": 0.12\n\
  \  },\n  \"paper\": {\n    \"dimensions\": {\n      \"height\": 1055,\n      \"\
  width\": 980,\n      \"x\": 150,\n      \"y\": 50\n    }\n  }\n}"
