fromversion: 3.6.0
id: exporttocsv_script_test
inputs: []
name: ExportToCSV script test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 544a3480-e5ce-4e9f-8eb9-28c3a5a152e1
      iscommand: false
      name: ''
      version: -1
    taskid: 544a3480-e5ce-4e9f-8eb9-28c3a5a152e1
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      csvArray:
        simple: '"rick",67,123'
      fileName:
        simple: test
      headers:
        simple: name,age,id
    separatecontext: false
    task:
      brand: ''
      id: 0894c5bd-8eab-4dbd-8a62-99af2b864f94
      iscommand: false
      name: Test with input of simple list of values and headers
      scriptName: ExportToCSV
      type: regular
      version: -1
    taskid: 0894c5bd-8eab-4dbd-8a62-99af2b864f94
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 515\n  }\n}"
  '10':
    id: '10'
    nexttasks:
      '#none#':
      - '9'
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 2cf268d1-3db9-4b42-83e5-549f51fabfe3
      iscommand: false
      name: Test with list of JSON objects (test execution, not validation)
      type: title
      version: -1
    taskid: 2cf268d1-3db9-4b42-83e5-549f51fabfe3
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1040\n  }\n}"
  '11':
    id: '11'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: fce83a06-61af-4f54-89a9-f826d87c0045
      iscommand: false
      name: Test and validate simpe list input
      type: title
      version: -1
    taskid: fce83a06-61af-4f54-89a9-f826d87c0045
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
      maxFileSize: {}
    separatecontext: false
    task:
      brand: ''
      id: 1057d050-dfcb-40ec-8146-fc745f821603
      iscommand: false
      name: Read file content
      scriptName: ReadFile
      type: regular
      version: -1
    taskid: 1057d050-dfcb-40ec-8146-fc745f821603
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 690\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      'yes':
      - '10'
    note: false
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        simple: ${FileData}
      right:
        simple: 'name,age,id

          rick,67,123'
    separatecontext: false
    task:
      brand: ''
      id: f34e6966-69eb-4347-87a6-d04795352896
      iscommand: false
      name: 'Compare file content to expected result '
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: f34e6966-69eb-4347-87a6-d04795352896
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 865\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      id: 346f9d69-f8ca-4577-8cbf-2da032692ab0
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 346f9d69-f8ca-4577-8cbf-2da032692ab0
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '8':
    id: '8'
    note: false
    scriptarguments:
      csvArray:
        simple: '[{"name":"rick", "age":57}, {"name":"morty","age":15, "status":"single"}]'
      fileName:
        simple: test
      headers: {}
    separatecontext: false
    task:
      brand: ''
      id: a0c883ac-c6e5-4ca1-8408-7124a3b6a62d
      iscommand: false
      name: Test with list of JSON objects, missing value
      scriptName: ExportToCSV
      type: regular
      version: -1
    taskid: a0c883ac-c6e5-4ca1-8408-7124a3b6a62d
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1185\n  }\n}"
  '9':
    id: '9'
    note: false
    scriptarguments:
      csvArray:
        simple: '[{"name":"rick", "age":57}, {"name":"morty","age":15, "status":"single"}]'
      fileName:
        simple: test
      headers:
        simple: name,age
    separatecontext: false
    task:
      brand: ''
      id: 9bd0e602-01dc-4cbc-890e-6e4419d073c8
      iscommand: false
      name: Test with list of JSON objects, with headers specified
      scriptName: ExportToCSV
      type: regular
      version: -1
    taskid: 9bd0e602-01dc-4cbc-890e-6e4419d073c8
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1185\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1230,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
