id: PcapHTTPExtractor-Test
inputs: []
name: PcapHTTPExtractor-Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 3114633f-b249-4b43-8a38-c264f4404f0c
      iscommand: false
      name: ''
      version: -1
    taskid: 3114633f-b249-4b43-8a38-c264f4404f0c
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: d41de1b4-8599-4fc7-813f-a089dac694a0
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: d41de1b4-8599-4fc7-813f-a089dac694a0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://github.com/demisto/content/raw/master/TestData/TestPcapPost.pcap
      username: {}
    separatecontext: false
    task:
      brand: ''
      id: 2a2daa67-b1f4-4a61-853e-b8d9eda9a717
      iscommand: false
      name: Get Remote File
      scriptName: http
      type: regular
      version: -1
    taskid: 2a2daa67-b1f4-4a61-853e-b8d9eda9a717
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      allowedContentTypes: {}
      entryID:
        simple: ${File.EntryID}
      limit: {}
      limitData: {}
      pcapFileName: {}
      start: {}
    separatecontext: false
    task:
      brand: ''
      description: Allows to parse and extract http flows (requests & responses) from
        a pcap/pcapng file.
      id: 6529ce01-dc41-45fd-8c5c-fcacd64511d6
      iscommand: false
      name: PcapHTTPExtractor
      scriptName: PcapHTTPExtractor
      type: regular
      version: -1
    taskid: 6529ce01-dc41-45fd-8c5c-fcacd64511d6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      'yes':
      - '7'
    note: false
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        complex:
          accessor: '[1].Response.HttpDate'
          root: PcapHTTPFlows
          transformers:
          - operator: trim
      right:
        simple: 2019-01-14 11:20:42
    separatecontext: false
    task:
      brand: ''
      id: ed40037b-4aef-4c70-86fd-a075c698f446
      iscommand: false
      name: IsResultContextCorrect
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: ed40037b-4aef-4c70-86fd-a075c698f446
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 6de92bf4-0e70-4a90-8b2c-b10f64563ca6
      iscommand: false
      name: All Good
      type: title
      version: -1
    taskid: 6de92bf4-0e70-4a90-8b2c-b10f64563ca6
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": -170,\n    \"y\": 1120\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      'yes':
      - '6'
    note: false
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        complex:
          accessor: '[0].Request.ResultIndex'
          root: PcapHTTPFlows
      right:
        simple: '6'
    separatecontext: false
    task:
      brand: ''
      id: 4a757e07-a8d7-4b5e-859d-9e1331160a60
      iscommand: false
      name: IsResultContextCorrect
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: 4a757e07-a8d7-4b5e-859d-9e1331160a60
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": -50,\n    \"y\": 910\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1135,\n      \"width\": 600,\n      \"x\": -170,\n      \"y\"\
  : 50\n    }\n  }\n}"
