id: TestIsValueInArray
inputs: []
name: TestIsValueInArray
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 4e436ced-fc4d-4a67-80fe-ae0aaf602bbb
      iscommand: false
      name: ''
      version: -1
    taskid: 4e436ced-fc4d-4a67-80fe-ae0aaf602bbb
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      append: {}
      key:
        simple: myArray
      roles: {}
      value:
        simple: ${.=function(obj){return ['value1','value2','value3']}(val)}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Find all users associated with a role
      id: 2538bd73-c5f9-46a4-8d0b-6c7fe3b8f97f
      iscommand: false
      name: Create array in context
      scriptName: Set
      type: regular
      version: -1
    taskid: 2538bd73-c5f9-46a4-8d0b-6c7fe3b8f97f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      'no':
      - '13'
      'yes':
      - '12'
    note: false
    quietmode: 0
    scriptarguments:
      array: {}
      left: {}
      list:
        simple: value
      right: {}
      value:
        simple: other
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: e0cbf7ae-4722-4599-83b3-0822451a384d
      iscommand: false
      name: Check empty array
      scriptName: IsValueInArray
      type: condition
      version: -1
    taskid: e0cbf7ae-4722-4599-83b3-0822451a384d
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 1125,\n    \"y\": 1070\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: c3f8fb52-a64b-49d2-8389-1aedde4c2ab2
      iscommand: false
      name: Bad...
      type: regular
      version: -1
    taskid: c3f8fb52-a64b-49d2-8389-1aedde4c2ab2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 1245\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      'no':
      - '15'
      'yes':
      - '14'
    note: false
    quietmode: 0
    scriptarguments:
      array:
        simple: ${myArray}
      left: {}
      list:
        simple: value
      right: {}
      value: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 18fb0ed0-515f-4f01-838a-4f32139fdab8
      iscommand: false
      name: Check empty value
      scriptName: IsValueInArray
      type: condition
      version: -1
    taskid: 18fb0ed0-515f-4f01-838a-4f32139fdab8
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 1245\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 3ac8f0d5-c5ea-4b2f-80f1-2612c0623ecb
      iscommand: false
      name: Bad...
      type: regular
      version: -1
    taskid: 3ac8f0d5-c5ea-4b2f-80f1-2612c0623ecb
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1125,\n    \"y\": 1420\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: fa9ce7d1-e32e-43fe-8408-cdbea31246b6
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: fa9ce7d1-e32e-43fe-8408-cdbea31246b6
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 1555,\n    \"y\": 1435\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      'no':
      - '3'
      'yes':
      - '4'
    note: false
    quietmode: 0
    scriptarguments:
      array:
        simple: ${myArray}
      left: {}
      list:
        simple: ${myList}
      right: {}
      value:
        simple: value2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Look for value in a list
      id: e9061539-cf17-4165-8e03-446500f82b3b
      iscommand: false
      name: Check existing value
      scriptName: IsValueInArray
      type: condition
      version: -1
    taskid: e9061539-cf17-4165-8e03-446500f82b3b
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 99b95b38-f5cc-498c-8362-a81988d1dbbe
      iscommand: false
      name: Bad...
      type: regular
      version: -1
    taskid: 99b95b38-f5cc-498c-8362-a81988d1dbbe
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      'no':
      - '6'
      'yes':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      array:
        simple: ${myArray}
      left: {}
      list:
        simple: ${myList}
      right: {}
      value:
        simple: value5
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 597cbd6c-650c-4501-8902-44a302bc3a40
      iscommand: false
      name: Check a non exist value
      scriptName: IsValueInArray
      type: condition
      version: -1
    taskid: 597cbd6c-650c-4501-8902-44a302bc3a40
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: d4224065-aa6c-4d9f-8eb6-6ffd93062e7e
      iscommand: false
      name: Bad...
      type: regular
      version: -1
    taskid: d4224065-aa6c-4d9f-8eb6-6ffd93062e7e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 720\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      'no':
      - '7'
      'yes':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      array:
        simple: value
      left: {}
      list:
        simple: value
      right: {}
      value:
        simple: value
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 6d43579b-fc97-4d73-8d22-851f22fba381
      iscommand: false
      name: 'Check two equal strings '
      scriptName: IsValueInArray
      type: condition
      version: -1
    taskid: 6d43579b-fc97-4d73-8d22-851f22fba381
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 720\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: fc6d9efa-2327-421f-855b-311d3f92f98c
      iscommand: false
      name: Bad...
      type: regular
      version: -1
    taskid: fc6d9efa-2327-421f-855b-311d3f92f98c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 895\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      'no':
      - '11'
      'yes':
      - '9'
    note: false
    quietmode: 0
    scriptarguments:
      array:
        simple: value
      left: {}
      list:
        simple: value
      right: {}
      value:
        simple: other
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 59ee38a0-9df8-4d7f-8bd0-13b14d904f61
      iscommand: false
      name: 'Check two non equal strings '
      scriptName: IsValueInArray
      type: condition
      version: -1
    taskid: 59ee38a0-9df8-4d7f-8bd0-13b14d904f61
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 895\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: d0a415ea-7754-4934-8a5d-3c24a878abaa
      iscommand: false
      name: Bad...
      type: regular
      version: -1
    taskid: d0a415ea-7754-4934-8a5d-3c24a878abaa
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 1070\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1465,\n      \"width\": 1885,\n      \"x\": 50,\n      \"y\":\
  \ 50\n    }\n  }\n}"
