id: CutTransformerTest
inputs: []
name: CutTransformerTest
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '2'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: ea5bda23-7e66-4ebe-89e9-ab9ac3daf99b
      iscommand: false
      name: ''
      version: -1
    taskid: ea5bda23-7e66-4ebe-89e9-ab9ac3daf99b
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: CutTest
                transformers:
                - args:
                    delimiter:
                      value:
                        simple: '-'
                    fields:
                      value:
                        simple: 1,2
                  operator: Cut
          operator: isEqualString
          right:
            value:
              simple: A-B
      label: 'yes'
    id: '1'
    nexttasks:
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: b4b6b31f-2cd4-4caf-8aa2-ea26868b200f
      iscommand: false
      name: Test Cut Result
      type: condition
      version: -1
    taskid: b4b6b31f-2cd4-4caf-8aa2-ea26868b200f
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 610\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: b6b23074-d47f-43ec-85df-d8628fc0d7a5
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: b6b23074-d47f-43ec-85df-d8628fc0d7a5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 200\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      append: {}
      key:
        simple: CutTest
      value:
        simple: A-B-C-D-E
    separatecontext: false
    task:
      brand: ''
      id: ee67f522-cd20-473e-825a-d15e393242f2
      iscommand: false
      name: Set String To Context
      scriptName: Set
      type: regular
      version: -1
    taskid: ee67f522-cd20-473e-825a-d15e393242f2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 390\n  }\n}"
  '4':
    id: '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 5dca4c3a-fc4e-4f92-8d4a-cae0f91789e4
      iscommand: false
      name: Cut Transformer Worked Successfuly
      type: title
      version: -1
    taskid: 5dca4c3a-fc4e-4f92-8d4a-cae0f91789e4
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 240,\n    \"y\": 890\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 905,\n      \"width\": 590,\n      \"x\": 240,\n      \"y\": 50\n\
  \    }\n  }\n}"
