id: CopyContextToFieldTest
inputs: []
name: CopyContextToFieldTest
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: e94df9b6-f714-4ece-83cc-f1c39654a276
      iscommand: false
      name: ''
      version: -1
    taskid: e94df9b6-f714-4ece-83cc-f1c39654a276
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      append: {}
      key:
        simple: testKey
      value:
        simple: Some test
    separatecontext: false
    task:
      brand: ''
      id: 1877675a-9e37-4572-8021-4216e1cc4abe
      iscommand: false
      name: Set context key
      scriptName: Set
      type: regular
      version: -1
    taskid: 1877675a-9e37-4572-8021-4216e1cc4abe
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 355\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      incidentsQuery:
        simple: id:${incident.id}
      limit: {}
      sourceContextKey:
        simple: testKey
      targetIncidentField:
        simple: name
    separatecontext: false
    task:
      brand: ''
      id: b47611c8-4b04-4f3d-8fc0-4898cd4d48d8
      iscommand: false
      name: 'Copy '
      scriptName: CopyContextToField
      type: regular
      version: -1
    taskid: b47611c8-4b04-4f3d-8fc0-4898cd4d48d8
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 750\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: incident.name
          operator: isEqualString
          right:
            value:
              simple: Some test
      label: 'yes'
    id: '3'
    nexttasks:
      '#default#':
      - '5'
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 18e4a27f-cdb8-469a-8ed6-4eca3c1be3e2
      iscommand: false
      name: Check incident name
      type: condition
      version: -1
    taskid: 18e4a27f-cdb8-469a-8ed6-4eca3c1be3e2
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 925\n  }\n}"
  '4':
    id: '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 0f800087-c005-4435-8a16-0a1d6238e230
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 0f800087-c005-4435-8a16-0a1d6238e230
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1115\n  }\n}"
  '5':
    id: '5'
    note: false
    scriptarguments:
      message:
        simple: Incident name different then expected
    separatecontext: false
    task:
      brand: ''
      id: 229b73da-83c7-4d28-8de5-a1e4ec0114e0
      iscommand: false
      name: Error
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 229b73da-83c7-4d28-8de5-a1e4ec0114e0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1100\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: 7824f0a1-e985-4fed-8741-8e96556efc3e
      iscommand: false
      name: Delete context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 7824f0a1-e985-4fed-8741-8e96556efc3e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 190\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      seconds:
        simple: '3'
    separatecontext: false
    task:
      brand: ''
      id: d02366c4-46e5-4e01-81c7-87c085e6978b
      iscommand: false
      name: Sleep
      scriptName: Sleep
      type: regular
      version: -1
    taskid: d02366c4-46e5-4e01-81c7-87c085e6978b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 550\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1145,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
