id: TestShowScheduledEntries
inputs: []
name: TestShowScheduledEntries
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d6ecfc1b-b9e3-4cb1-8d28-7777ade7206c
      iscommand: false
      name: ''
      version: -1
    taskid: d6ecfc1b-b9e3-4cb1-8d28-7777ade7206c
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      command:
        simple: '!Print value="Hello World"'
      cron:
        simple: '* * * * *'
      endDate: {}
      times:
        simple: '2'
    separatecontext: false
    task:
      brand: ''
      id: 0c6de3c7-fe6e-40ee-8cfd-e52733eb59bf
      iscommand: false
      name: Schedule Print
      scriptName: ScheduleCommand
      type: regular
      version: -1
    taskid: 0c6de3c7-fe6e-40ee-8cfd-e52733eb59bf
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      incidentId: {}
    separatecontext: false
    task:
      brand: ''
      id: 1bfff7ee-4bd0-4987-88dc-b4971da5d8ac
      iscommand: false
      name: ShowScheduledEntries
      scriptName: ShowScheduledEntries
      type: regular
      version: -1
    taskid: 1bfff7ee-4bd0-4987-88dc-b4971da5d8ac
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: f6a3f593-9f68-4323-8f22-f9a7a4cfcbd2
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: f6a3f593-9f68-4323-8f22-f9a7a4cfcbd2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '4':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ScheduledEntries.id
          operator: isExists
      label: 'yes'
    id: '4'
    nexttasks:
      'yes':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: a8523d5a-9359-4deb-8dd0-5dd64528f109
      iscommand: false
      name: Found Scheduled Tasks
      type: condition
      version: -1
    taskid: a8523d5a-9359-4deb-8dd0-5dd64528f109
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: b1071922-80ce-41cf-80e1-0707bbdb2660
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: b1071922-80ce-41cf-80e1-0707bbdb2660
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      seconds:
        simple: '120'
    separatecontext: false
    task:
      brand: ''
      id: 523628ef-7fa9-42d8-816f-800c3a672287
      iscommand: false
      name: Sleep
      scriptName: Sleep
      type: regular
      version: -1
    taskid: 523628ef-7fa9-42d8-816f-800c3a672287
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '7':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ScheduledEntries.id
          operator: isNotExists
      label: 'yes'
    id: '7'
    nexttasks:
      'yes':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: a3f7ebef-9909-432d-80d1-d976574067c2
      iscommand: false
      name: Found No Scheduled Tasks
      type: condition
      version: -1
    taskid: a3f7ebef-9909-432d-80d1-d976574067c2
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '8':
    id: '8'
    note: false
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      dataclassification: {}
      id: {}
      location: {}
      priority: {}
      reviewcomment: {}
      reviewedby: {}
      rsshandoverfeed: {}
    separatecontext: false
    task:
      brand: Builtin
      id: 231156b1-84bc-4948-88a6-6794bd2d72c1
      iscommand: true
      name: Close
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 231156b1-84bc-4948-88a6-6794bd2d72c1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
  '9':
    id: '9'
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      incidentId: {}
    separatecontext: false
    task:
      brand: ''
      id: 959ec6ab-c367-4d7f-8078-608d8da1855b
      iscommand: false
      name: ShowScheduled
      scriptName: ShowScheduledEntries
      type: regular
      version: -1
    taskid: 959ec6ab-c367-4d7f-8078-608d8da1855b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1640,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
