id: GeneratePassword-Test
inputs: []
name: GeneratePassword-Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 7fae88f2-fca0-42c1-8450-917923803fa4
      iscommand: false
      name: ''
      version: -1
    taskid: 7fae88f2-fca0-42c1-8450-917923803fa4
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      debug: {}
      max_digits: {}
      max_lcase: {}
      max_symbols: {}
      max_ucase: {}
      min_digits: {}
      min_lcase: {}
      min_symbols: {}
      min_ucase: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Default Args
      id: 3a0f65e4-7c9b-4f3b-8716-685511cbaab0
      iscommand: false
      name: Generate Password
      scriptName: GeneratePassword
      type: regular
      version: -1
    taskid: 3a0f65e4-7c9b-4f3b-8716-685511cbaab0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      'yes':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      expectedValue: {}
      fields: {}
      path: {}
      value:
        simple: ${NEW_PASSWORD}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 7d20646f-db66-4ee6-808f-8a2512d6055d
      iscommand: false
      name: Does New Password Exists in Context
      scriptName: Exists
      type: condition
      version: -1
    taskid: 7d20646f-db66-4ee6-808f-8a2512d6055d
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: 'Success! '
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: b2f6fd58-0c55-4927-8676-d13226a6163f
      iscommand: false
      name: Print if New Password
      scriptName: Print
      type: regular
      version: -1
    taskid: b2f6fd58-0c55-4927-8676-d13226a6163f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: bec01d97-ec99-4130-8ae4-6cee178bbdaa
      iscommand: false
      name: Delete All Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: bec01d97-ec99-4130-8ae4-6cee178bbdaa
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 765,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
