id: TestFileCreateAndUpload
inputs: []
name: TestFileCreateAndUpload
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 2efc1a8b-2917-44b1-859f-3ef25c5305ce
      iscommand: false
      name: ''
      version: -1
    taskid: 2efc1a8b-2917-44b1-859f-3ef25c5305ce
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Something
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 4cb52547-2af7-4f02-837d-58436097f902
      iscommand: false
      name: Print Something
      scriptName: Print
      type: regular
      version: -1
    taskid: 4cb52547-2af7-4f02-837d-58436097f902
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quietmode: 0
    scriptarguments:
      data: {}
      entryId:
        simple: ${lastCompletedTaskEntries}
      filename:
        simple: testPlaybookForFileCreateAndUpload-FileFromEntry.txt
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 1fd08984-45a8-42d5-888d-2a38e8cd3cc4
      iscommand: false
      name: FileCreateAndUpload from entry
      scriptName: FileCreateAndUpload
      type: regular
      version: -1
    taskid: 1fd08984-45a8-42d5-888d-2a38e8cd3cc4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 03d8983e-0bd4-4b0b-8c7f-440ae938f931
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 03d8983e-0bd4-4b0b-8c7f-440ae938f931
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${File.Name(val=="testPlaybookForFileCreateAndUpload-FileFromEntry.txt")}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: d7a2f2fa-449d-43a3-8798-5ec3bce0091b
      iscommand: false
      name: Verify we got the right filename
      scriptName: Print
      type: regular
      version: -1
    taskid: d7a2f2fa-449d-43a3-8798-5ec3bce0091b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 714\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      data:
        simple: This is data to be stored
      entryId: {}
      filename:
        simple: testPlaybookForFileCreateAndUpload-FileFromData.txt
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 203d25ec-a22d-4d4b-898a-ba40c52b6887
      iscommand: false
      name: FileCreateAndUpload from data
      scriptName: FileCreateAndUpload
      type: regular
      version: -1
    taskid: 203d25ec-a22d-4d4b-898a-ba40c52b6887
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 906\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${File.Name(val=="testPlaybookForFileCreateAndUpload-FileFromData.txt")}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: df2a2365-b1c6-4171-84ae-a0c579a88f7a
      iscommand: false
      name: Verify we got the right filename
      scriptName: Print
      type: regular
      version: -1
    taskid: df2a2365-b1c6-4171-84ae-a0c579a88f7a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1105\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1150,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
