contentitemfields:
  propagationLabels: []
description: Test ZipFile and UnzipFile scripts
id: ZipFile-Test
inputs:
- description: ''
  key: password
  required: false
  value:
    simple: '123'
name: ZipFile-Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: e2bbb5f1-44a1-4dc8-8024-622eabcbf93c
      iscommand: false
      name: ''
      version: -1
    taskid: e2bbb5f1-44a1-4dc8-8024-622eabcbf93c
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 65\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '32'
    note: false
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure:
        simple: 'true'
      url:
        simple: https://github.com/demisto/content/raw/master/TestData/test_image.png
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: Sends http request. Returns the response as json.
      id: f18e90fa-325e-4af2-8527-1f39747f389e
      iscommand: false
      name: http
      scriptName: http
      type: regular
      version: -1
    taskid: f18e90fa-325e-4af2-8527-1f39747f389e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 400\n  }\n}"
  '20':
    id: '20'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '30'
    note: false
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure:
        simple: 'true'
      url:
        simple: https://github.com/demisto/content/raw/master/TestData/test_image.png
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: Sends http request. Returns the response as json.
      id: 107be8df-0151-468d-8df7-17d4ce287ea4
      iscommand: false
      name: http
      scriptName: http
      type: regular
      version: -1
    taskid: 107be8df-0151-468d-8df7-17d4ce287ea4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
  '22':
    id: '22'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '23'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: fc4c13cc-e417-4261-89d1-79542e70c4bc
      iscommand: false
      name: Unzip password protected file
      type: title
      version: -1
    taskid: fc4c13cc-e417-4261-89d1-79542e70c4bc
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1275\n  }\n}"
  '23':
    id: '23'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '20'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: c95b9fa5-4a88-4152-8ca5-bf0ba4cc2102
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: c95b9fa5-4a88-4152-8ca5-bf0ba4cc2102
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '25':
    continueonerror: true
    id: '25'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '26'
    note: false
    scriptarguments:
      entryID:
        complex:
          accessor: EntryID
          filters:
          - - left:
                iscontext: true
                value:
                  simple: File.Name
              operator: isEqualString
              right:
                iscontext: true
                value:
                  simple: ZippedFiles
          root: File
      fileName: {}
      lastZipFileInWarroom: {}
      password:
        simple: '{ENCRYPTED}4zr//RCcj2770fwhrAp0LpQP+bGidss1PrsLBhH3kPVp6KvOMce2wfac4R++Nau4fBGTsSpxaCJH8Fogh7Om3g=='
    separatecontext: false
    task:
      brand: ''
      description: Unzip a file using fileName or entryID to specify a file. Unzipped
        files will be loaded to the War Room and names will be put into the context.
      id: ea0120b6-1fb8-4a3e-852a-c1a7919430c4
      iscommand: false
      name: Unzip with wrong password
      scriptName: UnzipFile
      type: regular
      version: -1
    taskid: ea0120b6-1fb8-4a3e-852a-c1a7919430c4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1945\n  }\n}"
  '26':
    id: '26'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '27'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 78c778de-cfa9-420f-8454-89a2143a5f35
      iscommand: false
      name: Check for error
      scriptName: ValidateErrorExistence
      type: regular
      version: -1
    taskid: 78c778de-cfa9-420f-8454-89a2143a5f35
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2120\n  }\n}"
  '27':
    id: '27'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: ae13ab7b-044d-4721-8e7c-7b687b788632
      iscommand: false
      name: Done testing
      type: title
      version: -1
    taskid: ae13ab7b-044d-4721-8e7c-7b687b788632
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2295\n  }\n}"
  '28':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: ExtractedFiles
                    operator: isExists
                root: ExtractedFiles
          operator: isExists
      label: 'yes'
    id: '28'
    ignoreworker: false
    nexttasks:
      'yes':
      - '22'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 935c492a-7ece-4999-8012-58ffc99ab42f
      iscommand: false
      name: Validated unzipped files exists
      type: condition
      version: -1
    taskid: 935c492a-7ece-4999-8012-58ffc99ab42f
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1100\n  }\n}"
  '29':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ZippedFiles
          operator: isExists
      label: 'yes'
    id: '29'
    ignoreworker: false
    nexttasks:
      'yes':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 84785497-edbe-4829-83af-a334659c82be
      iscommand: false
      name: Validated zipped file exists
      type: condition
      version: -1
    taskid: 84785497-edbe-4829-83af-a334659c82be
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 750\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '28'
    note: false
    scriptarguments:
      entryID:
        complex:
          accessor: EntryID
          filters:
          - - left:
                iscontext: true
                value:
                  simple: File.Name
              operator: isEqualString
              right:
                iscontext: true
                value:
                  simple: ZippedFiles
          root: File
      fileName: {}
      lastZipFileInWarroom: {}
      password:
        complex:
          root: inputs.password
    separatecontext: false
    task:
      brand: ''
      description: Unzip a file using fileName or entryID to specify a file. Files
        unzipped will be pushed to the war room and names will be pushed to the context.
      id: 32eec206-f850-4c54-8f49-463fa1f509ca
      iscommand: false
      name: UnzipFile
      scriptName: UnzipFile
      type: regular
      version: -1
    taskid: 32eec206-f850-4c54-8f49-463fa1f509ca
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 925\n  }\n}"
  '30':
    id: '30'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '25'
    note: false
    scriptarguments:
      entryID:
        complex:
          accessor: EntryID
          root: File
      password:
        complex:
          root: inputs.password
      zipName: {}
    separatecontext: false
    task:
      brand: ''
      description: Zip a file and upload to war room
      id: 49eddc5a-3ab7-4b85-84fd-b3d6e047f036
      iscommand: false
      name: Zip with password
      scriptName: ZipFile
      type: regular
      version: -1
    taskid: 49eddc5a-3ab7-4b85-84fd-b3d6e047f036
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '32':
    id: '32'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '29'
    note: false
    scriptarguments:
      entryID:
        complex:
          accessor: EntryID
          root: File
      password:
        complex:
          root: inputs.password
      zipName: {}
    separatecontext: false
    task:
      brand: ''
      description: Zip a file and upload to war room
      id: 3b36bb83-a4ce-49d8-8147-308fc26e2b83
      iscommand: false
      name: ZipFile
      scriptName: ZipFile
      type: regular
      version: -1
    taskid: 3b36bb83-a4ce-49d8-8147-308fc26e2b83
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 575\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 716a17e5-d806-4a55-859a-887093bfdc5c
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 716a17e5-d806-4a55-859a-887093bfdc5c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 225\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2295,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 65\n\
  \    }\n  }\n}"
