description: Testing LanguageDetect script
id: LanguageDetect-Test
inputs: []
name: LanguageDetect-Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: e878dc76-2922-4edf-8632-5ec19d61d958
      iscommand: false
      name: ''
      version: -1
    taskid: e878dc76-2922-4edf-8632-5ec19d61d958
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    continueonerror: true
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quietmode: 0
    scriptarguments:
      text:
        simple: Hello World
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: b1e5a6ec-5705-49c8-821d-4c0f70b97ff2
      iscommand: false
      name: Detect english
      scriptName: LanguageDetect
      type: regular
      version: -1
    taskid: b1e5a6ec-5705-49c8-821d-4c0f70b97ff2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      'yes':
      - '7'
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${langDetect(val.lang=='en')}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: d1b82982-f1be-4a16-8bda-f0784412919f
      iscommand: false
      name: Check if we found English
      scriptName: Exists
      type: condition
      version: -1
    taskid: d1b82982-f1be-4a16-8bda-f0784412919f
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: '60'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 44254d3c-7011-42cb-86af-3909f36bcb79
      iscommand: false
      name: Sleep for 3 minutes
      scriptName: Sleep
      type: regular
      version: -1
    taskid: 44254d3c-7011-42cb-86af-3909f36bcb79
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      text:
        simple: Hello World
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 6a34c6b7-766f-4ba3-8f9e-2a822e1d058e
      iscommand: false
      name: Detect english once again
      scriptName: LanguageDetect
      type: regular
      version: -1
    taskid: 6a34c6b7-766f-4ba3-8f9e-2a822e1d058e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 2e87b599-df38-43f6-8399-b6f56b255d84
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 2e87b599-df38-43f6-8399-b6f56b255d84
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: df91e379-e7f9-4b05-849f-ab16dd6de22f
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: df91e379-e7f9-4b05-849f-ab16dd6de22f
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1085,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
