id: ExposeIncidentOwner-Test
inputs: []
name: ExposeIncidentOwner-Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: a17a72b9-a3eb-4c4d-8e75-2ebbc74f45cf
      iscommand: false
      name: ''
      version: -1
    taskid: a17a72b9-a3eb-4c4d-8e75-2ebbc74f45cf
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      assignBy: {}
      email: {}
      roles: {}
      username: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: 'Assign analyst to incident.

        By default,  the analyst is picked randomly from the available users, according
        to the provided roles (if no roles provided, will fetch all users).

        Otherwise, the analyst will be picked according to the ''assignBy'' arguments.

        machine-learning: DBot will calculated and decide who is the best analyst
        for the job.

        top-user: The user that is most commonly owns this type of incident

        less-busy-user: The less busy analyst will be picked to be the incident owner.

        online: The analyst is picked randomly from all online analysts, according
        to the provided roles (if no roles provided, will fetch all users).'
      id: 1a7e58fa-99c5-4b17-876c-84efa847a839
      iscommand: false
      name: AssignAnalystToIncident
      scriptName: AssignAnalystToIncident
      type: regular
      version: -1
    taskid: 1a7e58fa-99c5-4b17-876c-84efa847a839
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    results:
    - IncidentOwner
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Expose the incident owner into IncidentOwner context key
      id: ae667d80-b514-4825-8759-c6464fe0915a
      iscommand: false
      name: ExposeIncidentOwner
      scriptName: ExposeIncidentOwner
      type: regular
      version: -1
    taskid: ae667d80-b514-4825-8759-c6464fe0915a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      'no':
      - '5'
      'yes':
      - '6'
    note: false
    quietmode: 0
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        simple: ${incident.owner}
      right:
        simple: ${IncidentOwner.username}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Check whether the values provided in arguments are equal.
      id: ec1f5155-a8a8-483f-86f6-2f1c2eacbc0a
      iscommand: false
      name: AreValuesEqual
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: ec1f5155-a8a8-483f-86f6-2f1c2eacbc0a
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 545\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 41d47758-7788-424d-84d0-40139b75f475
      iscommand: false
      name: Error
      type: regular
      version: -1
    taskid: 41d47758-7788-424d-84d0-40139b75f475
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 45b57291-8cfe-4ad2-8b1d-ab6e2740dbd1
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 45b57291-8cfe-4ad2-8b1d-ab6e2740dbd1
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 735\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 765,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
