description: Creates a test docx word file, parses it and runs various IOC extraction
  tasks.
id: TestWordFileToIOC
inputs: []
name: TestWordFileToIOC
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '4'
    separatecontext: false
    task:
      brand: ''
      id: 5652fc24-bb4f-42d9-8132-1ab0983f12b2
      iscommand: false
      name: ''
      version: -1
    taskid: 5652fc24-bb4f-42d9-8132-1ab0983f12b2
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 65\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '6'
    scriptarguments:
      name:
        simple: test.docx
      text:
        simple: 'These are some IP''s: 127.0.0.1, 127.0.0.8, Awesome!'
    separatecontext: false
    task:
      brand: ''
      description: Downloads a test file to parse
      id: e5dc1e98-c3e4-4acb-8974-4067b5e9b137
      iscommand: false
      name: CreateWordTestFile
      scriptName: TestCreateWordFile
      type: regular
      version: -1
    taskid: e5dc1e98-c3e4-4acb-8974-4067b5e9b137
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 227\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '8'
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
    separatecontext: false
    task:
      brand: ''
      description: Parses word files to text file
      id: 00dec68f-5b6c-44cd-8bc5-b6502b2748f1
      iscommand: false
      name: RunParseWordDoc
      scriptName: ParseWordDoc
      type: regular
      version: -1
    taskid: 00dec68f-5b6c-44cd-8bc5-b6502b2748f1
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 400\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '9'
    scriptarguments:
      extend-context: {}
      report: {}
      text:
        simple: ${FileData}
      url: {}
      urlRegex: {}
    separatecontext: false
    task:
      brand: ''
      id: 86be2b34-acf0-4bc6-8d81-2c88dac06509
      iscommand: false
      name: ExtractIPsFromFile
      scriptName: ExtractIP
      type: regular
      version: -1
    taskid: 86be2b34-acf0-4bc6-8d81-2c88dac06509
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 750\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '7'
    scriptarguments:
      action: {}
      contextKey: {}
      data: {}
      destpath: {}
      enforce_timeout: {}
      entry: {}
      entryID:
        simple: ${File.[1].EntryID}
      entryId: {}
      entryid: {}
      file: {}
      fileNames: {}
      filename: {}
      hostname: {}
      ip: {}
      issueId: {}
      machine: {}
      maxFileSize: {}
      max_file_size: {}
      memory: {}
      options: {}
      package: {}
      path: {}
      paths: {}
      pathtype: {}
      platform: {}
      profiles: {}
      system: {}
      tags: {}
      timeout: {}
      upload: {}
      verbose: {}
    separatecontext: false
    task:
      brand: ''
      id: 4ce81084-a5fa-4305-8934-3a1ad156058f
      iscommand: false
      name: ReadFileContentsToContext
      scriptName: ReadFile
      type: regular
      version: -1
    taskid: 4ce81084-a5fa-4305-8934-3a1ad156058f
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 575\n  }\n}"
  '9':
    id: '9'
    scriptarguments:
      expectedValue:
        simple: '["127.0.0.1", "127.0.0.8"]'
      extend-context: {}
      field1: {}
      field2: {}
      field3: {}
      field4: {}
      fields: {}
      path:
        simple: IP.Address
      value:
        simple: ${IP.Address}
      value1: {}
      value2: {}
      value3: {}
      value4: {}
    task:
      brand: ''
      id: 4a14ebb6-92e0-4adc-856a-a907d134639e
      iscommand: false
      name: CheckExtractedIPsExistInContext
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 4a14ebb6-92e0-4adc-856a-a907d134639e
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 925\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 955,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 65\n\
  \    }\n  }\n}"
