id: ParseExcel-test
inputs: []
name: ParseExcel-test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '2'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 3e604ad0-7f4c-45ac-8427-1ea8a71b3c3f
      iscommand: false
      name: ''
      version: -1
    taskid: 3e604ad0-7f4c-45ac-8427-1ea8a71b3c3f
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      body: {}
      filename:
        simple: test_file.xlsx
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: http://go.microsoft.com/fwlink/?LinkID=521962
      username: {}
    separatecontext: false
    task:
      brand: ''
      id: f130d0a4-6ebd-4b7b-8670-b5b600b5b680
      iscommand: false
      name: Downlaod xlsx file
      scriptName: http
      type: regular
      version: -1
    taskid: f130d0a4-6ebd-4b7b-8670-b5b600b5b680
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: 4f7429ed-121a-40c3-8da1-efc2cd8797f8
      iscommand: false
      name: DeleteContex
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 4f7429ed-121a-40c3-8da1-efc2cd8797f8
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      entryId:
        complex:
          accessor: EntryID
          root: File
    separatecontext: false
    task:
      brand: ''
      id: 5983e276-fed7-45ed-8dc4-3efa28ba7109
      iscommand: false
      name: ParseExcel
      scriptName: ParseExcel
      type: regular
      version: -1
    taskid: 5983e276-fed7-45ed-8dc4-3efa28ba7109
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: ParseExcel
          operator: isExists
      label: 'yes'
    id: '4'
    nexttasks:
      'yes':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 4d1b0ced-306f-45ca-8740-691d90da84c8
      iscommand: false
      name: Check context
      type: condition
      version: -1
    taskid: 4d1b0ced-306f-45ca-8740-691d90da84c8
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 0627f573-6fb3-4d46-81f6-1e76ccc3fb0e
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 0627f573-6fb3-4d46-81f6-1e76ccc3fb0e
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 910,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
