contentitemfields:
  propagationLabels: []
id: RandomStringGenerateTest
inputs: []
name: RandomStringGenerateTest
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: c52944e6-e59d-4aa0-89e1-d5288aedb945
      iscommand: false
      name: ''
      version: -1
    taskid: c52944e6-e59d-4aa0-89e1-d5288aedb945
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      Digits:
        simple: 'True'
      Length:
        simple: '10'
      Lowercase:
        simple: 'True'
      Punctuation:
        simple: 'True'
      Uppercase:
        simple: 'True'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 6666dfd1-07dd-403c-81ee-1cdf9ae9d0b1
      iscommand: false
      name: Generate String
      scriptName: GenerateRandomString
      type: regular
      version: -1
    taskid: 6666dfd1-07dd-403c-81ee-1cdf9ae9d0b1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    note: false
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 096efc65-ed82-4373-83b5-fbd7ac295494
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 096efc65-ed82-4373-83b5-fbd7ac295494
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '4':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: RandomString
          operator: isExists
      label: 'yes'
    id: '4'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '5'
      'yes':
      - '3'
    note: false
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 50b94bc2-aa8b-4a29-836a-6de8693c2f0f
      iscommand: false
      name: Verify generated string
      type: condition
      version: -1
    taskid: 50b94bc2-aa8b-4a29-836a-6de8693c2f0f
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      message:
        simple: Could not find entry 'RandomString'.
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: c6d59023-44ae-4ef8-8baf-7c5c284980a1
      iscommand: false
      name: Print error
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: c6d59023-44ae-4ef8-8baf-7c5c284980a1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 720\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: 6a47cb1f-6874-4033-8a07-77baae267b05
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 6a47cb1f-6874-4033-8a07-77baae267b05
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 910,\n      \"width\": 492.5,\n      \"x\": 50,\n      \"y\":\
  \ 50\n    }\n  }\n}"
