description: ''
fromversion: 3.5.0
id: decodemimeheader_-_test
inputs: []
name: DecodeMimeHeader - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '3'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 5c788354-cf3d-40f5-88a7-7c98a06a40e2
      iscommand: false
      name: ''
      version: -1
    taskid: 5c788354-cf3d-40f5-88a7-7c98a06a40e2
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      value:
        simple: 'Subject: =?ISO-8859-1?B?SWYgeW91IGNhbiByZWFkIHRoaXMgeW8=?='
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: efd621c2-6025-4fb9-816a-d7c1ad5717b3
      iscommand: false
      name: Decode mime header
      scriptName: DecodeMimeHeader
      type: regular
      version: -1
    taskid: efd621c2-6025-4fb9-816a-d7c1ad5717b3
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    scriptarguments:
      expectedValue:
        simple: Subject:If you can read this yo
      fields: {}
      path:
        simple: DecodedMimeHeader
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 981ac8cf-747a-45a0-8e52-c6509bb4c631
      iscommand: false
      name: Verify
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 981ac8cf-747a-45a0-8e52-c6509bb4c631
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '1'
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: ee790d8b-6ecd-4f3e-8141-b40101945fb4
      iscommand: false
      name: Delete context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: ee790d8b-6ecd-4f3e-8141-b40101945fb4
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 590,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
