id: Test_HTMLtoMD
inputs: []
name: Test_HTMLtoMD
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 980c0a0b-2112-44bf-8ef9-636f28d3a293
      iscommand: false
      name: ''
      version: -1
    taskid: 980c0a0b-2112-44bf-8ef9-636f28d3a293
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      html:
        simple: <a href="http://demisto.com">Demisto</a>
    separatecontext: false
    task:
      brand: ''
      id: 72e78c42-3525-481f-8337-5a83de3d70da
      iscommand: false
      name: HTMLtoMD
      scriptName: HTMLtoMD
      type: regular
      version: -1
    taskid: 72e78c42-3525-481f-8337-5a83de3d70da
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 230\n  }\n}"
  '2':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: HTMLtoMD.Result
          operator: isEqualString
          right:
            value:
              simple: '[Demisto](http://demisto.com)'
      label: 'yes'
    id: '2'
    ignoreworker: false
    nexttasks:
      'yes':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 60e5751f-ee8b-43de-84ad-8bdb113cb5a4
      iscommand: false
      name: Check Results
      type: condition
      version: -1
    taskid: 60e5751f-ee8b-43de-84ad-8bdb113cb5a4
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 390\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    note: false
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 5431d576-f533-4429-8340-206e22384d20
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 5431d576-f533-4429-8340-206e22384d20
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 610\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 655,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\": 50\n\
  \    }\n  }\n}"
