description: 'Testing output of URLDecode '
id: URLDecode-Test
inputs: []
name: URLDecode-Test
outputs: []
rolename: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 51f3c5c4-68fb-4e22-8827-71fe3e73108c
      iscommand: false
      name: ''
      version: -1
    taskid: 51f3c5c4-68fb-4e22-8827-71fe3e73108c
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      value:
        simple: https:%2F%2Fexample.com/%2F%2F
    separatecontext: false
    task:
      brand: ''
      description: 'Converts

        https:%2F%2Fexample.com

        into

        https://example.com'
      id: 8d170e20-df55-4302-83fa-267285681829
      iscommand: false
      name: URLDecode
      scriptName: URLDecode
      type: regular
      version: -1
    taskid: 8d170e20-df55-4302-83fa-267285681829
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '2':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: DecodedURL
          operator: isEqualString
          right:
            value:
              simple: https://example.com///
      label: 'yes'
    id: '2'
    nexttasks:
      'yes':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: b80c239c-d58a-4fda-8b99-57847c3f0875
      iscommand: false
      name: Check args
      type: condition
      version: -1
    taskid: b80c239c-d58a-4fda-8b99-57847c3f0875
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 5749107c-6584-4e5d-8f17-15fb7f7a3bed
      iscommand: false
      name: End test
      type: title
      version: -1
    taskid: 5749107c-6584-4e5d-8f17-15fb7f7a3bed
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: 63b09765-9535-4bbc-8b74-1e191a670a3a
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 63b09765-9535-4bbc-8b74-1e191a670a3a
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 735,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
