id: RSA NetWitness Test
inputs: []
name: RSA NetWitness Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 5e9fffeb-83fd-41a5-806a-fc47bb746db1
      iscommand: false
      name: ''
      version: -1
    taskid: 5e9fffeb-83fd-41a5-806a-fc47bb746db1
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      lastDays: {}
      limit:
        simple: '2'
      since:
        simple: 2018-03-15 00:00:00+00:00
      until:
        simple: 2018-03-15 23:55:00+00:00
    separatecontext: false
    task:
      brand: RSA NetWitness v11.1
      id: 5446d1b4-8eb0-478e-866d-2f73f6a94dd8
      iscommand: true
      name: Get incidents created on 15/03/18
      script: RSA NetWitness v11.1|||netwitness-get-incidents
      type: regular
      version: -1
    taskid: 5446d1b4-8eb0-478e-866d-2f73f6a94dd8
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      assignee:
        simple: deploy_admin
      incidentId:
        simple: INC-12
      status:
        simple: Assigned
    separatecontext: false
    task:
      brand: RSA NetWitness v11.1
      id: 43ea382f-f3fc-4249-8a3d-149e36390c17
      iscommand: true
      name: Update incident
      script: RSA NetWitness v11.1|||netwitness-update-incident
      type: regular
      version: -1
    taskid: 43ea382f-f3fc-4249-8a3d-149e36390c17
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
  '11':
    id: '11'
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: a02fc603-07e3-4d29-81a5-300a57f868aa
      iscommand: false
      name: Clear Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: a02fc603-07e3-4d29-81a5-300a57f868aa
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '12':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: NetWitness.Incidents.status
          operator: isEqualString
          right:
            value:
              simple: Assigned
      - - left:
            iscontext: true
            value:
              simple: NetWitness.Incidents.assignee
          operator: isEqualString
          right:
            value:
              simple: deploy_admin
      label: 'yes'
    id: '12'
    nexttasks:
      'yes':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 7c9a36aa-ef8f-4e72-8dbf-73a94c5d1f74
      iscommand: false
      name: Validate incident was updated correctly
      type: condition
      version: -1
    taskid: 7c9a36aa-ef8f-4e72-8dbf-73a94c5d1f74
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '2':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: NetWitness.Incidents
          operator: isNotEmpty
      label: 'yes'
    id: '2'
    nexttasks:
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 6b231c0a-c3eb-444f-865b-b991ce0105ee
      iscommand: false
      name: Validate results are returned
      type: condition
      version: -1
    taskid: 6b231c0a-c3eb-444f-865b-b991ce0105ee
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      incidentId:
        simple: ${NetWitness.Incidents.[0].id}
    separatecontext: false
    task:
      brand: RSA NetWitness v11.1
      id: c9d2b178-19fd-42e7-8dc1-b836f5937423
      iscommand: true
      name: Get incident
      script: RSA NetWitness v11.1|||netwitness-get-incident
      type: regular
      version: -1
    taskid: c9d2b178-19fd-42e7-8dc1-b836f5937423
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: NetWitness.Alerts
          operator: isNotEmpty
      label: 'yes'
    id: '5'
    nexttasks:
      'yes':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 8010d076-052e-4606-8088-2c4a7d8feb4a
      iscommand: false
      name: Validate results are returned
      type: condition
      version: -1
    taskid: 8010d076-052e-4606-8088-2c4a7d8feb4a
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '6':
    id: '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d2c5413c-780e-460c-837e-c82f035a07f9
      iscommand: false
      name: Test passed
      type: title
      version: -1
    taskid: d2c5413c-780e-460c-837e-c82f035a07f9
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1945\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      assignee:
        simple: admin
      incidentId:
        simple: INC-12
      status:
        simple: InProgress
    separatecontext: false
    task:
      brand: RSA NetWitness v11.1
      id: dd2dfdbf-0aba-49f7-8f02-bad257b4a1e5
      iscommand: true
      name: Update incident
      script: RSA NetWitness v11.1|||netwitness-update-incident
      type: regular
      version: -1
    taskid: dd2dfdbf-0aba-49f7-8f02-bad257b4a1e5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: f7c26229-a0a8-4f82-857c-04fa0532e5d7
      iscommand: false
      name: Clear Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: f7c26229-a0a8-4f82-857c-04fa0532e5d7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '9':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: NetWitness.Incidents.status
          operator: isEqualString
          right:
            value:
              simple: InProgress
      - - left:
            iscontext: true
            value:
              simple: NetWitness.Incidents.assignee
          operator: isEqualString
          right:
            value:
              simple: admin
      label: 'yes'
    id: '9'
    nexttasks:
      'yes':
      - '11'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 8c23b7e4-11d8-41be-8ec9-9fa71b4205a5
      iscommand: false
      name: Validate incident was updated correctly
      type: condition
      version: -1
    taskid: 8c23b7e4-11d8-41be-8ec9-9fa71b4205a5
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1960,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
