id: SMB test
inputs: []
name: SMB test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 7d00ae67-5175-4418-8e8a-d09ee6681135
      iscommand: false
      name: ''
      version: -1
    taskid: 7d00ae67-5175-4418-8e8a-d09ee6681135
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    note: false
    scriptarguments:
      download_and_attach:
        simple: 'no'
      file_path:
        simple: Shared/asd.txt
    separatecontext: false
    task:
      description: Download a file from the SMB server
      id: 1318b929-317a-4aca-8826-817a73394ccb
      iscommand: true
      name: smb-download
      script: '|||smb-download'
      type: regular
      version: -1
    taskid: 1318b929-317a-4aca-8826-817a73394ccb
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 895\n  }\n}"
  '2':
    id: '2'
    note: false
    scriptarguments:
      content:
        simple: '123'
      entryID: {}
      file_path:
        simple: Shared/zxc.txt
    separatecontext: false
    task:
      description: Upload a file to the SMB server
      id: 9a4f14b7-5df9-460b-8268-d292925c51a9
      iscommand: true
      name: smb-upload
      script: '|||smb-upload'
      type: regular
      version: -1
    taskid: 9a4f14b7-5df9-460b-8268-d292925c51a9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      content: {}
      entryID:
        simple: ${File.EntryID}
      file_path:
        simple: Shared/123.txt
    separatecontext: false
    task:
      description: Upload a file to the SMB server
      id: 5f522da4-b8a8-4a16-8658-7a28f214852b
      iscommand: true
      name: smb-upload
      script: '|||smb-upload'
      type: regular
      version: -1
    taskid: 5f522da4-b8a8-4a16-8658-7a28f214852b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    note: false
    scriptarguments:
      download_and_attach:
        simple: 'yes'
      file_path:
        simple: Shared/asd.txt
    separatecontext: false
    task:
      description: Download a file from the SMB server
      id: d86019cf-1da9-41ad-802f-c68016511089
      iscommand: true
      name: smb-download
      script: '|||smb-download'
      type: regular
      version: -1
    taskid: d86019cf-1da9-41ad-802f-c68016511089
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 895\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://github.com/demisto/content/raw/master/TestData/hebrew_file.txt
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: Sends http request. Returns the response as json.
      id: 43ed9c1d-0c1e-414a-8f54-963b2158e68e
      iscommand: false
      name: Get file
      scriptName: http
      type: regular
      version: -1
    taskid: 43ed9c1d-0c1e-414a-8f54-963b2158e68e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 2958dde9-ebbf-4021-8d57-5243e937a375
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 2958dde9-ebbf-4021-8d57-5243e937a375
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 195\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '2'
      - '1'
      - '4'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 9dc730fc-9fbc-4e10-88bb-0db7db5fc498
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 9dc730fc-9fbc-4e10-88bb-0db7db5fc498
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 720\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 940,\n      \"width\": 1240,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
