description: A test playbook for Search Endpoints By Hash - TIE
fromversion: 3.5.0
id: search_endpoints_by_hash_-_tie_-_test
inputs: []
name: Search Endpoints By Hash - TIE - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    task:
      brand: ''
      id: 066f0346-5546-4ce7-840d-52444dec212e
      iscommand: false
      name: ''
      version: -1
    taskid: 066f0346-5546-4ce7-840d-52444dec212e
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '6'
    scriptarguments:
      all:
        simple: 'yes'
      extend-context: {}
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: Clear all context
      id: b1cd7dc5-47f3-43c7-8cf8-71306f41a6a6
      iscommand: false
      name: Clear Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: b1cd7dc5-47f3-43c7-8cf8-71306f41a6a6
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '7'
    scriptarguments:
      append: {}
      key:
        simple: Hashes
      value:
        simple: '["0cc175b9c0f1b6a831c399e269772661", "7215ee9c7d9dc229d2921a40e899ec5f"]'
    separatecontext: false
    task:
      brand: ''
      description: Create dummy hashes for test purposes
      id: 69089d38-3918-451e-80c7-30ce6b4ec10f
      iscommand: false
      name: Create hashes for test
      scriptName: Set
      type: regular
      version: -1
    taskid: 69089d38-3918-451e-80c7-30ce6b4ec10f
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '7':
    id: '7'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    scriptarguments:
      Hash:
        complex:
          root: Hashes
    separatecontext: true
    task:
      brand: ''
      description: ''
      id: cabf545c-538f-4187-8424-1a4ef27c1a52
      iscommand: false
      name: Search Endpoints By Hash - TIE
      playbookId: search_endpoints_by_hash_-_tie
      playbookName: Search Endpoints By Hash - TIE
      type: playbook
      version: -1
    taskid: cabf545c-538f-4187-8424-1a4ef27c1a52
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 590,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
