id: McAfee-TIE Test
inputs: []
name: McAfee-TIE Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 48b0a26c-5ae3-46cc-86df-595550e7f6fa
      iscommand: false
      name: ''
      version: -1
    taskid: 48b0a26c-5ae3-46cc-86df-595550e7f6fa
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '10':
    id: '10'
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      file:
        simple: 5AF84A3DB5883627BFDFF909E210634E
    separatecontext: false
    task:
      brand: McAfee Threat Intelligence Exchange
      id: b134af34-476e-442f-8ced-e8c5f615cd93
      iscommand: true
      name: TIE File reputation - Malicious
      script: McAfee Threat Intelligence Exchange|||file
      type: regular
      version: -1
    taskid: b134af34-476e-442f-8ced-e8c5f615cd93
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '11':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Score
          operator: isEqualString
          right:
            value:
              simple: '3'
      label: 'yes'
    id: '11'
    nexttasks:
      'yes':
      - '12'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d63b213c-f1bc-4fe9-842f-2dc6ccbd0482
      iscommand: false
      name: Verify Context DBot Score
      type: condition
      version: -1
    taskid: d63b213c-f1bc-4fe9-842f-2dc6ccbd0482
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '12':
    id: '12'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: fe037440-31c6-4d5e-8ce3-c2a6c150ebc1
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: fe037440-31c6-4d5e-8ce3-c2a6c150ebc1
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
  '2':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: File.TrustLevel
          operator: isEqualString
          right:
            value:
              simple: '0'
      label: 'yes'
    id: '2'
    nexttasks:
      'yes':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 635c0710-f43c-4492-82cd-145dd4ec3d99
      iscommand: false
      name: Verify Context File Reputation
      type: condition
      version: -1
    taskid: 635c0710-f43c-4492-82cd-145dd4ec3d99
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Score
          operator: isEqualString
          right:
            value:
              simple: '0'
      label: 'yes'
    id: '3'
    nexttasks:
      'yes':
      - '9'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 1908d988-6de1-47c6-83eb-faff50494c67
      iscommand: false
      name: Verify Context DBot Score
      type: condition
      version: -1
    taskid: 1908d988-6de1-47c6-83eb-faff50494c67
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      file:
        simple: 6EAE26DB8C13182A7947982991B4321732CC3DE2
    separatecontext: false
    task:
      brand: McAfee Threat Intelligence Exchange
      description: Retrieves the reputations for the specified hash ( Supports MD5
        SHA1 & SHA256)
      id: 73f34142-9516-409e-8986-8fa3c122d89c
      iscommand: true
      name: TIE file reputation
      script: McAfee Threat Intelligence Exchange|||file
      type: regular
      version: -1
    taskid: 73f34142-9516-409e-8986-8fa3c122d89c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      file:
        simple: f2c7bb8acc97f92e987a2d4087d021b1
    separatecontext: false
    task:
      brand: McAfee Threat Intelligence Exchange
      id: 2fa64b7a-e29d-4e24-81ad-801d5d6ddf89
      iscommand: true
      name: tie-file-references
      script: McAfee Threat Intelligence Exchange|||tie-file-references
      type: regular
      version: -1
    taskid: 2fa64b7a-e29d-4e24-81ad-801d5d6ddf89
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      expectedValue: {}
      fields:
        simple: MD5,References
      path:
        simple: File
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: f664dbf3-e09d-4527-8c99-6e9e2d3caf64
      iscommand: false
      name: Verify Context tie-file-references
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: f664dbf3-e09d-4527-8c99-6e9e2d3caf64
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '9':
    id: '9'
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: e8998e24-05f6-4977-82dc-7c470a5c78cf
      iscommand: false
      name: Clear Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: e8998e24-05f6-4977-82dc-7c470a5c78cf
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1610,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
