id: Panorama Query Logs - Test
inputs: []
name: Panorama Query Logs - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
      - '4'
      - '5'
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 17a467a9-e967-4ae8-83ae-deb0ed7a1ed5
      iscommand: false
      name: ''
      version: -1
    taskid: 17a467a9-e967-4ae8-83ae-deb0ed7a1ed5
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      action: {}
      addr-dst: {}
      addr-src: {}
      filedigest: {}
      log_type:
        simple: url
      port-dst: {}
      query: {}
      rule: {}
      time-generated: {}
      url:
        simple: winatp-gw-weu.microsoft.com
      zone-dst: {}
      zone-src: {}
    separatecontext: true
    task:
      brand: ''
      description: 'Query Panorama Logs of types: traffic, threat, url, data-filtering
        and wildfire.'
      id: c72b7079-0540-4e4f-8e31-53ad677da71b
      iscommand: false
      name: Panorama Query Logs
      playbookName: Panorama Query Logs
      type: playbook
      version: -1
    taskid: c72b7079-0540-4e4f-8e31-53ad677da71b
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Panorama.Monitor.Logs
          operator: isExists
      label: 'yes'
    id: '2'
    ignoreworker: false
    nexttasks:
      'yes':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 282bf112-1fe9-42e3-8fb0-2a7d4d54bef2
      iscommand: false
      name: Exist context
      type: condition
      version: -1
    taskid: 282bf112-1fe9-42e3-8fb0-2a7d4d54bef2
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 6d8e86bb-a8ef-48c2-8641-8a676ae68af2
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 6d8e86bb-a8ef-48c2-8641-8a676ae68af2
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      action:
        simple: allow
      addr-dst: {}
      addr-src: {}
      filedigest: {}
      log_type:
        simple: traffic
      port-dst: {}
      query: {}
      rule: {}
      time-generated: {}
      url: {}
      zone-dst: {}
      zone-src: {}
    separatecontext: true
    task:
      brand: ''
      description: 'Query Panorama Logs of types: traffic, threat, url, data-filtering
        and wildfire.'
      id: e707ab50-0f9a-4436-862c-e80583c031ff
      iscommand: false
      name: Panorama Query Logs
      playbookName: Panorama Query Logs
      type: playbook
      version: -1
    taskid: e707ab50-0f9a-4436-862c-e80583c031ff
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 195\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      action: {}
      addr-dst: {}
      addr-src:
        simple: null
      filedigest: {}
      log_type:
        simple: threat
      port-dst: {}
      query: {}
      rule: {}
      time-generated: {}
      url: {}
      zone-dst: {}
      zone-src: {}
    separatecontext: true
    task:
      brand: ''
      description: 'Query Panorama Logs of types: traffic, threat, url, data-filtering
        and wildfire.'
      id: c4878f59-6826-42ae-8477-5d1b09a04de1
      iscommand: false
      name: Panorama Query Logs
      playbookName: Panorama Query Logs
      type: playbook
      version: -1
    taskid: c4878f59-6826-42ae-8477-5d1b09a04de1
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 195\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      action: {}
      addr-dst: {}
      addr-src: {}
      filedigest: {}
      ip:
        simple: null
      log_type:
        simple: wildfire
      port-dst: {}
      query: {}
      rule: {}
      time-generated: {}
      url: {}
      zone-dst: {}
      zone-src: {}
    separatecontext: true
    task:
      brand: ''
      id: c3388883-c13b-4175-8ac5-e6118c3445e1
      iscommand: false
      name: Panorama Query Logs
      playbookName: Panorama Query Logs
      type: playbook
      version: -1
    taskid: c3388883-c13b-4175-8ac5-e6118c3445e1
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 195\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 560,\n      \"width\": 1670,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
