id: PAN-OS Create Or Edit Rule Test
inputs:
- description: ''
  key: rule_name
  required: false
  value:
    simple: pan_test_rule
- description: ''
  key: ip
  required: false
  value:
    simple: 1.1.1.1
- description: ''
  key: ip2
  required: false
  value:
    simple: 3.3.3.3
name: PAN-OS Create Or Edit Rule Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 2a61000b-48d7-443f-80ec-c403b1777347
      iscommand: false
      name: ''
      version: -1
    taskid: 2a61000b-48d7-443f-80ec-c403b1777347
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 15afee65-dc02-43f9-8a0a-2dd7cf4176cb
      iscommand: false
      name: Clear Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 15afee65-dc02-43f9-8a0a-2dd7cf4176cb
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '21'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: feae7714-eb8f-4072-807e-9136ae373793
      iscommand: false
      name: Clear Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: feae7714-eb8f-4072-807e-9136ae373793
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1490\n  }\n}"
  '13':
    continueonerror: true
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    scriptarguments:
      pre_post:
        simple: pre-rulebase
    separatecontext: false
    task:
      brand: ''
      id: b80be511-9f8f-4316-82f0-c27e6f70b668
      iscommand: true
      name: Get Rules
      script: '|||panorama-list-rules'
      type: regular
      version: -1
    taskid: b80be511-9f8f-4316-82f0-c27e6f70b668
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 990\n  }\n}"
  '14':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Panorama.SecurityRule.Name
          operator: notContainsGeneral
          right:
            iscontext: true
            value:
              simple: inputs.rule_name
      label: 'yes'
    id: '14'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '31'
      'yes':
      - '10'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 436257bb-b1ff-4c10-8a43-89d542bd9e61
      iscommand: false
      name: Check the rule does not exist
      type: condition
      version: -1
    taskid: 436257bb-b1ff-4c10-8a43-89d542bd9e61
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1190\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    scriptarguments:
      pre_post:
        simple: pre-rulebase
    separatecontext: false
    task:
      brand: ''
      id: 196bb267-5b16-45e5-807e-f99430704363
      iscommand: true
      name: Get Rules
      script: '|||panorama-list-rules'
      type: regular
      version: -1
    taskid: 196bb267-5b16-45e5-807e-f99430704363
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2165\n  }\n}"
  '16':
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: inputs.rule_name
          operator: in
          right:
            iscontext: true
            value:
              simple: Panorama.SecurityRule.Name
      - - left:
            iscontext: true
            value:
              simple: inputs.ip
          operator: in
          right:
            iscontext: true
            value:
              simple: Panorama.SecurityRule.Source
      label: 'yes'
    id: '16'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '32'
      'yes':
      - '22'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 5dcaea20-db75-4cf8-8d1a-f81f6b45fff9
      iscommand: false
      name: Check if the rule defined
      type: condition
      version: -1
    taskid: 5dcaea20-db75-4cf8-8d1a-f81f6b45fff9
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2340\n  }\n}"
  '17':
    continueonerror: true
    id: '17'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '26'
    note: false
    scriptarguments:
      device-group: {}
      pre_post:
        simple: pre-rulebase
      rulename:
        simple: ${inputs.rule_name}
    separatecontext: false
    task:
      brand: ''
      id: 971cdd47-6022-4c4c-8499-e8fb587b356a
      iscommand: true
      name: delete rule
      script: '|||panorama-delete-rule'
      type: regular
      version: -1
    taskid: 971cdd47-6022-4c4c-8499-e8fb587b356a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 380\n  }\n}"
  '20':
    id: '20'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 99878968-df56-4013-878a-44a7acc4eca1
      iscommand: false
      name: Clear Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 99878968-df56-4013-878a-44a7acc4eca1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 765\n  }\n}"
  '21':
    id: '21'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '27'
    note: false
    scriptarguments:
      action-type:
        simple: drop
      element-to-add:
        simple: ${inputs.ip}
      inbound-or-outbound-rule:
        simple: inbound
      log-forwarding-object-name: {}
      pre-post-rulebase:
        simple: pre-rulebase
      relative-rule-name: {}
      rule-position:
        simple: bottom
      rule_name:
        simple: ${inputs.rule_name}
    separatecontext: true
    task:
      brand: ''
      id: 77167e48-76f6-4f85-81a7-ea6228116138
      iscommand: false
      name: PAN-OS - Create Or Edit Rule
      playbookName: PAN-OS - Create Or Edit Rule
      type: playbook
      version: -1
    taskid: 77167e48-76f6-4f85-81a7-ea6228116138
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1665\n  }\n}"
  '22':
    id: '22'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '23'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 02797e88-7d24-46ce-8e35-7e09641f4379
      iscommand: false
      name: Clear Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 02797e88-7d24-46ce-8e35-7e09641f4379
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2620\n  }\n}"
  '23':
    id: '23'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '28'
    note: false
    scriptarguments:
      action-type:
        simple: drop
      element-to-add:
        simple: ${inputs.ip2}
      inbound-or-outbound-rule:
        simple: inbound
      log-forwarding-object-name: {}
      pre-post-rulebase:
        simple: pre-rulebase
      relative-rule-name: {}
      rule-position:
        simple: bottom
      rule_name:
        simple: ${inputs.rule_name}
    separatecontext: true
    task:
      brand: ''
      id: 665bc2ec-00fc-43f9-8be9-0ad69023b96e
      iscommand: false
      name: PAN-OS - Create Or Edit Rule
      playbookName: PAN-OS - Create Or Edit Rule
      type: playbook
      version: -1
    taskid: 665bc2ec-00fc-43f9-8be9-0ad69023b96e
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2790\n  }\n}"
  '24':
    id: '24'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '25'
    note: false
    scriptarguments:
      pre_post:
        simple: pre-rulebase
    separatecontext: false
    task:
      brand: ''
      id: cb6871c1-99ef-43c5-8b37-9055827b302c
      iscommand: true
      name: Get Rules
      script: '|||panorama-list-rules'
      type: regular
      version: -1
    taskid: cb6871c1-99ef-43c5-8b37-9055827b302c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3270\n  }\n}"
  '25':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.rule_name
          operator: in
          right:
            iscontext: true
            value:
              simple: Panorama.SecurityRule.Name
      - - left:
            iscontext: true
            value:
              simple: inputs.ip2
          operator: in
          right:
            iscontext: true
            value:
              simple: Panorama.SecurityRule.Source
      label: 'yes'
    id: '25'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '33'
      'yes':
      - '9'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 0d78612b-eb17-40ae-89f1-2bd4fad76a91
      iscommand: false
      name: Check if the rule defined
      type: condition
      version: -1
    taskid: 0d78612b-eb17-40ae-89f1-2bd4fad76a91
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3410\n  }\n}"
  '26':
    id: '26'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '20'
    note: false
    separatecontext: true
    task:
      brand: ''
      id: c25f7083-d802-4b71-8e45-fd3bef801cd8
      iscommand: false
      name: PAN-OS Commit Configuration
      playbookName: PAN-OS Commit Configuration
      type: playbook
      version: -1
    taskid: c25f7083-d802-4b71-8e45-fd3bef801cd8
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 570\n  }\n}"
  '27':
    id: '27'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '29'
    note: false
    separatecontext: true
    task:
      brand: ''
      id: c6f6d0af-2dee-4917-8bab-babe2deb1f54
      iscommand: false
      name: PAN-OS Commit Configuration
      playbookName: PAN-OS Commit Configuration
      type: playbook
      version: -1
    taskid: c6f6d0af-2dee-4917-8bab-babe2deb1f54
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1830\n  }\n}"
  '28':
    id: '28'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '30'
    note: false
    separatecontext: true
    task:
      brand: ''
      id: dda11fe1-c718-4296-838d-7db20fe4ce6f
      iscommand: false
      name: PAN-OS Commit Configuration
      playbookName: PAN-OS Commit Configuration
      type: playbook
      version: -1
    taskid: dda11fe1-c718-4296-838d-7db20fe4ce6f
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2945\n  }\n}"
  '29':
    id: '29'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 9bbc0144-d51e-45c1-87ee-41c178262570
      iscommand: false
      name: Clear Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 9bbc0144-d51e-45c1-87ee-41c178262570
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2000\n  }\n}"
  '30':
    id: '30'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '24'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 50cedc3a-a6d1-449a-8266-5d219cd164c0
      iscommand: false
      name: Clear Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 50cedc3a-a6d1-449a-8266-5d219cd164c0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3120\n  }\n}"
  '31':
    id: '31'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      message:
        simple: rule with the name ${inputs.rule_name} already exists in panorama
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: 53b7e44f-9f6b-402b-8427-aaa00573563d
      iscommand: false
      name: PrintErrorEntry
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 53b7e44f-9f6b-402b-8427-aaa00573563d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -490,\n    \"y\": 1490\n  }\n}"
  '32':
    id: '32'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      message:
        simple: rule with the name ${inputs.rule_name} and source ${inputs.ip} was
          not found in panorama
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: 79336487-36e7-44af-893b-3e7ae767420a
      iscommand: false
      name: PrintErrorEntry
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 79336487-36e7-44af-893b-3e7ae767420a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 740,\n    \"y\": 3410\n  }\n}"
  '33':
    id: '33'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      message:
        simple: rule with the name ${inputs.rule_name} and source ${inputs.ip2} was
          not found in panorama
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: 822e452f-ff45-4ba5-8642-550e0e8802cf
      iscommand: false
      name: PrintErrorEntry
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 822e452f-ff45-4ba5-8642-550e0e8802cf
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 360,\n    \"y\": 3640\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: a6b35b49-1dbc-4d69-8d56-efa0b363bdd6
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: a6b35b49-1dbc-4d69-8d56-efa0b363bdd6
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": -10,\n    \"y\": 3910\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"14_10_yes\": 0.59,\n    \"25_9_yes\"\
  : 0.53\n  },\n  \"paper\": {\n    \"dimensions\": {\n      \"height\": 3925,\n \
  \     \"width\": 1610,\n      \"x\": -490,\n      \"y\": 50\n    }\n  }\n}"
