description: ''
fromversion: 4.0.0
id: PAN-OS - Block IP and URL - External Dynamic List v2 Test
inputs: []
name: PAN-OS - Block IP and URL - External Dynamic List v2 Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 3242738e-8fbe-4299-80ad-259827475cb8
      iscommand: false
      name: ''
      version: -1
    taskid: 3242738e-8fbe-4299-80ad-259827475cb8
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": -90\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: bfdb19a5-603d-4dbb-8f7a-e00c889b2f1a
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: bfdb19a5-603d-4dbb-8f7a-e00c889b2f1a
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 380\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      all:
        simple: true
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 7e4fd3ee-35a8-4289-8792-a2c0b8f2054b
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 7e4fd3ee-35a8-4289-8792-a2c0b8f2054b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 40\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      AutoCommit:
        simple: true
      'EDLManagementServerURL ':
        simple: http://18.219.190.57/files/
      IP:
        simple: 1.1.1.1
      IPListName:
        simple: dont-del-ip-edl-test-elior
      LogForwarding: {}
      URL:
        simple: http://www.testurl.com
      URLListName:
        simple: dont-del-url-edl-test-elior
      device-group: {}
      inbound-or-outbound-rule:
        simple: outbound
      ip-pre-post-rulebase:
        simple: pre-rulebase
      ip-rule-position:
        simple: top
      url-pre-post-rulebase:
        simple: pre-rulebase
      url-rule-position:
        simple: top
    separatecontext: true
    task:
      brand: ''
      description: 'This playbook blocks IP addresses and URLs using Palo Alto Networks
        Panorama or Firewall External Dynamic Lists.

        It checks if the EDL configuration is in place with the ''PAN-OS EDL Setup''
        sub-playbook (otherwise the list will be configured), and adds the input IPs
        and URLs to the relevant lists.'
      id: e2ba81af-d4c7-4278-86a1-3e002b82a766
      iscommand: false
      name: PAN-OS - Block IP and URL - External Dynamic List v2
      playbookName: PAN-OS - Block IP and URL - External Dynamic List v2
      type: playbook
      version: -1
    taskid: e2ba81af-d4c7-4278-86a1-3e002b82a766
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 200\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 535,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\": -90\n\
  \    }\n  }\n}"
