id: PAN-OS DAG Configuration Test
inputs:
- description: ''
  key: tag_name
  required: false
  value:
    simple: dag_test_tag2
- description: ''
  key: rule_name
  required: false
  value:
    simple: dag_test_rule2
- description: ''
  key: address_group
  required: false
  value:
    simple: dag_test_ag2
- description: ''
  key: ip
  required: false
  value:
    simple: 7.7.7.7
name: PAN-OS DAG Configuration Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: c8f1b369-9ce7-46b3-895e-c0926762f118
      iscommand: false
      name: ''
      version: -1
    taskid: c8f1b369-9ce7-46b3-895e-c0926762f118
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 3f22ab71-1b4b-4831-8f23-af5a0e9982e8
      iscommand: false
      name: Clear Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 3f22ab71-1b4b-4831-8f23-af5a0e9982e8
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '23'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 31adb11f-ccdb-4eae-8e8d-15a65cd6ab32
      iscommand: false
      name: Clear Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 31adb11f-ccdb-4eae-8e8d-15a65cd6ab32
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1970\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      name:
        simple: ${inputs.address_group}
    separatecontext: false
    task:
      brand: ''
      description: Get details for the specified address group
      id: eb3cbd72-c119-4c6e-8db0-58e1da1a8cb8
      iscommand: true
      name: Get address group
      script: '|||panorama-get-address-group'
      type: regular
      version: -1
    taskid: eb3cbd72-c119-4c6e-8db0-58e1da1a8cb8
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2320\n  }\n}"
  '12':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Panorama.AddressGroups.Name
          operator: isEqualString
          right:
            iscontext: true
            value:
              simple: inputs.address_group
      - - left:
            iscontext: true
            value:
              simple: Panorama.AddressGroups.Match
          operator: isEqualString
          right:
            iscontext: true
            value:
              simple: inputs.tag_name
      label: 'yes'
    id: '12'
    ignoreworker: false
    nexttasks:
      'yes':
      - '15'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 7cd5849f-8c62-45ef-8257-807ad8499006
      iscommand: false
      name: Check if address group exist
      type: condition
      version: -1
    taskid: 7cd5849f-8c62-45ef-8257-807ad8499006
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2495\n  }\n}"
  '13':
    continueonerror: true
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    scriptarguments:
      pre_post:
        simple: pre-rulebase
    separatecontext: false
    task:
      brand: ''
      description: Returns a list of predefined Security Rules.
      id: 57d3f381-da8c-46ba-87c3-c284e2f44d94
      iscommand: true
      name: Get Rules
      script: '|||panorama-list-rules'
      type: regular
      version: -1
    taskid: 57d3f381-da8c-46ba-87c3-c284e2f44d94
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1600\n  }\n}"
  '14':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Panorama.SecurityRule.Name
          operator: notContainsGeneral
          right:
            iscontext: true
            value:
              simple: inputs.rule_name
      label: 'yes'
    id: '14'
    ignoreworker: false
    nexttasks:
      'yes':
      - '10'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: e3e9df9d-1fcf-4f43-85d5-72c367ad4315
      iscommand: false
      name: Check the rule does not exist
      type: condition
      version: -1
    taskid: e3e9df9d-1fcf-4f43-85d5-72c367ad4315
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1775\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    scriptarguments:
      pre_post:
        simple: pre-rulebase
    separatecontext: false
    task:
      brand: ''
      description: Returns a list of predefined Security Rules.
      id: 8cf5f7c3-b2ef-4914-8b91-4971a58d5eaf
      iscommand: true
      name: Get Rules
      script: '|||panorama-list-rules'
      type: regular
      version: -1
    taskid: 8cf5f7c3-b2ef-4914-8b91-4971a58d5eaf
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2670\n  }\n}"
  '16':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Panorama.SecurityRule.Name
          operator: containsString
          right:
            iscontext: true
            value:
              simple: inputs.rule_name
      label: 'yes'
    id: '16'
    ignoreworker: false
    nexttasks:
      'yes':
      - '9'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 726770ec-bd4b-4db7-89c7-770f6378174c
      iscommand: false
      name: Check if the rule defined
      type: condition
      version: -1
    taskid: 726770ec-bd4b-4db7-89c7-770f6378174c
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2855\n  }\n}"
  '17':
    continueonerror: true
    id: '17'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      device-group: {}
      pre_post:
        simple: pre-rulebase
      rulename:
        simple: ${inputs.rule_name}
    separatecontext: false
    task:
      brand: ''
      description: Deletes a policy rule
      id: 2054b0e1-acf2-48af-8e4e-f5bb287d4991
      iscommand: true
      name: delete rule
      script: '|||panorama-delete-rule'
      type: regular
      version: -1
    taskid: 2054b0e1-acf2-48af-8e4e-f5bb287d4991
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 550\n  }\n}"
  '18':
    id: '18'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '20'
    note: false
    separatecontext: true
    task:
      brand: ''
      id: cd9e7821-44f9-481b-8871-d4d4c3c897e7
      iscommand: false
      name: PAN-OS Commit Configuration
      playbookName: PAN-OS Commit Configuration
      type: playbook
      version: -1
    taskid: cd9e7821-44f9-481b-8871-d4d4c3c897e7
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 900\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    scriptarguments:
      IPs:
        simple: ${inputs.ip}
      tag:
        simple: ${inputs.tag_name}
    separatecontext: false
    task:
      brand: ''
      description: Unregisters IP addresses from a tag
      id: eb4615d0-ed33-4683-8e4b-748b2fd13e69
      iscommand: true
      name: Unregister IP from tag
      script: '|||panorama-unregister-ip-tag'
      type: regular
      version: -1
    taskid: eb4615d0-ed33-4683-8e4b-748b2fd13e69
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '20':
    id: '20'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 8e0e584d-eff0-4b41-88e6-f70febd2e0a0
      iscommand: false
      name: Clear Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 8e0e584d-eff0-4b41-88e6-f70febd2e0a0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1065\n  }\n}"
  '23':
    id: '23'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      action-type:
        simple: drop
      address_group_name:
        complex:
          root: inputs.address_group
      auto_commit:
        simple: 'Yes'
      device-group: {}
      inbound-or-outbound-rule:
        simple: outbound
      ip_list:
        complex:
          root: inputs.ip
      log-forwarding-object-name: {}
      pre-post-rulebase:
        simple: pre-rulebase
      relative-rule-name: {}
      rule-position:
        simple: bottom
      rule_name:
        complex:
          root: inputs.rule_name
      tag_name:
        complex:
          root: inputs.tag_name
    separatecontext: true
    task:
      brand: ''
      id: 3aff2f5d-840c-4afb-845b-2641a3472038
      iscommand: false
      name: PAN-OS DAG Configuration
      playbookName: PAN-OS DAG Configuration
      type: playbook
      version: -1
    taskid: 3aff2f5d-840c-4afb-845b-2641a3472038
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2140\n  }\n}"
  '3':
    continueonerror: true
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '18'
    note: false
    scriptarguments:
      name:
        simple: ${inputs.address_group}
    separatecontext: false
    task:
      brand: ''
      description: Deletes an address group
      id: 2e503cf3-d0da-480f-872c-4c103e883c74
      iscommand: true
      name: Delete address group
      script: '|||panorama-delete-address-group'
      type: regular
      version: -1
    taskid: 2e503cf3-d0da-480f-872c-4c103e883c74
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 725\n  }\n}"
  '7':
    continueonerror: true
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      name:
        simple: ${inputs.address_group}
    separatecontext: false
    task:
      brand: ''
      description: Get details for the specified address group
      id: 18c1e60a-cf71-4825-8a61-dbd9ff7d8995
      iscommand: true
      name: Get address group
      script: '|||panorama-get-address-group'
      type: regular
      version: -1
    taskid: 18c1e60a-cf71-4825-8a61-dbd9ff7d8995
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1230\n  }\n}"
  '8':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Panorama.AddressGroups.Name
          operator: notContainsGeneral
          right:
            iscontext: true
            value:
              simple: inputs.address_group
      label: 'yes'
    id: '8'
    ignoreworker: false
    nexttasks:
      'yes':
      - '13'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 4f308b30-e348-4796-87ea-4ceeda248c45
      iscommand: false
      name: check if address group does not exist
      type: condition
      version: -1
    taskid: 4f308b30-e348-4796-87ea-4ceeda248c45
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1405\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 906d9486-da54-4e8f-888e-23432c66cad9
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 906d9486-da54-4e8f-888e-23432c66cad9
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3080\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 3095,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
