fromversion: 4.0.0
id: PAN-OS - Block URL - Custom URL Category Test
inputs: []
name: PAN-OS - Block URL - Custom URL Category Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 7a0387ef-8ce5-4726-89d2-ffde6d07a989
      iscommand: false
      name: ''
      version: -1
    taskid: 7a0387ef-8ce5-4726-89d2-ffde6d07a989
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      AutoCommit:
        simple: 'No'
      CustomURLCategory:
        simple: Demisto Remediation - Malicious URLs
      LogForwarding: {}
      URL: {}
    separatecontext: true
    task:
      brand: ''
      id: 4cc2b944-4222-457e-84fe-98bf24d980c8
      iscommand: false
      name: PAN-OS - Block URL - Custom URL Category
      playbookName: PAN-OS - Block URL - Custom URL Category
      type: playbook
      version: -1
    taskid: 4cc2b944-4222-457e-84fe-98bf24d980c8
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 210\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 28959154-9b4f-4914-8057-7a59cf05bb21
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 28959154-9b4f-4914-8057-7a59cf05bb21
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 410\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 425,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\": 50\n\
  \    }\n  }\n}"
