description: ''
fromversion: 4.0.0
id: PAN-OS EDL Setup v3 Test
inputs:
- description: the name of the external file
  key: list-name
  required: false
  value:
    simple: dont-del-ip-edl-test-elior
name: PAN-OS EDL Setup v3 Test
outputs: []
sourceplaybookid: PAN-OS EDL Setup Test
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: e0fd3092-abc1-401e-8b67-d12e10260b81
      iscommand: false
      name: ''
      version: -1
    taskid: e0fd3092-abc1-401e-8b67-d12e10260b81
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": -395\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      action-type:
        simple: drop
      auto-commit:
        simple: true
      device-group: {}
      inbound-or-outbound-rule:
        simple: outbound
      ioc-type:
        simple: ip
      list-items:
        simple: 1.1.1.1
      list-name:
        simple: ${inputs.list-name}
      log-forwarding-object-name: {}
      pre-post-rulebase:
        simple: pre-rulebase
      relative-rule-name: {}
      rule-name:
        simple: ${inputs.list-name}
      rule-position:
        simple: top
      web-server-url:
        simple: http://18.219.190.57/files/
    separatecontext: true
    task:
      brand: ''
      description: 'Configures an external dynamic list in PAN-OS.

        In the event that the file exists on the web server, it will sync it to demisto.
        Then it will create an EDL object and a matching rule.'
      id: 35acf283-96be-4f82-835a-d139a35f3736
      iscommand: false
      name: PAN-OS EDL Setup v3
      playbookName: PAN-OS EDL Setup v3
      type: playbook
      version: -1
    taskid: 35acf283-96be-4f82-835a-d139a35f3736
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": -90\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    scriptarguments:
      all:
        simple: true
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 07bab852-564b-4abf-8229-4ccf4f50feb1
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 07bab852-564b-4abf-8229-4ccf4f50feb1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": -260\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: c0c11e5f-61c7-45d7-8524-8aee93ffd6ab
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: c0c11e5f-61c7-45d7-8524-8aee93ffd6ab
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 65\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 525,\n      \"width\": 380,\n      \"x\": 480,\n      \"y\": -395\n\
  \    }\n  }\n}"
