description: Test playbook for "Digital Defense FrontlineVM - Scan Asset Not Recently
  Scanned"
fromversion: 4.1.0
id: Digital Defense FrontlineVM - Scan Asset Not Recently Scanned Test
inputs: []
name: Digital Defense FrontlineVM - Scan Asset Not Recently Scanned Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 1a52d07f-7dac-48ff-8ca4-3cfe3b9492d8
      iscommand: false
      name: ''
      version: -1
    taskid: 1a52d07f-7dac-48ff-8ca4-3cfe3b9492d8
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: fd0c9d4d-2499-4b75-8e52-74b79a1c7e4d
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: fd0c9d4d-2499-4b75-8e52-74b79a1c7e4d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 200\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    separatecontext: true
    task:
      brand: ''
      description: ''
      id: a94bfb16-5648-4e0f-8244-425973df8546
      iscommand: false
      name: Digital Defense FrontlineVM - Scan Asset Not Recently Scanned
      playbookName: Digital Defense FrontlineVM - Scan Asset Not Recently Scanned
      type: playbook
      version: -1
    taskid: a94bfb16-5648-4e0f-8244-425973df8546
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 580\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    note: false
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      emailclassification: {}
      id:
        simple: ${incident.id}
      phishingsubtype: {}
    separatecontext: false
    task:
      brand: Builtin
      description: Closes the current incident.
      id: 702a374b-7856-4183-81ff-489d1edaad42
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 702a374b-7856-4183-81ff-489d1edaad42
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 800\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 845,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\": 50\n\
  \    }\n  }\n}"
