description: Test PB for Lastline integration
id: Lastline v2 - Test
inputs: []
name: Lastline v2 - Test
outputs: []
rolename: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 1647e00c-751a-4cf0-83ec-d0b30f76b12f
      iscommand: false
      name: ''
      version: -1
    taskid: 1647e00c-751a-4cf0-83ec-d0b30f76b12f
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    note: false
    separatecontext: true
    task:
      brand: ''
      id: 02f37b39-5a1b-422a-88f5-22667044dbe8
      iscommand: false
      name: Detonate File - Lastline v2
      playbookName: Detonate File - Lastline v2
      type: playbook
      version: -1
    taskid: 02f37b39-5a1b-422a-88f5-22667044dbe8
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '2':
    id: '2'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    note: false
    scriptarguments:
      Interval:
        simple: '1'
      Timeout:
        simple: '15'
      URL:
        complex:
          accessor: Data
          root: URL
    separatecontext: true
    task:
      brand: ''
      id: f8947776-c5a9-4565-84c1-89fb7d343cfb
      iscommand: false
      name: Detonate URL - Lastline v2
      playbookName: Detonate URL - Lastline v2
      type: playbook
      version: -1
    taskid: f8947776-c5a9-4565-84c1-89fb7d343cfb
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 720\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      append: {}
      key:
        simple: URL.Data
      value:
        simple: https://www.demisto.com
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 1e597c6e-d547-4d0c-8de6-5d0be300361d
      iscommand: false
      name: Set
      scriptName: Set
      type: regular
      version: -1
    taskid: 1e597c6e-d547-4d0c-8de6-5d0be300361d
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: http://www.pdf995.com/samples/pdf.pdf
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: 'Will create a file (using the given data input or entry ID) and
        upload it to current investigation war room.

        '
      id: ca9e8a7b-60f2-491b-8cc4-2a9fdfe83d07
      iscommand: false
      name: get pdf file
      scriptName: http
      type: regular
      version: -1
    taskid: ca9e8a7b-60f2-491b-8cc4-2a9fdfe83d07
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '4'
      - '3'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 0edeff33-2b87-4f81-8230-6720df23aecc
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 0edeff33-2b87-4f81-8230-6720df23aecc
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      append:
        simple: 'true'
      key:
        simple: URL.Data
      value:
        simple: https://www.google.com
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 37a616c3-766a-4ea0-8353-3a579bc37e7f
      iscommand: false
      name: Set2
      scriptName: Set
      type: regular
      version: -1
    taskid: 37a616c3-766a-4ea0-8353-3a579bc37e7f
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 765,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
