description: This playbook returns a file sample to the war-room given the file's
  SHA256 hash, using Cylance Protect v2 integration.
fromversion: 4.0.0
id: Get File Sample By Hash - Cylance Protect v2
inputs:
- description: ''
  key: SHA256
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
- description: 'Specifies whether the downloaded file will be unzipped. The command
    default is ''no''.

    Yes - unzip automatically

    No - will not unzip'
  key: unzip
  required: false
  value: {}
name: Get File Sample By Hash - Cylance Protect v2
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: cfa6c853-3dae-449f-810e-8a0303dda6b0
      iscommand: false
      name: ''
      version: -1
    taskid: cfa6c853-3dae-449f-810e-8a0303dda6b0
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Cylance Protect v2
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: 'yes'
    id: '1'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: a23dc210-7967-4632-81a5-ca345c80f56b
      iscommand: false
      name: Is Cylance Protect v2 enabled?
      type: condition
      version: -1
    taskid: a23dc210-7967-4632-81a5-ca345c80f56b
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: d346aafe-2acb-49f6-81ae-dc461600d941
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d346aafe-2acb-49f6-81ae-dc461600d941
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 710\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.SHA256
          operator: isNotEmpty
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: d3cb43ee-f52d-4112-8a87-4202337b4d29
      iscommand: false
      name: Is there a file to download?
      type: condition
      version: -1
    taskid: d3cb43ee-f52d-4112-8a87-4202337b4d29
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 320,\n    \"y\": 370\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      sha256:
        complex:
          root: inputs.SHA256
      threshold: {}
      unzip:
        complex:
          root: inputs.unzip
          transformers:
          - operator: toLowerCase
    separatecontext: false
    task:
      brand: Cylance Protect v2
      description: Downloads the threat (file) attached to a specific SHA256 hash.
      id: dfadf1e2-5822-4eb8-8050-a244ba71ee6f
      iscommand: true
      name: Cylance Protect - download threat
      script: Cylance Protect v2|||cylance-protect-download-threat
      type: regular
      version: -1
    taskid: dfadf1e2-5822-4eb8-8050-a244ba71ee6f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 700,\n    \"y\": 540\n  }\n}"
tests:
- No test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"1_2_#default#\": 0.28,\n    \"3_2_#default#\"\
  : 0.35,\n    \"3_4_yes\": 0.55\n  },\n  \"paper\": {\n    \"dimensions\": {\n  \
  \    \"height\": 725,\n      \"width\": 1030,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
