description: Returns to the war-room a file sample correlating to SHA256 hashes in
  the inputs using Cylance Protect integration
fromversion: 3.5.0
id: get_file_sample_by_hash_-_cylance_protect
inputs:
- description: The SHA256 hash of the file we want to download
  key: SHA256
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
- description: The password for the zip file
  key: ZipPassword
  required: true
  value:
    simple: infected
name: Get File Sample By Hash - Cylance Protect
outputs:
- contextPath: File
  description: The sample file
  type: unknown
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: d947a1c1-7312-4f99-8f56-bfcb4b0c3dfe
      iscommand: false
      name: ''
      version: -1
    taskid: d947a1c1-7312-4f99-8f56-bfcb4b0c3dfe
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#default#':
      - '9'
      'yes':
      - '3'
    note: false
    scriptarguments:
      value:
        complex:
          accessor: brand
          filters:
          - - left:
                iscontext: true
                value:
                  simple: modules.brand
              operator: isEqualString
              right:
                value:
                  simple: Cylance Protect v2
          - - left:
                iscontext: true
                value:
                  simple: modules.state
              operator: isEqualString
              right:
                value:
                  simple: active
          root: modules
    separatecontext: false
    task:
      brand: ''
      description: Checks if the the "Cylance Protect" integration is enabled
      id: bb196c7a-ff84-44c7-81fd-625038a5bcf4
      iscommand: false
      name: Is Cylance V2 Protect enabled?
      scriptName: Exists
      type: condition
      version: -1
    taskid: bb196c7a-ff84-44c7-81fd-625038a5bcf4
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '11'
    note: false
    scriptarguments:
      value:
        simple: ${inputs.SHA256}
    separatecontext: false
    task:
      brand: ''
      description: Checks for SHA256 in context
      id: 9a83a232-86f0-419b-8c7d-f441b6f6c46e
      iscommand: false
      name: Do we have a SHA256?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 9a83a232-86f0-419b-8c7d-f441b6f6c46e
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": -620,\n    \"y\": 370\n  }\n}"
  '11':
    continueonerror: true
    id: '11'
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      sha256:
        simple: ${inputs.SHA256}
      threshold: {}
      unzip: {}
    separatecontext: false
    task:
      brand: Cylance Protect
      description: Query Cylance Protect for HASH's link
      id: dea0c877-321d-4efa-8dfe-d2169fa93089
      iscommand: true
      name: Get download link from HASH
      script: Cylance Protect|||cylance-protect-download-threat
      type: regular
      version: -1
    taskid: dea0c877-321d-4efa-8dfe-d2169fa93089
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -620,\n    \"y\": 545\n  }\n}"
  '12':
    id: '12'
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '13'
    note: false
    scriptarguments:
      left: {}
      right: {}
      value:
        complex:
          accessor: Threat.Url
          root: Cylance
    separatecontext: false
    task:
      brand: ''
      description: Checks for a download link in context
      id: a5416443-e7db-45d3-86eb-86810cc208d6
      iscommand: false
      name: Did we get a download link?
      scriptName: Exists
      type: condition
      version: -1
    taskid: a5416443-e7db-45d3-86eb-86810cc208d6
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": -620,\n    \"y\": 720\n  }\n}"
  '13':
    id: '13'
    nexttasks:
      '#none#':
      - '14'
    note: false
    scriptarguments:
      body: {}
      filename:
        simple: ${inputs.SHA256}.zip
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        complex:
          accessor: Threat.Url
          root: Cylance
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: Send an HTTP request to download the zip file
      id: 98e64df6-7105-455f-8298-9101e96b04a9
      iscommand: false
      name: Download File (ZIP format)
      scriptName: http
      type: regular
      version: -1
    taskid: 98e64df6-7105-455f-8298-9101e96b04a9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -620,\n    \"y\": 895\n  }\n}"
  '14':
    id: '14'
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '15'
    note: false
    scriptarguments:
      extend-context: {}
      value:
        complex:
          accessor: EntryID
          filters:
          - - left:
                iscontext: true
                value:
                  simple: File.Extension
              operator: isEqualString
              right:
                value:
                  simple: zip
          root: File
    separatecontext: false
    task:
      brand: ''
      description: Checks for ZIP file format in context
      id: 1f0dd602-7af3-4cf2-8d52-92fe5ab4ead0
      iscommand: false
      name: Did we successfully download the ZIP file?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 1f0dd602-7af3-4cf2-8d52-92fe5ab4ead0
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": -620,\n    \"y\": 1070\n  }\n}"
  '15':
    id: '15'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      entryID:
        complex:
          accessor: EntryID
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: File.Extension
              operator: isEqualString
              right:
                value:
                  simple: zip
          root: File
      extend-context: {}
      fileName: {}
      lastZipFileInWarroom: {}
      password:
        complex:
          root: inputs.ZipPassword
    separatecontext: false
    task:
      brand: ''
      description: Unzip a file using fileName or entryID to specify a file. Files
        unzipped will be pushed to the war room and names will be pushed to the context.
      id: 7e6d9805-2917-46d9-891c-a944aa45b1f8
      iscommand: false
      name: Unzip File
      scriptName: UnzipFile
      type: regular
      version: -1
    taskid: 7e6d9805-2917-46d9-891c-a944aa45b1f8
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -620,\n    \"y\": 1245\n  }\n}"
  '2':
    id: '2'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: af2e86ff-6413-4cd8-8d5f-799edb0770e6
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: af2e86ff-6413-4cd8-8d5f-799edb0770e6
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": -180,\n    \"y\": 1930\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '4'
    note: false
    scriptarguments:
      value:
        simple: ${inputs.SHA256}
    separatecontext: false
    task:
      brand: ''
      description: Checks for SHA256 in context
      id: 283e4157-b249-4d36-8a57-c2983a3d61d4
      iscommand: false
      name: Do we have a SHA256?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 283e4157-b249-4d36-8a57-c2983a3d61d4
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 160,\n    \"y\": 370\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      sha256:
        simple: ${inputs.SHA256}
      threshold: {}
      unzip: {}
    separatecontext: false
    task:
      brand: Cylance Protect v2
      description: Query Cylance Protect for HASH's link
      id: bfa8a0e5-39d1-4cae-82f5-aa6cca072232
      iscommand: true
      name: Get download link from HASH
      script: Cylance Protect v2|||cylance-protect-download-threat
      type: regular
      version: -1
    taskid: bfa8a0e5-39d1-4cae-82f5-aa6cca072232
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 160,\n    \"y\": 545\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '6'
    note: false
    scriptarguments:
      left: {}
      right: {}
      value:
        complex:
          accessor: DownloadURL
          root: File
    separatecontext: false
    task:
      brand: ''
      description: Checks for a download link in context
      id: a2dfc6e8-e78a-4cc0-8de5-be4a8c155931
      iscommand: false
      name: Did we get a download link?
      scriptName: Exists
      type: condition
      version: -1
    taskid: a2dfc6e8-e78a-4cc0-8de5-be4a8c155931
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 160,\n    \"y\": 720\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      body: {}
      filename:
        simple: ${inputs.SHA256}.zip
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        complex:
          accessor: DownloadURL
          root: File
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: Send an HTTP request to download the zip file
      id: d12daf11-c3b1-4079-8b6d-4bbc6023cc4d
      iscommand: false
      name: Download File (ZIP format)
      scriptName: http
      type: regular
      version: -1
    taskid: d12daf11-c3b1-4079-8b6d-4bbc6023cc4d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 160,\n    \"y\": 895\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '8'
    note: false
    scriptarguments:
      extend-context: {}
      value:
        complex:
          accessor: EntryID
          filters:
          - - left:
                iscontext: true
                value:
                  simple: File.Extension
              operator: isEqualString
              right:
                value:
                  simple: zip
          root: File
    separatecontext: false
    task:
      brand: ''
      description: Checks for ZIP file format in context
      id: 917958d1-9c25-4f8d-84f3-5e272848d939
      iscommand: false
      name: Did we successfully download the ZIP file?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 917958d1-9c25-4f8d-84f3-5e272848d939
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 160,\n    \"y\": 1070\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      entryID:
        complex:
          accessor: EntryID
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: File.Extension
              operator: isEqualString
              right:
                value:
                  simple: zip
          root: File
      extend-context: {}
      fileName: {}
      lastZipFileInWarroom: {}
      password:
        complex:
          root: inputs.ZipPassword
    separatecontext: false
    task:
      brand: ''
      description: Unzip a file using fileName or entryID to specify a file. Files
        unzipped will be pushed to the war room and names will be pushed to the context.
      id: 5492c4d0-b0c3-4245-8c14-e43fc3ce553f
      iscommand: false
      name: Unzip File
      scriptName: UnzipFile
      type: regular
      version: -1
    taskid: 5492c4d0-b0c3-4245-8c14-e43fc3ce553f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 160,\n    \"y\": 1245\n  }\n}"
  '9':
    id: '9'
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '10'
    note: false
    scriptarguments:
      value:
        complex:
          accessor: brand
          filters:
          - - left:
                iscontext: true
                value:
                  simple: modules.brand
              operator: isEqualString
              right:
                value:
                  simple: Cylance Protect
          - - left:
                iscontext: true
                value:
                  simple: modules.state
              operator: isEqualString
              right:
                value:
                  simple: active
          root: modules
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 1a5cf78a-2b23-487e-8520-980ffc50bdf7
      iscommand: false
      name: Is Cylance V1 Protect enabled?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 1a5cf78a-2b23-487e-8520-980ffc50bdf7
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": -410,\n    \"y\": 195\n  }\n}"
tests:
- get_file_sample_by_hash_-_cylance_protect_-_test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"10_2_#default#\": 0.23,\n    \"9_2_#default#\"\
  : 0.17\n  },\n  \"paper\": {\n    \"dimensions\": {\n      \"height\": 1945,\n \
  \     \"width\": 1160,\n      \"x\": -620,\n      \"y\": 50\n    }\n  }\n}"
