id: Netcraft test
inputs: []
name: Netcraft test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 14a38052-5da5-4f4a-8721-8395192b7e81
      iscommand: false
      name: ''
      version: -1
    taskid: 14a38052-5da5-4f4a-8721-8395192b7e81
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 6239754b-682e-41fe-8a0e-1b6d2077734d
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 6239754b-682e-41fe-8a0e-1b6d2077734d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 230\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      date_from: {}
      id:
        simple: '2071408'
      ip: {}
      region: {}
      updated_since: {}
      url: {}
    separatecontext: false
    task:
      brand: ''
      description: Get information on existing takedowns.
      id: eb43210d-a955-4c53-8d93-740d4960357d
      iscommand: true
      name: Get takedown info
      script: '|||netcraft-get-takedown-info'
      type: regular
      version: -1
    taskid: eb43210d-a955-4c53-8d93-740d4960357d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 410\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Netcraft.Takedown.ID
          operator: isEqualNumber
          right:
            value:
              simple: '2071408'
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: dfd5dad7-b8d6-4a3d-88dc-7592d5efd36d
      iscommand: false
      name: Verify takedown info was received
      type: condition
      version: -1
    taskid: dfd5dad7-b8d6-4a3d-88dc-7592d5efd36d
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 590\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 6bf8eea8-5ee0-47ec-841e-7d9d5a208e66
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 6bf8eea8-5ee0-47ec-841e-7d9d5a208e66
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 790\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      author: {}
      date_from: {}
      date_to: {}
      group_id: {}
      takedown_id:
        simple: '493542'
    separatecontext: false
    task:
      brand: ''
      description: Get notes for takedowns
      id: 4b4b952e-cebe-40ec-86b5-80a8604d53dc
      iscommand: true
      name: Get takedown notes
      script: '|||netcraft-get-takedown-notes'
      type: regular
      version: -1
    taskid: 4b4b952e-cebe-40ec-86b5-80a8604d53dc
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 970\n  }\n}"
  '6':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Netcraft.Takedown.Note.NoteID
          operator: isEqualNumber
          right:
            value:
              simple: '6011601'
      label: 'yes'
    id: '6'
    ignoreworker: false
    nexttasks:
      'yes':
      - '7'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 940093e7-647b-44ea-8e15-40d6c51b3439
      iscommand: false
      name: Verify takedown notes were received
      type: condition
      version: -1
    taskid: 940093e7-647b-44ea-8e15-40d6c51b3439
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 1150\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: bdde794e-ca38-41ef-873e-a84851b13621
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: bdde794e-ca38-41ef-873e-a84851b13621
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 1330\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 752dce56-5dab-40a1-8e74-c2b4f8390334
      iscommand: false
      name: Success
      type: title
      version: -1
    taskid: 752dce56-5dab-40a1-8e74-c2b4f8390334
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 1510\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1525,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\":\
  \ 50\n    }\n  }\n}"
