id: EWS Mail Sender Test 2
inputs: []
name: EWS Mail Sender Test 2
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 53e3e9b8-f046-4b6e-8bf1-9e314ec8ddd3
      iscommand: false
      name: ''
      version: -1
    taskid: 53e3e9b8-f046-4b6e-8bf1-9e314ec8ddd3
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: 3d824a33-ccf2-4fb8-88d9-1447cef90aa4
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 3d824a33-ccf2-4fb8-88d9-1447cef90aa4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      height: {}
      type: {}
      url:
        simple: https://www.google.com
      width: {}
    separatecontext: false
    task:
      brand: ''
      id: 510a6b8a-1596-4df8-8313-6d0ad1034731
      iscommand: true
      name: Rasterize URL
      script: '|||rasterize'
      type: regular
      version: -1
    taskid: 510a6b8a-1596-4df8-8313-6d0ad1034731
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      attIDs:
        simple: ${InfoFile.EntryID}
      cc: {}
      to:
        simple: buildtests@demisto.int
    separatecontext: true
    task:
      brand: ''
      id: dd517ff2-16c6-4fa8-8510-f8d231f4b0ce
      iscommand: false
      name: Send Email To Recipients
      playbookName: Send Email To Recipients
      type: playbook
      version: -1
    taskid: dd517ff2-16c6-4fa8-8510-f8d231f4b0ce
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: e97ec6c4-e790-4487-8736-0ddd30c578b8
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: e97ec6c4-e790-4487-8736-0ddd30c578b8
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 735,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
