id: JoeSecurityTestPlaybook
inputs: []
name: JoeSecurityTestPlaybook
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 26ea8a78-103c-49d7-8034-25638309261f
      iscommand: false
      name: ''
      version: -1
    taskid: 26ea8a78-103c-49d7-8034-25638309261f
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: a511ca8b-a267-4ab1-87c6-ffd93bbf8207
      iscommand: false
      name: Start fresh
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: a511ca8b-a267-4ab1-87c6-ffd93bbf8207
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 195\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
      - '16'
      - '17'
    note: false
    quietmode: 0
    scriptarguments:
      query:
        simple: www.google.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: Joe Security
      id: e88619e0-d356-40ec-8c3c-d0c59c56b961
      iscommand: true
      name: Search command
      script: Joe Security|||joe-search
      type: regular
      version: -1
    taskid: e88619e0-d356-40ec-8c3c-d0c59c56b961
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      type:
        simple: xml
      webid:
        complex:
          accessor: Analysis(val.Status == "finished")}
          root: ${Joe
          transformers:
          - args:
              index:
                value:
                  simple: '0'
            operator: atIndex
          - args:
              field:
                value:
                  simple: WebID
            operator: getField
    separatecontext: false
    skipunavailable: false
    task:
      brand: Joe Security
      id: b067f7de-4967-4793-8570-c8f6b0b8a6bc
      iscommand: true
      name: Download url Report - XML
      script: Joe Security|||joe-download-report
      type: regular
      version: -1
    taskid: b067f7de-4967-4793-8570-c8f6b0b8a6bc
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 720\n  }\n}"
  '16':
    id: '16'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      type:
        simple: json
      webid:
        complex:
          accessor: Analysis(val.Status == "finished")}
          root: ${Joe
          transformers:
          - args:
              index:
                value:
                  simple: '0'
            operator: atIndex
          - args:
              field:
                value:
                  simple: WebID
            operator: getField
    separatecontext: false
    skipunavailable: false
    task:
      brand: Joe Security
      id: 2a3255d2-9b09-4f30-8b96-a417ec6705ff
      iscommand: true
      name: Download url Report - JSON
      script: Joe Security|||joe-download-report
      type: regular
      version: -1
    taskid: 2a3255d2-9b09-4f30-8b96-a417ec6705ff
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 950,\n    \"y\": 720\n  }\n}"
  '17':
    id: '17'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      type:
        simple: html
      webid:
        complex:
          accessor: Analysis(val.Status == "finished")}
          root: ${Joe
          transformers:
          - args:
              index:
                value:
                  simple: '0'
            operator: atIndex
          - args:
              field:
                value:
                  simple: WebID
            operator: getField
    separatecontext: false
    skipunavailable: false
    task:
      brand: Joe Security
      id: ebf685a2-5055-4e9d-8ec7-121780feb044
      iscommand: true
      name: Download url Report - HTML
      script: Joe Security|||joe-download-report
      type: regular
      version: -1
    taskid: ebf685a2-5055-4e9d-8ec7-121780feb044
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 60,\n    \"y\": 720\n  }\n}"
  '18':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Indicator
          operator: isNotEmpty
      label: 'yes'
    id: '18'
    ignoreworker: false
    nexttasks:
      'yes':
      - '9'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 5f79523d-a8a1-4b00-8d7c-58d05a312129
      iscommand: false
      name: verify output DBotScore.Indicator
      type: condition
      version: -1
    taskid: 5f79523d-a8a1-4b00-8d7c-58d05a312129
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1590\n  }\n}"
  '19':
    id: '19'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      type:
        simple: html
      webid:
        complex:
          accessor: Analysis(val.Status == "finished")}
          root: ${Joe
          transformers:
          - args:
              index:
                value:
                  simple: '0'
            operator: atIndex
          - args:
              field:
                value:
                  simple: WebID
            operator: getField
    separatecontext: false
    skipunavailable: false
    task:
      brand: Joe Security
      id: aa4d0849-3369-4811-810b-34d8d098ec5c
      iscommand: true
      name: Download url Report - HTML
      script: Joe Security|||joe-download-report
      type: regular
      version: -1
    taskid: aa4d0849-3369-4811-810b-34d8d098ec5c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 60,\n    \"y\": 900\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 99dd7269-b1b8-4b4c-841d-77379a02fab6
      iscommand: true
      name: Validate instance is working
      script: '|||joe-is-online'
      type: regular
      version: -1
    taskid: 99dd7269-b1b8-4b4c-841d-77379a02fab6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 360\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quietmode: 0
    scriptarguments:
      comments: {}
      file_id: {}
      internet-access: {}
      sample_url:
        simple: http://www.tutorialspoint.com/java/java_tutorial.pdf
      should_wait: {}
      systems: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Joe Security
      id: 74c1e9f0-e8f8-43c8-8a5c-563bf10c1fef
      iscommand: true
      name: Analyse a file using a url without waiting
      script: Joe Security|||joe-analysis-submit-sample
      type: regular
      version: -1
    taskid: 74c1e9f0-e8f8-43c8-8a5c-563bf10c1fef
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      comments: {}
      internet-access: {}
      should_wait:
        simple: 'False'
      systems: {}
      url:
        simple: www.google.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: Joe Security
      id: 96d71934-7869-4547-8807-c95ab3e36f1e
      iscommand: true
      name: Analyse a url without waiting
      script: Joe Security|||joe-analysis-submit-url
      type: regular
      version: -1
    taskid: 96d71934-7869-4547-8807-c95ab3e36f1e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      webid:
        simple: ${Joe.Analysis.[1].WebID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Joe Security
      id: 14aa4fcd-e9e7-4cb8-828f-2fedf2cca3d5
      iscommand: true
      name: Get info on the file analysis
      script: Joe Security|||joe-analysis-info
      type: regular
      version: -1
    taskid: 14aa4fcd-e9e7-4cb8-828f-2fedf2cca3d5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '18'
    note: false
    quietmode: 0
    scriptarguments:
      webid:
        simple: ${Joe.Analysis.[2].WebID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Joe Security
      id: 1462577b-a8b5-4c3c-8b08-eed1b8ad61cb
      iscommand: true
      name: Get info on the URL analysis
      script: Joe Security|||joe-analysis-info
      type: regular
      version: -1
    taskid: 1462577b-a8b5-4c3c-8b08-eed1b8ad61cb
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      data:
        simple: qwerty
      entryId: {}
      filename:
        simple: zaq.txt
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: cd1182f2-a2f4-4212-8e0b-f1e56e1795da
      iscommand: false
      name: Create sample file
      scriptName: FileCreateAndUpload
      type: regular
      version: -1
    taskid: cd1182f2-a2f4-4212-8e0b-f1e56e1795da
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1745\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1790,\n      \"width\": 1280,\n      \"x\": 50,\n      \"y\":\
  \ 50\n    }\n  }\n}"
