id: CheckPhish-Test
inputs: []
name: CheckPhish-Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
      - '2'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d6304948-03e1-4ab0-8196-ca82afce0ced
      iscommand: false
      name: ''
      version: -1
    taskid: d6304948-03e1-4ab0-8196-ca82afce0ced
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      url:
        simple: http://demisto.com,paypal-secure.online,https://github.com,http://www.w3.org,http://www.yahoo.com,www.fontedevidaeterna.org.br,www.pharmacymall.net
    separatecontext: false
    task:
      brand: CheckPhish
      description: Get the results of the check in CheckPhish
      id: 1a7cf7f6-399e-4d2e-88ad-8985a2f249b9
      iscommand: true
      name: CheckPhish-check-urls
      script: CheckPhish|||CheckPhish-check-urls
      type: regular
      version: -1
    taskid: 1a7cf7f6-399e-4d2e-88ad-8985a2f249b9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      'yes':
      - '11'
    note: false
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        complex:
          accessor: URL
          root: CheckPhish
          transformers:
          - args:
              equalTo:
                value:
                  simple: https://github.com/
              field:
                value:
                  simple: url
              getField:
                value:
                  simple: disposition
            operator: WhereFieldEquals
      right:
        simple: clean
    separatecontext: false
    task:
      brand: ''
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: e13ccc1b-fda4-448c-82db-b5428c56de50
      iscommand: false
      name: AreValuesEqual
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: e13ccc1b-fda4-448c-82db-b5428c56de50
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      'yes':
      - '12'
    note: false
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        complex:
          accessor: URL
          root: CheckPhish
          transformers:
          - args:
              equalTo:
                value:
                  simple: http://www.w3.org/
              field:
                value:
                  simple: url
              getField:
                value:
                  simple: disposition
            operator: WhereFieldEquals
      right:
        simple: clean
    separatecontext: false
    task:
      brand: ''
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: 02591242-3427-4eb2-8d66-505ec05efd90
      iscommand: false
      name: AreValuesEqual
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: 02591242-3427-4eb2-8d66-505ec05efd90
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 720\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        complex:
          accessor: URL
          root: CheckPhish
          transformers:
          - args:
              equalTo:
                value:
                  simple: http://www.yahoo.com/
              field:
                value:
                  simple: url
              getField:
                value:
                  simple: disposition
            operator: WhereFieldEquals
      right:
        simple: clean
    separatecontext: false
    task:
      brand: ''
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: b7d7cbb6-312d-48b0-8c44-c996eef9750d
      iscommand: false
      name: AreValuesEqual
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: b7d7cbb6-312d-48b0-8c44-c996eef9750d
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 895\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      url:
        simple: www.demisto.com
    separatecontext: false
    task:
      brand: CheckPhish
      description: Get the results of the check in CheckPhish
      id: 1e79c560-6058-4d51-8485-b9643fc72420
      iscommand: true
      name: CheckPhish-check-urls
      script: CheckPhish|||CheckPhish-check-urls
      type: regular
      version: -1
    taskid: 1e79c560-6058-4d51-8485-b9643fc72420
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '10'
    note: false
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        complex:
          accessor: URL
          root: CheckPhish
          transformers:
          - args:
              equalTo:
                value:
                  simple: http://demisto.com/
              field:
                value:
                  simple: url
              getField:
                value:
                  simple: disposition
            operator: WhereFieldEquals
      right:
        simple: clean
    separatecontext: false
    task:
      brand: ''
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: eef8c65a-0d56-4ef0-8dfc-eca3af72f84f
      iscommand: false
      name: AreValuesEqual
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: eef8c65a-0d56-4ef0-8dfc-eca3af72f84f
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      'yes':
      - '5'
    note: false
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        complex:
          accessor: URL
          root: CheckPhish
          transformers:
          - args:
              equalTo:
                value:
                  simple: http://paypal-secure.online/
              field:
                value:
                  simple: url
              getField:
                value:
                  simple: disposition
            operator: WhereFieldEquals
      right:
        simple: likely_phish
    separatecontext: false
    task:
      brand: ''
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: f2df02c6-ef6f-4e6f-8058-697e3bac499f
      iscommand: false
      name: AreValuesEqual
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: f2df02c6-ef6f-4e6f-8058-697e3bac499f
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1070\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      'yes':
      - '6'
    note: false
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        complex:
          accessor: URL
          root: CheckPhish
          transformers:
          - args:
              equalTo:
                value:
                  simple: http://www.fontedevidaeterna.org.br/
              field:
                value:
                  simple: url
              getField:
                value:
                  simple: disposition
            operator: WhereFieldEquals
      right:
        simple: phish
    separatecontext: false
    task:
      brand: ''
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: 37e74bd6-f864-43ca-8692-725f38991ea2
      iscommand: false
      name: AreValuesEqual
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: 37e74bd6-f864-43ca-8692-725f38991ea2
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1245\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      'yes':
      - '7'
    note: false
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        complex:
          accessor: URL
          root: CheckPhish
          transformers:
          - args:
              equalTo:
                value:
                  simple: http://www.pharmacymall.net/
              field:
                value:
                  simple: url
              getField:
                value:
                  simple: disposition
            operator: WhereFieldEquals
      right:
        simple: drug_spam
    separatecontext: false
    task:
      brand: ''
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: f28a998a-9371-40e0-8273-1632f29401e8
      iscommand: false
      name: AreValuesEqual
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: f28a998a-9371-40e0-8273-1632f29401e8
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1420\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    note: false
    scriptarguments:
      value:
        simple: '*CheckPhish multiple URLs are all done and correct*'
    separatecontext: false
    task:
      brand: ''
      description: Prints text to war room (Markdown supported)
      id: b61a816e-9a33-4bfb-8e4b-5ff783dc958c
      iscommand: false
      name: Print
      scriptName: Print
      type: regular
      version: -1
    taskid: b61a816e-9a33-4bfb-8e4b-5ff783dc958c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1595\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    note: false
    scriptarguments:
      value:
        simple: '*CheckPhish single URL is done and correct*'
    separatecontext: false
    task:
      brand: ''
      description: Prints text to war room (Markdown supported)
      id: f74b3940-d2f6-403e-8a89-00c35b2ccdc6
      iscommand: false
      name: Print
      scriptName: Print
      type: regular
      version: -1
    taskid: f74b3940-d2f6-403e-8a89-00c35b2ccdc6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      'yes':
      - '8'
    note: false
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        complex:
          accessor: URL
          root: CheckPhish
          transformers:
          - args:
              equalTo:
                value:
                  simple: http://www.demisto.com/
              field:
                value:
                  simple: url
              getField:
                value:
                  simple: disposition
            operator: WhereFieldEquals
      right:
        simple: clean
    separatecontext: false
    task:
      brand: ''
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: 412ec2de-ff5a-44e7-8eb6-ccbfb5b76765
      iscommand: false
      name: AreValuesEqual
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: 412ec2de-ff5a-44e7-8eb6-ccbfb5b76765
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1640,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
