id: virusTotalPrivateAPI-test-playbook
inputs: []
name: playbook-virusTotalPrivateAPI-test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: bf6ced84-68ce-44a0-8537-cc4d0b0be2fb
      iscommand: false
      name: ''
      version: -1
    taskid: bf6ced84-68ce-44a0-8537-cc4d0b0be2fb
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: d37c3fc5-451f-4d41-8a7f-40e1bc9f1c85
      iscommand: true
      name: DeleteContext
      script: DeleteContext
      type: regular
      version: -1
    taskid: d37c3fc5-451f-4d41-8a7f-40e1bc9f1c85
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    quietmode: 0
    scriptarguments:
      fullResponse: {}
      ip:
        simple: 8.8.8.8
      threshold: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: b1fbbfb6-f89a-4410-86c1-62e2af4108da
      iscommand: true
      name: vt-private-get-ip-report
      script: '|||vt-private-get-ip-report'
      type: regular
      version: -1
    taskid: b1fbbfb6-f89a-4410-86c1-62e2af4108da
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
  '11':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: IP.Address
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: IP.ASN
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: IP.Geo.Country
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: IP.Malicious.Vendor
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: IP.Malicious.Description
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Indicator
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Type
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Vendor
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Score
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: IP.VirusTotal.DownloadedHashes
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: IP.VirusTotal.UnAVDetectedDownloadedHashes
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: IP.VirusTotal.DetectedURLs
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: IP.VirusTotal.CommunicatingHashes
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: IP.VirusTotal.UnAVDetectedCommunicatingHashes
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: IP.VirusTotal.Resolutions.hostname
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: IP.VirusTotal.ReferrerHashes
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: IP.VirusTotal.UnAVDetectedReferrerHashes
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: IP.VirusTotal.Resolutions.last_resolved
          operator: isNotEmpty
      label: 'yes'
    id: '11'
    ignoreworker: false
    nexttasks:
      'yes':
      - '12'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 671d98fc-1e83-4711-8f7c-2c0133d16e95
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 671d98fc-1e83-4711-8f7c-2c0133d16e95
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    quietmode: 0
    scriptarguments:
      fullResponse: {}
      query:
        simple: type:peexe size:90kb+ positives:5+ behaviour:'taskkill'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 7b9dcf89-a09c-44bf-8377-43a01c164903
      iscommand: true
      name: vt-private-search-file
      script: '|||vt-private-search-file'
      type: regular
      version: -1
    taskid: 7b9dcf89-a09c-44bf-8377-43a01c164903
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1945\n  }\n}"
  '13':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: VirusTotal.SearchFile.SearchResult
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: VirusTotal.SearchFile.Query
          operator: isNotEmpty
      label: 'yes'
    id: '13'
    ignoreworker: false
    nexttasks:
      'yes':
      - '14'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 88b479e1-ffeb-403c-8cca-c76be347c35c
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 88b479e1-ffeb-403c-8cca-c76be347c35c
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2120\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    quietmode: 0
    scriptarguments:
      fullResponse: {}
      hash:
        simple: 10676cf66244cfa91567fbc1a937f4cb19438338b35b69d4bcc2cf0d3a44af5e
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: e850846e-3f40-4a65-8bcb-9f7d1929113f
      iscommand: true
      name: vt-private-hash-communication
      script: '|||vt-private-hash-communication'
      type: regular
      version: -1
    taskid: e850846e-3f40-4a65-8bcb-9f7d1929113f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2295\n  }\n}"
  '17':
    id: '17'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: e4a2a001-19b1-4964-8abf-be90f7522245
      iscommand: false
      name: Test Done
      type: title
      version: -1
    taskid: e4a2a001-19b1-4964-8abf-be90f7522245
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2470\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quietmode: 0
    scriptarguments:
      fullResponse: {}
      resource:
        simple: 10676cf66244cfa91567fbc1a937f4cb19438338b35b69d4bcc2cf0d3a44af5e
      threshold: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 285a30c1-336a-4abf-8296-7df72a9c0569
      iscommand: true
      name: vt-private-check-file-behaviour
      script: '|||vt-private-check-file-behaviour'
      type: regular
      version: -1
    taskid: 285a30c1-336a-4abf-8296-7df72a9c0569
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      domain:
        simple: google.com
      fullResponse: {}
      threshold: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 2a2965f8-8ebf-48f6-8b63-5bb4a779797d
      iscommand: true
      name: vt-private-get-domain-report
      script: '|||vt-private-get-domain-report'
      type: regular
      version: -1
    taskid: 2a2965f8-8ebf-48f6-8b63-5bb4a779797d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Domain.Name
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: Domain.VirusTotal.CommunicatingHashes
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: Domain.VirusTotal.Whois
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: Domain.VirusTotal.Subdomains
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: Domain.VirusTotal.Resolutions
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: Domain.VirusTotal.Categories
          operator: isNotEmpty
      label: 'yes'
    id: '5'
    ignoreworker: false
    nexttasks:
      'yes':
      - '6'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: d7e33d9a-4b0d-4924-86a7-9de1a47200cf
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: d7e33d9a-4b0d-4924-86a7-9de1a47200cf
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    quietmode: 0
    scriptarguments:
      allInfo: {}
      resource:
        simple: 10676cf66244cfa91567fbc1a937f4cb19438338b35b69d4bcc2cf0d3a44af5e
      shortFormat: {}
      threshold: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 18bdc683-43bf-41b1-84fe-d0d3344e69db
      iscommand: true
      name: vt-private-get-file-report
      script: '|||vt-private-get-file-report'
      type: regular
      version: -1
    taskid: 18bdc683-43bf-41b1-84fe-d0d3344e69db
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '7':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: File.MD5
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: File.SHA1
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: File.SHA256
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Indicator
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Type
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Vendor
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Score
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: File.VirusTotal.Scans
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: VirusTotal.ID
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: VirusTotal.Status
          operator: isNotEmpty
      label: 'yes'
    id: '7'
    ignoreworker: false
    nexttasks:
      'yes':
      - '8'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: f29462be-55fb-4611-8f4f-a58ca8a78089
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: f29462be-55fb-4611-8f4f-a58ca8a78089
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    quietmode: 0
    scriptarguments:
      allInfo: {}
      fullResponse: {}
      resource:
        simple: www.demisto.com
      retries: {}
      retry_time: {}
      shortFormat: {}
      threshold: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 35f23dd8-d63b-470c-8d51-692e05fb2b18
      iscommand: true
      name: vt-private-get-url-report
      script: '|||vt-private-get-url-report'
      type: regular
      version: -1
    taskid: 35f23dd8-d63b-470c-8d51-692e05fb2b18
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '9':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: URL.Data
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Indicator
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Type
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Vendor
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Score
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: URL.VirusTotal.Scans
          operator: isNotEmpty
      label: 'yes'
    id: '9'
    ignoreworker: false
    nexttasks:
      'yes':
      - '10'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: b3e6bb66-0a59-4a5f-8bc2-855569176d2f
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: b3e6bb66-0a59-4a5f-8bc2-855569176d2f
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2485,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
