id: Ipstack_Test
inputs: []
name: Ipstack_Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: fe5945da-0ba2-42c6-8836-aa988eb44984
      iscommand: false
      name: ''
      version: -1
    taskid: fe5945da-0ba2-42c6-8836-aa988eb44984
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 41e9c18c-61a6-4d62-8f28-f0a18edbea16
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 41e9c18c-61a6-4d62-8f28-f0a18edbea16
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 230\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      ip:
        simple: 8.8.8.8
    separatecontext: false
    task:
      brand: Ipstack
      description: query ip in ipstack
      id: 7006c21e-ccf7-4283-8cad-afc638a7cdae
      iscommand: true
      name: ip
      script: Ipstack|||ip
      type: regular
      version: -1
    taskid: 7006c21e-ccf7-4283-8cad-afc638a7cdae
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 410\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: IP.Geo.Country
          operator: isEqualString
          right:
            value:
              simple: United States
      - - left:
            iscontext: true
            value:
              simple: IP.Address
          operator: isEqualString
          right:
            value:
              simple: 8.8.8.8
      - - left:
            iscontext: true
            value:
              simple: Ipstack.ip.address
          operator: isEqualString
          right:
            value:
              simple: 8.8.8.8
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 4178d0ab-0e9b-462b-8b58-9d50f232a5b9
      iscommand: false
      name: test result
      type: condition
      version: -1
    taskid: 4178d0ab-0e9b-462b-8b58-9d50f232a5b9
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 590\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      id: {}
      importantfield: {}
      test2: {}
      timefield1: {}
    separatecontext: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 4a711a79-d2e8-492a-8229-de524de1f0ac
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 4a711a79-d2e8-492a-8229-de524de1f0ac
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 900\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 945,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\": 50\n\
  \    }\n  }\n}"
