args:
- default: true
  description: The registry path of the key to query
  name: regpath
  required: true
comment: Collect values for the given registry path from all Windows systems in this
  investigation.
commonfields:
  id: RegCollectValues
  version: -1
dependson: {}
name: RegCollectValues
script: "def Reg2Markdown(baseKey,regResp):\n    res, mdRows  = [], ''\n    if isError(regResp[0]):\n\
  \        res += regResp\n    elif len(regResp) > 1 :\n        res.append( { 'Type'\
  \ : entryTypes['error'], 'ContentsFormat' : formats['text'], 'Contents' : 'Unexpected\
  \ output from D2RegQuery - more than one entry returned:\\n'+'\\n'.join( [ str(x)\
  \ for x in regResp ] ) } )\n    else:\n        subkeys = regResp[0]['Contents']\n\
  \        for sk in subkeys:\n            if type(subkeys[sk]) == dict:\n       \
  \         for ssk in subkeys[sk]:\n                    mdRows += '\\n|' + str(baseKey)\
  \ + '\\\\' + str(sk) + '|' + str(ssk) + '|' + str( subkeys[sk][ssk] ) + '|'\n  \
  \          else:\n                mdRows += '\\n|' + str(baseKey) + '|' + str(sk)\
  \ + '|' + str( subkeys[sk] ) + '|'\n    return ( res, mdRows )\n# Note: Don't use\
  \ !d2_status as that only shows systems with generated agents - the correct way\
  \ is below:\nres = []\nregPath = NormalizeRegistryPath( demisto.args()['regpath']\
  \ )\nfor system in demisto.investigation()['systems']:\n   if system['os'] == 'windows':\n\
  \        mdTable = '### Values retrieved from system *' + system['name'] + '*'\n\
  \        mdTable += '\\n|Key|SubKey|Value|'\n        mdTable += '\\n|-----|------|-----|'\n\
  \        cmdResp = demisto.executeCommand( 'D2RegQuery', { 'using' : system['name'],\
  \ 'regpath' : regPath } )\n        moreEntries, moreRows = Reg2Markdown( regPath\
  \ , cmdResp )\n        mdTable += moreRows\n        res += moreEntries\n       \
  \ res.append( { 'Type' : entryTypes['note'], 'ContentsFormat' : formats['markdown'],\
  \ 'Contents' : mdTable } )\ndemisto.results(res)"
scripttarget: 0
subtype: python2
system: true
tags:
- registry
- enhancement
timeout: 0s
toversion: 4.1.9
type: python
