description: ''
fromversion: 3.6.0
id: CBFindIP - Test
inputs: []
name: CBFindIP - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 11ee419a-12a9-4c9a-8064-661025b9413c
      iscommand: false
      name: ''
      version: -1
    taskid: 11ee419a-12a9-4c9a-8064-661025b9413c
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: f9c6da92-d6e1-4a7f-8de2-0474ae4fc01f
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: f9c6da92-d6e1-4a7f-8de2-0474ae4fc01f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 220\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      ip:
        simple: 8.8.8.8
    separatecontext: false
    task:
      brand: ''
      description: Search Carbon Black for connection to specified IP address(es).
      id: 86ab5275-9919-4f4d-8290-324fe01bb228
      iscommand: false
      name: Find IP
      scriptName: CBFindIP
      type: regular
      version: -1
    taskid: 86ab5275-9919-4f4d-8290-324fe01bb228
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 400\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: PID
                root: Process
                transformers:
                - operator: GetFirstObject
          operator: isExists
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: fd769a21-e039-49d1-8f17-2fa528084b89
      iscommand: false
      name: Check results
      type: condition
      version: -1
    taskid: fd769a21-e039-49d1-8f17-2fa528084b89
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 580\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: a85785c4-6612-447c-873f-142d418f61f0
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: a85785c4-6612-447c-873f-142d418f61f0
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 750\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 765,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\": 50\n\
  \    }\n  }\n}"
