description: ''
id: Flashpoint_report-Test
inputs: []
name: Flashpoint_report-Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: c193fb00-d70b-4ebe-80c5-f5e38d56627e
      iscommand: false
      name: ''
      version: -1
    taskid: c193fb00-d70b-4ebe-80c5-f5e38d56627e
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      report_search:
        simple: isis
    separatecontext: false
    task:
      brand: Flashpoint
      description: Search for the Intelligence Reports using a keyword
      id: eea3444f-5ca4-4ab7-8efe-863e18e6827e
      iscommand: true
      name: flashpoint-search-intelligence-reports
      script: Flashpoint|||flashpoint-search-intelligence-reports
      type: regular
      version: -1
    taskid: eea3444f-5ca4-4ab7-8efe-863e18e6827e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 610,\n    \"y\": 370\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      report_id:
        simple: tiPqg51OQpOTsoFyTaYa_w
    separatecontext: false
    task:
      brand: Flashpoint
      description: Get related reports for a given report id
      id: 219d1ba2-724c-4713-813f-98bbab9562af
      iscommand: true
      name: flashpoint-get-related-reports
      script: Flashpoint|||flashpoint-get-related-reports
      type: regular
      version: -1
    taskid: 219d1ba2-724c-4713-813f-98bbab9562af
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 670,\n    \"y\": 1600\n  }\n}"
  '11':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Report}
                root: ${Flashpoint
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: ${Flashpoint.Report.NotifiedAt}
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ${Flashpoint.Report.PlatformUrl}
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ${Flashpoint.Report.PostedAt}
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ${Flashpoint.Report.ReportId}
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ${Flashpoint.Report.Summary}
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ${Flashpoint.Report.Title}
          operator: isExists
      label: 'yes'
    id: '11'
    ignoreworker: false
    nexttasks:
      'yes':
      - '12'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: dc552997-592e-4418-88bd-659189009f7c
      iscommand: false
      name: Verify report
      type: condition
      version: -1
    taskid: dc552997-592e-4418-88bd-659189009f7c
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 690,\n    \"y\": 1780\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    note: false
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      emailclassification: {}
      id:
        simple: ${incident.id}
      phishingsubtype: {}
    separatecontext: false
    task:
      brand: Builtin
      description: Close the current incident
      id: eeed47e4-b3a3-4f43-8c4b-4f7abddbfe2a
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: eeed47e4-b3a3-4f43-8c4b-4f7abddbfe2a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 690,\n    \"y\": 1960\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: af29beec-63e1-4ab9-8efc-ddbfdbc166c7
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: af29beec-63e1-4ab9-8efc-ddbfdbc166c7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 570,\n    \"y\": 210\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Report}
                root: ${Flashpoint
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: ${Flashpoint.Report.NotifiedAt}
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ${Flashpoint.Report.PlatformUrl}
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ${Flashpoint.Report.PostedAt}
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ${Flashpoint.Report.ReportId}
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ${Flashpoint.Report.Summary}
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ${Flashpoint.Report.Title}
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ${Flashpoint.Report.UpdatedAt}
          operator: isExists
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: bb92bf67-b955-4bcd-840c-6364abcedd48
      iscommand: false
      name: verify report
      type: condition
      version: -1
    taskid: bb92bf67-b955-4bcd-840c-6364abcedd48
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 620,\n    \"y\": 520\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d735f8f5-c2e3-4339-8b19-ff4d12348c61
      iscommand: false
      name: Process Single Intelligence report
      type: title
      version: -1
    taskid: d735f8f5-c2e3-4339-8b19-ff4d12348c61
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 620,\n    \"y\": 680\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      report_id:
        simple: e-QdYuuwRwCntzRljzn9-A
    separatecontext: false
    task:
      brand: Flashpoint
      description: Get a single report by its ID
      id: 810740c6-59fe-472c-85f8-a75cc7f57f84
      iscommand: true
      name: flashpoint-get-single-intelligence-report
      script: Flashpoint|||flashpoint-get-single-intelligence-report
      type: regular
      version: -1
    taskid: 810740c6-59fe-472c-85f8-a75cc7f57f84
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 620,\n    \"y\": 970\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: fc386795-57c5-4020-8a99-b7fc93e061cd
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: fc386795-57c5-4020-8a99-b7fc93e061cd
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 620,\n    \"y\": 820\n  }\n}"
  '7':
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: Report.Title}
                root: ${Flashpoint
          operator: containsGeneral
          right:
            value:
              simple: ISIS
      - - left:
            iscontext: true
            value:
              simple: ${Flashpoint.Report.NotifiedAt}
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ${Flashpoint.Report.PlatformUrl}
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ${Flashpoint.Report.PostedAt}
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ${Flashpoint.Report.ReportId}
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ${Flashpoint.Report.Summary}
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ${Flashpoint.Report.UpdatedAt}
          operator: isExists
      label: 'yes'
    id: '7'
    ignoreworker: false
    nexttasks:
      'yes':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 599245b5-d5f7-4370-8a89-18cafdd0dab7
      iscommand: false
      name: Verify single intelligence report
      type: condition
      version: -1
    taskid: 599245b5-d5f7-4370-8a89-18cafdd0dab7
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 620,\n    \"y\": 1130\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d47f1166-c12c-4faa-8430-34fd9f5a3a08
      iscommand: false
      name: Process get related reoprt
      type: title
      version: -1
    taskid: d47f1166-c12c-4faa-8430-34fd9f5a3a08
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 620,\n    \"y\": 1290\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 89f218aa-affd-4c64-815e-c41da8098dae
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 89f218aa-affd-4c64-815e-c41da8098dae
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 670,\n    \"y\": 1420\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2005,\n      \"width\": 620,\n      \"x\": 450,\n      \"y\":\
  \ 50\n    }\n  }\n}"
