contentitemfields:
  propagationLabels: []
id: TruSTAR Test
inputs: []
name: TruSTAR Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 837b6056-f6e5-44a4-890a-2870506c79c7
      iscommand: false
      name: ''
      version: -1
    taskid: 837b6056-f6e5-44a4-890a-2870506c79c7
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    scriptarguments:
      days-back: {}
      type: {}
    separatecontext: false
    task:
      brand: TruSTAR
      description: Returns the 10 indicators that have recently appeared in the most
        community reports. This is analogous to the Community Trends section of the
        dashboard on Station.
      id: b139ff93-1628-4c02-86b5-40642c571a3f
      iscommand: true
      name: Trending Indicators
      script: TruSTAR|||trustar-trending-indicators
      type: regular
      version: -1
    taskid: b139ff93-1628-4c02-86b5-40642c571a3f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    scriptarguments:
      domain:
        simple: www.google.com
      threshold: {}
    separatecontext: false
    task:
      brand: TruSTAR
      description: Returns domain maliciousness details
      id: cf997137-f65a-46d3-8f1d-b46d7ffec56b
      iscommand: true
      name: Search for Domain using domain
      script: TruSTAR|||domain
      type: regular
      version: -1
    taskid: cf997137-f65a-46d3-8f1d-b46d7ffec56b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    scriptarguments:
      file:
        simple: 84c82835a5d21bbcf75a61706d8ab549
      threshold: {}
    separatecontext: false
    task:
      brand: TruSTAR
      description: Returns file maliciousness details
      id: 837b71a5-0bf2-4fa7-88ae-f46bc25609dc
      iscommand: true
      name: Search for File using file
      script: TruSTAR|||file
      type: regular
      version: -1
    taskid: 837b71a5-0bf2-4fa7-88ae-f46bc25609dc
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    scriptarguments:
      ip:
        simple: 8.8.4.4
      threshold: {}
    separatecontext: false
    task:
      brand: TruSTAR
      description: Returns ip maliciousness details
      id: fc76e371-d44f-44ee-8e59-46e083d2fe6d
      iscommand: true
      name: Search for IP using ip
      script: TruSTAR|||ip
      type: regular
      version: -1
    taskid: fc76e371-d44f-44ee-8e59-46e083d2fe6d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2120\n  }\n}"
  '13':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: URL.Data
          operator: isExists
      label: 'yes'
    id: '13'
    ignoreworker: false
    nexttasks:
      'yes':
      - '10'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: bd210e82-1605-4480-8420-9c7be9b8e388
      iscommand: false
      name: Verify Context
      type: condition
      version: -1
    taskid: bd210e82-1605-4480-8420-9c7be9b8e388
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '14':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Domain.Name
          operator: isExists
      label: 'yes'
    id: '14'
    ignoreworker: false
    nexttasks:
      'yes':
      - '11'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: c0c6df55-f737-4095-8b42-dc02b65e505e
      iscommand: false
      name: Verify Context
      type: condition
      version: -1
    taskid: c0c6df55-f737-4095-8b42-dc02b65e505e
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
  '15':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: TruSTAR.File.Value
          operator: isEqualString
          right:
            value:
              simple: 84c82835a5d21bbcf75a61706d8ab549
      label: 'yes'
    id: '15'
    ignoreworker: false
    nexttasks:
      'yes':
      - '12'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: e98a02b0-13c2-4308-879f-893cfef38fd0
      iscommand: false
      name: Verify Context
      type: condition
      version: -1
    taskid: e98a02b0-13c2-4308-879f-893cfef38fd0
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1945\n  }\n}"
  '16':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: IP.Address
          operator: isEqualString
          right:
            value:
              simple: 8.8.4.4
      label: 'yes'
    id: '16'
    ignoreworker: false
    nexttasks:
      'yes':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 1d6865af-8d82-4fed-8843-709384cc076d
      iscommand: false
      name: Verify Context
      type: condition
      version: -1
    taskid: 1d6865af-8d82-4fed-8843-709384cc076d
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2295\n  }\n}"
  '17':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: File
          operator: isExists
        - left:
            iscontext: true
            value:
              simple: IP
          operator: isExists
        - left:
            iscontext: true
            value:
              simple: URL
          operator: isExists
      label: 'yes'
    id: '17'
    ignoreworker: false
    nexttasks:
      'yes':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 3b061876-ef4e-4612-8642-500b4dfe0b58
      iscommand: false
      name: Verify Context
      type: condition
      version: -1
    taskid: 3b061876-ef4e-4612-8642-500b4dfe0b58
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 7122c19f-b494-4b75-8f4c-673dc2a5a57e
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 7122c19f-b494-4b75-8f4c-673dc2a5a57e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      enclave-ids: {}
      page-number: {}
      page-size: {}
      search-term:
        simple: http
    separatecontext: false
    task:
      brand: TruSTAR
      description: Searches for all indicators that contain the given search term.
      id: 422bc58b-9835-4659-8a26-12b933e9905c
      iscommand: true
      name: Search Indicators with the term http
      script: TruSTAR|||trustar-search-indicators
      type: regular
      version: -1
    taskid: 422bc58b-9835-4659-8a26-12b933e9905c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      distribution-type: {}
      enclave-ids: {}
      indicators:
        simple: https://medium.com
      page-number: {}
      page-size: {}
    separatecontext: false
    task:
      brand: TruSTAR
      description: Returns a paginated list of all reports that contain any of the
        provided indicator values.
      id: 2d8fb1db-33ac-4d17-89d7-d10aeddd39dc
      iscommand: true
      name: Get correlated reports of a URL indicator
      script: TruSTAR|||trustar-correlated-reports
      type: regular
      version: -1
    taskid: 2d8fb1db-33ac-4d17-89d7-d10aeddd39dc
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d7631929-293d-4ced-873d-e635d8ac5fba
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d7631929-293d-4ced-873d-e635d8ac5fba
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2470\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    scriptarguments:
      threshold: {}
      url:
        simple: www.google.com
    separatecontext: false
    task:
      brand: TruSTAR
      description: Returns url maliciousness details
      id: fdc7ee6f-4de7-4bb4-88ec-66477248cb36
      iscommand: true
      name: Search for URL using url
      script: TruSTAR|||url
      type: regular
      version: -1
    taskid: fdc7ee6f-4de7-4bb4-88ec-66477248cb36
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2485,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
