id: ThreatGridTest
inputs: []
name: ThreatGridTest
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 605c02ae-d143-46a9-8b47-0cabdc00815f
      iscommand: false
      name: ''
      version: -1
    taskid: 605c02ae-d143-46a9-8b47-0cabdc00815f
    type: start
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
      - '3'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: e67ea594-c1f8-4af8-8431-7e7251361cff
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: e67ea594-c1f8-4af8-8431-7e7251361cff
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    note: false
    scriptarguments:
      adminLogin:
        simple: ${ThreatGrid.User.Login}
    separatecontext: false
    task:
      brand: Threat Grid
      description: "Get rate limits applied to an organization. ThreatGrid employs\
        \ a simple rate limiting method for sample submissions by specifying the number\
        \ of samples which can be submitted within some variable time period by an\
        \ entire organization and/or per a license basis.\_Multiple rate limits can\
        \ be employed to form overlapping submission limits. For example, 20 submissions\
        \ per hour AND 400 per day."
      id: f3299dd5-9061-4701-80bc-c71a98646e72
      iscommand: true
      name: threat-grid-organization-get-rate-limit
      script: Threat Grid|||threat-grid-organization-get-rate-limit
      type: regular
      version: -1
    taskid: f3299dd5-9061-4701-80bc-c71a98646e72
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 720\n  }\n}"
  '11':
    id: '11'
    nexttasks:
      'yes':
      - '10'
    note: false
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        simple: ${ThreatGrid.User.Role}
      right:
        simple: org-admin
    separatecontext: false
    task:
      brand: ''
      id: 3b03c27f-76df-4931-8f91-0ff6fedd1569
      iscommand: false
      name: Check if user is admin
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: 3b03c27f-76df-4931-8f91-0ff6fedd1569
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '12':
    id: '12'
    nexttasks:
      'yes':
      - '7'
    note: false
    scriptarguments:
      value:
        simple: ${ThreatGrid.Sample.State(val=='succ')}
    separatecontext: false
    task:
      brand: ''
      id: e4034458-8dfb-430f-8bb3-440c7a5aed0f
      iscommand: false
      name: Verify that the sample state is succ
      scriptName: Exists
      type: condition
      version: -1
    taskid: e4034458-8dfb-430f-8bb3-440c7a5aed0f
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 545\n  }\n}"
  '18':
    id: '18'
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      all:
        simple: 'no'
      index: {}
      key:
        simple: ThreatGrid.Sample
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: 03ec97ab-dd12-4ca4-8951-1487440e2746
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 03ec97ab-dd12-4ca4-8951-1487440e2746
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 895\n  }\n}"
  '19':
    id: '19'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 03d28874-b3d2-481b-8069-e1bd0443d958
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 03d28874-b3d2-481b-8069-e1bd0443d958
    type: title
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 1420\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '4'
      - '11'
    note: false
    separatecontext: false
    task:
      brand: Threat Grid
      description: Get logged in user
      id: 449c3f3b-0976-4aef-87fc-b9d7955e9647
      iscommand: true
      name: Get user information from current session
      script: Threat Grid|||threat-grid-who-am-i
      type: regular
      version: -1
    taskid: 449c3f3b-0976-4aef-87fc-b9d7955e9647
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '20':
    id: '20'
    nexttasks:
      '#none#':
      - '19'
    note: false
    scriptarguments:
      id:
        simple: ${ThreatGrid.Sample.ID}
    separatecontext: false
    task:
      brand: Threat Grid
      description: Returns a summary of the threats detected during analysis
      id: f8a11599-7804-421b-8625-02bcad524061
      iscommand: true
      name: threat-grid-get-threat-summary-by-id
      script: Threat Grid|||threat-grid-get-threat-summary-by-id
      type: regular
      version: -1
    taskid: f8a11599-7804-421b-8625-02bcad524061
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 1245\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      after:
        simple: 2018-07-01T00:00:00-0000
      before:
        simple: 2018-09-10T00:00:00-0000
      id: {}
      ids: {}
      ioc: {}
      limit:
        simple: '1'
      md5: {}
      offset: {}
      org_only: {}
      sha1: {}
      sha256: {}
      user_only: {}
    separatecontext: false
    task:
      brand: Threat Grid
      description: Search samples on the Threat Grid platform. Input parameters are
        ANDed together. Only finished samples can be searched (that is, the ones that
        are having a status of succ or fail.)
      id: 28717024-c17a-4602-83f4-cc999b6b60c4
      iscommand: true
      name: Get samples (limit of 1) from given time range
      script: Threat Grid|||threat-grid-get-samples
      type: regular
      version: -1
    taskid: 28717024-c17a-4602-83f4-cc999b6b60c4
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 370\n  }\n}"
  '4':
    id: '4'
    note: false
    scriptarguments:
      login:
        simple: ${ThreatGrid.User.Login}
    separatecontext: false
    task:
      brand: Threat Grid
      description: "Get rate limit for a specific user name. ThreatGrid employs a\
        \ simple rate limiting method for sample submissions by specifying the number\
        \ of samples which can be submitted within some variable time period by a\
        \ user.\_Multiple rate limits can be employed to form overlapping submission\
        \ limits. For example, 20 submissions per hour AND 400 per day."
      id: bf7891c5-2f6f-4d6f-84cc-f66bea619105
      iscommand: true
      name: Get user rate limit
      script: Threat Grid|||threat-grid-user-get-rate-limit
      type: regular
      version: -1
    taskid: bf7891c5-2f6f-4d6f-84cc-f66bea619105
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '18'
    note: false
    scriptarguments:
      id:
        simple: ${ThreatGrid.Sample.ID}
    separatecontext: false
    task:
      brand: Threat Grid
      description: Download a sample by using its ID. The downloaded file is an archive
        of the sample itself, in a zip format as a form of quarantine.
      id: d11b9e22-f125-4151-8f2b-ca4f9d8e48ac
      iscommand: true
      name: 'Download the sample '
      script: Threat Grid|||threat-grid-download-sample-by-id
      type: regular
      version: -1
    taskid: d11b9e22-f125-4151-8f2b-ca4f9d8e48ac
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 720\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '20'
    note: false
    scriptarguments:
      file-id:
        simple: ${File.EntryID}
      filename:
        simple: SampleTestFile
      playbook: {}
      private: {}
      tags: {}
      vm: {}
    separatecontext: false
    task:
      brand: Threat Grid
      description: Submits a sample to threat grid for analysis
      id: cfbde5d6-beed-4e67-8533-6ccb5c6b3bcc
      iscommand: true
      name: Reupload the sample
      script: Threat Grid|||threat-grid-upload-sample
      type: regular
      version: -1
    taskid: cfbde5d6-beed-4e67-8533-6ccb5c6b3bcc
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 1070\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1435,\n      \"width\": 1240,\n      \"x\": 50,\n      \"y\":\
  \ 50\n    }\n  }\n}"
