id: Test-Detonate URL - ThreatGrid
inputs: []
name: Test-Detonate URL - ThreatGrid
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '2'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 0e004152-20aa-40d4-8be1-2f11031e176a
      iscommand: false
      name: ''
      version: -1
    taskid: 0e004152-20aa-40d4-8be1-2f11031e176a
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '2':
    id: '2'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    note: false
    scriptarguments:
      FileName:
        simple: file-detonated-via-demisto
      Interval:
        simple: '1'
      Playbook:
        simple: default
      Private: {}
      Source: {}
      Tags: {}
      Timeout:
        simple: '15'
      URL:
        simple: www.google.com
      VM: {}
    separatecontext: true
    task:
      brand: ''
      id: 2ebf7435-ceb3-4644-8a0c-52da8d7f830f
      iscommand: false
      name: Detonate URL - ThreatGrid
      playbookName: Detonate URL - ThreatGrid
      type: playbook
      version: -1
    taskid: 2ebf7435-ceb3-4644-8a0c-52da8d7f830f
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 240,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
