id: NetWitness Endpoint Test
inputs: []
name: NetWitness Endpoint Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: c83f5d74-1218-49db-8ec6-22e7693c4a57
      iscommand: false
      name: ''
      version: -1
    taskid: c83f5d74-1218-49db-8ec6-22e7693c4a57
    type: start
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
      - '7'
      - '9'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: 072d28c0-3f93-442f-8145-756cff17c6f1
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 072d28c0-3f93-442f-8145-756cff17c6f1
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 195\n  }\n}"
  '11':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: NetWitness.Blacklist.Domains
          operator: isEqualString
          right:
            value:
              simple: www.example.com
      label: 'yes'
    id: '11'
    nexttasks:
      'yes':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 25a4eb7a-dc38-4857-8845-7e7ce71406a5
      iscommand: false
      name: Verify domain blacklisted
      type: condition
      version: -1
    taskid: 25a4eb7a-dc38-4857-8845-7e7ce71406a5
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 720\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
      - '4'
    note: false
    scriptarguments:
      includeMachineData:
        simple: 'yes'
      includeMachineIOCs:
        simple: 'yes'
      includeMachineModules:
        simple: 'yes'
      iocScoreGreaterThan: {}
      iocScoreLessThan: {}
      ipAdress: {}
      limit: {}
      macAddress: {}
      machineName:
        simple: NWE
    separatecontext: false
    task:
      brand: RSA NetWitness Endpoint
      id: 1d6b1343-e12c-4c46-8fa0-ae02cb15ceb3
      iscommand: true
      name: Get all machine data
      script: RSA NetWitness Endpoint|||netwitness-get-machines
      type: regular
      version: -1
    taskid: 1d6b1343-e12c-4c46-8fa0-ae02cb15ceb3
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      machineGUID:
        simple: ${NetWitness.Machines.MachineGUID}
      moduleID:
        simple: ${NetWitness.Modules.[0].ModuleID}
    separatecontext: false
    task:
      brand: RSA NetWitness Endpoint
      id: 6b8a6f41-31c8-4a55-8ab6-96cbfbc1eb6a
      iscommand: true
      name: Get module
      script: RSA NetWitness Endpoint|||netwitness-get-machine-module
      type: regular
      version: -1
    taskid: 6b8a6f41-31c8-4a55-8ab6-96cbfbc1eb6a
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '4':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: NetWitness.Machines.MachineGUID
          operator: isEqualString
          right:
            value:
              simple: ea946082-0563-c15e-8128-c5b6e8b2fea9
      label: verified
    id: '4'
    nexttasks:
      verified:
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 0cb6cdbc-d32c-492c-8a12-c610f44d0233
      iscommand: false
      name: Verify machine ID matches expected value
      type: condition
      version: -1
    taskid: 0cb6cdbc-d32c-492c-8a12-c610f44d0233
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 09c86891-ac16-458e-829d-5cadc2624c00
      iscommand: false
      name: 'successful validation '
      type: title
      version: -1
    taskid: 09c86891-ac16-458e-829d-5cadc2624c00
    type: title
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 895\n  }\n}"
  '6':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: NetWitness.Modules.FullPath
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: File.MD5
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: NetWitness.Modules.RiskScore
          operator: isExists
      label: output exists
    id: '6'
    nexttasks:
      output exists:
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: b4e1b1c9-2b05-4dde-8b08-e7152b474e21
      iscommand: false
      name: Sample Outputs - Verify Existence Only
      type: condition
      version: -1
    taskid: b4e1b1c9-2b05-4dde-8b08-e7152b474e21
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 720\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      ips:
        simple: 1.2.3.4
    separatecontext: false
    task:
      brand: RSA NetWitness Endpoint
      id: 4d4df12a-ff53-43d5-82f1-40a32e11446b
      iscommand: true
      name: BlackList IPs
      script: RSA NetWitness Endpoint|||netwitness-blacklist-ips
      type: regular
      version: -1
    taskid: 4d4df12a-ff53-43d5-82f1-40a32e11446b
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 545\n  }\n}"
  '8':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: NetWitness.Blacklist.IPs
          operator: isEqualString
          right:
            value:
              simple: 1.2.3.4
      label: 'yes'
    id: '8'
    nexttasks:
      'yes':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 79d03966-980c-434c-8fd8-15de576fa3e7
      iscommand: false
      name: Verify IP blacklisted
      type: condition
      version: -1
    taskid: 79d03966-980c-434c-8fd8-15de576fa3e7
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 720\n  }\n}"
  '9':
    id: '9'
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      domains:
        simple: www.example.com
    separatecontext: false
    task:
      brand: ''
      id: 2bac8bf3-219e-4972-80f7-02c9a452cf59
      iscommand: true
      name: Blacklist Domains
      script: '|||netwitness-blacklist-domains'
      type: regular
      version: -1
    taskid: 2bac8bf3-219e-4972-80f7-02c9a452cf59
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 545\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 910,\n      \"width\": 1670,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
