description: Test XFE commands via playbook.
id: XFE Test
inputs: []
name: XFE Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '3'
    separatecontext: false
    task:
      brand: ''
      id: bc16f811-666d-4675-8f31-91dd505b3f0b
      iscommand: false
      name: ''
      version: -1
    taskid: bc16f811-666d-4675-8f31-91dd505b3f0b
    type: start
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      long: {}
      threshold: {}
      url:
        simple: http://www.iuqerfsodp9ifjaposdfjhgosurijfaewrwergwea.com/
    separatecontext: false
    task:
      brand: XFE
      description: Check the given URL reputation
      id: 765e219e-d970-4e40-85e3-7a4d1a51737a
      iscommand: true
      name: url
      script: XFE|||url
      type: regular
      version: -1
    taskid: 765e219e-d970-4e40-85e3-7a4d1a51737a
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '10':
    id: '10'
    nexttasks:
      'no':
      - '12'
    scriptarguments:
      value:
        complex:
          accessor: Malicious
          filters:
          - - left:
                iscontext: true
                value:
                  simple: URL.Data
              operator: string.isEqual
              right:
                value:
                  simple: https://www.demisto.com
          root: URL
    separatecontext: false
    task:
      brand: ''
      id: 8078ae4b-e637-4230-86a6-6aa8d77fbef3
      iscommand: false
      name: Check No Malicious found
      scriptName: Exists
      type: condition
      version: -1
    taskid: 8078ae4b-e637-4230-86a6-6aa8d77fbef3
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 2295\n  }\n}"
  '12':
    id: '12'
    nexttasks:
      '#none#':
      - '13'
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: b5ffdbc1-840b-48ee-815a-944403c9487d
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: b5ffdbc1-840b-48ee-815a-944403c9487d
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2470\n  }\n}"
  '13':
    id: '13'
    nexttasks:
      '#none#':
      - '16'
    scriptarguments:
      limit:
        simple: '1'
    separatecontext: false
    task:
      brand: XFE
      description: Return the latest vulnerabilities found
      id: 71ed45de-c953-4854-8145-2a0efe6cea40
      iscommand: true
      name: cve-latest
      script: XFE|||cve-latest
      type: regular
      version: -1
    taskid: 71ed45de-c953-4854-8145-2a0efe6cea40
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2645\n  }\n}"
  '14':
    id: '14'
    scriptarguments:
      cveId:
        simple: ${CVE.ID}
    separatecontext: false
    task:
      brand: XFE
      description: Search for details about the given CVE
      id: e68ca2ce-3dc5-4239-8b7b-fc63eb1f04b7
      iscommand: true
      name: cve-search
      script: XFE|||cve-search
      type: regular
      version: -1
    taskid: e68ca2ce-3dc5-4239-8b7b-fc63eb1f04b7
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2995\n  }\n}"
  '16':
    id: '16'
    nexttasks:
      'yes':
      - '14'
    scriptarguments:
      array:
        simple: ${ArraySize}
      contextKey: {}
      expectedValue:
        simple: '3'
      fields: {}
      path:
        simple: CVE
      value:
        simple: ${CVE}
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 74889031-2b1d-42db-8cd6-4922e31a8a82
      iscommand: false
      name: VerifyContext
      scriptName: Exists
      type: condition
      version: -1
    taskid: 74889031-2b1d-42db-8cd6-4922e31a8a82
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2820\n  }\n}"
  '17':
    id: '17'
    nexttasks:
      'yes':
      - '4'
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        complex:
          accessor: Malicious.Vendor
          filters:
          - - left:
                iscontext: true
                value:
                  simple: URL.Malicious.Score
              operator: string.isEqual
              right:
                value:
                  simple: '10'
          root: URL
      right:
        simple: XFE
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: a347e578-be56-446f-8be4-3e0faa5236ab
      iscommand: false
      name: AreValuesEqual
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: a347e578-be56-446f-8be4-3e0faa5236ab
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 720\n  }\n}"
  '18':
    id: '18'
    nexttasks:
      '#none#':
      - '19'
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      id: 8f03df06-05d0-4d9e-8f64-c3dabc66a4da
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 8f03df06-05d0-4d9e-8f64-c3dabc66a4da
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1420\n  }\n}"
  '19':
    id: '19'
    nexttasks:
      '#none#':
      - '20'
      - '21'
      - '22'
    scriptarguments:
      file:
        simple: 37c919f28798a886ec7202cc39818b8ce641ae83
      long: {}
    separatecontext: false
    task:
      brand: XFE
      description: Check file reputation
      id: fcdfb086-afc6-4c93-871f-313e7ae60d66
      iscommand: true
      name: file
      script: XFE|||file
      type: regular
      version: -1
    taskid: fcdfb086-afc6-4c93-871f-313e7ae60d66
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1595\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      'yes':
      - '17'
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        complex:
          accessor: Score
          filters:
          - - left:
                iscontext: true
                value:
                  simple: DBotScore.Vendor
              operator: string.isEqual
              right:
                value:
                  simple: XFE
          - - left:
                iscontext: true
                value:
                  simple: DBotScore.Indicator
              operator: string.isEqual
              right:
                value:
                  simple: http://www.iuqerfsodp9ifjaposdfjhgosurijfaewrwergwea.com/
          root: DBotScore
      right:
        simple: '3'
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: eabfa049-5bba-412f-85c4-4e238d2f0da5
      iscommand: false
      name: AreValuesEqual
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: eabfa049-5bba-412f-85c4-4e238d2f0da5
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '20':
    id: '20'
    nexttasks:
      'yes':
      - '9'
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        complex:
          accessor: Malicious.Vendor
          filters:
          - - left:
                iscontext: true
                value:
                  simple: File.Malicious.Score
              operator: string.isEqual
              right:
                value:
                  simple: high
          root: File
      right:
        simple: XFE
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 6b3a1cc8-b924-4899-8043-27318dd66ce9
      iscommand: false
      name: AreValuesEqual
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: 6b3a1cc8-b924-4899-8043-27318dd66ce9
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '21':
    id: '21'
    nexttasks:
      'yes':
      - '9'
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        complex:
          accessor: Score
          filters:
          - - left:
                iscontext: true
                value:
                  simple: DBotScore.Indicator
              operator: string.isEqual
              right:
                value:
                  simple: 37c919f28798a886ec7202cc39818b8ce641ae83
          - - left:
                iscontext: true
                value:
                  simple: DBotScore.Vendor
              operator: string.isEqual
              right:
                value:
                  simple: XFE
          root: DBotScore
      right:
        simple: '3'
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 6d56941b-1503-4065-8d2a-f641a4dcad48
      iscommand: false
      name: AreValuesEqual
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: 6d56941b-1503-4065-8d2a-f641a4dcad48
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1770\n  }\n}"
  '22':
    id: '22'
    nexttasks:
      '#none#':
      - '9'
    scriptarguments:
      expectedValue:
        simple: 37c919f28798a886ec7202cc39818b8ce641ae83
      fields: {}
      path:
        simple: File.SHA1
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 66e7b4f6-bd51-4ef8-8b4c-426d651d472d
      iscommand: false
      name: VerifyContext
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 66e7b4f6-bd51-4ef8-8b4c-426d651d472d
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 1770\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '1'
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 93edb301-ce27-4b2f-8650-d3979b029afd
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 93edb301-ce27-4b2f-8650-d3979b029afd
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 195\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '5'
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: f6657238-012d-4f1f-846a-ec82b8c96005
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: f6657238-012d-4f1f-846a-ec82b8c96005
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 895\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '6'
    scriptarguments:
      ip:
        simple: 103.225.52.112
      long: {}
      threshold: {}
    separatecontext: false
    task:
      brand: XFE
      description: Check the given URL reputation
      id: 9b30665b-d93b-4617-82ba-9a5954bd2142
      iscommand: true
      name: ip
      script: XFE|||ip
      type: regular
      version: -1
    taskid: 9b30665b-d93b-4617-82ba-9a5954bd2142
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1070\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '18'
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        simple: ${IP.Malicious.Vendor}
      right:
        simple: XFE
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 2cc6d6eb-a168-4023-8506-94ccc243c442
      iscommand: false
      name: VerifyContext
      scriptName: AreValuesEqual
      type: regular
      version: -1
    taskid: 2cc6d6eb-a168-4023-8506-94ccc243c442
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1245\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '8'
      - '10'
    scriptarguments:
      domain:
        simple: https://www.demisto.com
      long: {}
      threshold: {}
    separatecontext: false
    task:
      brand: XFE
      description: Check domain reputation
      id: 2e44786a-9527-4e34-850d-6a6109204ee7
      iscommand: true
      name: domain
      script: XFE|||domain
      type: regular
      version: -1
    taskid: 2e44786a-9527-4e34-850d-6a6109204ee7
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2120\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      'yes':
      - '12'
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        complex:
          accessor: Score
          filters:
          - - left:
                iscontext: true
                value:
                  simple: DBotScore.Vendor
              operator: string.isEqual
              right:
                value:
                  simple: XFE
          - - left:
                iscontext: true
                value:
                  simple: DBotScore.Indicator
              operator: string.isEqual
              right:
                value:
                  simple: https://www.demisto.com
          root: DBotScore
      right:
        simple: '1'
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 44e05ef5-c22c-4c70-8870-56a17ec53509
      iscommand: false
      name: AreValuesEqual
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: 44e05ef5-c22c-4c70-8870-56a17ec53509
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 2295\n  }\n}"
  '9':
    id: '9'
    nexttasks:
      '#none#':
      - '7'
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 24419001-1034-4471-8c26-c9b85b85ad5f
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 24419001-1034-4471-8c26-c9b85b85ad5f
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1975\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"21_9_yes\": 0.31\n  },\n  \"paper\":\
  \ {\n    \"dimensions\": {\n      \"height\": 3040,\n      \"width\": 1240,\n  \
  \    \"x\": 50,\n      \"y\": 50\n    }\n  }\n}"
