id: Microsoft Graph Calendar - Test
inputs: []
name: Microsoft Graph Calendar - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: b3451d3e-498e-455a-8fa9-1db0719f4b2e
      iscommand: false
      name: ''
      version: -1
    taskid: b3451d3e-498e-455a-8fa9-1db0719f4b2e
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: e76bb969-477d-4685-8955-9928d50111df
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: e76bb969-477d-4685-8955-9928d50111df
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      next_link: {}
      order_by: {}
      top: {}
      user:
        simple: oren@demistodev.onmicrosoft.com
    separatecontext: false
    task:
      brand: ''
      description: Retrieves a list of user Calendar.
      id: 8aaf92f3-2613-430c-84e2-42c5f72ea1d9
      iscommand: true
      name: list Calendars
      script: '|||msgraph-calendar-list-calendars'
      type: regular
      version: -1
    taskid: 8aaf92f3-2613-430c-84e2-42c5f72ea1d9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      attendees:
        simple: oren@demistodev.onmicrosoft.com
      body:
        simple: This event was created by MSGraph integration
      calendar_id:
        complex:
          accessor: Calendar.Name
          root: MSGraphCalendar
          transformers:
          - operator: FirstArrayElement
      end:
        simple: 2022-12-11 17:30:00
      location:
        simple: Tel Aviv
      original_end_time_zone: {}
      original_start: {}
      original_start_time_zone: {}
      start:
        simple: 2022-12-11 17:00:00
      subject:
        simple: test - delete
      time_zone:
        simple: Asia/Jerusalem
      user:
        simple: oren@demistodev.onmicrosoft.com
    separatecontext: false
    task:
      brand: ''
      description: Creates a new event.
      id: 2225140f-0adc-458d-80c0-6b5a6806b036
      iscommand: true
      name: Create new Event
      script: '|||msgraph-calendar-create-event'
      type: regular
      version: -1
    taskid: 2225140f-0adc-458d-80c0-6b5a6806b036
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      event_id:
        simple: ${MSGraphCalendar.Event.ID}
      user:
        simple: oren@demistodev.onmicrosoft.com
    separatecontext: false
    task:
      brand: ''
      description: Retrieves an event by event ID.
      id: 3024de1b-9615-4e6c-8e36-cb14f824847a
      iscommand: true
      name: Get Event
      script: '|||msgraph-calendar-get-event'
      type: regular
      version: -1
    taskid: 3024de1b-9615-4e6c-8e36-cb14f824847a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      attendees: {}
      body: {}
      end: {}
      event_id:
        simple: ${MSGraphCalendar.Event.ID}
      location: {}
      original_end_time_zone: {}
      original_start: {}
      original_start_time_zone: {}
      start: {}
      subject:
        simple: updated
      time_zone: {}
      user:
        simple: oren@demistodev.onmicrosoft.com
    separatecontext: false
    task:
      brand: ''
      description: Updates an existing event.
      id: dd3d0e18-2477-493a-8c1a-df0fa51453ff
      iscommand: true
      name: Update Event
      script: '|||msgraph-calendar-update-event'
      type: regular
      version: -1
    taskid: dd3d0e18-2477-493a-8c1a-df0fa51453ff
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      calendar_id: {}
      filter_by:
        simple: startswith(subject,'test')
      next_link: {}
      order_by: {}
      top: {}
      user:
        simple: oren@demistodev.onmicrosoft.com
    separatecontext: false
    task:
      brand: Microsoft Graph Calendar
      description: Retrieves a list of Calendar's events.
      id: 97b4f8dc-44a6-476d-8740-5b57f8b993f6
      iscommand: true
      name: List Events
      script: Microsoft Graph Calendar|||msgraph-calendar-list-events
      type: regular
      version: -1
    taskid: 97b4f8dc-44a6-476d-8740-5b57f8b993f6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      event_id:
        simple: ${MSGraphCalendar.ID}
      user:
        simple: oren@demistodev.onmicrosoft.com
    separatecontext: false
    task:
      brand: ''
      description: Updates an existing event.
      id: e22e17e0-cdc5-4897-8888-730f10129e99
      iscommand: true
      name: Delete Event
      script: '|||msgraph-calendar-delete-event'
      type: regular
      version: -1
    taskid: e22e17e0-cdc5-4897-8888-730f10129e99
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: eae8a0a1-48f7-4d8d-831f-1c460d82dfe0
      iscommand: false
      name: END
      type: title
      version: -1
    taskid: eae8a0a1-48f7-4d8d-831f-1c460d82dfe0
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1435,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
