description: ''
id: AbuseIPDB PopulateIndicators Test
inputs: []
name: AbuseIPDB PopulateIndicators Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 0295597d-b28b-437b-8c9c-f81c3ca854e4
      iscommand: false
      name: ''
      version: -1
    taskid: 0295597d-b28b-437b-8c9c-f81c3ca854e4
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    note: false
    scriptarguments:
      days: {}
      limit:
        simple: '10'
      saveToContext:
        simple: 'true'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 00a03d74-204e-4af1-8684-cb04e2db32bf
      iscommand: false
      name: AbuseIPDBPopulateIndicators
      scriptName: AbuseIPDBPopulateIndicators
      type: regular
      version: -1
    taskid: 00a03d74-204e-4af1-8684-cb04e2db32bf
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 220\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 265,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\": 50\n\
  \    }\n  }\n}"
