description: 'Use the latest Qualys report to manage vulnerabilities.


  This playbook runs as a job, and by default creates incidents of type "Vulnerability"
  based on assets and vulnerabilities.

  The incidents are created from the latest version of the report determined by the
  report timestamp.

  You can define the minimum severity (minSeverity) that incidents are created for.

  Duplicate incidents are not created for the same asset ID and QID.


  This playbook is a part of a series of playbooks for Qualys vulnerability management
  and remediation.

  For this series of playbooks to run successfully, create a Job and do the following:

  1. Assign this playbook to the Job

  2. Enter the Qualys XML report name into the "Details" field

  3. Associate the "Vulnerability" type incident to the "Vulnerability Handling -
  Qualys" playbook.'
fromversion: 3.6.0
id: vulnerability_management_-_qualys_Job
inputs:
- description: 'The report title as it appears in Qualys.

    Has to be in XML format. '
  key: QualysReportTitle
  required: true
  value:
    complex:
      accessor: details
      root: incident
- description: The minimum Qualys severity (1 -5) to create incidents for
  key: MinSeverity
  required: true
  value:
    simple: '3'
name: Vulnerability Management - Qualys (Job)
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '10'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 44eb6f9d-29e2-449e-85fd-2077af1ff45e
      iscommand: false
      name: ''
      version: -1
    taskid: 44eb6f9d-29e2-449e-85fd-2077af1ff45e
    type: start
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 50\n  }\n}"
  '10':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: string.isEqual
                    right:
                      value:
                        simple: Qualys
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: string.isEqual
                    right:
                      value:
                        simple: active
                root: modules
          operator: general.isExists
      label: 'yes'
    id: '10'
    nexttasks:
      '#default#':
      - '14'
      'yes':
      - '15'
    separatecontext: false
    task:
      brand: ''
      description: Verify that there's a valid instance of Qualys enabled.
      id: 7bd9b687-d830-4ef7-8f2c-11430ace9299
      iscommand: false
      name: Is Qualys enabled?
      type: condition
      version: -1
    taskid: 7bd9b687-d830-4ef7-8f2c-11430ace9299
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 195\n  }\n}"
  '11':
    id: '11'
    nexttasks:
      '#none#':
      - '7'
    scriptarguments:
      id:
        complex:
          accessor: ID
          filters:
          - - left:
                iscontext: true
                value:
                  simple: QualysReport.Title
              operator: string.isEqual
              right:
                iscontext: true
                value:
                  simple: inputs.QualysReportTitle
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: QualysReport.Status.State
              operator: string.isEqual
              right:
                value:
                  simple: Finished
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: QualysReport.OutputFormat
              operator: string.isEqual
              right:
                value:
                  simple: XML
          root: QualysReport
          transformers:
          - args:
              index:
                value:
                  simple: '0'
            operator: general.atIndex
    separatecontext: false
    task:
      brand: Qualys
      description: Retrieve the report from Qualys.
      id: 4e17432e-44c3-41c2-8c3a-50b477ac0d64
      iscommand: true
      name: Get report
      script: Qualys|||qualys-report-fetch
      type: regular
      version: -1
    taskid: 4e17432e-44c3-41c2-8c3a-50b477ac0d64
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1040\n  }\n}"
  '12':
    id: '12'
    nexttasks:
      '#none#':
      - '3'
    scriptarguments:
      append: {}
      key:
        simple: QualysReport
      value:
        complex:
          accessor: Report
          root: Qualys
    separatecontext: false
    task:
      brand: ''
      description: 'Set the Qualys reports list into context. '
      id: 760d26bf-1cf0-453e-874d-6289febaf523
      iscommand: false
      name: Set context
      scriptName: Set
      type: regular
      version: -1
    taskid: 760d26bf-1cf0-453e-874d-6289febaf523
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 690\n  }\n}"
  '14':
    id: '14'
    nexttasks:
      '#none#':
      - '5'
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      id: {}
      importantfield: {}
      test2: {}
      timefield1: {}
    separatecontext: false
    task:
      brand: Builtin
      description: Close the investigation.
      id: f6e8fab3-d733-4383-8969-f1db2e0850b6
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: f6e8fab3-d733-4383-8969-f1db2e0850b6
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 279,\n    \"y\": 1535\n  }\n}"
  '15':
    id: '15'
    nexttasks:
      '#none#':
      - '2'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: d810fa86-61da-49c6-84c6-1216e66f77bb
      iscommand: false
      name: Get report from Qualys
      type: title
      version: -1
    taskid: d810fa86-61da-49c6-84c6-1216e66f77bb
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '12'
    scriptarguments:
      expires_before_datetime: {}
      id: {}
      state: {}
      user_login: {}
    separatecontext: false
    task:
      brand: Qualys
      description: Retrieve a list of all reports from Qualys. Can be filtered by
        the `expires_before_datetime` parameter.
      id: 1471cc73-16be-429c-8619-b07e7e7271ba
      iscommand: true
      name: Get Qualys reports list
      script: Qualys|||qualys-report-list
      type: regular
      version: -1
    taskid: 1471cc73-16be-429c-8619-b07e7e7271ba
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 515\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: ID
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: QualysReport.Title
                    operator: string.isEqual
                    right:
                      iscontext: true
                      value:
                        simple: inputs.QualysReportTitle
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: QualysReport.Status.State
                    operator: string.isEqual
                    right:
                      value:
                        simple: Finished
                - - left:
                      iscontext: true
                      value:
                        simple: QualysReport.OutputFormat
                    operator: string.isEqual
                    right:
                      value:
                        simple: XML
                root: QualysReport
          operator: general.isExists
      label: 'YES'
    id: '3'
    nexttasks:
      '#default#':
      - '5'
      'YES':
      - '11'
    separatecontext: false
    task:
      brand: ''
      description: Check if there's a Qualys report that matches the input report
        name and is in XML format.
      id: 4ae94d3c-f26b-4d09-89a7-7e2d087a5549
      iscommand: false
      name: Is there a valid report?
      type: condition
      version: -1
    taskid: 4ae94d3c-f26b-4d09-89a7-7e2d087a5549
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 865\n  }\n}"
  '5':
    id: '5'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 03b60980-2f8f-4dc6-830e-781a10150988
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 03b60980-2f8f-4dc6-830e-781a10150988
    type: title
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1710\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '8'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 73f17571-d171-4ba5-8cd0-d4b39cfd62ab
      iscommand: false
      name: Create incidents from the Qualys report
      type: title
      version: -1
    taskid: 73f17571-d171-4ba5-8cd0-d4b39cfd62ab
    type: title
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1215\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '14'
    scriptarguments:
      entryID:
        complex:
          accessor: EntryID
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: File.Info
              operator: string.isEqual
              right:
                value:
                  simple: application/xml
          root: File
      maxFileSize: {}
      minSeverity:
        simple: ${inputs.MinSeverity}
    separatecontext: false
    task:
      brand: ''
      description: 'Create incidents from a Qualys report (XML), based on the Qualys
        asset ID and vulnerability ID (QID).

        Duplicate incidents are not created for the same asset ID and QID.'
      id: a898c316-7a9a-4c01-8984-e02c4a572a17
      iscommand: false
      name: Create incidents from the Qualys report
      scriptName: QualysCreateIncidentFromReport
      type: regular
      version: -1
    taskid: a898c316-7a9a-4c01-8984-e02c4a572a17
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1360\n  }\n}"
tests:
- No test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1725,\n      \"width\": 609,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
