id: RedLockTest
inputs: []
name: RedLockTest
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 5d8ffb2e-b39d-461d-8f33-0a53f7d4c8d4
      iscommand: false
      name: ''
      version: -1
    taskid: 5d8ffb2e-b39d-461d-8f33-0a53f7d4c8d4
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 260,\n    \"y\": -160\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '37'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: fbfde3f9-74c2-46b4-8a91-fd30de35ac1e
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: fbfde3f9-74c2-46b4-8a91-fd30de35ac1e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 260,\n    \"y\": -35\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '31'
    note: false
    quietmode: 0
    scriptarguments:
      alert-id:
        simple: ${RedLockID}
      detailed: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: a890b4cf-1126-41e6-8c85-c250c1848349
      iscommand: true
      name: Get Most Recent Alert Details
      script: '|||redlock-get-alert-details'
      type: regular
      version: -1
    taskid: a890b4cf-1126-41e6-8c85-c250c1848349
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1070\n  }\n}"
  '13':
    conditions:
    - condition:
      - - left:
            value:
              simple: ${RedLockStatus}
          operator: isEqualString
          right:
            value:
              simple: open
      label: already open
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${RedLockStatus}
          operator: isEqualString
          right:
            value:
              simple: resolved
      label: resolved
    id: '13'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '23'
      already open:
      - '28'
      resolved:
      - '32'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: e75c9e62-38e2-4d71-8b05-0096699e6edf
      iscommand: false
      name: Change Alert Status
      type: condition
      version: -1
    taskid: e75c9e62-38e2-4d71-8b05-0096699e6edf
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1420\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '21'
    note: false
    quietmode: 0
    scriptarguments:
      alert-id: {}
      alert-rule-name: {}
      alert-status:
        simple: resolved
      cloud-account: {}
      cloud-region: {}
      cloud-type: {}
      policy-compliance-standard: {}
      policy-label: {}
      policy-name: {}
      policy-severity: {}
      policy-type: {}
      resource-id: {}
      resource-name: {}
      resource-type: {}
      risk-grade: {}
      time-range-date-from: {}
      time-range-date-to: {}
      time-range-unit:
        simple: day
      time-range-value:
        simple: '1'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Search alerts on the RedLock platform
      id: 48bb2da7-70c3-4e95-8494-27efb29699e0
      iscommand: true
      name: Retrieve All Alerts from Last 6 hours
      script: '|||redlock-search-alerts'
      type: regular
      version: -1
    taskid: 48bb2da7-70c3-4e95-8494-27efb29699e0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '21':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Alert
                root: Redlock
          operator: isExists
      label: 'yes'
    id: '21'
    ignoreworker: false
    nexttasks:
      'yes':
      - '24'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: fccd641e-b424-4519-809f-31f05a7d3913
      iscommand: false
      name: Check for response
      type: condition
      version: -1
    taskid: fccd641e-b424-4519-809f-31f05a7d3913
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 545\n  }\n}"
  '22':
    id: '22'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: c7b8e3fa-8f9c-435e-8d81-3900072604bb
      iscommand: false
      name: Test Completed
      type: title
      version: -1
    taskid: c7b8e3fa-8f9c-435e-8d81-3900072604bb
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 2820\n  }\n}"
  '23':
    id: '23'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '32'
    note: false
    quietmode: 0
    scriptarguments:
      alert-id:
        simple: ${RedLockID}
      alert-rule-name: {}
      alert-status: {}
      cloud-account: {}
      cloud-region: {}
      cloud-type: {}
      policy-compliance-standard: {}
      policy-label: {}
      policy-name: {}
      policy-severity: {}
      policy-type: {}
      resource-id: {}
      resource-name: {}
      resource-type: {}
      risk-grade: {}
      time-range-date-from: {}
      time-range-date-to: {}
      time-range-unit: {}
      time-range-value: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Re-open the alerts matching the given filter.  Must provide either
        policy IDs or alert IDs.
      id: 48c2bd10-b9e7-4dbe-8263-68180d86559f
      iscommand: true
      name: Open the Alert
      script: '|||redlock-reopen-alerts'
      type: regular
      version: -1
    taskid: 48c2bd10-b9e7-4dbe-8263-68180d86559f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -20,\n    \"y\": 1595\n  }\n}"
  '24':
    id: '24'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '25'
    note: false
    quietmode: 0
    scriptarguments:
      append: {}
      key:
        simple: RedLockID
      stringify: {}
      value:
        simple: ${Redlock.Alert.[0].ID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 3d398a52-a40c-4bf6-87de-0af29dfe7e73
      iscommand: false
      name: Store Recent Alert ID
      scriptName: Set
      type: regular
      version: -1
    taskid: 3d398a52-a40c-4bf6-87de-0af29dfe7e73
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 720\n  }\n}"
  '25':
    id: '25'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep:
        simple: RedLockID
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: 412b1117-95cb-4384-8ebe-63bbef697511
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 412b1117-95cb-4384-8ebe-63bbef697511
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 895\n  }\n}"
  '28':
    id: '28'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '32'
    note: false
    quietmode: 0
    scriptarguments:
      alert-id:
        simple: ${RedLockID}
      alert-rule-name: {}
      alert-status: {}
      cloud-account: {}
      cloud-region: {}
      cloud-type: {}
      dismissal-note:
        simple: Testing
      policy-compliance-standard: {}
      policy-id: {}
      policy-label: {}
      policy-name: {}
      policy-severity: {}
      policy-type: {}
      resource-id: {}
      resource-name: {}
      resource-type: {}
      risk-grade: {}
      time-range-date-from: {}
      time-range-date-to: {}
      time-range-unit: {}
      time-range-value: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Dismiss the alerts matching the given filter. Must provide either
        policy IDs or alert IDs.
      id: bbda63e8-3913-46ae-8327-364bfd699e79
      iscommand: true
      name: Dismiss Alert
      script: '|||redlock-dismiss-alerts'
      type: regular
      version: -1
    taskid: bbda63e8-3913-46ae-8327-364bfd699e79
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 560,\n    \"y\": 1595\n  }\n}"
  '29':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Alert.Status}
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: ${Redlock.Alert.ID}
                    operator: isEqualString
                    right:
                      iscontext: true
                      value:
                        simple: ${RedlockID}
                root: ${Redlock
          operator: isNotEqualString
          right:
            iscontext: true
            value:
              simple: ${RedLockStatus}
      label: 'Yes'
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${RedLockStatus}
          operator: isEqualString
          right:
            value:
              simple: resolved
      label: resolved
    id: '29'
    ignoreworker: false
    nexttasks:
      'Yes':
      - '34'
      resolved:
      - '36'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: d2fe7668-df2d-4b08-888b-6e6886a81c90
      iscommand: false
      name: Verify Alert Status Change
      type: condition
      version: -1
    taskid: d2fe7668-df2d-4b08-888b-6e6886a81c90
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 260,\n    \"y\": 2120\n  }\n}"
  '30':
    id: '30'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '36'
    note: false
    quietmode: 0
    scriptarguments:
      alert-id:
        simple: ${RedLockID}
      alert-rule-name: {}
      alert-status:
        simple: open
      cloud-account: {}
      cloud-region: {}
      cloud-type: {}
      policy-compliance-standard: {}
      policy-label: {}
      policy-name: {}
      policy-severity: {}
      policy-type: {}
      resource-id: {}
      resource-name: {}
      resource-type: {}
      risk-grade: {}
      time-range-date-from: {}
      time-range-date-to: {}
      time-range-unit: {}
      time-range-value: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Re-open the alerts matching the given filter.  Must provide either
        policy IDs or alert IDs.
      id: 8f4ef273-dab0-4fe5-84de-5a1a7d5beb61
      iscommand: true
      name: Return alert To Open State
      script: '|||redlock-reopen-alerts'
      type: regular
      version: -1
    taskid: 8f4ef273-dab0-4fe5-84de-5a1a7d5beb61
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 610,\n    \"y\": 2470\n  }\n}"
  '31':
    id: '31'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    quietmode: 0
    scriptarguments:
      append: {}
      key:
        simple: RedLockStatus
      stringify: {}
      value:
        complex:
          accessor: Alert.Status
          filters:
          - - left:
                iscontext: true
                value:
                  simple: Redlock.Alert.ID
              operator: isEqualString
              right:
                iscontext: true
                value:
                  simple: RedLockID
          root: Redlock
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 43c4c79c-d5f4-4502-86ce-ded9cdd3e550
      iscommand: false
      name: Store Recent Alert Status
      scriptName: Set
      type: regular
      version: -1
    taskid: 43c4c79c-d5f4-4502-86ce-ded9cdd3e550
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1245\n  }\n}"
  '32':
    id: '32'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '33'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep:
        simple: RedLockStatus,RedLockID
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: 1d482a77-d906-4e5c-86de-ff23076f3fbb
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 1d482a77-d906-4e5c-86de-ff23076f3fbb
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1770\n  }\n}"
  '33':
    id: '33'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '29'
    note: false
    quietmode: 0
    scriptarguments:
      alert-id:
        simple: ${RedLockID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Get remediation details for a given alert
      id: 900b5aef-bc7b-4904-8b3a-2876f4ad7f0b
      iscommand: true
      name: Get Alert Details
      script: '|||redlock-get-remediation-details'
      type: regular
      version: -1
    taskid: 900b5aef-bc7b-4904-8b3a-2876f4ad7f0b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1945\n  }\n}"
  '34':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${RedLockStatus}
          operator: isEqualString
          right:
            value:
              simple: open
      label: open
    id: '34'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '35'
      open:
      - '30'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: aaf33fc3-ac3e-459e-8fac-098b93bf8503
      iscommand: false
      name: Return to original state
      type: condition
      version: -1
    taskid: aaf33fc3-ac3e-459e-8fac-098b93bf8503
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 260,\n    \"y\": 2295\n  }\n}"
  '35':
    id: '35'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '36'
    note: false
    quietmode: 0
    scriptarguments:
      alert-id:
        simple: ${RedLockID}
      alert-rule-name: {}
      alert-status:
        simple: dismissed
      cloud-account: {}
      cloud-region: {}
      cloud-type: {}
      dismissal-note:
        simple: Testing
      policy-compliance-standard: {}
      policy-id: {}
      policy-label: {}
      policy-name: {}
      policy-severity: {}
      policy-type: {}
      resource-id: {}
      resource-name: {}
      resource-type: {}
      risk-grade: {}
      time-range-date-from: {}
      time-range-date-to: {}
      time-range-unit: {}
      time-range-value: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Dismiss the alerts matching the given filter. Must provide either
        policy IDs or alert IDs.
      id: 9f3d69c7-426a-48de-843f-17d10e35bea6
      iscommand: true
      name: Return alert To Dismissed State
      script: '|||redlock-dismiss-alerts'
      type: regular
      version: -1
    taskid: 9f3d69c7-426a-48de-843f-17d10e35bea6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -70,\n    \"y\": 2470\n  }\n}"
  '36':
    id: '36'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '22'
    note: false
    quietmode: 0
    scriptarguments:
      alert-id:
        simple: ${RedLockID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Get remediation details for a given alert
      id: b89a65b8-9cac-42c2-8d9c-82c14c7b98db
      iscommand: true
      name: Get Remediation Details
      script: '|||redlock-get-remediation-details'
      type: regular
      version: -1
    taskid: b89a65b8-9cac-42c2-8d9c-82c14c7b98db
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 2645\n  }\n}"
  '37':
    id: '37'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: List the acceptable filters and values for alerts
      id: b71629af-3593-473a-8ae2-e397e57a99ce
      iscommand: true
      name: List Alert Filters
      script: '|||redlock-list-alert-filters'
      type: regular
      version: -1
    taskid: b71629af-3593-473a-8ae2-e397e57a99ce
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 260,\n    \"y\": 150\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"13_28_already open\": 0.57,\n    \"13_32_resolved\"\
  : 0.48,\n    \"21_24_yes\": 0.53,\n    \"29_34_Yes\": 0.58,\n    \"29_36_resolved\"\
  : 0.85,\n    \"34_30_open\": 0.59,\n    \"34_35_#default#\": 0.77\n  },\n  \"paper\"\
  : {\n    \"dimensions\": {\n      \"height\": 3045,\n      \"width\": 1060,\n  \
  \    \"x\": -70,\n      \"y\": -160\n    }\n  }\n}"
