description: The Palo Alto Networks Cortex Test playbook tests Cortex Data Lake main
  usecases
id: Cortex Data Lake Test
inputs: []
name: Cortex Data Lake Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 63da380f-41d4-4b8a-8b88-e660a35df4cd
      iscommand: false
      name: ''
      version: -1
    taskid: 63da380f-41d4-4b8a-8b88-e660a35df4cd
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      limit: {}
      query:
        simple: SELECT * FROM `firewall.traffic` limit 10
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cortex Data Lake
      description: Runs a query on the Cortex logging service.
      id: 120f3088-1651-40d1-8d6d-4a6faa57b38d
      iscommand: true
      name: Query Logs
      script: Cortex Data Lake|||cdl-query-logs
      type: regular
      version: -1
    taskid: 120f3088-1651-40d1-8d6d-4a6faa57b38d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '10':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Logging.Traffic.SourceIP
                root: CDL
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Logging.Traffic.DestinationIP
                root: CDL
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Logging.Traffic.RuleMatched
                root: CDL
          operator: isExists
      label: 'yes'
    id: '10'
    ignoreworker: false
    nexttasks:
      'yes':
      - '5'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Verify Query Traffic Logs Outputs
      id: 042a7bbf-c090-49fc-83fc-3cfbf9e7b605
      iscommand: false
      name: Verify Query Traffic Logs Outputs
      type: condition
      version: -1
    taskid: 042a7bbf-c090-49fc-83fc-3cfbf9e7b605
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      action: {}
      dest_ip: {}
      dest_port: {}
      end_time:
        simple: '2020-03-25 10:01:13'
      fields: {}
      file_name: {}
      file_sha_256: {}
      from_zone: {}
      limit: {}
      query: {}
      rule_matched: {}
      source_ip: {}
      source_port: {}
      start_time:
        simple: '2019-11-06 09:59:39'
      time_range: {}
      to_zone: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Searches the Cortex panw.threat table, which is the threat logs
        table for PAN-OS/Panorama.
      id: c7bde997-bbb9-4c2d-8042-36aec730c77e
      iscommand: true
      name: cdl-query-threat-logs
      script: '|||cdl-query-threat-logs'
      type: regular
      version: -1
    taskid: c7bde997-bbb9-4c2d-8042-36aec730c77e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '2':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: CDL.Logging.Action
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: CDL.Logging.App
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: CDL.Logging.DestinationIP
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: CDL.Logging.RuleMatched
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: CDL.Logging.SourceIP
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: CDL.Logging.SourceLocation
          operator: isExists
      label: 'yes'
    id: '2'
    ignoreworker: false
    nexttasks:
      'yes':
      - '11'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Verify Query Logs Outputs
      id: 9c3b712e-9b16-4bbd-8e2f-8bca5e9327cb
      iscommand: false
      name: Verify Query Logs Outputs
      type: condition
      version: -1
    taskid: 9c3b712e-9b16-4bbd-8e2f-8bca5e9327cb
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Query Cortex Logging service according to pre-set queries
      id: d5daefa7-efae-4837-8237-f62e278be936
      iscommand: false
      name: Success
      type: title
      version: -1
    taskid: d5daefa7-efae-4837-8237-f62e278be936
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      add_to_context: {}
      brand_name:
        simple: Cortex Data Lake
      error_msg_in_incident:
        simple: 'Error:'
      expect_data: {}
      instance_name: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Execute FetchIncident for a given instance
      id: c447ccb2-c846-4bea-8c4f-8ca8ca51b32b
      iscommand: false
      name: Fetch events
      scriptName: FetchFromInstance
      type: regular
      version: -1
    taskid: c447ccb2-c846-4bea-8c4f-8ca8ca51b32b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: 6326099c-cab1-4729-88b5-8692612aed85
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 6326099c-cab1-4729-88b5-8692612aed85
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '8':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Logging.Threat.SourceIP
                root: CDL
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Logging.Threat.DestinationIP
                root: CDL
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Logging.Threat.RuleMatched
                root: CDL
          operator: isExists
      label: 'yes'
    id: '8'
    ignoreworker: false
    nexttasks:
      'yes':
      - '9'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Verify Query Threat Logs Outputs
      id: 34e02456-9d76-41ab-8a96-9d3adbbea838
      iscommand: false
      name: Verify Query Threat Logs Outputs
      type: condition
      version: -1
    taskid: 34e02456-9d76-41ab-8a96-9d3adbbea838
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    quietmode: 0
    scriptarguments:
      action: {}
      dest_ip: {}
      dest_port: {}
      end_time:
        simple: '2020-03-25 10:01:13'
      fields: {}
      from_zone: {}
      limit: {}
      query: {}
      rule: {}
      source_ip: {}
      source_port: {}
      start_time:
        simple: '2019-11-06 09:59:39'
      time_range: {}
      to_zone: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cortex Data Lake
      description: Searches the Cortex firewall.traffic table. Traffic logs contain
        entries for the end of each network session
      id: 40b34124-63f2-4514-8843-ae952d321f37
      iscommand: true
      name: cdl-query-traffic-logs
      script: Cortex Data Lake|||cdl-query-traffic-logs
      type: regular
      version: -1
    taskid: 40b34124-63f2-4514-8843-ae952d321f37
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1610,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
