description: Test playbook for Trend Micro DDA integration, including the detonate
  File/URL playbooks.
id: Test Playbook TrendMicroDDA
inputs: []
name: Test Playbook TrendMicroDDA
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '17'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: cac5e409-9f5f-4ee1-8f36-70819f33b627
      iscommand: false
      name: ''
      version: -1
    taskid: cac5e409-9f5f-4ee1-8f36-70819f33b627
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '11':
    id: '11'
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      interval_end:
        simple: 2008-11-22 19:53:59
      interval_start:
        simple: 2008-11-22 19:53:42
      interval_type: {}
    separatecontext: false
    task:
      brand: Trend Micro Deep Discovery Analyzer
      id: b536bfcb-65c4-41ea-80ae-f0266b3ec006
      iscommand: true
      name: get-sample-list
      script: Trend Micro Deep Discovery Analyzer|||trendmicro-dda-get-sample-list
      type: regular
      version: -1
    taskid: b536bfcb-65c4-41ea-80ae-f0266b3ec006
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 515\n  }\n}"
  '12':
    id: '12'
    nexttasks:
      '#none#':
      - '13'
    note: false
    scriptarguments:
      data:
        simple: qwerty6
      entryId: {}
      filename:
        simple: test_file.txt
    separatecontext: false
    task:
      brand: ''
      id: f83a1490-70bb-4ec9-8bf2-93096b23cd3b
      iscommand: false
      name: FileCreateAndUpload
      scriptName: FileCreateAndUpload
      type: regular
      version: -1
    taskid: f83a1490-70bb-4ec9-8bf2-93096b23cd3b
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 690\n  }\n}"
  '13':
    id: '13'
    nexttasks:
      '#none#':
      - '19'
    note: false
    scriptarguments:
      EntryID:
        simple: ${File.EntryID}
      entryID:
        simple: ${File.EntryID}
    separatecontext: false
    task:
      brand: Trend Micro Deep Discovery Analyzer
      id: 25336071-2e11-45aa-866e-e6b7378a7bd1
      iscommand: true
      name: upload-file
      script: Trend Micro Deep Discovery Analyzer|||trendmicro-dda-upload-file
      type: regular
      version: -1
    taskid: 25336071-2e11-45aa-866e-e6b7378a7bd1
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 865\n  }\n}"
  '14':
    id: '14'
    nexttasks:
      'yes':
      - '20'
    note: false
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        complex:
          accessor: Submission.RiskLevel
          root: TrendMicroDDA
      right:
        simple: '-1'
    separatecontext: false
    task:
      brand: ''
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: 2e89f1f0-ccde-416f-8175-1b25c774f6a3
      iscommand: false
      name: get-report AreValuesEqual
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: 2e89f1f0-ccde-416f-8175-1b25c774f6a3
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1215\n  }\n}"
  '15':
    id: '15'
    nexttasks:
      '#none#':
      - '16'
    note: false
    scriptarguments:
      archive_name: {}
      encrypted: {}
      filename: {}
      sample_sha1:
        simple: 571AD0F7D5056F68D0F2B795EAF4618C082A89D9
      sha1:
        simple: 571ad0f7d5056f68d0f2b795eaf4618c082a89d9
      type: {}
      type_origin: {}
    separatecontext: false
    task:
      brand: Trend Micro Deep Discovery Analyzer
      id: 4183fa35-576e-41b2-8d2a-9fd0ad62728b
      iscommand: true
      name: get-sample
      script: Trend Micro Deep Discovery Analyzer|||trendmicro-dda-get-sample
      type: regular
      version: -1
    taskid: 4183fa35-576e-41b2-8d2a-9fd0ad62728b
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1565\n  }\n}"
  '16':
    id: '16'
    nexttasks:
      '#none#':
      - '27'
      - '24'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
      keysToKeep: {}
    separatecontext: false
    task:
      brand: ''
      id: c5382a0a-70ba-46ba-8ea1-cee235e5ff55
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: c5382a0a-70ba-46ba-8ea1-cee235e5ff55
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1822\n  }\n}"
  '17':
    id: '17'
    nexttasks:
      '#none#':
      - '25'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 0f31cae0-ecc0-4009-8938-a65d9caf1192
      iscommand: false
      name: Test Playbook TrendMicroADD
      type: title
      version: -1
    taskid: 0f31cae0-ecc0-4009-8938-a65d9caf1192
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '18':
    id: '18'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 6b323d98-d937-45c3-8eb3-975db9f29e01
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 6b323d98-d937-45c3-8eb3-975db9f29e01
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 2440\n  }\n}"
  '19':
    id: '19'
    nexttasks:
      '#none#':
      - '14'
    note: false
    scriptarguments:
      sha1:
        simple: 571ad0f7d5056f68d0f2b795eaf4618c082a89d9
      threshold: {}
      verbose: {}
    separatecontext: false
    task:
      brand: Trend Micro Deep Discovery Analyzer
      id: c6b92a06-2180-48f0-8894-f925ec986fbb
      iscommand: true
      name: get-report
      script: Trend Micro Deep Discovery Analyzer|||trendmicro-dda-get-report
      type: regular
      version: -1
    taskid: c6b92a06-2180-48f0-8894-f925ec986fbb
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1040\n  }\n}"
  '20':
    id: '20'
    nexttasks:
      '#none#':
      - '15'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
      keysToKeep: {}
    separatecontext: false
    task:
      brand: ''
      id: 8f1f6e95-3a23-4793-80b1-4e7ec2d31757
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 8f1f6e95-3a23-4793-80b1-4e7ec2d31757
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1390\n  }\n}"
  '24':
    id: '24'
    nexttasks:
      '#none#':
      - '26'
    note: false
    scriptarguments:
      data:
        simple: "Ooh\nYou can dance\nYou can jive\nHaving the time of your life\n\
          Ooh, see that girl\nWatch that scene\nDig in the dancing queen\nFriday night\
          \ and the lights are low\nLooking out for a place to go\nWhere they play\
          \ the right music\nGetting in the swing\nYou come to look for a king\nAnybody\
          \ could be that guy\nNight is young and the music's high\nWith a bit of\
          \ rock music\nEverything is fine\nYou're in the mood for a dance\nAnd when\
          \ you get the chance\nYou are the dancing queen\nYoung and sweet\nOnly seventeen\n\
          Dancing queen\nFeel the beat from the tambourine, oh yeah\nYou can dance\n\
          You can jive\nHaving the time of your life\nOoh, see that girl\nWatch that\
          \ scene\nDig in the dancing queen\nYou're a teaser, you turn 'em on\nLeave\
          \ 'em burning and then you're gone\nLooking out\u2026"
      entryId: {}
      filename:
        simple: abba.exe
    separatecontext: false
    task:
      brand: ''
      description: 'Will create a file (using the given data input or entry ID) and
        upload it to current investigation war room.

        '
      id: 07f5d0a6-616c-41ae-886b-ac74353656f2
      iscommand: false
      name: FileCreateAndUpload
      scriptName: FileCreateAndUpload
      type: regular
      version: -1
    taskid: 07f5d0a6-616c-41ae-886b-ac74353656f2
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2090\n  }\n}"
  '25':
    id: '25'
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
      keysToKeep: {}
    separatecontext: false
    task:
      brand: ''
      id: c98e55b2-5370-4e5d-870f-3fa2eefc5b0b
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: c98e55b2-5370-4e5d-870f-3fa2eefc5b0b
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 340\n  }\n}"
  '26':
    id: '26'
    nexttasks:
      '#none#':
      - '18'
    note: false
    separatecontext: true
    task:
      brand: ''
      id: 86700a5d-f744-402d-8201-69812002210e
      iscommand: false
      name: Detonate File - Trend Micro Deep Discovery Analyzer
      playbookName: Detonate File - Trend Micro Deep Discovery Analyzer Beta
      type: playbook
      version: -1
    taskid: 86700a5d-f744-402d-8201-69812002210e
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2265\n  }\n}"
  '27':
    id: '27'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '18'
    note: false
    scriptarguments:
      URL:
        simple: https://github.com
      interval:
        simple: '1'
      timeput:
        simple: '15'
    separatecontext: true
    task:
      brand: ''
      id: 927cfb35-eb2b-4d84-85cf-1d21a0cf855d
      iscommand: false
      name: Detonate URL - Trend Micro Deep Discovery Analyzer
      playbookName: Detonate URL - Trend Micro Deep Discovery Analyzer Beta
      type: playbook
      version: -1
    taskid: 927cfb35-eb2b-4d84-85cf-1d21a0cf855d
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2265\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2455,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
