id: awake_security_test_pb
inputs: []
name: awake_security_test_pb
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: e1bac280-aa77-403e-8469-70eb46aa4f0e
      iscommand: false
      name: ''
      version: -1
    taskid: e1bac280-aa77-403e-8469-70eb46aa4f0e
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1750\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    quietmode: 0
    scriptarguments:
      deviceName: {}
      domainName: {}
      endTime:
        simple: '2020-06-18T07:30:00Z'
      ipAddress: {}
      protocol: {}
      queryExpression: {}
      startTime:
        simple: '2018-07-18T07:00:00Z'
      tag: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Query domains
      id: 1c86f0e7-fe0e-48c4-814a-003b81787600
      iscommand: true
      name: awake-query-domains
      script: '|||awake-query-domains'
      type: regular
      version: -1
    taskid: 1c86f0e7-fe0e-48c4-814a-003b81787600
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2090\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 6214ad23-19a9-456d-8a52-d867ef944d7a
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 6214ad23-19a9-456d-8a52-d867ef944d7a
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3140\n  }\n}"
  '13':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Domains.name
                root: AwakeSecurity
          operator: containsString
          right:
            value:
              simple: amazonaws.com
      label: 'yes'
    id: '13'
    ignoreworker: false
    nexttasks:
      'yes':
      - '15'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: dc3aa3b2-32bc-4f48-806f-de601076f7b5
      iscommand: false
      name: Test awake-query-domains
      type: condition
      version: -1
    taskid: dc3aa3b2-32bc-4f48-806f-de601076f7b5
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2265\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: ec71359f-7998-41f3-82dc-b5dd87eb77b6
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: ec71359f-7998-41f3-82dc-b5dd87eb77b6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1910\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    quietmode: 0
    scriptarguments:
      deviceName: {}
      domainName: {}
      endTime:
        simple: '2020-06-01T00:00:00Z'
      ipAddress: {}
      protocol: {}
      queryExpression: {}
      startTime:
        simple: '2020-01-01T00:00:00Z'
      tag: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Query activities in Awake Security
      id: 43fabfb9-0664-490e-8824-4c43974931fa
      iscommand: true
      name: awake-query-activities
      script: '|||awake-query-activities'
      type: regular
      version: -1
    taskid: 43fabfb9-0664-490e-8824-4c43974931fa
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2440\n  }\n}"
  '16':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Activities.sourceIP
                root: AwakeSecurity
          operator: isNotEmpty
      label: 'yes'
    id: '16'
    ignoreworker: false
    nexttasks:
      'yes':
      - '17'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: ea57b365-54fc-445e-846b-179c8a84d482
      iscommand: false
      name: Test awake-query-activities
      type: condition
      version: -1
    taskid: ea57b365-54fc-445e-846b-179c8a84d482
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2615\n  }\n}"
  '17':
    id: '17'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '18'
    note: false
    quietmode: 0
    scriptarguments:
      deviceName: {}
      domainName: {}
      endTime:
        simple: '2020-07-18T07:30:00Z'
      ipAddress: {}
      protocol: {}
      queryExpression: {}
      startTime:
        simple: '2018-07-18T07:00:00Z'
      tag: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Query devices
      id: c1202631-311d-4130-8d90-d7ba643218f7
      iscommand: true
      name: awake-query-devices
      script: '|||awake-query-devices'
      type: regular
      version: -1
    taskid: c1202631-311d-4130-8d90-d7ba643218f7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2790\n  }\n}"
  '18':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Devices.deviceName
                root: AwakeSecurity
          operator: isNotEmpty
      label: 'yes'
    id: '18'
    ignoreworker: false
    nexttasks:
      'yes':
      - '12'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 3895371c-6c74-4598-8caa-ea30b4eed1e3
      iscommand: false
      name: Test awake-query-devices
      type: condition
      version: -1
    taskid: 3895371c-6c74-4598-8caa-ea30b4eed1e3
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2965\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"13_15_yes\": 0.89,\n    \"16_17_yes\"\
  : 0.87,\n    \"18_12_yes\": 0.81\n  },\n  \"paper\": {\n    \"dimensions\": {\n\
  \      \"height\": 1455,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\":\
  \ 1750\n    }\n  }\n}"
