description: 'Returns a file sample to the war-room from a path on an endpoint using
  Demisto Dissolvable Agent (D2)


  Input:

  * Credentials - credentials to use when trying to deploy Demisto Dissolvable Agent
  (D2)  (default: Admin)

  * ${Endpoint.Hostname} - deploy agent on target endpoint

  * ${File.Path} - file''s path to collect'
fromversion: 3.5.0
id: get_file_sample_from_path_-_d2
inputs:
- description: Name of the credential set from Demisto Settings -> Integrations ->
    Credentials
  key: Credentials
  required: false
  value:
    simple: Admin
- description: Endpoint hostname
  key: Hostname
  required: false
  value:
    simple: ${Endpoint.Hostname}
- description: The file path
  key: Path
  required: false
  value:
    simple: ${File.Path}
name: Get File Sample From Path - D2
outputs:
- contextPath: File
  description: The file to sample.
  type: unknown
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '7'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 62c65b41-e6f2-42d5-8abf-a3c971ae42b0
      iscommand: false
      name: ''
      version: -1
    taskid: 62c65b41-e6f2-42d5-8abf-a3c971ae42b0
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '11':
    id: '11'
    nexttasks:
      '#none#':
      - '12'
    scriptarguments:
      filepath:
        simple: ${inputs.Path}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 9f3aab69-b584-4929-815c-0579eb307807
      iscommand: false
      name: d2 agent - Collect file from endpoint
      scriptName: FetchFileD2
      type: regular
      version: -1
    taskid: 9f3aab69-b584-4929-815c-0579eb307807
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 545\n  }\n}"
  '12':
    id: '12'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 642cf7ac-e922-4379-8656-55c1eb4de929
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 642cf7ac-e922-4379-8656-55c1eb4de929
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '3':
    continueonerror: true
    id: '3'
    nexttasks:
      '#none#':
      - '11'
    scriptarguments:
      arch: {}
      credentialSet:
        simple: ${inputs.Credentials}
      dmbPort: {}
      host:
        simple: ${inputs.Hostname}
      name:
        simple: ${inputs.Hostname}
      os:
        simple: windows
      password: {}
      sshPort: {}
      username: {}
      workgroup: {}
    separatecontext: false
    task:
      brand: ''
      description: Add the relevant endpoint to the System
      id: a5a0b6b9-bd4d-42e6-8e96-5a5daeb0d5a5
      iscommand: false
      name: Add the endpoint as a System to this incident
      scriptName: IncidentAddSystem
      type: regular
      version: -1
    taskid: a5a0b6b9-bd4d-42e6-8e96-5a5daeb0d5a5
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 370\n  }\n}"
  '7':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Hostname
          operator: general.isExists
      - - left:
            iscontext: true
            value:
              simple: inputs.Path
          operator: general.isExists
      label: 'yes'
    id: '7'
    nexttasks:
      '#default#':
      - '12'
      'yes':
      - '3'
    scriptarguments:
      value:
        simple: ${Endpoint.Hostname}
    separatecontext: false
    task:
      brand: ''
      description: Check if there is hostname and file path to get.
      id: ba4872a3-3460-470f-81cd-14afaacd29d8
      iscommand: false
      name: Does Hostname and filepath exists?
      type: condition
      version: -1
    taskid: ba4872a3-3460-470f-81cd-14afaacd29d8
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
tests:
- get_file_sample_from_path_-_d2_-_test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 735,\n      \"width\": 492.5,\n      \"x\": 50,\n      \"y\":\
  \ 50\n    }\n  }\n}"
