id: Prisma_Access_Egress_IP_Feed-Test
inputs: []
name: Prisma_Access_Egress_IP_Feed-Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 4d23ce19-3cad-43e9-8aa1-e3781736fbeb
      iscommand: false
      name: ''
      version: -1
    taskid: 4d23ce19-3cad-43e9-8aa1-e3781736fbeb
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: f886275c-6865-4e76-8bcd-65beb7ec5dd7
      iscommand: true
      name: DeleteContext
      script: DeleteContext
      type: regular
      version: -1
    taskid: f886275c-6865-4e76-8bcd-65beb7ec5dd7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 200\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      limit:
        simple: '5'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 99f1bdea-4cac-4fcf-8b6e-a2536b85b0c7
      iscommand: true
      name: prisma-access-get-indicators
      script: '|||prisma-access-get-indicators'
      type: regular
      version: -1
    taskid: 99f1bdea-4cac-4fcf-8b6e-a2536b85b0c7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 400\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: PrismaAccess.Egress.IP.Address
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: PrismaAccess.Egress.IP.Zone
          operator: isNotEmpty
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 7a824f3a-cb51-43e4-8ccb-550c4f2db7b4
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 7a824f3a-cb51-43e4-8ccb-550c4f2db7b4
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 600\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 6852624e-367d-4c01-8eda-f205c577c359
      iscommand: false
      name: Test Done
      type: title
      version: -1
    taskid: 6852624e-367d-4c01-8eda-f205c577c359
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 800\n  }\n}"
tests:
- No tests
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 815,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
