id: Gmail Convert Html Test
inputs: []
name: Gmail Convert Html Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: c9203936-01e5-4282-838b-106bd31cbdd3
      iscommand: false
      name: ''
      version: -1
    taskid: c9203936-01e5-4282-838b-106bd31cbdd3
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: b6ec96d3-467f-4175-84b3-1cde56a868ab
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: b6ec96d3-467f-4175-84b3-1cde56a868ab
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 230\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      after: {}
      before: {}
      fields: {}
      filename: {}
      from:
        simple: kayak
      has-attachments: {}
      in: {}
      include-spam-trash: {}
      labels-ids: {}
      max-results: {}
      page-token: {}
      query: {}
      subject: {}
      to: {}
      user-id:
        simple: shai@demistodev.com
    separatecontext: false
    task:
      brand: ''
      description: Search for messages in the user's mailbox.
      id: c30e0f88-e32c-442a-88c1-c5225b323f3f
      iscommand: true
      name: gmail-search for html email
      script: '|||gmail-search'
      type: regular
      version: -1
    taskid: c30e0f88-e32c-442a-88c1-c5225b323f3f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 410\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Body
                root: Gmail
                transformers:
                - operator: toLowerCase
          operator: notContainsString
          right:
            value:
              simple: <div>
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Body
                root: Gmail
                transformers:
                - operator: toLowerCase
          operator: notContainsString
          right:
            value:
              simple: <span>
      - - left:
            iscontext: true
            value:
              simple: Gmail.Format
          operator: isEqualString
          right:
            value:
              simple: text/html
      label: 'yes'
    id: '3'
    nexttasks:
      '#default#':
      - '5'
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 8dbf04c8-5154-41a7-8964-422f7c96e9ff
      iscommand: false
      name: Check Body is Text
      type: condition
      version: -1
    taskid: 8dbf04c8-5154-41a7-8964-422f7c96e9ff
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 590\n  }\n}"
  '4':
    id: '4'
    note: false
    scriptarguments:
      outputformat: {}
    separatecontext: false
    task:
      brand: ''
      id: 4821f2d5-9f8f-43d5-872a-a42b58c8fcd0
      iscommand: false
      name: All is good
      scriptName: PrintContext
      type: regular
      version: -1
    taskid: 4821f2d5-9f8f-43d5-872a-a42b58c8fcd0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 220,\n    \"y\": 830\n  }\n}"
  '5':
    id: '5'
    note: false
    scriptarguments:
      message:
        simple: Body contains html
    separatecontext: false
    task:
      brand: ''
      id: c1f8bd02-e031-49f1-8a29-5f7fa864aca3
      iscommand: false
      name: Failed Text validation
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: c1f8bd02-e031-49f1-8a29-5f7fa864aca3
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 640,\n    \"y\": 830\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 875,\n      \"width\": 800,\n      \"x\": 220,\n      \"y\": 50\n\
  \    }\n  }\n}"
