id: get_original_email_-_gmail_-_test
inputs: []
name: Get Original Email - Gmail - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d7920fee-8ada-4d48-8197-2e08d19a54dc
      iscommand: false
      name: ''
      version: -1
    taskid: d7920fee-8ada-4d48-8197-2e08d19a54dc
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '3':
    id: '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: b52aade3-aa90-4343-8417-d4aa26803d62
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: b52aade3-aa90-4343-8417-d4aa26803d62
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      EmailID:
        simple: 1653783b47d78642
      From:
        simple: admin@demistodev.com
      User:
        simple: shai@demistodev.com
    separatecontext: true
    task:
      brand: ''
      id: 62a376b7-ff93-4fd6-8a04-c21d9379046d
      iscommand: false
      name: Get Original Message - Gmail
      playbookName: Get Original Email - Gmail
      type: playbook
      version: -1
    taskid: 62a376b7-ff93-4fd6-8a04-c21d9379046d
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: Email
    separatecontext: false
    task:
      brand: ''
      id: bccee3cc-846e-45ed-8f3d-eebf5c26049a
      iscommand: false
      name: Verify context
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: bccee3cc-846e-45ed-8f3d-eebf5c26049a
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 560,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
