description: Playbook test for Nexpose integration
id: nexpose_test
inputs: []
name: Nexpose test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: a4e7d052-b186-493b-89a0-b28f8a40597d
      iscommand: false
      name: ''
      version: -1
    taskid: a4e7d052-b186-493b-89a0-b28f8a40597d
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: 370ccd5b-14b6-4a0f-80d7-90eda29c5386
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 370ccd5b-14b6-4a0f-80d7-90eda29c5386
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 195\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    quietmode: 0
    scriptarguments:
      assets:
        simple: ${Nexpose.Asset.AssetId}
      format:
        simple: xml
      name: {}
      template: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Rapid7 Nexpose
      description: Generates a new report on given assets according to a template
        and arguments.
      id: 7e3979ea-3c52-458b-86bf-e16da6696594
      iscommand: true
      name: nexpose-create-assets-report-xml
      script: Rapid7 Nexpose|||nexpose-create-assets-report
      type: regular
      version: -1
    taskid: 7e3979ea-3c52-458b-86bf-e16da6696594
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 2470\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '27'
    note: false
    quietmode: 0
    scriptarguments:
      expectedValue:
        simple: '["pdf","xml"]'
      fields: {}
      path:
        simple: InfoFile.Extension
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 63bc30cb-d217-4b3b-8b2e-50cb2ea52e88
      iscommand: false
      name: VerifyContext
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 63bc30cb-d217-4b3b-8b2e-50cb2ea52e88
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 2645\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    quietmode: 0
    scriptarguments:
      assets:
        simple: ${Endpoint.IP}
      description: {}
      importance: {}
      name:
        complex:
          root: GeneratedUUID
          transformers:
          - args:
              prefix:
                value:
                  simple: test_playbook_site
              suffix: {}
            operator: concat
      scanTemplateId: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Rapid7 Nexpose
      description: Creates a new site with the specified configuration.
      id: 40215e42-756e-478d-8bf0-39891eff759f
      iscommand: true
      name: nexpose-create-site
      script: Rapid7 Nexpose|||nexpose-create-site
      type: regular
      version: -1
    taskid: 40215e42-756e-478d-8bf0-39891eff759f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1245\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '28'
    note: false
    quietmode: 0
    scriptarguments:
      id:
        simple: ${Nexpose.Site.Id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Rapid7 Nexpose
      description: Delete a site
      id: 48fb51eb-15ba-499f-8abf-e731e1c0e158
      iscommand: true
      name: nexpose-delete-site
      script: Rapid7 Nexpose|||nexpose-delete-site
      type: regular
      version: -1
    taskid: 48fb51eb-15ba-499f-8abf-e731e1c0e158
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1420\n  }\n}"
  '16':
    id: '16'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Generates random UUID
      id: f6c19b68-41d6-49bb-8dc3-616d98dfe748
      iscommand: false
      name: GenerateUUID
      scriptName: GenerateUUID
      type: regular
      version: -1
    taskid: f6c19b68-41d6-49bb-8dc3-616d98dfe748
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1070\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      limit:
        simple: '1'
      sort: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Rapid7 Nexpose
      description: Returns all assets for which you have access.
      id: 442f48a4-64e2-4afc-818e-b5f17c26cfc1
      iscommand: true
      name: nexpose-get-assets
      script: Rapid7 Nexpose|||nexpose-get-assets
      type: regular
      version: -1
    taskid: 442f48a4-64e2-4afc-818e-b5f17c26cfc1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 370\n  }\n}"
  '20':
    id: '20'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      id:
        simple: ${Nexpose.Scan.Id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Rapid7 Nexpose
      description: Pause the specified scan
      id: d6c2d6ec-45f2-4b6c-8af0-1c82c1c3fb2e
      iscommand: true
      name: nexpose-pause-scan
      script: Rapid7 Nexpose|||nexpose-pause-scan
      type: regular
      version: -1
    taskid: d6c2d6ec-45f2-4b6c-8af0-1c82c1c3fb2e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2120\n  }\n}"
  '21':
    id: '21'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '22'
    note: false
    quietmode: 0
    scriptarguments:
      id:
        simple: ${Nexpose.Scan.Id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Rapid7 Nexpose
      description: Resume the specified scan
      id: a0d0108a-6967-4cae-8f4b-6023359bdfd9
      iscommand: true
      name: nexpose-resume-scan
      script: Rapid7 Nexpose|||nexpose-resume-scan
      type: regular
      version: -1
    taskid: a0d0108a-6967-4cae-8f4b-6023359bdfd9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3170\n  }\n}"
  '22':
    id: '22'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      id:
        simple: ${Nexpose.Scan.Id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Rapid7 Nexpose
      description: Stop the specified scan
      id: 751fd8cb-62f7-459f-803e-208abc9569b1
      iscommand: true
      name: nexpose-stop-scan
      script: Rapid7 Nexpose|||nexpose-stop-scan
      type: regular
      version: -1
    taskid: 751fd8cb-62f7-459f-803e-208abc9569b1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 3345\n  }\n}"
  '23':
    id: '23'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '20'
    note: false
    quietmode: 0
    scriptarguments:
      hosts:
        simple: 192.168.1.144
      name: {}
      site:
        simple: '1'
    separatecontext: false
    skipunavailable: false
    task:
      brand: Rapid7 Nexpose
      description: Starts a scan for the specified site.
      id: 54643013-e868-4d89-8d6c-ac151ea88dd7
      iscommand: true
      name: nexpose-start-site-scan
      script: Rapid7 Nexpose|||nexpose-start-site-scan
      type: regular
      version: -1
    taskid: 54643013-e868-4d89-8d6c-ac151ea88dd7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1945\n  }\n}"
  '26':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Nexpose.Scan.Status
          operator: isEqualString
          right:
            value:
              simple: paused
      label: 'yes'
    id: '26'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '22'
      'yes':
      - '21'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: c40cde1e-481d-4a35-8279-4750388bdc59
      iscommand: false
      name: is-paused
      type: condition
      version: -1
    taskid: c40cde1e-481d-4a35-8279-4750388bdc59
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 2995\n  }\n}"
  '27':
    id: '27'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '26'
    note: false
    quietmode: 0
    scriptarguments:
      active: {}
      limit: {}
      sort: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Rapid7 Nexpose
      description: Returns a list of scans.
      id: 29847922-a3cd-459c-8f00-8228495039e9
      iscommand: true
      name: nexpose-get-scans
      script: Rapid7 Nexpose|||nexpose-get-scans
      type: regular
      version: -1
    taskid: 29847922-a3cd-459c-8f00-8228495039e9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 2820\n  }\n}"
  '28':
    id: '28'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '29'
    note: false
    quietmode: 0
    scriptarguments:
      active: {}
      limit: {}
      sort: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Rapid7 Nexpose
      description: Returns a list of scans.
      id: c897e1f2-5249-4345-8639-f7369c1aab40
      iscommand: true
      name: check for active scans
      script: Rapid7 Nexpose|||nexpose-get-scans
      type: regular
      version: -1
    taskid: c897e1f2-5249-4345-8639-f7369c1aab40
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1595\n  }\n}"
  '29':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Nexpose.Scan
          operator: isExists
      label: 'yes'
    id: '29'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '23'
      'yes':
      - '6'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 012008d6-cf6d-4e1a-8e06-e98215555ae0
      iscommand: false
      name: scan-running
      type: condition
      version: -1
    taskid: 012008d6-cf6d-4e1a-8e06-e98215555ae0
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1770\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quietmode: 0
    scriptarguments:
      hostNameIs: {}
      ipAddressIs:
        complex:
          accessor: Asset.Address
          root: Nexpose
      limit: {}
      match: {}
      query: {}
      riskScoreHigherThan: {}
      siteIdIn: {}
      sort: {}
      vulnerabilityTitleContains: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Rapid7 Nexpose
      description: Returns all assets for which you have access that match the given
        search criteria.
      id: d71096c8-435a-45f7-8a93-4aa403b806e9
      iscommand: true
      name: nexpose-search-assets
      script: Rapid7 Nexpose|||nexpose-search-assets
      type: regular
      version: -1
    taskid: d71096c8-435a-45f7-8a93-4aa403b806e9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      id:
        simple: ${Nexpose.Asset.AssetId}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Rapid7 Nexpose
      description: Returns the specified asset.
      id: 75ffbcc2-22aa-411f-8bc0-8e013a210c96
      iscommand: true
      name: nexpose-get-asset
      script: Rapid7 Nexpose|||nexpose-get-asset
      type: regular
      version: -1
    taskid: 75ffbcc2-22aa-411f-8bc0-8e013a210c96
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    quietmode: 0
    scriptarguments:
      expectedValue: {}
      fields:
        simple: IP, OS
      path:
        simple: Endpoint
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: daa223de-4758-4cb5-87c4-0d04617c2925
      iscommand: false
      name: VerifyContext
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: daa223de-4758-4cb5-87c4-0d04617c2925
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 895\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    quietmode: 0
    scriptarguments:
      assets:
        simple: ${Nexpose.Asset.AssetId}
      format: {}
      name: {}
      template: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Rapid7 Nexpose
      description: Generates a new report on given assets according to a template
        and arguments.
      id: d2a06eee-9c71-49cd-8b05-9086b86304e7
      iscommand: true
      name: nexpose-create-assets-report
      script: Rapid7 Nexpose|||nexpose-create-assets-report
      type: regular
      version: -1
    taskid: d2a06eee-9c71-49cd-8b05-9086b86304e7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 2295\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 3390,\n      \"width\": 492.5,\n      \"x\": 50,\n      \"y\"\
  : 50\n    }\n  }\n}"
