id: Nmap - Test
inputs: []
name: Nmap - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
      - '5'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: b71b221d-c057-448d-8166-dbdda28e1923
      iscommand: false
      name: ''
      version: -1
    taskid: b71b221d-c057-448d-8166-dbdda28e1923
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      options:
        simple: -sV
      targets:
        simple: scanme.nmap.org
    separatecontext: false
    skipunavailable: false
    task:
      brand: nmap
      description: Scan targets with the given parameters
      id: 57b76811-53f9-40f1-84db-34073d8decdc
      iscommand: true
      name: nmap-scan
      script: nmap|||nmap-scan
      type: regular
      version: -1
    taskid: 57b76811-53f9-40f1-84db-34073d8decdc
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      'no':
      - '4'
      'yes':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${NMAP.Scan.Hosts.Services.Port(val==22)}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 2c9015ee-deb7-4008-8ad4-d36df37aa554
      iscommand: false
      name: Exists
      scriptName: Exists
      type: condition
      version: -1
    taskid: 2c9015ee-deb7-4008-8ad4-d36df37aa554
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 375\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 63bf6238-d1c2-4a43-81b6-cc13014a8d75
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 63bf6238-d1c2-4a43-81b6-cc13014a8d75
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 170,\n    \"y\": 770\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Service not found
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: c84fe071-c5e8-4177-874c-fbd94d2b2c8c
      iscommand: false
      name: Oops, problem
      scriptName: Print
      type: regular
      version: -1
    taskid: c84fe071-c5e8-4177-874c-fbd94d2b2c8c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 970,\n    \"y\": 660\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      options:
        simple: -sn
      targets:
        simple: 8.8.8.8
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Scan targets with the given parameters
      id: 8cad128d-8595-4434-8691-3cf64fde55ee
      iscommand: true
      name: nmap-scan
      script: '|||nmap-scan'
      type: regular
      version: -1
    taskid: 8cad128d-8595-4434-8691-3cf64fde55ee
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 970,\n    \"y\": 195\n  }\n}"
  '6':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Scan.Hosts.Hostname
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: NMAP.Scan.Hosts.Address
                    operator: isEqualString
                    right:
                      value:
                        simple: 8.8.8.8
                root: NMAP
          operator: isEqualString
          right:
            value:
              simple: dns.google
      label: 'yes'
    id: '6'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '4'
      'yes':
      - '3'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: 1b55deeb-0356-43ca-8dc9-803c125d8269
      iscommand: false
      name: check Hostname
      type: condition
      version: -1
    taskid: 1b55deeb-0356-43ca-8dc9-803c125d8269
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 970,\n    \"y\": 375\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"2_4_no\": 0.26,\n    \"6_3_yes\": 0.63\n\
  \  },\n  \"paper\": {\n    \"dimensions\": {\n      \"height\": 785,\n      \"width\"\
  : 1180,\n      \"x\": 170,\n      \"y\": 50\n    }\n  }\n}"
