id: Claroty - Test
inputs: []
name: Claroty - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: aa4a022b-08d5-47ed-8368-38a6b9d4c338
      iscommand: false
      name: ''
      version: -1
    taskid: aa4a022b-08d5-47ed-8368-38a6b9d4c338
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: d000b72d-1375-431f-8190-9cf700334ae2
      iscommand: true
      name: DeleteContext
      script: DeleteContext
      type: regular
      version: -1
    taskid: d000b72d-1375-431f-8190-9cf700334ae2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: cf2df97d-2ab4-418e-85a4-952716b8e6df
      iscommand: false
      name: Test Done
      type: title
      version: -1
    taskid: cf2df97d-2ab4-418e-85a4-952716b8e6df
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1945\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      all: {}
      index: {}
      key:
        simple: Claroty.Alert.Description
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: e2775f67-2cdc-4da9-82c9-dedbac9698ee
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: e2775f67-2cdc-4da9-82c9-dedbac9698ee
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      asset_amount: {}
      asset_limit:
        simple: '1'
      assets_last_seen: {}
      criticality:
        simple: Low
      fields: {}
      insight_name: {}
      should_enrich_assets: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: f6770943-f06a-4c19-8c1f-f61d96acf289
      iscommand: true
      name: claroty-get-assets
      script: '|||claroty-get-assets'
      type: regular
      version: -1
    taskid: f6770943-f06a-4c19-8c1f-f61d96acf289
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Claroty.Asset.AssetID
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: Claroty.Asset.AssetType
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: Claroty.Asset.Criticality
          operator: isEqualString
          right:
            value:
              simple: Low
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 319c2c2c-24de-4c9d-8317-473bfe11108b
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 319c2c2c-24de-4c9d-8317-473bfe11108b
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      alert_limit:
        simple: '1'
      alert_number: {}
      date_from: {}
      fields: {}
      severity: {}
      sort_by: {}
      sort_order: {}
      type:
        simple: Configuration Download
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 9c95021e-8a1b-438b-853b-8ba220cfea47
      iscommand: true
      name: claroty-query-alerts
      script: '|||claroty-query-alerts'
      type: regular
      version: -1
    taskid: 9c95021e-8a1b-438b-853b-8ba220cfea47
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Claroty.Alert.AlertTypeID
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: Claroty.Alert.AlertTypeID
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: Claroty.Alert.Description
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: Claroty.Alert.Severity
          operator: isNotEmpty
      label: 'yes'
    id: '5'
    ignoreworker: false
    nexttasks:
      'yes':
      - '11'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 63ff8d38-f01a-429c-8346-9bf621dc362b
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 63ff8d38-f01a-429c-8346-9bf621dc362b
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    quietmode: 0
    scriptarguments:
      resolve_as: {}
      resolve_comment: {}
      selected_alerts:
        simple: ${Claroty.Alert.ResourceID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 4995897a-4aee-4585-8a18-013141afa4fb
      iscommand: true
      name: claroty-resolve-alert
      script: '|||claroty-resolve-alert'
      type: regular
      version: -1
    taskid: 4995897a-4aee-4585-8a18-013141afa4fb
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
  '7':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Claroty.Resolve_out.success
          operator: isNotEmpty
      label: 'yes'
    id: '7'
    ignoreworker: false
    nexttasks:
      'yes':
      - '10'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 101e203f-ec0b-4b1d-8f8e-17e653d21ea9
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 101e203f-ec0b-4b1d-8f8e-17e653d21ea9
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    quietmode: 0
    scriptarguments:
      alert_rid:
        simple: ${Claroty.Alert.ResourceID}
      fields: {}
      get_single_alert: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 438ae5d9-db33-41bb-8585-0494fbd1fc37
      iscommand: true
      name: claroty-get-single-alert
      script: '|||claroty-get-single-alert'
      type: regular
      version: -1
    taskid: 438ae5d9-db33-41bb-8585-0494fbd1fc37
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '9':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Claroty.Alert.Description
          operator: isNotEmpty
      label: 'yes'
    id: '9'
    ignoreworker: false
    nexttasks:
      'yes':
      - '6'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 11893f0b-04a1-4ec6-8133-78eb27124340
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 11893f0b-04a1-4ec6-8133-78eb27124340
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1960,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
