id: PhishTank Testing
inputs: []
name: PhishTank Testing
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '8'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      id: 7aaefdb3-41b2-4c42-8cd1-54f706951e5f
      iscommand: false
      name: ''
      version: -1
    taskid: 7aaefdb3-41b2-4c42-8cd1-54f706951e5f
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
      - '3'
    reputationcalc: 0
    scriptarguments:
      url:
        simple: ${badURL}
    separatecontext: false
    task:
      brand: PhishTank
      id: 5a505f28-e3be-4c95-81c6-ae394b129f80
      iscommand: true
      name: Check URL
      script: PhishTank|||url
      type: regular
      version: -1
    taskid: 5a505f28-e3be-4c95-81c6-ae394b129f80
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 895\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '4'
    reputationcalc: 0
    scriptarguments:
      expectedValue: {}
      fields:
        simple: Data
      path:
        simple: URL
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 0a2da204-3f8f-4eab-83df-f878268723f5
      iscommand: false
      name: Verify URL Data
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 0a2da204-3f8f-4eab-83df-f878268723f5
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '4'
    reputationcalc: 0
    scriptarguments:
      expectedValue: {}
      fields:
        simple: Indicator,Score,Type,Vendor
      path:
        simple: DBotScore
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 5cc2b958-d69e-43b2-89f6-55ceb23ef902
      iscommand: false
      name: Verify DBotScore
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 5cc2b958-d69e-43b2-89f6-55ceb23ef902
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1070\n  }\n}"
  '4':
    id: '4'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      id: ff7a088b-0315-4569-85e8-ec5556bd0b1f
      iscommand: false
      name: Success
      type: title
      version: -1
    taskid: ff7a088b-0315-4569-85e8-ec5556bd0b1f
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1245\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '6'
    reputationcalc: 0
    scriptarguments:
      body: {}
      filename:
        simple: phishtank.csv
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      url:
        simple: http://data.phishtank.com/data/online-valid.csv
      username: {}
    separatecontext: false
    task:
      brand: ''
      id: be16d6b0-c31f-48c8-8802-a4d71351a0e9
      iscommand: false
      name: Download phishtank CSV
      scriptName: http
      type: regular
      version: -1
    taskid: be16d6b0-c31f-48c8-8802-a4d71351a0e9
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '7'
    reputationcalc: 0
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
      maxFileSize:
        simple: '2000'
    separatecontext: false
    task:
      brand: ''
      id: 2460c597-5995-4288-887d-60873622416e
      iscommand: false
      name: Load file to context
      scriptName: ReadFile
      type: regular
      version: -1
    taskid: 2460c597-5995-4288-887d-60873622416e
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 545\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '1'
    reputationcalc: 0
    scriptarguments:
      append: {}
      key:
        simple: badURL
      value:
        simple: ${FileData=val.split('\n')[1].split(',')[1]}
    separatecontext: false
    task:
      brand: ''
      id: e8f9b718-59b5-431e-8e37-66b1025b321e
      iscommand: false
      name: Set badURL
      scriptName: Set
      type: regular
      version: -1
    taskid: e8f9b718-59b5-431e-8e37-66b1025b321e
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 720\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '5'
    reputationcalc: 0
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      id: 60b545ed-5c7c-4bc2-8131-00da26d2b52c
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 60b545ed-5c7c-4bc2-8131-00da26d2b52c
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1260,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
