description: 'This playbook receives an MD5 hash and adds it to the blacklist in Carbon
  Black Enterprise Response. Files with that MD5 hash are blocked from execution on
  the managed endpoints.


  If the integration is disabled at the time of running, or if the hash is already
  on the blacklist, no action is taken on the MD5.'
fromversion: 4.0.0
id: block_file_-_carbon_black_response
inputs:
- description: The MD5 hash of the file you want to block.
  key: MD5
  required: false
  value:
    complex:
      accessor: MD5
      root: File
name: Block File - Carbon Black Response
outputs:
- contextPath: CbResponse.BlockedHashes.LastBlock.Time
  description: Last block time
- contextPath: CbResponse.BlockedHashes.LastBlock.Hostname
  description: Last block hostname
- contextPath: CbResponse.BlockedHashes.LastBlock.CbSensorID
  description: Last block sensor ID
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 5e4385e3-76c2-48e2-80a4-c3798cdae027
      iscommand: false
      name: ''
      version: -1
    taskid: 5e4385e3-76c2-48e2-80a4-c3798cdae027
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": -340\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      banCount: {}
      lastBanHost: {}
      lastBanTime: {}
      md5hash:
        simple: ${inputs.MD5}
      text:
        simple: Malicious hash detected and will be blocked
    separatecontext: false
    task:
      brand: ''
      description: Adds the MD5 hash to the blacklist in Carbon Black, which blocks
        the execution of files with that hash on the managed endpoints.
      id: 0ee119bc-c1cf-435e-866c-69c8273f8e0d
      iscommand: true
      name: Add the MD5 to the blacklist
      script: '|||cb-block-hash'
      type: regular
      version: -1
    taskid: 0ee119bc-c1cf-435e-866c-69c8273f8e0d
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 230,\n    \"y\": 570\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      filter:
        complex:
          root: inputs.MD5
          transformers:
          - args:
              prefix:
                value:
                  simple: md5hash==
              suffix: {}
            operator: concat
    separatecontext: false
    task:
      brand: ''
      description: Returns a list of blacklisted hashes, with each list entry describing
        one blacklisted hash.
      id: f4665f30-1aca-401f-8011-8f6b76ee97ca
      iscommand: true
      name: Get a list of blacklisted hashes
      script: '|||cb-get-hash-blacklist'
      type: regular
      version: -1
    taskid: f4665f30-1aca-401f-8011-8f6b76ee97ca
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 200\n  }\n}"
  '4':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: CbResponse.BlockedHashes.MD5
          operator: isEqualString
          right:
            iscontext: true
            value:
              simple: inputs.MD5
      - - left:
            iscontext: true
            value:
              simple: CbResponse.BlockedHashes.Enabled
          operator: isTrue
      label: 'yes'
    id: '4'
    nexttasks:
      '#default#':
      - '1'
      'yes':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Checks whether the MD5 is already on the blacklist. This prevents
        blacklisting an MD5 hash that is already blacklisted.
      id: 82a3b953-f23a-4292-8662-14f58fe4e337
      iscommand: false
      name: Is the MD5 currently blacklisted?
      type: condition
      version: -1
    taskid: 82a3b953-f23a-4292-8662-14f58fe4e337
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 370\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '9'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 1447c8cb-2fa3-43ee-80d6-128a35bdcefa
      iscommand: false
      name: Hash Is Already Blocked
      type: title
      version: -1
    taskid: 1447c8cb-2fa3-43ee-80d6-128a35bdcefa
    type: title
    view: "{\n  \"position\": {\n    \"x\": 700,\n    \"y\": 570\n  }\n}"
  '6':
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: carbonblack-v2
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: 'yes'
    id: '6'
    nexttasks:
      '#default#':
      - '7'
      'yes':
      - '2'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Checks if Carbon Black Enterprise Response integration is enabled.
      id: 351582dc-a7a4-4ea0-843a-59c6770d0285
      iscommand: false
      name: Is Carbon Black Enterprise Response enabled?
      type: condition
      version: -1
    taskid: 351582dc-a7a4-4ea0-843a-59c6770d0285
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 0\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '9'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: bcd55436-7475-40ae-8cf1-e7e94ca27567
      iscommand: false
      name: No Integration / No MD5
      type: title
      version: -1
    taskid: bcd55436-7475-40ae-8cf1-e7e94ca27567
    type: title
    view: "{\n  \"position\": {\n    \"x\": 1250,\n    \"y\": 360\n  }\n}"
  '8':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.MD5
          operator: isExists
      label: 'yes'
    id: '8'
    nexttasks:
      '#default#':
      - '7'
      'yes':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Checks if there is a value for the MD5 input field. This task does
        not verify that the value is actually an MD5 hash, just that the value for
        the MD5 field exists.
      id: ff0935b7-054b-4729-82a3-5588d553d9d0
      iscommand: false
      name: Is there an MD5 to block?
      type: condition
      version: -1
    taskid: ff0935b7-054b-4729-82a3-5588d553d9d0
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": -200\n  }\n}"
  '9':
    id: '9'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 2c14bf01-7fd9-45f8-8554-86d0c1332d81
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 2c14bf01-7fd9-45f8-8554-86d0c1332d81
    type: title
    view: "{\n  \"position\": {\n    \"x\": 410,\n    \"y\": 830\n  }\n}"
tests:
- block_indicators_-_generic_-_test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1235,\n      \"width\": 1400,\n      \"x\": 230,\n      \"y\"\
  : -340\n    }\n  }\n}"
