description: Carbon Black Response - isolate an endpoint, given a hostname.
fromversion: 3.5.0
id: block_endpoint_-_carbon_black_response
inputs:
- description: The hostname to isolate.
  key: Hostname
  required: false
  value:
    simple: ${Endpoint.Hostname}
name: Block Endpoint - Carbon Black Response
outputs:
- contextPath: CbResponse.Sensors.CbSensorID
  description: Carbon Black Response Sensors ids that has been isolated
- contextPath: Endpoint
  description: The isolated enpoint
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '5'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 73040a0e-cca5-4197-8089-f46650317040
      iscommand: false
      name: ''
      version: -1
    taskid: 73040a0e-cca5-4197-8089-f46650317040
    type: start
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 50\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
    scriptarguments:
      groupid: {}
      hostname:
        simple: ${inputs.Hostname}
      ip: {}
      sensor: {}
    separatecontext: false
    task:
      brand: carbonblack
      description: Query  Carbon Black Enterprise Response for the host
      id: 81cfb3e4-cb04-4c91-8bc7-d23980939d7e
      iscommand: true
      name: Get host information from Carbon Black Enterprise Response
      script: carbonblack|||cb-sensor-info
      type: regular
      version: -1
    taskid: 81cfb3e4-cb04-4c91-8bc7-d23980939d7e
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '4'
    scriptarguments:
      sensor:
        simple: ${CbResponse.Sensors.CbSensorID}
    separatecontext: false
    task:
      brand: carbonblack
      description: Carbon Black Response - isolate the host
      id: 36d3a39d-ae26-4db6-8ed5-228172276852
      iscommand: true
      name: Isolate hostname
      script: carbonblack|||cb-quarantine-device
      type: regular
      version: -1
    taskid: 36d3a39d-ae26-4db6-8ed5-228172276852
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: d35be2d6-6709-40d0-846e-dc9aef142e30
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d35be2d6-6709-40d0-846e-dc9aef142e30
    type: title
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 720\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: brand
                    operator: string.isEqual
                    right:
                      value:
                        simple: carbonblack
                - - left:
                      iscontext: true
                      value:
                        simple: state
                    operator: string.isEqual
                    right:
                      value:
                        simple: active
                root: modules
          operator: general.isExists
      label: 'yes'
    id: '5'
    nexttasks:
      '#default#':
      - '4'
      'yes':
      - '2'
    separatecontext: false
    task:
      brand: ''
      description: Check if Carbon black active in the system.
      id: 27405cc3-bf4c-4879-87ad-880b99941e9a
      iscommand: false
      name: Is Carbon Black Enterprise Response enabled?
      type: condition
      version: -1
    taskid: 27405cc3-bf4c-4879-87ad-880b99941e9a
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 161,\n    \"y\": 210\n  }\n}"
tests:
- no test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 735,\n      \"width\": 492.5,\n      \"x\": 50,\n      \"y\":\
  \ 50\n    }\n  }\n}"
