description: Returns a file sample to the war-room from a path on an endpoint using
  Carbon Black Enterprise Response
fromversion: 3.5.0
id: get_file_sample_from_path_-_carbon_black_enterprise_response
inputs:
- description: The host to get file from
  key: Hostname
  required: false
  value:
    simple: ${Endpoint.Hostname}
- description: Path of the file on the endpoint
  key: Path
  required: false
  value:
    simple: ${File.Path}
name: Get File Sample From Path - Carbon Black Enterprise Response
outputs:
- contextPath: File
  description: The file to sample.
  type: unknown
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 6b09e12d-a699-4b98-8f93-0ee2fb3904df
      iscommand: false
      name: ''
      version: -1
    taskid: 6b09e12d-a699-4b98-8f93-0ee2fb3904df
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 48\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#default#':
      - '3'
      'yes':
      - '5'
    scriptarguments:
      extend-context: {}
      value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: brand
              operator: string.isEqual
              right:
                value:
                  simple: carbonblack
          - - left:
                iscontext: true
                value:
                  simple: state
              operator: string.isEqual
              right:
                value:
                  simple: active
          root: modules
    separatecontext: false
    task:
      brand: ''
      description: Check if  Carbon Black Enterprise Response active in the system.
      id: 40ec070b-2ab3-432a-86fa-eb02b381398a
      iscommand: false
      name: Is Carbon Black Enterprise Response enabled?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 40ec070b-2ab3-432a-86fa-eb02b381398a
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 196\n  }\n}"
  '3':
    id: '3'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 347006fd-60f5-4233-8c40-9b941735dd2a
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 347006fd-60f5-4233-8c40-9b941735dd2a
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '3'
    scriptarguments:
      hostname:
        simple: ${inputs.Hostname}
      ip: {}
      path:
        simple: ${inputs.Path}
    separatecontext: false
    task:
      brand: ''
      description: Use Carbon black Response Live session to retrieve a file from
        an endpoint. Endpoint needs to have a CbResponse sensor deployed.
      id: 6361a341-4a5c-4735-8ffe-ce13d9539b91
      iscommand: false
      name: Get File
      scriptName: CBLiveGetFile
      type: regular
      version: -1
    taskid: 6361a341-4a5c-4735-8ffe-ce13d9539b91
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 514,\n    \"y\": 544\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Path
          operator: general.isExists
      - - left:
            iscontext: true
            value:
              simple: inputs.Hostname
          operator: general.isExists
      label: 'yes'
    id: '5'
    nexttasks:
      '#default#':
      - '3'
      'yes':
      - '4'
    scriptarguments:
      value:
        simple: ${inputs.Path}
    separatecontext: false
    task:
      brand: ''
      description: Checks if a file path exists in playbook inputs.
      id: 69aeb053-04ea-4853-872a-adf410c08c5e
      iscommand: false
      name: Is there a file path and hostname?
      type: condition
      version: -1
    taskid: 69aeb053-04ea-4853-872a-adf410c08c5e
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 301,\n    \"y\": 367\n  }\n}"
tests:
- no test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"1_3_#default#\": 0.5\n  },\n  \"paper\"\
  : {\n    \"dimensions\": {\n      \"height\": 737,\n      \"width\": 844,\n    \
  \  \"x\": 50,\n      \"y\": 48\n    }\n  }\n}"
