description: Returns to the war-room a file sample correlating to MD5 hashes in the
  input using Carbon Black Enterprise Response integration
fromversion: 3.5.0
id: get_file_sample_by_hash_-_carbon_black_enterprise_Response
inputs:
- description: 'Get file sample from input MD5 '
  key: MD5
  required: false
  value:
    complex:
      accessor: MD5
      root: File
name: Get File Sample By Hash - Carbon Black Enterprise Response
outputs:
- contextPath: File
  description: File Sample
  type: unknown
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 13be4945-ec82-4790-8892-a66b8b74111c
      iscommand: false
      name: ''
      version: -1
    taskid: 13be4945-ec82-4790-8892-a66b8b74111c
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#default#':
      - '3'
      'yes':
      - '2'
    scriptarguments:
      extend-context: {}
      value:
        complex:
          accessor: brand
          filters:
          - - left:
                iscontext: true
                value:
                  simple: modules.brand
              operator: string.isEqual
              right:
                value:
                  simple: carbonblack
          - - left:
                iscontext: true
                value:
                  simple: modules.state
              operator: string.isEqual
              right:
                value:
                  simple: active
          root: modules
    separatecontext: false
    task:
      brand: ''
      description: Checks if the Carbon Black Enterprise Response integration is enabled
      id: 795290dd-889b-4ea6-8e83-7b04252bddf2
      iscommand: false
      name: Is Carbon Black Enterprise Response enabled?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 795290dd-889b-4ea6-8e83-7b04252bddf2
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#default#':
      - '3'
      'yes':
      - '4'
    scriptarguments:
      value:
        complex:
          root: inputs.MD5
    separatecontext: false
    task:
      brand: ''
      description: Checks for MD5 in context
      id: d489fccb-fab0-471b-849c-3b64ab63e7ce
      iscommand: false
      name: Do we have a MD5?
      scriptName: Exists
      type: condition
      version: -1
    taskid: d489fccb-fab0-471b-849c-3b64ab63e7ce
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 90947de7-db04-49c9-88f3-747e0ad4c026
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 90947de7-db04-49c9-88f3-747e0ad4c026
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 711\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '3'
    scriptarguments:
      facet: {}
      md5:
        complex:
          root: inputs.MD5
      pid: {}
      query: {}
      rows: {}
      segid: {}
      sort: {}
      start: {}
      summary: {}
    separatecontext: false
    task:
      brand: carbonblack
      description: ''
      id: 4241ccef-7acc-49f9-8976-e97a654bf89d
      iscommand: true
      name: Get binary from MD5
      script: carbonblack|||cb-binary-get
      type: regular
      version: -1
    taskid: 4241ccef-7acc-49f9-8976-e97a654bf89d
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 309,\n    \"y\": 550\n  }\n}"
tests:
- no test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 726,\n      \"width\": 639,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
