description: Tests that DUO pre-auth returns expected results for various user types
id: DUO Test Playbook
inputs: []
name: DUO Test Playbook
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 0ec6555c-e530-4e5f-8e17-3dc8295dcbf5
      iscommand: false
      name: ''
      version: -1
    taskid: 0ec6555c-e530-4e5f-8e17-3dc8295dcbf5
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: ae4ad4d9-d323-42c8-82bb-12bd5ea3e070
      iscommand: false
      name: delete context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: ae4ad4d9-d323-42c8-82bb-12bd5ea3e070
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 230\n  }\n}"
  '10':
    id: '10'
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      ipaddr: {}
      userID: {}
      username:
        simple: no-user
    separatecontext: false
    task:
      brand: ''
      id: a1b0afbe-a652-42ea-814d-e7649d314196
      iscommand: true
      name: Preauth non existent user
      script: '|||duo-preauth'
      type: regular
      version: -1
    taskid: a1b0afbe-a652-42ea-814d-e7649d314196
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 280,\n    \"y\": 1290\n  }\n}"
  '11':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: PreAuth.[2].Response.StatusMessage
                root: Duo
          operator: notContainsString
          right:
            value:
              simple: disabled
      - - left:
            iscontext: true
            value:
              complex:
                accessor: PreAuth.[2].Response.Result
                root: Duo
          operator: isEqualString
          right:
            value:
              simple: deny
      label: 'yes'
    id: '11'
    nexttasks:
      '#default#':
      - '7'
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 6d3a9b84-a90c-4490-8790-53d37deaeb71
      iscommand: false
      name: Check Non-Existent User Response
      type: condition
      version: -1
    taskid: 6d3a9b84-a90c-4490-8790-53d37deaeb71
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 280,\n    \"y\": 1440\n  }\n}"
  '4':
    id: '4'
    note: false
    scriptarguments:
      outputformat: {}
    separatecontext: false
    task:
      brand: ''
      id: 6fe0f9d3-f050-402e-8f67-bf95070cb309
      iscommand: false
      name: print context
      scriptName: PrintContext
      type: regular
      version: -1
    taskid: 6fe0f9d3-f050-402e-8f67-bf95070cb309
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 270,\n    \"y\": 1590\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      ipaddr: {}
      userID: {}
      username:
        simple: test-user
    separatecontext: false
    task:
      brand: ''
      id: 07bf20d5-abf9-431f-87d9-c72236f67eb4
      iscommand: true
      name: Preauth disabled user
      script: '|||duo-preauth'
      type: regular
      version: -1
    taskid: 07bf20d5-abf9-431f-87d9-c72236f67eb4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 390\n  }\n}"
  '6':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Duo.PreAuth.Response.Result
          operator: isEqualString
          right:
            value:
              simple: deny
      - - left:
            iscontext: true
            value:
              simple: Duo.PreAuth.Response.StatusMessage
          operator: containsString
          right:
            value:
              simple: disabled
      label: 'yes'
    id: '6'
    nexttasks:
      '#default#':
      - '7'
      'yes':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d339d691-c1c9-4d6a-8b83-98bab10dca9a
      iscommand: false
      name: Check Disabled User Response
      type: condition
      version: -1
    taskid: d339d691-c1c9-4d6a-8b83-98bab10dca9a
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 530\n  }\n}"
  '7':
    id: '7'
    note: false
    scriptarguments:
      message:
        simple: Duo result doesn't match expected result
    separatecontext: false
    task:
      brand: ''
      id: 546ed819-8c03-4f1f-819d-c9828b1ff38d
      iscommand: false
      name: Print Error
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 546ed819-8c03-4f1f-819d-c9828b1ff38d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 980,\n    \"y\": 1630\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      ipaddr: {}
      userID: {}
      username:
        simple: active-user
    separatecontext: false
    task:
      brand: ''
      id: 1f82e7a9-4b4a-4746-8d47-b40653254d10
      iscommand: true
      name: 'Preauth active user '
      script: '|||duo-preauth'
      type: regular
      version: -1
    taskid: 1f82e7a9-4b4a-4746-8d47-b40653254d10
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 260,\n    \"y\": 770\n  }\n}"
  '9':
    id: '9'
    nexttasks:
      '#default#':
      - '7'
      'yes':
      - '10'
    note: false
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        simple: ${Duo.PreAuth.[1].Response.Result}
      right:
        simple: auth
    separatecontext: false
    task:
      brand: ''
      id: 59dba592-6f2c-40a9-8557-533b60882ca5
      iscommand: false
      name: Check Active User Response
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: 59dba592-6f2c-40a9-8557-533b60882ca5
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 260,\n    \"y\": 980\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1675,\n      \"width\": 1100,\n      \"x\": 260,\n      \"y\"\
  : 50\n    }\n  }\n}"
