id: Request Debugging - Test
inputs: []
name: Request Debugging - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 272a0128-95e1-4c57-8f16-7aa0dcfaac4d
      iscommand: false
      name: ''
      version: -1
    taskid: 272a0128-95e1-4c57-8f16-7aa0dcfaac4d
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: f8c6f74f-05b9-48b4-882c-571cf60d96d5
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: f8c6f74f-05b9-48b4-882c-571cf60d96d5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Executes the SimpleRequest automation with `debug-mode=True`.
      id: 97bdaf8c-a684-4e70-84fd-0a95444d0182
      iscommand: false
      name: SimpleRequestExecutor
      scriptName: SimpleRequestExecutor
      type: regular
      version: -1
    taskid: 97bdaf8c-a684-4e70-84fd-0a95444d0182
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Read the contents of the debugging file and check that request
        debugging information is included in the file.
      id: 9dbe44f8-f26b-4a87-89e3-f15f905419e5
      iscommand: false
      name: SimpleRequestGetter
      scriptName: SimpleRequestGetter
      type: regular
      version: -1
    taskid: 9dbe44f8-f26b-4a87-89e3-f15f905419e5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 893cc623-a73d-47d1-853d-fbc45b2c45ec
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 893cc623-a73d-47d1-853d-fbc45b2c45ec
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 735,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
