id: GsuiteTest
inputs: []
name: test-Gsuite
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 9407849a-c88c-4039-8bf8-57b927260f2c
      iscommand: false
      name: ''
      version: -1
    taskid: 9407849a-c88c-4039-8bf8-57b927260f2c
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      custom-field-mask: {}
      customer: {}
      domain: {}
      event: {}
      max-results: {}
      projection: {}
      query: {}
      show-deleted: {}
      sort-order: {}
      view-type-public-domain: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: google
      description: Retrieves a paginated list of either deleted users or all users
        in a domain
      id: 70ea876b-80a8-4cf9-85a7-82b52ed9282e
      iscommand: true
      name: googleapps-list-users
      script: google|||googleapps-list-users
      type: regular
      version: -1
    taskid: 70ea876b-80a8-4cf9-85a7-82b52ed9282e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 230\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      field1:
        simple: ${Account.[1]}
      field2:
        simple: ${Account.[2]}
      field3: {}
      field4: {}
      value1: {}
      value2: {}
      value3: {}
      value4: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: c403a460-e3fb-42a8-86bb-b30eabbcc9eb
      iscommand: false
      name: VerifyContextFields
      scriptName: VerifyContextFields
      type: regular
      version: -1
    taskid: c403a460-e3fb-42a8-86bb-b30eabbcc9eb
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 410\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 455,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\": 50\n\
  \    }\n  }\n}"
