contentitemfields:
  propagationLabels: []
id: calculate_severity_-_critical_assets_-_test
inputs: []
name: Calculate Severity - Critical assets - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: e43fd77e-bfd4-4c0a-8dae-2e2eb07bc227
      iscommand: false
      name: ''
      version: -1
    taskid: e43fd77e-bfd4-4c0a-8dae-2e2eb07bc227
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      Account:
        complex:
          root: Account
      CriticalEndpoints: {}
      CriticalGroups:
        simple: CN=Discovery Management,OU=Microsoft Exchange Security Groups,DC=demisto,DC=int,
          CN=Organization Management,OU=Microsoft Exchange Security Groups,DC=demisto,DC=int
      CriticalUsers:
        simple: demistoadmin
      Endpoint:
        complex:
          root: Endpoint
    separatecontext: true
    task:
      brand: ''
      description: 'Determines if a critical assest is associated with the invesigation.
        The playbook returns a severity level of "Critical" if a critical asset is
        associated with the investigation.


        This playbook verifies if a user account or an endpoint is part of a critical
        list or a critical AD group. '
      id: aa03a1ce-5bb0-4e69-8c6e-5510c6c96285
      iscommand: false
      name: Calculate Severity - Critical assets
      playbookName: Calculate Severity - Critical assets
      type: playbook
      version: -1
    taskid: aa03a1ce-5bb0-4e69-8c6e-5510c6c96285
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 545\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      attributes: {}
      customFieldData: {}
      customFieldType: {}
      dn: {}
      email: {}
      headers: {}
      limit: {}
      name: {}
      nestedSearch: {}
      userAccountControlOut: {}
      username:
        simple: demistoadmin
    separatecontext: false
    task:
      brand: ''
      description: 'Use Active Directory to retrieve detailed information about a
        user account. The user can be specified by name, email or as an Active Directory
        Distinguished Name (DN).

        If no filter is provided, the result will show all users.'
      id: 0137adfd-0b9c-408f-832c-0f576e249229
      iscommand: false
      name: ADGetUser
      scriptName: ADGetUser
      type: regular
      version: -1
    taskid: 0137adfd-0b9c-408f-832c-0f576e249229
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Severity
          operator: isEqualString
          right:
            value:
              simple: critical
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '6'
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 05f82ada-8cbf-4f24-89b2-c8062547fb84
      iscommand: false
      name: Verify Context
      type: condition
      version: -1
    taskid: 05f82ada-8cbf-4f24-89b2-c8062547fb84
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 720\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 9e8e32f3-903a-4b4d-8ad9-c189ef3ca84c
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 9e8e32f3-903a-4b4d-8ad9-c189ef3ca84c
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 910\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 44b7a914-5080-4b05-8d9a-812f2e4f6c1d
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 44b7a914-5080-4b05-8d9a-812f2e4f6c1d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    note: false
    scriptarguments:
      message:
        simple: Severity is not in the context
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: f4079974-1450-4d7c-83c8-f15d55f04529
      iscommand: false
      name: PrintErrorEntry
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: f4079974-1450-4d7c-83c8-f15d55f04529
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 895\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 940,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
