id: CheckDockerImageAvailableTest
inputs: []
name: CheckDockerImageAvailableTest
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: f8d4bccc-17c6-457e-8f52-2fcab83262e8
      iscommand: false
      name: ''
      version: -1
    taskid: f8d4bccc-17c6-457e-8f52-2fcab83262e8
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
      - '3'
      - '8'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 2143d31e-a016-4f75-8fe6-01c6b33de709
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 2143d31e-a016-4f75-8fe6-01c6b33de709
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 180\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      extend-context:
        simple: CheckDockerValid=.
      input:
        simple: demisto/python:2.7.15.155
      trust_any_certificate:
        simple: 'yes'
      use_system_proxy:
        simple: 'no'
    separatecontext: false
    task:
      brand: ''
      description: Check if a docker image is available for performing docker pull.
        Script simulates the docker pull flow but doesn't actually pull the image.
        Returns an entry with 'ok' if all is good otherwise will return an error.
      id: ae3ab3d9-afad-4fdf-8e5a-8657fea0d49f
      iscommand: false
      name: Check docker valid image (docker hub)
      scriptName: CheckDockerImageAvailable
      type: regular
      version: -1
    taskid: ae3ab3d9-afad-4fdf-8e5a-8657fea0d49f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 360\n  }\n}"
  '3':
    continueonerror: true
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      extend-context:
        simple: CheckDockerBad=.
      input:
        simple: demisto/notgoodimage:1.0
      trust_any_certificate:
        simple: 'yes'
      use_system_proxy:
        simple: 'no'
    separatecontext: false
    task:
      brand: ''
      description: Check if a docker image is available for performing docker pull.
        Script simulates the docker pull flow but doesn't actually pull the image.
        Returns an entry with 'ok' if all is good otherwise will return an error.
      id: a1f9c603-7ed5-4ddd-8b52-546e10df1836
      iscommand: false
      name: Check docker in-valid image
      scriptName: CheckDockerImageAvailable
      type: regular
      version: -1
    taskid: a1f9c603-7ed5-4ddd-8b52-546e10df1836
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 20,\n    \"y\": 360\n  }\n}"
  '4':
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: CheckDockerValid
          operator: isEqualString
          right:
            value:
              simple: ok
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: CheckDockerBad
          operator: isNotEqualString
          right:
            value:
              simple: ok
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: CheckGcrValid
          operator: isEqualString
          right:
            value:
              simple: ok
      label: 'yes'
    id: '4'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '5'
      'yes':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 974f59d4-258f-4f7c-85c3-03f2586a18be
      iscommand: false
      name: Verify outputs
      type: condition
      version: -1
    taskid: 974f59d4-258f-4f7c-85c3-03f2586a18be
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    note: false
    scriptarguments:
      message:
        simple: 'Failed output verification: Check the context for the outputs'
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: 9f75aa4b-33d0-49c8-8a4a-cfe3ddf41c4b
      iscommand: false
      name: Error
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 9f75aa4b-33d0-49c8-8a4a-cfe3ddf41c4b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 760,\n    \"y\": 1020\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    note: false
    scriptarguments:
      outputformat: {}
    separatecontext: false
    task:
      brand: ''
      description: Pretty-print the contents of the playbook context
      id: dea20043-7c44-43bf-8c39-22f112ba4b45
      iscommand: false
      name: All is good
      scriptName: PrintContext
      type: regular
      version: -1
    taskid: dea20043-7c44-43bf-8c39-22f112ba4b45
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 320,\n    \"y\": 1030\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      extend-context:
        simple: CheckGcrValid=.
      input:
        simple: gcr.io/google-containers/busybox:1.27
      trust_any_certificate:
        simple: 'yes'
      use_system_proxy:
        simple: 'no'
    separatecontext: false
    task:
      brand: ''
      description: Check if a docker image is available for performing docker pull.
        Script simulates the docker pull flow but doesn't actually pull the image.
        Returns an entry with 'ok' if all is good otherwise will return an error.
      id: f4073b55-4e19-47cf-8722-8d5d596a1182
      iscommand: false
      name: Check docker valid image (gcr.io)
      scriptName: CheckDockerImageAvailable
      type: regular
      version: -1
    taskid: f4073b55-4e19-47cf-8722-8d5d596a1182
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 900,\n    \"y\": 360\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1075,\n      \"width\": 1260,\n      \"x\": 20,\n      \"y\":\
  \ 50\n    }\n  }\n}"
