description: Check if the script works
id: STIXParserTest
inputs: []
name: STIXParserTest
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 5ecbbf97-30cf-4735-84c7-612982491c60
      iscommand: false
      name: ''
      version: -1
    taskid: 5ecbbf97-30cf-4735-84c7-612982491c60
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile: {}
      unsecure: {}
      url:
        simple: https://raw.githubusercontent.com/demisto/content/master/TestData/stix2_example.json
      username: {}
    separatecontext: false
    task:
      brand: ''
      id: c0fd2d8b-b7b7-456c-8dc7-497ec888adf3
      iscommand: false
      name: Get file
      scriptName: http
      type: regular
      version: -1
    taskid: c0fd2d8b-b7b7-456c-8dc7-497ec888adf3
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      iocXml:
        complex:
          accessor: Response.Body
          root: HttpRequest
    separatecontext: false
    task:
      brand: ''
      id: 809ce983-ccd9-475b-84a3-e032c664f5e1
      iscommand: false
      name: Run script
      scriptName: StixParser
      type: regular
      version: -1
    taskid: 809ce983-ccd9-475b-84a3-e032c664f5e1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 354b287a-d4ec-4ab5-8413-f8035b478761
      iscommand: false
      name: DONE
      type: title
      version: -1
    taskid: 354b287a-d4ec-4ab5-8413-f8035b478761
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 560,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
