description: This playbook uses the Google Chronicle Backstory integration and tests
  the various scenarios of the reputation command.
id: Google Chronicle Backstory Reputation - Test
inputs: []
name: Google Chronicle Backstory Reputation - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 1c855b81-bae7-4121-83c6-671b8810a4d2
      iscommand: false
      name: ''
      version: -1
    taskid: 1c855b81-bae7-4121-83c6-671b8810a4d2
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
      - '4'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 7bf61226-1d2e-4f2b-87b0-4568fd7dbea9
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 7bf61226-1d2e-4f2b-87b0-4568fd7dbea9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      ip:
        simple: 23.20.239.12
    separatecontext: false
    task:
      brand: Google Chronicle Backstory
      description: Checks the reputation of an IP Address.
      id: 93c1aa4c-55be-481b-80a8-dd28ca782cd2
      iscommand: true
      name: IP
      script: Google Chronicle Backstory|||ip
      type: regular
      version: -1
    taskid: 93c1aa4c-55be-481b-80a8-dd28ca782cd2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Indicator
                root: DBotScore
                transformers:
                - operator: uniq
          operator: isEqualString
          right:
            value:
              simple: 23.20.239.12
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Type
                root: DBotScore
                transformers:
                - operator: uniq
          operator: isEqualString
          right:
            value:
              simple: ip
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Vendor
                root: DBotScore
                transformers:
                - operator: uniq
          operator: isEqualString
          right:
            value:
              simple: Google Chronicle Backstory
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Score
                root: DBotScore
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Address
                root: IP
                transformers:
                - operator: uniq
          operator: isEqualString
          right:
            value:
              simple: 23.20.239.12
      - - left:
            iscontext: true
            value:
              complex:
                accessor: IP.IoCQueried
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isEqualString
          right:
            value:
              simple: 23.20.239.12
      - - left:
            iscontext: true
            value:
              complex:
                accessor: IP.Sources.Address.IpAddress
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isEqualString
          right:
            value:
              simple: 23.20.239.12
      - - left:
            iscontext: true
            value:
              complex:
                accessor: IP.Sources.Category
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: IP.Sources.ConfidenceScore
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: IP.Sources.FirstAccessedTime
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: IP.Sources.FirstAccessedTime
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: IP.Sources.LastAccessedTime
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: IP.Sources.Severity
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: b8de4270-0440-4f0f-8433-e18550b4ca07
      iscommand: false
      name: Verify result for IP reputation command
      type: condition
      version: -1
    taskid: b8de4270-0440-4f0f-8433-e18550b4ca07
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      domain:
        simple: bing.com
    separatecontext: false
    task:
      brand: Google Chronicle Backstory
      description: Checks the reputation of the domain.
      id: 9e1d6c6c-dbaa-45a8-80b0-301b0542593c
      iscommand: true
      name: Domain
      script: Google Chronicle Backstory|||domain
      type: regular
      version: -1
    taskid: 9e1d6c6c-dbaa-45a8-80b0-301b0542593c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Indicator
                root: DBotScore
                transformers:
                - operator: uniq
          operator: isEqualString
          right:
            value:
              simple: bing.com
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Type
                root: DBotScore
                transformers:
                - operator: uniq
          operator: isEqualString
          right:
            value:
              simple: domain
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Vendor
                root: DBotScore
                transformers:
                - operator: uniq
          operator: isEqualString
          right:
            value:
              simple: Google Chronicle Backstory
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Score
                root: DBotScore
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Name
                root: Domain
                transformers:
                - operator: uniq
          operator: isEqualString
          right:
            value:
              simple: bing.com
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Domain.IoCQueried
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isEqualString
          right:
            value:
              simple: bing.com
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Domain.Sources.Address.Domain
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isEqualString
          right:
            value:
              simple: bing.com
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Domain.Sources.Category
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Domain.Sources.ConfidenceScore
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Domain.Sources.FirstAccessedTime
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Domain.Sources.LastAccessedTime
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Domain.Sources.Severity
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      label: 'yes'
    id: '5'
    ignoreworker: false
    nexttasks:
      'yes':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 9dc042be-c434-42b0-8132-2cee52b2ac27
      iscommand: false
      name: Verify result for Domain reputation command
      type: condition
      version: -1
    taskid: 9dc042be-c434-42b0-8132-2cee52b2ac27
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: ff07973b-96b4-42de-89ff-a0d0d3668a2d
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: ff07973b-96b4-42de-89ff-a0d0d3668a2d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 720\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: d0b591ad-0916-42e1-864b-b24138be24c6
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: d0b591ad-0916-42e1-864b-b24138be24c6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 895\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d99ce9e0-ba36-45a4-81c5-1885797d0b2c
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d99ce9e0-ba36-45a4-81c5-1885797d0b2c
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1070\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1085,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
