description: This playbook uses the Google Chronicle Backstory integration and tests
  the various scenarios of the "gcb-assets" command.
id: Google Chronicle Backstory Asset - Test
inputs: []
name: Google Chronicle Backstory Asset - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 48af2d43-f908-4857-8fae-1f857677de14
      iscommand: false
      name: ''
      version: -1
    taskid: 48af2d43-f908-4857-8fae-1f857677de14
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 50\n  }\n}"
  '1':
    continueonerror: true
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      artifact_value:
        simple: www.google.com
      end_time: {}
      page_size: {}
      preset_time_range: {}
      start_time: {}
    separatecontext: false
    task:
      brand: Google Chronicle Backstory
      description: This command will respond with a list of the assets which accessed
        the input artifact (ip, domain, md5, sha1, sha256) during the specified time.
      id: f2fa2107-51d2-41c0-87df-f570e5ec454b
      iscommand: true
      name: Get Assets list
      script: Google Chronicle Backstory|||gcb-assets
      type: regular
      version: -1
    taskid: f2fa2107-51d2-41c0-87df-f570e5ec454b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 370\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      'yes':
      - '11'
    note: false
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    task:
      brand: ''
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: c9a57a20-a070-4c4a-8308-e995f07148fd
      iscommand: false
      name: Is error?
      scriptName: isError
      type: condition
      version: -1
    taskid: c9a57a20-a070-4c4a-8308-e995f07148fd
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 8273ac18-c2b2-4c79-8293-1d691322d3d6
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 8273ac18-c2b2-4c79-8293-1d691322d3d6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 720\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 601519ca-10ca-4956-807e-e283d97ae61c
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 601519ca-10ca-4956-807e-e283d97ae61c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 895\n  }\n}"
  '2':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Asset.AccessedDomain
                root: GoogleChronicleBackstory
          operator: containsGeneral
          right:
            value:
              simple: www.google.com
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Asset.FirstAccessedTime
                root: GoogleChronicleBackstory
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Asset.LastAccessedTime
                root: GoogleChronicleBackstory
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Asset.HostName
                root: GoogleChronicleBackstory
          operator: isExists
        - left:
            iscontext: true
            value:
              complex:
                accessor: Asset.IpAddress
                root: GoogleChronicleBackstory
          operator: isExists
        - left:
            iscontext: true
            value:
              complex:
                accessor: Asset.MacAddress
                root: GoogleChronicleBackstory
          operator: isExists
        - left:
            iscontext: true
            value:
              complex:
                accessor: Asset.ProductId
                root: GoogleChronicleBackstory
          operator: isExists
      label: 'yes'
    id: '2'
    ignoreworker: false
    nexttasks:
      'yes':
      - '11'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: 286e6e68-7c92-4224-84b4-5d63884db417
      iscommand: false
      name: Verify
      type: condition
      version: -1
    taskid: 286e6e68-7c92-4224-84b4-5d63884db417
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 23e7a9ef-2033-4a28-8569-52ef3cf95b26
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 23e7a9ef-2033-4a28-8569-52ef3cf95b26
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 1070\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
      - '5'
      - '7'
      - '9'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 5afc6ca7-c5cd-4b4e-8fe8-56dee19c3686
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 5afc6ca7-c5cd-4b4e-8fe8-56dee19c3686
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 195\n  }\n}"
  '5':
    continueonerror: true
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      artifact_value:
        simple: www.google.com
      end_time: {}
      page_size:
        simple: '0'
      start_time: {}
    separatecontext: false
    task:
      brand: Google Chronicle Backstory
      description: This command will respond with a list of the assets which accessed
        the input artifact (ip, domain, md5, sha1, sha256) during the specified time.
      id: 3f62dd64-f446-4271-81f9-63a10eb1c409
      iscommand: true
      name: Invalid page size argument
      script: Google Chronicle Backstory|||gcb-assets
      type: regular
      version: -1
    taskid: 3f62dd64-f446-4271-81f9-63a10eb1c409
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 370\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      'yes':
      - '11'
    note: false
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    task:
      brand: ''
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 62ea068d-09a3-4ddf-88f8-4323ed0470e6
      iscommand: false
      name: Is error?
      scriptName: isError
      type: condition
      version: -1
    taskid: 62ea068d-09a3-4ddf-88f8-4323ed0470e6
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 545\n  }\n}"
  '7':
    continueonerror: true
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      artifact_value:
        simple: www.google.com
      end_time: {}
      page_size: {}
      preset_time_range: {}
      start_time:
        simple: '2020'
    separatecontext: false
    task:
      brand: Google Chronicle Backstory
      description: This command will respond with a list of the assets which accessed
        the input artifact (ip, domain, md5, sha1, sha256) during the specified time.
      id: 9dfb2427-7dd7-443e-8e2c-85b3fc9105c5
      iscommand: true
      name: Invalid start date argument
      script: Google Chronicle Backstory|||gcb-assets
      type: regular
      version: -1
    taskid: 9dfb2427-7dd7-443e-8e2c-85b3fc9105c5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      'yes':
      - '11'
    note: false
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    task:
      brand: ''
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: ba6f0389-3fc3-4920-8a36-24580c3b71c1
      iscommand: false
      name: Is error?
      scriptName: isError
      type: condition
      version: -1
    taskid: ba6f0389-3fc3-4920-8a36-24580c3b71c1
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '9':
    continueonerror: true
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      artifact_value:
        simple: www.google.com
      end_time:
        simple: '2020'
      page_size: {}
      preset_time_range: {}
      start_time: {}
    separatecontext: false
    task:
      brand: Google Chronicle Backstory
      description: This command will respond with a list of the assets which accessed
        the input artifact (ip, domain, md5, sha1, sha256) during the specified time.
      id: f113c74b-88c2-42b3-8ee9-42184dc5357b
      iscommand: true
      name: Invalid end date argument
      script: Google Chronicle Backstory|||gcb-assets
      type: regular
      version: -1
    taskid: f113c74b-88c2-42b3-8ee9-42184dc5357b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1085,\n      \"width\": 1670,\n      \"x\": 50,\n      \"y\":\
  \ 50\n    }\n  }\n}"
