description: This playbook uses the Google Chronicle Backstory integration and tests
  the various scenarios of the "gcb-list-iocs" command.
id: Google Chronicle Backstory List IOCs - Test
inputs: []
name: Google Chronicle Backstory List IOCs - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: e0bf41ff-38f9-460c-8f0f-6c4570fee4f8
      iscommand: false
      name: ''
      version: -1
    taskid: e0bf41ff-38f9-460c-8f0f-6c4570fee4f8
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
      - '5'
      - '7'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 37ac2c94-7278-437b-806a-4b5be222da96
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 37ac2c94-7278-437b-806a-4b5be222da96
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 6c7c3c53-4641-4fe8-8ef5-322f4de04079
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 6c7c3c53-4641-4fe8-8ef5-322f4de04079
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 895\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      page_size:
        simple: '3'
      start_time: {}
    separatecontext: false
    task:
      brand: Google Chronicle Backstory
      description: List all of the IoCs discovered within your enterprise within the
        specified time range.
      id: fe36dedb-affa-43df-81be-e39fbac23eb8
      iscommand: true
      name: Get list of IoCs
      script: Google Chronicle Backstory|||gcb-list-iocs
      type: regular
      version: -1
    taskid: fe36dedb-affa-43df-81be-e39fbac23eb8
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Name
                root: Domain
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Iocs.Artifact
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Iocs.IocIngestTime
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Iocs.FirstAccessedTime
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Iocs.LastAccessedTime
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Iocs.Sources.Category
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Iocs.Sources.IntRawConfidenceScore
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Iocs.Sources.NormalizedConfidenceScore
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Iocs.Sources.RawSeverity
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Iocs.Sources.Source
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '9'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 3a496ee1-89b0-4ce3-8882-af0075f635fa
      iscommand: false
      name: Verify results
      type: condition
      version: -1
    taskid: 3a496ee1-89b0-4ce3-8882-af0075f635fa
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 7523827b-50b9-4379-8515-14d558d5dc39
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 7523827b-50b9-4379-8515-14d558d5dc39
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1070\n  }\n}"
  '5':
    continueonerror: true
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      page_size:
        simple: 1a
      preset_time_range: {}
      start_time: {}
    separatecontext: false
    task:
      brand: Google Chronicle Backstory
      description: List all of the IoCs discovered within your enterprise within the
        specified time range.
      id: 26d0890f-773e-4560-8764-f63d6083637f
      iscommand: true
      name: Invalid page size argument
      script: Google Chronicle Backstory|||gcb-list-iocs
      type: regular
      version: -1
    taskid: 26d0890f-773e-4560-8764-f63d6083637f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      'yes':
      - '9'
    note: false
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    task:
      brand: ''
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 7943d48b-3364-4e7a-815b-a814af179b71
      iscommand: false
      name: Is error?
      scriptName: isError
      type: condition
      version: -1
    taskid: 7943d48b-3364-4e7a-815b-a814af179b71
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '7':
    continueonerror: true
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      page_size: {}
      start_time:
        simple: 2020-01-01 00:00:00
    separatecontext: false
    task:
      brand: Google Chronicle Backstory
      description: List all of the IoCs discovered within your enterprise within the
        specified time range.
      id: 2df2d226-8733-4378-8083-b2eaa0faf1e6
      iscommand: true
      name: Invalid start time argument
      script: Google Chronicle Backstory|||gcb-list-iocs
      type: regular
      version: -1
    taskid: 2df2d226-8733-4378-8083-b2eaa0faf1e6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 370\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      'yes':
      - '9'
    note: false
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    task:
      brand: ''
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 81ae629f-3ca3-4f06-853a-994f95bd9adc
      iscommand: false
      name: Is error?
      scriptName: isError
      type: condition
      version: -1
    taskid: 81ae629f-3ca3-4f06-853a-994f95bd9adc
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 545\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 0cce4e4f-461f-4ffd-835f-3d3a6c550a6c
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 0cce4e4f-461f-4ffd-835f-3d3a6c550a6c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 720\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"6_9_yes\": 0.4\n  },\n  \"paper\": {\n\
  \    \"dimensions\": {\n      \"height\": 1085,\n      \"width\": 1240,\n      \"\
  x\": 50,\n      \"y\": 50\n    }\n  }\n}"
