description: This playbook uses the Google Chronicle Backstory integration and tests
  the various scenarios of the "gcb-list-alerts" command.
id: Google Chronicle Backstory List Alerts - Test
inputs: []
name: Google Chronicle Backstory List Alerts - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: ffd315ca-1056-48bf-8dd3-dcb69440e516
      iscommand: false
      name: ''
      version: -1
    taskid: ffd315ca-1056-48bf-8dd3-dcb69440e516
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
      - '5'
      - '7'
      - '9'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 34f048a0-1324-4714-861e-6ef92d19b341
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 34f048a0-1324-4714-861e-6ef92d19b341
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      'yes':
      - '11'
    note: false
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    task:
      brand: ''
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 1727fb71-c5d8-4a6b-83b9-752e5c22c348
      iscommand: false
      name: Is Error?
      scriptName: isError
      type: condition
      version: -1
    taskid: 1727fb71-c5d8-4a6b-83b9-752e5c22c348
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 545\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: d40ca4b9-0936-4650-83ce-a53ca8af148e
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: d40ca4b9-0936-4650-83ce-a53ca8af148e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 720\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      emailclassification: {}
      id: {}
      phishingsubtype: {}
    separatecontext: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: f3c994bc-2065-421c-87f1-0e776fe2da63
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: f3c994bc-2065-421c-87f1-0e776fe2da63
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 895\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 11e71dbb-7013-43f4-89fa-a33d869a3301
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 11e71dbb-7013-43f4-89fa-a33d869a3301
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 1070\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      end_time: {}
      page_size: {}
      preset_time_range: {}
      severity: {}
      start_time: {}
    separatecontext: false
    task:
      brand: Google Chronicle Backstory
      description: List all the alerts tracked within your enterprise for the specified
        time range. Both the parsed alerts and their corresponding raw alert logs
        are returned.
      id: 36a0c0d0-8a93-475a-8292-0a160c8c994b
      iscommand: true
      name: Get list of alerts
      script: Google Chronicle Backstory|||gcb-list-alerts
      type: regular
      version: -1
    taskid: 36a0c0d0-8a93-475a-8292-0a160c8c994b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Alert.AssetName
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Alert.AlertInfo.Name
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Alert.AlertInfo.Severity
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Alert.AlertInfo.SourceProduct
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Alert.AlertInfo.Timestamp
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Alert.AlertCounts
                root: GoogleChronicleBackstory
                transformers:
                - operator: uniq
          operator: isExists
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '11'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 2dcb9543-7584-4487-876a-94f55a318d22
      iscommand: false
      name: Verify Result
      type: condition
      version: -1
    taskid: 2dcb9543-7584-4487-876a-94f55a318d22
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '5':
    continueonerror: true
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      end_time: {}
      page_size: {}
      preset_time_range: {}
      severity: {}
      start_time:
        simple: 2020-01-01 00:00:00
    separatecontext: false
    task:
      brand: Google Chronicle Backstory
      description: List all the alerts tracked within your enterprise for the specified
        time range. Both the parsed alerts and their corresponding raw alert logs
        are returned.
      id: b245ebdf-bb92-40a8-8efa-a237081ba23c
      iscommand: true
      name: Invalid start time argument
      script: Google Chronicle Backstory|||gcb-list-alerts
      type: regular
      version: -1
    taskid: b245ebdf-bb92-40a8-8efa-a237081ba23c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      'yes':
      - '11'
    note: false
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    task:
      brand: ''
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: c536235a-73d7-40d3-8d4d-ceb6750e1ffe
      iscommand: false
      name: Is Error?
      scriptName: isError
      type: condition
      version: -1
    taskid: c536235a-73d7-40d3-8d4d-ceb6750e1ffe
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '7':
    continueonerror: true
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      end_time: {}
      page_size:
        simple: 1a
      preset_time_range: {}
      severity: {}
      start_time: {}
    separatecontext: false
    task:
      brand: Google Chronicle Backstory
      description: List all the alerts tracked within your enterprise for the specified
        time range. Both the parsed alerts and their corresponding raw alert logs
        are returned.
      id: 50fa9767-adc9-4c2c-827c-624aa8781bf8
      iscommand: true
      name: Invalid page size argument
      script: Google Chronicle Backstory|||gcb-list-alerts
      type: regular
      version: -1
    taskid: 50fa9767-adc9-4c2c-827c-624aa8781bf8
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 370\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      'yes':
      - '11'
    note: false
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    task:
      brand: ''
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: 1476195e-6f4b-4e6c-89c2-e554458e2839
      iscommand: false
      name: Is Error?
      scriptName: isError
      type: condition
      version: -1
    taskid: 1476195e-6f4b-4e6c-89c2-e554458e2839
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 545\n  }\n}"
  '9':
    continueonerror: true
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      end_time: {}
      page_size: {}
      preset_time_range:
        simple: Last 8 days
      severity: {}
      start_time: {}
    separatecontext: false
    task:
      brand: Google Chronicle Backstory
      description: List all the alerts tracked within your enterprise for the specified
        time range. Both the parsed alerts and their corresponding raw alert logs
        are returned.
      id: 7e681bd6-fc02-4c64-8cc3-a136bddbac12
      iscommand: true
      name: Invalid preset time range argument
      script: Google Chronicle Backstory|||gcb-list-alerts
      type: regular
      version: -1
    taskid: 7e681bd6-fc02-4c64-8cc3-a136bddbac12
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 370\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"10_11_yes\": 0.3,\n    \"3_11_yes\":\
  \ 0.44,\n    \"6_11_yes\": 0.38,\n    \"8_11_yes\": 0.5\n  },\n  \"paper\": {\n\
  \    \"dimensions\": {\n      \"height\": 1085,\n      \"width\": 1670,\n      \"\
  x\": 50,\n      \"y\": 50\n    }\n  }\n}"
