description: ''
fromversion: 3.5.0
id: get_file_sample_by_hash_-_cylance_protect_-_test
inputs: []
name: Get File Sample By Hash - Cylance Protect - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: b4e8ef9f-c463-45d5-8798-facca14978c6
      iscommand: false
      name: ''
      version: -1
    taskid: b4e8ef9f-c463-45d5-8798-facca14978c6
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '2':
    id: '2'
    note: false
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: File.EntryID
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: c72ea6b4-a3e1-4d28-8271-5777873b1a85
      iscommand: false
      name: Verify output
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: c72ea6b4-a3e1-4d28-8271-5777873b1a85
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 5b021f07-65f4-4734-89e3-121ec397cb83
      iscommand: false
      name: Clear Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 5b021f07-65f4-4734-89e3-121ec397cb83
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      append: {}
      key:
        simple: File.SHA256
      value:
        simple: 5da547e87d6ef12349fb4dbba9cf3146a358e284f72361dd07bbabfc95b0bac3
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 901737e8-d0da-4864-8ed7-abedebd837cc
      iscommand: false
      name: add hash to context
      scriptName: Set
      type: regular
      version: -1
    taskid: 901737e8-d0da-4864-8ed7-abedebd837cc
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      append:
        simple: 'true'
      key:
        simple: File.SHA256
      value:
        simple: ed01ebfbc9eb5bbea545af4d01bf5f1071661840480439c6e5babe8e080e41aa
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 319cc4d2-b0f5-4b3f-87cd-4dad905a1fba
      iscommand: false
      name: add hash to context
      scriptName: Set
      type: regular
      version: -1
    taskid: 319cc4d2-b0f5-4b3f-87cd-4dad905a1fba
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '6':
    id: '6'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      SHA256:
        simple: ${File.SHA256}
      ZipPassword:
        simple: infected
    separatecontext: true
    task:
      brand: ''
      description: Returns to the war-room a file sample correlating to SHA256 hashes
        in the inputs using Cylance Protect integration
      id: 09206cc7-b59b-451a-8f10-776e4416d7a5
      iscommand: false
      name: Get File Sample By Hash - Cylance Protect
      playbookName: Get File Sample By Hash - Cylance Protect
      type: playbook
      version: -1
    taskid: 09206cc7-b59b-451a-8f10-776e4416d7a5
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 725\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 940,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
