id: Beta-Athena-Test
inputs: []
name: Beta-Athena-Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: c8fef65f-4455-4504-8743-1bbea18b650b
      iscommand: false
      name: ''
      version: -1
    taskid: c8fef65f-4455-4504-8743-1bbea18b650b
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    note: false
    scriptarguments:
      ClientRequestToken: {}
      Database: {}
      EncryptionOption: {}
      KmsKey: {}
      OutputLocation:
        simple: s3://aws-athena-query-results-120785635586-us-east-2.unknown
      QueryString:
        simple: "SELECT\n request_timestamp,\n elb_name,\n backend_ip,\n backend_response_code\n\
          FROM elb_logs\nWHERE backend_response_code LIKE '4%' OR\n      backend_response_code\
          \ LIKE '5%'\nLIMIT 100;"
      WorkGroup: {}
      region: {}
      roleArn: {}
      roleSessionDuration: {}
      roleSessionName: {}
    separatecontext: false
    task:
      brand: ''
      description: Start Athena Query.
      id: c5a4913a-9bfe-44f8-8ae7-242e5866d8ce
      iscommand: true
      name: aws-athena-start-query
      script: '|||aws-athena-start-query'
      type: regular
      version: -1
    taskid: c5a4913a-9bfe-44f8-8ae7-242e5866d8ce
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 230\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 275,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\": 50\n\
  \    }\n  }\n}"
