id: PhishlabsIOC_EIR-Test
inputs: []
name: PhishlabsIOC_EIR-Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 307bc320-87f0-4a07-8989-a40b3ca44aaf
      iscommand: false
      name: ''
      version: -1
    taskid: 307bc320-87f0-4a07-8989-a40b3ca44aaf
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: fccbaeb4-f8b7-4e5f-8c31-75d3a77f73d1
      iscommand: false
      name: Delete entry context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: fccbaeb4-f8b7-4e5f-8c31-75d3a77f73d1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      message:
        simple: ${PhishLabsIOC.EIR}
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: 88d03f2c-e681-453f-8e4b-ecc8a38cc1e2
      iscommand: false
      name: PrintErrorEntry
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 88d03f2c-e681-453f-8e4b-ecc8a38cc1e2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1245\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    note: false
    scriptarguments:
      add_to_context:
        simple: 'true'
      brand_name:
        simple: PhishLabs IOC EIR
      error_msg_in_incident: {}
      expect_data: {}
      instance_name: {}
    separatecontext: false
    task:
      brand: ''
      description: Execute FetchIncident for a given instance
      id: 02a0e461-fd59-4d28-82bd-cb7d89a35643
      iscommand: false
      name: Fetch incidents command
      scriptName: FetchFromInstance
      type: regular
      version: -1
    taskid: 02a0e461-fd59-4d28-82bd-cb7d89a35643
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1420\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      incident_id:
        simple: INC0660932
    separatecontext: false
    task:
      brand: ''
      description: Returns a single Incident based on the given ID.
      id: 59f37176-09a0-4c7a-83b9-31cac4ed3024
      iscommand: true
      name: Get incident by ID command
      script: '|||phishlabs-ioc-eir-get-incident-by-id'
      type: regular
      version: -1
    taskid: 59f37176-09a0-4c7a-83b9-31cac4ed3024
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: PhishLabsIOC.EIR.CaseType
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: PhishLabsIOC.EIR.Email.EmailBody
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: PhishLabsIOC.EIR.Email.URL.URL
          operator: isExists
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '8'
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: c18c12e3-a92e-4c82-81dc-3d58d227504a
      iscommand: false
      name: 'Check get incident by id '
      type: condition
      version: -1
    taskid: c18c12e3-a92e-4c82-81dc-3d58d227504a
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      outputformat:
        simple: ${PhishLabsIOC.EIR}
    separatecontext: false
    task:
      brand: ''
      description: Pretty-print the contents of the playbook context
      id: 2461030a-0767-4af6-87af-213094bc1b99
      iscommand: false
      name: PrintContext
      scriptName: PrintContext
      type: regular
      version: -1
    taskid: 2461030a-0767-4af6-87af-213094bc1b99
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      closed_after: {}
      closed_before: {}
      created_after: {}
      created_before: {}
      direction: {}
      limit:
        simple: '3'
      offset: {}
      sort: {}
      status: {}
    separatecontext: false
    task:
      brand: ''
      description: Get EIR incidents from PhishLabs-IOC EIR service (dafault limit
        50 incidents)
      id: 5d7452dc-3ddc-4fc0-8faa-622dce882e97
      iscommand: true
      name: Get incidents command
      script: '|||phishlabs-ioc-eir-get-incidents'
      type: regular
      version: -1
    taskid: 5d7452dc-3ddc-4fc0-8faa-622dce882e97
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 895\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      outputformat:
        simple: ${PhishLabsIOC.EIR}
    separatecontext: false
    task:
      brand: ''
      description: Pretty-print the contents of the playbook context
      id: ecedc27e-847c-44ac-835d-04a2e40875e5
      iscommand: false
      name: PrintContext
      scriptName: PrintContext
      type: regular
      version: -1
    taskid: ecedc27e-847c-44ac-835d-04a2e40875e5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      message:
        simple: ${PhishLabsIOC.EIR}
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: 74f7cf9e-2338-4fcc-8927-5a808bb5a143
      iscommand: false
      name: PrintErrorEntry
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 74f7cf9e-2338-4fcc-8927-5a808bb5a143
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 720\n  }\n}"
  '9':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: PhishLabsIOC.EIR.CaseType
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: PhishLabsIOC.EIR.Email.EmailBody
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: PhishLabsIOC.EIR.Email.URL.URL
          operator: isExists
      label: 'yes'
    id: '9'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '10'
      'yes':
      - '7'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: ec1c7a0c-1876-42d3-8f5c-c39ab054e635
      iscommand: false
      name: Check get incidents command
      type: condition
      version: -1
    taskid: ec1c7a0c-1876-42d3-8f5c-c39ab054e635
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1070\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1465,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
