id: PhishLabsIOC TestPlaybook
inputs: []
name: PhishLabsIOC TestPlaybook
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: c228a70e-49c7-4fb4-8030-a34ccbf4658f
      iscommand: false
      name: ''
      version: -1
    taskid: c228a70e-49c7-4fb4-8030-a34ccbf4658f
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 79cf305b-123e-4fb4-8ead-6a8928a9430e
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 79cf305b-123e-4fb4-8ead-6a8928a9430e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '10':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: URL.Data
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: PhishLabs.URL.Data
          operator: isExists
      label: 'yes'
    id: '10'
    ignoreworker: false
    nexttasks:
      'yes':
      - '11'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 488b5c59-2dfe-4b8e-8f9a-d818695939be
      iscommand: false
      name: Verify URL
      type: condition
      version: -1
    taskid: 488b5c59-2dfe-4b8e-8f9a-d818695939be
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '11':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Body
                root: Email
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: PhishLabs.Email.Body
          operator: isExists
      label: 'yes'
    id: '11'
    ignoreworker: false
    nexttasks:
      'yes':
      - '12'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 2657556a-64b1-4d19-8862-dcd489cb6284
      iscommand: false
      name: Verify Email
      type: condition
      version: -1
    taskid: 2657556a-64b1-4d19-8862-dcd489cb6284
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1945\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    scriptarguments:
      delete_false_positive: {}
      indicator_type: {}
      limit:
        simple: '5'
      since:
        simple: 365d
    separatecontext: false
    task:
      brand: ''
      description: Populate indicators by the PhishLabs IOC  global feed.
      id: c2ca0e75-3665-4e05-83ff-b11704efba59
      iscommand: false
      name: Populate indicators
      scriptName: PhishLabsPopulateIndicators
      type: regular
      version: -1
    taskid: c2ca0e75-3665-4e05-83ff-b11704efba59
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2120\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    scriptarguments:
      extend-context:
        simple: Source=source
      fromdate: {}
      query:
        simple: source:PhishLabs
      size: {}
      todate: {}
      value: {}
    separatecontext: false
    task:
      brand: Builtin
      description: Finds all indicators with given value.
      id: 6ab137a1-87a7-4c9e-8899-21528966233e
      iscommand: true
      name: Find indicators
      script: Builtin|||findIndicators
      type: regular
      version: -1
    taskid: 6ab137a1-87a7-4c9e-8899-21528966233e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2470\n  }\n}"
  '14':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${Source}
          operator: containsGeneral
          right:
            value:
              simple: PhishLabs
      label: 'yes'
    id: '14'
    ignoreworker: false
    nexttasks:
      'yes':
      - '15'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Verify given entry contains a string
      id: 2f23e4d3-f96d-4ce5-8f5a-ede527204092
      iscommand: false
      name: Verify PhishLabs indicators
      type: condition
      version: -1
    taskid: 2f23e4d3-f96d-4ce5-8f5a-ede527204092
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2645\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    scriptarguments:
      add_to_context: {}
      brand_name:
        simple: PhishLabs IOC
      error_msg_in_incident: {}
      expect_data: {}
      instance_name: {}
    separatecontext: false
    task:
      brand: ''
      description: Execute FetchIncident for a given instance
      id: 8bda41c9-a965-4568-8344-4b2b5bac465b
      iscommand: false
      name: Test fetch
      scriptName: FetchFromInstance
      type: regular
      version: -1
    taskid: 8bda41c9-a965-4568-8344-4b2b5bac465b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2820\n  }\n}"
  '16':
    id: '16'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 5378cd4e-edbc-4a0c-88ec-6e99d080c9a8
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 5378cd4e-edbc-4a0c-88ec-6e99d080c9a8
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2995\n  }\n}"
  '17':
    id: '17'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    scriptarguments:
      seconds:
        simple: '5'
    separatecontext: false
    task:
      brand: ''
      description: Sleep for X seconds
      id: b702f545-7c3a-4a52-8a8a-f221683f3c1a
      iscommand: false
      name: Sleep
      scriptName: Sleep
      type: regular
      version: -1
    taskid: b702f545-7c3a-4a52-8a8a-f221683f3c1a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2295\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      false_positive: {}
      indicator_type:
        simple: URL
      limit:
        simple: '5'
      offset: {}
      remove_protocol: {}
      remove_query: {}
      since:
        simple: 365d
    separatecontext: false
    task:
      brand: PhishLabs IOC
      description: Gets the global IOC feed from PhishLabs
      id: 5d25254b-150f-4285-8d61-7e3517af1e31
      iscommand: true
      name: Global Feed - URL
      script: PhishLabs IOC|||phishlabs-global-feed
      type: regular
      version: -1
    taskid: 5d25254b-150f-4285-8d61-7e3517af1e31
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: URL.Data
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: PhishLabs.URL.Data
          operator: isExists
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d9183c47-b44a-45ef-82f4-2a8c04511ee6
      iscommand: false
      name: Verify URL
      type: condition
      version: -1
    taskid: d9183c47-b44a-45ef-82f4-2a8c04511ee6
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      false_positive: {}
      indicator_type:
        simple: Domain
      limit:
        simple: '5'
      offset: {}
      remove_protocol: {}
      remove_query: {}
      since:
        simple: 365d
    separatecontext: false
    task:
      brand: PhishLabs IOC
      description: Gets the global IOC feed from PhishLabs
      id: 83668330-28c6-4d92-8d4e-4193afda7ea3
      iscommand: true
      name: Global Feed - Domain
      script: PhishLabs IOC|||phishlabs-global-feed
      type: regular
      version: -1
    taskid: 83668330-28c6-4d92-8d4e-4193afda7ea3
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Domain.Name
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: PhishLabs.Domain.Name
          operator: isExists
      label: 'yes'
    id: '5'
    ignoreworker: false
    nexttasks:
      'yes':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 0780ff29-df34-4929-84fa-e61a1228a9ad
      iscommand: false
      name: Verify Domain
      type: condition
      version: -1
    taskid: 0780ff29-df34-4929-84fa-e61a1228a9ad
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      false_positive: {}
      indicator_type:
        simple: Attachment
      limit:
        simple: '5'
      offset: {}
      remove_protocol: {}
      remove_query: {}
      since:
        simple: 365d
    separatecontext: false
    task:
      brand: PhishLabs IOC
      description: Gets the global IOC feed from PhishLabs
      id: 67ef59fd-0605-4da3-8be8-8931afd0f61e
      iscommand: true
      name: Global Feed - Attachment
      script: PhishLabs IOC|||phishlabs-global-feed
      type: regular
      version: -1
    taskid: 67ef59fd-0605-4da3-8be8-8931afd0f61e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '7':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: File.MD5
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: PhishLabs.File.MD5
          operator: isExists
      label: 'yes'
    id: '7'
    ignoreworker: false
    nexttasks:
      'yes':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: f36e5da2-cb32-40fb-86a7-8da357f576a3
      iscommand: false
      name: Verify File
      type: condition
      version: -1
    taskid: f36e5da2-cb32-40fb-86a7-8da357f576a3
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 62a354b8-b52a-4606-85fa-9584902a3758
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 62a354b8-b52a-4606-85fa-9584902a3758
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      id: {}
      incident_id:
        simple: INC0015516
      indicator_type: {}
      indicators_classification: {}
      limit: {}
      offset: {}
      remove_protocol: {}
      remove_query: {}
      since:
        simple: 720d
    separatecontext: false
    task:
      brand: PhishLabs IOC
      description: Gets indicators from a speicifed PhishLabs incident.
      id: 48d2cc22-1bb5-49ce-8714-082e4ee2e19c
      iscommand: true
      name: Get incident indicators
      script: PhishLabs IOC|||phishlabs-get-incident-indicators
      type: regular
      version: -1
    taskid: 48d2cc22-1bb5-49ce-8714-082e4ee2e19c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 3010,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
