id: PhishlabsIOC_DRP-Test
inputs: []
name: PhishlabsIOC_DRP-Test
outputs: []
sourceplaybookid: PhishlabsIOC_EIR-Test
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 307bc320-87f0-4a07-8989-a40b3ca44aaf
      iscommand: false
      name: ''
      version: -1
    taskid: 307bc320-87f0-4a07-8989-a40b3ca44aaf
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: fccbaeb4-f8b7-4e5f-8c31-75d3a77f73d1
      iscommand: false
      name: Delete entry context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: fccbaeb4-f8b7-4e5f-8c31-75d3a77f73d1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      message:
        simple: ${PhishLabsIOC.EIR}
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: 88d03f2c-e681-453f-8e4b-ecc8a38cc1e2
      iscommand: false
      name: PrintErrorEntry
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 88d03f2c-e681-453f-8e4b-ecc8a38cc1e2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    note: false
    scriptarguments:
      add_to_context:
        simple: 'true'
      brand_name:
        simple: PhishLabs IOC DRP
      error_msg_in_incident: {}
      expect_data: {}
      instance_name: {}
    separatecontext: false
    task:
      brand: ''
      description: Execute FetchIncident for a given instance
      id: f6e06d03-afa4-4459-8cbe-93f74564664d
      iscommand: false
      name: Fetch incidents command
      scriptName: FetchFromInstance
      type: regular
      version: -1
    taskid: f6e06d03-afa4-4459-8cbe-93f74564664d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 2470\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    scriptarguments:
      begin_date: {}
      case_type: {}
      date_field: {}
      end_date: {}
      max_records:
        simple: '3'
      offset: {}
      status: {}
    separatecontext: false
    task:
      brand: ''
      description: Get open cases of Phishlabs DRP service by filters
      id: 0598d738-a6ff-420d-8749-9c7c0a99db17
      iscommand: true
      name: Get open cases command
      script: '|||phishlabs-ioc-drp-get-open-cases'
      type: regular
      version: -1
    taskid: 0598d738-a6ff-420d-8749-9c7c0a99db17
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1420\n  }\n}"
  '13':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: PhishLabsIOC.DRP.CaseID
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: PhishLabsIOC.DRP.CaseNumber
          operator: isExists
      label: 'yes'
    id: '13'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '15'
      'yes':
      - '14'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: a24302fb-4720-4dd6-8041-35b31813e466
      iscommand: false
      name: Check get open cases command
      type: condition
      version: -1
    taskid: a24302fb-4720-4dd6-8041-35b31813e466
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1595\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    scriptarguments:
      outputformat:
        simple: ${PhishlabsIOC.DRP}
    separatecontext: false
    task:
      brand: ''
      description: Pretty-print the contents of the playbook context
      id: cdac0ad4-9e92-41bb-872c-f70e8e8a4f91
      iscommand: false
      name: PrintContext
      scriptName: PrintContext
      type: regular
      version: -1
    taskid: cdac0ad4-9e92-41bb-872c-f70e8e8a4f91
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    scriptarguments:
      message: {}
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: fbe3b4e7-1dac-4311-874e-70a6f274be63
      iscommand: false
      name: PrintErrorEntry
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: fbe3b4e7-1dac-4311-874e-70a6f274be63
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1770\n  }\n}"
  '16':
    id: '16'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    scriptarguments:
      Date_field: {}
      begin_date: {}
      case_type: {}
      end_date: {}
      max_records:
        simple: '3'
      offset: {}
      status: {}
    separatecontext: false
    task:
      brand: ''
      description: Get closed cases of Phishlabs DRP service by filters
      id: 912f0a90-769a-4d93-8495-b88784ea6aee
      iscommand: true
      name: Get closed cases command
      script: '|||phishlabs-ioc-drp-get-closed-cases'
      type: regular
      version: -1
    taskid: 912f0a90-769a-4d93-8495-b88784ea6aee
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1945\n  }\n}"
  '17':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: PhishLabsIOC.DRP.CaseID
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: PhishLabsIOC.DRP.CreatedBy.ID
          operator: isExists
      label: 'yes'
    id: '17'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '19'
      'yes':
      - '18'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 0c977881-fc19-4449-8516-a2dd902ba801
      iscommand: false
      name: Check get closed cases command
      type: condition
      version: -1
    taskid: 0c977881-fc19-4449-8516-a2dd902ba801
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 2120\n  }\n}"
  '18':
    id: '18'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      outputformat:
        simple: ${PhishlabsIOC.DRP}
    separatecontext: false
    task:
      brand: ''
      description: Pretty-print the contents of the playbook context
      id: 5ceea343-8cce-4978-8276-cf43f5cfc021
      iscommand: false
      name: PrintContext
      scriptName: PrintContext
      type: regular
      version: -1
    taskid: 5ceea343-8cce-4978-8276-cf43f5cfc021
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2295\n  }\n}"
  '19':
    id: '19'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      message: {}
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: 56ed3d53-08e0-4cd0-8c32-aa5fd73e45f4
      iscommand: false
      name: PrintErrorEntry
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 56ed3d53-08e0-4cd0-8c32-aa5fd73e45f4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2295\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      case_id:
        simple: daa1e25e-0528-11ea-94e8-0ee0a3f3cb1c
    separatecontext: false
    task:
      brand: ''
      description: Get case by ID of Phishlabs DRP service
      id: fb3aa3f0-b2cd-4bf8-8a29-8412d701e42c
      iscommand: true
      name: Get case by ID command
      script: '|||phishlabs-ioc-drp-get-case-by-id'
      type: regular
      version: -1
    taskid: fb3aa3f0-b2cd-4bf8-8a29-8412d701e42c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: PhishLabsIOC.DRP.CaseID
          operator: isExists
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '8'
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 987c7d2a-df99-48c1-8760-5958fa281d53
      iscommand: false
      name: 'Check get case by id '
      type: condition
      version: -1
    taskid: 987c7d2a-df99-48c1-8760-5958fa281d53
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      outputformat:
        simple: ${PhishLabsIOC.EIR}
    separatecontext: false
    task:
      brand: ''
      description: Pretty-print the contents of the playbook context
      id: 2461030a-0767-4af6-87af-213094bc1b99
      iscommand: false
      name: PrintContext
      scriptName: PrintContext
      type: regular
      version: -1
    taskid: 2461030a-0767-4af6-87af-213094bc1b99
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      begin_date: {}
      case_type: {}
      date_field: {}
      end_date: {}
      max_records:
        simple: '3'
      offset: {}
      status: {}
    separatecontext: false
    task:
      brand: ''
      description: Get cases of Phishlabs DRP service by filters
      id: ebcd86f8-4e3d-4060-89be-f2cbea055cfb
      iscommand: true
      name: Get cases command
      script: '|||phishlabs-ioc-drp-get-cases'
      type: regular
      version: -1
    taskid: ebcd86f8-4e3d-4060-89be-f2cbea055cfb
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 895\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      outputformat:
        simple: ${PhishLabsIOC.EIR}
    separatecontext: false
    task:
      brand: ''
      description: Pretty-print the contents of the playbook context
      id: ecedc27e-847c-44ac-835d-04a2e40875e5
      iscommand: false
      name: PrintContext
      scriptName: PrintContext
      type: regular
      version: -1
    taskid: ecedc27e-847c-44ac-835d-04a2e40875e5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1245\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      message: {}
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: 55293704-be08-4ff3-813e-878701084b72
      iscommand: false
      name: PrintErrorEntry
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 55293704-be08-4ff3-813e-878701084b72
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 720\n  }\n}"
  '9':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: PhishLabsIOC.DRP.CaseID
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: PhishLabsIOC.DRP.CreatedBy.ID
          operator: isExists
      label: 'yes'
    id: '9'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '10'
      'yes':
      - '7'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 09abc9c2-8593-48e3-8fef-ef41a4e0198e
      iscommand: false
      name: Check get case command
      type: condition
      version: -1
    taskid: 09abc9c2-8593-48e3-8fef-ef41a4e0198e
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1070\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2515,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
