description: illuminate Integration testplaybook
id: illuminate Integration Test
inputs: []
name: illuminate Integration Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 99d17fdc-e2cd-405f-8dcd-c1283198acbc
      iscommand: false
      name: ''
      version: -1
    taskid: 99d17fdc-e2cd-405f-8dcd-c1283198acbc
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 7feada3a-589c-47a7-8597-45b7baed9efc
      iscommand: true
      name: DeleteContext
      script: DeleteContext
      type: regular
      version: -1
    taskid: 7feada3a-589c-47a7-8597-45b7baed9efc
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 200\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    quietmode: 0
    scriptarguments:
      string:
        simple: ??
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 77190d09-6936-4179-8769-840ee551799c
      iscommand: true
      name: illuminate-enrich-string
      script: '|||illuminate-enrich-string'
      type: regular
      version: -1
    taskid: 77190d09-6936-4179-8769-840ee551799c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2000\n  }\n}"
  '11':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Illuminate.String.ID
          operator: isEqualNumber
          right:
            value:
              simple: '90548'
      label: 'yes'
    id: '11'
    ignoreworker: false
    nexttasks:
      'yes':
      - '12'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 6af13c9a-f337-43fa-807f-083c25f43aab
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 6af13c9a-f337-43fa-807f-083c25f43aab
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2200\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    quietmode: 0
    scriptarguments:
      ip:
        simple: '16::'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 0c433982-8194-4c33-8d14-980e4efe6e0b
      iscommand: true
      name: illuminate-enrich-ipv6
      script: '|||illuminate-enrich-ipv6'
      type: regular
      version: -1
    taskid: 0c433982-8194-4c33-8d14-980e4efe6e0b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2400\n  }\n}"
  '13':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Illuminate.Ipv6.ID
          operator: isEqualNumber
          right:
            value:
              simple: '2623838'
      label: 'yes'
    id: '13'
    ignoreworker: false
    nexttasks:
      'yes':
      - '14'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 5d033663-e4cd-4865-8f81-7b88dd3fd5a6
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 5d033663-e4cd-4865-8f81-7b88dd3fd5a6
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2600\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    quietmode: 0
    scriptarguments:
      mutex:
        simple: ??
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 9dead863-6d75-4caa-8939-1a42eba5cbc6
      iscommand: true
      name: illuminate-enrich-mutex
      script: '|||illuminate-enrich-mutex'
      type: regular
      version: -1
    taskid: 9dead863-6d75-4caa-8939-1a42eba5cbc6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2800\n  }\n}"
  '15':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Illuminate.Mutex.ID
          operator: isEqualNumber
          right:
            value:
              simple: '95267'
      label: 'yes'
    id: '15'
    ignoreworker: false
    nexttasks:
      'yes':
      - '16'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 43fa7d06-092a-413e-814a-2b3c76ebdc93
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 43fa7d06-092a-413e-814a-2b3c76ebdc93
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3000\n  }\n}"
  '16':
    id: '16'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    quietmode: 0
    scriptarguments:
      http-request:
        simple: /~
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: d08547f7-726e-4cff-859e-39b03fe20ff6
      iscommand: true
      name: illuminate-enrich-http-request
      script: '|||illuminate-enrich-http-request'
      type: regular
      version: -1
    taskid: d08547f7-726e-4cff-859e-39b03fe20ff6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3200\n  }\n}"
  '17':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Illuminate.Httprequest.ID
          operator: isEqualNumber
          right:
            value:
              simple: '2885382'
      label: 'yes'
    id: '17'
    ignoreworker: false
    nexttasks:
      'yes':
      - '18'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 60ad71b3-dac0-434f-8d6e-5c34f929f4ee
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 60ad71b3-dac0-434f-8d6e-5c34f929f4ee
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3400\n  }\n}"
  '18':
    id: '18'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '19'
    note: false
    quietmode: 0
    scriptarguments:
      url:
        simple: 104.218.120.128/check.aspx
    separatecontext: false
    skipunavailable: false
    task:
      brand: illuminate
      id: 50c33870-00a8-49dd-8823-104c0c9909cb
      iscommand: true
      name: url
      script: illuminate|||url
      type: regular
      version: -1
    taskid: 50c33870-00a8-49dd-8823-104c0c9909cb
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3600\n  }\n}"
  '19':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Illuminate.Url.ID
          operator: isEqualNumber
          right:
            value:
              simple: '2699554'
      label: 'yes'
    id: '19'
    ignoreworker: false
    nexttasks:
      'yes':
      - '20'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: bce55c05-94ed-48e7-87aa-6743133a6235
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: bce55c05-94ed-48e7-87aa-6743133a6235
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3800\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      domain:
        simple: abc.com
      long: {}
      threshold: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: illuminate
      id: 94d880d2-b26d-4ac2-8bf2-a73d795377c2
      iscommand: true
      name: domain
      script: illuminate|||domain
      type: regular
      version: -1
    taskid: 94d880d2-b26d-4ac2-8bf2-a73d795377c2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 400\n  }\n}"
  '20':
    id: '20'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: a5ccd8c3-ee49-4146-86c1-7bed4bce1f0e
      iscommand: false
      name: Test Done
      type: title
      version: -1
    taskid: a5ccd8c3-ee49-4146-86c1-7bed4bce1f0e
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 4000\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Illuminate.Domain.ID
          operator: isEqualNumber
          right:
            value:
              simple: '2043650'
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: c2af8198-d5ca-4c98-8f88-f7be31d6012d
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: c2af8198-d5ca-4c98-8f88-f7be31d6012d
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 600\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      email:
        simple: 001toxic@gmail.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: illuminate
      id: 9427ed8f-67ef-4cc0-8657-bb40a75eda6b
      iscommand: true
      name: email
      script: illuminate|||email
      type: regular
      version: -1
    taskid: 9427ed8f-67ef-4cc0-8657-bb40a75eda6b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 800\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Illuminate.Email.ID
          operator: isEqualNumber
          right:
            value:
              simple: '1637756'
      label: 'yes'
    id: '5'
    ignoreworker: false
    nexttasks:
      'yes':
      - '6'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 5a8f4147-b082-4aeb-88db-b77c14023c6a
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 5a8f4147-b082-4aeb-88db-b77c14023c6a
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1000\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    quietmode: 0
    scriptarguments:
      ip:
        simple: 0.154.17.105
      long: {}
      threshold: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: illuminate
      id: 1adef7ee-d248-45cf-8bd9-aabb9b573eb2
      iscommand: true
      name: ip
      script: illuminate|||ip
      type: regular
      version: -1
    taskid: 1adef7ee-d248-45cf-8bd9-aabb9b573eb2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1200\n  }\n}"
  '7':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Illuminate.Ip.ID
          operator: isEqualNumber
          right:
            value:
              simple: '51469'
      label: 'yes'
    id: '7'
    ignoreworker: false
    nexttasks:
      'yes':
      - '8'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 1c4413f3-bbb3-4d40-8f95-760ec5ded96a
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 1c4413f3-bbb3-4d40-8f95-760ec5ded96a
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1400\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    quietmode: 0
    scriptarguments:
      file:
        simple: '00000000000000000000000000000000'
      long: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: illuminate
      description: Queries the illuminate REST API and enriches the given file with
        illuminate indicator data.
      id: 58aceeaf-2628-4eba-833e-69c54ddd97cd
      iscommand: true
      name: file
      script: illuminate|||file
      type: regular
      version: -1
    taskid: 58aceeaf-2628-4eba-833e-69c54ddd97cd
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1600\n  }\n}"
  '9':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Illuminate.File.ID
          operator: isEqualNumber
          right:
            value:
              simple: '1527155'
      label: 'yes'
    id: '9'
    ignoreworker: false
    nexttasks:
      'yes':
      - '10'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 400dba72-583a-44ba-8f3e-1d842dae1674
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 400dba72-583a-44ba-8f3e-1d842dae1674
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1800\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 4015,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
