id: Splunk-Test
inputs: []
name: Splunk-Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 8a4e7498-3a6e-4313-86e9-807366c2579e
      iscommand: false
      name: ''
      version: -1
    taskid: 8a4e7498-3a6e-4313-86e9-807366c2579e
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      earliest_time:
        simple: -1000d
      event_limit: {}
      latest_time: {}
      query:
        simple: '* | head 3'
    separatecontext: false
    skipunavailable: false
    task:
      brand: SplunkPy
      description: Search Splunk for events
      id: 79f0e89d-b368-46e4-8745-d172e4249fb2
      iscommand: true
      name: splunk-search
      script: SplunkPy|||splunk-search
      type: regular
      version: -1
    taskid: 79f0e89d-b368-46e4-8745-d172e4249fb2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Hurry!
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 44da6fbf-cee3-43be-8939-0ca42a6a0a25
      iscommand: false
      name: Hurry!
      scriptName: Print
      type: regular
      version: -1
    taskid: 44da6fbf-cee3-43be-8939-0ca42a6a0a25
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 2645\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: non-existent
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: a69d01b3-e073-4409-8b35-304fefb0857b
      iscommand: false
      name: FAIL
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: a69d01b3-e073-4409-8b35-304fefb0857b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 9751e3fa-71c1-446e-8ea5-98e3a43ed453
      iscommand: false
      name: Test _raw parsing
      type: title
      version: -1
    taskid: 9751e3fa-71c1-446e-8ea5-98e3a43ed453
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1610\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    quietmode: 0
    scriptarguments:
      raw: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: SplunkPy
      id: db31ecdc-b2d2-4dae-8aa6-5700fc8180e3
      iscommand: true
      name: Parse Raw
      script: SplunkPy|||splunk-parse-raw
      type: regular
      version: -1
    taskid: db31ecdc-b2d2-4dae-8aa6-5700fc8180e3
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1770\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    quietmode: 0
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: Splunk.Raw.Parsed
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: b04ce2e3-c4c2-4ebb-82d3-06b3005f3ccc
      iscommand: false
      name: Verify parse get's to context
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: b04ce2e3-c4c2-4ebb-82d3-06b3005f3ccc
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1945\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    quietmode: 0
    scriptarguments:
      append: {}
      key:
        simple: rawEvent
      value:
        simple: 1531041382, search_name="0 - Azure AD-Concurrent Access From Different
          GEO", logon_ip="xx.xx.xx.xx", logon_ip="xx.xx.xx.xx", logon_ip="xx.xx.xx.xx",
          logon_source_Country="Egypt", logon_source_Country="Germany", logon_source_info="Potentially_unauthorized",
          logon_source_info="VPN", timestamps="2018-07-08T08:22:41", timestamps="2018-07-08T08:28:50",
          timestamps="2018-07-08T08:35:31", country_count="2", country_in_AD="United
          Arab Emirates", info_max_time="+Infinity", info_min_time="0.000", muid="xx.xx.xx.xx",
          service="AzureActiveDirectory", user="xx.xx.xx.xx", user_type="A regular
          user", users_bunit="xx.xx.xx.xx"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 87525101-8ca3-411d-894c-216699a09720
      iscommand: false
      name: Add raw Data example
      scriptName: Set
      type: regular
      version: -1
    taskid: 87525101-8ca3-411d-894c-216699a09720
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2120\n  }\n}"
  '16':
    id: '16'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: parsedRaw=
      raw:
        simple: ${rawEvent}
    separatecontext: false
    skipunavailable: false
    task:
      brand: SplunkPy
      id: d08c0ab1-e702-4a89-8562-efe6d6c647c2
      iscommand: true
      name: Parse Raw example
      script: SplunkPy|||splunk-parse-raw
      type: regular
      version: -1
    taskid: d08c0ab1-e702-4a89-8562-efe6d6c647c2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2295\n  }\n}"
  '17':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Splunk.Raw.Parsed
          operator: isExists
      label: 'yes'
    id: '17'
    ignoreworker: false
    nexttasks:
      'no':
      - '18'
      'yes':
      - '10'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 92a89add-542b-440b-8a6b-e1fea7816ee1
      iscommand: false
      name: Is Raw parsed ?
      type: condition
      version: -1
    taskid: 92a89add-542b-440b-8a6b-e1fea7816ee1
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2470\n  }\n}"
  '18':
    id: '18'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: non-existent
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 6c4f6ca7-bd71-450c-8049-69585c7b1cb7
      iscommand: false
      name: FAIL
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 6c4f6ca7-bd71-450c-8049-69585c7b1cb7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 2645\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: ${Splunk.Result}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 6e105202-5e95-48ee-8346-4ce02a01f436
      iscommand: false
      name: Verify Context result of Splunk Search
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 6e105202-5e95-48ee-8346-4ce02a01f436
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: indexes=
    separatecontext: false
    skipunavailable: false
    task:
      brand: SplunkPy
      id: ce01df98-6628-4495-8fcf-ee3d2486b57a
      iscommand: true
      name: Get indexes names
      script: SplunkPy|||splunk-get-indexes
      type: regular
      version: -1
    taskid: ce01df98-6628-4495-8fcf-ee3d2486b57a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      'no':
      - '7'
      'yes':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      left: {}
      right: {}
      string:
        simple: ${JsonStr}
      substring:
        simple: main
      substringSeperator: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: dc070e81-185d-44c7-8d42-87778e132c69
      iscommand: false
      name: Has main index
      scriptName: StringContains
      type: condition
      version: -1
    taskid: dc070e81-185d-44c7-8d42-87778e132c69
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 895\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      data:
        simple: test
      host:
        simple: localhost
      index:
        simple: main
      sourcetype:
        simple: demisto-ci
    separatecontext: false
    skipunavailable: false
    task:
      brand: SplunkPy
      id: b64295eb-01b7-4e5a-80a8-9e1a996a3804
      iscommand: true
      name: Create new Splunk event
      script: SplunkPy|||splunk-submit-event
      type: regular
      version: -1
    taskid: b64295eb-01b7-4e5a-80a8-9e1a996a3804
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1070\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quietmode: 0
    scriptarguments:
      extend-context: {}
      key:
        simple: indexes
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Dumps a json from context key input, and returns a json object
        string result
      id: 410552ef-2a04-49b2-85ed-65d37b7722f6
      iscommand: false
      name: DumpJSON
      scriptName: DumpJSON
      type: regular
      version: -1
    taskid: 410552ef-2a04-49b2-85ed-65d37b7722f6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 720\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: non-existent
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 246406d1-23e4-4848-8b45-772fb822cb25
      iscommand: false
      name: FAIL
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 246406d1-23e4-4848-8b45-772fb822cb25
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 1070\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    quietmode: 0
    scriptarguments:
      earliest_time: {}
      event_limit: {}
      extend-context:
        simple: eventcount=
      latest_time: {}
      query:
        simple: '| eventcount'
    separatecontext: false
    skipunavailable: false
    task:
      brand: SplunkPy
      id: 580024aa-5504-4eef-8caa-873072011b9a
      iscommand: true
      name: Test eventcount query
      script: SplunkPy|||splunk-search
      type: regular
      version: -1
    taskid: 580024aa-5504-4eef-8caa-873072011b9a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1245\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      'no':
      - '11'
      'yes':
      - '12'
    note: false
    quietmode: 0
    scriptarguments:
      first:
        simple: ${eventcount.[0].count}
      second:
        simple: '1'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 35dcd8b4-cdb4-4a4c-8fd4-0912986852bb
      iscommand: false
      name: Verify eventcount
      scriptName: IsGreaterThan
      type: condition
      version: -1
    taskid: 35dcd8b4-cdb4-4a4c-8fd4-0912986852bb
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1420\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2690,\n      \"width\": 1025,\n      \"x\": 50,\n      \"y\":\
  \ 50\n    }\n  }\n}"
