id: SCADAfence_test
inputs: []
name: SCADAfence_test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: fa9129fb-42ca-453f-8bfc-e1da842461a4
      iscommand: false
      name: ''
      version: -1
    taskid: fa9129fb-42ca-453f-8bfc-e1da842461a4
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      id: 357fa8e8-66fa-45a8-8a34-b46cc707f55a
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 357fa8e8-66fa-45a8-8a34-b46cc707f55a
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      severity:
        simple: Critical
    separatecontext: false
    task:
      brand: SCADAfence CNM
      id: 328a194b-07b0-4cd7-80c8-a4d3711b2f95
      iscommand: true
      name: Fetch critical alerts
      script: SCADAfence CNM|||scadafence-getAlerts
      type: regular
      version: -1
    taskid: 328a194b-07b0-4cd7-80c8-a4d3711b2f95
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      alertId:
        simple: ${SCADAfence.Alert.id}
      alertStatus:
        simple: InProgress
    separatecontext: false
    task:
      brand: SCADAfence CNM
      id: ebd5f4b9-ee76-496e-801b-92b4ed41841f
      iscommand: true
      name: Mark alerts in progress
      script: SCADAfence CNM|||scadafence-setAlertStatus
      type: regular
      version: -1
    taskid: ebd5f4b9-ee76-496e-801b-92b4ed41841f
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      assetType: {}
      hostName: {}
      ipAddress:
        simple: SCADAfence.Alert.ip
    separatecontext: false
    task:
      brand: SCADAfence CNM
      id: 057dd374-0090-4c96-8e5f-925be1f46936
      iscommand: true
      name: Suspicious asset details
      script: SCADAfence CNM|||scadafence-getAsset
      type: regular
      version: -1
    taskid: 057dd374-0090-4c96-8e5f-925be1f46936
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      alertId:
        simple: ${SCADAfence.Alert.id}
      alertStatus:
        simple: Resolved
    separatecontext: false
    task:
      brand: SCADAfence CNM
      id: d2d6fedb-3714-4874-8fb1-1310105d8f8b
      iscommand: true
      name: Resolve alerts
      script: SCADAfence CNM|||scadafence-setAlertStatus
      type: regular
      version: -1
    taskid: d2d6fedb-3714-4874-8fb1-1310105d8f8b
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '7':
    id: '7'
    note: false
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: SCADAfence.Alert.ip
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: e0807884-77f0-4713-8fde-0b1bf1814dbc
      iscommand: false
      name: Verify alert ip
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: e0807884-77f0-4713-8fde-0b1bf1814dbc
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1115,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
