id: MaxMind Test
inputs: []
name: MaxMind Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 718ff683-df2d-475f-824c-31f0b82e75dc
      iscommand: false
      name: ''
      version: -1
    taskid: 718ff683-df2d-475f-824c-31f0b82e75dc
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 11efa238-5201-447f-84ad-8b358ba55abe
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 11efa238-5201-447f-84ad-8b358ba55abe
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 180\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      fullResponse: {}
      ip:
        simple: 8.8.8.8
      long: {}
      retries: {}
      sampleSize: {}
      threshold: {}
      wait: {}
    separatecontext: false
    task:
      brand: MaxMind GeoIP2
      description: Check IP reputation (when information is available, returns a JSON
        with details). Uses all configured Threat Intelligence feeds
      id: 8784789e-0686-4d2d-8a42-c0970a8aad6c
      iscommand: true
      name: ip
      script: MaxMind GeoIP2|||ip
      type: regular
      version: -1
    taskid: 8784789e-0686-4d2d-8a42-c0970a8aad6c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 340\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${MaxMind.ISP}
          operator: isEqualString
          right:
            value:
              simple: Google
      label: 'yes'
    id: '3'
    nexttasks:
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 2d5408e8-2440-4eba-89cf-10633237785a
      iscommand: false
      name: Check results
      type: condition
      version: -1
    taskid: 2d5408e8-2440-4eba-89cf-10633237785a
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 520\n  }\n}"
  '4':
    id: '4'
    note: false
    scriptarguments:
      closeNotes: {}
      closeReason: {}
      id:
        simple: ${incident.id}
    separatecontext: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 62512374-fc0a-4e7f-8005-f73dcad0d1d3
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 62512374-fc0a-4e7f-8005-f73dcad0d1d3
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 730\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 775,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\": 50\n\
  \    }\n  }\n}"
