contentitemfields:
  propagationLabels:
  - all
id: TestProofpointFeed
inputs: []
name: TestProofpointFeed
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quiet: false
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 32374b87-da6e-47bb-876b-74e0b54edf8d
      iscommand: false
      name: ''
      version: -1
    taskid: 32374b87-da6e-47bb-876b-74e0b54edf8d
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quiet: false
    scriptarguments:
      indicator_type:
        simple: all
      limit: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ProofpointFeed
      description: Gets indicators from the feed.
      id: b9da1640-fffc-463f-8158-654927bad866
      iscommand: true
      name: all indicators
      script: ProofpointFeed|||proofpoint-get-indicators
      type: regular
      version: -1
    taskid: b9da1640-fffc-463f-8158-654927bad866
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quiet: false
    scriptarguments:
      indicator_type:
        simple: ip
      limit: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ProofpointFeed
      description: Gets indicators from the feed.
      id: 62e46271-5d05-4370-8933-87c931c8d454
      iscommand: true
      name: ips
      script: ProofpointFeed|||proofpoint-get-indicators
      type: regular
      version: -1
    taskid: 62e46271-5d05-4370-8933-87c931c8d454
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quiet: false
    scriptarguments:
      indicator_type:
        simple: domain
      limit: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ProofpointFeed
      description: Gets indicators from the feed.
      id: 3d3c98aa-e819-413b-83ed-674e9b813d4b
      iscommand: true
      name: domains
      script: ProofpointFeed|||proofpoint-get-indicators
      type: regular
      version: -1
    taskid: 3d3c98aa-e819-413b-83ed-674e9b813d4b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 370\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    quiet: false
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 10b461e0-8c0c-461d-80d6-262f0e2a2af5
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 10b461e0-8c0c-461d-80d6-262f0e2a2af5
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
      - '2'
      - '3'
    note: false
    quiet: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: 7fa2464b-5ff4-4589-813e-898c9f47311a
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 7fa2464b-5ff4-4589-813e-898c9f47311a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 195\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 560,\n      \"width\": 1240,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
