id: ThreatMiner-Test
inputs: []
name: ThreatMiner - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 93190d0d-d5e5-4783-8d33-b6e1cd4eeeae
      iscommand: false
      name: ''
      version: -1
    taskid: 93190d0d-d5e5-4783-8d33-b6e1cd4eeeae
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: caef15a4-d9c0-48e7-87f9-627196d74614
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: caef15a4-d9c0-48e7-87f9-627196d74614
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: 847ce4d6-e89b-46df-8ed0-0b266ac02ba1
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 847ce4d6-e89b-46df-8ed0-0b266ac02ba1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1535\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    quietmode: 0
    scriptarguments:
      file:
        simple: e6ff1bf0821f00384cdd25efb9b1cc09
      threshold: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ThreatMiner
      description: Retrieve data from ThreatMiner about a specified file.
      id: f6217024-a71f-41d1-86ac-d7a27eac7cb6
      iscommand: true
      name: file
      script: ThreatMiner|||file
      type: regular
      version: -1
    taskid: f6217024-a71f-41d1-86ac-d7a27eac7cb6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1710\n  }\n}"
  '12':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ThreatMiner.File.MD5
          operator: isEqualString
          right:
            value:
              simple: e6ff1bf0821f00384cdd25efb9b1cc09
      - - left:
            iscontext: true
            value:
              simple: ThreatMiner.File.HTTP
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ThreatMiner.File.Mutants
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ThreatMiner.File.Domains
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: File.MD5
          operator: isEqualString
          right:
            value:
              simple: e6ff1bf0821f00384cdd25efb9b1cc09
      label: 'yes'
    id: '12'
    ignoreworker: false
    nexttasks:
      'yes':
      - '14'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Verify File(Sample) Metadata, HTTP Traffic, Hosts, Mutants
      id: f6f253e6-84c1-4ce1-8619-7e734d132021
      iscommand: false
      name: Verify File(Samples)
      type: condition
      version: -1
    taskid: f6f253e6-84c1-4ce1-8619-7e734d132021
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1885\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: e83a3ed4-db86-40a7-8c90-a27fa6764f24
      iscommand: false
      name: Success
      type: title
      version: -1
    taskid: e83a3ed4-db86-40a7-8c90-a27fa6764f24
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2235\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    quietmode: 0
    scriptarguments:
      fullResponse: {}
      ip:
        simple: 35.24.216.211
      long: {}
      retries: {}
      sampleSize: {}
      threshold: {}
      wait: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ThreatMiner
      description: Retrieves data from ThreatMiner about a specified IP address.
      id: 822c70ef-4a8e-4168-8467-47e1228752b4
      iscommand: true
      name: Search for IP with no reports
      script: ThreatMiner|||ip
      type: regular
      version: -1
    taskid: 822c70ef-4a8e-4168-8467-47e1228752b4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2060\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      fullResponse: {}
      ip:
        simple: 8.8.8.8
    separatecontext: false
    skipunavailable: false
    task:
      brand: ThreatMiner
      description: Retrieve data from ThreatMiner about a specified IP address.
      id: e2654bf1-7589-4516-868b-cd11af433b2c
      iscommand: true
      name: ip
      script: ThreatMiner|||ip
      type: regular
      version: -1
    taskid: e2654bf1-7589-4516-868b-cd11af433b2c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ThreatMiner.IP.Whois.Org
          operator: isEqualString
          right:
            value:
              simple: Google Inc.
      - - left:
            iscontext: true
            value:
              simple: ThreatMiner.IP.PassiveDNS
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ThreatMiner.IP.URI
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ThreatMiner.IP.MD5
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ThreatMiner.IP.SSL
          operator: isExists
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: e666c49b-d5f0-4658-8e95-2d7eb02c25b7
      iscommand: false
      name: Verify ip results
      type: condition
      version: -1
    taskid: e666c49b-d5f0-4658-8e95-2d7eb02c25b7
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 5cf40890-6748-4992-89aa-94f1f67db593
      iscommand: false
      name: Success
      type: title
      version: -1
    taskid: 5cf40890-6748-4992-89aa-94f1f67db593
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      domain:
        simple: google.com
      fullResponse: {}
      long: {}
      retries: {}
      sampleSize: {}
      threshold: {}
      wait: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ThreatMiner
      description: Retrieve data from ThreatMiner about a specified IP address.
      id: e02aa887-a992-4257-8c38-cca6bd43b0f4
      iscommand: true
      name: domain command
      script: ThreatMiner|||domain
      type: regular
      version: -1
    taskid: e02aa887-a992-4257-8c38-cca6bd43b0f4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1040\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: c52db194-0ddb-4885-8f2c-97193bb715c3
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: c52db194-0ddb-4885-8f2c-97193bb715c3
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 865\n  }\n}"
  '8':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Domain.Name
          operator: isEqualString
          right:
            value:
              simple: google.com
      - - left:
            iscontext: true
            value:
              simple: ThreatMiner.Domain.PassiveDNS
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ThreatMiner.Domain.URI
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ThreatMiner.Domain.Whois
          operator: isExists
      label: 'yes'
    id: '8'
    ignoreworker: false
    nexttasks:
      'yes':
      - '9'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: '

        '
      id: dd81c97b-16a1-4e45-8fa8-d6350087d8e5
      iscommand: false
      name: Verify domain results
      type: condition
      version: -1
    taskid: dd81c97b-16a1-4e45-8fa8-d6350087d8e5
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1215\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 626042a5-9779-473d-8437-7ac4c303313f
      iscommand: false
      name: Success
      type: title
      version: -1
    taskid: 626042a5-9779-473d-8437-7ac4c303313f
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1390\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2250,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
