id: VMRay-Test
inputs: []
name: VMRay-Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 826ad986-cb90-458f-8958-f327f6821e2c
      iscommand: false
      name: ''
      version: -1
    taskid: 826ad986-cb90-458f-8958-f327f6821e2c
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://raw.githubusercontent.com/demisto/content/master/TestData/Inline_malicious.eml
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: Sends http request. Returns the response as json.
      id: 25cf9ba4-0c14-4a33-8ee4-1b5779c5c146
      iscommand: false
      name: Get file
      scriptName: http
      type: regular
      version: -1
    taskid: 25cf9ba4-0c14-4a33-8ee4-1b5779c5c146
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '3'
      - '4'
      - '5'
    note: false
    scriptarguments:
      File:
        simple: ${File}
      archive_password: {}
      document_password: {}
      interval:
        simple: '1'
      max_jobs:
        simple: '1'
      reanalyze:
        simple: '1'
      sample_type: {}
      shareable: {}
      tags: {}
      timeout:
        simple: '10'
    separatecontext: true
    task:
      brand: ''
      description: Detonating file with VMRay
      id: c700a3f9-f2dc-4cf1-8726-d3eb13cef76b
      iscommand: false
      name: Detonate File - VMRay
      playbookName: Detonate File - VMRay
      type: playbook
      version: -1
    taskid: c700a3f9-f2dc-4cf1-8726-d3eb13cef76b
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      limit:
        simple: '1'
      sample_id:
        simple: ${VMRay.Sample.SampleID}
    separatecontext: false
    task:
      brand: ''
      description: Get all analysis details about a specific sample.
      id: ad6c2f37-174b-4c7a-8624-51ec1878f43c
      iscommand: true
      name: Get analysis by sample
      script: '|||vmray-get-analysis-by-sample'
      type: regular
      version: -1
    taskid: ad6c2f37-174b-4c7a-8624-51ec1878f43c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 720\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      sample_id:
        simple: ${VMRay.Sample.SampleID}
    separatecontext: false
    task:
      brand: ''
      description: Get threat indicators (VTI)
      id: ae6d46a0-f1c2-40d2-832b-1d18df284e88
      iscommand: true
      name: get-threat-indicators
      script: '|||vmray-get-threat-indicators'
      type: regular
      version: -1
    taskid: ae6d46a0-f1c2-40d2-832b-1d18df284e88
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      sample_id:
        simple: ${VMRay.Sample.SampleID}
    separatecontext: false
    task:
      brand: ''
      description: getting iocs of given sample
      id: 3b6a005d-852c-4004-809a-e0aab8fbd766
      iscommand: true
      name: Get IOCs
      script: '|||vmray-get-iocs'
      type: regular
      version: -1
    taskid: 3b6a005d-852c-4004-809a-e0aab8fbd766
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1070\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      analysis_id:
        simple: ${VMRay.Analysis.AnalysisID}
      submission_id:
        simple: ${VMRay.Submission.SubmissionID}
      tag:
        simple: test_task
    separatecontext: false
    task:
      brand: ''
      description: Adds a tag to analysis and/or submission
      id: 38328f86-7a51-4215-84e4-ee9c60ee5366
      iscommand: true
      name: Add tag
      script: '|||vmray-add-tag'
      type: regular
      version: -1
    taskid: 38328f86-7a51-4215-84e4-ee9c60ee5366
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 895\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: ed6b816a-c46f-45bf-8cb3-13595b97800f
      iscommand: false
      name: End of test
      type: title
      version: -1
    taskid: ed6b816a-c46f-45bf-8cb3-13595b97800f
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1245\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      analysis_id:
        simple: ${VMRay.Analysis.AnalysisID}
      submission_id:
        simple: ${VMRay.Submission.SubmissionID}
      tag:
        simple: test_task
    separatecontext: false
    task:
      brand: ''
      description: Delete tags from analysis and/or submission
      id: 53c445f1-a166-4df9-823f-430688d8b4c9
      iscommand: true
      name: Remove tag
      script: '|||vmray-delete-tag'
      type: regular
      version: -1
    taskid: 53c445f1-a166-4df9-823f-430688d8b4c9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 1070\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 4ee76f03-fa2f-4394-8e9e-e867c98c1708
      iscommand: false
      name: Delete context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 4ee76f03-fa2f-4394-8e9e-e867c98c1708
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 195\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1260,\n      \"width\": 1240,\n      \"x\": 50,\n      \"y\":\
  \ 50\n    }\n  }\n}"
