id: test Arcsight - Get events related to the Case
inputs: []
name: test Arcsight - Get events related to the Case
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d0feb6ad-5470-4236-87e6-8321d979697a
      iscommand: false
      name: ''
      version: -1
    taskid: d0feb6ad-5470-4236-87e6-8321d979697a
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    note: false
    separatecontext: true
    task:
      brand: ''
      id: cdc0dbc5-a1c6-42ce-802a-aa8043d01a89
      iscommand: false
      name: Arcsight - Get events related to the Case
      playbookName: Arcsight - Get events related to the Case
      type: playbook
      version: -1
    taskid: cdc0dbc5-a1c6-42ce-802a-aa8043d01a89
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      addLabels: {}
      customFields: {}
      deleteEmptyField: {}
      details: {}
      id: {}
      labels:
        simple: '[{"ID":"77ax-uGgBABCWb2puJdY8ZA=="}]'
      name: {}
      occurred: {}
      owner: {}
      phase: {}
      replacePlaybook: {}
      roles: {}
      severity: {}
      sla: {}
      slaField: {}
      systems: {}
      type: {}
      vulnerabilitycategory: {}
    separatecontext: false
    task:
      brand: Builtin
      id: 87f17d16-b9c1-401d-8771-fb2ed60cf7bb
      iscommand: true
      name: set case ID
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 87f17d16-b9c1-401d-8771-fb2ed60cf7bb
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: af20bc42-662e-40a8-89a4-641d50ceee26
      iscommand: false
      name: delete context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: af20bc42-662e-40a8-89a4-641d50ceee26
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 590,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
