contentitemfields:
  propagationLabels: []
id: AWS Feed Test
inputs: []
name: AWS Feed Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quiet: false
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: db605e5e-22c7-4510-807c-5498bc676486
      iscommand: false
      name: ''
      version: -1
    taskid: db605e5e-22c7-4510-807c-5498bc676486
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quiet: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: d917ba08-5a1a-4fdc-8764-bff21002631f
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: d917ba08-5a1a-4fdc-8764-bff21002631f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    note: false
    quiet: false
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 89544cf6-bf4e-4bd2-84ce-c50b39c2825c
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 89544cf6-bf4e-4bd2-84ce-c50b39c2825c
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quiet: false
    scriptarguments:
      extend-context:
        simple: Type=type
      limit:
        simple: '1'
    separatecontext: false
    skipunavailable: false
    task:
      brand: AWS Feed
      description: Fetches indicators from the feed.
      id: cae48bae-be17-48fe-8dcf-ecf5eebe8949
      iscommand: true
      name: get-indicators-ip
      script: AWS Feed|||aws-get-indicators
      type: regular
      version: -1
    taskid: cae48bae-be17-48fe-8dcf-ecf5eebe8949
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '6':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Type
          operator: isEqualString
          right:
            value:
              simple: CIDR
      label: 'yes'
    id: '6'
    ignoreworker: false
    nexttasks:
      'yes':
      - '14'
    note: false
    quiet: false
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: eaab7819-ebdc-4acc-8cbb-6ac9552bc5e7
      iscommand: false
      name: verify get indicators
      type: condition
      version: -1
    taskid: eaab7819-ebdc-4acc-8cbb-6ac9552bc5e7
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 735,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
