description: Deprecated - We recommend using Entity Enrichment - Generic playbook
  instead. Enrich data with reputation. Data is expected to be found in the standard
  locations like File, URL, IP.
fromversion: 2.5.0
id: Enrichment Playbook
inputs: []
name: Enrichment Playbook
outputs: []
starttaskid: '0'
system: true
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: start-enrich
      iscommand: false
      name: ''
      version: -1
    taskid: start-enrich
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 950,\n    \"y\": 50\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '8'
      'yes':
      - '11'
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${File.MD5}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 1b38d3b8-4657-4cea-84f9-6e4ac2b5d544
      iscommand: false
      name: Do we have MD5 hashes?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 1b38d3b8-4657-4cea-84f9-6e4ac2b5d544
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 340\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      file:
        simple: ${File.MD5}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: d2de03c7-2e14-40b0-83f6-dee616098d0e
      iscommand: false
      name: Check MD5s
      scriptName: FileReputation
      type: regular
      version: -1
    taskid: d2de03c7-2e14-40b0-83f6-dee616098d0e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 167.5,\n    \"y\": 515\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '8'
      'yes':
      - '13'
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${File.SHA1}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 8c9ccba0-d9d6-477e-8774-3f6fc8624a57
      iscommand: false
      name: Do we have SHA1 hashes?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 8c9ccba0-d9d6-477e-8774-3f6fc8624a57
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 500,\n    \"y\": 340\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      file:
        simple: ${File.SHA1}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: b01bef15-7c9d-40a8-83e7-7fe9474399d4
      iscommand: false
      name: Check SHA1s
      scriptName: FileReputation
      type: regular
      version: -1
    taskid: b01bef15-7c9d-40a8-83e7-7fe9474399d4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 612.5,\n    \"y\": 515\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '8'
      'yes':
      - '18'
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${File.SHA256}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 5006c24b-1bc8-4af3-86be-0944cb97d7db
      iscommand: false
      name: Do we have SHA256 hashes?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 5006c24b-1bc8-4af3-86be-0944cb97d7db
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 950,\n    \"y\": 340\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '8'
      'yes':
      - '19'
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${IP.Address}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 57fc5852-cd27-43ba-87fc-03f8fd220b4d
      iscommand: false
      name: Do we have IPs?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 57fc5852-cd27-43ba-87fc-03f8fd220b4d
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 1400,\n    \"y\": 340\n  }\n}"
  '16':
    id: '16'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '8'
      'yes':
      - '20'
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${URL.Data}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 5417106f-4250-4478-8ce6-5bc2465393f9
      iscommand: false
      name: Do we have URLs?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 5417106f-4250-4478-8ce6-5bc2465393f9
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 1850,\n    \"y\": 340\n  }\n}"
  '18':
    id: '18'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      file:
        simple: ${File.SHA256}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: c54d3c30-e2bb-47af-83a0-bfe2279edc19
      iscommand: false
      name: Check SHA256s
      scriptName: FileReputation
      type: regular
      version: -1
    taskid: c54d3c30-e2bb-47af-83a0-bfe2279edc19
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1062.5,\n    \"y\": 515\n  }\n}"
  '19':
    id: '19'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      file:
        simple: ${File.SHA256}
      ip:
        simple: ${IP.Address}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: de7cff35-df2d-4e32-8f3e-657226146b05
      iscommand: false
      name: Check IPs
      scriptName: IPReputation
      type: regular
      version: -1
    taskid: de7cff35-df2d-4e32-8f3e-657226146b05
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1512.5,\n    \"y\": 515\n  }\n}"
  '20':
    id: '20'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      file:
        simple: ${File.SHA256}
      ip: {}
      url:
        simple: ${URL.Data}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 015bee76-dcfa-4a82-8db6-0ca8e268c7ab
      iscommand: false
      name: Check URLs
      scriptName: URLReputation
      type: regular
      version: -1
    taskid: 015bee76-dcfa-4a82-8db6-0ca8e268c7ab
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1962.5,\n    \"y\": 515\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
      - '12'
      - '14'
      - '15'
      - '16'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: enrich-integ
      iscommand: false
      name: Enrich with Integrations
      type: title
      version: -1
    taskid: enrich-integ
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 950,\n    \"y\": 195\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: check-res
      iscommand: false
      name: Check Result
      type: title
      version: -1
    taskid: check-res
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 950,\n    \"y\": 690\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Enrichment done
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: enrich-done
      iscommand: false
      name: Done
      scriptName: Print
      type: regular
      version: -1
    taskid: enrich-done
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 950,\n    \"y\": 835\n  }\n}"
tests:
- No tests - Deprecated playbook
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"10_11_yes\": 0.42,\n    \"10_8_#default#\"\
  : 0.21,\n    \"12_8_#default#\": 0.28,\n    \"14_8_#default#\": 0.24,\n    \"15_8_#default#\"\
  : 0.1,\n    \"16_8_#default#\": 0.18\n  },\n  \"paper\": {\n    \"dimensions\":\
  \ {\n      \"height\": 880,\n      \"width\": 2292.5,\n      \"x\": 50,\n      \"\
  y\": 50\n    }\n  }\n}"
