description: Add information about the vulnerability and asset from the "Vulnerability
  Handling - Qualys" playbook data to the default "Vulnerability" layout.
fromversion: 3.6.0
id: vulnerability_handling_-_qualys_-_add _ustom_fields_to_default_layout
inputs:
- description: The Qualys object containing the vulnerability data
  key: Qualys
  required: false
  value:
    complex:
      root: Qualys
- description: The CVE object containing the vulnerability data
  key: CVE
  required: false
  value:
    complex:
      root: CVE
name: Vulnerability Handling - Qualys - Add custom fields to default layout
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '15'
      - '17'
      - '18'
      - '19'
      - '20'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 7c0a6113-ccc4-4b67-8ae0-5b6ebed288fb
      iscommand: false
      name: ''
      version: -1
    taskid: 7c0a6113-ccc4-4b67-8ae0-5b6ebed288fb
    type: start
    view: "{\n  \"position\": {\n    \"x\": 1062.5,\n    \"y\": 50\n  }\n}"
  '11':
    id: '11'
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      addLabels: {}
      customFieldName:
        simple: cve
      customFieldValue:
        complex:
          accessor: ID
          root: inputs.CVE
          transformers:
          - operator: general.uniq
          - args:
              separator:
                value:
                  simple: ','
            operator: general.join
      details: {}
      labels: {}
      name: {}
      owner: {}
      playbook: {}
      severity: {}
      stage: {}
      type: {}
      updatePlaybookForType: {}
    separatecontext: false
    task:
      brand: ''
      description: Populate the custom field.
      id: b79b6492-0fe9-47ea-8712-25e67bb05384
      iscommand: false
      name: Set "CVE"
      scriptName: IncidentSet
      type: regular
      version: -1
    taskid: b79b6492-0fe9-47ea-8712-25e67bb05384
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 950,\n    \"y\": 370\n  }\n}"
  '13':
    id: '13'
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      addLabels: {}
      customFieldName:
        simple: cvss
      customFieldValue:
        complex:
          accessor: CVSS
          root: inputs.CVE
          transformers:
          - args:
              separator:
                value:
                  simple: ',  '
            operator: general.join
      details: {}
      labels: {}
      name: {}
      owner: {}
      playbook: {}
      severity: {}
      stage: {}
      type: {}
      updatePlaybookForType: {}
    separatecontext: false
    task:
      brand: ''
      description: Populate the custom field.
      id: 12f3c186-65f1-41b8-89bb-b2e47b2b358b
      iscommand: false
      name: Set "CVSS"
      scriptName: IncidentSet
      type: regular
      version: -1
    taskid: 12f3c186-65f1-41b8-89bb-b2e47b2b358b
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 500,\n    \"y\": 370\n  }\n}"
  '15':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Category
                root: inputs.Qualys
          operator: general.isExists
      label: 'yes'
    id: '15'
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '3'
    separatecontext: false
    task:
      brand: ''
      description: "Check if there\u2019s a \"Vulnerability Category\" in the playbook\
        \ inputs."
      id: e23eb213-9603-4c62-8825-9c3fb601e139
      iscommand: false
      name: Is there a valid "Vulnerability Category"?
      type: condition
      version: -1
    taskid: e23eb213-9603-4c62-8825-9c3fb601e139
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 195\n  }\n}"
  '17':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: CVSS
                root: inputs.CVE
          operator: general.isExists
      label: 'yes'
    id: '17'
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '13'
    separatecontext: false
    task:
      brand: ''
      description: "Check if there\u2019s a \"CVSS\" in the playbook inputs."
      id: 6c1b4f4a-5d12-4d78-81d3-02892cc3ad37
      iscommand: false
      name: Is there a valid "CVSS"?
      type: condition
      version: -1
    taskid: 6c1b4f4a-5d12-4d78-81d3-02892cc3ad37
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 612.5,\n    \"y\": 195\n  }\n}"
  '18':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: ID
                root: inputs.CVE
          operator: general.isExists
      label: 'yes'
    id: '18'
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '11'
    separatecontext: false
    task:
      brand: ''
      description: "Check if there\u2019s a \"CVE\" in the playbook inputs."
      id: 360bab9f-806f-48c0-8080-fbbbe2efd466
      iscommand: false
      name: Is there a valid "CVE"?
      type: condition
      version: -1
    taskid: 360bab9f-806f-48c0-8080-fbbbe2efd466
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 1062.5,\n    \"y\": 195\n  }\n}"
  '19':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Title
                root: inputs.Qualys
          operator: general.isExists
      label: 'yes'
    id: '19'
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '8'
    separatecontext: false
    task:
      brand: ''
      description: "Check if there\u2019s a \"Signature\" in the playbook inputs."
      id: 19976cc4-28dd-4594-8972-1c512a7dd3f5
      iscommand: false
      name: Is there a valid "Signature"?
      type: condition
      version: -1
    taskid: 19976cc4-28dd-4594-8972-1c512a7dd3f5
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 1512.5,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 2115cdff-522d-4787-822c-39684be05294
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 2115cdff-522d-4787-822c-39684be05294
    type: title
    view: "{\n  \"position\": {\n    \"x\": 1062.5,\n    \"y\": 545\n  }\n}"
  '20':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Bugtraq.ID
                root: inputs.Qualys
          operator: general.isExists
      label: 'yes'
    id: '20'
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '9'
    separatecontext: false
    task:
      brand: ''
      description: "Check if there\u2019s a \"Bugtraq\" in the playbook inputs."
      id: a3def47b-593f-4a87-8ce5-356ad232dc95
      iscommand: false
      name: Is there a valid "Bugtraq"?
      type: condition
      version: -1
    taskid: a3def47b-593f-4a87-8ce5-356ad232dc95
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 1962.5,\n    \"y\": 195\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      addLabels: {}
      customFieldName:
        simple: vulnerabilitycategory
      customFieldValue:
        complex:
          accessor: Category
          root: inputs.Qualys
          transformers:
          - operator: general.uniq
          - args:
              separator:
                value:
                  simple: ','
            operator: general.join
      details: {}
      labels: {}
      name: {}
      owner: {}
      playbook: {}
      severity: {}
      stage: {}
      type: {}
      updatePlaybookForType: {}
    separatecontext: false
    task:
      brand: ''
      description: Populate the custom field.
      id: 8e4fc911-843f-47ff-8a54-1b3efb8470b8
      iscommand: false
      name: Set "Vulnerability Category"
      scriptName: IncidentSet
      type: regular
      version: -1
    taskid: 8e4fc911-843f-47ff-8a54-1b3efb8470b8
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      addLabels: {}
      customFieldName:
        simple: signature
      customFieldValue:
        complex:
          accessor: Title
          root: inputs.Qualys
          transformers:
          - args:
              separator:
                value:
                  simple: ', '
            operator: general.join
      details: {}
      labels: {}
      name: {}
      owner: {}
      playbook: {}
      severity: {}
      stage: {}
      type: {}
      updatePlaybookForType: {}
    separatecontext: false
    task:
      brand: ''
      description: Populate the custom field.
      id: e041a676-db54-4695-8ecd-34befbfbc79c
      iscommand: false
      name: Set "Signature"
      scriptName: IncidentSet
      type: regular
      version: -1
    taskid: e041a676-db54-4695-8ecd-34befbfbc79c
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1400,\n    \"y\": 370\n  }\n}"
  '9':
    id: '9'
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      addLabels: {}
      customFieldName:
        simple: bugtraq
      customFieldValue:
        complex:
          accessor: Bugtraq.ID
          root: inputs.Qualys
          transformers:
          - args:
              separator:
                value:
                  simple: ', '
            operator: general.join
      details: {}
      labels: {}
      name: {}
      owner: {}
      playbook: {}
      severity: {}
      stage: {}
      type: {}
      updatePlaybookForType: {}
    separatecontext: false
    task:
      brand: ''
      description: Populate the custom field.
      id: 7c7cb394-27b8-470b-8503-fca384538827
      iscommand: false
      name: Set "Bugtraq"
      scriptName: IncidentSet
      type: regular
      version: -1
    taskid: 7c7cb394-27b8-470b-8503-fca384538827
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1850,\n    \"y\": 370\n  }\n}"
tests:
- no tests
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 560,\n      \"width\": 2292.5,\n      \"x\": 50,\n      \"y\"\
  : 50\n    }\n  }\n}"
