description: Enrich entities using one or more integrations
fromversion: 3.6.0
id: entity_enrichment_generic
inputs:
- description: The IP addresses to enrich
  key: IP
  required: false
  value:
    simple: ${IP.Address}
- description: The internal range to check against the IPs
  key: InternalRange
  required: false
  value: {}
- description: File MD5 to enrich
  key: MD5
  required: false
  value:
    simple: ${File.MD5}
- description: File SHA256 to enrich
  key: SHA256
  required: false
  value:
    simple: ${File.SHA256}
- description: File SHA1 to enrich
  key: SHA1
  required: false
  value:
    simple: ${File.SHA1}
- description: url to enrich
  key: url
  required: false
  value:
    simple: ${URL.Data}
- description: The email addresses to enrich
  key: Email
  required: false
  value:
    simple: ${Account.Email.Address}
- description: The hostname to enrich
  key: Hostname
  required: false
  value:
    simple: ${Endpoint.Hostname}
- description: The Username to enrich
  key: Username
  required: false
  value:
    simple: ${Account.Username}
- description: The domain name to enrich
  key: Domain
  required: false
  value:
    simple: ${Domain.Name}
name: Entity Enrichment - Generic
outputs:
- contextPath: Account
  description: The Account's object
  type: unknown
- contextPath: Account.ID
  description: The unique Account DN (Distinguished Name)
  type: string
- contextPath: Domain
  description: The domain objects
  type: unknown
- contextPath: URL
  description: The URL's object
  type: unknown
- contextPath: URL.Malicious
  description: whether url was detected as malicious
  type: unknown
- contextPath: URL.Vendor
  description: name of vendor who labeled as malicious
  type: string
- contextPath: URL.Description
  description: additional info on the url
  type: string
- contextPath: URL.Address
  description: The enriched URL
  type: string
- contextPath: Account.Email.Address
  description: The Email account full address
  type: string
- contextPath: IP
  description: The IP objects
  type: unknown
- contextPath: Account.Email.Domain
  description: The Email account domain
  type: string
- contextPath: Account.Email.NetworkType
  description: The Email account NetworkType (could be Internal/External)
  type: string
- contextPath: Account.Email.Username
  description: The Email account username
  type: string
- contextPath: Account.Email.Distance.Domain
  description: The compared domain
  type: unknown
- contextPath: Account.Email.Distance.Value
  description: 'The distance between the email domain and the compared domain '
  type: string
- contextPath: Account.Type
  description: Type of the Account entity
  type: string
- contextPath: Account.Username
  description: The Account username
  type: string
- contextPath: Account.Email
  description: The email address associated with the Account
- contextPath: Account.Groups
  description: The groups the Account is part of
  type: unknown
- contextPath: Account.DisplayName
  description: The Account display name
  type: string
- contextPath: Account.Manager
  description: The Account's manager
  type: string
- contextPath: File
  description: The File's object
  type: unknown
- contextPath: File.MD5
  description: MD5 hash of the file
  type: string
- contextPath: File.SHA1
  description: SHA1 hash of the file
  type: string
- contextPath: File.SHA256
  description: SHA256 hash of the file
  type: string
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision
  type: string
- contextPath: Endpoint
  description: The Endpoint's object
  type: unknown
- contextPath: Endpoint.Hostname
  description: The hostname to enrich
  type: string
- contextPath: Endpoint.OS
  description: Endpoint OS
  type: string
- contextPath: Endpoint.IP
  description: List of endpoint IP addresses
- contextPath: Endpoint.MAC
  description: List of endpoint MAC addresses
- contextPath: Endpoint.Domain
  description: Endpoint domain name
  type: string
- contextPath: DBotScore
  description: The Indicator's object
  type: unknown
- contextPath: DBotScore.Indicator
  description: The Indicator
  type: string
- contextPath: DBotScore.Type
  description: The Indicator Type
  type: string
- contextPath: DBotScore.Vendor
  description: The DBot score vendor
  type: string
- contextPath: DBotScore.Score
  description: The DBot score
  type: number
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '2'
      - '1'
      - '9'
      - '10'
      - '12'
      - '11'
      - '13'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: cdd6228a-7feb-4386-8ab1-7dfdf77d99c2
      iscommand: false
      name: ''
      version: -1
    taskid: cdd6228a-7feb-4386-8ab1-7dfdf77d99c2
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 67\n  }\n}"
  '1':
    id: '1'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '15'
    scriptarguments:
      IP:
        simple: ${inputs.IP}
      InternalRange: {}
    separatecontext: false
    task:
      brand: ''
      description: Enrich IP using one or more integrations
      id: 92a63802-d111-4add-8e92-03f485d20bab
      iscommand: false
      name: IP Enrichment - Generic
      playbookName: IP Enrichment - Generic
      type: playbook
      version: -1
    taskid: 92a63802-d111-4add-8e92-03f485d20bab
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 225\n  }\n}"
  '10':
    id: '10'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '15'
    scriptarguments:
      Hostname:
        simple: ${inputs.Hostname}
    separatecontext: false
    task:
      brand: ''
      description: Enrich an Endpoint Hostname using one or more integrations
      id: 06158760-6f5f-466e-8e57-d37f7ec29066
      iscommand: false
      name: Endpoint Enrichment - Generic
      playbookName: Endpoint Enrichment - Generic
      type: playbook
      version: -1
    taskid: 06158760-6f5f-466e-8e57-d37f7ec29066
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '11':
    id: '11'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '15'
    scriptarguments:
      Domain:
        simple: ${inputs.Domain}
    separatecontext: false
    task:
      brand: ''
      description: Enrich Domain using one or more integrations
      id: 5799a021-f77c-457b-85bc-e362b7ff4b43
      iscommand: false
      name: Domain Enrichment - Generic
      playbookName: Domain Enrichment - Generic
      type: playbook
      version: -1
    taskid: 5799a021-f77c-457b-85bc-e362b7ff4b43
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 709\n  }\n}"
  '12':
    id: '12'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '15'
    scriptarguments:
      Username:
        simple: ${inputs.Username}
    separatecontext: false
    task:
      brand: ''
      description: Enrich Accounts using one or more integrations
      id: f9ef04ef-5311-4cd3-8c5e-eff47f95b3d3
      iscommand: false
      name: Account Enrichment - Generic
      playbookName: Account Enrichment - Generic
      type: playbook
      version: -1
    taskid: f9ef04ef-5311-4cd3-8c5e-eff47f95b3d3
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '13':
    id: '13'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '15'
    scriptarguments:
      MD5:
        simple: ${inputs.MD5}
      SHA1:
        simple: ${inputs.SHA1}
      SHA256:
        simple: ${inputs.SHA256}
    separatecontext: false
    task:
      brand: ''
      description: Get file reputation using one or more integrations
      id: 07d8b6e7-df26-4c17-80f0-e8bd093720e0
      iscommand: false
      name: File Enrichment - Generic
      playbookName: File Enrichment - Generic
      type: playbook
      version: -1
    taskid: 07d8b6e7-df26-4c17-80f0-e8bd093720e0
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 225\n  }\n}"
  '15':
    id: '15'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 38007764-1687-47b1-8490-0f3cded9dc95
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 38007764-1687-47b1-8490-0f3cded9dc95
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 881\n  }\n}"
  '2':
    id: '2'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '15'
    scriptarguments:
      url:
        simple: ${inputs.url}
    separatecontext: false
    task:
      brand: ''
      description: Enrich URL using one or more integrations
      id: 427040f6-9903-4122-8537-bd72d6fcdab2
      iscommand: false
      name: URL Enrichment - Generic
      playbookName: URL Enrichment - Generic
      type: playbook
      version: -1
    taskid: 427040f6-9903-4122-8537-bd72d6fcdab2
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 386\n  }\n}"
  '9':
    id: '9'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '15'
    scriptarguments:
      Domain: {}
      Email:
        simple: ${inputs.Email}
    separatecontext: false
    task:
      brand: ''
      description: Get email address reputation using one or more integrations
      id: 7ea079dc-c904-4088-878d-908e7b5b1ab3
      iscommand: false
      name: Email Address Enrichment - Generic
      playbookName: Email Address Enrichment - Generic
      type: playbook
      version: -1
    taskid: 7ea079dc-c904-4088-878d-908e7b5b1ab3
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 386\n  }\n}"
tests:
- no test - each enrichment sub-playbook has or will have its own test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 879,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 67\n\
  \    }\n  }\n}"
