description: Get email address reputation using one or more integrations
fromversion: 3.6.0
id: email_address_enrichment_-_generic
inputs:
- description: A list of internal domains
  key: Domain
  required: false
  value: {}
- description: The email addresses to enrich
  key: Email
  required: false
  value:
    complex:
      accessor: Email.Address
      root: Account
- description: Should the playbook get reputation for the Email Address
  key: GetReputation
  required: true
  value:
    simple: 'True'
name: Email Address Enrichment - Generic
outputs:
- contextPath: Account
  description: The Account's object
  type: unknown
- contextPath: Account.Email.Address
  description: The Email account full address
  type: string
- contextPath: Account.Groups
  description: The groups the Account is part of
  type: string
- contextPath: Account.Email.Domain
  description: The Email account domain
  type: string
- contextPath: Account.Email.NetworkType
  description: The Email account NetworkType (could be Internal/External)
  type: string
- contextPath: Account.Type
  description: Type of the Account entity
  type: string
- contextPath: Account.Email.Username
  description: The Email account username
  type: string
- contextPath: Account.ID
  description: The unique Account DN (Distinguished Name)
  type: string
- contextPath: Account.DisplayName
  description: The Account display name
  type: string
- contextPath: Account.Manager
  description: The Account's manager
  type: string
- contextPath: Account.Email.Distance.Domain
  description: The compared domain
  type: string
- contextPath: Account.Email.Distance.Value
  description: 'The distance between the email domain and the compared domain '
  type: number
- contextPath: DBotScore.Indicator
  description: The Indicator
  type: string
- contextPath: DBotScore
  description: The DBotScore's object
  type: unknown
- contextPath: DBotScore.Type
  description: The Indicator Type
  type: string
- contextPath: DBotScore.Vendor
  description: The DBot score vendor
  type: string
- contextPath: DBotScore.Score
  description: The DBot score
  type: number
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '5'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 10b003be-68f2-4e57-8f11-d0475f1aac42
      iscommand: false
      name: ''
      version: -1
    taskid: 10b003be-68f2-4e57-8f11-d0475f1aac42
    type: start
    view: "{\n  \"position\": {\n    \"x\": 387.5,\n    \"y\": 50\n  }\n}"
  '10':
    id: '10'
    nexttasks:
      '#none#':
      - '16'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: e82515ea-9f9a-4273-8182-e6a84b24e4d6
      iscommand: false
      name: Internal
      type: title
      version: -1
    taskid: e82515ea-9f9a-4273-8182-e6a84b24e4d6
    type: title
    view: "{\n  \"position\": {\n    \"x\": 1175,\n    \"y\": 735\n  }\n}"
  '11':
    id: '11'
    nexttasks:
      '#none#':
      - '18'
      - '19'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: d501d6f3-d086-40fa-8c28-052fc32787fb
      iscommand: false
      name: External
      type: title
      version: -1
    taskid: d501d6f3-d086-40fa-8c28-052fc32787fb
    type: title
    view: "{\n  \"position\": {\n    \"x\": 377.5,\n    \"y\": 895\n  }\n}"
  '12':
    id: '12'
    nexttasks:
      '#none#':
      - '4'
    scriptarguments:
      attributes: {}
      customFieldData: {}
      customFieldType: {}
      dn: {}
      email:
        complex:
          accessor: Email.Address
          filters:
          - - left:
                iscontext: true
                value:
                  simple: Account.Email.NetworkType
              operator: string.isEqual
              right:
                value:
                  simple: Internal
          root: Account
      headers: {}
      limit: {}
      name: {}
      nestedSearch: {}
      userAccountControlOut: {}
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: Use Active Directory to get internal email address user information
      id: e66c5a66-3272-4ef8-8283-b0bc74af7cd0
      iscommand: false
      name: Get Email addresses info from Active Directory
      scriptName: ADGetUser
      type: regular
      version: -1
    taskid: e66c5a66-3272-4ef8-8283-b0bc74af7cd0
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1287.5,\n    \"y\": 1215\n  }\n}"
  '13':
    id: '13'
    nexttasks:
      '#default#':
      - '4'
      'yes':
      - '11'
    scriptarguments:
      value:
        complex:
          accessor: Email
          filters:
          - - left:
                iscontext: true
                value:
                  simple: Account.Email.NetworkType
              operator: string.isEqual
              right:
                value:
                  simple: External
          root: Account
    separatecontext: false
    task:
      brand: ''
      description: 'Check for Email Addresses with external NetworkType '
      id: f335c2d8-9c33-4b5e-8cf6-d8ab05f9cb9a
      iscommand: false
      name: Are there external email addresses?
      scriptName: Exists
      type: condition
      version: -1
    taskid: f335c2d8-9c33-4b5e-8cf6-d8ab05f9cb9a
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 720\n  }\n}"
  '14':
    id: '14'
    nexttasks:
      '#default#':
      - '4'
      'yes':
      - '10'
    scriptarguments:
      value:
        complex:
          accessor: Email
          filters:
          - - left:
                iscontext: true
                value:
                  simple: Account.Email.NetworkType
              operator: string.isEqual
              right:
                value:
                  simple: Internal
          root: Account
    separatecontext: false
    task:
      brand: ''
      description: 'Check for Email Addresses with internal NetworkType '
      id: 882a4290-4166-4b8a-81f9-b5d163f34f06
      iscommand: false
      name: Are there internal email addresses?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 882a4290-4166-4b8a-81f9-b5d163f34f06
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 1062.5,\n    \"y\": 545\n  }\n}"
  '15':
    id: '15'
    nexttasks:
      '#none#':
      - '4'
    scriptarguments:
      domain:
        complex:
          root: inputs.Domain
      email:
        complex:
          accessor: Email.Address
          filters:
          - - left:
                iscontext: true
                value:
                  simple: Account.Email.NetworkType
              operator: string.isEqual
              right:
                value:
                  simple: External
          root: Account
      threshold: {}
    separatecontext: false
    task:
      brand: ''
      description: Check if an email address's domain is trying to squat other domain
        using Levenshtein distance algorithm
      id: ab84c271-880d-4dc8-8feb-e73c2d4004e0
      iscommand: false
      name: Check Email addresses DomainSquatting Reputation
      scriptName: EmailDomainSquattingReputation
      type: regular
      version: -1
    taskid: ab84c271-880d-4dc8-8feb-e73c2d4004e0
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 140.5,\n    \"y\": 1215\n  }\n}"
  '16':
    id: '16'
    nexttasks:
      '#none#':
      - '17'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 9752ef45-8db2-45cc-80df-0926909ddf73
      iscommand: false
      name: Active Directory
      type: title
      version: -1
    taskid: 9752ef45-8db2-45cc-80df-0926909ddf73
    type: title
    view: "{\n  \"position\": {\n    \"x\": 1175,\n    \"y\": 895\n  }\n}"
  '17':
    id: '17'
    nexttasks:
      '#default#':
      - '4'
      'yes':
      - '12'
    scriptarguments:
      value:
        complex:
          accessor: brand
          filters:
          - - left:
                iscontext: true
                value:
                  simple: modules.brand
              operator: string.isEqual
              right:
                value:
                  simple: activedir
          - - left:
                iscontext: true
                value:
                  simple: modules.state
              operator: string.isEqual
              right:
                value:
                  simple: active
          root: modules
    separatecontext: false
    task:
      brand: ''
      description: Check if there's an active instance of Active Directory
      id: a030b50a-b7ba-4aba-89db-eb2a50d29e4d
      iscommand: false
      name: Is Active Directory enabled?
      scriptName: Exists
      type: condition
      version: -1
    taskid: a030b50a-b7ba-4aba-89db-eb2a50d29e4d
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 1175,\n    \"y\": 1040\n  }\n}"
  '18':
    id: '18'
    nexttasks:
      '#default#':
      - '4'
      'yes':
      - '15'
    scriptarguments:
      value:
        complex:
          root: inputs.Domain
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 2a3f300c-f84f-43ac-8ec7-c98afd558416
      iscommand: false
      name: Is there a domain list input?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 2a3f300c-f84f-43ac-8ec7-c98afd558416
    type: condition
    view: "{\n  \"position\": {\n    \"x\": -32,\n    \"y\": 1040\n  }\n}"
  '19':
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                root: inputs.GetReputation
          operator: string.isEqual
          right:
            value:
              simple: 'True'
      label: 'yes'
    id: '19'
    nexttasks:
      '#default#':
      - '4'
      'yes':
      - '7'
    separatecontext: false
    task:
      brand: ''
      description: '

        Should the system retrieve the  Email Addresses reputation from all of the
        relevant integration?

        Default: True'
      id: b0e3026b-ae43-4032-8074-381bfd0f8fa3
      iscommand: false
      name: Should the system get the Email Addresses reputation?
      type: condition
      version: -1
    taskid: b0e3026b-ae43-4032-8074-381bfd0f8fa3
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 705,\n    \"y\": 1040\n  }\n}"
  '4':
    id: '4'
    scriptarguments:
      details: {}
      fromclosedate: {}
      fromdate: {}
      fromduedate: {}
      id: {}
      level: {}
      name: {}
      notstatus: {}
      owner: {}
      page: {}
      query:
        simple: entry.contents:${Account.Username}
      reason: {}
      size: {}
      sort: {}
      status: {}
      toclosedate: {}
      todate: {}
      toduedate: {}
      type: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 01ab9a35-e60e-4331-826d-48194fb5a771
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 01ab9a35-e60e-4331-826d-48194fb5a771
    type: title
    view: "{\n  \"position\": {\n    \"x\": 592.5,\n    \"y\": 1390\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Email
          operator: general.isExists
      label: 'yes'
    id: '5'
    nexttasks:
      '#default#':
      - '4'
      'yes':
      - '9'
    separatecontext: false
    task:
      brand: ''
      description: Checks that the input email address is not empty
      id: 58fbce31-8318-47d5-881e-b17a428d22e0
      iscommand: false
      name: Are there Email addresses to check?
      type: condition
      version: -1
    taskid: 58fbce31-8318-47d5-881e-b17a428d22e0
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 387.5,\n    \"y\": 195\n  }\n}"
  '7':
    continueonerror: true
    id: '7'
    nexttasks:
      '#none#':
      - '4'
    scriptarguments:
      email:
        complex:
          accessor: Email.Address
          filters:
          - - left:
                iscontext: true
                value:
                  simple: Account.Email.NetworkType
              operator: string.isEqual
              right:
                value:
                  simple: External
          root: Account
    separatecontext: false
    task:
      brand: ''
      description: Get email address reputation from all supporting integrations
      id: 3291020c-5ec9-4f58-8814-27c07a575dc0
      iscommand: false
      name: Check Email addresses  reputation
      scriptName: EmailReputation
      type: regular
      version: -1
    taskid: 3291020c-5ec9-4f58-8814-27c07a575dc0
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 592.5,\n    \"y\": 1215\n  }\n}"
  '9':
    id: '9'
    nexttasks:
      '#none#':
      - '13'
      - '14'
    scriptarguments:
      domain:
        complex:
          root: inputs.Domain
      email:
        complex:
          root: inputs.Email
      extend-context: {}
    separatecontext: false
    task:
      brand: ''
      description: Add to each email address a NetworkType attribute
      id: 550ff29a-79f5-4274-847f-fabf4193d2a7
      iscommand: false
      name: Mark Email addresses as internal or external
      scriptName: IsEmailAddressInternal
      type: regular
      version: -1
    taskid: 550ff29a-79f5-4274-847f-fabf4193d2a7
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 500,\n    \"y\": 370\n  }\n}"
tests:
- No test - deprecated. use V2.1 instead.
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"13_4_#default#\": 0.74\n  },\n  \"paper\"\
  : {\n    \"dimensions\": {\n      \"height\": 1405,\n      \"width\": 1699.5,\n\
  \      \"x\": -32,\n      \"y\": 50\n    }\n  }\n}"
