description: This playbook identifies duplicate incidents using one of the supported
  methods.
fromversion: 4.0.0
id: dedup_-_generic
inputs:
- description: Select a method for identifying duplicate incidents. Can be "ml", "rules",
    or "text".
  key: DuplicateMethod
  required: true
  value:
    simple: ml
- description: The similarity threshold to consider an incident as a duplicate (0-1),
    where "1" is a duplicate and "0" is not a duplicate. Use this argument in the
    ML or text methods. A si
  key: DuplicateThreshold
  required: true
  value:
    simple: '0.75'
- description: The time frame (in hours) in which to check for duplicate incident
    candidates.
  key: TimeFrameHours
  required: true
  value:
    simple: '72'
- description: Whether to ignore closed incidents. Can be "yes" or "no".
  key: IgnoreCloseIncidents
  required: true
  value:
    simple: 'yes'
- description: The maximum number of candidates to check for duplication.
  key: MaxNumberOfCandidates
  required: false
  value:
    simple: '1000'
- description: Whether to close incidents identified as duplicates. Can be "true"
    or "false".
  key: CloseAsDuplicate
  required: false
  value:
    simple: 'true'
- description: 'The Time field by which to query past incidents to check for duplicate
    incident candidates. Values: created, occurred, modified'
  key: TimeField
  required: false
  value:
    simple: created
name: Dedup - Generic
outputs:
- contextPath: isSimilarIncidentFound
  description: Whether a similar incident was found? Can be "true" or "false".
  type: boolean
- contextPath: similarIncident
  description: The similar incident.
  type: unknown
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 4bb4cba3-1da4-4356-831e-87ca6523087a
      iscommand: false
      name: ''
      version: -1
    taskid: 4bb4cba3-1da4-4356-831e-87ca6523087a
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 50\n  }\n}"
  '1':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.DuplicateMethod
          operator: isEqualString
          right:
            value:
              simple: ml
      label: ml
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.DuplicateMethod
          operator: isEqualString
          right:
            value:
              simple: rules
      label: rules
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.DuplicateMethod
          operator: isEqualString
          right:
            value:
              simple: text
      label: text
    id: '1'
    ignoreworker: false
    nexttasks:
      ml:
      - '7'
      rules:
      - '6'
      text:
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: 'Select one of the following methods to identify duplicate incidents
        in Demisto.

        - ml: Machine learning model, which is trained mostly on phishing incidents.

        -rules: Rules help identify duplicate incidents when the logic is well defined,
        for example, same label or custom fields.

        -text: Statistics algorithm that compares text, which is generally useful
        for phishing incidents.'
      id: 48f0cedf-fad2-47db-81fd-348b062f41fe
      iscommand: false
      name: Select method to identify duplicates
      type: condition
      version: -1
    taskid: 48f0cedf-fad2-47db-81fd-348b062f41fe
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 195\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      ignoreClosedIncidents:
        simple: ${inputs.IgnoreCloseIncidents}
      maxResults: {}
      maximumNumberOfIncidents:
        simple: ${inputs.MaxNumberOfCandidates}
      minTextLength: {}
      textFields:
        simple: name,details
      threshold:
        simple: ${inputs.DuplicateThreshold}
      timeField:
        simple: ${inputs.TimeField}
      timeFrameHours:
        simple: ${inputs.TimeFrameHours}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: e533da63-e23f-43b2-8b12-e709e62401c0
      iscommand: false
      name: Identify duplicates by text
      scriptName: FindSimilarIncidentsByText
      type: regular
      version: -1
    taskid: e533da63-e23f-43b2-8b12-e709e62401c0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: isSimilarIncidentFound
          operator: isTrue
      - - left:
            iscontext: true
            value:
              simple: inputs.CloseAsDuplicate
          operator: isTrue
      label: 'yes'
    id: '5'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '9'
      'yes':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Checks if any duplicate incidents were found.
      id: 54a58f44-4f47-452c-8a4a-c7f64d5c499a
      iscommand: false
      name: Check if duplicates were found
      type: condition
      version: -1
    taskid: 54a58f44-4f47-452c-8a4a-c7f64d5c499a
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      filterQuery: {}
      hoursBack:
        simple: ${inputs.TimeFrameHours}
      ignoreClosedIncidents:
        simple: ${inputs.IgnoreCloseIncidents}
      incidentFieldsAppliedCondition: {}
      maxNumberOfIncidents:
        simple: ${inputs.MaxNumberOfCandidates}
      maxResults: {}
      similarContextKeys: {}
      similarCustomFields: {}
      similarIncidentFields:
        simple: type
      similarIncidentKeys: {}
      similarLabelsKeys:
        simple: Email/subject:*,Email/from
      skipMissingValues: {}
      timeField:
        simple: ${inputs.TimeField}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: bcc06547-4ca6-4ef4-8f3d-71c170f48218
      iscommand: false
      name: Identify similar incidents using rules
      scriptName: FindSimilarIncidents
      type: regular
      version: -1
    taskid: bcc06547-4ca6-4ef4-8f3d-71c170f48218
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      UseLocalEnvDuplicatesInLastDays: {}
      compareEmailLabels: {}
      compareIncidentTimeDiff: {}
      compareIndicators: {}
      compareOtherLabels: {}
      ignoreClosedIncidents:
        simple: ${inputs.IgnoreCloseIncidents}
      ipComparisonSubnetMask: {}
      maxCandidates: {}
      maxNumberOfIncidents:
        simple: ${inputs.MaxNumberOfCandidates}
      maxResults: {}
      threshold:
        simple: ${inputs.DuplicateThreshold}
      timeField:
        simple: ${inputs.TimeField}
      timeFrameHours:
        simple: ${inputs.TimeFrameHours}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 8148ea43-d8fd-44ea-8390-1d9661014141
      iscommand: false
      name: Identify duplicates using ML
      scriptName: GetDuplicatesMlv2
      type: regular
      version: -1
    taskid: 8148ea43-d8fd-44ea-8390-1d9661014141
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 370\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      duplicateId:
        simple: ${similarIncident.rawId}
    separatecontext: false
    task:
      brand: ''
      description: Closes the investigation as a duplicate to one of the incidents
        identified.
      id: 857267ed-a8bf-4d65-8a80-967656990b57
      iscommand: false
      name: Close investigation as duplicate
      scriptName: CloseInvestigationAsDuplicate
      type: regular
      version: -1
    taskid: 857267ed-a8bf-4d65-8a80-967656990b57
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 190,\n    \"y\": 750\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: c1f06a79-d539-4853-8140-f1f879a8f137
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: c1f06a79-d539-4853-8140-f1f879a8f137
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 490,\n    \"y\": 1000\n  }\n}"
tests:
- No tests
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1015,\n      \"width\": 1240,\n      \"x\": 50,\n      \"y\":\
  \ 50\n    }\n  }\n}"
