description: 'Manage vulnerability remediation using Qualys data, and optionally enrich
  data with 3rd-party tools.


  Before you run this playbook, run the "Vulnerability Management - Qualys (Job)"
  playbook.'
fromversion: 3.6.0
id: vulnerability_handling_-_qualys
inputs: []
name: Vulnerability Handling - Qualys
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '12'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 70a808bd-c5f5-4a34-8e73-7bd426ea3c48
      iscommand: false
      name: ''
      version: -1
    taskid: 70a808bd-c5f5-4a34-8e73-7bd426ea3c48
    type: start
    view: "{\n  \"position\": {\n    \"x\": 1370,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      ag_ids: {}
      ag_titles: {}
      compliance_enabled: {}
      compliance_scan_since: {}
      details: {}
      id_max: {}
      id_min: {}
      ids:
        complex:
          accessor: assetid
          root: incident
      ips: {}
      network_ids: {}
      no_compliance_scan_since: {}
      no_vm_scan_since: {}
      os_pattern: {}
      truncation_limit: {}
      vm_scan_since: {}
    separatecontext: false
    task:
      brand: Qualys
      description: Get asset metadata from Qualys based on Asset ID.
      id: c028a317-3e87-4ee2-85c9-53754152340d
      iscommand: true
      name: Get Asset information
      script: Qualys|||qualys-host-list
      type: regular
      version: -1
    taskid: c028a317-3e87-4ee2-85c9-53754152340d
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1257.5,\n    \"y\": 515\n  }\n}"
  '10':
    id: '10'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '19'
    scriptarguments:
      Hostname:
        complex:
          accessor: Endpoint.NETBIOS
          root: Qualys
    separatecontext: true
    task:
      brand: ''
      description: ''
      id: 01d06edb-b109-4ce1-8618-ad49f8f33648
      iscommand: false
      name: Endpoint Enrichment - Generic
      playbookName: Endpoint Enrichment - Generic
      type: playbook
      version: -1
    taskid: 01d06edb-b109-4ce1-8618-ad49f8f33648
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 1482.5,\n    \"y\": 1010\n  }\n}"
  '11':
    id: '11'
    nexttasks:
      '#none#':
      - '19'
    separatecontext: true
    task:
      brand: ''
      description: ''
      id: 60d2a53c-3ae5-453f-875a-1203347f16e7
      iscommand: false
      name: CVE Enrichment - Generic
      playbookName: CVE Enrichment - Generic
      type: playbook
      version: -1
    taskid: 60d2a53c-3ae5-453f-875a-1203347f16e7
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 1912.5,\n    \"y\": 1010\n  }\n}"
  '12':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: string.isEqual
                    right:
                      value:
                        simple: Qualys
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: string.isEqual
                    right:
                      value:
                        simple: active
                root: modules
          operator: general.isExists
      label: 'yes'
    id: '12'
    nexttasks:
      '#default#':
      - '7'
      'yes':
      - '17'
    separatecontext: false
    task:
      brand: ''
      description: Verify that there's a valid instance of Qualys enabled.
      id: a7ff415a-8066-4f3c-826c-5c6f840075f2
      iscommand: false
      name: Is Qualys enabled?
      type: condition
      version: -1
    taskid: a7ff415a-8066-4f3c-826c-5c6f840075f2
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 1370,\n    \"y\": 195\n  }\n}"
  '14':
    id: '14'
    nexttasks:
      '#none#':
      - '15'
    separatecontext: false
    task:
      brand: ''
      description: Manually remediate the vulnerability using the remediation note
        from Qualys.
      id: 65d23550-509d-4f8b-8f31-a9ec236d59d0
      iscommand: false
      name: 'Remediate the vulnerability '
      type: regular
      version: -1
    taskid: 65d23550-509d-4f8b-8f31-a9ec236d59d0
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 725,\n    \"y\": 1680\n  }\n}"
  '15':
    id: '15'
    nexttasks:
      '#none#':
      - '18'
    scriptarguments:
      notes: {}
      reason: {}
    separatecontext: false
    task:
      brand: ''
      description: Close the investigation.
      id: fd70751e-253f-404b-8820-e63a3eff0d68
      iscommand: false
      name: Close Investigation
      scriptName: CloseInvestigation
      type: regular
      version: -1
    taskid: fd70751e-253f-404b-8820-e63a3eff0d68
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 725,\n    \"y\": 1855\n  }\n}"
  '17':
    id: '17'
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 2d483c30-2066-4696-82f9-781aa207df9f
      iscommand: false
      name: Get incident information from Qualys
      type: title
      version: -1
    taskid: 2d483c30-2066-4696-82f9-781aa207df9f
    type: title
    view: "{\n  \"position\": {\n    \"x\": 1257.5,\n    \"y\": 370\n  }\n}"
  '18':
    id: '18'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: ab94f99a-9546-4837-8ed9-cfe970154bea
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: ab94f99a-9546-4837-8ed9-cfe970154bea
    type: title
    view: "{\n  \"position\": {\n    \"x\": 725,\n    \"y\": 2030\n  }\n}"
  '19':
    id: '19'
    nexttasks:
      '#none#':
      - '7'
    separatecontext: true
    task:
      brand: ''
      description: ''
      id: 3e271fab-839e-4253-8aa9-f8579c607fd6
      iscommand: false
      name: Vulnerability Management - Qualys - Add custom fields
      playbookName: Vulnerability Handling - Qualys - Add custom fields to default
        layout
      type: playbook
      version: -1
    taskid: 3e271fab-839e-4253-8aa9-f8579c607fd6
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 1697.5,\n    \"y\": 1185\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
      - '4'
    scriptarguments:
      details: {}
      discovery_auth_types: {}
      discovery_method: {}
      extend-context:
        simple: Qualys.Consequence=KNOWLEDGE_BASE_VULN_LIST_OUTPUT.RESPONSE.VULN_LIST.VULN.CONSEQUENCE::Qualys.Diagnosis=KNOWLEDGE_BASE_VULN_LIST_OUTPUT.RESPONSE.VULN_LIST.VULN.DIAGNOSIS::Qualys.Solution=KNOWLEDGE_BASE_VULN_LIST_OUTPUT.RESPONSE.VULN_LIST.VULN.SOLUTION::CVE.ID=KNOWLEDGE_BASE_VULN_LIST_OUTPUT.RESPONSE.VULN_LIST.VULN.CVE_LIST.CVE.ID::Qualys.Severity=KNOWLEDGE_BASE_VULN_LIST_OUTPUT.RESPONSE.VULN_LIST.VULN.SEVERITY_LEVEL::Qualys.Category=KNOWLEDGE_BASE_VULN_LIST_OUTPUT.RESPONSE.VULN_LIST.VULN.CATEGORY::Qualys.Bugtraq=KNOWLEDGE_BASE_VULN_LIST_OUTPUT.RESPONSE.VULN_LIST.VULN.BUGTRAQ_LIST.BUGTRAQ::Qualys.Title=KNOWLEDGE_BASE_VULN_LIST_OUTPUT.RESPONSE.VULN_LIST.VULN.TITLE
      id_max: {}
      id_min: {}
      ids:
        complex:
          accessor: vendorid
          root: incident
      is_patchable: {}
      last_modified_after: {}
      last_modified_before: {}
      last_modified_by_service_after: {}
      last_modified_by_service_before: {}
      last_modified_by_user_after: {}
      last_modified_by_user_before: {}
      published_after: {}
      published_before: {}
      show_pci_reasons: {}
    separatecontext: false
    task:
      brand: Qualys
      description: Get vulnerability metadata from Qualys based on QID.
      id: a0bb5b2f-f89a-48ec-8cef-70477b2adf1e
      iscommand: true
      name: Get Vulnerability information
      script: Qualys|||qualys-vulnerability-list
      type: regular
      version: -1
    taskid: a0bb5b2f-f89a-48ec-8cef-70477b2adf1e
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1257.5,\n    \"y\": 690\n  }\n}"
  '20':
    id: '20'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '14'
    scriptarguments:
      CriticalEndpoints: {}
      CriticalGroups: {}
      CriticalUsers: {}
    separatecontext: false
    task:
      brand: ''
      description: 'Calculate incident severity by indicators reputation and user/endpoint
        membership in critical groups.


        Note - current severity will be overwritten and new severity may be lower
        than the current one.


        Playbook inputs:

        * CriticalUsers - Comma separated array with usernames of critical users

        * CriticalEndpoints - Comma separated array with hostnames of critical endpoints

        * CriticalGroups - Comma separated array with DN of critical Active Directory
        groups'
      id: cd0cd64a-046d-467f-836f-3afa1f8e5acf
      iscommand: false
      name: Calculate Severity - Generic
      playbookName: Calculate Severity - Generic
      type: playbook
      version: -1
    taskid: cd0cd64a-046d-467f-836f-3afa1f8e5acf
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 725,\n    \"y\": 1505\n  }\n}"
  '21':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Consequence
                root: Qualys
          operator: general.isExists
      label: 'yes'
    id: '21'
    nexttasks:
      '#default#':
      - '7'
      'yes':
      - '22'
    separatecontext: false
    task:
      brand: ''
      description: Verify that there's a consequence for the detected vulnerability
        in context.
      id: e70ad3fc-4274-4b7b-8e05-564266f65b2e
      iscommand: false
      name: Is there a consequence for the vulnerability?
      type: condition
      version: -1
    taskid: e70ad3fc-4274-4b7b-8e05-564266f65b2e
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 612.5,\n    \"y\": 1010\n  }\n}"
  '22':
    id: '22'
    nexttasks:
      '#none#':
      - '7'
    scriptarguments:
      header:
        simple: Vulnerability Consequence
      html:
        complex:
          accessor: Consequence
          root: Qualys
      markAsNote:
        simple: 'true'
    separatecontext: false
    task:
      brand: ''
      description: Display the remediation HTML in the War Room.
      id: 85f071de-346c-4cf6-8a54-6bef8b32e3c1
      iscommand: false
      name: Display consequence
      scriptName: DisplayHTML
      type: regular
      version: -1
    taskid: 85f071de-346c-4cf6-8a54-6bef8b32e3c1
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 500,\n    \"y\": 1185\n  }\n}"
  '23':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Solution
                root: Qualys
          operator: general.isExists
      label: 'yes'
    id: '23'
    nexttasks:
      'yes':
      - '24'
    separatecontext: false
    task:
      brand: ''
      description: Verify that there's a remediation for the detected vulnerability
        in context.
      id: e142b442-105b-4016-8d77-40eb431e5503
      iscommand: false
      name: Is there a remediation for the vulnerability?
      type: condition
      version: -1
    taskid: e142b442-105b-4016-8d77-40eb431e5503
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 1052.5,\n    \"y\": 1010\n  }\n}"
  '24':
    id: '24'
    nexttasks:
      '#none#':
      - '7'
    scriptarguments:
      header:
        simple: Vulnerability Remediation
      html:
        complex:
          accessor: Solution
          root: Qualys
      markAsNote:
        simple: 'true'
    separatecontext: false
    task:
      brand: ''
      description: Display the remediation HTML in the War Room.
      id: e9c369da-0f47-4243-8628-c8f959084f2d
      iscommand: false
      name: Display remediation
      scriptName: DisplayHTML
      type: regular
      version: -1
    taskid: e9c369da-0f47-4243-8628-c8f959084f2d
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1052.5,\n    \"y\": 1185\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '6'
      - '21'
      - '23'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: f557cc38-4b4e-4beb-88fa-55a1c6cc3de6
      iscommand: false
      name: Mark important notes
      type: title
      version: -1
    taskid: f557cc38-4b4e-4beb-88fa-55a1c6cc3de6
    type: title
    view: "{\n  \"position\": {\n    \"x\": 612.5,\n    \"y\": 865\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '10'
      - '11'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: cdbea748-55ef-48c7-8e82-df37a53667ff
      iscommand: false
      name: Enrich Entities
      type: title
      version: -1
    taskid: cdbea748-55ef-48c7-8e82-df37a53667ff
    type: title
    view: "{\n  \"position\": {\n    \"x\": 1697.5,\n    \"y\": 865\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '7'
    scriptarguments:
      header:
        simple: Vulnerability Diagnosis
      html:
        complex:
          accessor: Diagnosis
          root: Qualys
      markAsNote:
        simple: 'true'
    separatecontext: false
    task:
      brand: ''
      description: Display the diagnosis HTML in the War Room.
      id: d75db3b1-aeec-44f1-88c9-fb782f8f0291
      iscommand: false
      name: 'Display diagnosis '
      scriptName: DisplayHTML
      type: regular
      version: -1
    taskid: d75db3b1-aeec-44f1-88c9-fb782f8f0291
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1185\n  }\n}"
  '6':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Diagnosis
                root: Qualys
          operator: general.isExists
      label: 'yes'
    id: '6'
    nexttasks:
      '#default#':
      - '7'
      'yes':
      - '5'
    separatecontext: false
    task:
      brand: ''
      description: Verify that there's a diagnosis for the detected vulnerability
        in context.
      id: 3a0acb6e-cd22-42b7-86cf-2c0c638d6e41
      iscommand: false
      name: Is there a diagnosis for the vulnerability?
      type: condition
      version: -1
    taskid: 3a0acb6e-cd22-42b7-86cf-2c0c638d6e41
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1010\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '20'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 58ab86c1-fd77-4a67-8804-2e8cc87eedb4
      iscommand: false
      name: Remediate
      type: title
      version: -1
    taskid: 58ab86c1-fd77-4a67-8804-2e8cc87eedb4
    type: title
    view: "{\n  \"position\": {\n    \"x\": 725,\n    \"y\": 1360\n  }\n}"
tests:
- No test - Should review soon
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"12_7_#default#\": 0.52\n  },\n  \"paper\"\
  : {\n    \"dimensions\": {\n      \"height\": 2045,\n      \"width\": 2242.5,\n\
  \      \"x\": 50,\n      \"y\": 50\n    }\n  }\n}"
