description: 'Check for duplicate incidents for the current incident, and close it
  if any duplicate has found.

  '
fromversion: 3.5.0
id: close_incident_if_duplicate_found
inputs:
- description: Identical incident keys
  key: similarIncidentKeys
  required: false
  value: {}
- description: "Identical\\Similar labels keys.\nYou allow difference in X words between\
    \ labels. For example, the input:\nEmail\\subject:2,Email\\from\nWill demand:\n\
    1. Email\\from to be identical \n2. Email\\subject to be similar with 2 max words\
    \ difference\n"
  key: similarLabels
  required: false
  value: {}
- description: 'Identical\Similar context keys.

    You allow difference in X words between values. '
  key: similarContextKeys
  required: false
  value: {}
- description: 'Identical\Similar custom fields.

    You allow difference in X words between values.'
  key: similarCustomFields
  required: false
  value: {}
- description: Check incidents within X hours back.
  key: hoursBack
  required: false
  value:
    simple: '24'
name: DeDup incidents
outputs:
- contextPath: isSimilarIncidentFound
  description: Is similar incident found? (true\false)
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '2'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 0c9fa614-e05a-4144-8e40-6b736392a16a
      iscommand: false
      name: ''
      version: -1
    taskid: 0c9fa614-e05a-4144-8e40-6b736392a16a
    type: start
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 51\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '4'
    scriptarguments:
      hoursBack:
        simple: ${inputs.hoursBack}
      ignoreClosedIncidents:
        simple: 'no'
      ignoreMissingKeys: {}
      maxNumberOfIncidents: {}
      minimumContextKeysToCompare: {}
      minimumCustomFieldsToCompare: {}
      minimumLabelsKeysToCompare: {}
      minimumNumberOfKeysToCompare: {}
      similarContextKeys:
        simple: ${inputs.similarContextKeys}
      similarCustomFields:
        simple: ${inputs.similarCustomFields}
      similarIncidentKeys:
        simple: ${inputs.similarIncidentKeys}
      similarLabelsKeys:
        simple: ${inputs.similarLabels}
    separatecontext: false
    task:
      brand: ''
      description: Find duplicate incidents for the current incident.
      id: 6c68450d-d32f-4a07-8978-8df36190ada6
      iscommand: false
      name: Find duplicate incidents
      scriptName: FindSimilarIncidents
      type: regular
      version: -1
    taskid: 6c68450d-d32f-4a07-8978-8df36190ada6
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 194\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '5'
    scriptarguments:
      duplicateId:
        simple: ${similarIncident.rawId}
    separatecontext: false
    task:
      brand: ''
      description: Close the current investigation as duplicate.
      id: bced6173-64c6-457c-85bd-2adf6be16c4c
      iscommand: false
      name: Close as duplicate
      scriptName: CloseInvestigationAsDuplicate
      type: regular
      version: -1
    taskid: bced6173-64c6-457c-85bd-2adf6be16c4c
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: isSimilarIncidentFound
          operator: isTrue
      label: 'yes'
    id: '4'
    nexttasks:
      '#default#':
      - '5'
      'yes':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Check if there is any duplicate incident found.
      id: e1952276-e1b2-4748-8198-9bc500d5c504
      iscommand: false
      name: Is duplicate incident found?
      type: condition
      version: -1
    taskid: e1952276-e1b2-4748-8198-9bc500d5c504
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 369\n  }\n}"
  '5':
    id: '5'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 813eba13-6ed9-4050-8d77-f9c3e0a3d07c
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 813eba13-6ed9-4050-8d77-f9c3e0a3d07c
    type: title
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 720\n  }\n}"
tests:
- No tests
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 734,\n      \"width\": 492.5,\n      \"x\": 50,\n      \"y\":\
  \ 51\n    }\n  }\n}"
