description: Returns to the war-room a file sample correlating from a hash using one
  or more products
fromversion: 3.5.0
id: get_file_sample_by_hash_-_generic
inputs:
- description: Get file sample from MD5 input
  key: MD5
  required: false
  value:
    complex:
      accessor: MD5
      root: File
- description: Get file sample from SHA256 input
  key: SHA256
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
name: Get File Sample By Hash - Generic
outputs:
- contextPath: File
  description: File sample object
  type: unknown
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '2'
      - '3'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 0131a1f1-22f0-489d-8c41-ec4a0e89369d
      iscommand: false
      name: ''
      version: -1
    taskid: 0131a1f1-22f0-489d-8c41-ec4a0e89369d
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '2':
    id: '2'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '4'
    scriptarguments:
      SHA256:
        complex:
          root: inputs.SHA256
    separatecontext: true
    task:
      brand: ''
      description: ''
      id: 366fe696-1d20-4473-87b6-d0c2ce334996
      iscommand: false
      name: Get File Sample By Hash - Cylance Protect
      playbookName: Get File Sample By Hash - Cylance Protect
      type: playbook
      version: -1
    taskid: 366fe696-1d20-4473-87b6-d0c2ce334996
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '3':
    id: '3'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '4'
    scriptarguments:
      MD5:
        complex:
          root: inputs.MD5
    separatecontext: true
    task:
      brand: ''
      description: ''
      id: 88fbf584-4a72-4097-86e6-3d22957bdd3e
      iscommand: false
      name: Get File Sample By Hash - Carbon Black Enterprise Response
      playbookName: Get File Sample By Hash - Carbon Black Enterprise Response
      type: playbook
      version: -1
    taskid: 88fbf584-4a72-4097-86e6-3d22957bdd3e
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 195\n  }\n}"
  '4':
    id: '4'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 905fca17-4fc2-4efb-8db3-322ff915dee8
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 905fca17-4fc2-4efb-8db3-322ff915dee8
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
tests:
- No tests
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 385,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
