description: 'Enrich IP using one or more integrations.


  IP enrichment includes:

  * Resolve IP to Hostname (DNS)

  * Threat information

  * Separate internal and external addresses

  * IP reputation

  * For internal addresses, get host information'
fromversion: 3.6.0
id: ip_enrichment_generic
inputs:
- description: The IP address to enrich.
  key: IP
  required: false
  value:
    complex:
      accessor: Address
      root: IP
- description: 'The internal range to check against the IP address.

    The default range is taken from the IPv4 protocol.'
  key: InternalRange
  required: false
  value: {}
- description: Convert the IP address to a hostname using a DNS query (True/ False).
  key: ResolveIP
  required: true
  value:
    simple: 'True'
name: IP Enrichment - Generic
outputs:
- contextPath: IP
  description: The IP objects
  type: unknown
- contextPath: DBotScore
  description: Indicator, Score, Type, Vendor
  type: unknown
- contextPath: Endpoint
  description: The Endpoint's object
  type: unknown
- contextPath: Endpoint.Hostname
  description: The hostname to enrich
  type: string
- contextPath: Endpoint.OS
  description: Endpoint OS
  type: string
- contextPath: Endpoint.IP
  description: List of endpoint IP addresses
- contextPath: Endpoint.MAC
  description: List of endpoint MAC addresses
- contextPath: Endpoint.Domain
  description: Endpoint domain name
  type: string
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '28'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 6635b28b-bdf1-42cf-88bc-14ad75e9ebe0
      iscommand: false
      name: ''
      version: -1
    taskid: 6635b28b-bdf1-42cf-88bc-14ad75e9ebe0
    type: start
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 49\n  }\n}"
  '15':
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: Address
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: IP.InRange
                    operator: string.isEqual
                    right:
                      value:
                        simple: 'no'
                root: IP
          operator: general.isExists
      label: 'yes'
    id: '15'
    nexttasks:
      '#default#':
      - '24'
      'yes':
      - '27'
    reputationcalc: 0
    scriptarguments:
      extend-context: {}
      value:
        complex:
          accessor: Address
          filters:
          - - left:
                iscontext: true
                value:
                  simple: IP.InRange
              operator: string.isEqual
              right:
                value:
                  simple: 'no'
          root: IP
    separatecontext: false
    task:
      brand: ''
      description: Checks whether the "InRange" attribute is set to "no".
      id: 7cc4eee4-d804-45aa-8c51-06e9e5a53a64
      iscommand: false
      name: Is there an external IP address?
      type: condition
      version: -1
    taskid: 7cc4eee4-d804-45aa-8c51-06e9e5a53a64
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 500,\n    \"y\": 1040\n  }\n}"
  '19':
    continueonerror: true
    id: '19'
    nexttasks:
      '#none#':
      - '24'
    reputationcalc: 0
    scriptarguments:
      extend-context: {}
      file:
        simple: ${File.SHA256}
      ip:
        complex:
          accessor: Address
          filters:
          - - left:
                iscontext: true
                value:
                  simple: IP.InRange
              operator: string.isEqual
              right:
                value:
                  simple: 'no'
          root: IP
    separatecontext: false
    task:
      brand: ''
      description: Get the IP reputation from every integration that supports the
        `!ip` command.
      id: 74889e4f-d5ea-46d2-8cfb-aac15c10a52f
      iscommand: false
      name: Check IP reputation
      scriptName: IPReputation
      type: regular
      version: -1
    taskid: 74889e4f-d5ea-46d2-8cfb-aac15c10a52f
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 612.5,\n    \"y\": 1360\n  }\n}"
  '24':
    id: '24'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 8149db7c-af8d-41e2-85ee-c9fe2efd5040
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 8149db7c-af8d-41e2-85ee-c9fe2efd5040
    type: title
    view: "{\n  \"position\": {\n    \"x\": -291,\n    \"y\": 1845\n  }\n}"
  '26':
    id: '26'
    nexttasks:
      '#none#':
      - '31'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: a22c2045-33e0-4ad3-8627-15886227f805
      iscommand: false
      name: Enrich internal IP addresses
      type: title
      version: -1
    taskid: a22c2045-33e0-4ad3-8627-15886227f805
    type: title
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1215\n  }\n}"
  '27':
    id: '27'
    nexttasks:
      '#none#':
      - '19'
      - '36'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 1734f24b-0b27-431e-81b6-89997f08894c
      iscommand: false
      name: Enrich external IP addresses
      type: title
      version: -1
    taskid: 1734f24b-0b27-431e-81b6-89997f08894c
    type: title
    view: "{\n  \"position\": {\n    \"x\": 612.5,\n    \"y\": 1215\n  }\n}"
  '28':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.IP
          operator: general.isExists
      label: 'yes'
    id: '28'
    nexttasks:
      '#default#':
      - '24'
      'yes':
      - '33'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      description: Determine whether the playbook's input contains an IP address.
      id: 3030b8e0-e076-4309-81df-e32298eb49a6
      iscommand: false
      name: Do we have IP Addresses?
      type: condition
      version: -1
    taskid: 3030b8e0-e076-4309-81df-e32298eb49a6
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 195\n  }\n}"
  '29':
    id: '29'
    nexttasks:
      '#none#':
      - '32'
      - '15'
    reputationcalc: 0
    scriptarguments:
      ip:
        complex:
          root: inputs.IP
      ipRanges:
        complex:
          root: inputs.InternalRange
    separatecontext: false
    task:
      brand: ''
      description: "Checks if the IP address is in the internal IP address ranges.\n\
        Adds  \"yes\" to the \"InRange\" attribute of the IP address  if it is internal.\
        \ \nAdds \"no\"  to the \"InRange\" attribute of the IP address  if it is\
        \ external. \n"
      id: dfe5b434-e54a-4290-841e-073030e2af53
      iscommand: false
      name: Determine whether the IP address is internal or external
      scriptName: IsIPInRanges
      type: regular
      version: -1
    taskid: dfe5b434-e54a-4290-841e-073030e2af53
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 275,\n    \"y\": 865\n  }\n}"
  '31':
    id: '31'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '24'
    reputationcalc: 0
    scriptarguments:
      Hostname:
        complex:
          accessor: Hostname
          filters:
          - - left:
                iscontext: true
                value:
                  simple: Endpoint.IP
              operator: string.inList
              right:
                iscontext: true
                value:
                  simple: inputs.IP
          root: Endpoint
    separatecontext: true
    task:
      brand: ''
      description: Enrich an Endpoint Hostname using one or more integrations
      id: e39bd0d9-0f03-4dda-8ccd-2e31340c8daa
      iscommand: false
      name: Endpoint Enrichment - Generic
      playbookName: Endpoint Enrichment - Generic
      type: playbook
      version: -1
    taskid: e39bd0d9-0f03-4dda-8ccd-2e31340c8daa
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1360\n  }\n}"
  '32':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Address
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: IP.InRange
                    operator: string.isEqual
                    right:
                      value:
                        simple: 'yes'
                root: IP
          operator: general.isExists
      label: 'yes'
    id: '32'
    nexttasks:
      '#default#':
      - '24'
      'yes':
      - '26'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      description: Checks whether the "InRange" attribute is set to "yes".
      id: a3fc98dc-45c4-4885-8ba1-15249424617f
      iscommand: false
      name: Is there an internal IP address?
      type: condition
      version: -1
    taskid: a3fc98dc-45c4-4885-8ba1-15249424617f
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1040\n  }\n}"
  '33':
    id: '33'
    nexttasks:
      '#none#':
      - '29'
      - '34'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 2ba6b138-2faa-4c41-8b83-8bc40445e02d
      iscommand: false
      name: Enrich IP address
      type: title
      version: -1
    taskid: 2ba6b138-2faa-4c41-8b83-8bc40445e02d
    type: title
    view: "{\n  \"position\": {\n    \"x\": 275,\n    \"y\": 370\n  }\n}"
  '34':
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: inputs.ResolveIP
          operator: string.isEqual
          right:
            value:
              simple: 'True'
      label: 'yes'
    id: '34'
    nexttasks:
      '#default#':
      - '29'
      'yes':
      - '35'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      description: Checks whether the ResolveIP parameter is set to "True".
      id: 3f405f27-26b8-4331-814b-6a5242030dca
      iscommand: false
      name: Resolve the IP address?
      type: condition
      version: -1
    taskid: 3f405f27-26b8-4331-814b-6a5242030dca
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 387.5,\n    \"y\": 515\n  }\n}"
  '35':
    continueonerror: true
    id: '35'
    nexttasks:
      '#none#':
      - '29'
    reputationcalc: 0
    scriptarguments:
      ip:
        complex:
          root: inputs.IP
    separatecontext: false
    task:
      brand: ''
      description: Convert the IP address to a hostname using DNS query.
      id: 4199432a-7b90-4880-8381-61a1f89a5073
      iscommand: false
      name: IP to Hostname (DNS)
      scriptName: IPToHost
      type: regular
      version: -1
    taskid: 4199432a-7b90-4880-8381-61a1f89a5073
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 500,\n    \"y\": 690\n  }\n}"
  '36':
    id: '36'
    nexttasks:
      '#none#':
      - '37'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 97b967b9-1fc6-425f-8204-c363fb8e974c
      iscommand: false
      name: Enrich with Virus Total Private API
      type: title
      version: -1
    taskid: 97b967b9-1fc6-425f-8204-c363fb8e974c
    type: title
    view: "{\n  \"position\": {\n    \"x\": 1032,\n    \"y\": 1375\n  }\n}"
  '37':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: string.isEqual
                    right:
                      value:
                        simple: VirusTotal - Private API
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: string.isEqual
                    right:
                      value:
                        simple: active
                root: modules
          operator: general.isExists
      label: 'yes'
    id: '37'
    nexttasks:
      '#default#':
      - '24'
      'yes':
      - '38'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      description: Checks if there is an active instance of the Virus Total Private
        API enabled.
      id: 2d6d9c62-3d21-423f-80f7-51f57ff3c881
      iscommand: false
      name: Is Virus Total Private API enabled?
      type: condition
      version: -1
    taskid: 2d6d9c62-3d21-423f-80f7-51f57ff3c881
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 1032,\n    \"y\": 1503\n  }\n}"
  '38':
    id: '38'
    nexttasks:
      '#none#':
      - '24'
    reputationcalc: 0
    scriptarguments:
      fullResponse: {}
      ip:
        complex:
          accessor: Address
          root: IP
      threshold: {}
    separatecontext: false
    task:
      brand: VirusTotal - Private API
      description: 'Retrieves a report for a given IP.

        '
      id: fce8e0ad-c5f8-47f0-8668-c9bb83c25c4e
      iscommand: true
      name: Get IP report form Virus Total Private API
      script: VirusTotal - Private API|||vt-private-get-ip-report
      type: regular
      version: -1
    taskid: fce8e0ad-c5f8-47f0-8668-c9bb83c25c4e
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1032,\n    \"y\": 1692\n  }\n}"
tests:
- No test - deprecated. use V2.1 instead.
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1861,\n      \"width\": 1703,\n      \"x\": -291,\n      \"y\"\
  : 49\n    }\n  }\n}"
