description: 'Deprecated: We recommend using extractIndicators command instead.

  Extract indicators from input data.'
fromversion: 3.5.0
id: extract_indicators_-_generic
inputs:
- description: ''
  key: incident
  required: false
  value:
    simple: ${incident}
name: Extract Indicators - Generic
outputs:
- contextPath: File.MD5
  description: Extracted MD5
  type: string
- contextPath: File.SHA1
  description: Extracted SHA1
  type: string
- contextPath: File.SHA256
  description: Extracted SHA256
  type: string
- contextPath: URL.Data
  description: Extracted URLs
  type: string
- contextPath: IP.Address
  description: Extracted IPs
  type: string
- contextPath: Domain.Name
  description: Extracted domains
  type: string
- contextPath: Account.Email.Address
  description: Extracted emails
  type: string
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '2'
      - '3'
      - '4'
      - '6'
      - '7'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: b2850e0d-eaee-4b1d-8e45-b61bd06f6aa9
      iscommand: false
      name: ''
      version: -1
    taskid: b2850e0d-eaee-4b1d-8e45-b61bd06f6aa9
    type: start
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 50\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '5'
    scriptarguments:
      text:
        simple: ${inputs.incident}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: d693465a-260b-4aac-8a18-4a11c047481e
      iscommand: false
      name: Collect Hashes from Incident
      scriptName: ExtractHash
      type: regular
      version: -1
    taskid: d693465a-260b-4aac-8a18-4a11c047481e
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '5'
    scriptarguments:
      text:
        simple: ${inputs.incident}
      urlRegex: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 963c3996-3eaf-457c-8c93-abee20d891e2
      iscommand: false
      name: Collect URLs from Incident
      scriptName: ExtractURL
      type: regular
      version: -1
    taskid: 963c3996-3eaf-457c-8c93-abee20d891e2
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 195\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '5'
    scriptarguments:
      text:
        simple: ${inputs.incident}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 4fe3f22e-7bec-4ed5-841c-9cd5808daf42
      iscommand: false
      name: Collect IPs from Incident
      scriptName: ExtractIP
      type: regular
      version: -1
    taskid: 4fe3f22e-7bec-4ed5-841c-9cd5808daf42
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 195\n  }\n}"
  '5':
    id: '5'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: a3089d6b-fce1-4d82-84d6-ecaaf3a55d10
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: a3089d6b-fce1-4d82-84d6-ecaaf3a55d10
    type: title
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 370\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '5'
    scriptarguments:
      calcReputation:
        simple: 'false'
      markAsIndicator: {}
      text:
        simple: ${inputs.incident}
      tldList: {}
      urlRegex: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: e4a19d6b-98be-49af-8202-fca71cfde7cd
      iscommand: false
      name: Collect Domains from Incident
      scriptName: ExtractDomain
      type: regular
      version: -1
    taskid: e4a19d6b-98be-49af-8202-fca71cfde7cd
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1770,\n    \"y\": 195\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '5'
    scriptarguments:
      text:
        simple: ${inputs.incident}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 16f55051-63fa-467b-8533-163b68f310b5
      iscommand: false
      name: Collect Email Addresses from Incident
      scriptName: ExtractEmail
      type: regular
      version: -1
    taskid: 16f55051-63fa-467b-8533-163b68f310b5
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 195\n  }\n}"
tests:
- No tests - Deprecated
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 385,\n      \"width\": 2100,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
