description: 'Check for duplicate incidents for the current incident, and close it
  if any duplicate has been found by machine-learning  find duplicates automation.


  '
fromversion: 3.5.0
id: dedup_incidents_-_ml
inputs:
- description: Candidate with score above this threshold will close the investigation
    automatically, and mark as duplicate to the current incident.
  key: closeThreshold
  required: true
  value:
    simple: '0.75'
name: DeDup incidents - ML
outputs:
- contextPath: foundDuplicates
  description: found any duplicate incident?
  type: boolean
- contextPath: duplicateCandidate
  description: the duplicate top candidate
  type: unknown
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: d49b7743-f43f-4677-8766-c9f16d3fc0ab
      iscommand: false
      name: ''
      version: -1
    taskid: d49b7743-f43f-4677-8766-c9f16d3fc0ab
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 51\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    results:
    - foundDuplicates
    - duplicateCandidateList
    scriptarguments:
      UseLocalEnvDuplicatesInLastDays: {}
      compareEmailLabels: {}
      compareIncidentTimeDiff: {}
      compareIndicators: {}
      compareOtherLabels: {}
      ignoreClosedIncidents: {}
      ipComparisonSubnetMask: {}
      maxCandidates: {}
      maxNumberOfIncidents: {}
      threshold: {}
      timeFrameDays: {}
    separatecontext: false
    task:
      brand: ''
      description: Find duplicate incidents using machine-learning.
      id: 19915cbc-3042-425d-8254-c3be9c291076
      iscommand: false
      name: Find duplicate incidents
      scriptName: GetDuplicatesMlv2
      type: regular
      version: -1
    taskid: 19915cbc-3042-425d-8254-c3be9c291076
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 196\n  }\n}"
  '2':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: foundDuplicates
          operator: general.isExists
      label: 'yes'
    id: '2'
    nexttasks:
      '#default#':
      - '4'
      'yes':
      - '6'
    scriptarguments:
      left:
        simple: ${foundDuplicates}
      right:
        simple: 'true'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 2ffa4239-003c-490a-849e-f910383a5ae0
      iscommand: false
      name: Is duplicate candidate found?
      type: condition
      version: -1
    taskid: 2ffa4239-003c-490a-849e-f910383a5ae0
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    scriptarguments:
      value:
        simple: Found ${duplicateCandidate.rawId} as duplicate candidate, but didn't
          closed automatically (below threshold)
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 4a8be468-2af6-4427-8ee8-a71d450260ee
      iscommand: false
      name: Print candidate
      scriptName: Print
      type: regular
      version: -1
    taskid: 4a8be468-2af6-4427-8ee8-a71d450260ee
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 720\n  }\n}"
  '4':
    id: '4'
    scriptarguments:
      value:
        simple: No duplicates incidents found
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 91676756-8dd8-41fc-801e-b19c98a5b048
      iscommand: false
      name: No duplicates found
      scriptName: Print
      type: regular
      version: -1
    taskid: 91676756-8dd8-41fc-801e-b19c98a5b048
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '5':
    id: '5'
    scriptarguments:
      duplicateId:
        simple: ${duplicateCandidate.rawId}
      duplicate_id:
        simple: ${duplicateCandidate.Id}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: fd106344-04d3-429b-8fb4-dced0a7a085f
      iscommand: false
      name: Close investigation as duplicate
      scriptName: CloseInvestigationAsDuplicate
      type: regular
      version: -1
    taskid: fd106344-04d3-429b-8fb4-dced0a7a085f
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 720\n  }\n}"
  '6':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: duplicateCandidate.duplicateProbability
          operator: number.greaterThanOrEqual
          right:
            iscontext: true
            value:
              simple: inputs.closeThreshold
      label: 'yes'
    id: '6'
    nexttasks:
      '#default#':
      - '3'
      'yes':
      - '5'
    scriptarguments:
      first:
        simple: ${duplicateCandidate.duplicateProbability}
      second:
        simple: ${inputs.closeThreshold}
    separatecontext: false
    task:
      brand: ''
      description: Check if the candidate for duplicate incident score is above the
        threshold.
      id: 7cc3505f-3571-414c-88bd-a60c8a0e3919
      iscommand: false
      name: Is duplicate score above threshold?
      type: condition
      version: -1
    taskid: 7cc3505f-3571-414c-88bd-a60c8a0e3919
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
tests:
- No Test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 764,\n      \"width\": 1025,\n      \"x\": 50,\n      \"y\": 51\n\
  \    }\n  }\n}"
