description: Generic playbook to collect data from endpoints for IR purposes. Will
  use whichever integrations are configured and available.
fromversion: ''
id: Endpoint data collection
inputs:
- description: ''
  key: UseD2
  required: false
  value:
    simple: 'False'
- description: ''
  key: Hostname
  required: false
  value: {}
name: Endpoint data collection
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 5c790e9c-edcd-4ad9-8a35-05451eb582df
      iscommand: false
      name: ''
      version: -1
    taskid: 5c790e9c-edcd-4ad9-8a35-05451eb582df
    type: start
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#default#':
      - '3'
      'yes':
      - '2'
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        simple: ${inputs.UseD2}
      right:
        simple: 'True'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: b2c6a043-bedf-40e9-8b34-064891fa6597
      iscommand: false
      name: Use D2 agent?
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: b2c6a043-bedf-40e9-8b34-064891fa6597
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      Hostname:
        simple: ${inputs.Hostname}
    separatecontext: true
    task:
      brand: ''
      description: ''
      id: e70f5c75-4cb1-430c-8660-b01ad288ddec
      iscommand: false
      name: MAR - Endpoint data collection
      playbookName: MAR - Endpoint data collection
      type: playbook
      version: -1
    taskid: 3359e593-8218-4132-8a69-d48fc9aa78a7
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 515\n  }\n}"
  '11':
    id: '11'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      Hostname:
        simple: ${inputs.Hostname}
    separatecontext: true
    task:
      brand: ''
      description: ''
      id: 121a30fb-c5ea-41d3-86db-e9753c08ada7
      iscommand: false
      name: Sentinel One - Endpoint data collection
      playbookName: Sentinel One - Endpoint data collection
      type: playbook
      version: -1
    taskid: 121a30fb-c5ea-41d3-86db-e9753c08ada7
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 960,\n    \"y\": 515\n  }\n}"
  '2':
    id: '2'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '8'
    scriptarguments:
      Credentials:
        simple: Admin
      Host:
        simple: ${inputs.Hostname}
      OS:
        simple: windows
      Path: {}
    separatecontext: false
    task:
      brand: ''
      description: 'Uses Demisto''s d2 agent to collect data from an endpoint for
        IR purposes.


        Input:

        * Hostname (default: ${Endpoint.Hostname})

        * OS (default: windows)

        * Credentials (default: Admin)

        * Path (default: None)'
      id: 8c9dec86-a668-4e3e-8824-075fe18330ac
      iscommand: false
      name: D2 - Endpoint data collection
      playbookName: D2 - Endpoint data collection
      type: playbook
      version: -1
    taskid: 8c9dec86-a668-4e3e-8824-075fe18330ac
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 515\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '10'
      - '11'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: dbfc8aa8-e3e8-4b03-8a20-2dc0edf62cae
      iscommand: false
      name: EDR products
      type: title
      version: -1
    taskid: dbfc8aa8-e3e8-4b03-8a20-2dc0edf62cae
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 370\n  }\n}"
  '8':
    id: '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: a726afff-a81d-4588-865c-f8085a6f41c2
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: a726afff-a81d-4588-865c-f8085a6f41c2
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 690\n  }\n}"
tests:
- No tests - Need to add
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 705,\n      \"width\": 1290,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
