description: DEPRECATED. Use the Hunt File Hash playbook instead. Playbook to quickly
  react to discovery of new IOCs. Receive a list of IOCs as attached text / csv files,
  extract IOCs using regular expressions and hunt rapidly across the infrastructure
  using various integrations. Also supports attaching multiple files.
fromversion: 2.5.0
id: playbook10
inputs: []
name: Rapid IOC Hunting Playbook
outputs: []
starttaskid: '0'
system: true
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: bba2ed1f-ba17-4fcc-81b3-990115ff1608
      iscommand: false
      name: start_task
      type: start
      version: -1
    taskid: bba2ed1f-ba17-4fcc-81b3-990115ff1608
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 1125,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
      - '38'
      - '39'
      - '47'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: a815b6ec-64bf-4a15-8314-5055c5d6d89d
      iscommand: false
      name: Set up the investigation and acquire IOCs
      type: title
      version: -1
    taskid: a815b6ec-64bf-4a15-8314-5055c5d6d89d
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 1125,\n    \"y\": 195\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '6'
      'yes':
      - '41'
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${File.EntryID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 7e822405-36be-4341-857e-bcc4e6b98402
      iscommand: false
      name: Need to Load data from attached text files?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 7e822405-36be-4341-857e-bcc4e6b98402
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 152.5,\n    \"y\": 340\n  }\n}"
  '38':
    id: '38'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      extend-context: {}
      text:
        simple: ${incident}
      value:
        simple: ${File.Extension(val.indexOf('csv')>=0)}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 37fc767e-b23c-463a-84da-40a94e6b1b6a
      iscommand: false
      name: Collect Hashes from incident
      scriptName: ExtractHash
      type: regular
      version: -1
    taskid: 37fc767e-b23c-463a-84da-40a94e6b1b6a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 690\n  }\n}"
  '39':
    id: '39'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      extend-context: {}
      text:
        simple: ${incident}
      value:
        simple: ${File.Extension(val.indexOf('csv')>=0)}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 7845e26f-f375-4a41-8720-0d186a052382
      iscommand: false
      name: Collect IPs from incident
      scriptName: ExtractIP
      type: regular
      version: -1
    taskid: 7845e26f-f375-4a41-8720-0d186a052382
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 690\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      text:
        simple: ${FileData}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: ef989693-4e8e-472e-84bf-bf6566ef1851
      iscommand: false
      name: Extract hashes from text file
      scriptName: ExtractHash
      type: regular
      version: -1
    taskid: ef989693-4e8e-472e-84bf-bf6566ef1851
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 690\n  }\n}"
  '41':
    id: '41'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 5e13d196-7f69-48e0-88d8-e9347d2b0567
      iscommand: false
      name: Load contents of attached textual files
      scriptName: ReadFile
      type: regular
      version: -1
    taskid: 5e13d196-7f69-48e0-88d8-e9347d2b0567
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 515\n  }\n}"
  '47':
    id: '47'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      extend-context: {}
      text:
        simple: ${incident}
      value:
        simple: ${File.Extension(val.indexOf('csv')>=0)}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 41007d8b-b092-4c62-8bb4-9176b3b8ad62
      iscommand: false
      name: Collect URLs from incident
      scriptName: ExtractURL
      type: regular
      version: -1
    taskid: 41007d8b-b092-4c62-8bb4-9176b3b8ad62
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1770,\n    \"y\": 690\n  }\n}"
  '48':
    id: '48'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Happy hunting!
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 80ca226e-af97-4a74-818b-5cbc2f74e7e5
      iscommand: false
      name: Analyst work - hunt manually
      scriptName: Print
      type: regular
      version: -1
    taskid: 80ca226e-af97-4a74-818b-5cbc2f74e7e5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 1185\n  }\n}"
  '49':
    id: '49'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '48'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 235f1662-0f0d-45fa-8e3f-18ee2419e1c1
      iscommand: false
      name: ''
      playbookName: Hunt for bad IOCs
      type: playbook
      version: -1
    taskid: 235f1662-0f0d-45fa-8e3f-18ee2419e1c1
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 1010\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      text:
        simple: ${FileData}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 43ddbd9e-84f5-42c1-8398-e94851c85cff
      iscommand: false
      name: Extract IP address from text file
      scriptName: ExtractIP
      type: regular
      version: -1
    taskid: 43ddbd9e-84f5-42c1-8398-e94851c85cff
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 690\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '49'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: c105e3b1-8e9a-40cd-8249-5337e8417b06
      iscommand: false
      name: Hunt
      type: title
      version: -1
    taskid: c105e3b1-8e9a-40cd-8249-5337e8417b06
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 865\n  }\n}"
tests:
- No test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"3_41_yes\": 0.55,\n    \"3_6_#default#\"\
  : 0.31\n  },\n  \"paper\": {\n    \"dimensions\": {\n      \"height\": 1230,\n \
  \     \"width\": 2100,\n      \"x\": 50,\n      \"y\": 50\n    }\n  }\n}"
