description: 'Calculates and assign the incident severity based on the highest returned
  severity level from the following severity calculations:


  * Indicators DBotScore - Calculates the incident severity level according to the
  highest indicator DBotScore.

  * Critical assets - Determines if a critical assest is associated with the invesigation.

  * 3rd-party integrations - Calculates the incident severity level according to the
  methodology of a 3rd-party integration.


  NOTE: the new severity level overwrites the previous severity level even if the
  previous severity level was more severe.'
fromversion: 3.6.0
id: Calculate Severity - Generic
inputs:
- description: Qualys Vulnerability Severity score (1-5)
  key: QualysSeverity
  required: false
  value:
    complex:
      accessor: Severity
      root: Qualys
- description: 'Array of all indicators associated with the incident. '
  key: DBotScore
  required: false
  value:
    complex:
      root: DBotScore
- description: A Endpoint to check against the critical lists.
  key: Endpoint
  required: false
  value:
    complex:
      root: Endpoint
- description: A User account to check against the critical lists.
  key: Account
  required: false
  value:
    complex:
      root: Account
- description: Nexpose Vulnerability Severity score (Moderate, Severe, Critical)
  key: NexposeSeverity
  required: false
  value:
    complex:
      accessor: Asset.Vulnerability.Severity
      root: Nexpose
name: Calculate Severity - Generic
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '14'
      - '13'
      - '16'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 3eded69b-617e-4212-86b7-2537474285f3
      iscommand: false
      name: ''
      version: -1
    taskid: 3eded69b-617e-4212-86b7-2537474285f3
    type: start
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 50\n  }\n}"
  '10':
    id: '10'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 483350d5-ab17-44cd-87b3-0e2360ce3577
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 483350d5-ab17-44cd-87b3-0e2360ce3577
    type: title
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 720\n  }\n}"
  '11':
    id: '11'
    nexttasks:
      '#none#':
      - '10'
    reputationcalc: 0
    scriptarguments:
      addLabels: {}
      arcsightcaseid: {}
      assetid: {}
      attachmentcount: {}
      attachmentextension: {}
      attachmenthash: {}
      attachmentid: {}
      attachmentitem: {}
      attachmentname: {}
      attachmentsize: {}
      attachmenttype: {}
      backupowner: {}
      blah: {}
      booltest: {}
      bugtraq: {}
      customFields: {}
      cve: {}
      cvss: {}
      daysbetweenreportcreation: {}
      details: {}
      emailbcc: {}
      emailbody: {}
      emailbodyformat: {}
      emailbodyhtml: {}
      emailcc: {}
      emailclientname: {}
      emailfrom: {}
      emailkeywords: {}
      emailmessageid: {}
      emailreceived: {}
      emailreplyto: {}
      emailreturnpath: {}
      emailsenderip: {}
      emailsize: {}
      emailsource: {}
      emailsubject: {}
      emailto: {}
      emailtocount: {}
      emailurlclicked: {}
      eventid: {}
      falses: {}
      fetchid: {}
      fetchtype: {}
      id: {}
      important: {}
      importantfield: {}
      labels: {}
      mdtest: {}
      myfield: {}
      name: {}
      occurred: {}
      owner: {}
      phase: {}
      replacePlaybook: {}
      reporteduser: {}
      roles: {}
      screenshot: {}
      screenshot2: {}
      selector: {}
      severity:
        simple: critical
      signature: {}
      single: {}
      single2: {}
      sla: {}
      source: {}
      systems: {}
      team: {}
      test: {}
      test2: {}
      testfield: {}
      timeassignedtolevel2: {}
      timefield1: {}
      timelevel1: {}
      type: {}
      username: {}
      vendorid: {}
      vulnerabilitycategory: {}
    separatecontext: false
    task:
      brand: Builtin
      description: Assign the incident severity level  to "Critical".
      id: d932e9f2-4ac2-4b27-8f83-8b0c71c398e1
      iscommand: true
      name: Assign the incident severity level  to "Critical"
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: d932e9f2-4ac2-4b27-8f83-8b0c71c398e1
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 292,\n    \"y\": 545\n  }\n}"
  '13':
    id: '13'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '15'
    reputationcalc: 0
    scriptarguments:
      Account:
        complex:
          root: inputs.Account
      CriticalEndpoints: {}
      CriticalGroups: {}
      CriticalUsers: {}
      Endpoint:
        complex:
          root: inputs.Endpoint
    separatecontext: true
    task:
      brand: ''
      description: 'Determines if a critical assest is associated with the invesigation.
        The playbook returns a severity level of "Critical" if a critical asset is
        associated with the investigation.


        This playbook verifies if a User Account or an Endpoint is part of a critical
        list or a critical AD group. '
      id: 1850d92e-938e-4f29-827a-ff8dd4d1da40
      iscommand: false
      name: Calculate Severity - Critical assets
      playbookName: Calculate Severity - Critical assets
      type: playbook
      version: -1
    taskid: 1850d92e-938e-4f29-827a-ff8dd4d1da40
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 807.5,\n    \"y\": 195\n  }\n}"
  '14':
    id: '14'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '15'
    reputationcalc: 0
    scriptarguments:
      DBotScore:
        complex:
          root: inputs.DBotScore
    separatecontext: true
    task:
      brand: ''
      description: 'Calculate incident severity by indicators reputation and user/endpoint
        membership in critical groups.


        Note - current severity will be overwritten and new severity may be lower
        than the current one.


        Playbook inputs:

        * CriticalUsers - Comma separated array with usernames of critical users

        * CriticalEndpoints - Comma separated array with hostnames of critical endpoints

        * CriticalGroups - Comma separated array with DN of critical Active Directory
        groups

        * QualysSeverity - A Qualys severity score (1-5) to calculate severity from'
      id: 09ef8f5b-0c54-4f0d-8d15-44daa61c60d5
      iscommand: false
      name: Calculate Severity - DBotScore
      playbookName: Calculate Severity - Indicators DBotScore
      type: playbook
      version: -1
    taskid: 09ef8f5b-0c54-4f0d-8d15-44daa61c60d5
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 377.5,\n    \"y\": 195\n  }\n}"
  '15':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: Severity
                    operator: string.isEqual
                    right:
                      value:
                        simple: critical
                root: Severity
          operator: general.isExists
      label: Critical
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: Severity
                    operator: string.isEqual
                    right:
                      value:
                        simple: high
                root: Severity
          operator: general.isExists
      label: High
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: Severity
                    operator: string.isEqual
                    right:
                      value:
                        simple: medium
                root: Severity
          operator: general.isExists
      label: Medium
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: Severity
                    operator: string.isEqual
                    right:
                      value:
                        simple: low
                root: Severity
          operator: general.isExists
      label: Low
    id: '15'
    nexttasks:
      '#default#':
      - '10'
      Critical:
      - '11'
      High:
      - '6'
      Low:
      - '4'
      Medium:
      - '5'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      description: Determines the severity level based on the highest result of all
        severity calculations.
      id: 9cb71dfd-3f18-403f-8351-c370d5a58987
      iscommand: false
      name: Set severity based on the highest returned severity level
      type: condition
      version: -1
    taskid: 9cb71dfd-3f18-403f-8351-c370d5a58987
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 370\n  }\n}"
  '16':
    id: '16'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '15'
    reputationcalc: 0
    scriptarguments:
      NexposeSeverity:
        complex:
          root: inputs.NexposeSeverity
      QualysSeverity:
        complex:
          root: inputs.QualysSeverity
    separatecontext: true
    task:
      brand: ''
      description: Calculates the incident severity level according to the methodology
        of a 3rd-party integration.
      id: e628aa74-143a-4068-8a75-3abd96479000
      iscommand: false
      name: Calculate Severity - 3rd-party integrations
      playbookName: Calculate Severity - 3rd-party integrations
      type: playbook
      version: -1
    taskid: e628aa74-143a-4068-8a75-3abd96479000
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 1258.5,\n    \"y\": 195\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '10'
    reputationcalc: 0
    scriptarguments:
      addLabels: {}
      arcsightcaseid: {}
      assetid: {}
      attachmentcount: {}
      attachmentextension: {}
      attachmenthash: {}
      attachmentid: {}
      attachmentitem: {}
      attachmentname: {}
      attachmentsize: {}
      attachmenttype: {}
      backupowner: {}
      blah: {}
      booltest: {}
      bugtraq: {}
      customFields: {}
      cve: {}
      cvss: {}
      daysbetweenreportcreation: {}
      details: {}
      emailbcc: {}
      emailbody: {}
      emailbodyformat: {}
      emailbodyhtml: {}
      emailcc: {}
      emailclientname: {}
      emailfrom: {}
      emailkeywords: {}
      emailmessageid: {}
      emailreceived: {}
      emailreplyto: {}
      emailreturnpath: {}
      emailsenderip: {}
      emailsize: {}
      emailsource: {}
      emailsubject: {}
      emailto: {}
      emailtocount: {}
      emailurlclicked: {}
      eventid: {}
      falses: {}
      fetchid: {}
      fetchtype: {}
      id: {}
      important: {}
      importantfield: {}
      killchain: {}
      labels: {}
      lob: {}
      mdtest: {}
      myfield: {}
      name: {}
      occurred: {}
      owner: {}
      phase: {}
      queues: {}
      replacePlaybook: {}
      reporteduser: {}
      roles: {}
      screenshot: {}
      screenshot2: {}
      selector: {}
      severity:
        simple: low
      signature: {}
      single: {}
      single2: {}
      sla: {}
      source: {}
      systems: {}
      team: {}
      test: {}
      test2: {}
      testfield: {}
      timeassignedtolevel2: {}
      timefield1: {}
      timelevel1: {}
      type: {}
      username: {}
      vendorid: {}
      vulnerabilitycategory: {}
    separatecontext: false
    task:
      brand: Builtin
      description: Assign the incident severity level  to "Low".
      id: faa9ae4a-e658-4ab7-8d99-07994fba39a1
      iscommand: true
      name: Assign the incident severity level  to "Low"
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: faa9ae4a-e658-4ab7-8d99-07994fba39a1
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1535,\n    \"y\": 545\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '10'
    reputationcalc: 0
    scriptarguments:
      addLabels: {}
      arcsightcaseid: {}
      assetid: {}
      attachmentcount: {}
      attachmentextension: {}
      attachmenthash: {}
      attachmentid: {}
      attachmentitem: {}
      attachmentname: {}
      attachmentsize: {}
      attachmenttype: {}
      backupowner: {}
      blah: {}
      booltest: {}
      bugtraq: {}
      customFields: {}
      cve: {}
      cvss: {}
      daysbetweenreportcreation: {}
      details: {}
      emailbcc: {}
      emailbody: {}
      emailbodyformat: {}
      emailbodyhtml: {}
      emailcc: {}
      emailclientname: {}
      emailfrom: {}
      emailkeywords: {}
      emailmessageid: {}
      emailreceived: {}
      emailreplyto: {}
      emailreturnpath: {}
      emailsenderip: {}
      emailsize: {}
      emailsource: {}
      emailsubject: {}
      emailto: {}
      emailtocount: {}
      emailurlclicked: {}
      eventid: {}
      falses: {}
      fetchid: {}
      fetchtype: {}
      id: {}
      important: {}
      importantfield: {}
      killchain: {}
      labels: {}
      lob: {}
      mdtest: {}
      myfield: {}
      name: {}
      occurred: {}
      owner: {}
      phase: {}
      queues: {}
      replacePlaybook: {}
      reporteduser: {}
      roles: {}
      screenshot: {}
      screenshot2: {}
      selector: {}
      severity:
        simple: medium
      signature: {}
      single: {}
      single2: {}
      sla: {}
      source: {}
      systems: {}
      team: {}
      test: {}
      test2: {}
      testfield: {}
      timeassignedtolevel2: {}
      timefield1: {}
      timelevel1: {}
      type: {}
      username: {}
      vendorid: {}
      vulnerabilitycategory: {}
    separatecontext: false
    task:
      brand: Builtin
      description: Assign the incident severity level  to "Medium".
      id: 7d9b6b23-3401-47f9-843d-cfa2a9679ef7
      iscommand: true
      name: Assign the incident severity level  to "Medium"
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 7d9b6b23-3401-47f9-843d-cfa2a9679ef7
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1116,\n    \"y\": 545\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '10'
    reputationcalc: 0
    scriptarguments:
      addLabels: {}
      arcsightcaseid: {}
      assetid: {}
      attachmentcount: {}
      attachmentextension: {}
      attachmenthash: {}
      attachmentid: {}
      attachmentitem: {}
      attachmentname: {}
      attachmentsize: {}
      attachmenttype: {}
      backupowner: {}
      blah: {}
      booltest: {}
      bugtraq: {}
      customFields: {}
      cve: {}
      cvss: {}
      daysbetweenreportcreation: {}
      details: {}
      emailbcc: {}
      emailbody: {}
      emailbodyformat: {}
      emailbodyhtml: {}
      emailcc: {}
      emailclientname: {}
      emailfrom: {}
      emailkeywords: {}
      emailmessageid: {}
      emailreceived: {}
      emailreplyto: {}
      emailreturnpath: {}
      emailsenderip: {}
      emailsize: {}
      emailsource: {}
      emailsubject: {}
      emailto: {}
      emailtocount: {}
      emailurlclicked: {}
      eventid: {}
      falses: {}
      fetchid: {}
      fetchtype: {}
      id: {}
      important: {}
      importantfield: {}
      killchain: {}
      labels: {}
      lob: {}
      mdtest: {}
      myfield: {}
      name: {}
      occurred: {}
      owner: {}
      phase: {}
      queues: {}
      replacePlaybook: {}
      reporteduser: {}
      roles: {}
      screenshot: {}
      screenshot2: {}
      selector: {}
      severity:
        simple: high
      signature: {}
      single: {}
      single2: {}
      sla: {}
      source: {}
      systems: {}
      team: {}
      test: {}
      test2: {}
      testfield: {}
      timeassignedtolevel2: {}
      timefield1: {}
      timelevel1: {}
      type: {}
      username: {}
      vendorid: {}
      vulnerabilitycategory: {}
    separatecontext: false
    task:
      brand: Builtin
      description: Assign the incident severity level  to "High".
      id: 26d70778-7064-49a2-880b-e167ae80b3ab
      iscommand: true
      name: Assign the incident severity level  to "High"
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 26d70778-7064-49a2-880b-e167ae80b3ab
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 703,\n    \"y\": 545\n  }\n}"
tests:
- no test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 735,\n      \"width\": 1623,\n      \"x\": 292,\n      \"y\":\
  \ 50\n    }\n  }\n}"
