description: Deprecated - We recommend using Account Enrichment - Generic playbook
  instead. Enrich the accounts under the Account context key with details from relevant
  integrations such as AD.
fromversion: 3.5.0
id: Account Enrichment
inputs: []
name: Account Enrichment
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 065b25dc-7aad-4356-8bee-261b189251b3
      iscommand: false
      name: ''
      version: -1
    taskid: 065b25dc-7aad-4356-8bee-261b189251b3
    type: start
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#default#':
      - '3'
      'yes':
      - '2'
    note: false
    scriptarguments:
      value:
        simple: ${modules.brand(val === 'activedir')}
    separatecontext: false
    task:
      brand: ''
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: be4d8a4d-14b5-4541-8d40-1df25ef145c6
      iscommand: false
      name: Is AD configured?
      scriptName: Exists
      type: condition
      version: -1
    taskid: be4d8a4d-14b5-4541-8d40-1df25ef145c6
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      attributes: {}
      customFieldData:
        simple: ${Account.Email.Address}
      customFieldType:
        simple: mail
      dn: {}
      email: {}
      headers: {}
      limit: {}
      name: {}
      nestedSearch: {}
      userAccountControlOut: {}
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: "Query \u201CActive Directory\u201D for the email address info"
      id: c7455a4b-be90-45c3-83be-a290e2660432
      iscommand: false
      name: Query AD to get user details
      scriptName: ADGetUser
      type: regular
      version: -1
    taskid: c7455a4b-be90-45c3-83be-a290e2660432
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 561f7e3c-e8cf-4f68-8bbe-64c7cb608995
      iscommand: false
      name: User Enrichment Done
      type: title
      version: -1
    taskid: 561f7e3c-e8cf-4f68-8bbe-64c7cb608995
    type: title
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 720\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#default#':
      - '3'
      'yes':
      - '1'
    note: false
    scriptarguments:
      value:
        simple: ${Account.Email.Address}
    separatecontext: false
    task:
      brand: ''
      description: Check if there is an Email address.
      id: 7e9ec3ab-29e0-458a-8a61-7ca559f4b428
      iscommand: false
      name: Check if there is an Email address
      scriptName: Exists
      type: condition
      version: -1
    taskid: 7e9ec3ab-29e0-458a-8a61-7ca559f4b428
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 195\n  }\n}"
tests:
- No tests - Deprecated playbook
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 735,\n      \"width\": 492.5,\n      \"x\": 50,\n      \"y\":\
  \ 50\n    }\n  }\n}"
