description: Triggers a backup task on each firewall appliance and pulls the resulting
  file into the war room via SCP.
fromversion: 2.5.0
id: playbook14
inputs: []
name: Checkpoint Firewall Configuration Backup Playbook
outputs: []
starttaskid: '0'
system: true
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 1048472f-83e3-4b55-8d84-8e9fafbbd6cf
      iscommand: false
      name: start_task
      type: start
      version: -1
    taskid: 1048472f-83e3-4b55-8d84-8e9fafbbd6cf
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: chkpdevicestobackup
      value: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 230eed7b-c702-4c0f-87f0-700bd9d630b1
      iscommand: false
      name: Determine list of devices to be backed up
      type: regular
      version: -1
    taskid: 230eed7b-c702-4c0f-87f0-700bd9d630b1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    results:
    - CheckpointBackup
    scriptarguments:
      devices:
        simple: ${chkpdevicestobackup}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 6eb6a468-79cc-460b-8e2c-cada1799b034
      iscommand: false
      name: Trigger backup on each device
      scriptName: CPCreateBackup
      type: regular
      version: -1
    taskid: 6eb6a468-79cc-460b-8e2c-cada1799b034
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quietmode: 0
    results:
    - CheckpointBackup
    scriptarguments:
      devices:
        simple: ${chkpbackupstarted}
      waittimeout:
        simple: '5'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 143e5bcf-7746-409b-8c53-ff761a2d4b99
      iscommand: false
      name: Show status for initiated backup tasks
      scriptName: CPShowBackupStatus
      type: regular
      version: -1
    taskid: 143e5bcf-7746-409b-8c53-ff761a2d4b99
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '6'
      'yes':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      data:
        simple: ${devicesbackuperror}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 1e1e3c6f-5703-47ea-8d70-871327266a2b
      iscommand: false
      name: Have any backups failed?
      scriptName: UtilAnyResults
      type: condition
      version: -1
    taskid: 1e1e3c6f-5703-47ea-8d70-871327266a2b
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      assignmentgroup: {}
      category: {}
      comments:
        simple: ${devicesbackuperror}
      shortdescription:
        simple: Checkpoint configuration backups - Failed
      subcategory: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 3fb51d97-0e06-4b4d-8d3d-44a10e657cc4
      iscommand: false
      name: Open ticket on ServiceNow with list of problematic devices
      scriptName: SNOpenTicket
      type: regular
      version: -1
    taskid: 3fb51d97-0e06-4b4d-8d3d-44a10e657cc4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 293,\n    \"y\": 903\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    quietmode: 0
    scriptarguments:
      systems2files:
        simple: ${devicesbackupfiles}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 36723772-43f0-4619-872f-f54d53770054
      iscommand: false
      name: Retrieve the backup files from the devices
      scriptName: SCPPullFiles
      type: regular
      version: -1
    taskid: 36723772-43f0-4619-872f-f54d53770054
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 80,\n    \"y\": 1097\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      attachIDs: {}
      bcc: {}
      body:
        simple: ${backupsreporttext}
      cc: {}
      htmlBody: {}
      subject:
        simple: Demisto - Checkpoint Backup Report
      to: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: d187c4cc-630c-4edd-8048-40678669101b
      iscommand: false
      name: Email a report of backup results
      scriptName: SendEmail
      type: regular
      version: -1
    taskid: d187c4cc-630c-4edd-8048-40678669101b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 80,\n    \"y\": 1291\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      notes: {}
      reason:
        simple: Done
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 65e21959-2a73-48ab-8b31-0aa8b55e66d9
      iscommand: false
      name: CloseInvestigation
      scriptName: CloseInvestigation
      type: regular
      version: -1
    taskid: 65e21959-2a73-48ab-8b31-0aa8b55e66d9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 80,\n    \"y\": 1485\n  }\n}"
tests:
- No test - old playbook
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1530,\n      \"width\": 623,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
