description: Deprecated - We recommend using Process Email - Generic playbook instead.
  Add email details into the relevant context entities and handle the case where you
  have attached original emails.
fromversion: 2.5.0
id: Process Email
inputs: []
name: Process Email
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: ccd00127-175c-4a93-8edb-14e71f7d47ea
      iscommand: false
      name: ''
      version: -1
    taskid: ccd00127-175c-4a93-8edb-14e71f7d47ea
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      'no':
      - '2'
      'yes':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${File(val.Type.toLowerCase().indexOf('composite document file v2
          document') >= 0 || val.Type.toLowerCase().indexOf('rfc 822 mail') >= 0 ||
          val.Extension == 'eml' && val.Type.toLowerCase().indexOf('ascii') >= 0 &&
          val.Type.toLowerCase().indexOf('crlf') >= 0).EntryID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Check if we have any attachments with relevant attachment types
        like eml or rfc822
      id: 0a3b6760-ffc7-4a5f-8042-47e9a15402ee
      iscommand: false
      name: Do we have original emails attached?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 0a3b6760-ffc7-4a5f-8042-47e9a15402ee
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Email
      value:
        simple: '${incident.labels={To: val[''Email''], CC: val[''Email/cc''], From:
          val[''Email/from''], Subject: val[''Email/subject''], Text: val[''Email/text''],
          HTML: val[''Email/html''], Headers: val[''Email/headers''], Format: val[''Email/format'']}}'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 3ad45b93-5373-4303-8a74-fcaeba4c3344
      iscommand: false
      name: Add original email details to context
      scriptName: Set
      type: regular
      version: -1
    taskid: 3ad45b93-5373-4303-8a74-fcaeba4c3344
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    note: false
    quietmode: 0
    results:
    - AttachmentName
    scriptarguments:
      entryid:
        simple: ${File(val.Type.toLowerCase().indexOf('composite document file v2
          document') >= 0 || val.Type.toLowerCase().indexOf('rfc 822 mail') >= 0 ||
          val.Extension == 'eml' && val.Type.toLowerCase().indexOf('ascii') >= 0 &&
          val.Type.toLowerCase().indexOf('crlf') >= 0).EntryID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: b7f50774-0497-4821-8910-02df73f2c91d
      iscommand: false
      name: Add original email attachments to context
      scriptName: ParseEmailFiles
      type: regular
      version: -1
    taskid: b7f50774-0497-4821-8910-02df73f2c91d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
tests:
- No tests - Deprecated playbook
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 415,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
