description: Investigate a malware using one or more integrations
fromversion: 3.6.0
id: malware_investigation-_generic
inputs:
- description: Set to true to assign only user that is currently on shift. Requires
    Cortex XSOAR v5.5 or later.
  key: OnCall
  required: false
  value:
    simple: false
name: Malware Investigation - Generic
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '4'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 6839ec7c-e614-4f3e-8eaf-17d155c840c2
      iscommand: false
      name: ''
      version: -1
    taskid: 6839ec7c-e614-4f3e-8eaf-17d155c840c2
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '17':
    id: '17'
    nexttasks:
      '#none#':
      - '31'
    scriptarguments:
      assignBy:
        simple: random
      email: {}
      onCall:
        complex:
          root: inputs.OnCall
      roles: {}
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: c3be8540-6c7f-440a-84c0-474f62764780
      iscommand: false
      name: Choose analyst
      scriptName: AssignAnalystToIncident
      type: regular
      version: -1
    taskid: c3be8540-6c7f-440a-84c0-474f62764780
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1010\n  }\n}"
  '30':
    id: '30'
    nexttasks:
      '#none#':
      - '47'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 27128b5c-e619-43d8-8913-baa519a3bd1a
      iscommand: false
      name: Handover to human analyst
      type: title
      version: -1
    taskid: 27128b5c-e619-43d8-8913-baa519a3bd1a
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 690\n  }\n}"
  '31':
    id: '31'
    nexttasks:
      '#none#':
      - '32'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 46f2f85d-5b7a-461c-84c8-926591fd866b
      iscommand: false
      name: Manually review the incident
      type: regular
      version: -1
    taskid: 46f2f85d-5b7a-461c-84c8-926591fd866b
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1185\n  }\n}"
  '32':
    id: '32'
    scriptarguments:
      notes: {}
      reason: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 7bb473b8-90de-490e-8adb-e19dcb67794d
      iscommand: false
      name: Close Investigation
      scriptName: CloseInvestigation
      type: regular
      version: -1
    taskid: 7bb473b8-90de-490e-8adb-e19dcb67794d
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1360\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '43'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 2d951f6e-18e3-4618-8546-9bacc2ebac5e
      iscommand: false
      name: Setup
      type: title
      version: -1
    taskid: 2d951f6e-18e3-4618-8546-9bacc2ebac5e
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '43':
    id: '43'
    nexttasks:
      '#none#':
      - '45'
      - '46'
    separatecontext: true
    task:
      brand: ''
      description: ''
      id: 160ae532-83b9-4b75-83b4-074a4da7a886
      iscommand: false
      name: Malware Investigation - Generic - Setup
      playbookName: Malware Investigation - Generic - Setup
      type: playbook
      version: -1
    taskid: 160ae532-83b9-4b75-83b4-074a4da7a886
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 340\n  }\n}"
  '45':
    id: '45'
    nexttasks:
      '#none#':
      - '30'
    separatecontext: true
    task:
      brand: ''
      description: ''
      id: 6dcf0e54-5c0c-4734-83a3-d15f83cb5360
      iscommand: false
      name: Entity Enrichment - Generic
      playbookName: Entity Enrichment - Generic
      type: playbook
      version: -1
    taskid: 6dcf0e54-5c0c-4734-83a3-d15f83cb5360
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 515\n  }\n}"
  '46':
    id: '46'
    nexttasks:
      '#none#':
      - '30'
    separatecontext: true
    task:
      brand: ''
      description: ''
      id: 0f80017f-66cd-410d-87b0-04cc9e3fbb74
      iscommand: false
      name: Detonate File - Generic
      playbookName: Detonate File - Generic
      type: playbook
      version: -1
    taskid: 0f80017f-66cd-410d-87b0-04cc9e3fbb74
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 515\n  }\n}"
  '47':
    id: '47'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '17'
    scriptarguments:
      CriticalEndpoints: {}
      CriticalGroups: {}
      CriticalUsers: {}
    separatecontext: false
    task:
      brand: ''
      description: 'Calculate incident severity by indicators reputation and user/endpoint
        membership in critical groups.


        Note - current severity will be overwritten and new severity may be lower
        than the current one.


        Playbook inputs:

        * CriticalUsers - Comma separated array with usernames of critical users

        * CriticalEndpoints - Comma separated array with hostnames of critical endpoints

        * CriticalGroups - Comma separated array with DN of critical Active Directory
        groups'
      id: 07dc310c-c368-4c96-878a-71a98af2c8f1
      iscommand: false
      name: Calculate Severity - Generic
      playbookName: Calculate Severity - Generic
      type: playbook
      version: -1
    taskid: 07dc310c-c368-4c96-878a-71a98af2c8f1
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 835\n  }\n}"
tests:
- No test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1405,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
