description: 'Extracts indicators from a file.

  Supported file types:

  - PDF

  - TXT

  - HTM, HTML

  - DOC, DOCX'
fromversion: 4.1.0
id: extract_indicators_from_file_-_generic
inputs:
- description: The file to extract indicators from.
  key: File
  required: false
  value:
    complex:
      root: File
name: Extract Indicators From File - Generic
outputs:
- contextPath: Domain.Name
  description: Extracted domains
- contextPath: Account.Email.Address
  description: Extracted emails
- contextPath: File.MD5
  description: Extracted MD5
- contextPath: File.SHA1
  description: Extracted SHA1
- contextPath: File.SHA256
  description: Extracted SHA256
- contextPath: IP.Address
  description: Extracted IPs
- contextPath: File.Text
  description: The PDF File extracted text
- contextPath: File.Producer
  description: The PDF File producer
- contextPath: File.Title
  description: The PDF File Title
- contextPath: File.xap
  description: The PDF File xap
- contextPath: File.Author
  description: The PDF File Author
- contextPath: File.dc
  description: The PDF File dc
- contextPath: File.xapmm
  description: The PDF File xapmm
- contextPath: File.ModDate
  description: The PDF File ModDate
- contextPath: File.CreationDate
  description: The PDF File CreationDate
- contextPath: File.Pages
  description: Number of pages in PDF file
- contextPath: URL.Data
  description: List of URLs that were extracted from the PDF file
  type: unknown
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 7c475fe8-ef6f-4203-8649-88c8ee1355a4
      iscommand: false
      name: ''
      version: -1
    taskid: 7c475fe8-ef6f-4203-8649-88c8ee1355a4
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": -20\n  }\n}"
  '1':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: EntryID
                root: inputs.File
          operator: isExists
      label: 'yes'
    id: '1'
    nexttasks:
      '#default#':
      - '10'
      'yes':
      - '2'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: 'Checks if there is a file in the playbook input.

        '
      id: 7d301230-7301-4a9c-879f-2e3b4366a3d7
      iscommand: false
      name: Is there a file?
      type: condition
      version: -1
    taskid: 7d301230-7301-4a9c-879f-2e3b4366a3d7
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 115\n  }\n}"
  '10':
    id: '10'
    nexttasks:
      '#none#':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: c552720b-f6fc-49be-8c2a-1beb7178c737
      iscommand: false
      name: No File To Parse
      type: title
      version: -1
    taskid: c552720b-f6fc-49be-8c2a-1beb7178c737
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": -530,\n    \"y\": 890\n  }\n}"
  '11':
    id: '11'
    nexttasks:
      '#none#':
      - '3'
    note: false
    reputationcalc: 2
    scriptarguments:
      entryID:
        complex:
          accessor: EntryID
          filters:
          - - left:
                iscontext: true
                value:
                  simple: File.Type
              operator: containsString
              right:
                value:
                  simple: Composite Document File V2 Document
            - left:
                iscontext: true
                value:
                  simple: File.Type
              operator: containsString
              right:
                value:
                  simple: Microsoft Word
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: File.Info
              operator: isNotEqualString
              right:
                value:
                  simple: msg
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: File.Info
              operator: isNotEqualString
              right:
                value:
                  simple: eml
          - - left:
                iscontext: true
                value:
                  simple: File.Extension
              operator: isNotExists
            - left:
                iscontext: true
                value:
                  simple: File.Extension
              operator: isNotEqualString
              right:
                value:
                  simple: xls
          - - left:
                iscontext: true
                value:
                  simple: File.Extension
              operator: isNotExists
            - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: File.Extension
              operator: isNotEqualString
              right:
                value:
                  simple: xlsx
          - - left:
                iscontext: true
                value:
                  simple: File.Type
              operator: isNotExists
            - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: File.Type
              operator: notContainsString
              right:
                value:
                  simple: Excel
          root: File
          transformers:
          - operator: uniq
    separatecontext: false
    task:
      brand: ''
      description: Extracts indicators from word files (DOC, DOCX).
      id: cf8a2830-ba83-43b2-802a-1b4e3281e834
      iscommand: false
      name: Extract indicators from Word file
      scriptName: ExtractIndicatorsFromWordFile
      type: regular
      version: -1
    taskid: cf8a2830-ba83-43b2-802a-1b4e3281e834
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 920,\n    \"y\": 990\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '4'
    note: false
    reputationcalc: 1
    scriptarguments:
      append: {}
      key:
        simple: File
      value:
        complex:
          root: inputs.File
    separatecontext: false
    task:
      brand: ''
      description: Set the input file into local context.
      id: 864c6f5e-7214-4a36-8c37-80f7057bd36e
      iscommand: false
      name: Set file to local context
      scriptName: Set
      type: regular
      version: -1
    taskid: 864c6f5e-7214-4a36-8c37-80f7057bd36e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 510,\n    \"y\": 350\n  }\n}"
  '3':
    id: '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: cc0c7ac6-f764-47df-8f1e-cfbdcbd25c4e
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: cc0c7ac6-f764-47df-8f1e-cfbdcbd25c4e
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 420,\n    \"y\": 1240\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '5'
      - '7'
      - '9'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: a3d79b72-2b6b-498f-887a-d406249d18e8
      iscommand: false
      name: Extract Indicators from file
      type: title
      version: -1
    taskid: a3d79b72-2b6b-498f-887a-d406249d18e8
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 510,\n    \"y\": 535\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: EntryID
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: File.Type
                    operator: containsString
                    right:
                      value:
                        simple: ASCII text
                - - left:
                      iscontext: true
                      value:
                        simple: File.Type
                    operator: notContainsString
                    right:
                      value:
                        simple: news or mail
                - - left:
                      iscontext: true
                      value:
                        simple: File.Info
                    operator: isNotEqualString
                    right:
                      value:
                        simple: eml
                - - left:
                      iscontext: true
                      value:
                        simple: File.Info
                    operator: isNotEqualString
                    right:
                      value:
                        simple: msg
                - - left:
                      iscontext: true
                      value:
                        simple: File.Type
                    operator: notContainsString
                    right:
                      value:
                        simple: Composite Document File V2 Document, No summary info
                - - left:
                      iscontext: true
                      value:
                        simple: File.Info
                    operator: notContainsString
                    right:
                      value:
                        simple: message/rfc822
                root: File
                transformers:
                - operator: uniq
          operator: isExists
      label: 'yes'
    id: '5'
    nexttasks:
      '#default#':
      - '10'
      'yes':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Checks if there is a text-based file in context. Skips MSG and
        EML files.
      id: 5e2997db-65a5-49a7-8f9a-87892701e8fe
      iscommand: false
      name: Is there a text-based file?
      type: condition
      version: -1
    taskid: 5e2997db-65a5-49a7-8f9a-87892701e8fe
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 92.5,\n    \"y\": 700\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '3'
    note: false
    reputationcalc: 2
    scriptarguments:
      entryID:
        complex:
          accessor: EntryID
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: File.Type
              operator: containsString
              right:
                value:
                  simple: ASCII text
          - - left:
                iscontext: true
                value:
                  simple: File.Type
              operator: notContainsString
              right:
                value:
                  simple: news or mail
          - - left:
                iscontext: true
                value:
                  simple: File.Info
              operator: isNotEqualString
              right:
                value:
                  simple: eml
          - - left:
                iscontext: true
                value:
                  simple: File.Info
              operator: isNotEqualString
              right:
                value:
                  simple: msg
          - - left:
                iscontext: true
                value:
                  simple: File.Type
              operator: notContainsString
              right:
                value:
                  simple: Composite Document File V2 Document, No summary info
          - - left:
                iscontext: true
                value:
                  simple: File.Info
              operator: notContainsString
              right:
                value:
                  simple: message/rfc822
          root: File
          transformers:
          - operator: uniq
      maxFileSize: {}
    separatecontext: false
    task:
      brand: ''
      description: Extracts indicators from text-based files.
      id: e077b5e8-a546-4da5-86ea-fb327ead5a2e
      iscommand: false
      name: Extract indicators from text-based file
      scriptName: ExtractIndicatorsFromTextFile
      type: regular
      version: -1
    taskid: e077b5e8-a546-4da5-86ea-fb327ead5a2e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 92.5,\n    \"y\": 990\n  }\n}"
  '7':
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: EntryID
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: File.Type
                    operator: containsString
                    right:
                      value:
                        simple: pdf
                - - left:
                      iscontext: true
                      value:
                        simple: File.Info
                    operator: containsString
                    right:
                      value:
                        simple: pdf
                root: File
                transformers:
                - operator: uniq
          operator: isExists
      label: 'yes'
    id: '7'
    nexttasks:
      '#default#':
      - '10'
      'yes':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Checks if there is a PDF file in context.
      id: 542f7e7a-6978-480e-8356-cc7cda51a6d7
      iscommand: false
      name: Is there a PDF file?
      type: condition
      version: -1
    taskid: 542f7e7a-6978-480e-8356-cc7cda51a6d7
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 510,\n    \"y\": 700\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '3'
    note: false
    reputationcalc: 2
    scriptarguments:
      entryID:
        complex:
          accessor: EntryID
          filters:
          - - left:
                iscontext: true
                value:
                  simple: File.Type
              operator: isEqualString
              right:
                value:
                  simple: application/pdf
            - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: File.Info
              operator: containsString
              right:
                value:
                  simple: application/pdf
          root: File
          transformers:
          - operator: uniq
      maxFileSize: {}
    separatecontext: false
    task:
      brand: ''
      description: Extracts indicators from PDF files.
      id: 34c98942-d6e9-4db6-81e9-a04339cdf58c
      iscommand: false
      name: Extract indicators from PDF file
      scriptName: ReadPDFFile
      type: regular
      version: -1
    taskid: 34c98942-d6e9-4db6-81e9-a04339cdf58c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 510,\n    \"y\": 990\n  }\n}"
  '9':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: EntryID
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: File.Type
                    operator: containsString
                    right:
                      value:
                        simple: Composite Document File V2 Document
                  - left:
                      iscontext: true
                      value:
                        simple: File.Type
                    operator: containsString
                    right:
                      value:
                        simple: Microsoft Word
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: File.Info
                    operator: isNotEqualString
                    right:
                      value:
                        simple: msg
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: File.Info
                    operator: isNotEqualString
                    right:
                      value:
                        simple: eml
                - - left:
                      iscontext: true
                      value:
                        simple: File.Extension
                    operator: isNotExists
                  - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: File.Extension
                    operator: isNotEqualString
                    right:
                      value:
                        simple: xls
                - - left:
                      iscontext: true
                      value:
                        simple: File.Extension
                    operator: isNotExists
                  - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: File.Extension
                    operator: isNotEqualString
                    right:
                      value:
                        simple: xlsx
                - - left:
                      iscontext: true
                      value:
                        simple: File.Type
                    operator: isNotExists
                  - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: File.Type
                    operator: notContainsString
                    right:
                      value:
                        simple: Excel
                root: File
                transformers:
                - operator: uniq
          operator: isExists
      label: 'yes'
    id: '9'
    nexttasks:
      '#default#':
      - '10'
      'yes':
      - '11'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Checks if there is a Word file (DOC, DOCX) in context.
      id: 9ba76882-583c-4eb1-8d44-6c28ddd44d13
      iscommand: false
      name: Is there a Word file?
      type: condition
      version: -1
    taskid: 9ba76882-583c-4eb1-8d44-6c28ddd44d13
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 920,\n    \"y\": 700\n  }\n}"
tests:
- No test - deprecated playbook
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1325,\n      \"width\": 1830,\n      \"x\": -530,\n      \"y\"\
  : -20\n    }\n  }\n}"
