description: Playbook to test the IronDefense Integration.
id: IronDefenseTest
inputs:
- description: Should preform enrichment on all indicators in the incident
  key: Enrich
  required: false
  value:
    simple: 'True'
name: IronDefenseTest
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '25'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 94667f9e-9634-46dc-8f92-efc31dfaff09
      iscommand: false
      name: ''
      version: -1
    taskid: 94667f9e-9634-46dc-8f92-efc31dfaff09
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '22'
    note: false
    scriptarguments:
      alert_id:
        simple: ${IronDefense.AlertID}
      comments:
        simple: alert is unexpetedly malicious...
      expectation:
        simple: Unexpected
      severity:
        simple: Malicious
      share_comment_with_irondome:
        simple: 'False'
    separatecontext: false
    task:
      brand: ''
      description: Rates an IronDefense alert.
      id: 98b9dafc-b290-428a-896d-b37fe82ea6df
      iscommand: true
      name: Submit Incident Rating to IronDefense
      script: '|||irondefense-rate-alert'
      type: regular
      version: -1
    taskid: 98b9dafc-b290-428a-896d-b37fe82ea6df
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '22':
    id: '22'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '29'
    note: false
    scriptarguments:
      alert_id:
        simple: ${IronDefense.AlertID}
      comment:
        simple: new comment from Demisto for alert ${IronDefense.AlertID}
      share_comment_with_irondome:
        simple: 'False'
    separatecontext: false
    task:
      brand: ''
      description: Adds a comment to an IronDefense alert.
      id: cd414c8d-4f42-45c8-840d-fd8ea511a490
      iscommand: true
      name: Submit Alert Comment to IronDefense
      script: '|||irondefense-comment-alert'
      type: regular
      version: -1
    taskid: cd414c8d-4f42-45c8-840d-fd8ea511a490
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '25':
    id: '25'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '32'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 8cffa6b5-fe3d-433c-8bb6-dba265dd6a96
      iscommand: false
      name: Start Clean
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 8cffa6b5-fe3d-433c-8bb6-dba265dd6a96
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '26':
    id: '26'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    scriptarguments:
      alert_id:
        simple: ${IronDefense.AlertID}
      comments:
        simple: Bitcoin Mining
      share_comment_with_irondome:
        simple: 'False'
      status:
        simple: Awaiting Review
    separatecontext: false
    task:
      brand: ''
      description: Sets the status of an IronDefense alert.
      id: 16d30dd8-7ad4-4f23-874f-c37618c3fe8a
      iscommand: true
      name: Submit Alert Status to IronDefense
      script: '|||irondefense-set-alert-status'
      type: regular
      version: -1
    taskid: 16d30dd8-7ad4-4f23-874f-c37618c3fe8a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '28':
    id: '28'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      alert_id:
        simple: ${IronDefense.AlertID}
      comments:
        simple: Alert closed from Demisto.
      share_comment_with_irondome:
        simple: 'False'
      status:
        simple: Closed
    separatecontext: false
    task:
      brand: ''
      description: Sets the status of an IronDefense alert.
      id: e81de4f3-05b5-4b80-8596-29d9b716e5f7
      iscommand: true
      name: Close Alert in IronDefense
      script: '|||irondefense-set-alert-status'
      type: regular
      version: -1
    taskid: e81de4f3-05b5-4b80-8596-29d9b716e5f7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '29':
    id: '29'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '28'
    note: false
    scriptarguments:
      activity_end_time:
        simple: '2019-11-21T22:20:50.52Z'
      activity_start_time:
        simple: '2019-04-21T22:20:50.52Z'
      description:
        simple: bad activity from Demisto test playbook
      domain: {}
      ip:
        simple: 23.62.60.187
      name:
        simple: Demisto Test
    separatecontext: false
    task:
      brand: ''
      description: Submits an observed bad endpoint to IronDefense to create Threat
        Intelligence Rules (TIR).
      id: f2cb153b-d78a-486d-8a33-d6326bfeb2c0
      iscommand: true
      name: Submit Observed Bad Activity
      script: '|||irondefense-report-observed-bad-activity'
      type: regular
      version: -1
    taskid: f2cb153b-d78a-486d-8a33-d6326bfeb2c0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '32':
    id: '32'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '26'
    note: false
    scriptarguments:
      append: {}
      key:
        simple: IronDefense.AlertID
      value:
        simple: 93e7dfbbaece42d1b10b0ed5e4caacc2
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: a8b3a599-b8bb-4044-89c8-8939aa1a4377
      iscommand: false
      name: Set Alert ID Example
      scriptName: Set
      type: regular
      version: -1
    taskid: a8b3a599-b8bb-4044-89c8-8939aa1a4377
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 7156268a-8814-4f45-8e17-b5403b7f19b3
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 7156268a-8814-4f45-8e17-b5403b7f19b3
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1435,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
