id: Perch-Test
inputs: []
name: Perch-Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 36ada72a-053d-4de3-80ec-d73c44802f29
      iscommand: false
      name: ''
      version: -1
    taskid: 36ada72a-053d-4de3-80ec-d73c44802f29
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      closed: {}
      closed_at: {}
      community_id: {}
      created_at: {}
      dest_ip: {}
      dest_port: {}
      full_url: {}
      id: {}
      indicator_id: {}
      indicator_loaded: {}
      observable_id: {}
      ordering: {}
      page: {}
      page_size:
        simple: '3'
      protocol: {}
      sensor_id: {}
      sensor_name: {}
      soc_status: {}
      src_ip: {}
      src_port: {}
      status: {}
      status_updated_at: {}
      team_id: {}
      title: {}
      ts: {}
    separatecontext: false
    task:
      brand: Perch
      description: Searches for Alerts in Perch.
      id: 3341e946-ba8d-4a66-87a3-d3c1500594a3
      iscommand: true
      name: perch-search-alerts
      script: Perch|||perch-search-alerts
      type: regular
      version: -1
    taskid: 3341e946-ba8d-4a66-87a3-d3c1500594a3
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 230\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: Perch
      description: Lists all communities.
      id: de45714d-8af3-489f-8069-7b410bd927be
      iscommand: true
      name: perch-list-communities
      script: Perch|||perch-list-communities
      type: regular
      version: -1
    taskid: de45714d-8af3-489f-8069-7b410bd927be
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 410\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 455,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\": 50\n\
  \    }\n  }\n}"
