description: 'Manage assets vulnerabilities using Nexpose.


  This playbook runs as a job, and by default creates incidents of type "Vulnerability"
  based on assets and vulnerabilities.

  The incidents are created by querying Nexpose for the input assets vulnerability
  list.

  You can define the minimum severity (minSeverity) that incidents are created for.

  Duplicate incidents are not created for the same asset ID and the Nexpose ID.


  This playbook is a part of a series of playbooks for Nexpose vulnerability management
  and remediation.

  For this series of playbooks to run successfully, create a Job and do the following:

  1. Assign this playbook to the Job

  2. Enter the relevant assets'' hostnames in the playbook inputs (comma separated
  list).

  3. Associate the "Vulnerability" type incident to the "Vulnerability Handling -
  Nexpose" playbook.'
fromversion: 3.6.0
id: vulnerability_management_-_nexpose_job
inputs:
- description: Assets' hostnames list (comma separated).
  key: Hostname
  required: false
  value: {}
- description: The minimum Nexpose severity (Moderate, Severe, Critical) to create
    incidents for.
  key: MinSeverity
  required: true
  value:
    simple: Severe
name: Vulnerability Management - Nexpose (Job)
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '5'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 262846f7-b22f-4bb4-8726-c0e9908239c7
      iscommand: false
      name: ''
      version: -1
    taskid: 262846f7-b22f-4bb4-8726-c0e9908239c7
    type: start
    view: "{\n  \"position\": {\n    \"x\": 377.5,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
      - '7'
    reputationcalc: 0
    scriptarguments:
      hostNameIs:
        complex:
          root: inputs.Hostname
          transformers:
          - args:
              delimiter:
                value:
                  simple: ','
            operator: string.splitAndTrim
      ipAddressIs: {}
      limit: {}
      match: {}
      query: {}
      riskScoreHigherThan: {}
      siteIdIn: {}
      sort: {}
      vulnerabilityTitleContains: {}
    separatecontext: false
    task:
      brand: Rapid7 Nexpose
      description: Query Nexpose for the assets' information.
      id: 705f459e-8a36-425a-8895-9acb80e6590a
      iscommand: true
      name: Get assets' information
      script: Rapid7 Nexpose|||nexpose-search-assets
      type: regular
      version: -1
    taskid: 705f459e-8a36-425a-8895-9acb80e6590a
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '10':
    id: '10'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: d6469ba0-ed85-42d0-80e6-770fe1ca044a
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d6469ba0-ed85-42d0-80e6-770fe1ca044a
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1185\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: f0e9c893-d62c-44d7-8d7a-505f13d19c9c
      iscommand: false
      name: Enrich assets
      type: title
      version: -1
    taskid: f0e9c893-d62c-44d7-8d7a-505f13d19c9c
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '6'
    reputationcalc: 0
    scriptarguments:
      assets:
        complex:
          accessor: Asset.AssetId
          root: Nexpose
      name: {}
      template: {}
    separatecontext: false
    task:
      brand: Rapid7 Nexpose
      description: Query Nexpose for the latest assets' reports.
      id: 59f0f9f6-ddfa-44ef-8768-6754855f9efb
      iscommand: true
      name: Get assets' reports
      script: Rapid7 Nexpose|||nexpose-create-assets-report
      type: regular
      version: -1
    taskid: 59f0f9f6-ddfa-44ef-8768-6754855f9efb
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 690\n  }\n}"
  '5':
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: string.isEqual
                    right:
                      value:
                        simple: Rapid7 Nexpose
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: string.isEqual
                    right:
                      value:
                        simple: active
                root: modules
          operator: general.isExists
      label: 'yes'
    id: '5'
    nexttasks:
      '#default#':
      - '6'
      'yes':
      - '1'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      description: 'Verify that there is a valid instance of Nexpose enabled.

        '
      id: a9c0c0e6-55eb-4f19-8c8b-675bcdb21138
      iscommand: false
      name: Is Nexpose enabled?
      type: condition
      version: -1
    taskid: a9c0c0e6-55eb-4f19-8c8b-675bcdb21138
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 377.5,\n    \"y\": 195\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '9'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 15066fb2-3cbe-448c-8cdf-f6560d23a013
      iscommand: false
      name: Close investigation
      type: title
      version: -1
    taskid: 15066fb2-3cbe-448c-8cdf-f6560d23a013
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 862\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '8'
    reputationcalc: 0
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: f893f0f5-10ea-43ea-8fc7-53a9e51d0e6c
      iscommand: false
      name: Create incidents
      type: title
      version: -1
    taskid: f893f0f5-10ea-43ea-8fc7-53a9e51d0e6c
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '6'
    reputationcalc: 0
    scriptarguments:
      assetID:
        complex:
          accessor: Asset.AssetId
          root: Nexpose
      incidentType: {}
      minSeverity:
        simple: ${inputs.MinSeverity}
    separatecontext: false
    task:
      brand: ''
      description: 'Create incidents based on the Nexpose asset ID and vulnerability
        ID.

        Duplicate incidents are not created for the same asset ID and vulnerability
        ID.'
      id: 8cac3cd1-2a87-45a5-8456-30991f126957
      iscommand: false
      name: Create Incidents for assets and vulnerabilities
      scriptName: NexposeCreateIncidentsFromAssets
      type: regular
      version: -1
    taskid: 8cac3cd1-2a87-45a5-8456-30991f126957
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 690\n  }\n}"
  '9':
    id: '9'
    nexttasks:
      '#none#':
      - '10'
    reputationcalc: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      id: {}
      importantfield: {}
      test2: {}
      timefield1: {}
    separatecontext: false
    task:
      brand: Builtin
      description: Close the investigation
      id: 100c24b9-566a-4dc6-8e41-ed1de7ed8a32
      iscommand: true
      name: Close investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 100c24b9-566a-4dc6-8e41-ed1de7ed8a32
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1010\n  }\n}"
tests:
- No test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1200,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
