description: ''
id: Test - Cofense Intelligence
inputs: []
name: Test - Cofense Intelligence
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: b062869b-f43b-4fdc-81ce-9ede86b1b87b
      iscommand: false
      name: ''
      version: -1
    taskid: b062869b-f43b-4fdc-81ce-9ede86b1b87b
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      ip:
        simple: 51.254.240.48
    separatecontext: false
    task:
      brand: Cofense Intelligence
      description: Check the reputation of an IP address.
      id: beb6b840-348a-42b8-8171-4d6d17b43283
      iscommand: true
      name: Check IP
      script: Cofense Intelligence|||ip
      type: regular
      version: -1
    taskid: beb6b840-348a-42b8-8171-4d6d17b43283
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      all:
        simple: true
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: c02790a6-06f3-4b00-8c67-22477beba083
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: c02790a6-06f3-4b00-8c67-22477beba083
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    scriptarguments:
      email:
        simple: earner@zoho.com
    separatecontext: false
    task:
      brand: Cofense Intelligence
      description: Check the reputation of an email address.
      id: cd6f98a4-ec7d-4e63-8043-d0fa9cf902f9
      iscommand: true
      name: Check email
      script: Cofense Intelligence|||email
      type: regular
      version: -1
    taskid: cd6f98a4-ec7d-4e63-8043-d0fa9cf902f9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    scriptarguments:
      all:
        simple: true
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 0c9b2644-d74b-4111-8156-98c3d794f3ca
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 0c9b2644-d74b-4111-8156-98c3d794f3ca
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    scriptarguments:
      limit: {}
      str:
        simple: sex
    separatecontext: false
    task:
      brand: ''
      description: Search for extracted strings identified within malware campaigns.
      id: f440a6e5-3e83-481a-89aa-d91e7adc2f29
      iscommand: true
      name: Check PhishMe string
      script: '|||cofense-search'
      type: regular
      version: -1
    taskid: f440a6e5-3e83-481a-89aa-d91e7adc2f29
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1945\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      true:
      - '16'
    note: false
    scriptarguments:
      first:
        simple: ${Cofense.NumOfThreats}
      key: {}
      left:
        simple: ${DBotScore.Score}
      right:
        simple: '0'
      second:
        simple: '9'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 5bcf192d-703d-4675-80b8-236e34acca23
      iscommand: false
      name: Check number of PhishMe threats
      scriptName: IsGreaterThan
      type: condition
      version: -1
    taskid: 5bcf192d-703d-4675-80b8-236e34acca23
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2120\n  }\n}"
  '16':
    id: '16'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: d4eb3bbf-70d3-43e5-8e94-f1fbfbc3e9b3
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d4eb3bbf-70d3-43e5-8e94-f1fbfbc3e9b3
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2295\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      true:
      - '22'
    note: false
    results:
    - AreValuesEqual
    scriptarguments:
      key: {}
      left:
        simple: ${DBotScore.Score}
      right:
        simple: '3'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 32185455-d129-45cd-824c-2dae3c44c82d
      iscommand: false
      name: Check DBotScore
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: 32185455-d129-45cd-824c-2dae3c44c82d
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '22':
    id: '22'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      all:
        simple: true
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 47ff9da6-51bc-4ab4-8d52-2c40ad3a9bb6
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 47ff9da6-51bc-4ab4-8d52-2c40ad3a9bb6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      url:
        simple: zsn5qtrgfpu4tmpg.onion.gq
    separatecontext: false
    task:
      brand: Cofense Intelligence
      description: Checks the reputation of a URL.
      id: 6fca4ebf-bc46-419a-8a52-7c5c4c26174e
      iscommand: true
      name: Check url
      script: Cofense Intelligence|||url
      type: regular
      version: -1
    taskid: 6fca4ebf-bc46-419a-8a52-7c5c4c26174e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: true
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: df96684f-ac80-49f5-845c-9637956ca12e
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: df96684f-ac80-49f5-845c-9637956ca12e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      all:
        simple: true
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 4a848dd9-5347-4c49-8cfc-12ca3cdc0010
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 4a848dd9-5347-4c49-8cfc-12ca3cdc0010
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      file:
        simple: 6be4f92e2ae9a2a9d411f7be9ecd06495f847009
    separatecontext: false
    task:
      brand: Cofense Intelligence
      description: Checks the reputation of a file hash.
      id: 2629890c-168a-411d-85d8-82dc73113354
      iscommand: true
      name: Check file hash
      script: Cofense Intelligence|||file
      type: regular
      version: -1
    taskid: 2629890c-168a-411d-85d8-82dc73113354
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2310,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
