id: WhatsMyBrowser-Test
inputs: []
name: WhatsMyBrowser-Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: ceb08362-ff7c-40f4-8765-a0c0367da2f3
      iscommand: false
      name: ''
      version: -1
    taskid: ceb08362-ff7c-40f4-8765-a0c0367da2f3
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      append: {}
      key:
        simple: UserAgent
      value:
        simple: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36
          (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: a1f2cd2f-3629-4cd2-828f-3cc96540d70b
      iscommand: false
      name: Set
      scriptName: Set
      type: regular
      version: -1
    taskid: a1f2cd2f-3629-4cd2-828f-3cc96540d70b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 190\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
      - '5'
    note: false
    scriptarguments:
      UserAgent:
        simple: ${UserAgent}
      extend-context:
        simple: Test.Parse=result.code
    separatecontext: false
    task:
      brand: WhatsMyBrowser
      description: Parses a User Agent string
      id: 1eceee9c-7f36-4e55-8487-0984db520b4f
      iscommand: true
      name: ua-parse
      script: WhatsMyBrowser|||ua-parse
      type: regular
      version: -1
    taskid: 1eceee9c-7f36-4e55-8487-0984db520b4f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 370\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${UA.Parse.OperatingSystem}
          operator: isEqualString
          right:
            value:
              simple: Mac OS X (Mavericks)
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: c9b72a5f-8b3d-4a4d-8fc1-10ec2fcaf6ae
      iscommand: false
      name: Check Results
      type: condition
      version: -1
    taskid: c9b72a5f-8b3d-4a4d-8fc1-10ec2fcaf6ae
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 160,\n    \"y\": 550\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 93bdad7e-c32d-4efb-86ac-178b9430c7e7
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 93bdad7e-c32d-4efb-86ac-178b9430c7e7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 750\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    note: false
    scriptarguments:
      value:
        simple: ${Test.Parse}
    separatecontext: false
    task:
      brand: ''
      description: Prints text to war room (Markdown supported)
      id: d04072b2-b3a9-4e28-87bd-fd21a2c655e2
      iscommand: false
      name: Verify Extend Context
      scriptName: Print
      type: regular
      version: -1
    taskid: d04072b2-b3a9-4e28-87bd-fd21a2c655e2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 760,\n    \"y\": 550\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 795,\n      \"width\": 980,\n      \"x\": 160,\n      \"y\": 50\n\
  \    }\n  }\n}"
