id: GCS Bucket Management - Test
inputs: []
name: GCS Bucket Management - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 6f7781f8-828c-4d20-8600-7acfa9400bd0
      iscommand: false
      name: ''
      version: -1
    taskid: 6f7781f8-828c-4d20-8600-7acfa9400bd0
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    separatecontext: false
    task:
      brand: Google Cloud Storage
      description: Retrieves the list of buckets in the project
      id: 7c2c246c-c3ff-480a-8fb0-1dbc409f4d3d
      iscommand: true
      name: List buckets
      script: Google Cloud Storage|||gcs-list-buckets
      type: regular
      version: -1
    taskid: 7c2c246c-c3ff-480a-8fb0-1dbc409f4d3d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1215\n  }\n}"
  '10':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Bucket.Name
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: GCS.Bucket.Name
                    operator: isEqualString
                    right:
                      value:
                        simple: demisto-test-1
                root: GCS
          operator: isExists
      label: 'yes'
    id: '10'
    ignoreworker: false
    nexttasks:
      'yes':
      - '24'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 2124810e-376d-42cd-814f-2f64c026e562
      iscommand: false
      name: Verify bucket created
      type: condition
      version: -1
    taskid: 2124810e-376d-42cd-814f-2f64c026e562
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1915\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      all: {}
      index: {}
      key:
        simple: GCS
      keysToKeep: {}
      subplaybook:
        simple: 'yes'
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: d8c10364-7016-4b27-8781-368458f8307d
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: d8c10364-7016-4b27-8781-368458f8307d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2235\n  }\n}"
  '12':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: GCS.Bucket
          operator: isNotExists
      label: 'yes'
    id: '12'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: b7d67780-37e5-4c96-8fd2-a3c90241fb27
      iscommand: false
      name: Test sanity - verify context cleared
      type: condition
      version: -1
    taskid: b7d67780-37e5-4c96-8fd2-a3c90241fb27
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2410\n  }\n}"
  '13':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Bucket.Name
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: GCS.Bucket.Name
                    operator: isEqualString
                    right:
                      value:
                        simple: demisto-test-1
                root: GCS
          operator: isExists
      label: 'yes'
    id: '13'
    ignoreworker: false
    nexttasks:
      'yes':
      - '25'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 10dae3c5-80c9-445d-8387-14a4ca15a7bd
      iscommand: false
      name: Verify bucket retrieved
      type: condition
      version: -1
    taskid: 10dae3c5-80c9-445d-8387-14a4ca15a7bd
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2760\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      all: {}
      index: {}
      key:
        simple: GCS
      keysToKeep: {}
      subplaybook:
        simple: 'yes'
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 9d63da06-07d2-4035-8570-4cac8e296025
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 9d63da06-07d2-4035-8570-4cac8e296025
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3255\n  }\n}"
  '16':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Bucket.Name
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: GCS.Bucket.Name
                    operator: isEqualString
                    right:
                      value:
                        simple: demisto-test-1
                root: GCS
          operator: isNotExists
      label: 'yes'
    id: '16'
    ignoreworker: false
    nexttasks:
      'yes':
      - '7'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 3de5756f-081c-46dd-8ffc-df7509317cc0
      iscommand: false
      name: Verify that bucket demisto-test-1 does not exist
      type: condition
      version: -1
    taskid: 3de5756f-081c-46dd-8ffc-df7509317cc0
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3605\n  }\n}"
  '17':
    id: '17'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '18'
    note: false
    separatecontext: false
    task:
      brand: Google Cloud Storage
      description: Retrieves the list of buckets in the project
      id: 1679c1ae-45f6-4c0a-88a9-35bb2bbd933f
      iscommand: true
      name: List buckets
      script: Google Cloud Storage|||gcs-list-buckets
      type: regular
      version: -1
    taskid: 1679c1ae-45f6-4c0a-88a9-35bb2bbd933f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '18':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: GCS.Bucket.Name
          operator: isEqualString
          right:
            value:
              simple: demisto-test-1
      label: 'yes'
    id: '18'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '20'
      'yes':
      - '19'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: ce7bca64-54f1-4a3c-8244-0ffc21abcecd
      iscommand: false
      name: Bucket demisto-test-1 exists?
      type: condition
      version: -1
    taskid: ce7bca64-54f1-4a3c-8244-0ffc21abcecd
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '19':
    id: '19'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '23'
    note: false
    scriptarguments:
      bucket_name:
        simple: demisto-test-1
      force:
        simple: 'true'
    separatecontext: false
    task:
      brand: Google Cloud Storage
      description: Permanently deletes a bucket
      id: d48eb14a-7245-43cb-8859-2c6a371c6c35
      iscommand: true
      name: Delete bucket
      script: Google Cloud Storage|||gcs-delete-bucket
      type: regular
      version: -1
    taskid: d48eb14a-7245-43cb-8859-2c6a371c6c35
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 545\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      bucket_acl: {}
      bucket_name:
        simple: demisto-test-1
      default_object_acl: {}
    separatecontext: false
    task:
      brand: Google Cloud Storage
      description: Creates a new bucket
      id: 4901914b-2618-4984-82c3-5fb09086ec6b
      iscommand: true
      name: Create bucket demisto-test-1
      script: Google Cloud Storage|||gcs-create-bucket
      type: regular
      version: -1
    taskid: 4901914b-2618-4984-82c3-5fb09086ec6b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1565\n  }\n}"
  '20':
    id: '20'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: b9e91aba-c353-40c3-88da-f29cf00933d9
      iscommand: false
      name: 'Test: List Buckets + Create Bucket'
      type: title
      version: -1
    taskid: b9e91aba-c353-40c3-88da-f29cf00933d9
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '22':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: GCS
          operator: isNotExists
      label: 'yes'
    id: '22'
    ignoreworker: false
    nexttasks:
      'yes':
      - '20'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 61817ffd-f4d7-42df-892b-ff67f36d3658
      iscommand: false
      name: Test sanity - verify context cleared
      type: condition
      version: -1
    taskid: 61817ffd-f4d7-42df-892b-ff67f36d3658
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 895\n  }\n}"
  '23':
    id: '23'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '22'
    note: false
    scriptarguments:
      all: {}
      index: {}
      key:
        simple: GCS
      keysToKeep: {}
      subplaybook:
        simple: 'yes'
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 9ee417c3-cf67-464b-892f-a6a88d5291bc
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 9ee417c3-cf67-464b-892f-a6a88d5291bc
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 720\n  }\n}"
  '24':
    id: '24'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: b639a3d8-a7b4-41da-8ed7-cd58e667075c
      iscommand: false
      name: 'Test: Get Bucket'
      type: title
      version: -1
    taskid: b639a3d8-a7b4-41da-8ed7-cd58e667075c
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2090\n  }\n}"
  '25':
    id: '25'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 201faf31-1b6b-45c6-846f-96da32b9cc8b
      iscommand: false
      name: 'Test: Delete Bucket'
      type: title
      version: -1
    taskid: 201faf31-1b6b-45c6-846f-96da32b9cc8b
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2935\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    separatecontext: false
    task:
      brand: Google Cloud Storage
      description: Retrieves the list of buckets in the project
      id: 953c67ae-56cd-4558-842b-a4c44fbcb2e6
      iscommand: true
      name: List buckets
      script: Google Cloud Storage|||gcs-list-buckets
      type: regular
      version: -1
    taskid: 953c67ae-56cd-4558-842b-a4c44fbcb2e6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1740\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    scriptarguments:
      bucket_name:
        simple: demisto-test-1
    separatecontext: false
    task:
      brand: Google Cloud Storage
      description: Retrieves bucket information
      id: 2ba84c82-e404-40cf-8dea-77f6b384821c
      iscommand: true
      name: Get demisto-test-1 info
      script: Google Cloud Storage|||gcs-get-bucket
      type: regular
      version: -1
    taskid: 2ba84c82-e404-40cf-8dea-77f6b384821c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2585\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    scriptarguments:
      bucket_name:
        simple: demisto-test-1
      force: {}
    separatecontext: false
    task:
      brand: Google Cloud Storage
      description: Permanently deletes a bucket
      id: 7a367ba3-5c4e-49c9-8e0b-8974fdd50077
      iscommand: true
      name: Delete bucket demisto-test-1
      script: Google Cloud Storage|||gcs-delete-bucket
      type: regular
      version: -1
    taskid: 7a367ba3-5c4e-49c9-8e0b-8974fdd50077
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3080\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    separatecontext: false
    task:
      brand: Google Cloud Storage
      description: Retrieves the list of buckets in the project
      id: fe8c0842-eb4e-43bc-82b1-6b1af9ac48b7
      iscommand: true
      name: List buckets
      script: Google Cloud Storage|||gcs-list-buckets
      type: regular
      version: -1
    taskid: fe8c0842-eb4e-43bc-82b1-6b1af9ac48b7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3430\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d95c33aa-cce0-4fe1-8ca1-7f28f0086149
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d95c33aa-cce0-4fe1-8ca1-7f28f0086149
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3780\n  }\n}"
  '9':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Bucket.Name
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: GCS.Bucket.Name
                    operator: isEqualString
                    right:
                      value:
                        simple: demisto-test-1
                root: GCS
          operator: isNotExists
      label: 'yes'
    id: '9'
    ignoreworker: false
    nexttasks:
      'yes':
      - '2'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 70296e79-cff9-4b35-892a-6c446351dfc8
      iscommand: false
      name: Verify that bucket demisto-test-1 does not exist
      type: condition
      version: -1
    taskid: 70296e79-cff9-4b35-892a-6c446351dfc8
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1390\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 3795,\n      \"width\": 492.5,\n      \"x\": 50,\n      \"y\"\
  : 50\n    }\n  }\n}"
