id: GCS Object Operations - Test
inputs: []
name: GCS Object Operations - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '21'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: bdf650db-5b82-483b-8992-9277a81bed10
      iscommand: false
      name: ''
      version: -1
    taskid: bdf650db-5b82-483b-8992-9277a81bed10
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '18'
    note: false
    scriptarguments:
      bucket_name:
        simple: demisto-test-2
      force:
        simple: 'true'
    separatecontext: false
    task:
      brand: Google Cloud Storage
      description: Permanently deletes a bucket
      id: 186182d0-b4fd-4b70-84b5-3d81b7a02829
      iscommand: true
      name: Delete bucket with force=true
      script: Google Cloud Storage|||gcs-delete-bucket
      type: regular
      version: -1
    taskid: 186182d0-b4fd-4b70-84b5-3d81b7a02829
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3255\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      data:
        simple: Think I'll take TWO chickens.
      entryId: {}
      filename:
        simple: test.txt
    separatecontext: false
    task:
      brand: ''
      description: 'Will create a file (using the given data input or entry ID) and
        upload it to current investigation war room.

        '
      id: 19b9e980-5e2a-4048-8b3c-bc7a0e9f98f8
      iscommand: false
      name: Create test.txt file
      scriptName: FileCreateAndUpload
      type: regular
      version: -1
    taskid: 19b9e980-5e2a-4048-8b3c-bc7a0e9f98f8
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1740\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d505c96a-6337-4e68-854b-4c79b5a24c3b
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d505c96a-6337-4e68-854b-4c79b5a24c3b
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3955\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '29'
    note: false
    scriptarguments:
      all: {}
      index: {}
      key:
        simple: GCS
      keysToKeep: {}
      subplaybook:
        simple: 'yes'
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: c7e6c250-d0a5-45a2-85b5-22f16a4920b6
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: c7e6c250-d0a5-45a2-85b5-22f16a4920b6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 720\n  }\n}"
  '14':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: BucketObject.Name
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: GCS.BucketObject.Bucket
                    operator: isEqualString
                    right:
                      value:
                        simple: demisto-test-2
                root: GCS
          operator: isNotExists
      label: 'yes'
    id: '14'
    ignoreworker: false
    nexttasks:
      'yes':
      - '11'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 4fc13b70-309c-4c03-8afe-a820b7554a57
      iscommand: false
      name: Verify no objects in bucket
      type: condition
      version: -1
    taskid: 4fc13b70-309c-4c03-8afe-a820b7554a57
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1565\n  }\n}"
  '15':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: GCS.BucketObject.Name
          operator: isEqualString
          right:
            value:
              simple: foo/bar/baz.txt
      - - left:
            iscontext: true
            value:
              simple: GCS.BucketObject.Bucket
          operator: isEqualString
          right:
            value:
              simple: demisto-test-2
      - - left:
            iscontext: true
            value:
              simple: GCS.BucketObject.Size
          operator: isEqualString
          right:
            value:
              simple: '29'
      label: 'yes'
    id: '15'
    ignoreworker: false
    nexttasks:
      'yes':
      - '27'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 479aae91-be0f-48b6-8f92-359265f232cd
      iscommand: false
      name: Verify object created
      type: condition
      version: -1
    taskid: 479aae91-be0f-48b6-8f92-359265f232cd
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2265\n  }\n}"
  '16':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: File.Name
          operator: isEqualString
          right:
            value:
              simple: baz.txt
      - - left:
            iscontext: true
            value:
              simple: File.Size
          operator: isEqualString
          right:
            value:
              simple: '29'
      label: 'yes'
    id: '16'
    ignoreworker: false
    nexttasks:
      'yes':
      - '28'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 4336ae3b-9a18-4c17-8f62-bad1b6f0d3ff
      iscommand: false
      name: Verify downloaded file name and size
      type: condition
      version: -1
    taskid: 4336ae3b-9a18-4c17-8f62-bad1b6f0d3ff
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2935\n  }\n}"
  '17':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Bucket.Name
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: GCS.Bucket.Name
                    operator: isEqualString
                    right:
                      value:
                        simple: demisto-test-2
                root: GCS
          operator: isNotExists
      label: 'yes'
    id: '17'
    ignoreworker: false
    nexttasks:
      'yes':
      - '12'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: a630d29f-1cad-4dfb-8d3c-38406daa3e2b
      iscommand: false
      name: Verify bucket was force-deleted
      type: condition
      version: -1
    taskid: a630d29f-1cad-4dfb-8d3c-38406daa3e2b
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3780\n  }\n}"
  '18':
    id: '18'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '19'
    note: false
    scriptarguments:
      all: {}
      index: {}
      key:
        simple: GCS
      keysToKeep: {}
      subplaybook:
        simple: 'yes'
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 1432e563-9b87-43b9-8380-ef9c3714215e
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 1432e563-9b87-43b9-8380-ef9c3714215e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3430\n  }\n}"
  '19':
    id: '19'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    separatecontext: false
    task:
      brand: Google Cloud Storage
      description: Retrieves the list of buckets in the project
      id: a77d921e-91c8-43e9-8d6b-b89719587c4c
      iscommand: true
      name: gcs-list-buckets
      script: Google Cloud Storage|||gcs-list-buckets
      type: regular
      version: -1
    taskid: a77d921e-91c8-43e9-8d6b-b89719587c4c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3605\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      bucket_acl: {}
      bucket_name:
        simple: demisto-test-2
      default_object_acl: {}
    separatecontext: false
    task:
      brand: Google Cloud Storage
      description: Creates a new bucket
      id: 3fd0ebec-72e5-4fef-81bf-056a12d0bf2b
      iscommand: true
      name: Create bucket demisto-test-2
      script: Google Cloud Storage|||gcs-create-bucket
      type: regular
      version: -1
    taskid: 3fd0ebec-72e5-4fef-81bf-056a12d0bf2b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1215\n  }\n}"
  '20':
    id: '20'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '26'
    note: false
    scriptarguments:
      all: {}
      index: {}
      key:
        simple: GCS
      keysToKeep: {}
      subplaybook:
        simple: 'yes'
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: ba111847-892d-4e8a-8356-b4bda64bef9c
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: ba111847-892d-4e8a-8356-b4bda64bef9c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2585\n  }\n}"
  '21':
    id: '21'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '22'
    note: false
    separatecontext: false
    task:
      brand: Google Cloud Storage
      description: Retrieves the list of buckets in the project
      id: 154407db-c656-408b-8c39-b24af6191839
      iscommand: true
      name: List buckets
      script: Google Cloud Storage|||gcs-list-buckets
      type: regular
      version: -1
    taskid: 154407db-c656-408b-8c39-b24af6191839
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '22':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: GCS.Bucket.Name
          operator: isEqualString
          right:
            value:
              simple: demisto-test-2
      label: 'yes'
    id: '22'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '24'
      'yes':
      - '23'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 0a74a50b-3ddd-414d-89a2-7c349ca35b6f
      iscommand: false
      name: Bucket demisto-test-2 exists?
      type: condition
      version: -1
    taskid: 0a74a50b-3ddd-414d-89a2-7c349ca35b6f
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '23':
    id: '23'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    scriptarguments:
      bucket_name:
        simple: demisto-test-2
      force:
        simple: 'true'
    separatecontext: false
    task:
      brand: Google Cloud Storage
      description: Permanently deletes a bucket
      id: 76d80703-7260-4947-8b8b-ddd750be40e6
      iscommand: true
      name: Delete bucket
      script: Google Cloud Storage|||gcs-delete-bucket
      type: regular
      version: -1
    taskid: 76d80703-7260-4947-8b8b-ddd750be40e6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 545\n  }\n}"
  '24':
    id: '24'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 6da2fdb7-3313-4e77-8bb9-84be2a6a6321
      iscommand: false
      name: 'Test: List Objects + Upload File'
      type: title
      version: -1
    taskid: 6da2fdb7-3313-4e77-8bb9-84be2a6a6321
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '26':
    id: '26'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    scriptarguments:
      bucket_name:
        simple: demisto-test-2
      object_name:
        simple: foo/bar/baz.txt
    separatecontext: false
    task:
      brand: Google Cloud Storage
      description: Retrieves object data into a file
      id: 91a5bb2c-a3b2-4d64-8b1a-f5a592afaf89
      iscommand: true
      name: Download the object
      script: Google Cloud Storage|||gcs-download-file
      type: regular
      version: -1
    taskid: 91a5bb2c-a3b2-4d64-8b1a-f5a592afaf89
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2760\n  }\n}"
  '27':
    id: '27'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '20'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 0c26f405-8f2c-46fa-8e9a-75930c8cb759
      iscommand: false
      name: 'Test: Download File'
      type: title
      version: -1
    taskid: 0c26f405-8f2c-46fa-8e9a-75930c8cb759
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2440\n  }\n}"
  '28':
    id: '28'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 0da256be-7a13-43ff-86f4-dd0d744c412f
      iscommand: false
      name: 'Test: Force-delete Bucket'
      type: title
      version: -1
    taskid: 0da256be-7a13-43ff-86f4-dd0d744c412f
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3110\n  }\n}"
  '29':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: GCS
          operator: isNotExists
      label: 'yes'
    id: '29'
    ignoreworker: false
    nexttasks:
      'yes':
      - '24'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: cd7fa3c2-0d60-4a0b-899d-745d688822e5
      iscommand: false
      name: Test sanity - verify context cleared
      type: condition
      version: -1
    taskid: cd7fa3c2-0d60-4a0b-899d-745d688822e5
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 895\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    scriptarguments:
      bucket_name:
        simple: demisto-test-2
    separatecontext: false
    task:
      brand: Google Cloud Storage
      description: Retrieves the list of objects in a bucket
      id: 15a221a5-8554-4661-8f62-9f7b978f6147
      iscommand: true
      name: List objects in bucket
      script: Google Cloud Storage|||gcs-list-bucket-objects
      type: regular
      version: -1
    taskid: 15a221a5-8554-4661-8f62-9f7b978f6147
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1390\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      bucket_name:
        simple: demisto-test-2
      entry_id:
        simple: ${File.EntryID}
      object_acl: {}
      object_name:
        simple: foo/bar/baz.txt
    separatecontext: false
    task:
      brand: Google Cloud Storage
      description: Uploads a file (object) into a bucket
      id: d1bdfab5-fd80-4e74-833a-5dfd1ec0b603
      iscommand: true
      name: Upload test.txt (create object)
      script: Google Cloud Storage|||gcs-upload-file
      type: regular
      version: -1
    taskid: d1bdfab5-fd80-4e74-833a-5dfd1ec0b603
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1915\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    scriptarguments:
      bucket_name:
        simple: demisto-test-2
    separatecontext: false
    task:
      brand: Google Cloud Storage
      description: Retrieves the list of objects in a bucket
      id: 29779a24-31d1-4e7e-8731-48fe0334a337
      iscommand: true
      name: List objects in bucket
      script: Google Cloud Storage|||gcs-list-bucket-objects
      type: regular
      version: -1
    taskid: 29779a24-31d1-4e7e-8731-48fe0334a337
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2090\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 3970,\n      \"width\": 492.5,\n      \"x\": 50,\n      \"y\"\
  : 50\n    }\n  }\n}"
