id: CrowdStrike Falcon Intel v2
inputs: []
name: CrowdStrike Falcon Intel v2
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 2563b107-8432-4d8f-86d6-cf4b2f74a0a2
      iscommand: false
      name: ''
      version: -1
    taskid: 2563b107-8432-4d8f-86d6-cf4b2f74a0a2
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      ip:
        simple: 4.4.4.4
    separatecontext: false
    task:
      brand: FalconIntel
      id: a0690b52-40a9-4023-8aba-5202bce9e7e2
      iscommand: true
      name: Check IP Address
      script: FalconIntel|||ip
      type: regular
      version: -1
    taskid: a0690b52-40a9-4023-8aba-5202bce9e7e2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    scriptarguments:
      filter:
        simple: match
      page: {}
      pageSize: {}
      parameter:
        simple: indicator
      sort: {}
      value:
        simple: panda
    separatecontext: false
    task:
      brand: ''
      description: Search known indicators based on the given parameters
      id: ef036f00-07eb-497b-8966-7b4e16072881
      iscommand: true
      name: Search known indicators
      script: '|||cs-indicators'
      type: regular
      version: -1
    taskid: ef036f00-07eb-497b-8966-7b4e16072881
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      actor:
        simple: panda
      description: {}
      limit:
        simple: '2'
      maxLastModifiedDate: {}
      minLastModifiedDate:
        simple: 2019-06-28
      motivations: {}
      name: {}
      offset: {}
      q: {}
      slug: {}
      sort: {}
      subType: {}
      tags: {}
      targetCountries: {}
      targetIndustries: {}
      type: {}
    separatecontext: false
    task:
      brand: ''
      description: The Falcon Intel Reports API allows to query CrowdStrike intelligence
        publications.
      id: 758d2d76-0d38-4750-80a7-1f07ec164d1d
      iscommand: true
      name: Query CrowdStrike intelligence publications
      script: '|||cs-reports'
      type: regular
      version: -1
    taskid: 758d2d76-0d38-4750-80a7-1f07ec164d1d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1945\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      id: 0c544724-337f-4d80-834f-9ab2d9377449
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 0c544724-337f-4d80-834f-9ab2d9377449
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '14':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Type
          operator: isEqualString
          right:
            value:
              simple: ip
        - left:
            iscontext: true
            value:
              simple: DBotScore.Type
          operator: isEqualString
          right:
            value:
              simple: hash
        - left:
            iscontext: true
            value:
              simple: DBotScore.Type
          operator: isEqualString
          right:
            value:
              simple: url
        - left:
            iscontext: true
            value:
              simple: DBotScore.Type
          operator: isEqualString
          right:
            value:
              simple: domain
      label: 'yes'
    id: '14'
    ignoreworker: false
    nexttasks:
      'yes':
      - '11'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 177816e5-3a30-45ac-8d8e-42b2296750d2
      iscommand: false
      name: Test if values exist from API calls
      type: condition
      version: -1
    taskid: 177816e5-3a30-45ac-8d8e-42b2296750d2
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      id: 22f372fd-22f4-45c8-8a56-6b0567d17fbe
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 22f372fd-22f4-45c8-8a56-6b0567d17fbe
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      file:
        simple: 369c8fc6532ba547d7ef5985bb5e880a
    separatecontext: false
    task:
      brand: FalconIntel
      id: 43e08778-21ef-4d20-8ec5-e694ad9b06cc
      iscommand: true
      name: Check File
      script: FalconIntel|||file
      type: regular
      version: -1
    taskid: 43e08778-21ef-4d20-8ec5-e694ad9b06cc
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      url:
        simple: http://8.8.8.8/google.doc
    separatecontext: false
    task:
      brand: FalconIntel
      id: 5825a5ef-e623-4b61-8f5d-8d27d54931ac
      iscommand: true
      name: Check URL
      script: FalconIntel|||url
      type: regular
      version: -1
    taskid: 5825a5ef-e623-4b61-8f5d-8d27d54931ac
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      domain:
        simple: dns02.hpupdat.net
    separatecontext: false
    task:
      brand: FalconIntel
      id: bb11d0c5-0478-436e-80e6-8c0b5c819be1
      iscommand: true
      name: Check Domain
      script: FalconIntel|||domain
      type: regular
      version: -1
    taskid: bb11d0c5-0478-436e-80e6-8c0b5c819be1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '6':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Type
          operator: isEqualString
          right:
            value:
              simple: ip
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Type
          operator: isEqualString
          right:
            value:
              simple: hash
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Type
          operator: isEqualString
          right:
            value:
              simple: url
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Type
          operator: isEqualString
          right:
            value:
              simple: domain
      label: 'yes'
    id: '6'
    ignoreworker: false
    nexttasks:
      'yes':
      - '13'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d3f0406d-c132-484c-8f15-40c08022a6c7
      iscommand: false
      name: Test if values exist from API calls
      type: condition
      version: -1
    taskid: d3f0406d-c132-484c-8f15-40c08022a6c7
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 4a47d3e9-70c6-47c9-86e9-2a9f37ad7793
      iscommand: false
      name: Test playbook finished successfully.
      type: title
      version: -1
    taskid: 4a47d3e9-70c6-47c9-86e9-2a9f37ad7793
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2120\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      desc: {}
      limit:
        simple: '1'
      maxLastActivityDate: {}
      maxLastModifiedDate: {}
      minLastActivityDate: {}
      minLastModifiedDate: {}
      motivations: {}
      name: {}
      offset: {}
      origins: {}
      q:
        simple: google
      slug: {}
      sort: {}
      targetCountries: {}
      targetIndustries: {}
    separatecontext: false
    task:
      brand: ''
      description: Search known actors based on the given parameters. Dates are formatted
        as YYYY-MM-DD. Max date is taken automatically looking at end-of-day time.
        Origins, targetCountries, targetIndustries and motivations can all receive
        multiple values separated by ",". Offset is 0 based. Sort is field_name.order,
        field_name.order where order is either asc or desc.
      id: d9ae6ec4-2d15-41aa-895e-b3aecc0580e5
      iscommand: true
      name: Search known actors
      script: '|||cs-actors'
      type: regular
      version: -1
    taskid: d9ae6ec4-2d15-41aa-895e-b3aecc0580e5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2135,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
