id: Test_URLhaus
inputs: []
name: Test_URLhaus
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: d7616781-7931-4e6b-89b2-07382a4f84b9
      iscommand: false
      name: ''
      version: -1
    taskid: d7616781-7931-4e6b-89b2-07382a4f84b9
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 1555,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
      - '5'
      - '7'
      - '9'
      - '11'
      - '15'
      - '19'
      - '20'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: a0b420c8-fdff-44a4-8429-e807fd84df4a
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: a0b420c8-fdff-44a4-8429-e807fd84df4a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1555,\n    \"y\": 195\n  }\n}"
  '10':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Score
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: DBotScore.Indicator
                    operator: isEqualString
                    right:
                      value:
                        simple: google.com
                root: DBotScore
          operator: isEqualString
          right:
            value:
              simple: '0'
      label: 'yes'
    id: '10'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 729e90ca-1927-4cde-8c1c-fbf62eecca72
      iscommand: false
      name: verify context
      type: condition
      version: -1
    taskid: 729e90ca-1927-4cde-8c1c-fbf62eecca72
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 545\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quietmode: 0
    scriptarguments:
      file:
        simple: 01fa56184fcaa42b6ee1882787a34098c79898c182814774fd81dc18a6af0b01
      hash:
        simple: 01fa56184fcaa42b6ee1882787a34098c79898c182814774fd81dc18a6af0b01
      hash_type:
        simple: SHA256
      long: {}
      retries: {}
      threshold: {}
      wait: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: URLhaus
      description: Retrieve file information from URLhaus
      id: 983bea7f-3175-4c84-8642-e6abe02de307
      iscommand: true
      name: file - no data
      script: URLhaus|||file
      type: regular
      version: -1
    taskid: 983bea7f-3175-4c84-8642-e6abe02de307
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1770,\n    \"y\": 545\n  }\n}"
  '13':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: MD5
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: File.SHA256
                    operator: isEqualString
                    right:
                      value:
                        simple: 01fa56184fcaa42b6ee1882787a34098c79898c182814774fd81dc18a6af0b00
                root: File
          operator: isEqualString
          right:
            value:
              simple: 12c8aec5766ac3e6f26f2505e2f4a8f2
      label: 'yes'
    id: '13'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 8a9b8cee-79fe-46bf-8e2e-97d2f9cd2a9f
      iscommand: false
      name: verify context
      type: condition
      version: -1
    taskid: 8a9b8cee-79fe-46bf-8e2e-97d2f9cd2a9f
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 2200,\n    \"y\": 545\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    quietmode: 0
    scriptarguments:
      file:
        simple: 254ca6a7a7ef7f17d9884c4a86f88b5d5fd8fe5341c0996eaaf1d4bcb3b2337b
    separatecontext: false
    skipunavailable: false
    task:
      brand: URLhaus
      description: Download a malware sample from URLhaus
      id: 550a02a9-54c0-4a3e-8c56-cc874b9892f6
      iscommand: true
      name: urlhaus-download-sample - with data
      script: URLhaus|||urlhaus-download-sample
      type: regular
      version: -1
    taskid: 550a02a9-54c0-4a3e-8c56-cc874b9892f6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 2630,\n    \"y\": 370\n  }\n}"
  '17':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: MD5
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: File.SHA256
                    operator: isEqualString
                    right:
                      value:
                        simple: 254ca6a7a7ef7f17d9884c4a86f88b5d5fd8fe5341c0996eaaf1d4bcb3b2337b
                root: File
          operator: isEqualString
          right:
            value:
              simple: a820381c8acf07cfcb4d9b13498db71d
      label: 'yes'
    id: '17'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 67ca41db-b26b-4bf2-8d9e-25b300598fe6
      iscommand: false
      name: verify context
      type: condition
      version: -1
    taskid: 67ca41db-b26b-4bf2-8d9e-25b300598fe6
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 2630,\n    \"y\": 545\n  }\n}"
  '19':
    id: '19'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quietmode: 0
    scriptarguments:
      file:
        simple: 254ca6a7a7ef7f17d9884c4a86f88b5d5fd8fe5341c0996eaaf1d4bcb3b2337c
    separatecontext: false
    skipunavailable: false
    task:
      brand: URLhaus
      description: Download a malware sample from URLhaus
      id: 4bea44bb-3cd6-4bd2-819b-90831db4d9c9
      iscommand: true
      name: urlhaus-download-sample - w/o data
      script: URLhaus|||urlhaus-download-sample
      type: regular
      version: -1
    taskid: 4bea44bb-3cd6-4bd2-819b-90831db4d9c9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 3060,\n    \"y\": 545\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      long: {}
      retries: {}
      sampleSize: {}
      submitWait: {}
      threshold: {}
      url:
        simple: http://sskymedia.com/VMYB-ht_JAQo-gi/INV/99401FORPO/20673114777/US/Outstanding-Invoices/
      wait: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: URLhaus
      description: Retrieve URL information from URLhaus
      id: 070b3d4e-aa14-451e-8d56-2117e3a6eded
      iscommand: true
      name: url - with data
      script: URLhaus|||url
      type: regular
      version: -1
    taskid: 070b3d4e-aa14-451e-8d56-2117e3a6eded
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '20':
    id: '20'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    quietmode: 0
    scriptarguments:
      file:
        simple: 01fa56184fcaa42b6ee1882787a34098c79898c182814774fd81dc18a6af0b00
      hash:
        simple: 01fa56184fcaa42b6ee1882787a34098c79898c182814774fd81dc18a6af0b00
      hash_type:
        simple: SHA256
      long: {}
      retries: {}
      threshold: {}
      wait: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: URLhaus
      description: Retrieve file information from URLhaus
      id: e5c617a3-cd7a-4089-89a2-c42b8b159f93
      iscommand: true
      name: file - with data
      script: URLhaus|||file
      type: regular
      version: -1
    taskid: e5c617a3-cd7a-4089-89a2-c42b8b159f93
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 2200,\n    \"y\": 370\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Score
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: DBotScore.Indicator
                    operator: isEqualString
                    right:
                      value:
                        simple: http://sskymedia.com/VMYB-ht_JAQo-gi/INV/99401FORPO/20673114777/US/Outstanding-Invoices/
                root: DBotScore
          operator: isEqualString
          right:
            value:
              simple: '1'
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 19f3d24b-25c1-491f-8eed-770d22a67bf1
      iscommand: false
      name: verify context
      type: condition
      version: -1
    taskid: 19f3d24b-25c1-491f-8eed-770d22a67bf1
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 00285b1b-8c6e-42b9-8817-4720e3bde01f
      iscommand: false
      name: complete
      type: title
      version: -1
    taskid: 00285b1b-8c6e-42b9-8817-4720e3bde01f
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 1555,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      long: {}
      retries: {}
      sampleSize: {}
      submitWait: {}
      threshold: {}
      url:
        simple: http://gfrewdfsersfsfersfgergre.com
      wait: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: URLhaus
      description: Retrieve URL information from URLhaus
      id: a6a68e69-a32b-46c5-86a1-0ae8bc54e321
      iscommand: true
      name: url - nonexisting
      script: URLhaus|||url
      type: regular
      version: -1
    taskid: a6a68e69-a32b-46c5-86a1-0ae8bc54e321
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '6':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Score
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: DBotScore.Indicator
                    operator: isEqualString
                    right:
                      value:
                        simple: http://gfrewdfsersfsfersfgergre.com
                root: DBotScore
          operator: isEqualString
          right:
            value:
              simple: '0'
      label: 'yes'
    id: '6'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: fd8af1b1-c83c-4354-84fc-0547f13151b0
      iscommand: false
      name: verify context
      type: condition
      version: -1
    taskid: fd8af1b1-c83c-4354-84fc-0547f13151b0
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      domain:
        simple: vektorex.com
      fullResponse: {}
      long: {}
      retries: {}
      sampleSize: {}
      threshold: {}
      wait: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: URLhaus
      description: Retrieve domain information from URLhaus
      id: f2664a18-6b82-4dff-8b69-48e2c5a35f25
      iscommand: true
      name: domain - with data
      script: URLhaus|||domain
      type: regular
      version: -1
    taskid: f2664a18-6b82-4dff-8b69-48e2c5a35f25
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 370\n  }\n}"
  '8':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Score
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: DBotScore.Indicator
                    operator: isEqualString
                    right:
                      value:
                        simple: vektorex.com
                root: DBotScore
          operator: isEqualString
          right:
            value:
              simple: '1'
      label: 'yes'
    id: '8'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 9770aa46-145f-4da5-824c-5415e877e9ab
      iscommand: false
      name: verify context
      type: condition
      version: -1
    taskid: 9770aa46-145f-4da5-824c-5415e877e9ab
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 545\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    quietmode: 0
    scriptarguments:
      domain:
        simple: google.com
      fullResponse: {}
      long: {}
      retries: {}
      sampleSize: {}
      threshold: {}
      wait: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: URLhaus
      description: Retrieve domain information from URLhaus
      id: a295b127-06e6-4adb-80f2-1a9f70dabbd4
      iscommand: true
      name: domain - no data
      script: URLhaus|||domain
      type: regular
      version: -1
    taskid: a295b127-06e6-4adb-80f2-1a9f70dabbd4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 370\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 735,\n      \"width\": 3390,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
