id: Tufin-Test
inputs: []
name: Tufin-Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 470da016-9270-40e4-8f9f-48f9b144c741
      iscommand: false
      name: ''
      version: -1
    taskid: 470da016-9270-40e4-8f9f-48f9b144c741
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
    separatecontext: false
    task:
      brand: ''
      id: ac788cb4-07b4-43e2-8fba-91e0e3b6b39f
      iscommand: true
      name: DeleteContext
      script: DeleteContext
      type: regular
      version: -1
    taskid: ac788cb4-07b4-43e2-8fba-91e0e3b6b39f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 200\n  }\n}"
  '10':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Tufin.Zones.ID
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: Tufin.Zones.Name
          operator: isNotEmpty
      label: 'yes'
    id: '10'
    ignoreworker: false
    nexttasks:
      'yes':
      - '11'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 80afe505-7ced-408d-870f-1eb5c44779f4
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 80afe505-7ced-408d-870f-1eb5c44779f4
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2000\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      action: {}
      comment: {}
      destination: {}
      port: {}
      priority:
        simple: High
      protocol: {}
      request-type:
        simple: Server Decommission Request
      source:
        simple: 192.168.1.1
      subject:
        simple: Test Server Decomm
    separatecontext: false
    task:
      brand: ''
      id: b4ae7887-7716-4e59-8cef-f6fa81e9dc13
      iscommand: true
      name: tufin-submit-change-request
      script: '|||tufin-submit-change-request'
      type: regular
      version: -1
    taskid: b4ae7887-7716-4e59-8cef-f6fa81e9dc13
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2200\n  }\n}"
  '12':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Tufin.Request.Status
          operator: isNotEmpty
      label: 'yes'
    id: '12'
    ignoreworker: false
    nexttasks:
      'yes':
      - '13'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 82b70fb8-a70e-404a-8fde-2e1396de7911
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 82b70fb8-a70e-404a-8fde-2e1396de7911
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2400\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    scriptarguments:
      ip: {}
      model: {}
      name: {}
      vendor:
        simple: Cisco
    separatecontext: false
    task:
      brand: ''
      id: aa0fbc4b-67d7-47f3-8a3b-bcad6ce142a9
      iscommand: true
      name: tufin-search-devices
      script: '|||tufin-search-devices'
      type: regular
      version: -1
    taskid: aa0fbc4b-67d7-47f3-8a3b-bcad6ce142a9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2600\n  }\n}"
  '14':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Tufin.Devices.ID
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: Tufin.Devices.Name
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: Tufin.Devices.Vendor
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: Tufin.Devices.Model
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: Tufin.Devices.IP
          operator: isNotEmpty
      label: 'yes'
    id: '14'
    ignoreworker: false
    nexttasks:
      'yes':
      - '15'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 7b5c5cd4-76be-44b5-88c7-74d24117ff19
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 7b5c5cd4-76be-44b5-88c7-74d24117ff19
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2800\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    scriptarguments:
      ticket-id:
        simple: '250'
    separatecontext: false
    task:
      brand: ''
      id: e8c1e2f0-c39e-4c3b-89d2-c818d855ba45
      iscommand: true
      name: tufin-get-change-info
      script: '|||tufin-get-change-info'
      type: regular
      version: -1
    taskid: e8c1e2f0-c39e-4c3b-89d2-c818d855ba45
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3000\n  }\n}"
  '16':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Tufin.Tickets.ID
          operator: isNotEmpty
      label: 'yes'
    id: '16'
    ignoreworker: false
    nexttasks:
      'yes':
      - '17'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d18150a2-bc69-44e6-862d-4ca632b73499
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: d18150a2-bc69-44e6-862d-4ca632b73499
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3200\n  }\n}"
  '17':
    id: '17'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '18'
    note: false
    scriptarguments:
      name:
        simple: 3Rivers
    separatecontext: false
    task:
      brand: ''
      id: 2c0fc74a-0db8-48d0-8d6b-8e7802278b05
      iscommand: true
      name: tufin-search-applications
      script: '|||tufin-search-applications'
      type: regular
      version: -1
    taskid: 2c0fc74a-0db8-48d0-8d6b-8e7802278b05
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3400\n  }\n}"
  '18':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Tufin.Apps.ID
          operator: isNotEmpty
      label: 'yes'
    id: '18'
    ignoreworker: false
    nexttasks:
      'yes':
      - '19'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: b3dabf60-aea9-4dee-89c1-1cf2e0161c0b
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: b3dabf60-aea9-4dee-89c1-1cf2e0161c0b
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3600\n  }\n}"
  '19':
    id: '19'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '20'
    note: false
    scriptarguments:
      application-id:
        simple: ${Tufin.Apps.ID}
    separatecontext: false
    task:
      brand: ''
      id: 4857b87c-c02f-4dd5-85d4-427ed4ccc1fd
      iscommand: true
      name: tufin-search-application-connections
      script: '|||tufin-search-application-connections'
      type: regular
      version: -1
    taskid: 4857b87c-c02f-4dd5-85d4-427ed4ccc1fd
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3800\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      destination:
        simple: 10.2.2.0/24
      service: {}
      source:
        simple: 192.168.60.0/24
    separatecontext: false
    task:
      brand: ''
      id: 4a89416c-2039-4490-8403-503886696062
      iscommand: true
      name: tufin-search-topology
      script: '|||tufin-search-topology'
      type: regular
      version: -1
    taskid: 4a89416c-2039-4490-8403-503886696062
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 400\n  }\n}"
  '20':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Tufin.Apps.Connections.ID
          operator: isNotEmpty
      label: 'yes'
    id: '20'
    ignoreworker: false
    nexttasks:
      'yes':
      - '21'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 228fff16-8d5f-4522-8132-707935cf4cc8
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 228fff16-8d5f-4522-8132-707935cf4cc8
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 4000\n  }\n}"
  '21':
    id: '21'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 72fb7bb1-a4bd-4408-895c-9d3a5c79dc13
      iscommand: false
      name: Test Done
      type: title
      version: -1
    taskid: 72fb7bb1-a4bd-4408-895c-9d3a5c79dc13
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 4200\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Tufin.Topology.TrafficDevices
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              simple: Tufin.Topology.TrafficAllowed
          operator: isFalse
        - left:
            iscontext: true
            value:
              simple: Tufin.Topology.TrafficAllowed
          operator: isTrue
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 99c47d54-3256-43ad-8074-699d04dec2de
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 99c47d54-3256-43ad-8074-699d04dec2de
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 610\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      destination:
        simple: 10.2.2.0/24
      service: {}
      source:
        simple: 192.168.60.0/24
    separatecontext: false
    task:
      brand: ''
      id: a52d31f8-1e47-4946-8a08-64aa17bd8b20
      iscommand: true
      name: tufin-search-topology-image
      script: '|||tufin-search-topology-image'
      type: regular
      version: -1
    taskid: a52d31f8-1e47-4946-8a08-64aa17bd8b20
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 800\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      ip:
        simple: 10.3.3.3
    separatecontext: false
    task:
      brand: ''
      id: b0c57784-2e89-4b17-8d8f-b22d65e33efb
      iscommand: true
      name: tufin-object-resolve
      script: '|||tufin-object-resolve'
      type: regular
      version: -1
    taskid: b0c57784-2e89-4b17-8d8f-b22d65e33efb
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1000\n  }\n}"
  '6':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Tufin.ObjectResolve.NumberOfObjects
          operator: isNotEmpty
      label: 'yes'
    id: '6'
    ignoreworker: false
    nexttasks:
      'yes':
      - '7'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 42d3b192-75a5-4a3d-81dc-bc1191edb401
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 42d3b192-75a5-4a3d-81dc-bc1191edb401
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1200\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      search:
        simple: 1.1.1.1
    separatecontext: false
    task:
      brand: ''
      id: e0354a2e-1119-45e6-8a84-3d914995aa35
      iscommand: true
      name: tufin-policy-search
      script: '|||tufin-policy-search'
      type: regular
      version: -1
    taskid: e0354a2e-1119-45e6-8a84-3d914995aa35
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1400\n  }\n}"
  '8':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Tufin.Policysearch.NumberRulesFound
          operator: isNotEmpty
      label: 'yes'
    id: '8'
    ignoreworker: false
    nexttasks:
      'yes':
      - '9'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 62433da2-7a53-46ff-813b-4e7f1b2acaa7
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 62433da2-7a53-46ff-813b-4e7f1b2acaa7
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1600\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      ip:
        simple: 10.10.12.1
    separatecontext: false
    task:
      brand: ''
      id: 326042bf-fcf6-4c2d-8c2e-bd044c3ba109
      iscommand: true
      name: tufin-get-zone-for-ip
      script: '|||tufin-get-zone-for-ip'
      type: regular
      version: -1
    taskid: 326042bf-fcf6-4c2d-8c2e-bd044c3ba109
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1790\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 4215,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
