description: 'Returns a file sample to the war-room from a path on an endpoint using
  one or more integrations


  inputs:

  * UseD2 - if "True", use Demisto Dissolvable Agent (D2) to return the file (default:
  False)'
fromversion: 3.5.0
id: get_file_sample_from_path_-_generic
inputs:
- description: ''
  key: UseD2
  required: false
  value:
    simple: 'no'
- description: ''
  key: Hostname
  required: false
  value:
    simple: ${Endpoint.Hostname}
- description: ''
  key: Path
  required: false
  value:
    simple: ${File.Path}
name: Get File Sample From Path - Generic
outputs:
- contextPath: File
  description: The file to sample.
  type: unknown
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 5d887731-fb71-4226-872c-a9e8dbddac42
      iscommand: false
      name: ''
      version: -1
    taskid: 5d887731-fb71-4226-872c-a9e8dbddac42
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.UseD2
          operator: string.isEqual
          right:
            value:
              simple: 'yes'
      label: 'yes'
    id: '1'
    nexttasks:
      '#default#':
      - '11'
      'yes':
      - '10'
    scriptarguments:
      left:
        simple: ${inputs.UseD2}
      right:
        simple: 'True'
    separatecontext: false
    task:
      brand: ''
      description: Yes if we want to use D2 agent to get the file
      id: 8adb1ff3-5400-4f88-8a2b-4511ae8303f5
      iscommand: false
      name: Use D2 agent?
      type: condition
      version: -1
    taskid: 8adb1ff3-5400-4f88-8a2b-4511ae8303f5
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '8'
    scriptarguments:
      Credentials:
        simple: Admin
      Hostname:
        simple: ${Endpoint.Hostname}
      Path:
        simple: ${File.Path}
    separatecontext: false
    task:
      brand: ''
      description: 'Returns a file sample to the war-room from a path on an endpoint
        using Demisto Dissolvable Agent (D2)


        Input:

        * Credentials - credentials to use when trying to deploy Demisto Dissolvable
        Agent (D2)  (default: Admin)

        * ${Endpoint.Hostname} - deploy agent on target endpoint

        * ${File.Path} - file''s path to collect'
      id: 487eeea9-469f-4725-8695-e25a6ce9c0fc
      iscommand: false
      name: Get File Sample From Path - D2
      playbookName: Get File Sample From Path - D2
      type: playbook
      version: -1
    taskid: 487eeea9-469f-4725-8695-e25a6ce9c0fc
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 1,\n    \"y\": 355\n  }\n}"
  '11':
    id: '11'
    nexttasks:
      '#none#':
      - '12'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 33162da0-6e16-4324-8e6e-bcbd0e74f463
      iscommand: false
      name: Use 3rd party products
      type: title
      version: -1
    taskid: 33162da0-6e16-4324-8e6e-bcbd0e74f463
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '12':
    id: '12'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '8'
    scriptarguments:
      Hostname:
        simple: ${inputs.Hostname}
      Path:
        simple: ${inputs.Path}
    separatecontext: true
    task:
      brand: ''
      description: Returns a file sample to the war-room from a path on an endpoint
        using Carbon Black Enterprise Response
      id: 6689a943-ee94-437a-868b-0c6971de86f4
      iscommand: false
      name: Get File Sample From Path - Carbon Black Enterprise Response
      playbookName: Get File Sample From Path - Carbon Black Enterprise Response
      type: playbook
      version: -1
    taskid: 6689a943-ee94-437a-868b-0c6971de86f4
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 516\n  }\n}"
  '8':
    id: '8'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: f81d6908-8ce9-452b-8dde-689f44256933
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: f81d6908-8ce9-452b-8dde-689f44256933
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 690\n  }\n}"
tests:
- No Test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 705,\n      \"width\": 859,\n      \"x\": 1,\n      \"y\": 50\n\
  \    }\n  }\n}"
