description: 'This playbook blocks malicious usernames using all integrations that
  you have enabled.


  Supported integrations for this playbook:

  * Active Directory

  * PAN-OS - This requires PAN-OS 9.1 or higher.'
fromversion: 4.0.0
id: block_account_-_generic
inputs:
- description: Array of malicious usernames to block.
  key: Username
  required: false
  value: {}
- description: PAN-OS Tag name to apply to the username that you want to block.
  key: Tag
  required: false
  value: {}
name: Block Account - Generic
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: b95110b7-ba18-42a5-87ad-c5d37915401c
      iscommand: false
      name: ''
      version: -1
    taskid: b95110b7-ba18-42a5-87ad-c5d37915401c
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 20\n  }\n}"
  '12':
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: activedir
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: 'yes'
    id: '12'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '13'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: 'Verify that there is a valid instance of Active Directory enabled.

        '
      id: 5da07472-33bb-451d-8562-365e05f456ec
      iscommand: false
      name: Is Active Directory enabled?
      type: condition
      version: -1
    taskid: 5da07472-33bb-451d-8562-365e05f456ec
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 230,\n    \"y\": 505\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      base-dn: {}
      username:
        complex:
          root: inputs.Username
    separatecontext: false
    task:
      brand: activedir
      description: Disable the account using Active Directory.
      id: c8b9285e-4d21-4070-89b6-33c611531812
      iscommand: true
      name: Disable account in active directory
      script: activedir|||ad-disable-account
      type: regular
      version: -1
    taskid: c8b9285e-4d21-4070-89b6-33c611531812
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 320,\n    \"y\": 730\n  }\n}"
  '14':
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: panorama
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: 'yes'
    id: '14'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '16'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: 'Verify that there is a valid instance of PAN-OS enabled.

        '
      id: 7b9a0521-f530-41f2-8e6c-06df1f72ad87
      iscommand: false
      name: Is PAN-OS enabled?
      type: condition
      version: -1
    taskid: 7b9a0521-f530-41f2-8e6c-06df1f72ad87
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 770,\n    \"y\": 505\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      Users:
        simple: ${inputs.Username}
      tag:
        simple: ${inputs.Tag}
    separatecontext: false
    task:
      brand: ''
      description: Apply a tag to a user.
      id: 9da1c44c-5522-421f-8f84-a70123600e4a
      iscommand: true
      name: PAN-OS - Register Tag to User
      script: '|||panorama-register-user-tag'
      type: regular
      version: -1
    taskid: 9da1c44c-5522-421f-8f84-a70123600e4a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 900,\n    \"y\": 1000\n  }\n}"
  '16':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Tag
          operator: isExists
      label: 'yes'
    id: '16'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '15'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Verify that the playbook input includes at least one tag to apply
        to the user.
      id: 06dfb070-8751-4cbc-8dcd-b7ffd39ca2cc
      iscommand: false
      name: Is there a Tag name to register?
      type: condition
      version: -1
    taskid: 06dfb070-8751-4cbc-8dcd-b7ffd39ca2cc
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 900,\n    \"y\": 730\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 1808d949-f921-4957-8796-7bbedd822ad9
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 1808d949-f921-4957-8796-7bbedd822ad9
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 0,\n    \"y\": 1180\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
      - '14'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 0b958771-7e06-4239-899f-f7d133be6938
      iscommand: false
      name: Block accounts
      type: title
      version: -1
    taskid: 0b958771-7e06-4239-899f-f7d133be6938
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 250,\n    \"y\": 360\n  }\n}"
  '8':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Username
          operator: isExists
      label: 'yes'
    id: '8'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Verify that the playbook input includes at least one username to
        block.
      id: 2c5a17dd-e019-4e20-8f5b-4333678a26e0
      iscommand: false
      name: Is there a username to block?
      type: condition
      version: -1
    taskid: 2c5a17dd-e019-4e20-8f5b-4333678a26e0
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 165\n  }\n}"
tests:
- block_indicators_-_generic_-_test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"12_2_#default#\": 0.1,\n    \"14_16_yes\"\
  : 0.6,\n    \"14_2_#default#\": 0.1,\n    \"16_15_yes\": 0.71,\n    \"16_2_#default#\"\
  : 0.1,\n    \"8_2_#default#\": 0.16\n  },\n  \"paper\": {\n    \"dimensions\": {\n\
  \      \"height\": 1225,\n      \"width\": 1280,\n      \"x\": 0,\n      \"y\":\
  \ 20\n    }\n  }\n}"
