description: Test playbook for TAXII Feed
fromversion: 4.1.0
id: TAXII_Feed_Test
inputs: []
name: TAXII_Feed_Test
outputs: []
starttaskid: '0'
system: true
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 988653ca-17d0-4f6b-8ef3-209f1a45d3de
      iscommand: false
      name: ''
      version: -1
    taskid: 988653ca-17d0-4f6b-8ef3-209f1a45d3de
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      initial_interval:
        simple: 4 days
      limit:
        simple: '10'
    separatecontext: false
    skipunavailable: false
    task:
      brand: TAXIIFeed
      description: Get the feed indicators.
      id: 31e30a66-72b2-48d3-8dc2-cc54e09ad486
      iscommand: true
      name: Get Indicators
      script: TAXIIFeed|||get-indicators
      type: regular
      version: -1
    taskid: 31e30a66-72b2-48d3-8dc2-cc54e09ad486
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '2':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Indicator.Value
                root: TAXII
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Indicator.Type
                root: TAXII
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Indicator.Rawjson.type
                root: TAXII
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Indicator.Rawjson.value
                root: TAXII
          operator: isExists
      label: 'yes'
    id: '2'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '6'
      'yes':
      - '3'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Asserts output.
      id: 5402c5e6-14ae-4cd6-810e-ab992cb16115
      iscommand: false
      name: Assert Output
      type: condition
      version: -1
    taskid: 5402c5e6-14ae-4cd6-810e-ab992cb16115
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Done
      id: f1521e9e-4b28-43b9-8e9e-ab7df821ee8a
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: f1521e9e-4b28-43b9-8e9e-ab7df821ee8a
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context.
      id: 388b3a2c-ead7-4e3a-8765-834101867a84
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 388b3a2c-ead7-4e3a-8765-834101867a84
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    scriptarguments:
      accounttype: {}
      actor: {}
      admincountry: {}
      adminemail: {}
      adminname: {}
      adminphone: {}
      asn: {}
      associatedfilenames: {}
      associations: {}
      biosversion: {}
      creationdate: {}
      customFields: {}
      cvedescription: {}
      cvemodified: {}
      cvss: {}
      description: {}
      detectionengines: {}
      devicemodel: {}
      dhcpserver: {}
      displayname: {}
      dns: {}
      domainname: {}
      domainstatus: {}
      emailaddress: {}
      employeehealthstatus: {}
      employeeresponsestatus: {}
      entryid: {}
      expirationdate: {}
      fileextension: {}
      filetype: {}
      firstname: {}
      firstseenbysource: {}
      geocountry: {}
      geolocation: {}
      groups: {}
      hostname: {}
      imphash: {}
      indicatoridentification: {}
      internal: {}
      ipaddress: {}
      jobtitle: {}
      lastname: {}
      lastseenbysource: {}
      macaddress: {}
      malwarefamily: {}
      md5: {}
      memory: {}
      merge: {}
      mitrealiases: {}
      mitrecontributors: {}
      mitredatasources: {}
      mitredefensebypassed: {}
      mitredescription: {}
      mitredetection: {}
      mitreextendedaliases: {}
      mitreexternalreferences: {}
      mitreid: {}
      mitreimpacttype: {}
      mitrekillchainphases: {}
      mitrelabels: {}
      mitrename: {}
      mitrepermissionsrequired: {}
      mitreplatforms: {}
      mitresystemrequirements: {}
      mitretype: {}
      mitreversion: {}
      name: {}
      namefield: {}
      nameservers: {}
      office365category: {}
      office365expressroute: {}
      office365required: {}
      operatingsystem: {}
      operatingsystemversion: {}
      organization: {}
      organizationalunitou: {}
      osversion: {}
      path: {}
      port: {}
      positivedetections: {}
      processor: {}
      processors: {}
      published: {}
      quarantined: {}
      recordedfutureevidencedetails: {}
      region: {}
      registrantcountry: {}
      registrantemail: {}
      registrantname: {}
      registrantphone: {}
      registrarabuseemail: {}
      registrarabusephone: {}
      registrarname: {}
      relatedIncidents: {}
      reportedby: {}
      reputation: {}
      seenNow: {}
      service: {}
      sha1: {}
      sha256: {}
      sha512: {}
      signatureauthentihash: {}
      signaturecopyright: {}
      signaturedescription: {}
      signaturefileversion: {}
      signatureinternalname: {}
      signed: {}
      size: {}
      source:
        simple: taxiitest
      sourceTimeStamp: {}
      sourceoriginalseverity: {}
      ssdeep: {}
      subdomains: {}
      tags: {}
      threattypes: {}
      trafficlightprotocol: {}
      type:
        simple: URL
      updateddate: {}
      username: {}
      value:
        simple: www.demisto.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Change the properties of an indicator
      id: 55fe4210-fa84-4b08-82fe-12134c9e72d0
      iscommand: true
      name: createNewIndicator
      script: Builtin|||createNewIndicator
      type: regular
      version: -1
    taskid: 55fe4210-fa84-4b08-82fe-12134c9e72d0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: '5'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Sleep for X seconds
      id: 215c092f-0c67-4e43-821d-5582b78833b2
      iscommand: false
      name: Sleep
      scriptName: Sleep
      type: regular
      version: -1
    taskid: 215c092f-0c67-4e43-821d-5582b78833b2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 350,\n    \"y\": 890\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      initial_interval:
        simple: 4 days
      limit:
        simple: '10'
    separatecontext: false
    skipunavailable: false
    task:
      brand: TAXIIFeed
      description: Get the feed indicators.
      id: 6d990d13-a36a-429d-8520-fd09a5f7cc6b
      iscommand: true
      name: Get Indicators
      script: TAXIIFeed|||get-indicators
      type: regular
      version: -1
    taskid: 6d990d13-a36a-429d-8520-fd09a5f7cc6b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 350,\n    \"y\": 1070\n  }\n}"
  '8':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Indicator.Value
                root: TAXII
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Indicator.Type
                root: TAXII
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Indicator.Rawjson.type
                root: TAXII
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Indicator.Rawjson.value
                root: TAXII
          operator: isExists
      label: 'yes'
    id: '8'
    ignoreworker: false
    nexttasks:
      'yes':
      - '3'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Asserts output.
      id: 7a0a42b7-e339-4e18-8c75-86f705bedc16
      iscommand: false
      name: Assert Output
      type: condition
      version: -1
    taskid: 7a0a42b7-e339-4e18-8c75-86f705bedc16
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 350,\n    \"y\": 1245\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1435,\n      \"width\": 680,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
