id: Detonate File - ANYRUN - Test
inputs: []
name: Detonate File - ANYRUN - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: bb65f935-184a-4f62-8e8c-915ba55101fa
      iscommand: false
      name: ''
      version: -1
    taskid: bb65f935-184a-4f62-8e8c-915ba55101fa
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      id: 40d4dcc9-16f1-47bb-8c17-8334d4e77342
      iscommand: false
      name: Start fresh
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 40d4dcc9-16f1-47bb-8c17-8334d4e77342
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    separatecontext: true
    task:
      brand: ''
      id: 7176abd1-ae8d-4806-8c7c-bf13903c1694
      iscommand: false
      name: Detonate File - ANYRUN
      playbookName: Detonate File - ANYRUN
      type: playbook
      version: -1
    taskid: 7176abd1-ae8d-4806-8c7c-bf13903c1694
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: f7c5a3a9-b513-4ea2-864c-cfe5420b9e38
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: f7c5a3a9-b513-4ea2-864c-cfe5420b9e38
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      body: {}
      filename:
        simple: test_file.pdf
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://raw.githubusercontent.com/demisto/content/master/TestData/pdfworking.pdf
      username: {}
    separatecontext: false
    task:
      brand: ''
      id: 44dbbaae-6174-4c1e-8dd5-e79ef2c59f6c
      iscommand: false
      name: Create sample file
      scriptName: http
      type: regular
      version: -1
    taskid: 44dbbaae-6174-4c1e-8dd5-e79ef2c59f6c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 735,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
