id: Detonate File From URL - ANYRUN - Test
inputs: []
name: Detonate File From URL - ANYRUN - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 65a8b522-11bf-4dca-890e-0fc61cdc3852
      iscommand: false
      name: ''
      version: -1
    taskid: 65a8b522-11bf-4dca-890e-0fc61cdc3852
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: b858cb72-1de4-4f27-8e89-67e729b4304f
      iscommand: false
      name: Start Fresh
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: b858cb72-1de4-4f27-8e89-67e729b4304f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      append: {}
      key:
        simple: URL.Data
      value:
        simple: https://www.python.org/downloads/release/python-373/
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 34668430-83bc-4ce8-88be-05737b7b6645
      iscommand: false
      name: Set URL for File Download
      scriptName: Set
      type: regular
      version: -1
    taskid: 34668430-83bc-4ce8-88be-05737b7b6645
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    separatecontext: true
    task:
      brand: ''
      id: 1b0d1800-9bfe-486d-84c5-b8c6a736d2c2
      iscommand: false
      name: Detonate File From URL - ANYRUN
      playbookName: Detonate File From URL - ANYRUN
      type: playbook
      version: -1
    taskid: 1b0d1800-9bfe-486d-84c5-b8c6a736d2c2
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 8f393862-0c9d-46b4-89a0-afc033fb523f
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 8f393862-0c9d-46b4-89a0-afc033fb523f
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 735,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
