id: Detonate URL - ANYRUN - Test
inputs: []
name: Detonate URL - ANYRUN - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 248bd6ce-5cc0-4382-8989-cf6ac3feb46c
      iscommand: false
      name: ''
      version: -1
    taskid: 248bd6ce-5cc0-4382-8989-cf6ac3feb46c
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      append: {}
      key:
        simple: URL.Data
      value:
        simple: https://www.demisto.com
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 0b881e68-330b-4f99-8f33-5fc9279317fb
      iscommand: false
      name: Set
      scriptName: Set
      type: regular
      version: -1
    taskid: 0b881e68-330b-4f99-8f33-5fc9279317fb
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    separatecontext: true
    task:
      brand: ''
      id: 8b84aacf-859e-40e6-8a32-aba6235fb93a
      iscommand: false
      name: Detonate URL - ANYRUN
      playbookName: Detonate URL - ANYRUN
      type: playbook
      version: -1
    taskid: 8b84aacf-859e-40e6-8a32-aba6235fb93a
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: cb75cebc-5bf4-4f2f-8d2e-4530cc730701
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: cb75cebc-5bf4-4f2f-8d2e-4530cc730701
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: e110d4c9-2b47-4ec8-8f6e-3632b039742c
      iscommand: false
      name: Start Fresh
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: e110d4c9-2b47-4ec8-8f6e-3632b039742c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 735,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
