description: A test for email address enrichment. Currently, due to issues, the test
  does not check all domain squatting results or whether the email addresses were
  detected as internal or external.
fromversion: 4.1.0
id: Email Address Enrichment - Generic v2.1 - Test
inputs:
- description: A comma-separated list of internal domains
  key: InternalDomains
  required: false
  value:
    simple: demisto.com, demistodev.com, demisto.ninja
name: Email Address Enrichment - Generic v2.1 - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 22a2e035-f857-417e-81cb-308b8a9dfec8
      iscommand: false
      name: ''
      version: -1
    taskid: 22a2e035-f857-417e-81cb-308b8a9dfec8
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '5'
      - '9'
    note: false
    scriptarguments:
      Domain:
        complex:
          accessor: Name
          root: Domain
          transformers:
          - operator: uniq
      Email:
        complex:
          accessor: Email.Address
          root: Account
          transformers:
          - operator: uniq
      InternalDomains:
        complex:
          root: inputs.InternalDomains
          transformers:
          - operator: uniq
    separatecontext: true
    task:
      brand: ''
      description: ''
      id: c053cdba-d7b4-4029-88e1-ecf3bef316a6
      iscommand: false
      name: Email Address Enrichment - Generic v2.1
      playbookName: Email Address Enrichment - Generic v2.1
      type: playbook
      version: -1
    taskid: c053cdba-d7b4-4029-88e1-ecf3bef316a6
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 550\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    reputationcalc: 1
    scriptarguments:
      append: {}
      key:
        simple: Domain.Name
      value:
        simple: domainthatdoesntexis.co.uk
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 1fa00f4b-9c90-4068-865e-dd35742dbcef
      iscommand: false
      name: Set domains to context
      scriptName: Set
      type: regular
      version: -1
    taskid: 1fa00f4b-9c90-4068-865e-dd35742dbcef
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 230,\n    \"y\": 360\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    reputationcalc: 1
    scriptarguments:
      append: {}
      key:
        simple: Account.Email.Address
      value:
        simple: '["geverwithnoname@domainthatdoesntexist.co.uk", "soso@demisto.com",
          "koko@demisto.com", "user1@domain.com","donotdelete@demisto.ninja"]'
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 9f1e4074-58dc-4393-8d9a-d640da6ca203
      iscommand: false
      name: Set email addresses to context
      scriptName: Set
      type: regular
      version: -1
    taskid: 9f1e4074-58dc-4393-8d9a-d640da6ca203
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 670,\n    \"y\": 360\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
      - '3'
    note: false
    reputationcalc: 1
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Deletes context for a fresh start of this test.
      id: 43deb7e7-c488-46ec-8408-d1a303a4b563
      iscommand: false
      name: Delete context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 43deb7e7-c488-46ec-8408-d1a303a4b563
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 180\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Score
                root: DBotScore
          operator: isEqualNumber
          right:
            value:
              simple: '2'
      label: 'yes'
    id: '5'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '7'
      'yes':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d9227bdc-084f-4652-8a86-10659a4c8fe4
      iscommand: false
      name: Was there a case of domain squatting?
      type: condition
      version: -1
    taskid: d9227bdc-084f-4652-8a86-10659a4c8fe4
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 230,\n    \"y\": 740\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 02372e49-2953-4bed-844a-ed4c5011234f
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 02372e49-2953-4bed-844a-ed4c5011234f
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 460,\n    \"y\": 1170\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    reputationcalc: 1
    scriptarguments:
      message:
        simple: Domain squatting should have been detected, but wasn't, or the user
          was not enriched using Active Directory.
    separatecontext: false
    task:
      brand: ''
      description: Fail the test if domain squatting was not detected.
      id: 2d80769c-f001-4237-88e6-dfc63763f597
      iscommand: false
      name: Make test fail
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 2d80769c-f001-4237-88e6-dfc63763f597
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 460,\n    \"y\": 940\n  }\n}"
  '9':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Account.ID
          operator: isExists
      label: 'yes'
    id: '9'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '7'
      'yes':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 2775a16e-1c15-4e62-853a-b5e87b62c797
      iscommand: false
      name: Was internal email enriched using Active Directory?
      type: condition
      version: -1
    taskid: 2775a16e-1c15-4e62-853a-b5e87b62c797
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 670,\n    \"y\": 740\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"5_6_yes\": 0.57,\n    \"5_7_#default#\"\
  : 0.42,\n    \"9_6_yes\": 0.58,\n    \"9_7_#default#\": 0.43\n  },\n  \"paper\"\
  : {\n    \"dimensions\": {\n      \"height\": 1185,\n      \"width\": 820,\n   \
  \   \"x\": 230,\n      \"y\": 50\n    }\n  }\n}"
