description: A test for the File Enrichment - Generic v2 playbook.
fromversion: 4.1.0
id: File Enrichment - Generic v2 - Test
inputs: []
name: File Enrichment - Generic v2 - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 10c4378f-44df-4293-8f72-874b0495a27a
      iscommand: false
      name: ''
      version: -1
    taskid: 10c4378f-44df-4293-8f72-874b0495a27a
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    reputationcalc: 1
    scriptarguments:
      append:
        simple: 'true'
      key:
        simple: File.MD5
      value:
        simple: 3f066dd1f1da052248aed5abc4a0c6a1
    separatecontext: false
    task:
      brand: ''
      id: a39113bf-3b59-4935-84a4-ca700c708154
      iscommand: false
      name: Add file MD5 to context
      scriptName: Set
      type: regular
      version: -1
    taskid: a39113bf-3b59-4935-84a4-ca700c708154
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    reputationcalc: 1
    scriptarguments:
      message:
        simple: Not all DBotScore context fields were created.
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: 60f8b33c-5629-4912-8ef0-9c465db61356
      iscommand: false
      name: Make test fail
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 60f8b33c-5629-4912-8ef0-9c465db61356
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 410,\n    \"y\": 1070\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    reputationcalc: 1
    scriptarguments:
      append:
        simple: 'true'
      key:
        simple: File.SHA1
      value:
        simple: 795b33795f0308fc5e83abc2daff1d7129dfa400
    separatecontext: false
    task:
      brand: ''
      id: 65c19517-7c8f-4064-8fb6-6ef179bed34b
      iscommand: false
      name: Add file SHA1 to context
      scriptName: Set
      type: regular
      version: -1
    taskid: 65c19517-7c8f-4064-8fb6-6ef179bed34b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    reputationcalc: 1
    scriptarguments:
      append:
        simple: 'true'
      key:
        simple: File.SHA256
      value:
        simple: afd3b729cf99fb9ea441f42862a4835d1d6eeb36ee535f9b206e3a00382c972e
    separatecontext: false
    task:
      brand: ''
      id: 8f11095f-844f-441d-8ec3-f849cdb6d23a
      iscommand: false
      name: Add file SHA256 to context
      scriptName: Set
      type: regular
      version: -1
    taskid: 8f11095f-844f-441d-8ec3-f849cdb6d23a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '7':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Indicator
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Type
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Vendor
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Score
          operator: isExists
      label: 'yes'
    id: '7'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '10'
      'yes':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Checks if the expected DBotScore fields were populated in the context.
      id: f509768d-6029-4bd0-8f41-b96be360aff9
      iscommand: false
      name: Verify DBotScore context fields
      type: condition
      version: -1
    taskid: f509768d-6029-4bd0-8f41-b96be360aff9
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: f083cfd3-28ab-4f13-8692-32ae498df885
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: f083cfd3-28ab-4f13-8692-32ae498df885
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1240\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      MD5:
        complex:
          accessor: MD5
          root: File
      SHA1:
        complex:
          accessor: SHA1
          root: File
      SHA256:
        complex:
          accessor: SHA256
          root: File
    separatecontext: true
    task:
      brand: ''
      description: ''
      id: 144f05c5-0c6b-45a4-8c74-46e471288276
      iscommand: false
      name: File Enrichment - Generic v2
      playbookName: File Enrichment - Generic v2
      type: playbook
      version: -1
    taskid: 144f05c5-0c6b-45a4-8c74-46e471288276
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1255,\n      \"width\": 740,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
