fromversion: 4.1.0
id: IP Enrichment - Generic v2 - Test
inputs:
- description: Determines whether the IP Enrichment - Generic playbook should convert
    IP addresses to hostnames using a DNS query. You can set this to either True or
    False.
  key: ResolveIP
  required: false
  value:
    simple: 'True'
name: IP Enrichment - Generic v2 - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: e80130b8-9f8e-4704-87d8-2c6919d7b7c0
      iscommand: false
      name: ''
      version: -1
    taskid: e80130b8-9f8e-4704-87d8-2c6919d7b7c0
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 10\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    reputationcalc: 1
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Deletes the context of the incident to start the test with no unnecessary
        data.
      id: 48651a1d-b6fd-4816-80d9-a8e5a45899e9
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 48651a1d-b6fd-4816-80d9-a8e5a45899e9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 150\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '5'
      - '6'
      - '7'
    note: false
    scriptarguments:
      IP:
        complex:
          accessor: Address
          root: IP
          transformers:
          - operator: uniq
      InternalRange: {}
      ResolveIP:
        complex:
          root: inputs.ResolveIP
    separatecontext: true
    task:
      brand: ''
      description: 'Enrich IP using one or more integrations.


        IP enrichment includes:

        * Resolve IP to Hostname (DNS)

        * Threat information

        * Separate internal and external addresses

        * IP reputation

        * For internal addresses, get host information'
      id: 7ffe5bea-a7af-4437-806d-34ec70eabbf9
      iscommand: false
      name: IP Enrichment - Generic v2
      playbookName: IP Enrichment - Generic v2
      type: playbook
      version: -1
    taskid: 7ffe5bea-a7af-4437-806d-34ec70eabbf9
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 500\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    reputationcalc: 1
    separatecontext: false
    task:
      brand: ''
      description: 'Sets IPs in context for testing purposes.

        3 IPs are set: 1 internal, and 2 external.'
      id: 29addbb6-e385-4720-8d4a-0b8ba7cdebd7
      iscommand: false
      name: Set IPs in context
      scriptName: SetIPsTest
      type: regular
      version: -1
    taskid: 29addbb6-e385-4720-8d4a-0b8ba7cdebd7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 330\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 221f8221-ddd6-4b7a-831d-f426a5928495
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 221f8221-ddd6-4b7a-831d-f426a5928495
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 490,\n    \"y\": 1170\n  }\n}"
  '5':
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: Hostname
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: Endpoint.Hostname
                    operator: endWith
                    right:
                      value:
                        simple: yahoo.com
                root: Endpoint
          operator: isExists
      label: 'yes'
    id: '5'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '8'
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Checks whether one of the external IPs was resolved to the yahoo.com
        domain.
      id: 54fa1e23-dcbb-4b7f-8bb6-d928f2a9fd5b
      iscommand: false
      name: Was external IP resolved?
      type: condition
      version: -1
    taskid: 54fa1e23-dcbb-4b7f-8bb6-d928f2a9fd5b
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 30,\n    \"y\": 670\n  }\n}"
  '6':
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: Hostname
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: Endpoint.Hostname
                    operator: notEndWith
                    right:
                      value:
                        simple: yahoo.com
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: Endpoint.Hostname
                    operator: notEndWith
                    right:
                      value:
                        simple: akamaitechnologies.com
                root: Endpoint
          operator: isExists
      label: 'yes'
    id: '6'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '8'
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Checks whether the internal IP specified in this test, has been
        resolved.
      id: 0d739831-24ca-4043-8f30-7e46348550ad
      iscommand: false
      name: Was internal IP resolved?
      type: condition
      version: -1
    taskid: 0d739831-24ca-4043-8f30-7e46348550ad
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 940,\n    \"y\": 670\n  }\n}"
  '7':
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              complex:
                accessor: ThreatCrowd.Resolutions.domain
                root: IP
          operator: containsGeneral
          right:
            value:
              simple: ca.yahoo.com
      label: 'yes'
    id: '7'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '8'
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Checks whether Yahoo's IP was enriched using Threat Crowd.
      id: 19720a66-9eba-4cee-8af8-4befd464aa37
      iscommand: false
      name: Was IP enriched using Threat Crowd?
      type: condition
      version: -1
    taskid: 19720a66-9eba-4cee-8af8-4befd464aa37
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 670\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      message:
        simple: IP Enrichment has failed. Please check the conditions and see which
          one was not met, or if another error has occurred during the enrichment
          process.
    separatecontext: false
    task:
      brand: ''
      id: da14e18a-fb55-49ae-8f1d-8076c37dd8ed
      iscommand: false
      name: Make the test fail
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: da14e18a-fb55-49ae-8f1d-8076c37dd8ed
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1350,\n    \"y\": 970\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"5_8_#default#\": 0.1,\n    \"6_8_#default#\"\
  : 0.26,\n    \"7_8_#default#\": 0.14\n  },\n  \"paper\": {\n    \"dimensions\":\
  \ {\n      \"height\": 1225,\n      \"width\": 1700,\n      \"x\": 30,\n      \"\
  y\": 10\n    }\n  }\n}"
