id: Detonate File - No Files test
inputs: []
name: Detonate File - No Files test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 5582e6af-5671-4da2-8797-817dd974b35a
      iscommand: false
      name: ''
      version: -1
    taskid: 5582e6af-5671-4da2-8797-817dd974b35a
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: 7e1d40b1-a30e-4533-8ac0-9c57f466b96d
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 7e1d40b1-a30e-4533-8ac0-9c57f466b96d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
    note: false
    separatecontext: true
    task:
      brand: ''
      id: a84f5fa7-70c6-4ad2-8526-29bea5198794
      iscommand: false
      name: Detonate File - Generic
      playbookName: Detonate File - Generic
      type: playbook
      version: -1
    taskid: a84f5fa7-70c6-4ad2-8526-29bea5198794
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 8ed7c5d9-6d25-4739-8f17-a6e8d53da200
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 8ed7c5d9-6d25-4739-8f17-a6e8d53da200
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 560,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
