id: block_indicators_-_generic_-_test
inputs: []
name: Block Indicators - Generic - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: ec5abe2a-eb2a-4850-8e89-510de411d17b
      iscommand: false
      name: ''
      version: -1
    taskid: ec5abe2a-eb2a-4850-8e89-510de411d17b
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      IP:
        complex:
          accessor: Indicator
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: DBotScore.Type
              operator: isEqualString
              right:
                value:
                  simple: ip
          - - left:
                iscontext: true
                value:
                  simple: DBotScore.Score
              operator: greaterThanOrEqual
              right:
                value:
                  simple: '3'
          root: DBotScore
          transformers:
          - operator: uniq
      IPBlacklistMiner:
        simple: IPv4_blacklist
      URL:
        complex:
          accessor: Indicator
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: DBotScore.Type
              operator: isEqualString
              right:
                value:
                  simple: url
          - - left:
                iscontext: true
                value:
                  simple: DBotScore.Score
              operator: greaterThanOrEqual
              right:
                value:
                  simple: '3'
          root: DBotScore
          transformers:
          - operator: uniq
      URLBlacklistMiner: {}
      Username:
        complex:
          accessor: Indicator
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: DBotScore.Type
              operator: isEqualString
              right:
                value:
                  simple: username
          - - left:
                iscontext: true
                value:
                  simple: DBotScore.Score
              operator: greaterThanOrEqual
              right:
                value:
                  simple: '3'
          root: DBotScore
    separatecontext: true
    task:
      brand: ''
      id: f06511eb-a128-4be7-8354-fdc7921307a6
      iscommand: false
      name: Block Indicators - Generic
      playbookName: Block Indicators - Generic
      type: playbook
      version: -1
    taskid: f06511eb-a128-4be7-8354-fdc7921307a6
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 230\n  }\n}"
  '2':
    id: '2'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 9a35b725-4860-4576-8318-b97438c2d2e6
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 9a35b725-4860-4576-8318-b97438c2d2e6
    type: title
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 400\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 415,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\": 50\n\
  \    }\n  }\n}"
