description: A test for the URL Enrichment - Generic v2 playbook.
fromversion: 4.1.0
id: URL Enrichment - Generic v2 - Test
inputs: []
name: URL Enrichment - Generic v2 - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: fdfb6e67-9f56-4e09-8adc-2840921415ff
      iscommand: false
      name: ''
      version: -1
    taskid: fdfb6e67-9f56-4e09-8adc-2840921415ff
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": -100\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 480876c6-7f2b-4f3b-84e0-4857d0d83368
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 480876c6-7f2b-4f3b-84e0-4857d0d83368
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 980\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '16'
      - '18'
    note: false
    scriptarguments:
      Rasterize:
        simple: 'True'
      URL:
        complex:
          root: URL
          transformers:
          - operator: uniq
      VerifyURL:
        simple: 'True'
    separatecontext: true
    task:
      brand: ''
      description: 'Enrich URL using one or more integrations.


        URL enrichment includes:

        * Verify URL SSL

        * Threat information

        * URL reputaiton

        * Take URL screenshot'
      id: 962e4198-f41d-4436-8602-96de795a5183
      iscommand: false
      name: URL Enrichment - Generic v2
      playbookName: URL Enrichment - Generic v2
      type: playbook
      version: -1
    taskid: 962e4198-f41d-4436-8602-96de795a5183
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 445\n  }\n}"
  '16':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Indicator
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Type
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Vendor
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Score
          operator: isExists
      label: 'yes'
    id: '16'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '17'
      'yes':
      - '12'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 1d0fd1cb-954a-444b-86c5-80660c0ed637
      iscommand: false
      name: Verify DBotScore context fields
      type: condition
      version: -1
    taskid: 1d0fd1cb-954a-444b-86c5-80660c0ed637
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 620,\n    \"y\": 620\n  }\n}"
  '17':
    id: '17'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    reputationcalc: 1
    scriptarguments:
      message:
        simple: Not all DBotScore context fields were created.
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: d3d29b45-7064-4512-8ce0-20ccf3426bd0
      iscommand: false
      name: Make test fail
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: d3d29b45-7064-4512-8ce0-20ccf3426bd0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 755\n  }\n}"
  '18':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: InfoFile.Name
          operator: containsString
          right:
            value:
              simple: url.png
      label: 'yes'
    id: '18'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '17'
      'yes':
      - '12'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Verifies that at least one screenshot of the URLs has been created.
      id: 10182857-c240-4ee1-8cfd-a458dd201571
      iscommand: false
      name: Verify URL screenshot
      type: condition
      version: -1
    taskid: 10182857-c240-4ee1-8cfd-a458dd201571
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": -90,\n    \"y\": 620\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    reputationcalc: 1
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Clear the context for a fresh start of the test.
      id: b5a53d6c-00e9-4978-8ed8-d7a5d8053dd4
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: b5a53d6c-00e9-4978-8ed8-d7a5d8053dd4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 45\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    reputationcalc: 1
    scriptarguments:
      append: {}
      key:
        simple: URL
      value:
        simple: '["www.google.com", "http://www.yahoo.com", "https://www.facebook.com/"]'
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 0010d483-c357-4fda-87e5-ddcdd3fbf778
      iscommand: false
      name: Add URLs to context
      scriptName: Set
      type: regular
      version: -1
    taskid: 0010d483-c357-4fda-87e5-ddcdd3fbf778
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 230\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1145,\n      \"width\": 1090,\n      \"x\": -90,\n      \"y\"\
  : -100\n    }\n  }\n}"
