description: A test for the Domain Enrichment - Generic v2 playbook.
fromversion: 4.1.0
id: Domain Enrichment - Generic v2 - Test
inputs: []
name: Domain Enrichment - Generic v2 - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 02acc377-4ee9-4f26-88db-5a0a702ebd7a
      iscommand: false
      name: ''
      version: -1
    taskid: 02acc377-4ee9-4f26-88db-5a0a702ebd7a
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      Domain:
        complex:
          accessor: Name
          root: Domain
          transformers:
          - operator: uniq
    separatecontext: true
    task:
      brand: ''
      id: 2a204919-f35d-4c0f-85a0-83dfccccaa1d
      iscommand: false
      name: Domain Enrichment - Generic v2
      playbookName: Domain Enrichment - Generic v2
      type: playbook
      version: -1
    taskid: 2a204919-f35d-4c0f-85a0-83dfccccaa1d
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 530\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    reputationcalc: 1
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Clear the context for a fresh start of the test.
      id: 1119feb2-183c-45b3-87dd-a1dfe7a5b9be
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 1119feb2-183c-45b3-87dd-a1dfe7a5b9be
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 190\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    reputationcalc: 1
    scriptarguments:
      append: {}
      key:
        simple: Domain.Name
      value:
        simple: '["msn.com", "demisto.com"]'
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: af78f53f-2c12-4084-8549-f1bd5eebb3ef
      iscommand: false
      name: Set domains in context
      scriptName: Set
      type: regular
      version: -1
    taskid: af78f53f-2c12-4084-8549-f1bd5eebb3ef
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 360\n  }\n}"
  '4':
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: Domain.ContentCategories
          operator: containsGeneral
          right:
            value:
              simple: News/Media,Portals,Search Engines
        - ignorecase: true
          left:
            iscontext: true
            value:
              simple: Domain.ContentCategories
          operator: containsGeneral
          right:
            value:
              simple: Software/Technology
      label: 'yes'
    id: '4'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '5'
      'yes':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Checks if Cisco Umbrella Investigate fetched a category for the
        domain specified.
      id: a04fa368-1c51-423d-859d-ad2554298dfe
      iscommand: false
      name: Has a domain category been found?
      type: condition
      version: -1
    taskid: a04fa368-1c51-423d-859d-ad2554298dfe
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 700\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      message:
        simple: Domain category was not found. Maybe quota was reached, or something
          changed with the domain.
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: a327a491-40ce-4df3-8954-5397d032f753
      iscommand: false
      name: Make test fail
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: a327a491-40ce-4df3-8954-5397d032f753
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 800,\n    \"y\": 880\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 16b5b5ab-cb4f-4672-832c-0b9e2f93254d
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 16b5b5ab-cb4f-4672-832c-0b9e2f93254d
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 1050\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1065,\n      \"width\": 730,\n      \"x\": 450,\n      \"y\":\
  \ 50\n    }\n  }\n}"
