id: get_original_email_-_ews-_test
inputs: []
name: Get Original Email - EWS - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d7920fee-8ada-4d48-8197-2e08d19a54dc
      iscommand: false
      name: ''
      version: -1
    taskid: d7920fee-8ada-4d48-8197-2e08d19a54dc
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      InReplyTo:
        simple: <8504be6f440847ce988eae64585c1012@WIN-MICMSOEE1BU.demisto.int>
      Mailbox:
        simple: demistoadmin@demisto.int
      ThreadTopic:
        simple: Attach Item
    separatecontext: true
    task:
      brand: ''
      description: 'Use this playbook to retrieve the original email in the thread,
        including headers and attahcments, when the reporting user forwarded the original
        email not as an attachment.


        You must have the necessary permissions in the EWS integration to execute
        global search: eDiscovery'
      id: 17e0dd57-f2a9-499e-833c-523e800ae647
      iscommand: false
      name: Get Original Email - EWS
      playbookName: Get Original Email - EWS
      type: playbook
      version: -1
    taskid: 17e0dd57-f2a9-499e-833c-523e800ae647
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '3':
    id: '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: b52aade3-aa90-4343-8417-d4aa26803d62
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: b52aade3-aa90-4343-8417-d4aa26803d62
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: Email
    separatecontext: false
    task:
      brand: ''
      id: 83e29dbb-bf5e-41a3-82a4-f406d154aa14
      iscommand: false
      name: Verify context
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 83e29dbb-bf5e-41a3-82a4-f406d154aa14
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 560,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
