id: EWS search-mailbox test
inputs: []
name: EWS search-mailbox test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 03415abd-cd88-4130-8aba-616439621e89
      iscommand: false
      name: ''
      version: -1
    taskid: 03415abd-cd88-4130-8aba-616439621e89
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      folder-path: {}
      is-public: {}
      limit:
        simple: '1'
      query:
        simple: body:384868fafe3ef9190a8a5e59c5c195c3
      target-mailbox: {}
    separatecontext: false
    task:
      brand: ''
      id: af03ade1-d451-4483-82bd-eb3177276f20
      iscommand: true
      name: Search Item In All Directories
      script: '|||ews-search-mailbox'
      type: regular
      version: -1
    taskid: af03ade1-d451-4483-82bd-eb3177276f20
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '10':
    id: '10'
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: 3464c8b9-df94-4dda-8f77-32fade033f7e
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 3464c8b9-df94-4dda-8f77-32fade033f7e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1420\n  }\n}"
  '11':
    id: '11'
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      folder-path: {}
      is-public: {}
      limit:
        simple: '1'
      query:
        simple: body:384868fafe3ef9190a8a5e59c5c195c3
      target-mailbox: {}
    separatecontext: false
    task:
      brand: ''
      id: 1b4c6b69-4465-48d7-86d1-d5bbae758d28
      iscommand: true
      name: Search Item In All Directories
      script: '|||ews-search-mailbox'
      type: regular
      version: -1
    taskid: 1b4c6b69-4465-48d7-86d1-d5bbae758d28
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1770\n  }\n}"
  '12':
    id: '12'
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      seconds:
        simple: '60'
    separatecontext: false
    task:
      brand: ''
      id: b27f8993-f022-4a46-8f2c-fdeac4a5f4bf
      iscommand: false
      name: Wait
      scriptName: Sleep
      type: regular
      version: -1
    taskid: b27f8993-f022-4a46-8f2c-fdeac4a5f4bf
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1595\n  }\n}"
  '2':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: EWS.Items.body
          operator: isEqualString
          right:
            value:
              simple: 384868fafe3ef9190a8a5e59c5c195c3
      - - left:
            iscontext: true
            value:
              simple: EWS.Items.messageId
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: EWS.Items.author
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: EWS.Items.subject
          operator: isExists
      label: 'yes'
    id: '2'
    nexttasks:
      '#default#':
      - '5'
      'yes':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 932fec69-67a2-41e9-8295-3d49421f1979
      iscommand: false
      name: Verify Context
      type: condition
      version: -1
    taskid: 932fec69-67a2-41e9-8295-3d49421f1979
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 048f0b73-2c4f-41ea-8351-80e54a1cd4de
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 048f0b73-2c4f-41ea-8351-80e54a1cd4de
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2120\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: 2ab7b162-9557-4bbb-8461-52ac0cfa12d5
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 2ab7b162-9557-4bbb-8461-52ac0cfa12d5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      attachIDs: {}
      attachNames: {}
      bcc: {}
      body:
        simple: 384868fafe3ef9190a8a5e59c5c195c3
      cc: {}
      htmlBody: {}
      replyTo: {}
      subject:
        simple: EWS search-mailbox test
      to:
        simple: demistoadmin@demisto.int
    separatecontext: false
    task:
      brand: ''
      id: 54c87061-98b7-4036-8609-e0a0a3f1162b
      iscommand: true
      name: Send Email
      script: '|||send-mail'
      type: regular
      version: -1
    taskid: 54c87061-98b7-4036-8609-e0a0a3f1162b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 720\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      seconds:
        simple: '150'
    separatecontext: false
    task:
      brand: ''
      id: f0fd4825-7ed9-4842-88e4-7e4f6ca00e68
      iscommand: false
      name: Wait For Email
      scriptName: Sleep
      type: regular
      version: -1
    taskid: f0fd4825-7ed9-4842-88e4-7e4f6ca00e68
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 895\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      folder-path:
        simple: Inbox
      is-public: {}
      limit:
        simple: '1'
      query:
        simple: body:384868fafe3ef9190a8a5e59c5c195c3
      target-mailbox: {}
    separatecontext: false
    task:
      brand: ''
      id: 9cf2e442-b2d3-4b89-8c5e-79402cca6eb8
      iscommand: true
      name: Search Item In Inbox
      script: '|||ews-search-mailbox'
      type: regular
      version: -1
    taskid: 9cf2e442-b2d3-4b89-8c5e-79402cca6eb8
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1070\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      expectedValue: {}
      fields:
        simple: body,messageId,author,subject
      path:
        simple: EWS.Items
    separatecontext: false
    task:
      brand: ''
      id: 25263c73-3dcb-43bc-8413-0446b26a50cc
      iscommand: false
      name: Verify Context
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 25263c73-3dcb-43bc-8413-0446b26a50cc
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1945\n  }\n}"
  '9':
    id: '9'
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      is-public: {}
      item-id:
        simple: ${EWS.Items.itemId}
      target-folder-path:
        simple: Inbox/TEST
      target-mailbox: {}
    separatecontext: false
    task:
      brand: ''
      id: cf24db4b-578f-4e34-8e1e-6304940d612d
      iscommand: true
      name: Move
      script: '|||ews-move-item'
      type: regular
      version: -1
    taskid: cf24db4b-578f-4e34-8e1e-6304940d612d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 1245\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"2_3_yes\": 0.25\n  },\n  \"paper\": {\n\
  \    \"dimensions\": {\n      \"height\": 2135,\n      \"width\": 492.5,\n     \
  \ \"x\": 50,\n      \"y\": 50\n    }\n  }\n}"
