description: ''
id: EWS Public Folders Test
inputs: []
name: EWS Public Folders Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '2'
      - '3'
      - '1'
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 3ae4ee2b-2135-4207-8917-f0bed3a119d9
      iscommand: false
      name: ''
      version: -1
    taskid: 3ae4ee2b-2135-4207-8917-f0bed3a119d9
    type: start
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    note: false
    scriptarguments:
      is-public: {}
      target-mailbox: {}
    separatecontext: false
    task:
      brand: ''
      description: Get folders information for a mailbox. Only folders with read permissions
        will be return as a result. Notice that your visual folders on the mailbox
        (like Inbox, etc) is under the folder "Top of Information Store".
      id: afa7fd40-59b1-4b4f-869e-266afabe5d05
      iscommand: true
      name: ews-find-folders
      script: '|||ews-find-folders'
      type: regular
      version: -1
    taskid: afa7fd40-59b1-4b4f-869e-266afabe5d05
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    note: false
    scriptarguments:
      folder-path:
        simple: pub/sub
      is-public:
        simple: 'True'
      target-mailbox: {}
    separatecontext: false
    task:
      brand: ''
      description: Get a single specific folder.
      id: 5a19781c-491a-4e4b-810b-228cfbafee89
      iscommand: true
      name: ews-get-folder
      script: '|||ews-get-folder'
      type: regular
      version: -1
    taskid: 5a19781c-491a-4e4b-810b-228cfbafee89
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '3':
    id: '3'
    note: false
    scriptarguments:
      folder-path:
        simple: pub/sub
      is-public:
        simple: 'True'
      limit: {}
      query:
        simple: From:demistoadmin@demisto.int AND Subject:ismyplaybookworking?
      target-mailbox: {}
    separatecontext: false
    task:
      brand: ''
      description: Search items in a specific mailbox. Notice that a proper permissions
        needed for this operation to search in another target mailbox than the default.
      id: ee559217-5399-41b9-8778-abab57420f2f
      iscommand: true
      name: ews-search-mailbox
      script: '|||ews-search-mailbox'
      type: regular
      version: -1
    taskid: ee559217-5399-41b9-8778-abab57420f2f
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 195\n  }\n}"
  '4':
    id: '4'
    note: false
    scriptarguments:
      folder-path:
        simple: pub/sub
      is-public:
        simple: 'True'
      limit: {}
      target-mailbox: {}
    separatecontext: false
    task:
      brand: ''
      description: Get items from a specific folder in a mailbox. The items will return
        order by created time, first item is the most recent item.
      id: 3affa4ea-b4a8-4ca8-823b-c9baa7619948
      iscommand: true
      name: ews-get-items-from-folder
      script: '|||ews-get-items-from-folder'
      type: regular
      version: -1
    taskid: 3affa4ea-b4a8-4ca8-823b-c9baa7619948
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 195\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 240,\n      \"width\": 1670,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
