description: Use this playbook to initiate an endpoint scan and retrieve the scan
  results.
fromversion: ''
id: Traps Scan Endpoint
inputs:
- description: The ID of the endpoint.
  key: endpoint_id
  required: true
  value: {}
name: Traps Scan Endpoint
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: f12d335f-9a8b-4c06-8b0e-d9fe3eefd8e1
      iscommand: false
      name: ''
      version: -1
    taskid: f12d335f-9a8b-4c06-8b0e-d9fe3eefd8e1
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      endpoint_id:
        simple: ${inputs.endpoint_id}
    separatecontext: false
    task:
      brand: ''
      description: Perform a scan operation on the specified endpoint.
      id: c97a4413-cb98-4672-8157-d440d7f872f2
      iscommand: true
      name: traps-endpoint-scan
      script: '|||traps-endpoint-scan'
      type: regular
      version: -1
    taskid: c97a4413-cb98-4672-8157-d440d7f872f2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      AdditionalPollingCommandArgNames: {}
      AdditionalPollingCommandArgValues: {}
      Ids:
        simple: ${Traps.ScanResult.OperationID}
      Interval:
        simple: '1'
      PollingCommandArgName:
        simple: operation_id
      PollingCommandName:
        simple: traps-endpoint-scan-result
      Timeout:
        simple: '10'
      dt:
        simple: Traps.ScanResult(val.Status == 'pending' || val.Status == 'in progress').OperationID
    separatecontext: true
    task:
      brand: ''
      description: 'Use this playbook as a sub-playbook to block execution of the
        master playbook until a remote action is complete.

        This playbook implements polling by continuously running the command in Step
        \#2 until the operation completes.

        The remote action should have the following structure:

        1. Initiate the operation.

        2. Poll to check if the operation completed.

        3. (optional) Get the results of the operation.'
      id: be62fa74-f969-499a-87d9-deb6451fbd84
      iscommand: false
      name: GenericPolling
      playbookName: GenericPolling
      type: playbook
      version: -1
    taskid: be62fa74-f969-499a-87d9-deb6451fbd84
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      operation_id:
        simple: ${Traps.Scan.OperationID}
    separatecontext: false
    task:
      brand: ''
      description: Get results of an endpoint scan operation.
      id: d6e3caa9-e39b-4f37-897b-a8c873f95ff8
      iscommand: true
      name: traps-endpoint-scan-result
      script: '|||traps-endpoint-scan-result'
      type: regular
      version: -1
    taskid: d6e3caa9-e39b-4f37-897b-a8c873f95ff8
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    scriptarguments:
      operation_id:
        simple: ${Traps.Scan.OperationID}
    separatecontext: false
    task:
      brand: ''
      description: Get results of an endpoint scan operation.
      id: d8b4ca86-3e62-4e03-806c-f3e4b4888ec8
      iscommand: true
      name: traps-endpoint-scan-result
      script: '|||traps-endpoint-scan-result'
      type: regular
      version: -1
    taskid: d8b4ca86-3e62-4e03-806c-f3e4b4888ec8
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
tests:
- No test - Is be tested in Traps test playbook
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 765,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
