description: Enrich Endpoint with CrowdStrike
fromversion: 3.5.0
id: crowdstrike_endpoint_enrichment
inputs:
- description: The hostname to enrich
  key: Hostname
  required: false
  value:
    simple: ${Endpoint.Hostname}
name: CrowdStrike Endpoint Enrichment
outputs:
- contextPath: Endpoint.ID
  description: Unique ID of the endpoint in FalconHost
  type: string
- contextPath: Endpoint.IPAddress
  description: IPAddress of the endpoint
  type: string
- contextPath: Endpoint.Domain
  description: Domain of the endpoint
  type: string
- contextPath: Endpoint.MACAddress
  description: MACAddress of the endpoint
  type: string
- contextPath: Endpoint.OS
  description: OS of the endpoint
  type: string
- contextPath: Endpoint.OSVersion
  description: OSVersion of the endpoint
  type: string
- contextPath: Endpoint.BIOSVersion
  description: BIOSVersion of the endpoint
  type: string
- contextPath: Endpoint.HostName
  description: The host of the endpoint
  type: string
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 7cfa3cf6-82b0-452f-8c52-85355d20008a
      iscommand: false
      name: ''
      version: -1
    taskid: 7cfa3cf6-82b0-452f-8c52-85355d20008a
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 51\n  }\n}"
  '3':
    id: '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: ed6e2d6c-2eac-4e07-8a0d-8412d8700a52
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: ed6e2d6c-2eac-4e07-8a0d-8412d8700a52
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '4':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: FalconHostDevices
          operator: isExists
      label: 'yes'
    id: '4'
    nexttasks:
      '#default#':
      - '3'
      'yes':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Check if there was any machine match to the hostname
      id: 6b7bfc47-d31a-4296-8cc5-0522912daa56
      iscommand: false
      name: Was device found?
      type: condition
      version: -1
    taskid: 6b7bfc47-d31a-4296-8cc5-0522912daa56
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      ids:
        simple: ${FalconHostDevices}
    separatecontext: false
    task:
      brand: ''
      description: Get host information from CrowdStrike Falcon Host
      id: dcdf99c6-c7ad-48fa-895c-2730fe3821d6
      iscommand: true
      name: Get host information from CrowdStrike Falcon Host
      script: '|||cs-device-details'
      type: regular
      version: -1
    taskid: dcdf99c6-c7ad-48fa-895c-2730fe3821d6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 299,\n    \"y\": 550\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      filter:
        complex:
          root: inputs.Hostname
          transformers:
          - args:
              prefix:
                value:
                  simple: hostname:"
              suffix:
                value:
                  simple: '"'
            operator: concat
      limit: {}
      offset: {}
      query: {}
    separatecontext: false
    task:
      brand: ''
      description: Get CrowdStrike device id
      id: bea25d30-36cf-4ca9-8909-1a6ac435bcc1
      iscommand: true
      name: Get device ID
      script: '|||cs-device-search'
      type: regular
      version: -1
    taskid: bea25d30-36cf-4ca9-8909-1a6ac435bcc1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 210\n  }\n}"
tests:
- No test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 734,\n      \"width\": 629,\n      \"x\": 50,\n      \"y\": 51\n\
  \    }\n  }\n}"
