args:
- default: true
  description: The first list (or CSV string).
  isArray: true
  name: value
  required: true
- description: The second list (or CSV string).
  isArray: true
  name: list2
  required: true
- defaultValue: '='
  description: Separator
  name: join
  required: true
comment: Returns the product of two lists, joined by a separator, as a list of strings.
commonfields:
  id: ProductJoin
  version: -1
enabled: true
name: ProductJoin
runas: DBotWeakRole
runonce: false
script: ''
scripttarget: 0
subtype: python3
tags:
- transformer
- general
- entirelist
toversion: 4.1.9
type: python
