fromversion: 3.6.0
id: cve_enrichment_-_generic_-_test
inputs: []
name: CVE Enrichment - Generic - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: ed2884bf-ae21-4e3c-8bbc-e0b46d8a9bf0
      iscommand: false
      name: ''
      version: -1
    taskid: ed2884bf-ae21-4e3c-8bbc-e0b46d8a9bf0
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      append: {}
      key:
        simple: CVE.ID
      value:
        simple: CVE-2013-2566,CVE-2016-3333
    separatecontext: false
    task:
      brand: ''
      id: ad58c061-20aa-4c5f-8cf2-2a9cac2215ad
      iscommand: false
      name: Set CVE
      scriptName: Set
      type: regular
      version: -1
    taskid: ad58c061-20aa-4c5f-8cf2-2a9cac2215ad
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    separatecontext: true
    task:
      brand: ''
      id: 220d2a1f-c7cb-4910-823b-0774e0adada2
      iscommand: false
      name: CVE Enrichment - Generic
      playbookName: CVE Enrichment - Generic
      type: playbook
      version: -1
    taskid: 220d2a1f-c7cb-4910-823b-0774e0adada2
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: ID
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: CVE.CVSS
                    operator: isEqualNumber
                    right:
                      value:
                        simple: '9.3'
                root: CVE
          operator: isEqualString
          right:
            value:
              simple: CVE-2016-3333
      - - left:
            iscontext: true
            value:
              complex:
                accessor: ID
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: CVE.CVSS
                    operator: isEqualNumber
                    right:
                      value:
                        simple: '4.3'
                root: CVE
          operator: isEqualString
          right:
            value:
              simple: CVE-2013-2566
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: "Gets a value and return it. This is to be used in playbook conditional\
        \ tasks - get a value from incident field, label or context, and act accordingly.\
        \ \nIf an array is returned. the first value will be the decision making value."
      id: 6db7f463-a6b1-498b-8e55-a0d79ad364a8
      iscommand: false
      name: Verify
      type: condition
      version: -1
    taskid: 6db7f463-a6b1-498b-8e55-a0d79ad364a8
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: face288a-b66a-41d2-868c-7dda5c039fd5
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: face288a-b66a-41d2-868c-7dda5c039fd5
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 735,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
