description: 'A test playbook for extracting indicators from a file.

  Supported file types:

  PDF

  TXT

  HTM, HTML

  DOC, DOCX'
fromversion: 4.1.0
id: Extract Indicators From File - Generic v2 - Test
inputs: []
name: Extract Indicators From File - Generic v2 - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: acf29053-815f-4e96-8122-4781e4f967d7
      iscommand: false
      name: ''
      version: -1
    taskid: acf29053-815f-4e96-8122-4781e4f967d7
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '19'
    note: false
    reputationcalc: 1
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://raw.githubusercontent.com/demisto/content/master/TestData/textwithindicators.txt
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: Downloads a TXT file using HTTP GET.
      id: 8d01fbd2-8fe8-49f3-89ea-1c412a1c53a1
      iscommand: false
      name: Download TXT file
      scriptName: http
      type: regular
      version: -1
    taskid: 8d01fbd2-8fe8-49f3-89ea-1c412a1c53a1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 570\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '19'
    note: false
    reputationcalc: 1
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://raw.githubusercontent.com/demisto/content/master/TestData/pdfwithindicators.pdf
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: Downloads a PDF file using HTTP GET.
      id: 2c831b40-0b51-4868-8d07-3452279b8f0b
      iscommand: false
      name: Download PDF file
      scriptName: http
      type: regular
      version: -1
    taskid: 2c831b40-0b51-4868-8d07-3452279b8f0b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -430,\n    \"y\": 570\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    reputationcalc: 1
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete the context of the incident to start with clear context.
      id: 77764bdf-2752-45c1-845b-9912d826761d
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 77764bdf-2752-45c1-845b-9912d826761d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 210\n  }\n}"
  '14':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Text
                root: File
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Producer
                root: File
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Author
                root: File
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: ModDate
                root: File
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: CreationDate
                root: File
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Pages
                root: File
          operator: isExists
      label: 'yes'
    id: '14'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '5'
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: 'Checks if the PDF returned all of the expected outputs, except
        for title.

        Checks for the following outputs:

        - File.Text

        - File.Producer

        - File.xap

        - File.Author

        - File.dc

        - File.xapmm

        - File.ModDate

        - File.CreationDate

        - File.Pages


        File.Title is not being checked because it doesn''t exist in the test PDF
        provided.'
      id: 6d32259d-a837-4547-82d0-cf883f087d8b
      iscommand: false
      name: Did the PDF file return outputs?
      type: condition
      version: -1
    taskid: 6d32259d-a837-4547-82d0-cf883f087d8b
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": -180,\n    \"y\": 980\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '19'
    note: false
    reputationcalc: 1
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://raw.githubusercontent.com/demisto/content/master/TestData/Inline_malicious_url.eml
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: Downloads an EML file using HTTP GET.
      id: 9ac7080d-c4dd-4b94-8fe0-4b182283c074
      iscommand: false
      name: Download EML file
      scriptName: http
      type: regular
      version: -1
    taskid: 9ac7080d-c4dd-4b94-8fe0-4b182283c074
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -910,\n    \"y\": 570\n  }\n}"
  '18':
    id: '18'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '19'
    note: false
    reputationcalc: 1
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://raw.githubusercontent.com/demisto/content/master/TestData/TestExcelFile.xlsx
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: Downloads an XLSX file using HTTP GET.
      id: b24d3e5f-c9a5-4d2a-851a-2e7d7aea1877
      iscommand: false
      name: Download XLSX file
      scriptName: http
      type: regular
      version: -1
    taskid: b24d3e5f-c9a5-4d2a-851a-2e7d7aea1877
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1480,\n    \"y\": 570\n  }\n}"
  '19':
    id: '19'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
      - '3'
    note: false
    separatecontext: true
    task:
      brand: ''
      id: aaea1865-4ee1-4738-8d3a-794c62b22d03
      iscommand: false
      name: Extract Indicators From File - Generic v2
      playbookName: Extract Indicators From File - Generic v2
      type: playbook
      version: -1
    taskid: aaea1865-4ee1-4738-8d3a-794c62b22d03
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 770\n  }\n}"
  '20':
    id: '20'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '19'
    note: false
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://raw.githubusercontent.com/demisto/content/master/TestData/ACH.Payment.Advice.rtf
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: Sends http request. Returns the response as json.
      id: 3f9b5e0d-cf2f-4305-8983-856df49f1b50
      iscommand: false
      name: Download RTF file
      scriptName: http
      type: regular
      version: -1
    taskid: 3f9b5e0d-cf2f-4305-8983-856df49f1b50
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -1380,\n    \"y\": 570\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Data
                root: URL
          operator: containsGeneral
          right:
            value:
              simple: http://www.txttesturl.com
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Data
                root: URL
          operator: containsGeneral
          right:
            value:
              simple: http://www.pdftesturl.com
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Data
                root: URL
          operator: containsGeneral
          right:
            value:
              simple: http://www.doctesturl.com
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Data
                root: URL
          operator: containsGeneral
          right:
            value:
              simple: http://www.docxtesturl.com
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Data
                root: URL
          operator: notContainsGeneral
          right:
            value:
              simple: http://www.desktop-style.de
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Text
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: File.Text
                    operator: containsString
                    right:
                      value:
                        simple: 'This is an example of a non-text-searchable '
                root: File
                transformers:
                - operator: toUpperCase
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Data
                root: URL
          operator: containsGeneral
          right:
            value:
              simple: https://mock.com?e=P6wGLG
      label: 'Yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '5'
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Checks whether specific indicators were extracted from each one
        of the downloaded files.
      id: 36c14cb2-423d-4d53-8423-2f1a44f4875f
      iscommand: false
      name: Were the correct indicators extracted?
      type: condition
      version: -1
    taskid: 36c14cb2-423d-4d53-8423-2f1a44f4875f
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 280,\n    \"y\": 980\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 88666eac-de82-43cd-80e7-b7bcbd707c8b
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 88666eac-de82-43cd-80e7-b7bcbd707c8b
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1400\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    reputationcalc: 1
    scriptarguments:
      message:
        simple: The email addresses were not found in context.
    separatecontext: false
    task:
      brand: ''
      description: Causes the test playbook to fail if the correct email addresses
        were not extracted.
      id: a7537367-cc86-4d5c-8179-eb9e3edbf463
      iscommand: false
      name: Make test fail
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: a7537367-cc86-4d5c-8179-eb9e3edbf463
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 600,\n    \"y\": 1220\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
      - '9'
      - '1'
      - '11'
      - '15'
      - '18'
      - '20'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 69f8a4ec-a422-4067-84d8-c09cf54de4a9
      iscommand: false
      name: Download Files
      type: title
      version: -1
    taskid: 69f8a4ec-a422-4067-84d8-c09cf54de4a9
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 400\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '19'
    note: false
    reputationcalc: 1
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://raw.githubusercontent.com/demisto/content/master/TestData/docwithindicators.doc
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: Downloads a DOC file using HTTP GET.
      id: d021722f-2461-4b45-863a-d17979a1988e
      iscommand: false
      name: Download DOC file
      scriptName: http
      type: regular
      version: -1
    taskid: d021722f-2461-4b45-863a-d17979a1988e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1010,\n    \"y\": 570\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '19'
    note: false
    reputationcalc: 1
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://raw.githubusercontent.com/demisto/content/master/TestData/docxwithindicators.docx
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: Downloads a DOCX file using HTTP GET.
      id: d79d8f9b-0d3d-479f-8fe1-1cf0902d8bf2
      iscommand: false
      name: Download DOCX file
      scriptName: http
      type: regular
      version: -1
    taskid: d79d8f9b-0d3d-479f-8fe1-1cf0902d8bf2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 530,\n    \"y\": 570\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"14_4_yes\": 0.65,\n    \"3_4_yes\": 0.65\n\
  \  },\n  \"paper\": {\n    \"dimensions\": {\n      \"height\": 1415,\n      \"\
  width\": 3240,\n      \"x\": -1380,\n      \"y\": 50\n    }\n  }\n}"
