description: Test ImageOCR integration
id: TestImageOCR
inputs: []
name: TestImageOCR
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: ca1500de-479a-4148-833c-224648249b0d
      iscommand: false
      name: ''
      version: -1
    taskid: ca1500de-479a-4148-833c-224648249b0d
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    scriptarguments:
      body: {}
      filename:
        simple: irs.png
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://raw.githubusercontent.com/demisto/content/09065150a989bd0bdc9a848dd635dca59e8e1330/Integrations/ImageOCR/test_data/irs.png
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: Sends http request. Returns the response as json.
      id: 7546faa1-33e1-4388-8ad5-5c3b52a8bca2
      iscommand: false
      name: Get Image
      scriptName: http
      type: regular
      version: -1
    taskid: 7546faa1-33e1-4388-8ad5-5c3b52a8bca2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    note: false
    scriptarguments:
      message:
        simple: Failed Internal/External check
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: 5e1eb7ef-507f-4e2d-8141-d8b4607173d6
      iscommand: false
      name: Error
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 5e1eb7ef-507f-4e2d-8141-d8b4607173d6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 640,\n    \"y\": 1220\n  }\n}"
  '13':
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: File.Text
          operator: containsString
          right:
            value:
              simple: Internal Revenue Service
      label: 'yes'
    id: '13'
    ignoreworker: false
    nexttasks:
      'no':
      - '10'
      'yes':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: dca3e0d3-0ffe-49ae-8eca-f55d87b3cf41
      iscommand: false
      name: Check text
      type: condition
      version: -1
    taskid: dca3e0d3-0ffe-49ae-8eca-f55d87b3cf41
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 60,\n    \"y\": 820\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    scriptarguments:
      entryid:
        complex:
          accessor: EntryID
          root: File
      langs: {}
    separatecontext: false
    task:
      brand: ''
      description: Extract test from an image
      id: 837dbecf-5601-49de-812e-eaf3354a9113
      iscommand: true
      name: OCR Extract Text
      script: '|||image-ocr-extract-text'
      type: regular
      version: -1
    taskid: 837dbecf-5601-49de-812e-eaf3354a9113
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 560\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 9d352601-8215-4312-8368-382bb17c5a6e
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 9d352601-8215-4312-8368-382bb17c5a6e
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 20,\n    \"y\": 1260\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
      keysToKeep: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 31606802-117a-49b4-80ef-ed85c690614a
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 31606802-117a-49b4-80ef-ed85c690614a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1275,\n      \"width\": 1000,\n      \"x\": 20,\n      \"y\":\
  \ 50\n    }\n  }\n}"
