fromversion: 4.1.0
id: Jask_Test
inputs: []
name: Jask Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 1dfe79ba-2b8b-4d40-8f8a-830ecc1a76f1
      iscommand: false
      name: ''
      version: -1
    taskid: 1dfe79ba-2b8b-4d40-8f8a-830ecc1a76f1
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 1125,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      assigned-team: {}
      assigned-user: {}
      last-seen: {}
      limit: {}
      offset: {}
      rating: {}
      sort: {}
      status: {}
      time-from:
        simple: 12/1/2018
      time-to:
        simple: 12/29/2019
    separatecontext: false
    task:
      brand: ''
      description: 'Search insights using the given filters. '
      id: f3b824c2-45a4-4123-8307-f04acf62b9b6
      iscommand: true
      name: Get insights for a given date
      script: '|||jask-search-insights'
      type: regular
      version: -1
    taskid: f3b824c2-45a4-4123-8307-f04acf62b9b6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 370\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      category: {}
      last-seen: {}
      limit:
        simple: '10'
      offset: {}
      sort: {}
      source: {}
      time-from:
        simple: 12/20/2018
      time-to:
        simple: 12/29/2018
    separatecontext: false
    task:
      brand: ''
      description: 'Search signals using the given filters. '
      id: e0da9ca1-0332-437c-871e-5f09a6e03538
      iscommand: true
      name: Get signals for a given date
      script: '|||jask-search-signals'
      type: regular
      version: -1
    taskid: e0da9ca1-0332-437c-871e-5f09a6e03538
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1770,\n    \"y\": 1070\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '20'
    note: false
    scriptarguments:
      expectedValue:
        simple: 'true'
      fields: {}
      path:
        simple: Jask.Signal=>val.length >= 10
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 7a65358e-0a34-4fa7-89ad-7a06a199c6d1
      iscommand: false
      name: VerifyContext
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 7a65358e-0a34-4fa7-89ad-7a06a199c6d1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1770,\n    \"y\": 1245\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    scriptarguments:
      entity-type: {}
      last-seen: {}
      limit:
        simple: '10'
      offset: {}
      sort: {}
      time-from:
        simple: 12/20/2018
      time-to:
        simple: 12/29/2018
    separatecontext: false
    task:
      brand: ''
      description: Search entities using the given filters.
      id: 86d139ac-5bff-41bb-86dd-e9ffe1404409
      iscommand: true
      name: Get entities for a given date
      script: '|||jask-search-entities'
      type: regular
      version: -1
    taskid: 86d139ac-5bff-41bb-86dd-e9ffe1404409
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 2200,\n    \"y\": 1070\n  }\n}"
  '14':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Entity
                root: Jask
                transformers:
                - operator: count
          operator: isEqualString
          right:
            value:
              simple: '10'
      label: 'yes'
    id: '14'
    ignoreworker: false
    nexttasks:
      'yes':
      - '20'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 1ad2b6fd-26fa-4901-8b5d-192e5dd1165c
      iscommand: false
      name: VerifyContext
      type: condition
      version: -1
    taskid: 1ad2b6fd-26fa-4901-8b5d-192e5dd1165c
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 2200,\n    \"y\": 1245\n  }\n}"
  '19':
    id: '19'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '20'
    note: false
    scriptarguments:
      insight-id:
        simple: ${Jask.Insight.[0].Id}
    separatecontext: false
    task:
      brand: ''
      description: Get comments for a specific Insight ID. (Users can post and update
        comments on the JASK SIEM portal for any Insight ID.)
      id: 58a64c77-f800-4968-81e7-29d3a3b58b94
      iscommand: true
      name: jask-get-insight-comments
      script: '|||jask-get-insight-comments'
      type: regular
      version: -1
    taskid: 58a64c77-f800-4968-81e7-29d3a3b58b94
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 1245\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
      - '19'
    note: false
    scriptarguments:
      expectedValue:
        simple: 'true'
      fields: {}
      path:
        simple: Jask.Insight=>val.length >= 1
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: a5525492-d9cb-40e6-8f06-4c299abbf46f
      iscommand: false
      name: VerifyContext
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: a5525492-d9cb-40e6-8f06-4c299abbf46f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 545\n  }\n}"
  '20':
    id: '20'
    ignoreworker: false
    note: false
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      id: {}
    separatecontext: false
    task:
      brand: Builtin
      description: Close the current investigation
      id: 03493a0f-fcb5-45d4-8b15-716f481791e2
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 03493a0f-fcb5-45d4-8b15-716f481791e2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1125,\n    \"y\": 1420\n  }\n}"
  '21':
    id: '21'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '22'
    note: false
    scriptarguments:
      add_to_context:
        simple: 'true'
      brand_name:
        simple: Jask
      expect_data: {}
      instance_name: {}
    separatecontext: false
    task:
      brand: ''
      id: 2dc5cf78-a38e-4119-86b6-05a60739b71e
      iscommand: false
      name: Test Fetch Incidents
      scriptName: FetchFromInstance
      type: regular
      version: -1
    taskid: 2dc5cf78-a38e-4119-86b6-05a60739b71e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '22':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: FetchedIncidents.id
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: FetchedIncidents.severity
          operator: isExists
      label: 'yes'
    id: '22'
    ignoreworker: false
    nexttasks:
      'yes':
      - '20'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 5326dafd-a0f4-4b9d-861c-3183e4eabf21
      iscommand: false
      name: VerifyContext
      type: condition
      version: -1
    taskid: 5326dafd-a0f4-4b9d-861c-3183e4eabf21
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
      - '11'
      - '13'
      - '21'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: e611ac11-fa73-4d46-80d9-de0cbe256c6c
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: e611ac11-fa73-4d46-80d9-de0cbe256c6c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1125,\n    \"y\": 195\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
      - '6'
    note: false
    scriptarguments:
      insight-id:
        simple: ${Jask.Insight.[0].Id}
    separatecontext: false
    task:
      brand: ''
      description: Get Insight details for a specific Insight ID. Insight details
        command references SmartAlerts, which are the highest level abstractions in
        JASK SIEM consisting of multiple signals, and records and relating to one
        or more assets.
      id: b539dcf6-b35c-4230-8870-c4a065742ce4
      iscommand: true
      name: Get details for the first one
      script: '|||jask-get-insight-details'
      type: regular
      version: -1
    taskid: b539dcf6-b35c-4230-8870-c4a065742ce4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      entity-id:
        complex:
          accessor: Insight.EntityDetails.Id
          root: Jask
    separatecontext: false
    task:
      brand: ''
      description: Get entity details for a specific entity ID
      id: 54e942af-589b-46b6-83ba-b43e487122d2
      iscommand: true
      name: Get entity details for first related entity
      script: '|||jask-get-entity-details'
      type: regular
      version: -1
    taskid: 54e942af-589b-46b6-83ba-b43e487122d2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 895\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      signal-id:
        simple: ${Jask.Insight.SignalList.[0].Id}
    separatecontext: false
    task:
      brand: ''
      description: Get Signal details for a specific Signal ID. Signal details command
        references signals in JASK which are created when records exhibit suspicious
        properties and mate with patterns or other detection logic.
      id: 2246ad22-6d23-4e3b-8fcd-534b71493035
      iscommand: true
      name: Get signal details for first related signal
      script: '|||jask-get-signal-details'
      type: regular
      version: -1
    taskid: 2246ad22-6d23-4e3b-8fcd-534b71493035
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 1070\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: Jask.Entity.Id
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 0d4df15a-863f-4801-885b-1d2ac034f191
      iscommand: false
      name: Verify we have an entity
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 0d4df15a-863f-4801-885b-1d2ac034f191
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1070\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '20'
    note: false
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: Jask.Signal.Id
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 7ab79c45-f4ca-4d1c-83fe-e6729eb685e2
      iscommand: false
      name: Verify we have a signal
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 7ab79c45-f4ca-4d1c-83fe-e6729eb685e2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 1245\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '20'
    note: false
    scriptarguments:
      entity-id:
        simple: ${Jask.Entity.Id}
    separatecontext: false
    task:
      brand: ''
      description: Get entities related to a specific entity ID.
      id: 551e9bcf-c998-4eb5-82f7-7e22e483e339
      iscommand: true
      name: Get entities related to the given entity
      script: '|||jask-get-related-entities'
      type: regular
      version: -1
    taskid: 551e9bcf-c998-4eb5-82f7-7e22e483e339
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1245\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1465,\n      \"width\": 2530,\n      \"x\": 50,\n      \"y\":\
  \ 50\n    }\n  }\n}"
