id: Zscaler Test
inputs: []
name: Zscaler Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '23'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 42269acb-4a0b-4241-808d-1a4690873f25
      iscommand: false
      name: ''
      version: -1
    taskid: 42269acb-4a0b-4241-808d-1a4690873f25
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": -290,\n    \"y\": -590\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      displayURL: {}
    separatecontext: false
    task:
      brand: ''
      description: Returns a list of all categories
      id: 040229c6-389d-45a1-8759-1680434a149f
      iscommand: true
      name: zscaler-get-categories
      script: '|||zscaler-get-categories'
      type: regular
      version: -1
    taskid: 040229c6-389d-45a1-8759-1680434a149f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      entryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    task:
      brand: ''
      id: d7d0b668-423f-488d-8321-c004abc3bd6e
      iscommand: false
      name: Ensure error occurred
      scriptName: isError
      type: regular
      version: -1
    taskid: d7d0b668-423f-488d-8321-c004abc3bd6e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 285,\n    \"y\": 1595\n  }\n}"
  '11':
    id: '11'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 705b73ea-67ab-493d-8c00-928cea09e3a6
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 705b73ea-67ab-493d-8c00-928cea09e3a6
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 285,\n    \"y\": 1770\n  }\n}"
  '12':
    id: '12'
    nexttasks:
      '#none#':
      - '17'
      - '16'
      - '15'
      - '13'
      - '14'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 975d37e2-5ec9-4ae0-8706-458bf03fb6f4
      iscommand: false
      name: Test simultaneous IP requests
      type: title
      version: -1
    taskid: 975d37e2-5ec9-4ae0-8706-458bf03fb6f4
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": -1570,\n    \"y\": 430\n  }\n}"
  '13':
    id: '13'
    note: false
    scriptarguments:
      ip:
        simple: 1.1.1.2
    separatecontext: false
    task:
      brand: Zscaler
      id: 5d9f899c-ad54-4dcd-89ba-5a5aee8ee7c7
      iscommand: true
      name: Check IP with Zscaler
      script: Zscaler|||ip
      type: regular
      version: -1
    taskid: 5d9f899c-ad54-4dcd-89ba-5a5aee8ee7c7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -1140,\n    \"y\": 680\n  }\n}"
  '14':
    id: '14'
    note: false
    scriptarguments:
      ip:
        simple: 1.1.1.2
    separatecontext: false
    task:
      brand: Zscaler
      id: f46376e9-ea37-45d5-80f2-436e58c677f1
      iscommand: true
      name: Check IP with Zscaler
      script: Zscaler|||ip
      type: regular
      version: -1
    taskid: f46376e9-ea37-45d5-80f2-436e58c677f1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -710,\n    \"y\": 670\n  }\n}"
  '15':
    id: '15'
    note: false
    scriptarguments:
      ip:
        simple: 1.1.1.2
    separatecontext: false
    task:
      brand: Zscaler
      id: d27c8712-96fe-453b-801e-2e7c305b2d51
      iscommand: true
      name: Check IP with Zscaler
      script: Zscaler|||ip
      type: regular
      version: -1
    taskid: d27c8712-96fe-453b-801e-2e7c305b2d51
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -1570,\n    \"y\": 680\n  }\n}"
  '16':
    id: '16'
    note: false
    scriptarguments:
      ip:
        simple: 1.1.1.2
    separatecontext: false
    task:
      brand: Zscaler
      id: 0060808d-6d47-4928-811f-25649d4fda0a
      iscommand: true
      name: Check IP with Zscaler
      script: Zscaler|||ip
      type: regular
      version: -1
    taskid: 0060808d-6d47-4928-811f-25649d4fda0a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -1990,\n    \"y\": 680\n  }\n}"
  '17':
    id: '17'
    note: false
    scriptarguments:
      ip:
        simple: 1.1.1.2
    separatecontext: false
    task:
      brand: Zscaler
      id: 785f7a4f-1c69-463a-8359-af8300cfa5b5
      iscommand: true
      name: Check IP with Zscaler
      script: Zscaler|||ip
      type: regular
      version: -1
    taskid: 785f7a4f-1c69-463a-8359-af8300cfa5b5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -2430,\n    \"y\": 680\n  }\n}"
  '2':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Zscaler.Category.ID
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Zscaler.Category.CustomCategory
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Zscaler.Category.Description
          operator: isExists
      label: 'yes'
    id: '2'
    nexttasks:
      'yes':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: dbdce48b-6baf-40a5-8ad2-1252a233809b
      iscommand: false
      name: Verify Get Categories output
      type: condition
      version: -1
    taskid: dbdce48b-6baf-40a5-8ad2-1252a233809b
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '23':
    id: '23'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
      - '1'
      - '4'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: 166d3876-dc2d-480e-8fcb-ad33d4aa70d9
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 166d3876-dc2d-480e-8fcb-ad33d4aa70d9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -470,\n    \"y\": -200\n  }\n}"
  '24':
    id: '24'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      details:
        simple: full
      md5:
        simple: 3FD0EA0AE759D58274310C022FB0CBBA
    separatecontext: false
    task:
      brand: ''
      description: asasd
      id: e26d1c1e-4b20-4561-8778-5ec2adedc24c
      iscommand: true
      name: test SandBox Report
      script: '|||zscaler-sandbox-report'
      type: regular
      version: -1
    taskid: e26d1c1e-4b20-4561-8778-5ec2adedc24c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 285,\n    \"y\": 1790\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      category-id:
        simple: ${Zscaler.Category.[0].ID}
      url:
        simple: ${GeneratedUUID}.com
    separatecontext: false
    task:
      brand: ''
      id: 6aa6488e-7f47-4072-8771-1a677b05f857
      iscommand: true
      name: Add URL to URL category
      script: '|||zscaler-category-add-url'
      type: regular
      version: -1
    taskid: 6aa6488e-7f47-4072-8771-1a677b05f857
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '3'
      - '5'
      - '7'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Generates random UUID
      id: 0cbdc342-ec1e-422f-8aea-bfc0c2fd4c58
      iscommand: false
      name: GenerateUUID
      scriptName: GenerateUUID
      type: regular
      version: -1
    taskid: 0cbdc342-ec1e-422f-8aea-bfc0c2fd4c58
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: GeneratedUUID
                transformers:
                - args:
                    prefix: {}
                    suffix:
                      value:
                        simple: .com
                  operator: concat
          operator: in
          right:
            iscontext: true
            value:
              simple: Zscaler.Category.URL
      label: 'yes'
    id: '5'
    nexttasks:
      'yes':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: e26ac553-7c86-4300-848a-70c9e4faa52b
      iscommand: false
      name: Verify Add URL to URL category output
      type: condition
      version: -1
    taskid: e26ac553-7c86-4300-848a-70c9e4faa52b
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 172.5,\n    \"y\": 720\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      url:
        simple: ${GeneratedUUID}.com
    separatecontext: false
    task:
      brand: ''
      id: d8dea887-2459-43ec-873e-668ddf074bae
      iscommand: true
      name: Blacklist URL
      script: '|||zscaler-blacklist-url'
      type: regular
      version: -1
    taskid: d8dea887-2459-43ec-873e-668ddf074bae
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 172.5,\n    \"y\": 895\n  }\n}"
  '7':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: GeneratedUUID
                transformers:
                - args:
                    prefix: {}
                    suffix:
                      value:
                        simple: .com
                  operator: concat
          operator: in
          right:
            iscontext: true
            value:
              simple: Zscaler.Blacklist
      label: 'yes'
    id: '7'
    nexttasks:
      'yes':
      - '9'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: c462a7a7-c197-4867-83bc-89fa247e126e
      iscommand: false
      name: Verify Blacklist URL ouput
      type: condition
      version: -1
    taskid: c462a7a7-c197-4867-83bc-89fa247e126e
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 285,\n    \"y\": 1245\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '7'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: c500fa4e-88b3-4663-898a-24df3f6a1493
      iscommand: true
      name: Get blacklist
      script: '|||zscaler-get-blacklist'
      type: regular
      version: -1
    taskid: c500fa4e-88b3-4663-898a-24df3f6a1493
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 172.5,\n    \"y\": 1070\n  }\n}"
  '9':
    continueonerror: true
    id: '9'
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      url:
        simple: https://www.google.com
    separatecontext: false
    task:
      brand: ''
      id: 94a3cf6e-5b56-4dbb-895a-366409c77022
      iscommand: true
      name: Try to blacklist url which starts with https://
      script: '|||zscaler-blacklist-url'
      type: regular
      version: -1
    taskid: 94a3cf6e-5b56-4dbb-895a-366409c77022
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 285,\n    \"y\": 1420\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2615,\n      \"width\": 3290,\n      \"x\": -2430,\n      \"y\"\
  : -590\n    }\n  }\n}"
