id: Snowflake-Test
inputs: []
name: Snowflake-Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: a3244a3d-eb9a-4b61-86ae-cef683fcca3a
      iscommand: false
      name: ''
      version: -1
    taskid: a3244a3d-eb9a-4b61-86ae-cef683fcca3a
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: dacc063e-50f7-43d1-812f-1c1d0a433380
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: dacc063e-50f7-43d1-812f-1c1d0a433380
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '11':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Result.TS
                root: Snowflake
                transformers:
                - args:
                    index:
                      value:
                        simple: '0'
                  operator: atIndex
          operator: isEqualString
          right:
            value:
              simple: 2019-03-26 11:14:18.574000
      label: 'yes'
    id: '11'
    ignoreworker: false
    nexttasks:
      'yes':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: b6ec06ad-ace2-45ec-8cf8-102810f05f03
      iscommand: false
      name: Verify Query Output
      type: condition
      version: -1
    taskid: b6ec06ad-ace2-45ec-8cf8-102810f05f03
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      columns: {}
      database:
        simple: demo_db
      query:
        simple: select * from test where ID = 8 and NAME = 'blah'
      role:
        simple: sysadmin
      rows: {}
      schema:
        simple: public
      warehouse:
        simple: demo_wh
    separatecontext: false
    task:
      brand: Snowflake
      description: Execute a SELECT query and retrieve the data
      id: 8694012b-4bb5-4056-8480-faef40999716
      iscommand: true
      name: snowflake-query
      script: Snowflake|||snowflake-query
      type: regular
      version: -1
    taskid: 8694012b-4bb5-4056-8480-faef40999716
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: af19262d-c556-4f70-8e64-4aa726540bce
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: af19262d-c556-4f70-8e64-4aa726540bce
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 735,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
