description: initiate Archer incident
fromversion: 3.5.0
id: Archer initiate incident
inputs: []
name: Archer initiate incident
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '2'
    separatecontext: false
    task:
      brand: ''
      description: start
      id: 438120e9-1d87-4bf5-8b48-1000633050e3
      iscommand: false
      name: ''
      version: -1
    taskid: 438120e9-1d87-4bf5-8b48-1000633050e3
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '2':
    id: '2'
    scriptarguments:
      extend-context: {}
      fileId:
        simple: ${incident.labels.attachedFiles->FileID}
    separatecontext: false
    task:
      brand: RSA Archer
      description: Downloads file from Archer to Demisto's context
      id: 474e6e86-127d-46e3-8a9e-9efee132001a
      iscommand: true
      name: archer-get-file
      script: RSA Archer|||archer-get-file
      type: regular
      version: -1
    taskid: 474e6e86-127d-46e3-8a9e-9efee132001a
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 452\n  }\n}"
tests:
- No test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 497,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\": 50\n\
  \    }\n  }\n}"
