id: McAfeeESMTest
inputs: []
name: McAfeeESMTest
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '28'
      - '32'
      - '33'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 5985abd4-2661-4077-8f90-65dda191f955
      iscommand: false
      name: ''
      version: -1
    taskid: 5985abd4-2661-4077-8f90-65dda191f955
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 50\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    scriptarguments:
      assignee:
        simple: JKRolling
      organization:
        simple: LuthorCorp
      severity:
        simple: '1'
      status:
        simple: Research_${TimeNowUnix}
      summary:
        simple: McAfee ESM playbook test - all parameter case
    separatecontext: false
    task:
      brand: ''
      id: 5ed048f9-e4cb-4749-8ef8-c6f970e635c0
      iscommand: true
      name: Add new case with all parameters.
      script: '|||esm-add-case'
      type: regular
      version: -1
    taskid: 5ed048f9-e4cb-4749-8ef8-c6f970e635c0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1390\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      assignee:
        simple: me
      id:
        simple: ${Case.ID}
      organization: {}
      severity: {}
      status:
        simple: Open
      summary: {}
    separatecontext: false
    task:
      brand: ''
      id: d88b9072-9c2a-4301-8672-3bd1517a8db6
      iscommand: true
      name: Edit the user name of last case to default
      script: '|||esm-edit-case'
      type: regular
      version: -1
    taskid: d88b9072-9c2a-4301-8672-3bd1517a8db6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1565\n  }\n}"
  '16':
    id: '16'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '18'
    note: false
    scriptarguments:
      new_name:
        simple: Development_${TimeNowUnix}
      original_name:
        simple: Research_${TimeNowUnix}
      show_in_case_pane: {}
    separatecontext: false
    task:
      brand: ''
      id: cf9dae43-8c4c-41c6-8247-711a819694e0
      iscommand: true
      name: Change case status name from Research to Development
      script: '|||esm-edit-case-status'
      type: regular
      version: -1
    taskid: cf9dae43-8c4c-41c6-8247-711a819694e0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1915\n  }\n}"
  '17':
    id: '17'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '20'
    note: false
    scriptarguments:
      name:
        simple: Development_${TimeNowUnix}
    separatecontext: false
    task:
      brand: ''
      id: ab491efa-5956-40bf-8b5c-492222572987
      iscommand: true
      name: Remove additional case status
      script: '|||esm-delete-case-status'
      type: regular
      version: -1
    taskid: ab491efa-5956-40bf-8b5c-492222572987
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2440\n  }\n}"
  '18':
    id: '18'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '19'
    note: false
    scriptarguments:
      name:
        simple: VooDoo_${TimeNowUnix}
      show_in_case_pane:
        simple: 'True'
    separatecontext: false
    task:
      brand: ''
      id: 59ba0557-874b-45f9-8260-1cde3ebba3d3
      iscommand: true
      name: Set show case pane of new case status
      script: '|||esm-add-case-status'
      type: regular
      version: -1
    taskid: 59ba0557-874b-45f9-8260-1cde3ebba3d3
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2090\n  }\n}"
  '19':
    id: '19'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    scriptarguments:
      new_name:
        simple: VooDoo_${TimeNowUnix}
      original_name:
        simple: VooDoo_${TimeNowUnix}
      show_in_case_pane:
        simple: 'False'
    separatecontext: false
    task:
      brand: ''
      id: f48b645d-18b9-4d5d-84b5-b391e8c4e034
      iscommand: true
      name: Change case status optional parameter
      script: '|||esm-edit-case-status'
      type: regular
      version: -1
    taskid: f48b645d-18b9-4d5d-84b5-b391e8c4e034
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2265\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      assignee: {}
      organization: {}
      severity: {}
      status: {}
      summary:
        simple: this is the first case
    separatecontext: false
    task:
      brand: ''
      description: Add a case to the system
      id: 308e35ee-825b-4990-8ed8-60ffc89013e6
      iscommand: true
      name: esm-add-case
      script: '|||esm-add-case'
      type: regular
      version: -1
    taskid: 308e35ee-825b-4990-8ed8-60ffc89013e6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 690\n  }\n}"
  '20':
    id: '20'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '22'
    note: false
    scriptarguments:
      name:
        simple: VooDoo_${TimeNowUnix}
    separatecontext: false
    task:
      brand: ''
      id: b9bd2237-14eb-4cfe-8ceb-09af44759de4
      iscommand: true
      name: Remove additional case status2
      script: '|||esm-delete-case-status'
      type: regular
      version: -1
    taskid: b9bd2237-14eb-4cfe-8ceb-09af44759de4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2615\n  }\n}"
  '22':
    id: '22'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '23'
      - '25'
      - '26'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d51965c9-43bc-44af-8a99-c4becd316916
      iscommand: false
      name: All listing commands
      type: title
      version: -1
    taskid: d51965c9-43bc-44af-8a99-c4becd316916
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2805\n  }\n}"
  '23':
    id: '23'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '37'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 7d222eac-395c-47ec-88f4-db036d572bbd
      iscommand: true
      name: Get status cases
      script: '|||esm-get-case-statuses'
      type: regular
      version: -1
    taskid: 7d222eac-395c-47ec-88f4-db036d572bbd
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2965\n  }\n}"
  '25':
    id: '25'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '37'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 40e5d7d2-1ea1-417f-8110-c78fff946029
      iscommand: true
      name: Get users
      script: '|||esm-get-user-list'
      type: regular
      version: -1
    taskid: 40e5d7d2-1ea1-417f-8110-c78fff946029
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2965\n  }\n}"
  '26':
    id: '26'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '37'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 6047d94f-2aa4-4313-8712-6cd570b5706c
      iscommand: true
      name: Get organizations
      script: '|||esm-get-organization-list'
      type: regular
      version: -1
    taskid: 6047d94f-2aa4-4313-8712-6cd570b5706c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 2965\n  }\n}"
  '27':
    id: '27'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      assignedUser: {}
      assignee: {}
      customEnd: {}
      customStart: {}
      filters: {}
      id:
        simple: ${Case.ID}
      maxWait: {}
      organization: {}
      queryType: {}
      severity: {}
      status:
        simple: Closed
      summary: {}
      timeRange: {}
    separatecontext: false
    task:
      brand: ''
      id: ef0596aa-cc23-4d2b-8376-e4a1909a7333
      iscommand: true
      name: Close Case
      script: '|||esm-edit-case'
      type: regular
      version: -1
    taskid: ef0596aa-cc23-4d2b-8376-e4a1909a7333
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1215\n  }\n}"
  '28':
    id: '28'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '37'
    note: false
    scriptarguments:
      customEnd: {}
      customStart: {}
      fields:
        simple: SrcIP,IPSIDAlertID,DstIP
      filters:
        simple: '[{  "type": "EsmFieldFilter",  "field": {"name": "SrcIP"},  "operator":
          "EQUALS",   "values": [{  "type": "EsmBasicValue",    "value": "199.203.151.209"  }]  }]'
      maxWait: {}
      queryType: {}
      timeRange:
        simple: CURRENT_DAY
    separatecontext: false
    task:
      brand: ''
      id: 59b77a71-31e8-445a-84b8-f8502ea9a3fa
      iscommand: true
      name: Search by fields
      script: '|||esm-search'
      type: regular
      version: -1
    taskid: 59b77a71-31e8-445a-84b8-f8502ea9a3fa
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 2965\n  }\n}"
  '29':
    id: '29'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '27'
    note: false
    scriptarguments:
      name:
        simple: Research_${TimeNowUnix}
      show_in_case_pane: {}
    separatecontext: false
    task:
      brand: ''
      id: e4c94277-90dc-4b83-8553-202cdf791a0c
      iscommand: true
      name: Add a new case status named with timestamp
      script: '|||esm-add-case-status'
      type: regular
      version: -1
    taskid: e4c94277-90dc-4b83-8553-202cdf791a0c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1040\n  }\n}"
  '30':
    id: '30'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      contextKey: {}
      date: {}
      dateFormat: {}
      extend-context: {}
      hoursAgo: {}
      minutesAgo: {}
      monthsAgo: {}
    separatecontext: false
    task:
      brand: ''
      id: 363dde45-3b64-4ef4-8ebf-2b4830341f9a
      iscommand: false
      name: Setup
      scriptName: GetTime
      type: regular
      version: -1
    taskid: 363dde45-3b64-4ef4-8ebf-2b4830341f9a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 515\n  }\n}"
  '31':
    id: '31'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '34'
    note: false
    scriptarguments:
      assignedUser: {}
      customEnd: {}
      customStart: {}
      timeRange:
        simple: LAST_3_DAYS
    separatecontext: false
    task:
      brand: ''
      id: 042fcf01-2e7f-47c9-8c7f-6e570b018375
      iscommand: true
      name: Fetch Alarms
      script: '|||esm-fetch-alarms'
      type: regular
      version: -1
    taskid: 042fcf01-2e7f-47c9-8c7f-6e570b018375
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1790,\n    \"y\": 2090\n  }\n}"
  '32':
    id: '32'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 62f6307a-b8f5-4cae-8aec-4a465bb872b7
      iscommand: false
      name: Case Management
      type: title
      version: -1
    taskid: 62f6307a-b8f5-4cae-8aec-4a465bb872b7
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 195\n  }\n}"
  '33':
    id: '33'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '31'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 392e98ab-9297-4248-88f7-8a76953ae881
      iscommand: false
      name: Alarm Management
      type: title
      version: -1
    taskid: 392e98ab-9297-4248-88f7-8a76953ae881
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 1790,\n    \"y\": 1930\n  }\n}"
  '34':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Alarm.ID
          operator: isExists
      label: 'yes'
    id: '34'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '37'
      'yes':
      - '35'
    note: false
    scriptarguments:
      expectedValue: {}
      fields: {}
      path: {}
    separatecontext: false
    task:
      brand: ''
      id: 0d0d5658-85a3-4310-85db-0da3f51d9668
      iscommand: false
      name: Check if we got results
      type: condition
      version: -1
    taskid: 0d0d5658-85a3-4310-85db-0da3f51d9668
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 1790,\n    \"y\": 2265\n  }\n}"
  '35':
    id: '35'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '39'
    note: false
    scriptarguments:
      alarmId:
        complex:
          accessor: ID
          root: Alarm
          transformers:
          - operator: GetFirstObject
    separatecontext: false
    task:
      brand: ''
      id: 1f3e40a9-f6fb-47ee-8287-407ed886738a
      iscommand: true
      name: 'Get Event list of alarm '
      script: '|||esm-list-alarm-events'
      type: regular
      version: -1
    taskid: 1f3e40a9-f6fb-47ee-8287-407ed886738a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1902.5,\n    \"y\": 2440\n  }\n}"
  '36':
    id: '36'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '38'
    note: false
    scriptarguments:
      eventId:
        complex:
          accessor: ID
          root: EsmAlarmEvent
    separatecontext: false
    task:
      brand: ''
      id: 528e4d17-1a54-441c-8be6-5cfeb8f0ea8b
      iscommand: true
      name: Get specific event details
      script: '|||esm-get-alarm-event-details'
      type: regular
      version: -1
    taskid: 528e4d17-1a54-441c-8be6-5cfeb8f0ea8b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1790,\n    \"y\": 2790\n  }\n}"
  '37':
    id: '37'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 2d666b32-9a98-4e65-84b2-f385d009fd16
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 2d666b32-9a98-4e65-84b2-f385d009fd16
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 3140\n  }\n}"
  '38':
    id: '38'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '37'
    note: false
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: EsmAlarmEvent.SrcMac
    separatecontext: false
    task:
      brand: ''
      id: ee474fc6-a791-447b-8dcf-2eff1c323ae4
      iscommand: false
      name: Validate event details context
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: ee474fc6-a791-447b-8dcf-2eff1c323ae4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1790,\n    \"y\": 2965\n  }\n}"
  '39':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: EsmAlarmEvent.ID
          operator: isExists
      label: 'yes'
    id: '39'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '37'
      'yes':
      - '36'
    note: false
    scriptarguments:
      expectedValue: {}
      fields: {}
      path: {}
    separatecontext: false
    task:
      brand: ''
      id: 028ccce3-d5f1-4238-8310-4f7cafe28997
      iscommand: false
      name: Check if we got results
      type: condition
      version: -1
    taskid: 028ccce3-d5f1-4238-8310-4f7cafe28997
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 1902.5,\n    \"y\": 2615\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '30'
    note: false
    scriptarguments:
      additional: {}
      all:
        simple: 'yes'
      contextKey: {}
      data: {}
      filter: {}
      filterType: {}
      key: {}
      out: {}
      table: {}
      title: {}
      verbose: {}
      xml: {}
    separatecontext: false
    task:
      brand: ''
      id: 3ae4d425-f495-4933-83c9-1743b219cf71
      iscommand: false
      name: Clear Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 3ae4d425-f495-4933-83c9-1743b219cf71
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 340\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '29'
    note: false
    scriptarguments:
      assignedUser: {}
      assignee: {}
      customEnd: {}
      customStart: {}
      filters: {}
      id:
        simple: ${Case.ID}
      maxWait: {}
      organization:
        simple: LuthorCorp
      queryType: {}
      severity:
        simple: '50'
      status: {}
      summary:
        simple: editing first case
      timeRange: {}
    separatecontext: false
    task:
      brand: ''
      id: 5b144d8b-8570-4b8f-8b64-d9ee85136bef
      iscommand: true
      name: Edit severity, organization and summary
      script: '|||esm-edit-case'
      type: regular
      version: -1
    taskid: 5b144d8b-8570-4b8f-8b64-d9ee85136bef
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 865\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    scriptarguments:
      field1: {}
      field2: {}
      field3: {}
      field4: {}
      id:
        simple: ${Case.ID}
      value1: {}
      value2: {}
      value3: {}
      value4: {}
    separatecontext: false
    task:
      brand: ''
      id: cf5f24bd-5ac7-4d32-84fb-a6fb79eda330
      iscommand: true
      name: Get case info after event assignment
      script: '|||esm-get-case-detail'
      type: regular
      version: -1
    taskid: cf5f24bd-5ac7-4d32-84fb-a6fb79eda330
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1740\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 3155,\n      \"width\": 2232.5,\n      \"x\": 50,\n      \"y\"\
  : 50\n    }\n  }\n}"
