description: '-'
id: CuckooTest
inputs: []
name: CuckooTest
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: '-'
      id: 72626119-b97c-4141-82ef-370fb9ed3b11
      iscommand: false
      name: ''
      version: -1
    taskid: 72626119-b97c-4141-82ef-370fb9ed3b11
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile: {}
      unsecure: {}
      url:
        simple: https://github.com/demisto/content/raw/master/TestData/pdf_noeof.pdf
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: getting file using get
      id: 4a4101e9-b07d-4186-8686-c71d8ccbbb3a
      iscommand: false
      name: Get file
      scriptName: http
      type: regular
      version: -1
    taskid: 4a4101e9-b07d-4186-8686-c71d8ccbbb3a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: delete context
      id: bcb8b1fd-eaad-4e8e-858a-1e3af6fb620c
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: bcb8b1fd-eaad-4e8e-858a-1e3af6fb620c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 865\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://github.com/demisto/content/raw/master/TestData/pdf-example-password.pdf
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: getting file using get
      id: 6a88f674-9d86-478a-8b8c-2e95b4bdaf6f
      iscommand: false
      name: Get file
      scriptName: http
      type: regular
      version: -1
    taskid: 6a88f674-9d86-478a-8b8c-2e95b4bdaf6f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: delete context
      id: 08d587b8-ddf0-4212-85c5-af9491110886
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 08d587b8-ddf0-4212-85c5-af9491110886
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      File:
        simple: ${File}
    separatecontext: true
    task:
      brand: ''
      description: start detonation playbook file
      id: 73d4c5e5-b609-49e8-8b60-ba8e395e7b8b
      iscommand: false
      name: Detonate File - Cuckoo
      playbookName: Detonate File - Cuckoo
      type: playbook
      version: -1
    taskid: 73d4c5e5-b609-49e8-8b60-ba8e395e7b8b
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 545\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      description: done file
      id: 44a55722-69e1-4453-8dce-7ba793b00045
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 44a55722-69e1-4453-8dce-7ba793b00045
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1215\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      URL:
        simple: google.com
    separatecontext: true
    task:
      brand: ''
      description: url detonation playbook
      id: 4ec9088d-1ec0-4831-84b6-7f8c2d267263
      iscommand: false
      name: Detonate URL - Cuckoo
      playbookName: Detonate URL - Cuckoo
      type: playbook
      version: -1
    taskid: 4ec9088d-1ec0-4831-84b6-7f8c2d267263
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1040\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: done file detonate
      id: 9195d534-6cd8-4d62-8eba-aea963b1770c
      iscommand: false
      name: FileDetonate Done
      type: title
      version: -1
    taskid: 9195d534-6cd8-4d62-8eba-aea963b1770c
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 720\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1230,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
