id: IntSights Mssp Test
inputs: []
name: IntSights Mssp Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 4de7dcd9-7e58-432e-8ef4-2d0c6335b348
      iscommand: false
      name: ''
      version: -1
    taskid: 4de7dcd9-7e58-432e-8ef4-2d0c6335b348
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 229f401f-a723-4b35-8872-61557ffd9f9f
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 229f401f-a723-4b35-8872-61557ffd9f9f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 3349a8e5-321b-4d03-8847-e9989f53f8a9
      iscommand: true
      name: Test mssp feature
      script: '|||intsights-mssp-get-sub-accounts'
      type: regular
      version: -1
    taskid: 3349a8e5-321b-4d03-8847-e9989f53f8a9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      'no':
      - '4'
    note: false
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        simple: IntSights.MsspAccount.[0].ID
      right:
        simple: IntSights.MsspAccount.[1].ID
    separatecontext: false
    task:
      brand: ''
      id: 5a86fc55-6c7e-4be8-8a34-43f12cc3867c
      iscommand: false
      name: Test mssp different sub accounts
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: 5a86fc55-6c7e-4be8-8a34-43f12cc3867c
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: cc834b16-193c-421e-8d50-b4ba8fc376f4
      iscommand: false
      name: Good result
      type: title
      version: -1
    taskid: cc834b16-193c-421e-8d50-b4ba8fc376f4
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 735,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
