id: SymantecMSSTest
inputs: []
name: SymantecMSSTest
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '2'
    task:
      brand: ''
      id: e8ad073e-45f1-4d5d-86a2-5a3f69af231d
      iscommand: false
      name: ''
      version: -1
    taskid: e8ad073e-45f1-4d5d-86a2-5a3f69af231d
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '3'
    scriptarguments:
      max: {}
      severities: {}
      sourceIp: {}
      time: {}
    task:
      brand: Symantec MSS
      description: Get a list of incidents
      id: 526d531e-5b08-4489-8b31-d941e3cee175
      iscommand: true
      name: symantec-mss-incidents-list
      script: Symantec MSS|||symantec-mss-incidents-list
      type: regular
      version: -1
    taskid: 526d531e-5b08-4489-8b31-d941e3cee175
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '1'
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    task:
      brand: ''
      description: Delete field from context
      id: 33c8cbb8-ae53-44b5-8081-5dd100247b07
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 33c8cbb8-ae53-44b5-8081-5dd100247b07
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '5'
    scriptarguments:
      expectedValue: {}
      field1: {}
      field2: {}
      field3: {}
      field4: {}
      fields:
        simple: GlobalLookbackDays,DestOrganizationName,DaysSeenInLast30Days,UpdateTimestampGMT,CountryName,LatestKeyEvent,Correlation,DaysSeenGlobally,CountryCode,Classification,UserList,HostNameList,IsInternalExternal,SourceIPString,CountryOfOrigin,SourceOrganizationName,PrevalenceGlobally,FirstSeenInLast30Days,CustomerSeverity,FirstSeenGlobally,IncidentNumber,Severity,Category
      humanReadableEntryId: {}
      path:
        simple: Symantec MSS.Incidents list
      substring: {}
      value1: {}
      value2: {}
      value3: {}
      value4: {}
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: a48e2b92-0d09-4ad2-87e8-02f73d646e96
      iscommand: false
      name: VerifyContext
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: a48e2b92-0d09-4ad2-87e8-02f73d646e96
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '6'
    scriptarguments:
      number:
        simple: '1'
    task:
      brand: Symantec MSS
      description: Query an incident by number
      id: cc5c3bfc-337c-41a3-861a-3367f2bf1737
      iscommand: true
      name: symantec-mss-get-incident
      script: Symantec MSS|||symantec-mss-get-incident
      type: regular
      version: -1
    taskid: cc5c3bfc-337c-41a3-861a-3367f2bf1737
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '4'
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    task:
      brand: ''
      description: Delete field from context
      id: c83a1e0f-56ba-49ca-8ff8-612039672692
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: c83a1e0f-56ba-49ca-8ff8-612039672692
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '7'
    scriptarguments:
      expectedValue: {}
      fields:
        simple: CountryName,CountryCode,AnalyswtAssesment,Classification,IncidentComments,IncidentAttachmentItems,WorkflowDetail,SignatureList,RelatedIncidents,IncidentNumber,TimeCreated,RelatedTickets,Description
      path:
        simple: Symantec MSS.Inident query
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 24d40e58-6dbd-482e-8753-38fb0379bda0
      iscommand: false
      name: VerifyContext
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 24d40e58-6dbd-482e-8753-38fb0379bda0
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '8'
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    task:
      brand: ''
      description: Delete field from context
      id: 042b5c8b-8821-42b1-8e99-2f2b7334a08c
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 042b5c8b-8821-42b1-8e99-2f2b7334a08c
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '8':
    id: '8'
    scriptarguments:
      assignOrganization: {}
      assignPerson: {}
      comments: {}
      number:
        simple: '1'
      reference: {}
      resolution:
        simple: Resolved
      severity: {}
      status:
        simple: Closed
    task:
      brand: Symantec MSS
      description: Updates an incident's workflow by incident number
      id: 54ec948f-07fe-467d-87fe-a3c36e008c06
      iscommand: true
      name: symantec-mss-update-incident
      script: Symantec MSS|||symantec-mss-update-incident
      type: regular
      version: -1
    taskid: 54ec948f-07fe-467d-87fe-a3c36e008c06
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1465,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
