description: ''
id: DemistoUploadFile Test
inputs: []
name: DemistoUploadFile Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 75b97996-ebf9-4315-8df6-46600829df39
      iscommand: false
      name: ''
      version: -1
    taskid: 75b97996-ebf9-4315-8df6-46600829df39
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      body: {}
      filename:
        simple: image.png
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure:
        simple: 'true'
      url:
        simple: https://3xqz5p387rui1hjtdv1up7lw-wpengine.netdna-ssl.com/wp-content/uploads/2018/05/Demisto_Logo.png
      username: {}
    separatecontext: false
    task:
      brand: ''
      id: fcb02f8d-637b-4eee-88e7-85f8522bd8ce
      iscommand: false
      name: Download Image and Add to Context
      scriptName: http
      type: regular
      version: -1
    taskid: fcb02f8d-637b-4eee-88e7-85f8522bd8ce
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      entryID:
        complex:
          accessor: EntryID
          filters:
          - - left:
                iscontext: true
                value:
                  simple: File.Name
              operator: isEqualString
              right:
                value:
                  simple: image.png
          root: File
      incidentID:
        complex:
          root: CreatedIncidentID
    separatecontext: false
    task:
      brand: ''
      description: Upload file from incident war room to another incident's war room
      id: a8be3052-aa11-4ef5-881d-31f441d77274
      iscommand: false
      name: Upload Downloaded File to War Room
      scriptName: DemistoUploadFile
      type: regular
      version: -1
    taskid: a8be3052-aa11-4ef5-881d-31f441d77274
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      app: {}
      assetid: {}
      attachmentcount: {}
      attachmentextension: {}
      attachmenthash: {}
      attachmentid: {}
      attachmentname: {}
      attachmentsize: {}
      attachmenttype: {}
      bugtraq: {}
      customFields: {}
      cve: {}
      cvss: {}
      dest: {}
      destntdomain: {}
      details: {}
      duration: {}
      emailbcc: {}
      emailbody: {}
      emailbodyformat: {}
      emailbodyhtml: {}
      emailcc: {}
      emailclientname: {}
      emailfrom: {}
      emailinreplyto: {}
      emailkeywords: {}
      emailmessageid: {}
      emailreceived: {}
      emailreplyto: {}
      emailreturnpath: {}
      emailsenderip: {}
      emailsize: {}
      emailsource: {}
      emailsubject: {}
      emailto: {}
      emailtocount: {}
      emailurlclicked: {}
      entryIDs: {}
      filehash: {}
      filename: {}
      filepath: {}
      labels: {}
      malwarefamily: {}
      name:
        simple: DemistoUploadFile - test incident
      occurred: {}
      owner: {}
      phase: {}
      roles: {}
      severity: {}
      signature: {}
      sla: {}
      slaField: {}
      src: {}
      srcntdomain: {}
      srcuser: {}
      systems: {}
      type: {}
      user: {}
      vendorid: {}
      vendorproduct: {}
      vulnerabilitycategory: {}
    separatecontext: false
    task:
      brand: Builtin
      description: Create a new incident
      id: b3094930-1c69-4a7a-8a8c-20c1d4ebc3d2
      iscommand: true
      name: createNewIncident
      script: Builtin|||createNewIncident
      type: regular
      version: -1
    taskid: b3094930-1c69-4a7a-8a8c-20c1d4ebc3d2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: dbc0c9fc-bf19-4007-89fd-e6b08502fd0e
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: dbc0c9fc-bf19-4007-89fd-e6b08502fd0e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      id:
        complex:
          root: CreatedIncidentID
    separatecontext: false
    task:
      brand: Builtin
      description: Retrieve context of another incident to be used in this script
      id: 82894ee2-eab9-4144-89f1-eb6f29d27962
      iscommand: true
      name: getContext
      script: Builtin|||getContext
      type: regular
      version: -1
    taskid: 82894ee2-eab9-4144-89f1-eb6f29d27962
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      contextKey:
        simple: DemistoUploadFile
      entryId:
        simple: ${lastCompletedTaskEntries.[0]}
      listSeperator: {}
    separatecontext: false
    task:
      brand: ''
      description: "Takes the comments of a given entry ID and stores them in the\
        \ incident context, under a provided context key. \nFor accessing the last\
        \ executed task's comments, provide ${lastCompletedTaskEntries.[0]} as the\
        \ value for the entryId input parameter."
      id: 280413a6-fb84-4400-8752-48bd03fc5b78
      iscommand: false
      name: commentsToContext
      scriptName: commentsToContext
      type: regular
      version: -1
    taskid: 280413a6-fb84-4400-8752-48bd03fc5b78
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '7':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: context.File
                root: DemistoUploadFile
          operator: isExists
      label: 'yes'
    id: '7'
    ignoreworker: false
    nexttasks:
      'yes':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 351e01a5-1ee7-42fc-8b73-134b3cb55174
      iscommand: false
      name: Verify upload was successful
      type: condition
      version: -1
    taskid: 351e01a5-1ee7-42fc-8b73-134b3cb55174
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 927a19f8-437c-4ea9-8475-01a95340e330
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 927a19f8-437c-4ea9-8475-01a95340e330
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1435,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
