description: Test playbook for mcafee ATD and for its File and URL detonation playbooks.
id: Test Playbook McAfee ATD
inputs: []
name: Test Playbook McAfee ATD
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: '-'
      id: 5ad1e361-21d6-4fce-83ae-9d0d9c4ef24f
      iscommand: false
      name: ''
      version: -1
    taskid: 5ad1e361-21d6-4fce-83ae-9d0d9c4ef24f
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Returns a logon result for ATD
      id: 93f72f9a-6f0d-4252-852d-68e5cacf9062
      iscommand: true
      name: atd-login
      script: '|||atd-login'
      type: regular
      version: -1
    taskid: 93f72f9a-6f0d-4252-852d-68e5cacf9062
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 515\n  }\n}"
  '16':
    id: '16'
    nexttasks:
      '#none#':
      - '21'
    note: false
    scriptarguments:
      data:
        simple: jmyetnrhk96lktrshfdghj74
      entryId: {}
      filename:
        simple: excel.xls
    separatecontext: false
    task:
      brand: ''
      description: 'Will create a file (using the given data input or entry ID) and
        upload it to current investigation war room.

        '
      id: ba669fdf-8eb3-410d-819f-6d5d3ed5b9e3
      iscommand: false
      name: FileCreateAndUpload
      scriptName: FileCreateAndUpload
      type: regular
      version: -1
    taskid: ba669fdf-8eb3-410d-819f-6d5d3ed5b9e3
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1565\n  }\n}"
  '18':
    id: '18'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: finished
      id: d60917a3-b82f-4450-8c31-d933f9da8992
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d60917a3-b82f-4450-8c31-d933f9da8992
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1915\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 2444ef96-ae7d-463b-8342-467e915776b5
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 2444ef96-ae7d-463b-8342-467e915776b5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 340\n  }\n}"
  '21':
    id: '21'
    nexttasks:
      '#none#':
      - '18'
    note: false
    separatecontext: true
    task:
      brand: ''
      id: 110e1659-0dc7-444d-88fb-73ad813b0e3b
      iscommand: false
      name: ATD - Detonate File
      playbookName: ATD - Detonate File
      type: playbook
      version: -1
    taskid: 110e1659-0dc7-444d-88fb-73ad813b0e3b
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1740\n  }\n}"
  '22':
    id: '22'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '18'
    note: false
    scriptarguments:
      Interval:
        simple: '1'
      Timeout:
        simple: '15'
      URL:
        simple: https://www.demisto.com
    separatecontext: true
    task:
      brand: ''
      id: 4cfef8f4-bda1-4d4c-88f8-9d318c54741b
      iscommand: false
      name: Detonate URL - McAfee ATD
      playbookName: Detonate URL - McAfee ATD
      type: playbook
      version: -1
    taskid: 4cfef8f4-bda1-4d4c-88f8-9d318c54741b
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1740\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '2'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 14c67466-163c-4575-8e87-c9d4f3b90dfe
      iscommand: false
      name: Test Playbook McAfee ATD
      type: title
      version: -1
    taskid: 14c67466-163c-4575-8e87-c9d4f3b90dfe
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      'yes':
      - '5'
    note: false
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        simple: ${ATD.Session.UserId}
      right:
        simple: '1'
    separatecontext: false
    task:
      brand: ''
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: 44a69b4b-808b-46a9-8ac9-8fe2a63ac7ab
      iscommand: false
      name: atd-login AreValuesEqual
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: 44a69b4b-808b-46a9-8ac9-8fe2a63ac7ab
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 690\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      userType: {}
    separatecontext: false
    task:
      brand: ''
      description: ' displays the user profile information present on the McAfee Advanced
        Threat Defense.'
      id: 6717e324-23bc-40fe-8299-70ecf1aec986
      iscommand: true
      name: atd-list-user
      script: '|||atd-list-user'
      type: regular
      version: -1
    taskid: 6717e324-23bc-40fe-8299-70ecf1aec986
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 865\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      'yes':
      - '7'
    note: false
    results:
    - AreValuesEqual
    scriptarguments:
      left:
        complex:
          accessor: Users.FullName
          filters:
          - - left:
                iscontext: true
                value:
                  simple: ATD.Users.FullName
              operator: containsGeneral
              right:
                value:
                  simple: ATD upload Admin
          root: ATD
      right:
        simple: ATD upload Admin
    separatecontext: false
    task:
      brand: ''
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: b5403b6b-3571-4bae-8866-f396f1c641c3
      iscommand: false
      name: AreValuesEqual
      scriptName: AreValuesEqual
      type: condition
      version: -1
    taskid: b5403b6b-3571-4bae-8866-f396f1c641c3
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1040\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ' display the analyzer profiles. Only the analyzer profiles to
        which the user has access are displayed.'
      id: 78ce8e32-9935-4d0d-8ae0-3a78b8c9c792
      iscommand: true
      name: atd-list-analyzer-profiles
      script: '|||atd-list-analyzer-profiles'
      type: regular
      version: -1
    taskid: 78ce8e32-9935-4d0d-8ae0-3a78b8c9c792
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1215\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      'yes':
      - '16'
      - '22'
    note: false
    scriptarguments:
      value:
        simple: ${ATD.ListAnalyzerProfiles}
    separatecontext: false
    task:
      brand: ''
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: cea2229b-466a-4fdc-88a7-a97cf63c3500
      iscommand: false
      name: Exists
      scriptName: Exists
      type: condition
      version: -1
    taskid: cea2229b-466a-4fdc-88a7-a97cf63c3500
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1390\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1930,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
