id: McAfee-MAR_Test
inputs: []
name: McAfee-MAR_Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '9'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 383c2b00-fa66-4cbe-8547-6dde49d9bd55
      iscommand: false
      name: ''
      version: -1
    taskid: 383c2b00-fa66-4cbe-8547-6dde49d9bd55
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": -120\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    note: false
    separatecontext: false
    task:
      brand: McAfee Active Response
      description: Returns a list of all collectors and their outputs
      id: f504d547-a230-4c77-8113-d85c7cf46b8f
      iscommand: true
      name: mar-collectors-list
      script: McAfee Active Response|||mar-collectors-list
      type: regular
      version: -1
    taskid: f504d547-a230-4c77-8113-d85c7cf46b8f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: c1a381b3-9371-4b7b-8bba-ffab18950c86
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: c1a381b3-9371-4b7b-8bba-ffab18950c86
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1430\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      collector:
        simple: HostInfo
      filter-by: {}
      filter-operator: {}
      filter-value: {}
      outputs: {}
    separatecontext: false
    task:
      brand: McAfee Active Response
      description: Search endpoint data
      id: c8d110a2-bc74-45b3-8dd6-6decdedd80f8
      iscommand: true
      name: mar-search
      script: McAfee Active Response|||mar-search
      type: regular
      version: -1
    taskid: c8d110a2-bc74-45b3-8dd6-6decdedd80f8
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      expectedValue: {}
      fields:
        simple: os,created_at,hostname,ip_address
      path:
        simple: MAR.HostInfo
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 9dbfa549-9ece-492e-8d88-d70aeab9840a
      iscommand: false
      name: VerifyContext mar-search
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 9dbfa549-9ece-492e-8d88-d70aeab9840a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      collector:
        simple: Processes
      filter-by:
        simple: name
      filter-operator:
        simple: Equals
      filter-value:
        simple: SYSTEM
      outputs:
        simple: user_id,name,uptime
    separatecontext: false
    task:
      brand: McAfee Active Response
      description: '!mar-search collector=Processes filter-by=name filter-operator=Equals
        filter-value=SYSTEM outputs=user_id,name,uptime'
      id: 37da63cf-c285-4793-88db-b7e8baee04ac
      iscommand: true
      name: mar-search with filter
      script: McAfee Active Response|||mar-search
      type: regular
      version: -1
    taskid: 37da63cf-c285-4793-88db-b7e8baee04ac
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      expectedValue: {}
      fields:
        simple: user_id,name,uptime
      path:
        simple: MAR.Processes
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 55011276-cd95-4732-83c6-78c34a2f0c4a
      iscommand: false
      name: VerifyContext mar-search with filter
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 55011276-cd95-4732-83c6-78c34a2f0c4a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      collectors:
        simple: HostInfo
      filter-by: {}
      filter-operator: {}
      filter-value: {}
      filter_collector: {}
    separatecontext: false
    task:
      brand: McAfee Active Response
      description: '!mar-search-multiple collectors=HostInfo,Processes filter_collector=HostInfo
        filter-by=hostname filter-operator=Equals filter-value=ADMIN-PC'
      id: fa73b2c9-2813-4fa4-82a5-16b457d65d05
      iscommand: true
      name: mar-search-multiple
      script: McAfee Active Response|||mar-search-multiple
      type: regular
      version: -1
    taskid: fa73b2c9-2813-4fa4-82a5-16b457d65d05
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '8':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: SearchMultiple
                root: MAR
                transformers:
                - args:
                    index:
                      value:
                        simple: '0'
                  operator: atIndex
          operator: isExists
      label: 'yes'
    id: '8'
    nexttasks:
      'yes':
      - '10'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 11941a95-0a2a-46a6-8226-917ee997d4e0
      iscommand: false
      name: Check search multiple
      type: condition
      version: -1
    taskid: 11941a95-0a2a-46a6-8226-917ee997d4e0
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1260\n  }\n}"
  '9':
    id: '9'
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: dfadcb24-11ee-4142-84cd-5230375dc9cc
      iscommand: false
      name: Delete context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: dfadcb24-11ee-4142-84cd-5230375dc9cc
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 20\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1615,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": -120\n\
  \    }\n  }\n}"
