id: urlscan_malicious_Test
inputs: []
name: urlscan_malicious_Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '24'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: ea63e051-33b1-4a6f-863a-169298759981
      iscommand: false
      name: ''
      version: -1
    taskid: ea63e051-33b1-4a6f-863a-169298759981
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      limit: {}
      searchParameter:
        simple: shlepme.com
      url:
        simple: shlepme.com
    separatecontext: false
    task:
      brand: ''
      description: Check if file MD5 is malicious
      id: e28b9c44-6bd9-4e9c-838d-41caee5c715a
      iscommand: true
      name: Check non-malicious url
      script: '|||urlscan-search'
      type: regular
      version: -1
    taskid: e28b9c44-6bd9-4e9c-838d-41caee5c715a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1710\n  }\n}"
  '11':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: URLScan.Domain
          operator: isEqualString
          right:
            value:
              simple: shlepme.com
      label: 'yes'
    id: '11'
    ignoreworker: false
    nexttasks:
      'yes':
      - '12'
    note: false
    scriptarguments:
      additional: {}
      data: {}
      filter: {}
      filterType: {}
      out: {}
    separatecontext: false
    task:
      brand: ''
      description: Filter context keys by applying one of the various available manipulations
        and storing in a new context key. Please notice that the resulting context
        key will not be available automatically as an option but you can still specify
        it.
      id: 06cffd37-650e-41c4-812a-51789f03771c
      iscommand: false
      name: Get result
      type: condition
      version: -1
    taskid: 06cffd37-650e-41c4-812a-51789f03771c
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1885\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: a124863b-c027-421d-8622-647ef81ac352
      iscommand: false
      name: Rate Limiting Test
      type: title
      version: -1
    taskid: a124863b-c027-421d-8622-647ef81ac352
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2060\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 97ab4e87-b89c-47fa-80e1-ebfea613944a
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 97ab4e87-b89c-47fa-80e1-ebfea613944a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1535\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    scriptarguments:
      limit: {}
      long: {}
      public: {}
      retries:
        simple: '3'
      threshold: {}
      timeout: {}
      url:
        simple: https://www.demisto.com
      wait:
        simple: '23'
    separatecontext: false
    task:
      brand: urlscan.io
      description: Submit a url to scan
      id: 9fc52f8b-997f-4338-8802-c8cd08e521a8
      iscommand: true
      name: Multiple url submission(rate limit test)
      script: urlscan.io|||url
      type: regular
      version: -1
    taskid: 9fc52f8b-997f-4338-8802-c8cd08e521a8
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2205\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    scriptarguments:
      limit: {}
      long: {}
      public: {}
      retries:
        simple: '2'
      threshold: {}
      timeout: {}
      url:
        simple: https://www.ebay.com
      wait:
        simple: '20'
    separatecontext: false
    task:
      brand: urlscan.io
      description: Submit a url to scan
      id: 9beb3f70-5c01-4ed5-83ff-6be35945035d
      iscommand: true
      name: url
      script: urlscan.io|||url
      type: regular
      version: -1
    taskid: 9beb3f70-5c01-4ed5-83ff-6be35945035d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2380\n  }\n}"
  '16':
    id: '16'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '20'
    note: false
    scriptarguments:
      limit: {}
      long: {}
      public: {}
      retries:
        simple: '2'
      threshold: {}
      timeout: {}
      url:
        simple: https://www.paloaltonetworks.com
      wait:
        simple: '21'
    separatecontext: false
    task:
      brand: urlscan.io
      description: Submit a url to scan
      id: 0979373f-503b-441f-895c-bfdfd9958237
      iscommand: true
      name: url
      script: urlscan.io|||url
      type: regular
      version: -1
    taskid: 0979373f-503b-441f-895c-bfdfd9958237
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2555\n  }\n}"
  '17':
    id: '17'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '19'
    note: false
    scriptarguments:
      limit: {}
      long: {}
      public: {}
      retries:
        simple: '5'
      sampleSize: {}
      submitWait: {}
      threshold: {}
      timeout: {}
      url:
        simple: http://malware.wicar.org/data/js_crypto_miner.html
      wait:
        simple: '10'
    separatecontext: false
    task:
      brand: urlscan.io
      description: Submit a url to scan
      id: ac163943-88fc-49bf-8d83-5667a2266696
      iscommand: true
      name: Check another Malicious url
      script: urlscan.io|||url
      type: regular
      version: -1
    taskid: ac163943-88fc-49bf-8d83-5667a2266696
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1040\n  }\n}"
  '18':
    id: '18'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 5a056b1b-637b-4d9c-88ff-f3cbf2dea99f
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 5a056b1b-637b-4d9c-88ff-f3cbf2dea99f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 865\n  }\n}"
  '19':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Score
                root: DBotScore
          operator: isEqualNumber
          right:
            value:
              simple: '3'
      label: 'yes'
    id: '19'
    ignoreworker: false
    nexttasks:
      'yes':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 7aba8ec6-7d38-4ef9-8fb0-60ef9a6ed7c9
      iscommand: false
      name: Check DBot score is 3
      type: condition
      version: -1
    taskid: 7aba8ec6-7d38-4ef9-8fb0-60ef9a6ed7c9
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1215\n  }\n}"
  '20':
    id: '20'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '21'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 45145044-4d25-487a-80dd-d69f7b0573de
      iscommand: false
      name: HTTP Transaction Test
      type: title
      version: -1
    taskid: 45145044-4d25-487a-80dd-d69f7b0573de
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2730\n  }\n}"
  '21':
    id: '21'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '22'
    note: false
    scriptarguments:
      limit: {}
      timeout:
        simple: '120'
      url:
        simple: http://demisto.com
      wait_time_for_polling:
        simple: '10'
    separatecontext: false
    task:
      brand: ''
      description: This script enables gives you the functionallity of getting the
        http transactions made for a given URL using the UrlScan integration
      id: a12fc4ca-e33a-4ea6-8042-6aa94e9f9b16
      iscommand: false
      name: get http transactions
      scriptName: UrlscanGetHttpTransactions
      type: regular
      version: -1
    taskid: a12fc4ca-e33a-4ea6-8042-6aa94e9f9b16
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2875\n  }\n}"
  '22':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: httpTransaction
                root: URLScan
          operator: containsString
          right:
            value:
              simple: demisto.com
      label: 'yes'
    id: '22'
    ignoreworker: false
    nexttasks:
      'yes':
      - '25'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 9df3542e-2f65-41b9-80d2-cabf7d4ebcfc
      iscommand: false
      name: validate http transaction
      type: condition
      version: -1
    taskid: 9df3542e-2f65-41b9-80d2-cabf7d4ebcfc
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3050\n  }\n}"
  '23':
    id: '23'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 5aed811e-b2c7-41d1-8e8f-9180c86daf32
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 5aed811e-b2c7-41d1-8e8f-9180c86daf32
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3895\n  }\n}"
  '24':
    id: '24'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 7b525f77-394a-495b-8e14-f17e254258de
      iscommand: false
      name: Malicious URLs
      type: title
      version: -1
    taskid: 7b525f77-394a-495b-8e14-f17e254258de
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '25':
    id: '25'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '26'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: bd84959b-e9aa-4dd4-8e1f-5087b29b40c2
      iscommand: false
      name: Batch URLs Test
      type: title
      version: -1
    taskid: bd84959b-e9aa-4dd4-8e1f-5087b29b40c2
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3225\n  }\n}"
  '26':
    id: '26'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '27'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 8791d497-23ee-469a-882d-7bfe6ca786e8
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 8791d497-23ee-469a-882d-7bfe6ca786e8
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3370\n  }\n}"
  '27':
    id: '27'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '28'
    note: false
    scriptarguments:
      limit: {}
      long: {}
      public: {}
      retries:
        simple: '5'
      sampleSize: {}
      submitWait: {}
      threshold: {}
      timeout: {}
      url:
        simple: http://urlscan.io,http://www.demisto.com
      wait:
        simple: '10'
    separatecontext: false
    task:
      brand: urlscan.io
      description: Submits a URL to scan.
      id: da77b165-1bbe-4efb-86bb-7d5b7e738c1c
      iscommand: true
      name: Batch URL Submission
      script: urlscan.io|||url
      type: regular
      version: -1
    taskid: da77b165-1bbe-4efb-86bb-7d5b7e738c1c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3545\n  }\n}"
  '28':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: DBotScore
          operator: hasLength
          right:
            value:
              simple: '2'
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Score
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: DBotScore.Indicator
                    operator: isEqualString
                    right:
                      value:
                        simple: http://www.demisto.com
                root: DBotScore
          operator: isEqualNumber
          right:
            value:
              simple: '0'
      label: 'yes'
    id: '28'
    ignoreworker: false
    nexttasks:
      'yes':
      - '23'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: b492243e-12f1-42aa-880e-d842ae0d0880
      iscommand: false
      name: Validate Results
      type: condition
      version: -1
    taskid: b492243e-12f1-42aa-880e-d842ae0d0880
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3720\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      limit: {}
      searchParameter:
        simple: malware.wicar.org
      url:
        simple: http://malware.wicar.org/data/eicar.com
    separatecontext: false
    task:
      brand: ''
      description: Check if file MD5 is malicious
      id: e039ac7f-7fa0-4fef-8113-590aea23fa49
      iscommand: true
      name: Check Malicious url
      script: '|||urlscan-search'
      type: regular
      version: -1
    taskid: e039ac7f-7fa0-4fef-8113-590aea23fa49
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 515\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 660d0ea8-da7d-407b-87f3-392c1a132417
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 660d0ea8-da7d-407b-87f3-392c1a132417
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 340\n  }\n}"
  '7':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: URLScan.Domain
          operator: isEqualString
          right:
            value:
              simple: malware.wicar.org
      label: 'yes'
    id: '7'
    ignoreworker: false
    nexttasks:
      'yes':
      - '18'
    note: false
    scriptarguments:
      additional: {}
      data: {}
      filter: {}
      filterType: {}
      out: {}
    separatecontext: false
    task:
      brand: ''
      description: Filter context keys by applying one of the various available manipulations
        and storing in a new context key. Please notice that the resulting context
        key will not be available automatically as an option but you can still specify
        it.
      id: aa129b6a-759b-42e1-8c01-940a6d9edb86
      iscommand: false
      name: Get result
      type: condition
      version: -1
    taskid: aa129b6a-759b-42e1-8c01-940a6d9edb86
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 690\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: c7d9a72d-c1be-4d91-822a-192e883a1532
      iscommand: false
      name: Not Malicious URLs
      type: title
      version: -1
    taskid: c7d9a72d-c1be-4d91-822a-192e883a1532
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1390\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 3910,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
