fromversion: 4.1.0
id: Test - CrowdStrike Falcon
inputs: []
name: Test - CrowdStrike Falcon
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 3e20bf2e-cb18-4178-8efe-caa9e28b41b2
      iscommand: false
      name: ''
      version: -1
    taskid: 3e20bf2e-cb18-4178-8efe-caa9e28b41b2
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      add_to_context: {}
      brand_name:
        simple: CrowdstrikeFalcon
      expect_data: {}
      instance_name: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 554d6588-213b-4d3e-8f8c-d942c38a6703
      iscommand: false
      name: Fetch from instance
      scriptName: FetchFromInstance
      type: regular
      version: -1
    taskid: 554d6588-213b-4d3e-8f8c-d942c38a6703
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      filter:
        simple: created_timestamp:>'2020-03-05T15:25:00Z'
      ids: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 470a8a05-50c8-47e6-8d36-ce973abdc94d
      iscommand: true
      name: Get detections by filter
      script: '|||cs-falcon-search-detection'
      type: regular
      version: -1
    taskid: 470a8a05-50c8-47e6-8d36-ce973abdc94d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Detection
                root: CrowdStrike
                transformers:
                - operator: count
          operator: greaterThanOrEqual
          right:
            value:
              simple: '1'
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 2bb78f10-176c-4ace-859c-2862b513a442
      iscommand: false
      name: Assert detections were fetched
      type: condition
      version: -1
    taskid: 2bb78f10-176c-4ace-859c-2862b513a442
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      behavior_id:
        simple: '10197'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 9526ce2e-9a6b-4216-845d-b7d803051e39
      iscommand: true
      name: Get behavior
      script: '|||cs-falcon-get-behavior'
      type: regular
      version: -1
    taskid: 9526ce2e-9a6b-4216-845d-b7d803051e39
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 720\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Behavior.Scenario
                root: CrowdStrike
          operator: isEqualString
          right:
            value:
              simple: suspicious_activity
      label: 'yes'
    id: '5'
    ignoreworker: false
    nexttasks:
      'yes':
      - '6'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 0c5b6fff-a2e8-4fea-819b-4bc2cd8e6434
      iscommand: false
      name: Assert 'suspicious_activity' scenario
      type: condition
      version: -1
    taskid: 0c5b6fff-a2e8-4fea-819b-4bc2cd8e6434
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 895\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    quietmode: 0
    scriptarguments:
      filter: {}
      hostname: {}
      ids:
        simple: c1a4575cd124419db5ed3c1e8ddc2c04,15dbb9d8f06b45fe9f61eb46e829d986
      platform_name: {}
      platfrom_name: {}
      site_name: {}
      status: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: b36b37a0-434b-48ca-8683-6243354bdf4e
      iscommand: true
      name: Get multiple devices
      script: '|||cs-falcon-search-device'
      type: regular
      version: -1
    taskid: b36b37a0-434b-48ca-8683-6243354bdf4e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1070\n  }\n}"
  '7':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Device
                root: CrowdStrike
                transformers:
                - operator: count
          operator: greaterThanOrEqual
          right:
            value:
              simple: '1'
      label: 'yes'
    id: '7'
    ignoreworker: false
    nexttasks:
      'yes':
      - '8'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 8b89d67a-947a-4e31-8f45-e9308846af86
      iscommand: false
      name: Assert devices were fetched
      type: condition
      version: -1
    taskid: 8b89d67a-947a-4e31-8f45-e9308846af86
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1245\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: dabf9864-0516-41de-8b0b-bfc4c58fe1cc
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: dabf9864-0516-41de-8b0b-bfc4c58fe1cc
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1420\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: c0d9e042-0146-4d7e-863f-c00c6f62dad2
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: c0d9e042-0146-4d7e-863f-c00c6f62dad2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1435,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
