id: Test Syslog
inputs: []
name: Test Syslog
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 45ee5f16-24fb-46f2-8c70-c2e9c55a8380
      iscommand: false
      name: ''
      version: -1
    taskid: 45ee5f16-24fb-46f2-8c70-c2e9c55a8380
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Get the Server URL.
      id: 7897b5ec-c981-4fdf-8134-50a915c9991b
      iscommand: false
      name: Get the server URL
      scriptName: GetServerURL
      type: regular
      version: -1
    taskid: 7897b5ec-c981-4fdf-8134-50a915c9991b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      address:
        simple: ${ServerURL.Host}
      facility: {}
      level: {}
      message:
        simple: This is a test from syslog
      port:
        simple: '5140'
      protocol:
        simple: TCP
    separatecontext: false
    skipunavailable: false
    task:
      brand: Syslog Sender
      description: Send a message to syslog
      id: de26d64e-1220-485d-8c5a-d6ed2b66c757
      iscommand: true
      name: syslog-send
      script: Syslog Sender|||syslog-send
      type: regular
      version: -1
    taskid: de26d64e-1220-485d-8c5a-d6ed2b66c757
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: '70'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Sleep for X seconds
      id: 8c7b75d8-f763-4790-862c-9a91a13b6b1f
      iscommand: false
      name: Wait for the incident
      scriptName: Sleep
      type: regular
      version: -1
    taskid: 8c7b75d8-f763-4790-862c-9a91a13b6b1f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      details:
        simple: syslog
      fromclosedate: {}
      fromdate: {}
      fromduedate: {}
      id: {}
      level: {}
      name: {}
      notstatus: {}
      owner: {}
      page: {}
      query: {}
      reason: {}
      size: {}
      sort: {}
      status: {}
      toclosedate: {}
      todate: {}
      toduedate: {}
      type: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Searches Demisto incidents
      id: 507be312-76f3-4d7b-8569-8c94acc0ca40
      iscommand: false
      name: SearchIncidentsV2
      scriptName: SearchIncidentsV2
      type: regular
      version: -1
    taskid: 507be312-76f3-4d7b-8569-8c94acc0ca40
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: foundIncidents
          operator: isExists
      label: 'yes'
    id: '5'
    ignoreworker: false
    nexttasks:
      'yes':
      - '6'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 2a6e2761-3cbd-43fd-8803-2319f7f973e2
      iscommand: false
      name: Found incidents?
      type: condition
      version: -1
    taskid: 2a6e2761-3cbd-43fd-8803-2319f7f973e2
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: cf3d7672-e9cb-4bf6-8126-41574aaeb1f3
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: cf3d7672-e9cb-4bf6-8126-41574aaeb1f3
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: '60'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Sleep for X seconds
      id: 755092c0-a08c-465b-8e7f-e180b597bfcf
      iscommand: false
      name: Wait for syslog
      scriptName: Sleep
      type: regular
      version: -1
    taskid: 755092c0-a08c-465b-8e7f-e180b597bfcf
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1260,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
