description: A quick demonstration of the various illuminate enrichment commands.
fromversion: 4.0.0
id: Illuminate Integration Demonstration
inputs: []
name: Illuminate Integration Demonstration
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 0681a9a8-796a-4039-8a83-3e6d2eec72b9
      iscommand: false
      name: ''
      version: -1
    taskid: 0681a9a8-796a-4039-8a83-3e6d2eec72b9
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 1770,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      extend-context:
        simple: IndicatorType=indicator_type
      value:
        simple: ${incident.details}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 1d12c401-4190-40d0-803f-ea81d67a0144
      iscommand: false
      name: Parse Incident Details
      scriptName: ParseJSON
      type: regular
      version: -1
    taskid: 1d12c401-4190-40d0-803f-ea81d67a0144
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1770,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    note: false
    scriptarguments:
      mutex:
        simple: ${incident.labels.Indicator}
    separatecontext: false
    task:
      brand: illuminate
      description: ''
      id: d836bd2a-4711-4eca-8ebd-0f87199e8d8b
      iscommand: true
      name: Enrich MUTEX with illuminate Data
      script: illuminate|||illuminate-enrich-mutex
      type: regular
      version: -1
    taskid: d836bd2a-4711-4eca-8ebd-0f87199e8d8b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 3480,\n    \"y\": 465\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    note: false
    scriptarguments:
      string:
        simple: ${incident.labels.Indicator}
    separatecontext: false
    task:
      brand: illuminate
      description: ''
      id: caa4eae5-208d-4b95-89f5-56afc12f04e4
      iscommand: true
      name: Enrich String with illuminate Data
      script: illuminate|||illuminate-enrich-string
      type: regular
      version: -1
    taskid: caa4eae5-208d-4b95-89f5-56afc12f04e4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1780,\n    \"y\": 615\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    note: false
    scriptarguments:
      ip:
        simple: ${incident.labels.Indicator}
    separatecontext: false
    task:
      brand: illuminate
      description: ''
      id: 454241c0-d230-4be0-87ed-ab11cb772071
      iscommand: true
      name: Enrich IPV4 with illuminate Data
      script: illuminate|||ip
      type: regular
      version: -1
    taskid: 454241c0-d230-4be0-87ed-ab11cb772071
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 520\n  }\n}"
  '2':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${IndicatorType}
          operator: isEqualString
          right:
            value:
              simple: Domain
      label: domain
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${IndicatorType}
          operator: isEqualString
          right:
            value:
              simple: Email
      label: email
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${IndicatorType}
          operator: isEqualString
          right:
            value:
              simple: URL
      label: url
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${IndicatorType}
          operator: inList
          right:
            value:
              simple: File MD5,File SHA-1,File SHA-256
      label: file
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${IndicatorType}
          operator: isEqualString
          right:
            value:
              simple: HTTP Request
      label: HTTP Request
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${IndicatorType}
          operator: isEqualString
          right:
            value:
              simple: IP
      - - left:
            iscontext: true
            value:
              simple: ${incident.labels.Indicator}
          operator: containsGeneral
          right:
            value:
              simple: .
      label: IPV4
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${IndicatorType}
          operator: isEqualString
          right:
            value:
              simple: IP
      - - left:
            iscontext: true
            value:
              simple: ${incident.labels.Indicator}
          operator: containsGeneral
          right:
            value:
              simple: ':'
      label: IPV6
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${IndicatorType}
          operator: isEqualString
          right:
            value:
              simple: File
      label: MUTEX
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${IndicatorType}
          operator: isEqualString
          right:
            value:
              simple: String
      label: String
    id: '2'
    ignoreworker: false
    nexttasks:
      HTTP Request:
      - '7'
      IPV4:
      - '12'
      IPV6:
      - '9'
      MUTEX:
      - '10'
      String:
      - '11'
      domain:
      - '3'
      email:
      - '4'
      file:
      - '6'
      url:
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 7533c791-824a-45ff-8e3e-8ff6301f380e
      iscommand: false
      name: Determine Indicator Type
      type: condition
      version: -1
    taskid: 7533c791-824a-45ff-8e3e-8ff6301f380e
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 1770,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    note: false
    scriptarguments:
      domain:
        simple: ${incident.labels.Indicator}
    separatecontext: false
    task:
      brand: illuminate
      description: ''
      id: 0b649084-5147-47e7-8ccb-558f7e912d33
      iscommand: true
      name: Enrich Domain with Illuminate Data
      script: illuminate|||domain
      type: regular
      version: -1
    taskid: 0b649084-5147-47e7-8ccb-558f7e912d33
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 60,\n    \"y\": 465\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    scriptarguments:
      email:
        simple: ${incident.labels.Indicator}
    separatecontext: false
    task:
      brand: illuminate
      description: ''
      id: b817ed0c-6c42-47a8-8a63-e709ee15378f
      iscommand: true
      name: Enrich Email with Illuminate Data
      script: illuminate|||email
      type: regular
      version: -1
    taskid: b817ed0c-6c42-47a8-8a63-e709ee15378f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 3060,\n    \"y\": 520\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    note: false
    scriptarguments:
      url:
        simple: ${incident.labels.Indicator}
    separatecontext: false
    task:
      brand: illuminate
      description: ''
      id: 695d2efb-66c8-4f6f-8cb0-bb41d2408384
      iscommand: true
      name: Enrich URL with illuminate Data
      script: illuminate|||url
      type: regular
      version: -1
    taskid: 695d2efb-66c8-4f6f-8cb0-bb41d2408384
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 570\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    note: false
    scriptarguments:
      file:
        simple: ${incident.labels.Indicator}
    separatecontext: false
    task:
      brand: illuminate
      description: ''
      id: 36c02b8f-c105-4707-8f4b-725d341c0434
      iscommand: true
      name: Enrich File with illuminate Data
      script: illuminate|||file
      type: regular
      version: -1
    taskid: 36c02b8f-c105-4707-8f4b-725d341c0434
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 2630,\n    \"y\": 545\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    note: false
    scriptarguments:
      http-request:
        simple: ${incident.labels.Indicator}
    separatecontext: false
    task:
      brand: illuminate
      description: ''
      id: 64e9b54f-371b-401d-80a6-a384b28db418
      iscommand: true
      name: Enrich HTTP Request with illuminate Data
      script: illuminate|||illuminate-enrich-http-request
      type: regular
      version: -1
    taskid: 64e9b54f-371b-401d-80a6-a384b28db418
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 2200,\n    \"y\": 570\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    note: false
    scriptarguments:
      ip:
        simple: ${incident.labels.Indicator}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 3bff48e6-58a5-430b-8ff8-07848026d38b
      iscommand: true
      name: Enrich IPV6 with illuminate Data
      script: '|||illuminate-enrich-ipv6'
      type: regular
      version: -1
    taskid: 3bff48e6-58a5-430b-8ff8-07848026d38b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 545\n  }\n}"
tests:
- illuminate Integration Demonstration - Test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 660,\n      \"width\": 3800,\n      \"x\": 60,\n      \"y\": 50\n\
  \    }\n  }\n}"
