id: VerifyHumanReadableFormat
inputs: []
name: VerifyHumanReadableFormat
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: a10080a4-a157-4b18-ae17-3d2126198949
      iscommand: false
      name: ''
      version: -1
    taskid: a10080a4-a157-4b18-ae17-3d2126198949
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 9d730003-f421-4e2b-a60f-9bc54b996086
      iscommand: false
      name: VerifyTableToMarkDown
      scriptName: VerifyTableToMarkDown
      type: regular
      version: -1
    taskid: 9d730003-f421-4e2b-a60f-9bc54b996086
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 230\n  }\n}"
  '2':
    id: '2'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 3f0ad000-a2ae-4712-9994-0802f125ac7a
      iscommand: false
      name: VerifyTreeToFlatObject
      scriptName: VerifyTreeToFlatObject
      type: regular
      version: -1
    taskid: 3f0ad000-a2ae-4712-9994-0802f125ac7a
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 410\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 455,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\": 50\n\
  \    }\n  }\n}"
