description: The reason for having a "starter" test and an "actual incident" test
  is so that we can create a new incident which will have the right incident type
  ("Phishing" incident type) from the very beginning. This is absolutely needed in
  order to create the right incident fields for the test incident. If we create an
  incident and CHANGE its type after creating it, we will not have the phishing incident
  fields generated for us (fields like Email Headers, which we later set in the playbook).
id: Process Email - Generic - Test - Incident Starter
inputs: []
name: Process Email - Generic - Test - Incident Starter
outputs: []
sourceplaybookid: Phishing v2 Test - Attachment
starttaskid: '0'
system: true
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: f75a674b-0bda-4ea3-85a2-2241722cbe29
      iscommand: false
      name: ''
      version: -1
    taskid: f75a674b-0bda-4ea3-85a2-2241722cbe29
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": -140\n  }\n}"
  '17':
    id: '17'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '23'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 0797a6a4-8aa3-493d-8654-8b775136bce8
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 0797a6a4-8aa3-493d-8654-8b775136bce8
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 5\n  }\n}"
  '23':
    id: '23'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '25'
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      accountid: {}
      accountname: {}
      agentid: {}
      app: {}
      assetid: {}
      attachmentcount: {}
      attachmentextension: {}
      attachmenthash: {}
      attachmentid: {}
      attachmentname: {}
      attachmentsize: {}
      attachmenttype: {}
      blockedaction: {}
      bugtraq: {}
      city: {}
      commandline: {}
      country: {}
      criticalassets: {}
      customFields: {}
      cve: {}
      cvss: {}
      dbotprediction: {}
      dbotpredictionprobability: {}
      dbottextsuggestionhighlighted: {}
      dest: {}
      desthostname: {}
      destinationhostname: {}
      destinationip: {}
      destinationport: {}
      destntdomain: {}
      destos: {}
      details: {}
      detectionendtime: {}
      detectionid: {}
      detectionupdatetime: {}
      detectionurl: {}
      devicename: {}
      duration: {}
      emailauthenticitycheck: {}
      emailbcc: {}
      emailbody: {}
      emailbodyformat: {}
      emailbodyhtml: {}
      emailcc: {}
      emailclassification: {}
      emailclientname: {}
      emailfrom: {}
      emailheaders: {}
      emailhtml: {}
      emailinreplyto: {}
      emailkeywords: {}
      emailmessageid: {}
      emailreceived: {}
      emailreplyto: {}
      emailreturnpath: {}
      emailsenderip: {}
      emailsize: {}
      emailsource: {}
      emailsubject: {}
      emailto: {}
      emailtocount: {}
      emailurlclicked: {}
      employeedisplayname: {}
      employeeemail: {}
      employeemanageremail: {}
      entryIDs: {}
      eventid: {}
      eventtype: {}
      filehash: {}
      filename: {}
      filepath: {}
      filesize: {}
      firstseen: {}
      helloworldid: {}
      helloworldstatus: {}
      helloworldtype: {}
      hostname: {}
      infectedhosts: {}
      investigationstage: {}
      isolated: {}
      labels: {}
      lastmodifiedby: {}
      lastmodifiedon: {}
      lastseen: {}
      logsource: {}
      macaddress: {}
      maliciousbehavior: {}
      malwarefamily: {}
      name:
        simple: Process Email - Generic - Test
      occurred: {}
      os: {}
      owner: {}
      parentprocessid: {}
      phase: {}
      phishingsubtype: {}
      pid: {}
      policydeleted: {}
      policydescription: {}
      policydetails: {}
      policyid: {}
      policyrecommendation: {}
      policyremediable: {}
      policyseverity: {}
      policytype: {}
      protocol: {}
      quarantined: {}
      rating: {}
      region: {}
      regionid: {}
      reporteremailaddress: {}
      resourceid: {}
      resourcename: {}
      resourcetype: {}
      riskrating: {}
      riskscore: {}
      roles: {}
      samaccountname: {}
      severity: {}
      signature: {}
      skuname: {}
      skutier: {}
      sla: {}
      slaField: {}
      sourcehostname: {}
      sourceip: {}
      sourceport: {}
      sourceusername: {}
      src: {}
      srchostname: {}
      srcntdomain: {}
      srcos: {}
      srcuser: {}
      subtype: {}
      systems: {}
      tenantname: {}
      terminatedaction: {}
      threatactor: {}
      triggeredsecurityprofile: {}
      type:
        simple: Phishing
      urlsslverification: {}
      user: {}
      username: {}
      vendorid: {}
      vendorproduct: {}
      vulnerabilitycategory: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.create.inc
      id: b93114ae-779d-4c8b-8720-f448e22c2423
      iscommand: true
      name: Create new Phishing incident
      script: Builtin|||createNewIncident
      type: regular
      version: -1
    taskid: b93114ae-779d-4c8b-8720-f448e22c2423
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 185\n  }\n}"
  '24':
    id: '24'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      incidentId:
        complex:
          root: CreatedIncidentID
      name:
        simple: Process Email - Generic - Test - Actual Incident
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.playbook
      id: b203f285-eacf-469d-8cd8-326b4eaa13fa
      iscommand: true
      name: Set playbook for new incident
      script: Builtin|||setPlaybook
      type: regular
      version: -1
    taskid: b203f285-eacf-469d-8cd8-326b4eaa13fa
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 730\n  }\n}"
  '25':
    id: '25'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '26'
    note: false
    quietmode: 0
    scriptarguments:
      id:
        complex:
          root: CreatedIncidentID
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Start investigation of the incident, so that we can later set the
        right playbook to run on it. This command has t be unhidden using server configuration.
      id: 95976e00-e8d6-4a95-8c55-491b547cbddf
      iscommand: true
      name: Begin investigating the incident
      script: Builtin|||investigate
      type: regular
      version: -1
    taskid: 95976e00-e8d6-4a95-8c55-491b547cbddf
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '26':
    id: '26'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '24'
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: '15'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Sleep for X seconds
      id: 7f63f321-da44-4a4d-8d0b-0067a34cc71d
      iscommand: false
      name: Wait for investigation to begin
      scriptName: Sleep
      type: regular
      version: -1
    taskid: 7f63f321-da44-4a4d-8d0b-0067a34cc71d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 550\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 273875ba-fbcb-4b69-8145-1c388f5dfcff
      iscommand: false
      name: Begin Real Incident
      type: title
      version: -1
    taskid: 273875ba-fbcb-4b69-8145-1c388f5dfcff
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 905\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1110,\n      \"width\": 380,\n      \"x\": 265,\n      \"y\":\
  \ -140\n    }\n  }\n}"
