args:
- description: The id of the incident
  name: id
  required: true
- description: Type of manual task. Can be regular or condition.
  name: type
- description: Relevant only for conditional tasks.
  name: closing_option
- description: Name of manual task.
  name: name
comment: Script that will allow to close Manual task on the current investigation
commonfields:
  id: CompleteManualTask
  version: -1
enabled: true
name: CompleteManualTask
runonce: false
script: "args = demisto.args()\ntask_type = args.get('type', 'regular')\ntask_name\
  \ = args.get('name')\n\nsearch_args =  {\n            \"incidentId\": args['id'],\n\
  \            \"states\": \"Waiting\",\n            \"raw-response\": \"true\"\n\
  \        }\n\nresCmdName = demisto.executeCommand(\"DemistoGetIncidentTasksByState\"\
  , search_args)\ncontents = resCmdName[0].get(\"Contents\", {})\ndemisto.debug('found\
  \ the following waiting commands on investigation {}:\\n{}'.format(args['id'], contents))\n\
  tasks = [i.get('id', 0) for i in contents if i.get('type', '') == task_type]\nif\
  \ task_name:\n    tasks = [i.get('id', 0) for i in contents if i.get('name') ==\
  \ task_name]\n\nif tasks:\n    closing_args = { \"id\": tasks[0] }\n    if task_type\
  \ == 'condition':\n        closing_args['input'] = demisto.args().get('closing_option')\n\
  \n    demisto.debug('closing command: {}'.format(closing_args))\n    demisto.executeCommand(\"\
  taskComplete\", closing_args)\nelse:\n    demisto.debug('not closing anything...')\n"
scripttarget: 0
subtype: python3
tags: []
tests:
- No test
toversion: 4.1.9
type: python
