args:
- defaultValue: '6'
  description: Hours different between the original incident and created incident.
  name: hoursDiff
comment: Create a duplicate incident to the current.
commonfields:
  id: TestCreateDuplicates
  version: -1
enabled: true
name: TestCreateDuplicates
runonce: false
script: "from datetime import timedelta, datetime\nincident = demisto.incidents()[0]\n\
  \ndef parse_datetime(datetime_str):\n    datetime_str = datetime_str[:datetime_str.find(\"\
  .\")]\n    return datetime.strptime(datetime_str, \"%Y-%m-%dT%H:%M:%S\")\n\ndef\
  \ parse_label(label):\n    return {label['type']: label['value']}\n\nnew_incident_time\
  \ = parse_datetime(incident['occurred']) - timedelta(hours=int(demisto.args()['hoursDiff']))\n\
  res = demisto.executeCommand(\"createNewIncident\", {'name': 'ThisIsATestForDuplicate',\n\
  'occurred': new_incident_time.strftime('%d %b %y %H:%M MST'), 'type': incident['type'],\n\
  'labels': map(parse_label, incident['labels'])\n})\ndemisto.results(res)"
scripttarget: 0
subtype: python2
tags: []
toversion: 4.1.9
type: python
