comment: Create duplicate incident to the current incident.
commonfields:
  id: CreateDuplicateIncident
  version: -1
dockerimage: demisto/dateutil
enabled: true
name: CreateDuplicateIncident
script: "import json\nfrom dateutil.parser import parse\nfrom datetime import timedelta\n\
  \nincident = demisto.incidents()[0]\n\ndef get_labels_map(labels):\n    labels_map\
  \ = []\n    for x in labels:\n        labels_map.append({x['type']: x['value']})\n\
  \    return labels_map\nold_time = (parse(incident['occurred']) - timedelta(hours=1)).isoformat()#.strftime(\"\
  %Y-%m-%dT%H:%M:%S%z\")\nduplicate_incident = {\n    'name': incident['name'],\n\
  \    'details': incident['details'],\n    'severity': incident['severity'],\n  \
  \  'customFields': incident['CustomFields'],\n    'labels': get_labels_map(incident['labels']),\n\
  \    'occurred': old_time\n}\n\nres = demisto.executeCommand(\"createNewIncident\"\
  , duplicate_incident)\ndemisto.results(res)\n"
scripttarget: 0
subtype: python2
tags: []
toversion: 4.1.9
type: python
