args:
- description: The name of the file to create
  name: name
  required: true
- description: The content of the file to create
  name: text
  required: true
comment: A test script to create a word file with a text as content and file name
  and put it in the context.
commonfields:
  id: TestCreateWordFile
  version: -1
dockerimage: demisto/word-parser
enabled: true
name: TestCreateWordFile
script: "from StringIO import StringIO\nfrom docx import Document\n\nres = []\nerrEntry\
  \ = {\n    \"Type\": entryTypes[\"error\"],\n    \"ContentsFormat\": formats[\"\
  text\"],\n    \"Contents\": \"\"\n}\n\nargs = demisto.args()\ntry:\n    document\
  \ = Document()\n    document.add_paragraph(args['text'])\n    target_stream = StringIO()\n\
  \    document.save(target_stream)\n    res = fileResult(args['name'], target_stream.getvalue())\n\
  except BaseException as e:\n    errEntry[\"Contents\"] = \"Error occurred while\
  \ creating the word file.\\nException info: \" + str(e)\n    res = errEntry\n\n\
  demisto.results(res)\n"
scripttarget: 0
subtype: python2
tags: []
toversion: 4.1.9
type: python
