args:
- description: Command to execute
  name: commandName
- description: Name of argument 1
  name: argName1
- description: Value of argument 1
  name: argVal1
- description: Name of argument 1
  name: argName2
- description: Value of argument 1
  name: argVal2
- description: Name of argument 1
  name: argName3
- description: Value of argument 1
  name: argVal3
- description: Name of argument 1
  name: argName4
- description: Value of argument 1
  name: argVal4
- description: Name of argument 1
  name: argName5
- description: Value of argument 1
  name: argVal5
comment: Run executeCommand in a generic manner. Can be used to dynamically execute
  a command and also for cases when there is need to pass arguments not defined in
  the command's configuration.
commonfields:
  id: ExecuteCommandGeneric
  version: -1
dockerimage: demisto/python3:3.7.4.2245
enabled: true
name: ExecuteCommandGeneric
runas: DBotWeakRole
runonce: false
script: "command = demisto.args()['commandName']\n\ncmd_args = {}\n\nfor i in range(1,\
  \ 6):\n    name = demisto.args().get('argName' + str(i))\n    if name:\n       \
  \ cmd_args[name] = demisto.args().get('argVal' + str(i))\n\nres = demisto.executeCommand(command,\
  \ cmd_args)\ndemisto.results(res)\n"
scripttarget: 0
subtype: python3
tags:
- Utilities
toversion: 4.1.9
type: python
