comment: Generates random UUID
commonfields:
  id: GenerateUUID
  version: -1
enabled: true
name: GenerateUUID
outputs:
- contextPath: GeneratedUUID
  description: Generated UUID
  type: string
runonce: false
script: "import uuid\nuuid = uuid.uuid4().hex\ndemisto.results({\n    'Type': entryTypes['note'],\n\
  \    'Contents': uuid,\n    'ContentsFormat': formats['json'],\n    'ReadableContentsFormat':\
  \ formats['markdown'],\n    'HumanReadable': uuid,\n    'EntryContext': {'GeneratedUUID':\
  \ uuid}\n})"
scripttarget: 0
subtype: python2
tags: []
toversion: 4.1.9
type: python
