args:
- description: Password for the Archer instance.
  name: password
  required: true
- description: Instance name for the Archer instance.
  name: instance_name
  required: true
- description: Username name for the Archer instance.
  name: username
  required: true
- description: Server URL name for the Archer instance.
  name: server_url
  required: true
comment: Checks whether given Archer credentials are valid
commonfields:
  id: CheckArcherInstance
  version: -1
dockerimage: demisto/archer:1.0.0.270
enabled: true
name: CheckArcherInstance
runas: DBotWeakRole
runonce: false
script: "import rsa_archer.archer_instance as arc\n\nargs = demisto.args()\npassword\
  \ = args[\"password\"]\ninstance_name = args[\"instance_name\"]\nusername = args[\"\
  username\"]\nserver_url = args[\"server_url\"]\n\ndef new_log(s, s2):\n    raise\
  \ Exception(s % s2)\n\narc.log.error = new_log\n\ntry:\n    archer_instance = arc.ArcherInstance(server_url,\
  \ instance_name, username, password)\n    demisto.results(\"Success - your credentials\
  \ are valid\")\nexcept Exception as e:\n    return_error(\"Your credentials are\
  \ invalid.\\n Error from Archer: {}\".format(str(e)))"
scripttarget: 0
subtype: python3
tags: []
tests:
- No Test
toversion: 4.1.9
type: python
