description: 'Hunt for sightings of MD5, SHA1 and/or SHA256 hashes on endpoints, using
  McAfee TIE (requires ePO as well).


  Input:

  * Hash (default, takes all deferent hashes from context)


  Output:

  * All agents that files with "Hash" has been executed on (TIE)

  * Enrich Agents info from ePO'
fromversion: 3.5.0
id: search_endpoints_by_hash_-_tie
inputs:
- description: 'The Hash to hunt (Could be MD5,SHA1,SHA256).

    Default is set to all hashes'
  key: Hash
  required: false
  value:
    simple: ${.=val.File.map(function(f) {return [f.MD5, f.SHA1, f.SHA256];}).reduce(function(a,
      b){return a.concat(b);}, []).filter(function (val1) {return val1;})}
name: Search Endpoints By Hash - TIE
outputs:
- contextPath: Endpoint.Hostname
  description: Hostname
  type: string
- contextPath: Endpoint
  description: The endpoint
  type: unknown
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '7'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 80386f11-23d2-4ca7-8e8a-efc6c7d8b797
      iscommand: false
      name: ''
      version: -1
    taskid: 80386f11-23d2-4ca7-8e8a-efc6c7d8b797
    type: start
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 50\n  }\n}"
  '1':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: string.isEqual
                    right:
                      value:
                        simple: McAfee Threat Intelligence Exchange
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: string.isEqual
                    right:
                      value:
                        simple: active
                root: modules
          operator: general.isExists
      label: 'yes'
    id: '1'
    nexttasks:
      '#default#':
      - '4'
      'yes':
      - '9'
    scriptarguments:
      left: {}
      right: {}
      value: {}
    separatecontext: false
    task:
      brand: ''
      description: Is TIE enabled?
      id: f96c54b2-b8fa-48b8-8a56-56555a749c10
      iscommand: false
      name: Is TIE enabled?
      type: condition
      version: -1
    taskid: f96c54b2-b8fa-48b8-8a56-56555a749c10
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 340\n  }\n}"
  '2':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: string.isEqual
                    right:
                      value:
                        simple: epo
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: string.isEqual
                    right:
                      value:
                        simple: active
                root: modules
          operator: general.isExists
      label: 'yes'
    id: '2'
    nexttasks:
      '#default#':
      - '4'
      'yes':
      - '6'
    scriptarguments:
      left: {}
      right: {}
      value:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: modules.brand
              operator: string.isEqual
              right:
                value:
                  simple: epo
          - - left:
                iscontext: true
                value:
                  simple: modules.state
              operator: string.isEqual
              right:
                value:
                  simple: active
          root: modules
    separatecontext: false
    task:
      brand: ''
      description: Is ePO enabled?
      id: b098fed0-d1ae-418c-8a37-756e1ae0cb37
      iscommand: false
      name: Is ePO enabled?
      type: condition
      version: -1
    taskid: b098fed0-d1ae-418c-8a37-756e1ae0cb37
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 430,\n    \"y\": 1288\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '5'
    scriptarguments:
      file:
        complex:
          root: inputs.Hash
    separatecontext: false
    task:
      brand: McAfee Threat Intelligence Exchange
      description: Get Agent GUIDS for the given hashes
      id: 26ba9604-ced2-4c35-8e13-075d3ed04042
      iscommand: true
      name: List all agents that the Hash has been executed on
      script: McAfee Threat Intelligence Exchange|||tie-file-references
      type: regular
      version: -1
    taskid: 26ba9604-ced2-4c35-8e13-075d3ed04042
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 430,\n    \"y\": 737\n  }\n}"
  '4':
    id: '4'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: b000dc4b-e71b-43dc-87d3-da7fbeae2d91
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: b000dc4b-e71b-43dc-87d3-da7fbeae2d91
    type: title
    view: "{\n  \"position\": {\n    \"x\": 138,\n    \"y\": 1793\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: References.AgentGuid
                root: File
          operator: general.isExists
      label: 'yes'
    id: '5'
    nexttasks:
      '#default#':
      - '4'
      'yes':
      - '8'
    scriptarguments:
      value:
        complex:
          accessor: References.AgentGuid
          root: File
    separatecontext: false
    task:
      brand: ''
      description: Did we get any Agent GUIDS?
      id: c7e628c9-cb07-408a-8667-8f4bb2c6d944
      iscommand: false
      name: Did we find any relevant agents?
      type: condition
      version: -1
    taskid: c7e628c9-cb07-408a-8667-8f4bb2c6d944
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 430,\n    \"y\": 910\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '4'
    scriptarguments:
      searchText:
        complex:
          accessor: References.AgentGuid
          root: File
      taskID: {}
    separatecontext: false
    task:
      brand: ''
      description: Get hostnames for the Agent GUIDS
      id: 101e3e85-0246-4bd4-80be-2df713ee96e6
      iscommand: false
      name: Get Agent info from ePO
      scriptName: EPOFindSystem
      type: regular
      version: -1
    taskid: 101e3e85-0246-4bd4-80be-2df713ee96e6
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 430,\n    \"y\": 1587\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: ef3c7391-412b-4976-8fc4-f66cbe2607c4
      iscommand: false
      name: Hunt HASH in TIE
      type: title
      version: -1
    taskid: ef3c7391-412b-4976-8fc4-f66cbe2607c4
    type: title
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 195\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '2'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 4795a873-58e7-4312-83ae-bd7e29d8e8f1
      iscommand: false
      name: Enrich in ePO
      type: title
      version: -1
    taskid: 4795a873-58e7-4312-83ae-bd7e29d8e8f1
    type: title
    view: "{\n  \"position\": {\n    \"x\": 430,\n    \"y\": 1145\n  }\n}"
  '9':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Hash
          operator: general.isExists
      label: 'yes'
    id: '9'
    nexttasks:
      '#default#':
      - '4'
      'yes':
      - '3'
    separatecontext: false
    task:
      brand: ''
      description: Do we have any files to hunt?
      id: c8baebe6-606d-4e83-88ab-09ac98b1be34
      iscommand: false
      name: Do we have any files to hunt?
      type: condition
      version: -1
    taskid: c8baebe6-606d-4e83-88ab-09ac98b1be34
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 430,\n    \"y\": 507\n  }\n}"
tests:
- search_endpoints_by_hash_-_tie_-_test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"1_4_#default#\": 0.1,\n    \"2_4_#default#\"\
  : 0.17,\n    \"5_4_#default#\": 0.11,\n    \"9_4_#default#\": 0.12\n  },\n  \"paper\"\
  : {\n    \"dimensions\": {\n      \"height\": 1808,\n      \"width\": 672,\n   \
  \   \"x\": 138,\n      \"y\": 50\n    }\n  }\n}"
