description: 'Hunt for sightings of MD5, SHA1 and/or SHA256 hashes on endpoints, using
  McAfee TIE (requires ePO as well).


  Input:

  * Hash (default, takes all deferent hashes from context)


  Output:

  * All agents that files with "Hash" has been executed on (TIE)

  * Enrich Agents info from ePO'
fromversion: 2.5.0
id: TIE - IOC Hunt
inputs:
- description: 'The Hash to hunt (Could be MD5,SHA1,SHA256).

    Default is set to all hashes'
  key: Hash
  playbookInputQuery: null
  required: false
  value:
    simple: ${.=val.File.map(function(f) {return [f.MD5, f.SHA1, f.SHA256];}).reduce(function(a,
      b){return a.concat(b);}, []).filter(function (val1) {return val1;})}
name: TIE - IOC Hunt
outputs: []
starttaskid: '0'
system: true
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: b79d975a-a6dc-4a66-8515-c8f4177b0a40
      iscommand: false
      name: ''
      version: -1
    taskid: b79d975a-a6dc-4a66-8515-c8f4177b0a40
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '4'
      'yes':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      left: {}
      right: {}
      value:
        simple: ${modules(val.brand=="McAfee Threat Intelligence Exchange")}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 1bf80041-9e03-4daf-861c-a709df537687
      iscommand: false
      name: Is TIE enabled?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 1bf80041-9e03-4daf-861c-a709df537687
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 340\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '4'
      'yes':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      left: {}
      right: {}
      value:
        simple: ${modules(val.brand=="epo")}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 992f05a8-3c0e-43bc-8f68-b40d2a9542e9
      iscommand: false
      name: Is ePO enabled?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 992f05a8-3c0e-43bc-8f68-b40d2a9542e9
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 430,\n    \"y\": 1080\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      file:
        simple: ${inputs.Hash}
    separatecontext: false
    skipunavailable: false
    task:
      brand: McAfee Threat Intelligence Exchange
      description: ''
      id: c906e63c-45c5-4540-8f42-b74db1943725
      iscommand: true
      name: List all agents that the Hash has been executed on
      script: McAfee Threat Intelligence Exchange|||tie-file-references
      type: regular
      version: -1
    taskid: c906e63c-45c5-4540-8f42-b74db1943725
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 430,\n    \"y\": 519\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: c283821d-46ac-4b77-8728-9bc136f0c729
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: c283821d-46ac-4b77-8728-9bc136f0c729
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 135,\n    \"y\": 1492\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '4'
      'yes':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${File.References.AgentGuid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: adfc3709-ca91-4ac0-8c2b-179c44d30403
      iscommand: false
      name: Did we find any relevant agents?
      scriptName: Exists
      type: condition
      version: -1
    taskid: adfc3709-ca91-4ac0-8c2b-179c44d30403
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 430,\n    \"y\": 703\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quietmode: 0
    scriptarguments:
      searchText:
        simple: ${File.References.AgentGuid}
      taskID: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 6b8b1d0c-fae5-4779-83a2-9b0e5edbd983
      iscommand: false
      name: Get Agent info from ePO
      scriptName: EPOFindSystem
      type: regular
      version: -1
    taskid: 6b8b1d0c-fae5-4779-83a2-9b0e5edbd983
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 430,\n    \"y\": 1326\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: a08baee9-a402-4bc8-8cae-77c4c144d889
      iscommand: false
      name: Hunt HASH in TIE
      type: title
      version: -1
    taskid: a08baee9-a402-4bc8-8cae-77c4c144d889
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 162.5,\n    \"y\": 195\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 1df1aefe-fce4-4fb8-80e0-3fbef311f772
      iscommand: false
      name: Enrich in ePO
      type: title
      version: -1
    taskid: 1df1aefe-fce4-4fb8-80e0-3fbef311f772
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 430,\n    \"y\": 956\n  }\n}"
tests:
- No test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"1_4_#default#\": 0.1,\n    \"2_4_#default#\"\
  : 0.17,\n    \"5_4_#default#\": 0.11\n  },\n  \"paper\": {\n    \"dimensions\":\
  \ {\n      \"height\": 1507,\n      \"width\": 675,\n      \"x\": 135,\n      \"\
  y\": 50\n    }\n  }\n}"
