id: Mitre Attack List 10 Indicators Feed Test
inputs: []
name: Mitre Attack List 10 Indicators Feed Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 59581c2f-91b8-4647-806a-f72810eb1003
      iscommand: false
      name: ''
      version: -1
    taskid: 59581c2f-91b8-4647-806a-f72810eb1003
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      limit:
        simple: '2'
      raw: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: MITRE ATT&CK
      description: Retreives a limited number of the indicators .
      id: cdbecdbb-bab3-418a-8b12-8d1338e2b265
      iscommand: true
      name: mitre-get-indicators
      script: MITRE ATT&CK|||mitre-get-indicators
      type: regular
      version: -1
    taskid: cdbecdbb-bab3-418a-8b12-8d1338e2b265
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: 90b52ed3-6655-4611-8066-790e4c7aff5a
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 90b52ed3-6655-4611-8066-790e4c7aff5a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: ATT&CK
                root: MITRE
                transformers:
                - args:
                    index:
                      value:
                        simple: '0'
                  operator: atIndex
          operator: isExists
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '6'
      'yes':
      - '5'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: b9fc5ae5-9c1f-48e0-82b5-cafaf147a619
      iscommand: false
      name: Indiactors found
      type: condition
      version: -1
    taskid: b9fc5ae5-9c1f-48e0-82b5-cafaf147a619
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 731b40ee-d7e6-4810-8f0e-8ee8433f5999
      iscommand: false
      name: Complete
      type: title
      version: -1
    taskid: 731b40ee-d7e6-4810-8f0e-8ee8433f5999
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quietmode: 0
    scriptarguments:
      indicator:
        simple: T153111
    separatecontext: false
    skipunavailable: false
    task:
      brand: MITRE ATT&CK
      description: Lookup reputation in the indicators.
      id: ba18d85d-fa0f-473b-894c-1014b7b858d9
      iscommand: true
      name: mitre-reputation with non existing ID
      script: MITRE ATT&CK|||mitre-reputation
      type: regular
      version: -1
    taskid: ba18d85d-fa0f-473b-894c-1014b7b858d9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      message:
        simple: mitre IOCs not found
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: e5f7d1d2-e80b-4516-8027-326c08046dd4
      iscommand: false
      name: Print error from get-indicators
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: e5f7d1d2-e80b-4516-8027-326c08046dd4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 720\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 910,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
