contentitemfields:
  propagationLabels: []
id: McAfee DXL - Test
inputs: []
name: McAfee DXL - test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
      - '3'
      - '4'
      - '5'
      - '6'
    note: false
    separatecontext: false
    task:
      id: 779793c2-558a-495f-87a5-fb527a7724e5
      iscommand: false
      name: ''
      version: -1
    taskid: 779793c2-558a-495f-87a5-fb527a7724e5
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      ip:
        simple: 8.8.8.8
      trust_level:
        simple: KNOWN_TRUSTED
    separatecontext: false
    task:
      description: Push given IP  to the DXL fabric
      id: 39dfd1b2-0375-43cc-8cbf-2b89faa7eeb0
      iscommand: true
      name: send ip message
      script: '|||dxl-push-ip'
      type: regular
      version: -1
    taskid: 39dfd1b2-0375-43cc-8cbf-2b89faa7eeb0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 180\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      id: 8ba48f89-9d7f-4e04-85f2-fe060928b0f1
      iscommand: false
      name: done
      type: title
      version: -1
    taskid: 8ba48f89-9d7f-4e04-85f2-fe060928b0f1
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 350\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      hash:
        simple: 0123456789
      trust_level:
        simple: NOT_SET
    separatecontext: false
    task:
      description: Push given hash  to the DXL fabric
      id: 35d0683e-e6f8-450e-8d8a-1d3d5b073af0
      iscommand: true
      name: send hash message
      script: '|||dxl-push-hash'
      type: regular
      version: -1
    taskid: 35d0683e-e6f8-450e-8d8a-1d3d5b073af0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 870,\n    \"y\": 180\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      domain:
        simple: malicious.com
      trust_level:
        simple: KNOWN_MALICIOUS
    separatecontext: false
    task:
      description: Push given domain  to the DXL fabric
      id: 2148da77-5c61-4b89-82f6-31a5fb463ad7
      iscommand: true
      name: dxl-push-domain
      script: '|||dxl-push-domain'
      type: regular
      version: -1
    taskid: 2148da77-5c61-4b89-82f6-31a5fb463ad7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 20,\n    \"y\": 180\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      trust_level:
        simple: KNOWN_TRUSTED
      url:
        simple: https://www.google.com
    separatecontext: false
    task:
      description: Push given url  to the DXL fabric
      id: 87026516-2a46-43ff-8ff5-7cd79dc04057
      iscommand: true
      name: dxl-push-url
      script: '|||dxl-push-url'
      type: regular
      version: -1
    taskid: 87026516-2a46-43ff-8ff5-7cd79dc04057
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -400,\n    \"y\": 180\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      payload:
        simple: test
      topic:
        simple: TEST_TOPIC
    separatecontext: false
    task:
      description: Deliver the specified event to the DXL fabric
      id: 798e3bc9-e79b-492f-872c-9430be443e8e
      iscommand: true
      name: dxl-send-event
      script: '|||dxl-send-event'
      type: regular
      version: -1
    taskid: 798e3bc9-e79b-492f-872c-9430be443e8e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1300,\n    \"y\": 180\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 365,\n      \"width\": 2080,\n      \"x\": -400,\n      \"y\"\
  : 50\n    }\n  }\n}"
