elasticcommonfields: {}
id: CounterCraft - Test
inputs: []
name: CounterCraft - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      elasticcommonfields: {}
      id: f0982991-2da9-4f84-8b3e-3748e62c63d5
      iscommand: false
      name: ''
      version: -1
    taskid: f0982991-2da9-4f84-8b3e-3748e62c63d5
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      elasticcommonfields: {}
      id: e598d926-344b-4177-86ed-f233bd0ebd43
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: e598d926-344b-4177-86ed-f233bd0ebd43
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: root
    separatecontext: false
    skipunavailable: false
    task:
      brand: CounterCraft Deception Director
      description: Get information about an object (IoC)
      elasticcommonfields: {}
      id: 9762dd37-95d1-4bda-8a2e-f7254d479304
      iscommand: true
      name: countercraft-get-object
      script: CounterCraft Deception Director|||countercraft-get-object
      type: regular
      version: -1
    taskid: 9762dd37-95d1-4bda-8a2e-f7254d479304
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: CounterCraft.Campaign.Name
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: CounterCraft.Campaign.ID
          operator: isExists
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '8'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      elasticcommonfields: {}
      id: 70532b36-4b91-44fc-88a8-b13a8a58d8c6
      iscommand: false
      name: Verify Command Results
      type: condition
      version: -1
    taskid: 70532b36-4b91-44fc-88a8-b13a8a58d8c6
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: Test Campaign
    separatecontext: false
    skipunavailable: false
    task:
      brand: CounterCraft Deception Director
      description: 'List all deception campaigns '
      elasticcommonfields: {}
      id: 2eeba76b-1c3a-436b-8fad-ea9ff18d9a76
      iscommand: true
      name: countercraft-list-campaigns
      script: CounterCraft Deception Director|||countercraft-list-campaigns
      type: regular
      version: -1
    taskid: 2eeba76b-1c3a-436b-8fad-ea9ff18d9a76
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '7':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: CounterCraft.Object.Value
          operator: isEqualString
          right:
            value:
              simple: root
      - - left:
            iscontext: true
            value:
              simple: CounterCraft.Object.TypeCode
          operator: isExists
      label: 'yes'
    id: '7'
    ignoreworker: false
    nexttasks:
      'yes':
      - '6'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      elasticcommonfields: {}
      id: ac44628a-9cfc-40de-84b8-1544b29dc1c2
      iscommand: false
      name: Verify Command Results
      type: condition
      version: -1
    taskid: ac44628a-9cfc-40de-84b8-1544b29dc1c2
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      elasticcommonfields: {}
      id: 3c730d3f-0ae7-451f-80da-3ba2d5942be6
      iscommand: false
      name: Success
      type: title
      version: -1
    taskid: 3c730d3f-0ae7-451f-80da-3ba2d5942be6
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1085,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
