description: Test playbook to run with Rasterize up to version 4.5. When adding tests
  you probably want to add to 'Rasterize Test' and NOT this playbook
id: Rasterize 4.5 Test
inputs: []
name: Rasterize 4.5 Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: a6642a08-aff5-490d-880c-f350e6362102
      iscommand: false
      name: ''
      version: -1
    taskid: a6642a08-aff5-490d-880c-f350e6362102
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      body: {}
      filename:
        simple: valid_email-rasterize
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://raw.githubusercontent.com/demisto/content/master/TestData/valid_email-rasterize.eml
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: Sends http request. Returns the response as json.
      id: c9eab1c9-7d5f-49e5-8aca-90708c94de3b
      iscommand: false
      name: get vaild email
      scriptName: http
      type: regular
      version: -1
    taskid: c9eab1c9-7d5f-49e5-8aca-90708c94de3b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 6b2f615d-b4c9-4d9f-838f-6d6612efe9cd
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 6b2f615d-b4c9-4d9f-838f-6d6612efe9cd
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: a42b434b-e10a-4f2c-8779-afd8e4720e72
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: a42b434b-e10a-4f2c-8779-afd8e4720e72
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2295\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    scriptarguments:
      height: {}
      type:
        simple: png
      url:
        simple: https://github.com
      wait_time:
        simple: '5'
      width: {}
    separatecontext: false
    task:
      brand: ''
      description: Rasterize a URL into image or PDF
      id: 4aa90de0-8d88-40b8-814b-50c7b9a9b7fd
      iscommand: true
      name: Rasterize URL to PNG (Github)
      script: '|||rasterize'
      type: regular
      version: -1
    taskid: 4aa90de0-8d88-40b8-814b-50c7b9a9b7fd
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    scriptarguments:
      entryid:
        complex:
          accessor: EntryID
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: InfoFile.Info
              operator: isEqualString
              right:
                value:
                  simple: image/png
            - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: InfoFile.Info
              operator: isEqualString
              right:
                value:
                  simple: url.png
          root: InfoFile
          transformers:
          - operator: uniq
      langs: {}
    separatecontext: false
    task:
      brand: ''
      description: Extracts text from an image.
      id: 6fe3cccb-d494-4291-8767-dae37b0428f7
      iscommand: true
      name: Test Image (ImageOCR)
      script: '|||image-ocr-extract-text'
      type: regular
      version: -1
    taskid: 6fe3cccb-d494-4291-8767-dae37b0428f7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '15':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Text
                root: File
                transformers:
                - operator: toLowerCase
          operator: containsGeneral
          right:
            value:
              simple: github
      label: 'Yes'
    id: '15'
    ignoreworker: false
    nexttasks:
      'Yes':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 2307f6cb-2776-47a5-8592-c25f273cd210
      iscommand: false
      name: Check Text
      type: condition
      version: -1
    taskid: 2307f6cb-2776-47a5-8592-c25f273cd210
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    separatecontext: true
    task:
      brand: ''
      id: 35b720d1-ffb7-4714-8574-d769230f11cc
      iscommand: false
      name: Process Email - Generic for Rasterize
      playbookName: Process Email - Generic for Rasterize
      type: playbook
      version: -1
    taskid: 35b720d1-ffb7-4714-8574-d769230f11cc
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 3f84b40d-32dc-4ba8-854b-705efdfdf099
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 3f84b40d-32dc-4ba8-854b-705efdfdf099
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 157d411e-ab44-40e5-8b89-e4c8f5c3d95f
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 157d411e-ab44-40e5-8b89-e4c8f5c3d95f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      body: {}
      filename:
        simple: corrupt_email-rasterize
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://raw.githubusercontent.com/demisto/content/master/TestData/corrupt_email-rasterize.eml
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: Sends http request. Returns the response as json.
      id: 2e0641ea-67c9-429d-8881-dcb3f048209d
      iscommand: false
      name: get corrupt email
      scriptName: http
      type: regular
      version: -1
    taskid: 2e0641ea-67c9-429d-8881-dcb3f048209d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    separatecontext: true
    task:
      brand: ''
      id: abad5959-972d-4fca-8475-c9a794cd9f85
      iscommand: false
      name: Process Email - Generic for Rasterize
      playbookName: Process Email - Generic for Rasterize
      type: playbook
      version: -1
    taskid: abad5959-972d-4fca-8475-c9a794cd9f85
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2120\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      body: {}
      filename:
        simple: corrupt_email-rasterize
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://raw.githubusercontent.com/demisto/content/master/TestData/test_image.png
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: Sends http request. Returns the response as json.
      id: bd77bc53-a2df-4ff0-8cfd-4c08d2530de0
      iscommand: false
      name: get valid Image
      scriptName: http
      type: regular
      version: -1
    taskid: bd77bc53-a2df-4ff0-8cfd-4c08d2530de0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1945\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    separatecontext: true
    task:
      brand: ''
      id: ce382f1d-984e-437f-8fc1-5af09346cab8
      iscommand: false
      name: Process Email - Generic for Rasterize
      playbookName: Process Email - Generic for Rasterize
      type: playbook
      version: -1
    taskid: ce382f1d-984e-437f-8fc1-5af09346cab8
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2310,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
