id: ArcSight Logger test
inputs: []
name: ArcSight Logger test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: b9b8d709-708d-4b07-86ac-5fd2fc149e0a
      iscommand: false
      name: ''
      version: -1
    taskid: b9b8d709-708d-4b07-86ac-5fd2fc149e0a
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete all context
      id: bbbcdeb5-0c34-4e16-8770-aa346c4a5751
      iscommand: false
      name: Delete Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: bbbcdeb5-0c34-4e16-8770-aa346c4a5751
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      searchSessionId:
        simple: ${ArcSightLogger.Search.SearchSessionId}
      sessionId:
        simple: ${ArcSightLogger.Search.SessionId}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ArcSight Logger
      description: using 'as-search'
      id: 7963a823-66bc-4f8a-88ac-91091586ae59
      iscommand: true
      name: Get search status
      script: ArcSight Logger|||as-status
      type: regular
      version: -1
    taskid: 7963a823-66bc-4f8a-88ac-91091586ae59
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 895\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete all context
      id: 69a4ece6-0753-4cbe-8736-1184524bcf27
      iscommand: false
      name: Delete Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: 69a4ece6-0753-4cbe-8736-1184524bcf27
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1420\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      dir: {}
      discover_fields: {}
      end_time: {}
      field_summary: {}
      fields: {}
      lastDays: {}
      length:
        simple: '10'
      local_search: {}
      offset: {}
      query: {}
      start_time: {}
      summary_fields: {}
      timeout: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ArcSight Logger
      description: execute as-search-events. Limit length to 10 events.
      id: 831a807e-a20d-4873-866f-9a27aaeb3b68
      iscommand: true
      name: Search events
      script: ArcSight Logger|||as-search-events
      type: regular
      version: -1
    taskid: 831a807e-a20d-4873-866f-9a27aaeb3b68
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1595\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quietmode: 0
    scriptarguments:
      discover_fields: {}
      end_time: {}
      field_summary: {}
      lastDays: {}
      local_search: {}
      query: {}
      search_type: {}
      start_time: {}
      summary_fields: {}
      timeout: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ArcSight Logger
      description: Start a search session with 'as-search' command
      id: 915923af-de13-4cdd-82ab-a5116d12ced7
      iscommand: true
      name: Start Search Session
      script: ArcSight Logger|||as-search
      type: regular
      version: -1
    taskid: 915923af-de13-4cdd-82ab-a5116d12ced7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    quietmode: 0
    scriptarguments:
      end_time: {}
      lastDays:
        simple: '1'
      searchSessionId:
        simple: ${ArcSightLogger.Search.SearchSessionId}
      sessionId:
        simple: ${ArcSightLogger.Search.SessionId}
      start_time: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ArcSight Logger
      description: Narrow the search time range. Passing  lastDays=1
      id: a5a14007-1113-4aa4-83f6-04e81d04a768
      iscommand: true
      name: Narrow search time range
      script: ArcSight Logger|||as-drilldown
      type: regular
      version: -1
    taskid: a5a14007-1113-4aa4-83f6-04e81d04a768
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 545\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      dir: {}
      fields: {}
      length:
        simple: '10'
      offset: {}
      searchSessionId:
        simple: ${ArcSightLogger.Search.SearchSessionId}
      sessionId:
        simple: ${ArcSightLogger.Search.SessionId}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ArcSight Logger
      description: Limit list length to 10 events
      id: 4f7407a0-fbe0-40c8-8ddf-58bd4d5cde0f
      iscommand: true
      name: Find events
      script: ArcSight Logger|||as-events
      type: regular
      version: -1
    taskid: 4f7407a0-fbe0-40c8-8ddf-58bd4d5cde0f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1070\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    quietmode: 0
    scriptarguments:
      searchSessionId:
        simple: ${ArcSightLogger.Search.SearchSessionId}
      sessionId:
        simple: ${ArcSightLogger.Search.SessionId}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ArcSight Logger
      description: Close the search session
      id: c38f760a-f448-41d1-8029-a941b7e97c14
      iscommand: true
      name: Close session
      script: ArcSight Logger|||as-close
      type: regular
      version: -1
    taskid: c38f760a-f448-41d1-8029-a941b7e97c14
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1245\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: '2'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Wait 2 seconds in order to aloow the search to be completed.
      id: e7b4f762-27af-42b6-8c25-9d3bc6485fe4
      iscommand: false
      name: Wait 2 seconds
      script: Sleep
      type: regular
      version: -1
    taskid: e7b4f762-27af-42b6-8c25-9d3bc6485fe4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 720\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1640,\n      \"width\": 595,\n      \"x\": 265,\n      \"y\":\
  \ 50\n    }\n  }\n}"
