description: ''
fromversion: 4.1.0
id: Test ADGetUser Fails with no instances 'Active Directory Query' (old version)
inputs: []
name: Test ADGetUser Fails with no instances 'Active Directory Query' (old version)
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 0d9e5b93-cd1f-4c49-86f8-72c9fd643e97
      iscommand: false
      name: ''
      version: -1
    taskid: 0d9e5b93-cd1f-4c49-86f8-72c9fd643e97
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '2':
    continueonerror: true
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      attributes: {}
      customFieldData: {}
      customFieldType: {}
      dn: {}
      email: {}
      extend-context:
        simple: errData=
      headers: {}
      limit: {}
      name: {}
      nestedSearch: {}
      userAccountControlOut: {}
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: 'Use Active Directory to retrieve detailed information about a
        user account. The user can be specified by name, email or as an Active Directory
        Distinguished Name (DN).

        If no filter is provided, the result will show all users.


        The script will be executed with an ''Active Directory Query'' instance by
        default.


        To use this script with an instance of ''Active Directory Query V2'' specify
        using-brand="Active Directory Query".'
      id: 430b0162-0b03-4100-8803-f35b10f44c5c
      iscommand: false
      name: Run ADGetUser
      scriptName: ADGetUser
      type: regular
      version: -1
    taskid: 430b0162-0b03-4100-8803-f35b10f44c5c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: errData
          operator: isEqualString
          right:
            value:
              simple: 'No instances of "Active Directory Query" are configured.

                If you are trying to run "ADGetUser" with "Active Directory Query
                V2", please use the aquivilant command "ad-get-user" instead.'
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 755f9100-27ce-40bb-815a-4bab16eaf5f8
      iscommand: false
      name: Verify expected err message is shown
      type: condition
      version: -1
    taskid: 755f9100-27ce-40bb-815a-4bab16eaf5f8
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: d510a5b6-c8e8-44c9-8e7a-a2c442532bbd
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d510a5b6-c8e8-44c9-8e7a-a2c442532bbd
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 900\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"3_5_yes\": 0.41\n  },\n  \"paper\": {\n\
  \    \"dimensions\": {\n      \"height\": 915,\n      \"width\": 380,\n      \"\
  x\": 50,\n      \"y\": 50\n    }\n  }\n}"
