description: Test RSA P&L integration
id: rsa_packets_and_logs_test
inputs: []
name: RSA Packets And Logs test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: bdf24cf0-515e-4d2d-8ad3-d841d65b8017
      iscommand: false
      name: ''
      version: -1
    taskid: bdf24cf0-515e-4d2d-8ad3-d841d65b8017
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      concentratorIP: {}
      concentratorPort: {}
      flags:
        simple: regex,sp,si,sm
      limit:
        simple: '1'
      packets: {}
      search:
        simple: ^(.*)
      sessions: {}
      where: {}
    separatecontext: false
    task:
      brand: RSA NetWitness Packets and Logs
      description: Search for pattern matches in many sessions or packets
      id: 6bad06e4-975e-46f0-8d2c-ffe873025f58
      iscommand: true
      name: netwitness-msearch
      script: RSA NetWitness Packets and Logs|||netwitness-msearch
      type: regular
      version: -1
    taskid: 6bad06e4-975e-46f0-8d2c-ffe873025f58
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
      - '2'
      - '7'
      - '14'
      - '16'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 69837a16-595c-44f6-8782-93220ee4e598
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 69837a16-595c-44f6-8782-93220ee4e598
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 195\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    note: false
    scriptarguments:
      expectedValue: {}
      fields:
        simple: aliasHost
      path:
        simple: NetWitness.Events
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: b949bbb5-1ee0-4b3f-8730-b8ff546fe89d
      iscommand: false
      name: Verify Context
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: b949bbb5-1ee0-4b3f-8730-b8ff546fe89d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    note: false
    scriptarguments:
      expectedValue: {}
      fields:
        simple: ipSrc
      path:
        simple: NetWitness.Values
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: c2af2459-39ce-47db-8868-04d5b3d76236
      iscommand: false
      name: Verify Context
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: c2af2459-39ce-47db-8868-04d5b3d76236
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 545\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    scriptarguments:
      base64: {}
      concentratorIP: {}
      concentratorPort: {}
      excludeFileTypes: {}
      fileExt: {}
      flags: {}
      includeFileTypes: {}
      maxDirSize: {}
      maxSize: {}
      renameFileTypes: {}
      renderFlags: {}
      renderType: {}
      session:
        simple: '61'
      subdirFileTypes: {}
      where: {}
    separatecontext: false
    task:
      brand: RSA NetWitness Packets and Logs
      description: Returns the packet content for a session
      id: 5a84e5b2-9d39-4ef2-8862-5911446af4fd
      iscommand: true
      name: nw-sdk-content
      script: RSA NetWitness Packets and Logs|||nw-sdk-content
      type: regular
      version: -1
    taskid: 5a84e5b2-9d39-4ef2-8862-5911446af4fd
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 370\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    note: false
    scriptarguments:
      expectedValue: {}
      fields:
        simple: MD5
      path:
        simple: File
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: e76b7da3-c629-4954-8548-e7dbefd3be7a
      iscommand: false
      name: Verify Context
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: e76b7da3-c629-4954-8548-e7dbefd3be7a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 545\n  }\n}"
  '16':
    id: '16'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    scriptarguments:
      concentratorIP: {}
      concentratorPort: {}
      flags: {}
      id1: {}
      id2: {}
      lastHours:
        simple: '48'
      lastMinutes: {}
      query:
        simple: select alias.host where alias.host contains 'skimresources' group
          by alias.host
      size:
        simple: '100'
      threshold: {}
    separatecontext: false
    task:
      brand: RSA NetWitness Packets and Logs
      description: Performs a query against the meta database
      id: 867d2922-85ea-41b5-80e9-21227da0f8a5
      iscommand: true
      name: netwitness-query-where-and-group-by
      script: RSA NetWitness Packets and Logs|||netwitness-query
      type: regular
      version: -1
    taskid: 867d2922-85ea-41b5-80e9-21227da0f8a5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1770,\n    \"y\": 370\n  }\n}"
  '17':
    id: '17'
    ignoreworker: false
    note: false
    scriptarguments:
      concentratorIP: {}
      concentratorPort: {}
      flags: {}
      id1: {}
      id2: {}
      lastHours:
        simple: '48'
      lastMinutes: {}
      query:
        simple: select alias.host group by alias.host
      size:
        simple: '100'
      threshold: {}
    separatecontext: false
    task:
      brand: RSA NetWitness Packets and Logs
      description: Performs a query against the meta database
      id: 9285deed-0147-46ce-86a8-6d80b9908d96
      iscommand: true
      name: netwitness-query-group-by-only
      script: RSA NetWitness Packets and Logs|||netwitness-query
      type: regular
      version: -1
    taskid: 9285deed-0147-46ce-86a8-6d80b9908d96
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1770,\n    \"y\": 545\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      concentratorIP: {}
      concentratorPort: {}
      flags: {}
      id1: {}
      id2: {}
      lastHours: {}
      lastMinutes: {}
      query:
        simple: select alias.host where alias.host contains 'skimresources'
      size:
        simple: '100'
      threshold: {}
    separatecontext: false
    task:
      brand: RSA NetWitness Packets and Logs
      description: Performs a query against the meta database
      id: 8a2b7b6f-aa7c-4303-8395-cd84f3454f29
      iscommand: true
      name: netwitness-query-standard
      script: RSA NetWitness Packets and Logs|||netwitness-query
      type: regular
      version: -1
    taskid: 8a2b7b6f-aa7c-4303-8395-cd84f3454f29
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    scriptarguments:
      aggregateFieldName: {}
      aggregateFunction: {}
      concentratorIP: {}
      concentratorPort: {}
      fieldName:
        simple: ip.src
      flags:
        simple: sessions,sort-total,order-ascending
      id1: {}
      id2: {}
      max: {}
      min: {}
      size:
        simple: '20'
      threshold:
        simple: '100000'
      where:
        simple: time="2016-Jan-30 13:56:30"-"2018-May-21 12:20:49"
    separatecontext: false
    task:
      brand: RSA NetWitness Packets and Logs
      description: Performs a value count query and returns the matching values for
        a report
      id: 3043e05e-ead5-49c6-866b-263adc3b8b17
      iscommand: true
      name: nw-sdk-values
      script: RSA NetWitness Packets and Logs|||nw-sdk-values
      type: regular
      version: -1
    taskid: 3043e05e-ead5-49c6-866b-263adc3b8b17
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 370\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    note: false
    scriptarguments:
      expectedValue: {}
      fields:
        simple: hit
      path:
        simple: NetWitness.SearchHits
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 5d0c6722-ce3c-4aa2-8a8f-346541bc5658
      iscommand: false
      name: Verify Context
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 5d0c6722-ce3c-4aa2-8a8f-346541bc5658
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 590,\n      \"width\": 2100,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
