id: Exabeam - Test
inputs: []
name: Exabeam - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 24712de6-8daf-48b4-8384-766ce55a91c1
      iscommand: false
      name: ''
      version: -1
    taskid: 24712de6-8daf-48b4-8384-766ce55a91c1
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
      - '3'
      - '8'
      - '17'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: f84330a2-ef17-4831-848e-d2475fe246e9
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: f84330a2-ef17-4831-848e-d2475fe246e9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Returns all labels of the user.
      id: c762b259-893a-4848-821f-e47a886b07e5
      iscommand: true
      name: Get User Labels
      script: '|||exabeam-get-user-labels'
      type: regular
      version: -1
    taskid: c762b259-893a-4848-821f-e47a886b07e5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 865\n  }\n}"
  '11':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Exabeam.Watchlist.WatchlistID
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Exabeam.Watchlist.Title
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Exabeam.Watchlist.Category
          operator: isExists
      label: 'yes'
    id: '11'
    ignoreworker: false
    nexttasks:
      'yes':
      - '12'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d890a0eb-e982-4942-8f16-e027af612cfd
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: d890a0eb-e982-4942-8f16-e027af612cfd
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1040\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 75b591fb-91c0-4d31-82b8-ac6b828ab4bd
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 75b591fb-91c0-4d31-82b8-ac6b828ab4bd
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 1125,\n    \"y\": 1215\n  }\n}"
  '13':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Exabeam.UserLabel.Label
          operator: isEqualString
          right:
            value:
              simple: privileged_user
      label: 'yes'
    id: '13'
    ignoreworker: false
    nexttasks:
      'yes':
      - '12'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 68b8d33a-8a1d-4cde-8cad-9e2f539f175a
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 68b8d33a-8a1d-4cde-8cad-9e2f539f175a
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 1040\n  }\n}"
  '14':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Exabeam.PeerGroup.Name
          operator: isExists
      label: 'yes'
    id: '14'
    ignoreworker: false
    nexttasks:
      'yes':
      - '12'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 81d7977a-acd0-4dcd-846a-650f043ac568
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: 81d7977a-acd0-4dcd-846a-650f043ac568
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 1770,\n    \"y\": 1040\n  }\n}"
  '16':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Exabeam.User.Username
          operator: isEqualString
          right:
            value:
              simple: jmontoya
      - - left:
            iscontext: true
            value:
              simple: Exabeam.User.Session.SessionID
          operator: isExists
      label: 'yes'
    id: '16'
    ignoreworker: false
    nexttasks:
      'yes':
      - '12'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: e235d8cd-0161-48fe-8de2-6802ce7aeba0
      iscommand: false
      name: Verify Outputs
      type: condition
      version: -1
    taskid: e235d8cd-0161-48fe-8de2-6802ce7aeba0
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 1040\n  }\n}"
  '17':
    id: '17'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '18'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: f31070ed-df9e-4bdb-8899-bcf736d36a72
      iscommand: false
      name: Assets
      type: title
      version: -1
    taskid: f31070ed-df9e-4bdb-8899-bcf736d36a72
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 2200,\n    \"y\": 880\n  }\n}"
  '18':
    id: '18'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      asset_name:
        simple: 10.77.184.232
    separatecontext: false
    task:
      brand: ''
      description: Get asset data.
      id: c45bd566-51bb-48b4-8dd0-f2931087b138
      iscommand: true
      name: Get asset data
      script: '|||exabeam-get-asset-data'
      type: regular
      version: -1
    taskid: c45bd566-51bb-48b4-8dd0-f2931087b138
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 2200,\n    \"y\": 1040\n  }\n}"
  '19':
    id: '19'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '20'
    note: false
    scriptarguments:
      category:
        simple: Users
      description:
        simple: dummy sesc
      items:
        simple: bsalazar
      title:
        simple: my_tpb_watchlist
    separatecontext: false
    task:
      brand: ''
      description: Create a watchlist.
      id: 08ca42db-5ba7-4eca-872c-e727dbe9a11c
      iscommand: true
      name: Create watchlist
      script: '|||exabeam-create-watchlist'
      type: regular
      version: -1
    taskid: 08ca42db-5ba7-4eca-872c-e727dbe9a11c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 865\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
      - '19'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d8019d7d-931e-4ee5-8bf0-d8b321021225
      iscommand: false
      name: Watchlists
      type: title
      version: -1
    taskid: d8019d7d-931e-4ee5-8bf0-d8b321021225
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 705\n  }\n}"
  '20':
    id: '20'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      watchlist_id:
        complex:
          accessor: Watchlist.WatchlistID
          root: Exabeam
    separatecontext: false
    task:
      brand: ''
      description: Delete a watchlist.
      id: 2dba052e-c21f-45d1-8469-f6e853c3b956
      iscommand: true
      name: Delete watchlist
      script: '|||exabeam-delete-watchlist'
      type: regular
      version: -1
    taskid: 2dba052e-c21f-45d1-8469-f6e853c3b956
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1040\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
      - '10'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 1062d081-c2dc-4cf7-8db2-84988f220385
      iscommand: false
      name: Users
      type: title
      version: -1
    taskid: 1062d081-c2dc-4cf7-8db2-84988f220385
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 1125,\n    \"y\": 370\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Returns all watchlist IDs and titles.
      id: 4bf87f11-8d3a-4fc9-8461-68936a55bb94
      iscommand: true
      name: Get Watchlists
      script: '|||exabeam-get-watchlists'
      type: regular
      version: -1
    taskid: 4bf87f11-8d3a-4fc9-8461-68936a55bb94
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 865\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      limit:
        simple: '5'
      time_period:
        simple: 3 days
    separatecontext: false
    task:
      brand: ''
      description: Returns notable users in a period of time.
      id: a0651fe6-c99d-41d2-8b27-a6ff5e2e2eaf
      iscommand: true
      name: Get Notable Users
      script: '|||exabeam-get-notable-users'
      type: regular
      version: -1
    taskid: a0651fe6-c99d-41d2-8b27-a6ff5e2e2eaf
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 515\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      username:
        simple: jmontoya
    separatecontext: false
    task:
      brand: ''
      description: Returns user information data for the username.
      id: be8028ed-e75c-443d-8c33-f36f46b871ad
      iscommand: true
      name: Get User Info
      script: '|||exabeam-get-user-info'
      type: regular
      version: -1
    taskid: be8028ed-e75c-443d-8c33-f36f46b871ad
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 690\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    scriptarguments:
      end_time:
        simple: 2018-08-03 11:50:16
      start_time:
        simple: 2018-08-01 11:50:16
      username:
        simple: ${Exabeam.User.Username}
    separatecontext: false
    task:
      brand: ''
      description: Returns sessions for the given username and time range.
      id: fdf45308-91fb-4280-8cf4-f1e86a571ed7
      iscommand: true
      name: Get User Sessions
      script: '|||exabeam-get-user-sessions'
      type: regular
      version: -1
    taskid: fdf45308-91fb-4280-8cf4-f1e86a571ed7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 865\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: a3c36822-675c-4f4d-8b84-27a5d046c94d
      iscommand: false
      name: PeerGroups
      type: title
      version: -1
    taskid: a3c36822-675c-4f4d-8b84-27a5d046c94d
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 1770,\n    \"y\": 705\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Returns all peer groups.
      id: 2775ef26-5e51-41d6-8e39-f426ce531ef5
      iscommand: true
      name: Get Peer Groups
      script: '|||exabeam-get-peer-groups'
      type: regular
      version: -1
    taskid: 2775ef26-5e51-41d6-8e39-f426ce531ef5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1770,\n    \"y\": 865\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1230,\n      \"width\": 2530,\n      \"x\": 50,\n      \"y\":\
  \ 50\n    }\n  }\n}"
