description: '# Collect endpoint information based on SentinelOne commands.


  Input:

  * Hostname (Default: ${Endpoint.Hostname})'
fromversion: ''
id: Sentinel One - Endpoint data collection
inputs:
- description: The Hostname of the device to run on
  key: Hostname
  required: false
  value:
    simple: ${Endpoint.Hostname}
name: Sentinel One - Endpoint data collection
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '7'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 27fc5e2d-5e47-4d5b-81ef-889cfeb1676e
      iscommand: false
      name: ''
      version: -1
    taskid: 27fc5e2d-5e47-4d5b-81ef-889cfeb1676e
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": -120\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      agent_version__in: {}
      computer_name__like:
        simple: ${inputs.Hostname}
      core_count__gte: {}
      core_count__lte: {}
      cpu_count__gte: {}
      cpu_count__lte: {}
      created_at__gt: {}
      created_at__lt: {}
      domain__in: {}
      encrypted_applications: {}
      group_id: {}
      group_id__in: {}
      id__in: {}
      id__nin: {}
      include_decommissioned: {}
      infected: {}
      is_active: {}
      is_decommissioned: {}
      is_pending_uninstall: {}
      is_uninstalled: {}
      is_up_to_date: {}
      last_active_date__gt: {}
      last_active_date__lt: {}
      limit: {}
      machine_type__in: {}
      network_status: {}
      os_type: {}
      os_type__in: {}
      policy_id__in: {}
      query: {}
      registerd_at__gt: {}
      registered_at__lt: {}
      skip: {}
      total_memory__gte: {}
      total_memory__lte: {}
    separatecontext: false
    task:
      brand: SentinelOne
      description: ''
      id: a127bd66-2910-4a57-86b2-e0c36065263c
      iscommand: true
      name: Get  Host Agent info
      script: SentinelOne|||so-agents-query
      type: regular
      version: -1
    taskid: a127bd66-2910-4a57-86b2-e0c36065263c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      'no':
      - '3'
      'yes':
      - '5'
    note: false
    scriptarguments:
      value:
        simple: ${SentinelOne.Agents.Id}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 8a5366c2-6ab4-4eeb-8515-edde825d2f0d
      iscommand: false
      name: Did we get the Agent info?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 8a5366c2-6ab4-4eeb-8515-edde825d2f0d
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      value:
        simple: No Agent was found
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 88cf0630-08b2-4ec8-8dff-a49dc81a9f8c
      iscommand: false
      name: No Agent was found
      scriptName: Print
      type: regular
      version: -1
    taskid: 88cf0630-08b2-4ec8-8dff-a49dc81a9f8c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 51,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 85bc7a45-7439-417a-84a8-51eebf2753b3
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 85bc7a45-7439-417a-84a8-51eebf2753b3
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 865\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 9300a326-4267-4ade-8870-24310ab4445c
      iscommand: false
      name: Collect info
      type: title
      version: -1
    taskid: 9300a326-4267-4ade-8870-24310ab4445c
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      agent_id:
        simple: ${SentinelOne.Agents.Id}
    separatecontext: false
    task:
      brand: SentinelOne
      description: Get agent proccesses
      id: cdb41868-c1b9-471c-8abd-da5ca3cac6e6
      iscommand: true
      name: Get Processes
      script: SentinelOne|||so-get-agent-processes
      type: regular
      version: -1
    taskid: cdb41868-c1b9-471c-8abd-da5ca3cac6e6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 690\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#default#':
      - '4'
      'yes':
      - '1'
    note: false
    scriptarguments:
      value:
        simple: ${modules(val.brand=="SentinelOne")}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: d5db1794-ef8a-400b-8001-7f8f196f602e
      iscommand: false
      name: Is SentinelOne enabled?
      scriptName: Exists
      type: condition
      version: -1
    taskid: d5db1794-ef8a-400b-8001-7f8f196f602e
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 20\n  }\n}"
tests:
- No test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1050,\n      \"width\": 809,\n      \"x\": 51,\n      \"y\": -120\n\
  \    }\n  }\n}"
