contentitemfields:
  propagationLabels: []
id: Akamai_WAF_SIEM-Test
inputs: []
name: Akamai-WAF-SIEM_Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quiet: false
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 068d2e11-d07a-4ce8-831a-fb3f447cf178
      iscommand: false
      name: ''
      version: -1
    taskid: 068d2e11-d07a-4ce8-831a-fb3f447cf178
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quiet: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: b73ef49f-afb5-458c-8de4-aa0cefb724fa
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: b73ef49f-afb5-458c-8de4-aa0cefb724fa
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quiet: false
    scriptarguments:
      config_ids:
        simple: '50170'
      from_epoch:
        simple: '1576602011'
      limit:
        simple: '1'
      offset: {}
      period: {}
      to_epoch: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Get security events from Akamai WAF
      id: 2fc912e5-21a8-45c6-881d-4b089b2476b3
      iscommand: true
      name: Command get events
      script: '|||akamai-siem-get-events'
      type: regular
      version: -1
    taskid: 2fc912e5-21a8-45c6-881d-4b089b2476b3
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    quiet: false
    scriptarguments:
      add_to_context: {}
      brand_name:
        simple: Akamai WAF SIEM
      error_msg_in_incident: {}
      expect_data: {}
      instance_name: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Execute FetchIncident for a given instance
      id: cf1614be-f954-46b1-818f-9849edafaf02
      iscommand: false
      name: Fetch incidents
      scriptName: FetchFromInstance
      type: regular
      version: -1
    taskid: cf1614be-f954-46b1-818f-9849edafaf02
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 590,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
