id: Sandblast_malicious_test
inputs:
- description: ''
  key: Malicious
  required: false
  value:
    simple: 'true'
name: Sandblast_malicious_test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: d4fa9100-fb70-47b9-856b-20e03012889c
      iscommand: false
      name: ''
      version: -1
    taskid: d4fa9100-fb70-47b9-856b-20e03012889c
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": -300\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      benign_reports: {}
      features: {}
      file_id:
        simple: ${File.EntryID}
      file_name:
        simple: ${File.Name}
      file_type: {}
      images: {}
      md5: {}
      reports: {}
      sha1: {}
      sha256: {}
    separatecontext: false
    task:
      brand: ''
      description: Use the Upload API to have a client application request that Check
        Point Threat Prevention modules scan and analyze a file. When you upload a
        file to the service, the file is encrypted. It is un-encrypted during analysis,
        and then deleted
      id: 1008e4d4-41f5-480a-8069-bd3cc22506a7
      iscommand: true
      name: sandblast-upload
      script: '|||sandblast-upload'
      type: regular
      version: -1
    taskid: 1008e4d4-41f5-480a-8069-bd3cc22506a7
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 155\n  }\n}"
  '11':
    id: '11'
    note: false
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      id: {}
    separatecontext: false
    task:
      brand: Builtin
      description: Close the current incident
      id: b4192539-6ab9-4c75-86e0-71b56bfc18de
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: b4192539-6ab9-4c75-86e0-71b56bfc18de
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 840\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      benign_reports: {}
      features: {}
      file_name: {}
      file_type: {}
      images: {}
      md5:
        simple: ${File.MD5}
      quota: {}
      reports: {}
      sha1: {}
      sha256: {}
    separatecontext: false
    task:
      brand: Check Point Sandblast
      description: Use the Query API to have a client application look for either
        the analysis report of a specific file on the Check Point Threat Prevention
        service databases or the status of a file, uploaded for analysis
      id: 8d41e3a8-fdfc-4226-88f6-84105601df22
      iscommand: true
      name: sandblast-query
      script: Check Point Sandblast|||sandblast-query
      type: regular
      version: -1
    taskid: 8d41e3a8-fdfc-4226-88f6-84105601df22
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 510\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      'yes':
      - '2'
    note: false
    scriptarguments:
      value:
        simple: File.Malicious
    separatecontext: false
    task:
      brand: ''
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: f30d2083-6cae-4a8b-8a0f-ad5ccbf733f5
      iscommand: false
      name: Exists
      scriptName: Exists
      type: condition
      version: -1
    taskid: f30d2083-6cae-4a8b-8a0f-ad5ccbf733f5
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 320\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      'yes':
      - '11'
    note: false
    scriptarguments:
      value:
        simple: File.Malicious
    separatecontext: false
    task:
      brand: ''
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      id: 42626316-95fa-4483-8d15-cbe2a12faea4
      iscommand: false
      name: Exists
      scriptName: Exists
      type: condition
      version: -1
    taskid: 42626316-95fa-4483-8d15-cbe2a12faea4
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 675\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 01b6224a-9dd0-4e88-8648-de2bef70f104
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 01b6224a-9dd0-4e88-8648-de2bef70f104
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": -180\n  }\n}"
  '9':
    id: '9'
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      body: {}
      filename:
        simple: test.pdf
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: http://www.pdf995.com/samples/pdf.pdf
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: Sends http request. Returns the response as json.
      id: 0c868ff7-1f1f-4e93-8e93-3d2a0495f5b3
      iscommand: false
      name: http
      scriptName: http
      type: regular
      version: -1
    taskid: 0c868ff7-1f1f-4e93-8e93-3d2a0495f5b3
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 0\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1235,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": -300\n\
  \    }\n  }\n}"
