description: ''
id: Cherwell Example Scripts - test
inputs: []
name: Cherwell Example Scripts - test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: dae78645-0ec8-4d24-8ec8-6d8cdb244f5c
      iscommand: false
      name: ''
      version: -1
    taskid: dae78645-0ec8-4d24-8ec8-6d8cdb244f5c
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      customer_display_name:
        simple: Playbook customer
      description:
        simple: 'Example scripts test playbook '
      owned_by: {}
      priority:
        simple: '1'
      service:
        simple: Account Management
    separatecontext: false
    task:
      brand: ''
      description: This script is an example script of how to create an incident in
        Cherwell. The scruot wraps the create business bject command in the cherwell
        integration. When writing your own script to creat a business object, follow
        the instructions in the configuration part, leace the execution part untouched
      id: 02688c4e-0a73-466a-8880-16fe64babbc3
      iscommand: false
      name: Cherwell Create Incident - script
      scriptName: CherwellCreateIncident
      type: regular
      version: -1
    taskid: 02688c4e-0a73-466a-8880-16fe64babbc3
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      incident_record_id:
        simple: ${Cherwell.BusinessObjects(val.Description).RecordId}
      task_record_id:
        simple: ${Cherwell.BusinessObjects(!val.Description).RecordId}
    separatecontext: false
    task:
      brand: ''
      description: This script is an example script of how to link an Incident to
        a Task in Cherwell. The script wraps the cherwell-link-business-object command
        of the cherwell integration. When writing your own script to link business
        objects, follow the instructions found in the configuration section of the
        script, leave the execution part untouched.
      id: cfe5411a-35b4-443d-8cae-43c5811c4a6d
      iscommand: false
      name: Cherwell Incident Own Task
      scriptName: CherwellIncidentOwnTask
      type: regular
      version: -1
    taskid: cfe5411a-35b4-443d-8cae-43c5811c4a6d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1770\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    scriptarguments:
      id_type:
        simple: public_id
      id_value:
        simple: ${Cherwell.BusinessObjects(!val.Description).PublicId}
      type:
        simple: Task
    separatecontext: false
    task:
      brand: ''
      description: Get a business objects by an id
      id: db216a1e-8b39-4add-8268-0e8b528dd5c3
      iscommand: true
      name: Cherwell Get Task
      script: '|||cherwell-get-business-object'
      type: regular
      version: -1
    taskid: db216a1e-8b39-4add-8268-0e8b528dd5c3
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1945\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '20'
    note: false
    scriptarguments:
      incident_record_id:
        simple: ${Cherwell.BusinessObjects(!val.Type).RecordId}
      task_record_id:
        simple: ${Cherwell.BusinessObjects(val.Type == 'Work Item').RecID}
    separatecontext: false
    task:
      brand: ''
      description: This script is an example script of how to unlink a Task from am
        Incident in Cherwell. The script wraps the cherwell-unlink-business-object
        command of the cherwell integration. When writing your own script to unlink
        business objects, follow the instructions found in the configuration section
        of the script, leave the execution part untouched.
      id: 24f8e464-e893-48ef-8fda-8316f96a18d2
      iscommand: false
      name: Cherwell Incident Unlink Task
      scriptName: CherwellIncidentUnlinkTask
      type: regular
      version: -1
    taskid: 24f8e464-e893-48ef-8fda-8316f96a18d2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 2295\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 702740e9-6931-46af-8280-47589da43934
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 702740e9-6931-46af-8280-47589da43934
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 2995\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: c5909faf-c6b1-4f88-8848-bcc815c99baa
      iscommand: false
      name: Clear Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: c5909faf-c6b1-4f88-8848-bcc815c99baa
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '15':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: BusinessObjects(val.Type == 'Work Item').ParentRecID}
                root: ${Cherwell
                transformers:
                - args:
                    index:
                      value:
                        simple: '0'
                  operator: atIndex
          operator: isEqualString
          right:
            iscontext: true
            value:
              complex:
                accessor: BusinessObjects(!val.Type).RecordId}
                root: ${Cherwell
                transformers:
                - args:
                    index:
                      value:
                        simple: '0'
                  operator: atIndex
      label: 'yes'
    id: '15'
    ignoreworker: false
    nexttasks:
      'yes':
      - '12'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: f9711ad0-98a6-4beb-83e9-e6fe37e6d035
      iscommand: false
      name: Validate Incident Own Task
      type: condition
      version: -1
    taskid: f9711ad0-98a6-4beb-83e9-e6fe37e6d035
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 2120\n  }\n}"
  '16':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Cherwell.QueryResults.Priority
          operator: containsGeneral
          right:
            value:
              simple: '2'
      - - left:
            iscontext: true
            value:
              simple: Cherwell.QueryResults.RecordId
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cherwell.QueryResults.PublicId
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cherwell.QueryResults.Description
          operator: containsGeneral
          right:
            value:
              simple: Example scripts test playbook
      - - left:
            iscontext: true
            value:
              simple: Cherwell.QueryResults.OwnedBy
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cherwell.QueryResults.Service
          operator: containsGeneral
          right:
            value:
              simple: Account Management
      - - left:
            iscontext: true
            value:
              simple: Cherwell.QueryResults.CustomerDisplayName
          operator: containsGeneral
          right:
            value:
              simple: Playbook customer
      - - left:
            iscontext: true
            value:
              simple: Cherwell.QueryResults.CreatedDateTime
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cherwell.QueryResults.TotalTasks
          operator: isEqualNumber
          right:
            value:
              simple: '0'
      label: 'yes'
    id: '16'
    ignoreworker: false
    nexttasks:
      'yes':
      - '2'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 1b2e85b6-a871-4e4d-8a55-3dc9c941c02f
      iscommand: false
      name: Validate Get Incident
      type: condition
      version: -1
    taskid: 1b2e85b6-a871-4e4d-8a55-3dc9c941c02f
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1420\n  }\n}"
  '17':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${Cherwell.BusinessObjects(val.Type).ParentPublicID}
          operator: isEmpty
      label: 'yes'
    id: '17'
    ignoreworker: false
    nexttasks:
      'yes':
      - '18'
      - '19'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 53f03aad-53ef-4baf-88ff-64c38e463bd4
      iscommand: false
      name: Validate Incident Unlink Task
      type: condition
      version: -1
    taskid: 53f03aad-53ef-4baf-88ff-64c38e463bd4
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 2645\n  }\n}"
  '18':
    id: '18'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    scriptarguments:
      id_type:
        simple: public_id
      id_value:
        simple: ${Cherwell.BusinessObjects(!val.Type).PublicId}
      type:
        simple: Incident
    separatecontext: false
    task:
      brand: ''
      description: Delete a given business object
      id: ae8e0f4b-0093-4a23-8425-11bbb6937570
      iscommand: true
      name: 'Delete Incident '
      script: '|||cherwell-delete-business-object'
      type: regular
      version: -1
    taskid: ae8e0f4b-0093-4a23-8425-11bbb6937570
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2820\n  }\n}"
  '19':
    id: '19'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    scriptarguments:
      id_type:
        simple: public_id
      id_value:
        simple: ${Cherwell.BusinessObjects(val.Type).PublicId}
      type:
        simple: Task
    separatecontext: false
    task:
      brand: ''
      description: Delete a given business object
      id: bfa4a8ff-6ba8-45fa-822e-5e9e98ae5ee2
      iscommand: true
      name: 'Delete Task '
      script: '|||cherwell-delete-business-object'
      type: regular
      version: -1
    taskid: bfa4a8ff-6ba8-45fa-822e-5e9e98ae5ee2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2820\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      json:
        simple: "{\n\"Title\": \"Test task\", \n\"Description\": \"Test task generated\
          \ from scripts test playbook\", \n\"OwnedByTeam\": \"HR\",\n\"Type\":\"\
          Work Item\", \n\"Status\":\"New\"\n}"
      type:
        simple: task
    separatecontext: false
    task:
      brand: ''
      description: Create a business object
      id: 29f49fcc-09fb-4b26-8b6b-fb2e7fbe9763
      iscommand: true
      name: Cherwell Create Task - command
      script: '|||cherwell-create-business-object'
      type: regular
      version: -1
    taskid: 29f49fcc-09fb-4b26-8b6b-fb2e7fbe9763
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1595\n  }\n}"
  '20':
    id: '20'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    scriptarguments:
      id_type:
        simple: public_id
      id_value:
        simple: ${Cherwell.BusinessObjects(val.Type).PublicId}
      type:
        simple: Task
    separatecontext: false
    task:
      brand: ''
      description: Get a business objects by an id
      id: 3d2c94cf-3b01-4832-8ce7-1de36d94ca65
      iscommand: true
      name: Cherwell Get Task
      script: '|||cherwell-get-business-object'
      type: regular
      version: -1
    taskid: 3d2c94cf-3b01-4832-8ce7-1de36d94ca65
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 2470\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      id_type:
        simple: public_id
      id_value:
        simple: ${Cherwell.BusinessObjects.PublicId}
    separatecontext: false
    task:
      brand: ''
      description: This script is an example script of how to retreive an incident
        from Cherwell. The script wraps the cherwell-get-business-object command of
        the cherwell integration. When writing your own script to get a business object,
        follow the instructions found in the configuration section of the script,
        leave the execution part untouched.
      id: d4029e9f-00d7-4519-889b-a33df5d2c4c9
      iscommand: false
      name: Cherwell Get Incident
      scriptName: CherwellGetIncident
      type: regular
      version: -1
    taskid: d4029e9f-00d7-4519-889b-a33df5d2c4c9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 895\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      description: {}
      id_type:
        simple: public_id
      id_value:
        simple: ${Cherwell.BusinessObjects.PublicId}
      owned_by: {}
      priority:
        simple: '2'
      service: {}
    separatecontext: false
    task:
      brand: ''
      description: This script is an example script of how to update an incident in
        Cherwell. The script wraps the update-business-object command of the cherwell
        integration. When writing your own script to update a business object, follow
        the instructions found in the configuration section of the script, leave the
        execution part untouched.
      id: b01c3e70-66ae-4f27-80d6-950bba2fda78
      iscommand: false
      name: Cherwell Update Incident
      scriptName: CherwellUpdateIncident
      type: regular
      version: -1
    taskid: b01c3e70-66ae-4f27-80d6-950bba2fda78
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    scriptarguments:
      query:
        simple: '[["Priority","lt","3"],["Description","contains","Example scripts"]]'
    separatecontext: false
    task:
      brand: ''
      description: This script is an example script of how to query incidents from
        Cherwell. The script wraps the cherwell-query-business-object command of the
        cherwell integration. When writing your own script to query  business objects,
        follow the instructions found in the configuration section of the script,
        leave the execution part untouched.
      id: e5ac0def-5ae1-4ee8-8998-5a96b229eb6b
      iscommand: false
      name: Cherwell Query Incident
      scriptName: CherwellQueryIncidents
      type: regular
      version: -1
    taskid: e5ac0def-5ae1-4ee8-8998-5a96b229eb6b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1245\n  }\n}"
  '7':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Cherwell.BusinessObjects.PublicId
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cherwell.BusinessObjects.RecordId
          operator: isExists
      label: 'yes'
    id: '7'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: af82e97d-2eff-42af-8168-6ea751a23b73
      iscommand: false
      name: Validate Create Incident
      type: condition
      version: -1
    taskid: af82e97d-2eff-42af-8168-6ea751a23b73
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 545\n  }\n}"
  '8':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Cherwell.BusinessObjects.Priority
          operator: isEqualString
          right:
            value:
              simple: '2'
      - - left:
            iscontext: true
            value:
              simple: Cherwell.BusinessObjects.RecordId
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cherwell.BusinessObjects.PublicId
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cherwell.BusinessObjects.Description
          operator: isEqualString
          right:
            value:
              simple: Example scripts test playbook
      - - left:
            iscontext: true
            value:
              simple: Cherwell.BusinessObjects.Service
          operator: isEqualString
          right:
            value:
              simple: Account Management
      - - left:
            iscontext: true
            value:
              simple: Cherwell.BusinessObjects.CustomerDisplayName
          operator: isEqualString
          right:
            value:
              simple: Playbook customer
      - - left:
            iscontext: true
            value:
              simple: Cherwell.BusinessObjects.CreatedDateTime
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cherwell.BusinessObjects.TotalTasks
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Cherwell.BusinessObjects.OwnedBy
          operator: isExists
      label: 'yes'
    id: '8'
    ignoreworker: false
    nexttasks:
      'yes':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 0500316a-49e0-45cc-8e53-83050fc7c5d0
      iscommand: false
      name: Validate Get Incident
      type: condition
      version: -1
    taskid: 0500316a-49e0-45cc-8e53-83050fc7c5d0
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1070\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 3010,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
