id: Elasticsearch_v2_test
inputs: []
name: Elasticsearch_v2_test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 938b52b4-c7af-4d75-8724-cc015cda9bfa
      iscommand: false
      name: ''
      version: -1
    taskid: 938b52b4-c7af-4d75-8724-cc015cda9bfa
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 1771af49-8703-4635-8166-02f33183cba0
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 1771af49-8703-4635-8166-02f33183cba0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 200\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: b35308bb-acf6-48a9-825e-2849f8609bf0
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: b35308bb-acf6-48a9-825e-2849f8609bf0
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 460,\n    \"y\": 1750\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 0e464169-9978-4860-8b4b-d669f7225c95
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 0e464169-9978-4860-8b4b-d669f7225c95
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 460,\n    \"y\": 710\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 7d04f0c5-9f39-479d-8c24-7fc121739064
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 7d04f0c5-9f39-479d-8c24-7fc121739064
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 460,\n    \"y\": 1200\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    scriptarguments:
      explain: {}
      fields: {}
      index:
        simple: customer
      page: {}
      query:
        simple: check
      size:
        simple: '1'
      sort-field:
        simple: nums
      sort-order:
        simple: asc
    separatecontext: false
    task:
      brand: Elasticsearch v2
      description: search index using Elasticsearch
      id: 183faa74-0d37-4484-8785-1bdb366453ee
      iscommand: true
      name: search - sort ascending
      script: Elasticsearch v2|||search
      type: regular
      version: -1
    taskid: 183faa74-0d37-4484-8785-1bdb366453ee
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 460,\n    \"y\": 1360\n  }\n}"
  '14':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Elasticsearch.Search.Results._id
          operator: isEqualString
          right:
            value:
              simple: vfWp3GwBqofk71c5-NOI
      label: 'yes'
    id: '14'
    ignoreworker: false
    nexttasks:
      'yes':
      - '10'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: b5e5d359-d90e-4da8-8d44-bb55823ecbe4
      iscommand: false
      name: verify ascend
      type: condition
      version: -1
    taskid: b5e5d359-d90e-4da8-8d44-bb55823ecbe4
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 460,\n    \"y\": 1540\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      explain: {}
      fields: {}
      index:
        simple: customer
      page: {}
      query:
        simple: '*'
      size: {}
      sort-field: {}
      sort-order: {}
    separatecontext: false
    task:
      brand: Elasticsearch v2
      description: search index using Elasticsearch
      id: 823b4680-d95a-4d1d-8d7e-e7a3c41fc67f
      iscommand: true
      name: general search
      script: Elasticsearch v2|||search
      type: regular
      version: -1
    taskid: 823b4680-d95a-4d1d-8d7e-e7a3c41fc67f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 370\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Elasticsearch.Search.total.value
          operator: greaterThan
          right:
            value:
              simple: '0'
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '11'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: e87d351f-7817-48bc-8d51-a63814495065
      iscommand: false
      name: Verify results
      type: condition
      version: -1
    taskid: e87d351f-7817-48bc-8d51-a63814495065
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 540\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      explain: {}
      fields: {}
      index:
        simple: customer
      page: {}
      query:
        simple: check
      size:
        simple: '1'
      sort-field:
        simple: nums
      sort-order:
        simple: desc
    separatecontext: false
    task:
      brand: Elasticsearch v2
      description: search index using Elasticsearch
      id: db6a432f-3158-439a-806f-cdd4aad3fd53
      iscommand: true
      name: search - sort descending
      script: Elasticsearch v2|||search
      type: regular
      version: -1
    taskid: db6a432f-3158-439a-806f-cdd4aad3fd53
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 460,\n    \"y\": 870\n  }\n}"
  '8':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Elasticsearch.Search.Results._id
          operator: isEqualString
          right:
            value:
              simple: xPXG62wBqofk71c5KdOw
      label: 'yes'
    id: '8'
    ignoreworker: false
    nexttasks:
      'yes':
      - '12'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 7aa7cece-04c9-47b6-8bd1-7463e172adf9
      iscommand: false
      name: verify decend
      type: condition
      version: -1
    taskid: 7aa7cece-04c9-47b6-8bd1-7463e172adf9
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 460,\n    \"y\": 1030\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1765,\n      \"width\": 390,\n      \"x\": 450,\n      \"y\":\
  \ 50\n    }\n  }\n}"
