description: This is a playbook for performing for testing all google docs commands.
  creation, update and get.
id: GoogleDocs-test
inputs: []
name: GoogleDocs-test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 4acf014d-a5fc-4a0f-8e02-6f9da387ab39
      iscommand: false
      name: ''
      version: -1
    taskid: 4acf014d-a5fc-4a0f-8e02-6f9da387ab39
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      title:
        simple: test_file
    separatecontext: false
    task:
      brand: GoogleDocs
      description: Creates a document
      id: 5e6c6540-005e-46e2-82a6-3438abc5e54e
      iscommand: true
      name: Create Test Doucment
      script: GoogleDocs|||google-docs-create-document
      type: regular
      version: -1
    taskid: 5e6c6540-005e-46e2-82a6-3438abc5e54e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      document_id:
        complex:
          accessor: DocumentId
          root: GoogleDocs
    separatecontext: false
    task:
      brand: GoogleDocs
      description: Returns a document matching the given ID.
      id: 4c495078-ea58-4fb7-8f28-4c680e7b330a
      iscommand: true
      name: 'Get Document after creation '
      script: GoogleDocs|||google-docs-get-document
      type: regular
      version: -1
    taskid: 4c495078-ea58-4fb7-8f28-4c680e7b330a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      actions:
        simple: insertTable{1,7,9}
      document_id:
        simple: ${GoogleDocs.DocumentId}
      required_revision_id:
        simple: ${GoogleDocs.RevisionId}
      target_revision_id: {}
    separatecontext: false
    task:
      brand: GoogleDocs
      description: Updates a document with a given ID
      id: 7b989b93-9175-4d37-8cdf-3e88443e2562
      iscommand: true
      name: Update document
      script: GoogleDocs|||google-docs-update-document
      type: regular
      version: -1
    taskid: 7b989b93-9175-4d37-8cdf-3e88443e2562
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 730\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    scriptarguments:
      document_id:
        simple: ${GoogleDocs.DocumentId}
    separatecontext: false
    task:
      brand: GoogleDocs
      description: Returns a document matching the given ID.
      id: a0aa50db-4056-4097-85de-68e5ac338788
      iscommand: true
      name: Get document after update
      script: GoogleDocs|||google-docs-get-document
      type: regular
      version: -1
    taskid: a0aa50db-4056-4097-85de-68e5ac338788
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 07fe34d2-b010-4913-8ad3-582d8557bbc8
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 07fe34d2-b010-4913-8ad3-582d8557bbc8
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 940,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
