description: This playbook can be used in a job to whitelist indicators from PhishLabs
  that were classified as false positives, according to a defined period of time.
fromversion: 4.0.0
id: PhishLabs - Whitelist false positives
inputs:
- description: Whitelist indicators within this duration (from now).
  key: Since
  required: false
  value:
    simple: 1h
name: PhishLabs - Whitelist false positives
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 6def49b7-29f8-4905-8db0-6448936126ad
      iscommand: false
      name: ''
      version: -1
    taskid: 6def49b7-29f8-4905-8db0-6448936126ad
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      delete_false_positive:
        simple: 'true'
      indicator_type: {}
      limit: {}
      remove_protocol: {}
      remove_query: {}
      since:
        complex:
          root: inputs.Since
    separatecontext: false
    task:
      brand: ''
      description: Populate indicators by the PhishLabs IOC global feed.
      id: 5bf410a0-bb6f-4278-80a9-aaf0e6122344
      iscommand: false
      name: Whitelist false positives
      scriptName: PhishLabsPopulateIndicators
      type: regular
      version: -1
    taskid: 5bf410a0-bb6f-4278-80a9-aaf0e6122344
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      id: {}
    separatecontext: false
    task:
      brand: Builtin
      description: Close the current incident.
      id: 58403bf5-5825-4058-8c42-6cbfdb6caac2
      iscommand: true
      name: Close investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 58403bf5-5825-4058-8c42-6cbfdb6caac2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: PhishLabs IOC
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '4'
      'yes':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: bf18488a-3da2-4074-84f4-71d023dbb313
      iscommand: false
      name: Is PhishLabs IOC enabled?
      type: condition
      version: -1
    taskid: bf18488a-3da2-4074-84f4-71d023dbb313
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 4682a8db-5f39-4d30-8385-3b1ead5d338b
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 4682a8db-5f39-4d30-8385-3b1ead5d338b
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 740\n  }\n}"
tests:
- PhishLabsTestPopulateIndicators
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 755,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
