id: forcepoint test
inputs: []
name: forcepoint test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: b3e76235-b461-46d2-80aa-c53a64d18b7c
      iscommand: false
      name: ''
      version: -1
    taskid: b3e76235-b461-46d2-80aa-c53a64d18b7c
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: 'Deletes previous context '
      id: c45723e1-b428-41da-89ad-7e11c82c390e
      iscommand: false
      name: Delete Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: 3fee81c5-3b59-4e8e-8ee7-e5e09da65c8a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      categoryDescription: {}
      categoryName:
        simple: NEW TEST CATEGORY
      parent: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Forcepoint
      description: Will Add new API-managed category.
      id: d28c1a0a-18eb-429c-803c-b9fa04bdf384
      iscommand: true
      name: Add new 'TEST' category
      script: Forcepoint|||fp-add-category
      type: regular
      version: -1
    taskid: ac0556df-aba3-4a09-8493-5f689b6c4f70
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quietmode: 0
    scriptarguments:
      categoryId: {}
      categoryName:
        simple: ${Forcepoint.AddCategory.CategoryName}
      extend-context: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Forcepoint
      description: Query by category name
      id: 8ac94280-84c1-465f-88da-a48ac24c5eaa
      iscommand: true
      name: Get new category details
      script: Forcepoint|||fp-get-category-detailes
      type: regular
      version: -1
    taskid: 87314ac8-4c2b-4265-8424-c6e9eae5a251
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      categoryID: {}
      categoryName:
        simple: ${Forcepoint.CategoryDetails.CategoryName}
      ips: {}
      urls:
        simple: https://test.com,http://dem.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: Forcepoint
      description: 'Using the ID associated with the new category.

        Add ''https://test.com'', ''http://dem.com'' to category URL list.'
      id: 8d9036f8-48b8-44fb-84e2-2ac5fe0a0d0a
      iscommand: true
      name: Add URLs to 'TEST' category
      script: Forcepoint|||fp-add-address-to-category
      type: regular
      version: -1
    taskid: 405a4d19-0f8e-4c83-80a4-32e558f876ed
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      categoryID:
        simple: ${Forcepoint.CategoryDetails.CategoryID}
      categoryName: {}
      ips: {}
      urls:
        simple: https://test.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: Forcepoint
      description: Delete https://test.com from the category URL list
      id: 1bd3107e-0132-4560-8b91-6a71ad091ca3
      iscommand: true
      name: Delete URL from 'TEST' category
      script: Forcepoint|||fp-delete-address-from-category
      type: regular
      version: -1
    taskid: e9517bb9-565f-4c71-8625-66917e1a2516
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      categoryId:
        simple: ${Forcepoint.CategoryDetails.CategoryID}
      categoryName: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Forcepoint
      id: cc9e9986-06e7-4986-86a0-cc90cbcada96
      iscommand: true
      name: Get 'TEST' category details after alterations
      script: Forcepoint|||fp-get-category-detailes
      type: regular
      version: -1
    taskid: 67c019d5-a69d-4ea0-8dc8-8095cfd11c13
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      categoryIDs:
        simple: ${Forcepoint.CategoryDetails.CategoryID}
      categoryNames: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Forcepoint
      description: Using the category ID
      id: ece37b21-c90b-4240-8681-98c7f46bb12f
      iscommand: true
      name: Delete 'TEST' category
      script: Forcepoint|||fp-delete-categories
      type: regular
      version: -1
    taskid: 7f927d99-8eb6-428d-8fe0-e4d920d4e046
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1290,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
