id: TestHPServiceManager
inputs: []
name: TestHPServiceManager
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: e0666c9c-106f-4da4-8f2f-0ca63991c23f
      iscommand: false
      name: ''
      version: -1
    taskid: e0666c9c-106f-4da4-8f2f-0ca63991c23f
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: a68cf45b-e944-40cb-8d55-8592b592103b
      iscommand: false
      name: DeleteContext
      script: DeleteContext
      type: regular
      version: -1
    taskid: 0078ae49-bd9b-406d-875a-3c5b44e275ed
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: b29cb06c-8eb2-4618-8e40-5890813ec954
      iscommand: false
      name: DeleteContext
      script: DeleteContext
      type: regular
      version: -1
    taskid: 9f52ca06-1fb7-4fc0-8516-3ff366edbc6b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    quietmode: 0
    scriptarguments:
      expectedValue:
        simple: '["IM10259"]'
      fields: {}
      path:
        simple: HPSM.IncidentIDs
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 4c117414-49cf-43b0-84b4-d5e974e85cd7
      iscommand: false
      name: VerifyContext HPSM.IncidentIDs
      script: VerifyContext
      type: regular
      version: -1
    taskid: 85baa12e-1ec3-4f0e-8d64-6c6e4d8019ee
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2120\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    quietmode: 0
    scriptarguments:
      field1:
        simple: Ticket.ID
      field2:
        simple: Ticket.Creator
      field3:
        simple: Ticket.Assignee
      field4:
        simple: Ticket.State
      value1:
        simple: IM10258
      value2:
        simple: System.Admin
      value3:
        simple: Incident.Manager
      value4:
        simple: Categorize
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 5e466429-1b4d-472b-8345-bcf9185c00c4
      iscommand: false
      name: VerifyContextFields Tickets fields correct
      script: VerifyContextFields
      type: regular
      version: -1
    taskid: a8ee6ef8-874d-44c8-86c0-83d3f7366ea9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1596\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    quietmode: 0
    scriptarguments:
      configurationItem:
        simple: CI1000001
    separatecontext: false
    skipunavailable: false
    task:
      brand: Service Manager
      id: 9432fc74-24dc-4e81-8a64-c192689e3e4a
      iscommand: true
      name: hpsm-get-device
      script: Service Manager|||hpsm-get-device
      type: regular
      version: -1
    taskid: ae10e437-0242-411d-82ba-6ce313e306ed
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2326\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      expectedValue: {}
      fields:
        simple: ConfigurationItem,DisplayName,Status
      path:
        simple: HPSM.Devices
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: f2adcf2d-8cb6-4104-80ee-6f00b6887c82
      iscommand: false
      name: Verify Context Fields HPSM.Devices
      script: VerifyContext
      type: regular
      version: -1
    taskid: f4eded68-7ef1-4009-8cee-bdac8ac12e07
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2541\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      expectedValue: {}
      fields:
        simple: IncidentID,Description,Title,Assignee,OpenedBy
      path:
        simple: HPSM.Incidents
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 3721dbde-c958-4760-8c07-1e8b56ff52bf
      iscommand: false
      name: VerifyContext HPSM.Incidents
      script: VerifyContext
      type: regular
      version: -1
    taskid: 059a422b-ddc9-41be-84b7-40fe71efd907
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    quietmode: 0
    scriptarguments:
      expectedValue: {}
      fields:
        simple: ID,Creator,Assignee,State
      path:
        simple: Ticket
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Verify that get-incident-by-id exports and converts ticket in Demisto
        general format
      id: 5aca81bb-4da2-4985-80c5-2e35c4c7ffcc
      iscommand: false
      name: VerifyContext HPSM.Ticket
      script: VerifyContext
      type: regular
      version: -1
    taskid: 915d0b30-749a-46af-819e-0527589c0928
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      affectedCI: {}
      alertStatus: {}
      area: {}
      assignmentGroup: {}
      category:
        simple: incident
      company: {}
      description:
        simple: This is description
      impact: {}
      phase: {}
      service:
        simple: CI1001030
      status: {}
      subarea: {}
      title:
        simple: TestPlaybookTitleCreated
      urgency: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Service Manager
      description: 'Creating new incident '
      id: 8fd733b2-b206-4feb-87cb-22230a899f40
      iscommand: true
      name: hpsm-create-incident
      script: Service Manager|||hpsm-create-incident
      type: regular
      version: -1
    taskid: 6eb21ea1-34ea-4eda-84e1-f20c5ed677b9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    quietmode: 0
    scriptarguments:
      query:
        simple: Title=TestPlaybookListIncidents
    separatecontext: false
    skipunavailable: false
    task:
      brand: Service Manager
      description: Returns all incidents
      id: 374f31f9-5b48-474e-86dc-90720214838e
      iscommand: true
      name: hpsm-list-incidents
      script: Service Manager|||hpsm-list-incidents
      type: regular
      version: -1
    taskid: 0ffb1072-3851-47eb-886c-26d56e59b461
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1945\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    quietmode: 0
    scriptarguments:
      incidentId:
        simple: IM10258
    separatecontext: false
    skipunavailable: false
    task:
      brand: Service Manager
      id: 4f34fba9-8047-4201-8701-4139b20d1683
      iscommand: true
      name: hpsm-get-incident-by-id
      script: Service Manager|||hpsm-get-incident-by-id
      type: regular
      version: -1
    taskid: 0951a22e-5cfd-42c0-8599-d11bb83237b9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: a1d2b6bb-4398-48f3-8954-d84613b4009d
      iscommand: false
      name: DeleteContext
      script: DeleteContext
      type: regular
      version: -1
    taskid: acbea6dd-4bfa-4d12-8185-873c582f6f1a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    quietmode: 0
    scriptarguments:
      expectedValue: {}
      fields:
        simple: ID,Creator,Assignee,State
      path:
        simple: Ticket
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Verify that get-incident-by-id exports and converts ticket in Demisto
        general format
      id: a16b7448-9d05-4f55-8c38-713bdd6c0246
      iscommand: false
      name: VerifyContext Ticket
      script: VerifyContext
      type: regular
      version: -1
    taskid: 3b074203-ccca-47f9-856b-4617c9acd131
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      expectedValue: {}
      fields:
        simple: IncidentID,Description,Title,Assignee,OpenedBy
      path:
        simple: HPSM.Incidents
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: accefebe-2c7d-4238-8821-72ba278605ea
      iscommand: false
      name: VerifyContext HPSM.Incidents
      script: VerifyContext
      type: regular
      version: -1
    taskid: 5326d459-3e65-49b5-8221-64c54344d314
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2586,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
