id: Symantec ATP Test
inputs: []
name: Symantec ATP Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 206c9190-2a2e-4ebc-8090-b4513012229a
      iscommand: false
      name: ''
      version: -1
    taskid: 206c9190-2a2e-4ebc-8090-b4513012229a
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": -110\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 44a675db-fb35-4f53-801c-417660dab0de
      iscommand: true
      name: Get appliances
      script: '|||satp-appliances'
      type: regular
      version: -1
    taskid: 44a675db-fb35-4f53-801c-417660dab0de
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 230\n  }\n}"
  '10':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: incident
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: incident
          operator: isNotEmpty
      label: 'yes'
    id: '10'
    nexttasks:
      'yes':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: a006ab3a-cd27-4dbd-8d39-8eff39ddd87f
      iscommand: false
      name: Verify file context
      type: condition
      version: -1
    taskid: a006ab3a-cd27-4dbd-8d39-8eff39ddd87f
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 1570\n  }\n}"
  '2':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ATPAppliance
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ATPAppliance
          operator: isNotEmpty
      label: 'yes'
    id: '2'
    nexttasks:
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 6c4a68be-7e98-4e11-8105-dbd2b2a97025
      iscommand: false
      name: Verify appliances context
      type: condition
      version: -1
    taskid: 6c4a68be-7e98-4e11-8105-dbd2b2a97025
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 410\n  }\n}"
  '3':
    id: '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 7e27fb46-55d6-400d-8cb9-c80c740142ec
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 7e27fb46-55d6-400d-8cb9-c80c740142ec
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 1770\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      hash:
        simple: 09068bc7c18af175ecc13e41ad72da56337be7f3fdb1acf793156f98d565bb64
    separatecontext: false
    task:
      brand: ''
      id: fc1d820f-6107-4dfc-89e5-aa32d30f6384
      iscommand: true
      name: Get file
      script: '|||satp-files'
      type: regular
      version: -1
    taskid: fc1d820f-6107-4dfc-89e5-aa32d30f6384
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 610\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: File
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: File
          operator: isNotEmpty
      label: 'yes'
    id: '5'
    nexttasks:
      'yes':
      - '7'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 4ef51de1-505b-4f76-8e8d-5350a18e0d7c
      iscommand: false
      name: Verify file context
      type: condition
      version: -1
    taskid: 4ef51de1-505b-4f76-8e8d-5350a18e0d7c
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 800\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: 707f4df7-107e-4030-81e5-b0b9032bce24
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 707f4df7-107e-4030-81e5-b0b9032bce24
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      end_time: {}
      limit: {}
      next: {}
      query: {}
      start_time: {}
    separatecontext: false
    task:
      brand: ''
      id: 0b18eb68-7e8c-4fbf-8ff4-752c44172a6b
      iscommand: true
      name: Get events
      script: '|||satp-events'
      type: regular
      version: -1
    taskid: 0b18eb68-7e8c-4fbf-8ff4-752c44172a6b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 990\n  }\n}"
  '8':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ATPEvents
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: ATPEvents
          operator: isNotEmpty
      label: 'yes'
    id: '8'
    nexttasks:
      'yes':
      - '9'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: b32fe96d-0ab6-4f8f-8235-b2cb32b5d3f6
      iscommand: false
      name: Verify file context
      type: condition
      version: -1
    taskid: b32fe96d-0ab6-4f8f-8235-b2cb32b5d3f6
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 1180\n  }\n}"
  '9':
    id: '9'
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      end_time: {}
      limit: {}
      next: {}
      query: {}
      start_time: {}
    separatecontext: false
    task:
      brand: ''
      id: bdcba0ae-873e-447e-8365-13e33665731a
      iscommand: true
      name: Get incidents
      script: '|||satp-incidents'
      type: regular
      version: -1
    taskid: bdcba0ae-873e-447e-8365-13e33665731a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 1390\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1945,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\":\
  \ -110\n    }\n  }\n}"
