id: C2sec-Test
inputs: []
name: C2sec-Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 1a1b1297-48f2-436b-8497-d7076cdae3e0
      iscommand: false
      name: ''
      version: -1
    taskid: 1a1b1297-48f2-436b-8497-d7076cdae3e0
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      domain:
        simple: demisto.com
      newscan:
        simple: 'true'
    separatecontext: false
    task:
      brand: ''
      id: 2085bafc-f0de-4ec6-84c8-71139aaa51d6
      iscommand: true
      name: Search Domain
      script: '|||irisk-add-domain'
      type: regular
      version: -1
    taskid: 2085bafc-f0de-4ec6-84c8-71139aaa51d6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    note: false
    scriptarguments:
      component:
        simple: credential
      domain:
        simple: demisto.com
    separatecontext: false
    task:
      brand: ''
      id: e892d3d9-e6ad-4a4e-8b4b-d9a00d95087d
      iscommand: true
      name: Get Scan results
      script: '|||irisk-get-scan-results'
      type: regular
      version: -1
    taskid: e892d3d9-e6ad-4a4e-8b4b-d9a00d95087d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      domain:
        simple: demisto.com
    separatecontext: false
    task:
      brand: ''
      id: a32fbdcc-d8b1-4bb9-80c7-000bef532332
      iscommand: true
      name: Get Domain Issues
      script: '|||irisk-get-domain-issues'
      type: regular
      version: -1
    taskid: a32fbdcc-d8b1-4bb9-80c7-000bef532332
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      id:
        simple: ${C2sec.Domain.Scan.workitemid}
    separatecontext: false
    task:
      brand: ''
      id: 3141efc1-8672-41fa-8163-ee730eaffaea
      iscommand: true
      name: Get WorkItem status
      script: '|||irisk-get-scan-status'
      type: regular
      version: -1
    taskid: 3141efc1-8672-41fa-8163-ee730eaffaea
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      domain:
        simple: demisto.com
    separatecontext: false
    task:
      brand: ''
      id: bd8f6e3d-9151-4622-8648-546366a1fa0b
      iscommand: true
      name: Rescan Domaun
      script: '|||irisk-rescan-domain'
      type: regular
      version: -1
    taskid: bd8f6e3d-9151-4622-8648-546366a1fa0b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: 3f4635c3-ebb1-46d9-83e0-1e7c38bf9f46
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 3f4635c3-ebb1-46d9-83e0-1e7c38bf9f46
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1115,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
