contentitemfields:
  propagationLabels: []
description: Test for Traps integration
id: Traps test
inputs: []
name: Traps test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '22'
    note: false
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: cd141148-ace4-4eb1-866d-e6a904a177d3
      iscommand: false
      name: ''
      version: -1
    taskid: cd141148-ace4-4eb1-866d-e6a904a177d3
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 50\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 575b27e1-0d5d-4fe0-803c-2432edb4c929
      iscommand: false
      name: 'Missing: Get events'
      type: title
      version: -1
    taskid: 575b27e1-0d5d-4fe0-803c-2432edb4c929
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 385\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '29'
    note: false
    scriptarguments:
      event_ids:
        simple: df4e60a62515482f98c8ef37e74363df,cfe4d15aca924bfcb7d2fc629b696bdd
      status:
        simple: investigating
    separatecontext: false
    skipunavailable: false
    task:
      brand: Traps
      description: Change the status of multiple events.
      id: 0474c8e7-3c72-454b-87e2-a474412e3cc9
      iscommand: true
      name: traps-event-bulk-update-status
      script: Traps|||traps-event-bulk-update-status
      type: regular
      version: -1
    taskid: 0474c8e7-3c72-454b-87e2-a474412e3cc9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 900\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '18'
    note: false
    scriptarguments:
      hash_ids:
        simple: 1111111111111111111111111111111111111111111111111111111111111111,0000000000000000000000000000000000000000000000000000000000000000
    separatecontext: false
    skipunavailable: false
    task:
      brand: Traps
      description: Get blacklist status of guven hashes.
      id: 20498bc5-61df-47b1-8f11-4b9dd2eb44e5
      iscommand: true
      name: traps-hashes-blacklist-status
      script: Traps|||traps-hashes-blacklist-status
      type: regular
      version: -1
    taskid: 20498bc5-61df-47b1-8f11-4b9dd2eb44e5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 370\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    scriptarguments:
      hash_id:
        simple: '1111111111111111111111111111111111111111111111111111111111111111'
    separatecontext: false
    skipunavailable: false
    task:
      brand: Traps
      description: Blacklist specified hash.
      id: c3a1ddb3-5ee7-44d6-8da8-f959643b44d6
      iscommand: true
      name: traps-hash-blacklist
      script: Traps|||traps-hash-blacklist
      type: regular
      version: -1
    taskid: c3a1ddb3-5ee7-44d6-8da8-f959643b44d6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 720\n  }\n}"
  '16':
    id: '16'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '19'
    note: false
    scriptarguments:
      hash_id:
        simple: '1111111111111111111111111111111111111111111111111111111111111111'
    separatecontext: false
    skipunavailable: false
    task:
      brand: Traps
      description: Remove a given hash from blacklist
      id: 5a206db7-092a-4e38-8d5e-65fc65a450ed
      iscommand: true
      name: traps-hash-blacklist-remove
      script: Traps|||traps-hash-blacklist-remove
      type: regular
      version: -1
    taskid: 5a206db7-092a-4e38-8d5e-65fc65a450ed
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 1070\n  }\n}"
  '17':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${Traps.File(val.SHA256 == '1111111111111111111111111111111111111111111111111111111111111111').BlacklistStatus}
          operator: containsGeneral
          right:
            value:
              simple: blacklisted
      label: 'yes'
    id: '17'
    ignoreworker: false
    nexttasks:
      'yes':
      - '16'
    note: false
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: cb1e029e-91c4-4c52-884e-8c45656f6b48
      iscommand: false
      name: Is blacklisted?
      type: condition
      version: -1
    taskid: cb1e029e-91c4-4c52-884e-8c45656f6b48
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 895\n  }\n}"
  '18':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Traps.File.SHA256
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: Traps.File.BlacklistStatus
          operator: isEqualString
          right:
            value:
              simple: none
        - left:
            iscontext: true
            value:
              simple: Traps.File.BlacklistStatus
          operator: isEqualString
          right:
            value:
              simple: blacklisted
      - - left:
            iscontext: true
            value:
              complex:
                accessor: File
                root: Traps
          operator: hasLength
          right:
            value:
              simple: '2'
      label: 'yes'
    id: '18'
    ignoreworker: false
    nexttasks:
      'yes':
      - '15'
    note: false
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 84df4f18-36b8-4c9c-84f9-1404045d7c3e
      iscommand: false
      name: Verify context
      type: condition
      version: -1
    taskid: 84df4f18-36b8-4c9c-84f9-1404045d7c3e
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 545\n  }\n}"
  '19':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${Traps.File(val.SHA256 == '1111111111111111111111111111111111111111111111111111111111111111').BlacklistStatus}
          operator: containsGeneral
          right:
            value:
              simple: none
      label: 'yes'
    id: '19'
    ignoreworker: false
    nexttasks:
      'yes':
      - '25'
    note: false
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: b4e6db43-ccc9-4825-88a6-c34e80372d3d
      iscommand: false
      name: Is not blacklisted?
      type: condition
      version: -1
    taskid: b4e6db43-ccc9-4825-88a6-c34e80372d3d
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 1245\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '30'
    note: false
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: e3ebee45-4797-4a54-84df-c243015d50ef
      iscommand: false
      name: 'Missing: get all endpoints'
      type: title
      version: -1
    taskid: e3ebee45-4797-4a54-84df-c243015d50ef
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 385\n  }\n}"
  '22':
    id: '22'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
      - '10'
      - '14'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: 82eabbf7-5a06-484b-8f9a-10f18a96f693
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 82eabbf7-5a06-484b-8f9a-10f18a96f693
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 195\n  }\n}"
  '25':
    id: '25'
    ignoreworker: false
    note: false
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 04c5f9f8-a53d-46df-87ea-886bc46f5d0d
      iscommand: false
      name: DONE!
      type: title
      version: -1
    taskid: 04c5f9f8-a53d-46df-87ea-886bc46f5d0d
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 910,\n    \"y\": 1425\n  }\n}"
  '26':
    id: '26'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - '25'
    note: false
    scriptarguments:
      endpoint_id:
        simple: d3339851f18f470182bf2bf98ad5db4b
      event_id:
        simple: 1cfb8fac7b504dc9894eabb9eb33de73
      file_name:
        simple: C:\Program Files (x86)\Notepad++\notepad++.exe
    separatecontext: true
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 0def5ef4-3b16-452b-8eb9-16ac3894e6ff
      iscommand: false
      name: Traps Retrieve And Download Files
      playbookName: Traps Retrieve And Download Files
      type: playbook
      version: -1
    taskid: 0def5ef4-3b16-452b-8eb9-16ac3894e6ff
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 20,\n    \"y\": 720\n  }\n}"
  '27':
    id: '27'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - '25'
    note: false
    scriptarguments:
      endpoint_id:
        simple: d3339851f18f470182bf2bf98ad5db4b
    separatecontext: true
    skipunavailable: false
    task:
      brand: ''
      description: Use this playbook to initiate an endpoint scan and retrieve the
        scan results.
      id: 2fbd4929-4ac4-4aac-853d-db5d8e2d6d12
      iscommand: false
      name: Traps Scan Endpoint
      playbookName: Traps Scan Endpoint
      type: playbook
      version: -1
    taskid: 2fbd4929-4ac4-4aac-853d-db5d8e2d6d12
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 500,\n    \"y\": 1165\n  }\n}"
  '28':
    id: '28'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      comment: {}
      event_id:
        simple: 53edb3fa9a3b4b83bcf168390a2ec08d
      status:
        simple: new
    separatecontext: false
    skipunavailable: false
    task:
      brand: Traps
      description: Change status and add a comment to an existing event.
      id: fd8d033e-bc01-400d-884d-0f539314c274
      iscommand: true
      name: traps-event-update (revert)
      script: Traps|||traps-event-update
      type: regular
      version: -1
    taskid: fd8d033e-bc01-400d-884d-0f539314c274
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 720\n  }\n}"
  '29':
    id: '29'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '25'
    note: false
    scriptarguments:
      event_ids:
        simple: df4e60a62515482f98c8ef37e74363df,cfe4d15aca924bfcb7d2fc629b696bdd
      status:
        simple: new
    separatecontext: false
    skipunavailable: false
    task:
      brand: Traps
      description: Change the status of multiple events.
      id: 04d7e58f-c517-4689-8f4b-fd2b8a33446e
      iscommand: true
      name: traps-event-bulk-update-status (revert)
      script: Traps|||traps-event-bulk-update-status
      type: regular
      version: -1
    taskid: 04d7e58f-c517-4689-8f4b-fd2b8a33446e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 1075\n  }\n}"
  '30':
    continueonerror: true
    id: '30'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '31'
      - '26'
    note: false
    scriptarguments:
      endpoint_id:
        simple: d3339851f18f470182bf2bf98ad5db4b
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Returns details for the specified endpoint.
      id: bbe837b7-5c91-44e1-8850-e63dd5927e9c
      iscommand: true
      name: traps-get-endpoint-by-id
      script: '|||traps-get-endpoint-by-id'
      type: regular
      version: -1
    taskid: bbe837b7-5c91-44e1-8850-e63dd5927e9c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 320,\n    \"y\": 530\n  }\n}"
  '31':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Endpoint.ScanStatus
                root: Traps
          operator: notInList
          right:
            value:
              simple: pending, in_progress
      label: 'yes'
    id: '31'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '25'
      'yes':
      - '27'
    note: false
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: fe1156ed-fb93-4ed6-869b-31a8ed503f3d
      iscommand: false
      name: Check if Scan status is not pending or in_progress
      type: condition
      version: -1
    taskid: fe1156ed-fb93-4ed6-869b-31a8ed503f3d
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 440,\n    \"y\": 860\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '28'
    note: false
    scriptarguments:
      comment: {}
      event_id:
        simple: 53edb3fa9a3b4b83bcf168390a2ec08d
      status:
        simple: investigating
    separatecontext: false
    skipunavailable: false
    task:
      brand: Traps
      description: Change status and add a comment to an existing event.
      id: dc8f10c1-851e-44dd-8fa6-ca488b3b90d6
      iscommand: true
      name: traps-event-update
      script: Traps|||traps-event-update
      type: regular
      version: -1
    taskid: dc8f10c1-851e-44dd-8fa6-ca488b3b90d6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1340,\n    \"y\": 545\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1440,\n      \"width\": 1700,\n      \"x\": 20,\n      \"y\":\
  \ 50\n    }\n  }\n}"
