id: TestDedupIncidentsPlaybook
inputs: []
name: TestDedupIncidentsPlaybook
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: e3c5db64-4c12-4cfa-8b7e-7bd202b74a37
      iscommand: false
      name: ''
      version: -1
    taskid: e3c5db64-4c12-4cfa-8b7e-7bd202b74a37
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      1longtexttest: {}
      aaaa: {}
      addLabels:
        simple: '[{"Email/subject":"This is a subject"},{"Email/from":"test@demisto.com"}]'
      amarkdownsection: {}
      anothernumberpleasejusttomakesure: {}
      app: {}
      arcsightcaseid: {}
      assetid: {}
      attach: {}
      attachamenthash: {}
      attachmentcount: {}
      attachmentextension: {}
      attachmenthash: {}
      attachmentid: {}
      attachmentitem: {}
      attachmentname: {}
      attachmentsize: {}
      attachmenttype: {}
      backupowner: {}
      bbb: {}
      blah: {}
      bool1: {}
      bool2: {}
      booleansummary: {}
      boolfield: {}
      booltest: {}
      bugtraq: {}
      ccc: {}
      ccipaddress: {}
      compliance: {}
      constvalue: {}
      customFields: {}
      customfield: {}
      cve: {}
      cvss: {}
      daysbetweenreportcreation: {}
      deleteEmptyField: {}
      department: {}
      departmentadmin: {}
      dest: {}
      destntdomain: {}
      details:
        simple: fdslkjflks sldkfj lsdfklsd flsdkfj sldkfjlsdfj lskdfj lsd flksd fsdlkfj
          sdlfj slkdfj lsdkfjlsdf sdlkfjsldfj sldkfj sldf sdlkfjsldfjslkdf sldkfjlsdkfj
          lsdfjlksdf jlsdfj lsdkfj dlskf jldskfjdskldlskf jsdlkfjsd lfskdf
      duration: {}
      emailbcc: {}
      emailbody: {}
      emailbodyformat: {}
      emailbodyhtml: {}
      emailcc: {}
      emailclientname: {}
      emailfrom: {}
      emailinreplyto: {}
      emailkeywords: {}
      emailmessageid: {}
      emailreceived: {}
      emailreplyto: {}
      emailreturnpath: {}
      emailsenderip: {}
      emailsize: {}
      emailsource: {}
      emailsubject: {}
      emailto: {}
      emailtocount: {}
      emailurlclicked: {}
      escalationdate: {}
      eventid: {}
      falses: {}
      fetchid: {}
      fetchtype: {}
      field1: {}
      field2: {}
      field3: {}
      field4: {}
      filehash: {}
      filename: {}
      filepath: {}
      hjhj: {}
      host: {}
      htmltypefield: {}
      id: {}
      important: {}
      importantfield: {}
      itaytestfield: {}
      labels: {}
      longtextone: {}
      longtexttoo: {}
      mailbody: {}
      malwarefamily: {}
      multilinetext: {}
      name: {}
      newmarkdownfield: {}
      newtextfield: {}
      numberplease: {}
      occurred: {}
      one: {}
      owner: {}
      phase: {}
      relatedincidentssummary: {}
      replacePlaybook: {}
      reporteduser: {}
      roles: {}
      screenshot: {}
      screenshot2: {}
      selector: {}
      severity: {}
      signature: {}
      single: {}
      single2: {}
      sla: {}
      slaField: {}
      source: {}
      sourceip: {}
      sourceip1: {}
      src: {}
      srcntdomain: {}
      srcuser: {}
      subcat: {}
      subcategory: {}
      systems: {}
      team: {}
      test: {}
      test111: {}
      test2: {}
      testfield: {}
      testhtml: {}
      timeassignedtolevel2: {}
      timefield1: {}
      timelevel1: {}
      tldr: {}
      tttttt: {}
      type: {}
      user: {}
      username: {}
      vendorid: {}
      vendorproduct: {}
      vulnerabilitycategory: {}
    separatecontext: false
    task:
      brand: Builtin
      id: 3610001c-691f-468c-81cd-823925579179
      iscommand: true
      name: Add labels
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 3610001c-691f-468c-81cd-823925579179
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '11':
    id: '11'
    nexttasks:
      '#none#':
      - '17'
    note: false
    scriptarguments:
      filterQuery: {}
      hoursBack: {}
      ignoreClosedIncidents: {}
      incidentFieldsAppliedCondition: {}
      maxNumberOfIncidents: {}
      maxResults: {}
      similarContextKeys: {}
      similarCustomFields: {}
      similarIncidentFields: {}
      similarIncidentKeys:
        simple: name
      similarLabelsKeys: {}
      skipMissingValues: {}
      timeField:
        simple: occurred
    separatecontext: false
    task:
      brand: ''
      id: 02406255-50d6-4081-8aab-a6cd322b56ac
      iscommand: false
      name: FindSimilarIncidents
      scriptName: FindSimilarIncidents
      type: regular
      version: -1
    taskid: 02406255-50d6-4081-8aab-a6cd322b56ac
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '12':
    id: '12'
    nexttasks:
      '#none#':
      - '13'
    note: false
    scriptarguments:
      incidentId:
        simple: ${similarIncident.rawId}
      name:
        simple: TestDedupIncidentsByName
    separatecontext: false
    task:
      brand: Builtin
      id: 75cff374-ae9b-4ab3-8887-764d4f9ff34f
      iscommand: true
      name: set dedup playbook to the similar incident
      script: Builtin|||setPlaybook
      type: regular
      version: -1
    taskid: 75cff374-ae9b-4ab3-8887-764d4f9ff34f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '13':
    id: '13'
    nexttasks:
      '#none#':
      - '15'
    note: false
    scriptarguments:
      seconds:
        simple: '5'
    separatecontext: false
    task:
      brand: ''
      id: b6475090-5acd-4f0d-8aff-b0e09e0f4998
      iscommand: false
      name: Wait so the playbook of the similar incident get executed and close
      scriptName: Sleep
      type: regular
      version: -1
    taskid: b6475090-5acd-4f0d-8aff-b0e09e0f4998
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '14':
    id: '14'
    nexttasks:
      '#none#':
      - '16'
    note: false
    scriptarguments:
      filterQuery: {}
      hoursBack: {}
      ignoreClosedIncidents: {}
      incidentFieldsAppliedCondition: {}
      maxNumberOfIncidents: {}
      maxResults: {}
      similarContextKeys: {}
      similarCustomFields: {}
      similarIncidentFields: {}
      similarIncidentKeys:
        simple: name
      similarLabelsKeys: {}
      skipMissingValues: {}
      timeField: {}
    separatecontext: false
    task:
      brand: ''
      id: 8c8f4b9a-3bae-4963-8956-1f742887e7aa
      iscommand: false
      name: FindSimilarIncidents
      scriptName: FindSimilarIncidents
      type: regular
      version: -1
    taskid: 8c8f4b9a-3bae-4963-8956-1f742887e7aa
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '15':
    id: '15'
    nexttasks:
      '#none#':
      - '14'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: 91d03c01-34fe-4b8c-88e2-3014b90fedc2
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 91d03c01-34fe-4b8c-88e2-3014b90fedc2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
  '16':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: isSimilarIncidentFound
          operator: isFalse
      label: 'yes'
    id: '16'
    nexttasks:
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 7c35460b-47d2-4359-8ac8-c6bc27d3dcb5
      iscommand: false
      name: Ensure there are no similar incident, similar incidents should be closed
        (dedup)
      type: condition
      version: -1
    taskid: 7c35460b-47d2-4359-8ac8-c6bc27d3dcb5
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1945\n  }\n}"
  '17':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: isSimilarIncidentFound
          operator: isTrue
      label: 'yes'
    id: '17'
    nexttasks:
      'yes':
      - '12'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 9aa41975-86fa-49a4-86cf-98fa148bb7e3
      iscommand: false
      name: make sure we found similar incident
      type: condition
      version: -1
    taskid: 9aa41975-86fa-49a4-86cf-98fa148bb7e3
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '18':
    id: '18'
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      seconds:
        simple: '4'
    separatecontext: false
    task:
      brand: ''
      id: 25f40783-e095-4e0f-867f-04a7bc262cdd
      iscommand: false
      name: Wait till the incident will be created
      scriptName: Sleep
      type: regular
      version: -1
    taskid: 25f40783-e095-4e0f-867f-04a7bc262cdd
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '18'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: b703c012-dea4-43ca-8fef-530330d2bde1
      iscommand: false
      name: Create duplicate incident
      scriptName: CreateDuplicateIncident
      type: regular
      version: -1
    taskid: b703c012-dea4-43ca-8fef-530330d2bde1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: fce3305c-93e9-44d8-882a-addcd377544d
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: fce3305c-93e9-44d8-882a-addcd377544d
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2120\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      id: d8e9b5aa-4d75-495f-8a41-a93cb5c51ad1
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: d8e9b5aa-4d75-495f-8a41-a93cb5c51ad1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2135,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
