description: Test ExifRead Script
id: ExifReadTest
inputs: []
name: ExifReadTest
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '2'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 68de2c2c-6c0d-4167-83e7-20d0bc09f48a
      iscommand: false
      name: ''
      version: -1
    taskid: 68de2c2c-6c0d-4167-83e7-20d0bc09f48a
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 250330ca-f4af-42b2-8184-e905b8ec493c
      iscommand: false
      name: Generate File
      scriptName: GenerateImageFileEntry
      type: regular
      version: -1
    taskid: 250330ca-f4af-42b2-8184-e905b8ec493c
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: 858d11de-d159-4b08-880d-dc93f68bdcd6
      iscommand: false
      name: Clear Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 858d11de-d159-4b08-880d-dc93f68bdcd6
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      EntryID:
        simple: ${File.EntryID}
    separatecontext: false
    task:
      brand: ''
      id: 6f02712f-5ac5-4e50-85e4-04d9ca5cc9fe
      iscommand: false
      name: ExifRead
      scriptName: ExifRead
      type: regular
      version: -1
    taskid: 6f02712f-5ac5-4e50-85e4-04d9ca5cc9fe
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: value
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: Exif.tag
                    operator: isEqualString
                    right:
                      value:
                        simple: EXIF ColorSpace
                root: Exif
          operator: isEqualString
          right:
            value:
              simple: sRGB
      label: 'yes'
    id: '4'
    nexttasks:
      'yes':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 8e09b6e9-7b71-4696-8425-2ca7c1d2e6a9
      iscommand: false
      name: Check exif
      type: condition
      version: -1
    taskid: 8e09b6e9-7b71-4696-8425-2ca7c1d2e6a9
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    note: false
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      id: {}
    separatecontext: false
    task:
      brand: Builtin
      id: 27764f12-bf79-4f42-85ee-b775ac78439e
      iscommand: true
      name: Close
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 27764f12-bf79-4f42-85ee-b775ac78439e
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 940,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
