args: []
comment: The settings information includes S-series sensor and X-series configurations
  input by the administrator
commonfields:
  id: VectraSettings
  version: -1
dependson:
  must:
  - vec-settings
deprecated: true
name: VectraSettings
script: "\nresp = demisto.executeCommand(\"vec-settings\", demisto.args())\n\nif isError(resp[0]):\n\
  \    demisto.results(resp)\nelse:\n    data = demisto.get(resp[0], \"Contents.results\"\
  )\n    if data:\n        data = data if isinstance(data, list) else [data]\n   \
  \     data = [{k: formatCell(row[k]) for k in row} for row in data]\n        demisto.results({\"\
  ContentsFormat\": formats[\"table\"], \"Type\": entryTypes[\"note\"], \"Contents\"\
  : data} )\n    else:\n        demisto.results(\"No results.\")\n"
scripttarget: 0
subtype: python2
system: true
tags:
- Vectra
timeout: 0s
toversion: 4.1.9
type: python
