id: Test-BPA
inputs: []
name: Test-BPA
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 06afda6f-3011-4b7d-81cd-d7d68376ef74
      iscommand: false
      name: ''
      version: -1
    taskid: 06afda6f-3011-4b7d-81cd-d7d68376ef74
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: 7c822901-b728-43ea-87a5-20d0a5712cec
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 7c822901-b728-43ea-87a5-20d0a5712cec
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep:
        simple: PAN-OS-BPA.SubmittedJob.JobID
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: 9f72939b-1058-45b6-88b1-6cc21b0bfa04
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 9f72939b-1058-45b6-88b1-6cc21b0bfa04
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    quietmode: 0
    scriptarguments:
      exclude_passed_checks:
        simple: 'true'
      task_id:
        simple: ${PAN-OS-BPA.SubmittedJob.JobID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: BPA
      description: Returns results of BPA job.
      id: ec9101b0-65a8-49be-8794-304ab19e17f0
      iscommand: true
      name: pan-os-bpa-get-job-results
      script: BPA|||pan-os-bpa-get-job-results
      type: regular
      version: -1
    taskid: ec9101b0-65a8-49be-8794-304ab19e17f0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '12':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: JobResults.Checks
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: PAN-OS-BPA.JobResults.Checks.check_passed
                    operator: isTrue
                root: PAN-OS-BPA
          operator: isEmpty
      label: 'yes'
    id: '12'
    ignoreworker: false
    nexttasks:
      'yes':
      - '7'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 1a12b604-293a-4fdf-8b0b-1cf8e7b0d2a7
      iscommand: false
      name: Test BPA Checks Are Returned
      type: condition
      version: -1
    taskid: 1a12b604-293a-4fdf-8b0b-1cf8e7b0d2a7
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      generate_zip_bundle:
        simple: 'true'
    separatecontext: false
    skipunavailable: false
    task:
      brand: BPA
      description: Submits a BPA job.
      id: 1523fbb5-8f28-49f0-8562-ec01e9e8a2c4
      iscommand: true
      name: pan-os-bpa-submit-job
      script: BPA|||pan-os-bpa-submit-job
      type: regular
      version: -1
    taskid: 1523fbb5-8f28-49f0-8562-ec01e9e8a2c4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - '9'
    note: false
    quietmode: 0
    scriptarguments:
      AdditionalPollingCommandArgNames: {}
      AdditionalPollingCommandArgValues: {}
      Ids:
        simple: ${PAN-OS-BPA.SubmittedJob.JobID}
      Interval:
        simple: '1'
      PollingCommandArgName:
        simple: task_id
      PollingCommandName:
        simple: pan-os-bpa-get-job-results
      Timeout:
        simple: '10'
      dt:
        simple: PAN-OS-BPA.JobResults(val.Status!='complete').JobID
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: 'Use this playbook as a sub-playbook to block execution of the
        master playbook until a remote action is complete.

        This playbook implements polling by continuously running the command in Step
        \#2 until the operation completes.

        The remote action should have the following structure:


        1. Initiate the operation.

        2. Poll to check if the operation completed.

        3. (optional) Get the results of the operation.'
      id: 25a4742a-99e5-457d-87fb-9c3bd103cc36
      iscommand: false
      name: GenericPolling
      playbookName: GenericPolling
      type: playbook
      version: -1
    taskid: 25a4742a-99e5-457d-87fb-9c3bd103cc36
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${PAN-OS-BPA.JobResults(val.Status==='complete').Checks}
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Name
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: InfoFile
                    operator: isNotEmpty
                root: InfoFile
          operator: containsString
          right:
            value:
              simple: report
      label: 'yes'
    id: '5'
    ignoreworker: false
    nexttasks:
      'yes':
      - '10'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 9bc78e2e-5722-4e96-8a5a-1f503d1dd7a2
      iscommand: false
      name: Test BPA Checks Are Returned
      type: condition
      version: -1
    taskid: 9bc78e2e-5722-4e96-8a5a-1f503d1dd7a2
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      emailclassification: {}
      id:
        simple: ${incident.id}
      phishingsubtype: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the current incident
      id: 86268dac-3b75-4713-8a92-13672c5a90d0
      iscommand: true
      name: closeInvestigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 86268dac-3b75-4713-8a92-13672c5a90d0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: BPA
      description: Get documentaion
      id: 0642547e-3930-45ed-8c6c-04f10290e6b1
      iscommand: true
      name: pan-os-get-documentation
      script: BPA|||pan-os-get-documentation
      type: regular
      version: -1
    taskid: 0642547e-3930-45ed-8c6c-04f10290e6b1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      task_id:
        simple: ${PAN-OS-BPA.SubmittedJob.JobID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: BPA
      description: Returns results of BPA job.
      id: 9da2cd68-133e-4adc-8526-e5b7cb3ef2ef
      iscommand: true
      name: pan-os-bpa-get-job-results
      script: BPA|||pan-os-bpa-get-job-results
      type: regular
      version: -1
    taskid: 9da2cd68-133e-4adc-8526-e5b7cb3ef2ef
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
toversion: 4.1.9
version: 8
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1815,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
