id: Google Vision API - Test
inputs: []
name: Google Vision API - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 83d6c75b-dc5b-4019-8b9e-42fa0e2975f3
      iscommand: false
      name: ''
      version: -1
    taskid: 83d6c75b-dc5b-4019-8b9e-42fa0e2975f3
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: b02f139d-7d40-40b9-89b3-05d49635e772
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: b02f139d-7d40-40b9-89b3-05d49635e772
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '32'
    note: false
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy:
        simple: 'true'
      saveAsFile:
        simple: 'yes'
      unsecure: {}
      url:
        simple: https://raw.githubusercontent.com/demisto/content/master/TestData/test_image.png
      username: {}
    separatecontext: false
    task:
      brand: ''
      description: Sends http request. Returns the response as json.
      id: b179ff85-89b9-4ff3-8545-d491ab4fb892
      iscommand: false
      name: Get test image
      scriptName: http
      type: regular
      version: -1
    taskid: b179ff85-89b9-4ff3-8545-d491ab4fb892
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Logo.[0].Description
                root: GoogleVisionAPI
                transformers:
                - operator: toLowerCase
          operator: containsString
          right:
            value:
              simple: microsoft
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '33'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 933f1776-d906-4de9-8feb-59e568fabb4c
      iscommand: false
      name: Verify query worked as planned
      type: condition
      version: -1
    taskid: 933f1776-d906-4de9-8feb-59e568fabb4c
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '32':
    id: '32'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      entry_id:
        simple: ${File.EntryID}
    separatecontext: false
    task:
      brand: ''
      id: 1df5277c-3567-4112-8813-fd2a7ec389ee
      iscommand: true
      name: Detect logos
      script: '|||google-vision-detect-logos'
      type: regular
      version: -1
    taskid: 1df5277c-3567-4112-8813-fd2a7ec389ee
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '33':
    id: '33'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      id:
        simple: ${incident.id}
      ticket: {}
    separatecontext: false
    task:
      brand: Builtin
      id: f5780469-d422-4e36-8870-17b726daf3e7
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: f5780469-d422-4e36-8870-17b726daf3e7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 08e7933d-8379-40f0-8e58-834ca4521324
      iscommand: false
      name: Success
      type: title
      version: -1
    taskid: 08e7933d-8379-40f0-8e58-834ca4521324
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1085,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
