description: ''
id: Devo test
inputs: []
name: Devo test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 72407b54-6e6d-4537-89b6-683d085faa74
      iscommand: false
      name: ''
      version: -1
    taskid: 72407b54-6e6d-4537-89b6-683d085faa74
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 49ff8dcb-6146-4d93-8da4-2130fed54621
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 49ff8dcb-6146-4d93-8da4-2130fed54621
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      from:
        simple: '2019-10-14T08:00:00Z'
      limit:
        simple: '5'
      query:
        simple: from demo.ecommerce.data select * where method="GET"
      queryId: {}
      skip: {}
      to:
        simple: '2019-10-14T08:30:00Z'
      writeToContext: {}
    separatecontext: false
    task:
      brand: Devo
      description: Perform a query.
      id: ea898dd8-691d-4f38-81f0-3c0583dd8fcc
      iscommand: true
      name: Select query
      script: Devo|||devo-query
      type: regular
      version: -1
    taskid: ea898dd8-691d-4f38-81f0-3c0583dd8fcc
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      from:
        simple: '2018-10-07T08:00:00Z'
      limit: {}
      query: {}
      queryId:
        simple: a7561571-c786-4fb7-93d0-e2f2c74c190d
      skip: {}
      to: {}
      writeToContext: {}
    separatecontext: false
    task:
      brand: Devo
      description: Perform a query.
      id: 65441542-2bc1-429a-83a8-de9e868b6da7
      iscommand: true
      name: Query by Id
      script: Devo|||devo-query
      type: regular
      version: -1
    taskid: 65441542-2bc1-429a-83a8-de9e868b6da7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      expectedValue: {}
      fields:
        simple: Results
      path:
        simple: Devo
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 74616a07-709a-4bc5-8178-8d761168b78f
      iscommand: false
      name: Verify Results
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 74616a07-709a-4bc5-8178-8d761168b78f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: a65cff6d-d386-4202-8718-ce304ed5b6de
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: a65cff6d-d386-4202-8718-ce304ed5b6de
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    note: false
    scriptarguments:
      expectedValue: {}
      fields:
        simple: Results
      path:
        simple: Devo
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 32222117-e7d0-43b4-812b-a90e79811dce
      iscommand: false
      name: Verify Results
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 32222117-e7d0-43b4-812b-a90e79811dce
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1115,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
