id: Forescout-Test
inputs: []
name: Forescout-Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: e7282b89-73a7-47a2-801e-5c453d2f20c3
      iscommand: false
      name: ''
      version: -1
    taskid: e7282b89-73a7-47a2-801e-5c453d2f20c3
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 8fc6b0c3-dc06-4000-813e-8ec188d69a95
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 8fc6b0c3-dc06-4000-813e-8ec188d69a95
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      field:
        simple: fsapi_DemistoTest
      fields_json: {}
      host_ip:
        simple: 192.168.1.212
      update_type:
        simple: update
      value:
        simple: billie jean is not my girl
    separatecontext: false
    task:
      brand: Forescout
      description: Update a host's field. Note that if a List field or Composite field
        has not been defined in Forescout to 'Aggregate new values from each update'
        that performing an update operation on a field will overwrite previous data
        written to that field.
      id: 8241630b-a6d1-4570-82fe-fd2adb0e1ebe
      iscommand: true
      name: forescout-update-host-fields
      script: Forescout|||forescout-update-host-fields
      type: regular
      version: -1
    taskid: 8241630b-a6d1-4570-82fe-fd2adb0e1ebe
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      fields:
        simple: fsapi_DemistoTest
      id: {}
      identifier:
        simple: ip=192.168.1.212
      ip:
        simple: 192.168.1.212
      mac: {}
    separatecontext: false
    task:
      brand: ''
      description: Retrieve specified host property values for an endpoint.
      id: e99e9bcb-95a7-47dd-89ec-6afaea7b6f78
      iscommand: true
      name: forescout-get-host Get Updated Host
      script: '|||forescout-get-host'
      type: regular
      version: -1
    taskid: e99e9bcb-95a7-47dd-89ec-6afaea7b6f78
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1945\n  }\n}"
  '12':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Host.fsapi_DemistoTest
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: Forescout.Host.IPAddress
                    operator: isEqualString
                    right:
                      value:
                        simple: 192.168.1.212
                root: Forescout
          operator: isEqualString
          right:
            value:
              simple: billie jean is not my girl
      label: 'yes'
    id: '12'
    ignoreworker: false
    nexttasks:
      'yes':
      - '13'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: fe2027f1-4df4-46dc-8802-68c613ee2e06
      iscommand: false
      name: Verify `forescout-update-host-fields` executed properly
      type: condition
      version: -1
    taskid: fe2027f1-4df4-46dc-8802-68c613ee2e06
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2120\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    scriptarguments:
      field:
        simple: fsapi_DemistoTest
      fields_json: {}
      host_ip:
        simple: 192.168.1.212
      update_type:
        simple: delete
      value: {}
    separatecontext: false
    task:
      brand: Forescout
      description: Update a host's field. Note that if a List field or Composite field
        has not been defined in Forescout to 'Aggregate new values from each update'
        that performing an update operation on a field will overwrite previous data
        written to that field.
      id: 93bbaa4e-28a6-4316-81d6-915d6dfc7cd8
      iscommand: true
      name: forescout-update-host-properties Delete Previously Updated Property
      script: Forescout|||forescout-update-host-fields
      type: regular
      version: -1
    taskid: 93bbaa4e-28a6-4316-81d6-915d6dfc7cd8
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2295\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '15'
    note: false
    scriptarguments:
      list_names:
        simple: disallowed_names
      lists:
        simple: disallowed_names=Ignatius Quaternello,Dominic Venetzi,Pietro Fulmineschi
      update_type:
        simple: add_list_values
      values:
        simple: Ignatius Quaternello,Dominic Venetzi,Pietro Fulmineschi
    separatecontext: false
    task:
      brand: Forescout
      description: Update Forescout lists.
      id: c5afad15-4a32-40a1-80a0-cbab5c09c55f
      iscommand: true
      name: forescout-update-lists Add List Values
      script: Forescout|||forescout-update-lists
      type: regular
      version: -1
    taskid: c5afad15-4a32-40a1-80a0-cbab5c09c55f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2470\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    scriptarguments:
      list_names:
        simple: disallowed_names
      lists:
        simple: disallowed_names
      update_type:
        simple: delete_all_list_values
      values: {}
    separatecontext: false
    task:
      brand: Forescout
      description: Update Forescout lists.
      id: 18b8c793-d354-448a-838e-9533560066f5
      iscommand: true
      name: forescout-update-lists Delete List Values (Cleanup)
      script: Forescout|||forescout-update-lists
      type: regular
      version: -1
    taskid: 18b8c793-d354-448a-838e-9533560066f5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2645\n  }\n}"
  '16':
    id: '16'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 3e64bdf7-f264-4b15-8ce9-3fdc59bdcf85
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 3e64bdf7-f264-4b15-8ce9-3fdc59bdcf85
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2820\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      case_sensitive: {}
      host_field_type: {}
      match_exactly: {}
      search_in: {}
      search_term:
        simple: demisto
    separatecontext: false
    task:
      brand: Forescout
      description: Retrieve an index of Forescout host fields that match the specified
        criteria.
      id: 4861b6a6-cd22-40fb-8432-74694d971181
      iscommand: true
      name: forescout-get-hostfields
      script: Forescout|||forescout-get-host-fields
      type: regular
      version: -1
    taskid: 4861b6a6-cd22-40fb-8432-74694d971181
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: HostField
                root: Forescout
                transformers:
                - args:
                    equalTo:
                      value:
                        simple: demisto_prop
                    field:
                      value:
                        simple: Label
                    getField: {}
                  operator: WhereFieldEquals
          operator: isExists
      label: 'yes'
    id: '3'
    ignoreworker: false
    nexttasks:
      'yes':
      - '4'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 00b26965-ecfa-43d7-8a14-e84a8421a349
      iscommand: false
      name: Verify that 'demisto_prop' was returned by `forescout-get-hostfields`
      type: condition
      version: -1
    taskid: 00b26965-ecfa-43d7-8a14-e84a8421a349
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: Forescout
      description: 'Retrieves a list of all policies defined in the Forescout platform
        and

        their sub-rules.'
      id: c695d5df-5137-4e2c-807e-b27db5064508
      iscommand: true
      name: forescout-get-policies
      script: Forescout|||forescout-get-policies
      type: regular
      version: -1
    taskid: c695d5df-5137-4e2c-807e-b27db5064508
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            value:
              simple: '2101168655015691125'
          operator: in
          right:
            iscontext: true
            value:
              complex:
                accessor: Policy.ID
                root: Forescout
      label: 'yes'
    id: '5'
    ignoreworker: false
    nexttasks:
      'yes':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: a6a02050-fd0f-48dc-89bf-e01fb571eaed
      iscommand: false
      name: Verify Policies Returned
      type: condition
      version: -1
    taskid: a6a02050-fd0f-48dc-89bf-e01fb571eaed
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      properties: {}
      rule_ids:
        simple: '2101168655015691125'
    separatecontext: false
    task:
      brand: Forescout
      description: Retrieve a list of active endpoints.
      id: cc6de8fe-ecd4-4d67-894b-c18ce2777819
      iscommand: true
      name: forescout-get-hosts
      script: Forescout|||forescout-get-hosts
      type: regular
      version: -1
    taskid: cc6de8fe-ecd4-4d67-894b-c18ce2777819
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '7':
    conditions:
    - condition:
      - - left:
            value:
              simple: 192.168.1.212
          operator: in
          right:
            iscontext: true
            value:
              complex:
                accessor: Host.IPAddress
                root: Forescout
      label: 'yes'
    id: '7'
    ignoreworker: false
    nexttasks:
      'yes':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 28c5cad2-3c4b-4d7c-88a8-57f802fa470f
      iscommand: false
      name: Verify Expected Host is Returned by `forescout-get-hosts` command with
        filter
      type: condition
      version: -1
    taskid: 28c5cad2-3c4b-4d7c-88a8-57f802fa470f
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      fields: {}
      id: {}
      identifier:
        simple: ip=192.168.1.212
      ip:
        simple: 192.168.1.212
      mac: {}
    separatecontext: false
    task:
      brand: Forescout
      description: Retrieve specified host property values for an endpoint.
      id: b76316c9-c097-4430-819f-327c5e92926b
      iscommand: true
      name: forescout-get-host
      script: Forescout|||forescout-get-host
      type: regular
      version: -1
    taskid: b76316c9-c097-4430-819f-327c5e92926b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '9':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Host.OSClassification
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: Forescout.Host.IPAddress
                    operator: isEqualString
                    right:
                      value:
                        simple: 192.168.1.212
                root: Forescout
          operator: isEqualString
          right:
            value:
              simple: Linux
      label: 'yes'
    id: '9'
    ignoreworker: false
    nexttasks:
      'yes':
      - '10'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 7486e2d0-c83d-4bda-8514-3040a8bb94fb
      iscommand: false
      name: Verify `forescout-get-host` returned expected field
      type: condition
      version: -1
    taskid: 7486e2d0-c83d-4bda-8514-3040a8bb94fb
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2835,\n      \"width\": 380,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
