id: RedCanaryTest
inputs: []
name: RedCanaryTest
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 84663d49-6b0a-4045-86ac-b2e95609f379
      iscommand: false
      name: ''
      version: -1
    taskid: 84663d49-6b0a-4045-86ac-b2e95609f379
    type: start
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: e2cdcf98-7063-4f06-83ae-944ec284022e
      iscommand: false
      name: Start Fresh
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: e2cdcf98-7063-4f06-83ae-944ec284022e
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      id:
        simple: '2'
    separatecontext: false
    task:
      brand: RedCanary
      id: 32479535-4ee6-4e48-82d2-bfcd5fd7b2ff
      iscommand: true
      name: Get specific detection
      script: RedCanary|||redcanary-get-detection
      type: regular
      version: -1
    taskid: 32479535-4ee6-4e48-82d2-bfcd5fd7b2ff
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1595\n  }\n}"
  '11':
    id: '11'
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      id:
        simple: ${Endpoint.ID}
    separatecontext: false
    task:
      brand: RedCanary
      id: 77726f63-9154-468b-8fad-1d694727a5f4
      iscommand: true
      name: Get endpoint detections
      script: RedCanary|||redcanary-get-endpoint-detections
      type: regular
      version: -1
    taskid: 77726f63-9154-468b-8fad-1d694727a5f4
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1770\n  }\n}"
  '12':
    id: '12'
    note: false
    scriptarguments:
      id:
        complex:
          accessor: ID
          root: Endpoint
    separatecontext: false
    task:
      brand: RedCanary
      id: 0c6607ff-5319-4ec3-865e-bfaee1ec343b
      iscommand: true
      name: Get specific endpoint
      script: RedCanary|||redcanary-get-endpoint
      type: regular
      version: -1
    taskid: 0c6607ff-5319-4ec3-865e-bfaee1ec343b
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1950\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      page:
        simple: '2'
      per-page:
        simple: '3'
    separatecontext: false
    task:
      brand: RedCanary
      id: 1f545044-33cd-458a-8cf5-23fb4bcbf469
      iscommand: true
      name: List Detections
      script: RedCanary|||redcanary-list-detections
      type: regular
      version: -1
    taskid: 1f545044-33cd-458a-8cf5-23fb4bcbf469
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 720\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Detection.ID
                root: RedCanary
                transformers:
                - operator: count
          operator: greaterThanOrEqual
          right:
            value:
              simple: '1'
      label: 'yes'
    id: '3'
    nexttasks:
      'yes':
      - '6'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 7b4458cc-e287-457e-8e92-a38f8f29cf6f
      iscommand: false
      name: Verify Context
      type: condition
      version: -1
    taskid: 7b4458cc-e287-457e-8e92-a38f8f29cf6f
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 895\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      page: {}
      per-page: {}
    separatecontext: false
    task:
      brand: RedCanary
      id: c58859e5-adcf-4050-8e3a-292d2dca02d2
      iscommand: true
      name: List EndPoints
      script: RedCanary|||redcanary-list-endpoints
      type: regular
      version: -1
    taskid: c58859e5-adcf-4050-8e3a-292d2dca02d2
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '5':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: EndPoint
          operator: isExists
      label: 'yes'
    id: '5'
    nexttasks:
      'yes':
      - '2'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 03692221-f098-4b9e-81b9-9e863663c369
      iscommand: false
      name: Verify Context
      type: condition
      version: -1
    taskid: 03692221-f098-4b9e-81b9-9e863663c369
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 545\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '7'
      - '9'
    note: false
    scriptarguments:
      id:
        complex:
          accessor: Detection
          filters:
          - - left:
                iscontext: true
                value:
                  simple: RedCanary.Detection.RemediationStatus
              operator: isNotExists
          root: RedCanary
          transformers:
          - operator: GetFirstObject
          - args:
              field:
                value:
                  simple: ID
            operator: getField
    separatecontext: false
    task:
      brand: RedCanary
      id: 3cce8e88-0c5a-4b23-891e-3b49f5828cd4
      iscommand: true
      name: Acknowledge detection
      script: RedCanary|||redcanary-acknowledge-detection
      type: regular
      version: -1
    taskid: 3cce8e88-0c5a-4b23-891e-3b49f5828cd4
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1070\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      detection-id:
        complex:
          accessor: Detection.ID
          root: RedCanary
          transformers:
          - operator: GetFirstObject
      playbook-id:
        simple: '3001'
      playbook-name: {}
    separatecontext: false
    task:
      brand: RedCanary
      id: 617f35e5-b284-495b-8e58-0b116ed4a5bc
      iscommand: true
      name: Execute test playbook on detection using ID
      script: RedCanary|||redcanary-execute-playbook
      type: regular
      version: -1
    taskid: 617f35e5-b284-495b-8e58-0b116ed4a5bc
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '10'
    note: false
    scriptarguments:
      comment:
        simple: 'demisto testing '
      id:
        complex:
          accessor: Detection
          filters:
          - - left:
                iscontext: true
                value:
                  simple: RedCanary.Detection.RemediationStatus
              operator: isNotExists
          root: RedCanary
          transformers:
          - operator: GetFirstObject
          - args:
              field:
                value:
                  simple: ID
            operator: getField
      remediation-state:
        simple: not_remediated_false_positive
    separatecontext: false
    task:
      brand: RedCanary
      id: 293aa7eb-6b43-4663-8e46-12de5f7ba286
      iscommand: true
      name: Remediate detection
      script: RedCanary|||redcanary-update-remediation-state
      type: regular
      version: -1
    taskid: 293aa7eb-6b43-4663-8e46-12de5f7ba286
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1420\n  }\n}"
  '9':
    id: '9'
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      detection-id:
        complex:
          accessor: Detection.ID
          root: RedCanary
          transformers:
          - operator: GetFirstObject
      playbook-id: {}
      playbook-name:
        simple: TestPlaybook
    separatecontext: false
    task:
      brand: RedCanary
      id: a9a7aed8-f254-4b1b-8b4b-98a1a3cdfe8c
      iscommand: true
      name: Execute test playbook on detection using name
      script: RedCanary|||redcanary-execute-playbook
      type: regular
      version: -1
    taskid: a9a7aed8-f254-4b1b-8b4b-98a1a3cdfe8c
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1245\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1995,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
