description: Master playbook for phishing incidents. This playbook is a manual playbook.
fromversion: 2.5.0
id: playbook2
name: Phishing Playbook - Manual
starttaskid: '0'
system: true
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    task:
      brand: ''
      description: ''
      id: 42767ebd-7fcd-4525-859f-be9d16a8517c
      iscommand: false
      name: start_task
      type: start
      version: -1
    taskid: 42767ebd-7fcd-4525-859f-be9d16a8517c
    type: start
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '3'
    task:
      brand: ''
      description: ''
      id: f61f3880-e5f6-4a41-8af8-3349e3ebffff
      iscommand: false
      name: Engage
      type: title
      version: -1
    taskid: f61f3880-e5f6-4a41-8af8-3349e3ebffff
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    nexttasks:
      'no':
      - '11'
      'yes':
      - '12'
    task:
      brand: ''
      description: Based on the steps above, is this really a phishing email?
      id: 5d36d65b-d63f-40b7-8167-2a341e9bed62
      iscommand: false
      name: Is this a real phishing email?
      version: -1
    taskid: 5d36d65b-d63f-40b7-8167-2a341e9bed62
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1535\n  }\n}"
  '11':
    id: '11'
    nexttasks:
      '#none#':
      - '14'
    task:
      brand: ''
      description: Close the investigation as false positive and reply to the user
        sending the email that it is not malicious.
      id: b37377be-5c13-41f5-8635-69ea34571af7
      iscommand: false
      name: Close the investigation as false positive
      version: -1
    taskid: b37377be-5c13-41f5-8635-69ea34571af7
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 278,\n    \"y\": 1909\n  }\n}"
  '12':
    id: '12'
    nexttasks:
      '#none#':
      - '13'
    task:
      brand: ''
      description: 'Based on the end user affected, and other information assess and
        change the severity if needed. '
      id: e76cfd73-35f3-4065-8e59-c37e365cd06c
      iscommand: false
      name: Assess severity
      type: regular
      version: -1
    taskid: e76cfd73-35f3-4065-8e59-c37e365cd06c
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 1710\n  }\n}"
  '13':
    id: '13'
    nexttasks:
      '#none#':
      - '14'
    task:
      brand: ''
      description: 'Invite the relevant users for investigation - malware expert and
        network experts if needed. '
      id: 5445acdd-df36-403e-8635-a0cbc3bd3f04
      iscommand: false
      name: Assign and involve appropriate personnel
      type: regular
      version: -1
    taskid: 5445acdd-df36-403e-8635-a0cbc3bd3f04
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 695,\n    \"y\": 1909\n  }\n}"
  '14':
    id: '14'
    nexttasks:
      '#none#':
      - '15'
    task:
      brand: ''
      description: ''
      id: eb2b0d5a-cc72-4640-8116-85750701ae1d
      iscommand: false
      name: 'Investigation Step 2: Deeper Analysis'
      version: -1
    taskid: eb2b0d5a-cc72-4640-8116-85750701ae1d
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2070\n  }\n}"
  '15':
    id: '15'
    nexttasks:
      '#none#':
      - '16'
    task:
      brand: ''
      description: ''
      id: 92ae3779-12c5-4a24-827e-56e413088b80
      iscommand: false
      name: Get all the URLs from the email
      version: -1
    taskid: 92ae3779-12c5-4a24-827e-56e413088b80
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2205\n  }\n}"
  '16':
    id: '16'
    nexttasks:
      '#none#':
      - '17'
    task:
      brand: ''
      description: ''
      id: 13e0228e-ad6a-4148-8aa6-55e8143a4620
      iscommand: false
      name: Get all the hostnames inside the email
      version: -1
    taskid: 13e0228e-ad6a-4148-8aa6-55e8143a4620
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2380\n  }\n}"
  '17':
    id: '17'
    nexttasks:
      '#none#':
      - '18'
    task:
      brand: ''
      description: 'Use curl or similar tool to download all the files from the URLs
        in the email. '
      id: 05855c19-9221-478d-8c83-4145aa2cff16
      iscommand: false
      name: Fetch all the files from the URL
      version: -1
    taskid: 05855c19-9221-478d-8c83-4145aa2cff16
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2555\n  }\n}"
  '18':
    id: '18'
    nexttasks:
      'no':
      - '19'
      'yes':
      - '23'
    task:
      brand: ''
      description: Check the files MD5 and SHA1 against the threat feed databases.
      id: 010895a1-9f86-4106-8e56-8f6889d5e228
      iscommand: false
      name: Are the files download malicious - hash inspection?
      version: -1
    taskid: 010895a1-9f86-4106-8e56-8f6889d5e228
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2730\n  }\n}"
  '19':
    id: '19'
    nexttasks:
      'no':
      - '20'
      'yes':
      - '22'
    task:
      brand: ''
      description: Check the files in a sandbox solution to see if they are malicious.
      id: 2580b31a-6c04-45b1-8752-959f66084ae3
      iscommand: false
      name: Are the files download malicious - static and dynamic analysis?
      version: -1
    taskid: 2580b31a-6c04-45b1-8752-959f66084ae3
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 2905\n  }\n}"
  '20':
    id: '20'
    nexttasks:
      '#default#':
      - '24'
      'yes':
      - '21'
    task:
      brand: ''
      description: 'Use Cuckoo or similar sandbox solutions for fetching the content
        of the URL for deeper analysis. '
      id: 24063b39-4c30-4ef2-8e7c-36081b45faaa
      iscommand: false
      name: Is any URL malicious based on sandbox inspection?
      version: -1
    taskid: 24063b39-4c30-4ef2-8e7c-36081b45faaa
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3080\n  }\n}"
  '21':
    id: '21'
    nexttasks:
      '#none#':
      - '24'
    task:
      brand: ''
      description: ''
      id: 9c572188-54b5-4d56-8e62-95ee93e3a157
      iscommand: false
      name: Consider this email as phishing and move to "Response Section"
      version: -1
    taskid: 9c572188-54b5-4d56-8e62-95ee93e3a157
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 215,\n    \"y\": 3255\n  }\n}"
  '22':
    id: '22'
    nexttasks:
      '#none#':
      - '24'
    task:
      brand: ''
      description: ''
      id: email_phishing
      iscommand: false
      name: Consider this email as phishing and move to "Response Section"
      version: -1
    taskid: email_phishing
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 631,\n    \"y\": 3080\n  }\n}"
  '23':
    id: '23'
    nexttasks:
      '#none#':
      - '24'
    task:
      brand: ''
      description: ''
      id: ff551c65-6d74-460d-8e4d-4a5a84517e9b
      iscommand: false
      name: Consider this email as phishing and move to "Response Section"
      version: -1
    taskid: ff551c65-6d74-460d-8e4d-4a5a84517e9b
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1024.5,\n    \"y\": 2905\n  }\n}"
  '24':
    id: '24'
    nexttasks:
      '#none#':
      - '25'
    task:
      brand: ''
      description: ''
      id: 3b29ac0a-190d-46bf-80cf-dbc1197d2f80
      iscommand: false
      name: 'Investigation Step 3: Is it a Campaign?'
      version: -1
    taskid: 3b29ac0a-190d-46bf-80cf-dbc1197d2f80
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3527\n  }\n}"
  '25':
    id: '25'
    nexttasks:
      '#default#':
      - '28'
      'yes':
      - '26'
    task:
      brand: ''
      description: Search past phishing investigations for subject sender, email content
        and URLs.
      id: 78cc334d-fe36-4cb0-8e63-dbb571077edc
      iscommand: false
      name: Did we have a similar phishing email earlier?
      version: -1
    taskid: 78cc334d-fe36-4cb0-8e63-dbb571077edc
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3676\n  }\n}"
  '26':
    id: '26'
    nexttasks:
      '#none#':
      - '27'
    task:
      brand: ''
      description: ''
      id: ec15c113-29a0-4ab5-85fc-3fc1fbe85a70
      iscommand: false
      name: Mark this as a campaign rather than isolated incident.
      version: -1
    taskid: ec15c113-29a0-4ab5-85fc-3fc1fbe85a70
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 278,\n    \"y\": 3841\n  }\n}"
  '27':
    id: '27'
    nexttasks:
      '#none#':
      - '28'
    task:
      brand: ''
      description: Future emails with similar subject should be associated with this
        incident
      id: e3710c0f-861d-4a9a-8e89-3488f572d74e
      iscommand: false
      name: Link old and new incidents to this master incident.
      version: -1
    taskid: e3710c0f-861d-4a9a-8e89-3488f572d74e
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 575,\n    \"y\": 4005\n  }\n}"
  '28':
    id: '28'
    nexttasks:
      '#none#':
      - '29'
    task:
      brand: ''
      description: ''
      id: 0386fa2c-a246-4dd9-8592-976b630148fc
      iscommand: false
      name: Respond
      version: -1
    taskid: 0386fa2c-a246-4dd9-8592-976b630148fc
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 4180\n  }\n}"
  '29':
    id: '29'
    nexttasks:
      '#none#':
      - '30'
    task:
      brand: ''
      description: 'If we identified multiple emails with similar content, subject
        and identified this as a campaign, we need to notify our users. Send an email
        to internal communications team with the details - like sender, content etc. '
      id: faf506e6-c1bd-49ee-8348-bdb258984785
      iscommand: false
      name: Notify internal PR team if this is a campaign
      version: -1
    taskid: faf506e6-c1bd-49ee-8348-bdb258984785
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 4365\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '4'
    task:
      brand: ''
      description: 'Notify appropriate people inside the organization. '
      id: d69a6289-b692-404c-8f90-d37d72aa265c
      iscommand: false
      name: Notify management chain
      version: -1
    taskid: d69a6289-b692-404c-8f90-d37d72aa265c
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 340\n  }\n}"
  '30':
    id: '30'
    nexttasks:
      '#none#':
      - '31'
    task:
      brand: ''
      description: "Identify the appropriate headers from the initial email beyond\
        \ subject\n and sender email to make sure we can effectively block this on\
        \ server. This\n task needs analysis of header to make sure we do not block\
        \ other emails and\n still be effective in blocking."
      id: a0b42339-fa44-4215-8fdd-8dc900011dd8
      iscommand: false
      name: Block email on the server
      version: -1
    taskid: a0b42339-fa44-4215-8fdd-8dc900011dd8
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 4568\n  }\n}"
  '31':
    id: '31'
    nexttasks:
      '#none#':
      - '32'
    task:
      brand: ''
      description: 'Give IT the phishing email so that they can train the SPAM filter
        with this email to avoid future attacks. '
      id: e93a15aa-1c5d-46ff-813c-b1f6eed114f3
      iscommand: false
      name: Notify IT to update SPAM filters
      version: -1
    taskid: e93a15aa-1c5d-46ff-813c-b1f6eed114f3
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 4770\n  }\n}"
  '32':
    id: '32'
    nexttasks:
      '#none#':
      - '33'
    task:
      brand: ''
      description: "Forward all the details to your security vendor for email security\n\
        \ solution. This will help them with the future updates."
      id: f487ba1c-d67b-40f2-8cf8-85f646b0d768
      iscommand: false
      name: Notify email security vendor
      version: -1
    taskid: f487ba1c-d67b-40f2-8cf8-85f646b0d768
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 4986\n  }\n}"
  '33':
    id: '33'
    nexttasks:
      '#none#':
      - '34'
    task:
      brand: ''
      description: 'Work with IT to completely delete similar emails from all user
        inboxes. Search through the SMTP logs to find all the recipients and delete
        the emails. '
      id: 1b6d8f94-452c-43b2-8606-da89d3f738c8
      iscommand: false
      name: Remove email from inboxes
      version: -1
    taskid: 1b6d8f94-452c-43b2-8606-da89d3f738c8
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 5215\n  }\n}"
  '34':
    id: '34'
    nexttasks:
      '#none#':
      - '35'
    task:
      brand: ''
      description: "Work with IT to black hole the phishing domains (this particular\n\
        \ and related ones from other emails and incidents that were marked duplicate).\n\
        \ This should be blocked on the domain controller by resolving to 127.0.0.1"
      id: c47f9b5a-cba2-4b2c-89ca-0c1003e9c295
      iscommand: false
      name: Blackholing phishing domain on Domain Controller
      version: -1
    taskid: c47f9b5a-cba2-4b2c-89ca-0c1003e9c295
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 5440\n  }\n}"
  '35':
    id: '35'
    nexttasks:
      '#none#':
      - '36'
    task:
      brand: ''
      description: " 1. Try to identify a pattern in the URL. For example if the URL\
        \ is: http://hackedwebsite.com/dl.php?campaign=ra&id=12731342834923919\n 2.\
        \ Create a reasonable regex like: ^.+/dl.php?.*campaign=ra.$\n 3. Contact\
        \ the proxy team to block URLs based on the pattern"
      id: b3e805e2-2566-4f28-884d-dcc8a8fe3573
      iscommand: false
      name: Blocking download URL
      version: -1
    taskid: b3e805e2-2566-4f28-884d-dcc8a8fe3573
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 5628\n  }\n}"
  '36':
    id: '36'
    task:
      brand: ''
      description: Report all the files that were downloaded from URL to AV vendor
        and virustotal like services.
      id: ffa62d59-1b44-4305-8324-3cc29f4585ff
      iscommand: false
      name: Report malware sample to AV vendors
      version: -1
    taskid: ffa62d59-1b44-4305-8324-3cc29f4585ff
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 5842\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '5'
    task:
      brand: ''
      description: 1. Make sure that there is relevant information in the incident
        - system name, end user name and initial severity as reported.
      id: 21cb9178-78a0-4610-801f-3bc5f808e4a2
      iscommand: false
      name: Initial triage
      version: -1
    taskid: 21cb9178-78a0-4610-801f-3bc5f808e4a2
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 515\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '6'
    task:
      brand: ''
      description: ''
      id: b7f2e51f-a39f-4cba-881d-e7efbef2553e
      iscommand: false
      name: 'Investigation Step 1: Initial Inspection'
      version: -1
    taskid: b7f2e51f-a39f-4cba-881d-e7efbef2553e
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 690\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '7'
    task:
      brand: ''
      description: Check the email body attached to the incident and see if it has
        malicious URLs in it using threat feeds
      id: 30e833d0-8336-4ecd-8a36-a997ac1bb100
      iscommand: false
      name: Inspect the email body for malicious URLs
      version: -1
    taskid: 30e833d0-8336-4ecd-8a36-a997ac1bb100
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 835\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '8'
    task:
      brand: ''
      description: Check the attachments with threat services to see if any of them
        is known bad
      id: 0aba5f0e-c71f-4a1f-8f7a-993f727e3825
      iscommand: false
      name: Inspect the email attachments
      version: -1
    taskid: 0aba5f0e-c71f-4a1f-8f7a-993f727e3825
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1010\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '9'
    task:
      brand: ''
      description: Check the sender email and name against threat feed sources.
      id: fa90abdd-2ec1-490b-8a9e-2acc6f2f721d
      iscommand: false
      name: Is the sender name or email address identified as bad by threat feeds?
      version: -1
    taskid: fa90abdd-2ec1-490b-8a9e-2acc6f2f721d
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1185\n  }\n}"
  '9':
    id: '9'
    nexttasks:
      '#none#':
      - '10'
    task:
      brand: ''
      description: "Check if domain of sender or any hostname in the URLs inside the\
        \ email body are misrepresented. See if the URL text versus the hostname shown\
        \ are different by comparing the link with the text. Also carefully inspected\
        \ the URLs for spelling spoofing which\n is typically a sign of phishing email."
      id: d9fad845-7f5b-4c79-8835-2e8358c84e04
      iscommand: false
      name: Check if the hostname is being misrepresented?
      version: -1
    taskid: d9fad845-7f5b-4c79-8835-2e8358c84e04
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1360\n  }\n}"
tests:
- No tests
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 5887,\n      \"width\": 1354.5,\n      \"x\": 50,\n      \"y\"\
  : 50\n    }\n  }\n}"
