id: AlienVaultUSMAnywhereTest
inputs: []
name: AlienVaultUSMAnywhereTest
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 11ea892b-ca95-4a24-874f-932468b6facc
      iscommand: false
      name: ''
      version: -1
    taskid: 11ea892b-ca95-4a24-874f-932468b6facc
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
      - '11'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: cd3f00c4-a826-4fde-885b-3f2543b70a8e
      iscommand: false
      name: Clean Start
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: cd3f00c4-a826-4fde-885b-3f2543b70a8e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    note: false
    scriptarguments:
      alarm_id:
        simple: ${AV.AlarmID}
    separatecontext: false
    task:
      brand: ''
      description: Get events associated with an alarm.
      id: 7ea3115a-c861-492a-873a-491d4c51beff
      iscommand: true
      name: Get Events by Alarm ID
      script: '|||alienvault-get-events-by-alarm'
      type: regular
      version: -1
    taskid: 7ea3115a-c861-492a-873a-491d4c51beff
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 920,\n    \"y\": 1070\n  }\n}"
  '11':
    id: '11'
    note: false
    scriptarguments:
      account_name: {}
      end_time: {}
      event_name:
        simple: ET POLICY RDP connection confirm
      limit:
        simple: '5'
      source_name: {}
      start_time: {}
      time_frame:
        simple: Today
    separatecontext: false
    task:
      brand: ''
      description: Search events.
      id: db25d685-d8fd-4325-80ac-6f9392b094d7
      iscommand: true
      name: Search events
      script: '|||alienvault-search-events'
      type: regular
      version: -1
    taskid: db25d685-d8fd-4325-80ac-6f9392b094d7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -180,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      end_time: {}
      limit:
        simple: '6'
      priority: {}
      rule_intent: {}
      rule_method: {}
      rule_strategy: {}
      show_suppressed: {}
      start_time: {}
      status: {}
      time_frame: {}
    separatecontext: false
    task:
      brand: ''
      description: Get alarms from service.
      id: 8fc3581b-a478-40b4-81ce-ff262366b33b
      iscommand: true
      name: Search alarms
      script: '|||alienvault-search-alarms'
      type: regular
      version: -1
    taskid: 8fc3581b-a478-40b4-81ce-ff262366b33b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '3':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Alarm
                root: AlienVault
                transformers:
                - operator: GetFirstObject
                - args:
                    field:
                      value:
                        simple: ID
                  operator: getField
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Alarm
                root: AlienVault
                transformers:
                - operator: GetFirstObject
                - args:
                    field:
                      value:
                        simple: Priority
                  operator: getField
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: AlienVault.Alarm.OccurredTime
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: AlienVault.Alarm.Source.IPAddress
          operator: isExists
      label: 'yes'
    id: '3'
    nexttasks:
      '#default#':
      - '4'
      'yes':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 9ae31abc-9945-4eb8-8318-ad9622805555
      iscommand: false
      name: Verify Command Success
      type: condition
      version: -1
    taskid: 9ae31abc-9945-4eb8-8318-ad9622805555
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    note: false
    scriptarguments:
      message:
        simple: Invalid Outputs
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: 99c897af-114b-4559-8e19-3f3851561943
      iscommand: false
      name: Error
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 99c897af-114b-4559-8e19-3f3851561943
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      append: {}
      key:
        simple: AV.AlarmID
      value:
        complex:
          accessor: Alarm
          root: AlienVault
          transformers:
          - args:
              index:
                value:
                  simple: '0'
            operator: atIndex
          - args:
              field:
                value:
                  simple: ID
            operator: getField
    separatecontext: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: 2ff050b8-65e8-4fa1-88f6-a5a2672b5076
      iscommand: false
      name: Save one ID
      scriptName: Set
      type: regular
      version: -1
    taskid: 2ff050b8-65e8-4fa1-88f6-a5a2672b5076
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 470,\n    \"y\": 720\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      '#none#':
      - '7'
      - '10'
    note: false
    scriptarguments:
      all: {}
      index: {}
      key:
        simple: AlienVault
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 5813d409-d4ce-43e3-86cc-512c476a3df3
      iscommand: false
      name: Clear Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 5813d409-d4ce-43e3-86cc-512c476a3df3
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 470,\n    \"y\": 895\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '8'
    note: false
    scriptarguments:
      alarm_id:
        simple: ${AV.AlarmID}
      id:
        simple: ${AV.AlarmID}
    separatecontext: false
    task:
      brand: ''
      description: Get an alarm's details using ID
      id: f8ecbafd-a595-4691-8723-a5878238e1c6
      iscommand: true
      name: Get Specific Alarm
      script: '|||alienvault-get-alarm'
      type: regular
      version: -1
    taskid: f8ecbafd-a595-4691-8723-a5878238e1c6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 470,\n    \"y\": 1070\n  }\n}"
  '8':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: AlienVault.Alarm.ID
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: AlienVault.Alarm.Priority
          operator: isExists
      - - left:
            iscontext: true
            value:
              simple: AlienVault.Alarm.OccurredTime
          operator: isExists
      label: 'yes'
    id: '8'
    nexttasks:
      '#default#':
      - '4'
      'yes':
      - '9'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 6dba6e3a-bd3c-478a-8f75-968a4648acb2
      iscommand: false
      name: Verify Command Success
      type: condition
      version: -1
    taskid: 6dba6e3a-bd3c-478a-8f75-968a4648acb2
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 470,\n    \"y\": 1245\n  }\n}"
  '9':
    id: '9'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 3eea87db-d087-4ffc-8aff-d0959872f42d
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 3eea87db-d087-4ffc-8aff-d0959872f42d
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1435\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1465,\n      \"width\": 1480,\n      \"x\": -180,\n      \"y\"\
  : 50\n    }\n  }\n}"
