id: Netskope Test
inputs: []
name: Netskope Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 460c6756-a817-4a6b-8964-5e8b6cf7323c
      iscommand: false
      name: ''
      version: -1
    taskid: 460c6756-a817-4a6b-8964-5e8b6cf7323c
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      endtime: {}
      query: {}
      starttime: {}
      timeperiod:
        simple: Last90Days
      type:
        simple: Malware
    separatecontext: false
    task:
      brand: ''
      id: 647f312a-8616-4b6e-874e-596f183f1567
      iscommand: true
      name: netskope-alerts
      script: '|||netskope-alerts'
      type: regular
      version: -1
    taskid: 647f312a-8616-4b6e-874e-596f183f1567
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 230\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      expectedValue: {}
      fields:
        simple: ID,Timestamp
      path:
        simple: Netskope.Alerts
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 4f46a651-cff8-473a-82f5-a49b4e422a38
      iscommand: false
      name: VerifyContext
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 4f46a651-cff8-473a-82f5-a49b4e422a38
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 410\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      endtime:
        simple: 28-12-2018T01:01:01Z
      limit: {}
      query: {}
      skip: {}
      starttime:
        simple: '1545260461'
      timeperiod: {}
      type:
        simple: audit
    separatecontext: false
    task:
      brand: ''
      id: 69a409e1-6a8e-4046-8622-50963c6d74f7
      iscommand: true
      name: netskope-events
      script: '|||netskope-events'
      type: regular
      version: -1
    taskid: 69a409e1-6a8e-4046-8622-50963c6d74f7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 590\n  }\n}"
  '4':
    id: '4'
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      expectedValue: {}
      fields:
        simple: ID,Timestamp,User
      path:
        simple: Netskope.Events
    separatecontext: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: 71e5c03d-a66e-4326-89dc-097c10777a78
      iscommand: false
      name: VerifyContext
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: 71e5c03d-a66e-4326-89dc-097c10777a78
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 770\n  }\n}"
  '5':
    id: '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 65ea66fc-1743-492a-8801-a093a20bb132
      iscommand: false
      name: Success
      type: title
      version: -1
    taskid: 65ea66fc-1743-492a-8801-a093a20bb132
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 961\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 976,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\": 50\n\
  \    }\n  }\n}"
