id: MxToolbox-test
inputs: []
name: MxToolbox-test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: c0877588-82bc-413c-8799-cdeeb1d69974
      iscommand: false
      name: ''
      version: -1
    taskid: c0877588-82bc-413c-8799-cdeeb1d69974
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    scriptarguments:
      additionalParams: {}
      command:
        simple: a
      data:
        simple: example.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: MxToolBox
      description: Run any supported command on the mxtoolbox API
      id: e3656ffe-6ea6-4744-8cd8-2851dd627d5c
      iscommand: true
      name: mxtoolbox
      script: MxToolBox|||mxtoolbox
      type: regular
      version: -1
    taskid: e3656ffe-6ea6-4744-8cd8-2851dd627d5c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      columns: {}
      data:
        simple: ${MXToolbox.Errors}
      title: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 9c00dae7-f9e8-486e-828d-5c700623055b
      iscommand: false
      name: Print failures
      scriptName: ToTable
      type: regular
      version: -1
    taskid: 9c00dae7-f9e8-486e-828d-5c700623055b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 2f4d8e5f-9569-4491-8068-882f7931dc17
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 2f4d8e5f-9569-4491-8068-882f7931dc17
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1610\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    quietmode: 0
    scriptarguments:
      additionalParams: {}
      command:
        simple: dns
      data:
        simple: example.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: MxToolBox
      description: Run any supported command on the mxtoolbox API
      id: 818a35f4-461e-4cfd-8bc3-34463ea80a9d
      iscommand: true
      name: mxtoolbox
      script: MxToolBox|||mxtoolbox
      type: regular
      version: -1
    taskid: 818a35f4-461e-4cfd-8bc3-34463ea80a9d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    quietmode: 0
    scriptarguments:
      additionalParams: {}
      command:
        simple: mx
      data:
        simple: example.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: MxToolBox
      description: Run any supported command on the mxtoolbox API
      id: bbcfe90c-56ba-44be-813f-a41d4cf12116
      iscommand: true
      name: mxtoolbox
      script: MxToolBox|||mxtoolbox
      type: regular
      version: -1
    taskid: bbcfe90c-56ba-44be-813f-a41d4cf12116
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 545\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    scriptarguments:
      additionalParams: {}
      command:
        simple: spf
      data:
        simple: example.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: MxToolBox
      description: Run any supported command on the mxtoolbox API
      id: b174436d-2fb4-4fe0-8689-63f7757f2058
      iscommand: true
      name: mxtoolbox
      script: MxToolBox|||mxtoolbox
      type: regular
      version: -1
    taskid: b174436d-2fb4-4fe0-8689-63f7757f2058
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      additionalParams: {}
      command:
        simple: txt
      data:
        simple: example.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: MxToolBox
      description: Run any supported command on the mxtoolbox API
      id: e457361e-d247-4fcb-8592-d79d00241c81
      iscommand: true
      name: mxtoolbox
      script: MxToolBox|||mxtoolbox
      type: regular
      version: -1
    taskid: e457361e-d247-4fcb-8592-d79d00241c81
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 895\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    quietmode: 0
    scriptarguments:
      additionalParams: {}
      command:
        simple: soa
      data:
        simple: example.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: MxToolBox
      description: Run any supported command on the mxtoolbox API
      id: 5e210e1d-c8fc-4242-87ed-9c28302c709e
      iscommand: true
      name: mxtoolbox
      script: MxToolBox|||mxtoolbox
      type: regular
      version: -1
    taskid: 5e210e1d-c8fc-4242-87ed-9c28302c709e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1070\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    quietmode: 0
    scriptarguments:
      additionalParams: {}
      command:
        simple: ptr
      data:
        simple: 93.184.216.34
    separatecontext: false
    skipunavailable: false
    task:
      brand: MxToolBox
      description: Run any supported command on the mxtoolbox API
      id: 351ec25e-bd50-4557-8026-703fa844f020
      iscommand: true
      name: mxtoolbox
      script: MxToolBox|||mxtoolbox
      type: regular
      version: -1
    taskid: 351ec25e-bd50-4557-8026-703fa844f020
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1245\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '12'
      'yes':
      - '11'
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${MXToolbox.Errors}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 7c03d173-6235-48fb-839b-e99ecaf11b38
      iscommand: false
      name: Exists errors?
      scriptName: Exists
      type: condition
      version: -1
    taskid: 7c03d173-6235-48fb-839b-e99ecaf11b38
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 1420\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1640,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
