id: FalconHost Test
inputs: []
name: FalconHost Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 814a2191-34e0-40f0-8666-40c67174a0e3
      iscommand: false
      name: ''
      version: -1
    taskid: 814a2191-34e0-40f0-8666-40c67174a0e3
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '13':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: FalconHostDevices
          operator: isExists
      label: 'yes'
    id: '13'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '31'
      'yes':
      - '15'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 1a6ef7d7-f6a0-4028-8111-56913ffcc87d
      iscommand: false
      name: Found any devices?
      type: condition
      version: -1
    taskid: 1a6ef7d7-f6a0-4028-8111-56913ffcc87d
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 545\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    quietmode: 0
    scriptarguments:
      ids:
        simple: ${FalconHostDevices}
    separatecontext: false
    skipunavailable: false
    task:
      brand: FalconHost
      description: Get details for one or more devices, according to device ID
      id: d3f6e785-edad-4a2b-89ed-1247ea92d857
      iscommand: true
      name: Get device details
      script: FalconHost|||cs-device-details
      type: regular
      version: -1
    taskid: d3f6e785-edad-4a2b-89ed-1247ea92d857
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 377.5,\n    \"y\": 720\n  }\n}"
  '16':
    id: '16'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '19'
    note: false
    quietmode: 0
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: Endpoint
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: 'Verifies path in context:

        - Verifies path existence

        - If matching object is an array: verify fields exists in each of the objects
        in the array

        - If matching object is not an array: verify fields exists in matching object

        - if ''expectedValue'' is given: ensure that the given value is equal to the
        context path'
      id: c5092555-1c08-41ae-8d39-b4cee81f02fd
      iscommand: false
      name: Verify Endpoint
      scriptName: VerifyContext
      type: regular
      version: -1
    taskid: c5092555-1c08-41ae-8d39-b4cee81f02fd
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 377.5,\n    \"y\": 895\n  }\n}"
  '17':
    id: '17'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '24'
    note: false
    quietmode: 0
    scriptarguments:
      type:
        simple: md5
      value:
        simple: 36bd4be7042f6de7e332c05cef287d05
    separatecontext: false
    skipunavailable: false
    task:
      brand: FalconHost
      description: Returns a list of device IDs on which an indicator ran
      id: e32e6cd8-3a3f-4af6-8f74-aa25e3f5166f
      iscommand: true
      name: Search by MD5
      script: FalconHost|||cs-device-ran-on
      type: regular
      version: -1
    taskid: e32e6cd8-3a3f-4af6-8f74-aa25e3f5166f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 377.5,\n    \"y\": 1245\n  }\n}"
  '18':
    id: '18'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '33'
    note: false
    quietmode: 0
    scriptarguments:
      ids:
        simple: ${FalconHostDevices}
    separatecontext: false
    skipunavailable: false
    task:
      brand: FalconHost
      description: Get details for one or more devices, according to device ID
      id: 30a8b402-3b19-4fcd-85c2-89c784800ce4
      iscommand: true
      name: Get details
      script: FalconHost|||cs-device-details
      type: regular
      version: -1
    taskid: 30a8b402-3b19-4fcd-85c2-89c784800ce4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 490,\n    \"y\": 1595\n  }\n}"
  '19':
    id: '19'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: 89baa8b3-c51d-4fd3-82ca-4ab5b0aa68f8
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 89baa8b3-c51d-4fd3-82ca-4ab5b0aa68f8
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 377.5,\n    \"y\": 1070\n  }\n}"
  '21':
    id: '21'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '22'
    note: false
    quietmode: 0
    scriptarguments:
      filter: {}
      limit: {}
      offset:
        simple: ${Offset}
      query: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: FalconHost
      description: Search for devices in your environment by platform, host name,
        IP, or various other parameters
      id: 68dfc3fe-83f7-4055-8ae4-2c8ea4e0277b
      iscommand: true
      name: Search with number offset
      script: FalconHost|||cs-device-search
      type: regular
      version: -1
    taskid: 68dfc3fe-83f7-4055-8ae4-2c8ea4e0277b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 377.5,\n    \"y\": 2470\n  }\n}"
  '22':
    id: '22'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '31'
    note: false
    quietmode: 0
    scriptarguments:
      ids:
        simple: ${FalconHostDevices}
    separatecontext: false
    skipunavailable: false
    task:
      brand: FalconHost
      description: Get details for one or more devices, according to device ID
      id: 96b3082f-634e-4464-8243-eb28911f29fa
      iscommand: true
      name: Get device details
      script: FalconHost|||cs-device-details
      type: regular
      version: -1
    taskid: 96b3082f-634e-4464-8243-eb28911f29fa
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 377.5,\n    \"y\": 2645\n  }\n}"
  '23':
    id: '23'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '21'
    note: false
    quietmode: 0
    scriptarguments:
      append: {}
      key:
        simple: Offset
      value:
        simple: '1'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Sets a value into the context with the given context key
      id: bebd7ce9-ca44-4728-8bc2-d182accddbf5
      iscommand: false
      name: Set number offset
      scriptName: Set
      type: regular
      version: -1
    taskid: bebd7ce9-ca44-4728-8bc2-d182accddbf5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 377.5,\n    \"y\": 2295\n  }\n}"
  '24':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: FalconHostDevices
          operator: isExists
      label: 'yes'
    id: '24'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '33'
      'yes':
      - '18'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: d9e46570-c5f0-4c44-8aaa-a9f001c8d688
      iscommand: false
      name: Found any devices?
      type: condition
      version: -1
    taskid: d9e46570-c5f0-4c44-8aaa-a9f001c8d688
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 377.5,\n    \"y\": 1420\n  }\n}"
  '25':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Detections.detection_id
                root: CrowdStrikeHost
          operator: isExists
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Detections.detection_id
                root: CrowdStrikeHost
                transformers:
                - operator: count
          operator: greaterThan
          right:
            value:
              simple: '1'
      label: 'yes'
    id: '25'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '27'
      'yes':
      - '26'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Check detections were fetched
      id: 9c68c21d-78a8-4487-89c1-0a7876c8b74a
      iscommand: false
      name: Check detections were fetched
      type: condition
      version: -1
    taskid: 9c68c21d-78a8-4487-89c1-0a7876c8b74a
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 2995\n  }\n}"
  '26':
    id: '26'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '28'
    note: false
    quietmode: 0
    scriptarguments:
      detection_id:
        complex:
          accessor: Detections.detection_id
          root: CrowdStrikeHost
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Fetch details of a Crowdstrike Detection using the detection ID
      id: 4b1c707d-956b-48c6-8db8-ea6eadb7a0bd
      iscommand: true
      name: Get Detection Details
      script: '|||cs-detection-details'
      type: regular
      version: -1
    taskid: 4b1c707d-956b-48c6-8db8-ea6eadb7a0bd
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3170\n  }\n}"
  '27':
    id: '27'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 79dd6e1e-4b80-42e8-8628-3078e72aef69
      iscommand: false
      name: No Detections to check
      type: title
      version: -1
    taskid: 79dd6e1e-4b80-42e8-8628-3078e72aef69
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 3185\n  }\n}"
  '28':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Detections.first_behavior
                root: CrowdStrikeHost
          operator: isExists
      label: 'yes'
    id: '28'
    ignoreworker: false
    nexttasks:
      'yes':
      - '29'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Assert detections details were fetched
      id: e915c6ff-a88b-47d5-8572-14fdec4d6ee8
      iscommand: false
      name: Assert detections details were fetched
      type: condition
      version: -1
    taskid: e915c6ff-a88b-47d5-8572-14fdec4d6ee8
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3345\n  }\n}"
  '29':
    id: '29'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '30'
    note: false
    quietmode: 0
    scriptarguments:
      ids:
        complex:
          accessor: Detections.detection_id
          root: CrowdStrikeHost
      status:
        simple: in_progress
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Sets the state of a detection in Falcon Host. You can obtain detection
        IDs from the Falcon Host UI or from the Falcon Streaming API.
      id: b9c891b1-3d19-4a68-8519-2f48f94b7105
      iscommand: true
      name: Change Detection to in_progress
      script: '|||cs-resolve-detection'
      type: regular
      version: -1
    taskid: b9c891b1-3d19-4a68-8519-2f48f94b7105
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3520\n  }\n}"
  '30':
    id: '30'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Done
      id: db5f714e-a4e7-4da1-8d07-2083c0b33e5a
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: db5f714e-a4e7-4da1-8d07-2083c0b33e5a
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3695\n  }\n}"
  '31':
    id: '31'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '25'
    note: false
    quietmode: 0
    scriptarguments:
      first_behavior:
        simple: '2017-01-31T22:36:11Z'
      query: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: String search through all Crowdstrike Detection fields.  For example,
        provide a sensor ID to search for all detections that contain that sensor
        ID (and any other fields that would happen to contain it)
      id: f40e6b74-da7f-4dd9-8196-18957526f7d3
      iscommand: true
      name: Search Detections Since 2017
      script: '|||cs-detection-search'
      type: regular
      version: -1
    taskid: f40e6b74-da7f-4dd9-8196-18957526f7d3
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 2820\n  }\n}"
  '33':
    id: '33'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '37'
    note: false
    quietmode: 0
    scriptarguments:
      type:
        simple: ipv4
      value:
        simple: 10.2.101.237
    separatecontext: false
    skipunavailable: false
    task:
      brand: FalconHost
      description: Returns a list of device IDs on which an indicator ran
      id: d6c3da2e-28a9-43a6-87ab-7b8e0385079d
      iscommand: true
      name: Search by IPv4
      script: FalconHost|||cs-device-ran-on
      type: regular
      version: -1
    taskid: d6c3da2e-28a9-43a6-87ab-7b8e0385079d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 377.5,\n    \"y\": 1770\n  }\n}"
  '37':
    id: '37'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '38'
    note: false
    quietmode: 0
    scriptarguments:
      type:
        simple: ipv6
      value:
        simple: 2001:4860:4860::8888
    separatecontext: false
    skipunavailable: false
    task:
      brand: FalconHost
      description: Returns a list of device IDs on which an indicator ran
      id: 4529e31f-2a27-48d8-83c0-e26bccad20e7
      iscommand: true
      name: Search by IPv6
      script: FalconHost|||cs-device-ran-on
      type: regular
      version: -1
    taskid: 4529e31f-2a27-48d8-83c0-e26bccad20e7
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 377.5,\n    \"y\": 1945\n  }\n}"
  '38':
    id: '38'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '23'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: 657811da-8607-42da-87e2-fa4b393a1de2
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 657811da-8607-42da-87e2-fa4b393a1de2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 377.5,\n    \"y\": 2120\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    quietmode: 0
    scriptarguments:
      filter: {}
      limit: {}
      offset:
        simple: '1'
      query: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: FalconHost
      description: Search for devices in your environment by platform, host name,
        IP, or a number of other parameters
      id: f16f4c13-934e-422f-8415-6d84bd306c88
      iscommand: true
      name: Search devices
      script: FalconHost|||cs-device-search
      type: regular
      version: -1
    taskid: f16f4c13-934e-422f-8415-6d84bd306c88
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      id: d84e95eb-b9a3-457e-83c9-4cab302a94b5
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: d84e95eb-b9a3-457e-83c9-4cab302a94b5
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
toversion: 4.1.9
vcShouldKeepItemLegacyProdMachine: false
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 3710,\n      \"width\": 820,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
