fromversion: 3.5.0
id: CrowdStrike Endpoint Enrichment - Test
inputs: []
name: CrowdStrike Endpoint Enrichment - Test
outputs: []
rolename: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 82d14d08-e086-413e-8f6f-cb7c9309303a
      iscommand: false
      name: ''
      version: -1
    taskid: 82d14d08-e086-413e-8f6f-cb7c9309303a
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '12':
    id: '12'
    note: false
    scriptarguments:
      first_behavior: {}
      query:
        simple: '1'
    separatecontext: false
    task:
      brand: FalconHost
      description: String search through all Crowdstrike Detection fields.  For example,
        provide a sensor ID to search for all detections that contain that sensor
        ID (and any other fields that would happen to contain it)
      id: afed1757-85c5-40a8-82ff-be7f8a00fb8e
      iscommand: true
      name: cs-detection-search
      script: FalconHost|||cs-detection-search
      type: regular
      version: -1
    taskid: afed1757-85c5-40a8-82ff-be7f8a00fb8e
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '13':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Endpoint.OS
          operator: containsGeneral
          right:
            value:
              simple: Windows
        - left:
            iscontext: true
            value:
              simple: Endpoint.OS
          operator: containsGeneral
          right:
            value:
              simple: Linux
      label: 'yes'
    id: '13'
    nexttasks:
      '#default#':
      - '14'
      'yes':
      - '12'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: a9ab8750-2d51-4bbb-85c1-2e77591cf409
      iscommand: false
      name: Context check
      type: condition
      version: -1
    taskid: a9ab8750-2d51-4bbb-85c1-2e77591cf409
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 720\n  }\n}"
  '14':
    id: '14'
    note: false
    scriptarguments:
      message:
        simple: No endpoint data
    separatecontext: false
    task:
      brand: ''
      id: 49c635f7-d828-4351-8099-c7b15595facd
      iscommand: false
      name: raise an error
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 49c635f7-d828-4351-8099-c7b15595facd
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 895\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      filter: {}
      limit: {}
      offset: {}
      query: {}
    separatecontext: false
    task:
      brand: FalconHost
      description: Search for devices in your environment by platform, host name,
        IP, or a number of other parameters
      id: ed0336e2-778b-4c07-86ad-511d86cd520c
      iscommand: true
      name: cs-device-search
      script: FalconHost|||cs-device-search
      type: regular
      version: -1
    taskid: ed0336e2-778b-4c07-86ad-511d86cd520c
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: e3edaafa-0d2a-44b8-8317-9d73ff3dcf0f
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: e3edaafa-0d2a-44b8-8317-9d73ff3dcf0f
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '9':
    id: '9'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '13'
    note: false
    scriptarguments:
      Hostname:
        simple: ${Endpoint.Hostname}
    separatecontext: true
    task:
      brand: ''
      description: Enrich Endpoint with CrowdStrike
      id: fc7af480-343f-4bed-8081-b53cbd6e8b5f
      iscommand: false
      name: CrowdStrike Endpoint Enrichment
      playbookName: CrowdStrike Endpoint Enrichment
      type: playbook
      version: -1
    taskid: fc7af480-343f-4bed-8081-b53cbd6e8b5f
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 545\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 940,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
