id: Preempt Test
inputs:
- description: ''
  key: userGUID
  required: false
  value:
    simple: efa1c5c5-5fee-4573-878b-3c0070b25e07
name: Preempt Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '1'
      - '3'
      - '4'
    separatecontext: false
    task:
      brand: ''
      id: 886e9130-12d4-4ece-8600-395bcf12709f
      iscommand: false
      name: ''
      version: -1
    taskid: 886e9130-12d4-4ece-8600-395bcf12709f
    type: start
    view: "{\n  \"position\": {\n    \"x\": 618,\n    \"y\": 45\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      accountObjectGuid:
        simple: ${inputs.userGUID}
    separatecontext: false
    task:
      brand: Preempt
      description: Adds requested user to Preempt's watch list
      id: fce7002f-54ae-467b-8b6e-6b76cfacd703
      iscommand: true
      name: preempt-add-to-watch-list
      script: Preempt|||preempt-add-to-watch-list
      type: regular
      version: -1
    taskid: fce7002f-54ae-467b-8b6e-6b76cfacd703
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 191\n  }\n}"
  '2':
    id: '2'
    scriptarguments:
      accountObjectGuid:
        simple: ${inputs.userGUID}
    separatecontext: false
    task:
      brand: Preempt
      description: Removes requested user from Preempt's watch list
      id: 9c803b87-be49-4415-8dea-79b81d4e8341
      iscommand: true
      name: preempt-remove-from-watch-list
      script: Preempt|||preempt-remove-from-watch-list
      type: regular
      version: -1
    taskid: 9c803b87-be49-4415-8dea-79b81d4e8341
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 342\n  }\n}"
  '3':
    id: '3'
    scriptarguments:
      endTime: {}
      numOfHours: {}
      sourceUserId:
        simple: ${inputs.userGUID}
      types: {}
    separatecontext: false
    task:
      brand: Preempt
      description: Get activities from a time frame
      id: 4701b6c4-a2ac-46f4-8d6d-0a030f1a25c4
      iscommand: true
      name: preempt-get-activities
      script: Preempt|||preempt-get-activities
      type: regular
      version: -1
    taskid: 4701b6c4-a2ac-46f4-8d6d-0a030f1a25c4
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 929,\n    \"y\": 274\n  }\n}"
  '4':
    id: '4'
    scriptarguments:
      sourceUserId:
        simple: ${inputs.userGUID}
    separatecontext: false
    task:
      brand: Preempt
      description: Gets the endpoints regularly used by the user account
      id: f8351780-ab37-4407-8957-d5c3d0c5ae18
      iscommand: true
      name: preempt-get-user-endpoints
      script: Preempt|||preempt-get-user-endpoints
      type: regular
      version: -1
    taskid: f8351780-ab37-4407-8957-d5c3d0c5ae18
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1369,\n    \"y\": 274\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 392,\n      \"width\": 1699,\n      \"x\": 50,\n      \"y\": 45\n\
  \    }\n  }\n}"
