description: This is a playbook for queuing and displaying vault search result
fromversion: 4.0.0
id: Google-Vault-Display-Results
inputs:
- description: Interval to check export status (minutes)
  key: pollInterval
  required: false
  value:
    simple: '2'
- description: Timeout to terminate the poll (minutes)
  key: pollTimeout
  required: false
  value:
    simple: '30'
- description: The maximal number of result to be displayed
  key: maxResultForDisplay
  required: false
  value:
    simple: '30'
- description: If set to true the export file created will be downloaded into the
    War Room
  key: downloadFile
  required: false
  value:
    simple: 'false'
- description: Export ID
  key: ExportID
  required: true
  value: {}
- description: Matter ID
  key: MatterID
  required: true
  value: {}
- description: 'Type of Search could be one of: ''Drive'', ''Groups'' or ''Mail'''
  key: SearchtType
  required: true
  value: {}
name: Google Vault - Display Results
outputs:
- contextPath: GoogleVault.Matter.Export.MatterID
  description: Matter ID
  type: string
- contextPath: GoogleVault.Matter.Export.ExportID
  description: Export ID
  type: string
- contextPath: GoogleVault.Matter.Export.Name
  description: Export's name
  type: string
- contextPath: GoogleVault.Matter.Export.CreateTime
  description: Export's creation time
  type: string
- contextPath: GoogleVault.Matter.Export.Results.CC
  description: CC of the mail
  type: string
- contextPath: GoogleVault.Matter.Export.Results.BCC
  description: 'BCC of the mail '
  type: string
- contextPath: GoogleVault.Matter.Export.Results.DateSent
  description: The date the email was sent
  type: string
- contextPath: GoogleVault.Matter.Export.Results.From
  description: The sender of the email
  type: string
- contextPath: GoogleVault.Matter.Export.Results.Subject
  description: The subject of the email
  type: string
- contextPath: GoogleVault.Matter.Export.Results.DateReceived
  description: The date the email was received
  type: string
- contextPath: GoogleVault.Matter.Export.Results.To
  description: The address the email was sent to
  type: string
- contextPath: GoogleVault.Matter.Export.Status
  description: Export Status (COMPLETED,FAILED,IN_PROGRESS)
  type: string
- contextPath: GoogleVault.Matter.Export.BucketName
  description: Bucket holder name for this export
  type: string
- contextPath: GoogleVault.Matter.Export.DownloadID
  description: ID to be used by the download-export command
  type: string
- contextPath: GoogleVault.Matter.Export.ViewID
  description: ID to be used by the get-X-results command (X=drive/mail/groups)
  type: string
- contextPath: GoogleVault.Matter.Export
  description: Export object
  type: unknown
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '23'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 14cac14a-3745-46d2-8ef6-da411a06da52
      iscommand: false
      name: ''
      version: -1
    taskid: 14cac14a-3745-46d2-8ef6-da411a06da52
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 210\n  }\n}"
  '15':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.downloadFile
          operator: isEqualString
          right:
            value:
              simple: 'true'
      label: 'yes'
    id: '15'
    nexttasks:
      '#default#':
      - '5'
      'yes':
      - '17'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 3f8f4650-cc6f-4dde-85cf-52875002b5a1
      iscommand: false
      name: Check downloadFile
      type: condition
      version: -1
    taskid: 3f8f4650-cc6f-4dde-85cf-52875002b5a1
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 40,\n    \"y\": 1580\n  }\n}"
  '16':
    id: '16'
    nexttasks:
      '#none#':
      - '18'
    note: false
    scriptarguments:
      exportID:
        complex:
          accessor: Matter.Export.ExportID
          root: GoogleVault
      exportIDS:
        complex:
          accessor: Matter.Export.ExportID
          root: GoogleVault
      matterId:
        complex:
          accessor: Matter.Export.MatterID
          root: GoogleVault
      queryIDS: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: f873bc49-88c8-4095-8ab1-440e337f2b0f
      iscommand: true
      name: Get Export status to context
      script: '|||gvault-export-status'
      type: regular
      version: -1
    taskid: f873bc49-88c8-4095-8ab1-440e337f2b0f
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 730\n  }\n}"
  '17':
    id: '17'
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      bucketName:
        complex:
          accessor: Matter.Export.BucketName
          root: GoogleVault
      downloadID:
        complex:
          accessor: Matter.Export.DownloadID
          root: GoogleVault
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: b77d974e-d9c0-4ace-87e1-4344eb70c3e9
      iscommand: true
      name: Download Export file
      script: '|||gvault-download-results'
      type: regular
      version: -1
    taskid: b77d974e-d9c0-4ace-87e1-4344eb70c3e9
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 40,\n    \"y\": 1810\n  }\n}"
  '18':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Matter.Export.Status
                root: GoogleVault
          operator: isEqualString
          right:
            value:
              simple: COMPLETED
      label: 'yes'
    id: '18'
    nexttasks:
      '#default#':
      - '19'
      'yes':
      - '20'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 29cf7602-509a-49b1-8a73-558783b23992
      iscommand: false
      name: Check if status COMPLETED
      type: condition
      version: -1
    taskid: 29cf7602-509a-49b1-8a73-558783b23992
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 920\n  }\n}"
  '19':
    id: '19'
    nexttasks:
      '#none#':
      - '5'
    note: false
    scriptarguments:
      message:
        simple: 'Polling time out: Your search is taking a bit more time. To see your
          results please run this integration once more with a grater ''PollIntarval''
          and ''PollTimeout'' using this ExportID: ${GoogleVault.Matter.Export.ExportID}
          and MatterID: ${GoogleVault.Matter.Export.MatterID}'
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 1662b04a-4594-48d7-8045-cbc5ab3e1d62
      iscommand: false
      name: Polling Timeout
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 1662b04a-4594-48d7-8045-cbc5ab3e1d62
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 760,\n    \"y\": 1110\n  }\n}"
  '2':
    id: '2'
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '16'
    note: false
    scriptarguments:
      Ids:
        simple: ${GoogleVault.Matter.MatterID}#${GoogleVault.Matter.Export.[0].ExportID}
      Interval:
        complex:
          root: inputs.pollInterval
      PollingCommandArgName:
        simple: queryIDS
      PollingCommandName:
        simple: gvault-export-status
      Timeout:
        complex:
          root: inputs.pollTimeout
      dt:
        simple: GoogleVault.Matter.Export(val.Status != 'COMPLETED')=val.MatterID
          + '#' + val.ExportID
    separatecontext: true
    task:
      brand: ''
      description: 'Use as a sub-playbook to block execution of the master playbook
        until a remote action is complete.

        This playbook implements polling by continually running the command in Step
        #2 until the operation completes.

        The remote action should have the following structure:


        1. Initiate the operation.

        2. Poll to check if the operation completed.

        3. (optional) Get the results of the operation.'
      id: 5176c141-e27d-4814-8bfd-5cd510f2373a
      iscommand: false
      name: GenericPolling
      playbookName: GenericPolling
      type: playbook
      version: -1
    taskid: 5176c141-e27d-4814-8bfd-5cd510f2373a
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '20':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.SearchtType
          operator: isEqualString
          right:
            value:
              simple: Mail
      label: Mail type
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.SearchtType
          operator: isEqualString
          right:
            value:
              simple: Groups
      label: Group Type
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.SearchtType
          operator: isEqualString
          right:
            value:
              simple: Drive
      label: Drive Type
    id: '20'
    nexttasks:
      Drive Type:
      - '22'
      Group Type:
      - '21'
      Mail type:
      - '3'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 20e92d00-1da1-4519-88a3-b94b3594631e
      iscommand: false
      name: Check Search Type
      type: condition
      version: -1
    taskid: 20e92d00-1da1-4519-88a3-b94b3594631e
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 40,\n    \"y\": 1110\n  }\n}"
  '21':
    id: '21'
    nexttasks:
      '#none#':
      - '15'
    note: false
    scriptarguments:
      bucketName:
        complex:
          accessor: Matter.Export.BucketName
          root: GoogleVault
      maxResult:
        complex:
          root: inputs.maxResultForDisplay
      viewID:
        complex:
          accessor: Matter.Export.ViewID
          root: GoogleVault
    separatecontext: false
    task:
      brand: ''
      description: Get the results of a given mail export
      id: 976638c2-22e7-400e-8a33-d35b13ad9cc5
      iscommand: true
      name: Get Groups results
      script: '|||gvault-get-groups-results'
      type: regular
      version: -1
    taskid: 976638c2-22e7-400e-8a33-d35b13ad9cc5
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 40,\n    \"y\": 1320\n  }\n}"
  '22':
    id: '22'
    nexttasks:
      '#none#':
      - '15'
    note: false
    scriptarguments:
      bucketName:
        complex:
          accessor: Matter.Export.BucketName
          root: GoogleVault
      maxResult:
        complex:
          root: inputs.maxResultForDisplay
      viewID:
        complex:
          accessor: Matter.Export.ViewID
          root: GoogleVault
    separatecontext: false
    task:
      brand: ''
      description: Get the results of a given mail export
      id: b8f65130-b7ff-4a37-81c9-385a68caf2f4
      iscommand: true
      name: Get Drive results
      script: '|||gvault-get-drive-results'
      type: regular
      version: -1
    taskid: b8f65130-b7ff-4a37-81c9-385a68caf2f4
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 500,\n    \"y\": 1320\n  }\n}"
  '23':
    id: '23'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      exportID:
        complex:
          accessor: Matter.Export.ExportID
          root: GoogleVault
      exportIDS:
        complex:
          root: inputs.ExportID
      matterId:
        complex:
          root: inputs.MatterID
      queryIDS: {}
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: b6a4b39d-b0b9-4914-856a-1f8365e43442
      iscommand: true
      name: Get Export status to context
      script: '|||gvault-export-status'
      type: regular
      version: -1
    taskid: b6a4b39d-b0b9-4914-856a-1f8365e43442
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 350\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      '#none#':
      - '15'
    note: false
    scriptarguments:
      bucketName:
        complex:
          accessor: Matter.Export.BucketName
          root: GoogleVault
      maxResult:
        complex:
          root: inputs.maxResultForDisplay
      viewID:
        complex:
          accessor: Matter.Export.ViewID
          root: GoogleVault
    separatecontext: false
    task:
      brand: ''
      description: Get the results of a given mail export
      id: d23be093-82be-472a-85df-b01e155fe19f
      iscommand: true
      name: Get Mail results
      script: '|||gvault-get-mail-results'
      type: regular
      version: -1
    taskid: d23be093-82be-472a-85df-b01e155fe19f
    type: regular
    view: "{\n  \"position\": {\n    \"x\": -430,\n    \"y\": 1320\n  }\n}"
  '5':
    id: '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: ''
      id: 9ed8fed0-adb4-4d5a-8de3-4390979be049
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 9ed8fed0-adb4-4d5a-8de3-4390979be049
    type: title
    view: "{\n  \"position\": {\n    \"x\": 780,\n    \"y\": 2020\n  }\n}"
tests:
- Google_Vault-Search_And_Display_Results_test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1875,\n      \"width\": 1590,\n      \"x\": -430,\n      \"y\"\
  : 210\n    }\n  }\n}"
