id: PerceptionPoint Test
inputs: []
name: PerceptionPoint Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '14'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 3000b795-d4b5-49ce-8191-be05333d4991
      iscommand: false
      name: ''
      version: -1
    taskid: 3000b795-d4b5-49ce-8191-be05333d4991
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      add_to_context:
        simple: 'true'
      brand_name:
        simple: PerceptionPoint
      error_msg_in_incident: {}
      expect_data: {}
      instance_name: {}
    separatecontext: false
    task:
      brand: ''
      id: c7da933a-ea1a-413f-89cc-e16fd3c4f12a
      iscommand: false
      name: Fetch Incidents
      scriptName: FetchFromInstance
      type: regular
      version: -1
    taskid: c7da933a-ea1a-413f-89cc-e16fd3c4f12a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '10':
    id: '10'
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      value:
        simple: Fetched incidents successfully
    separatecontext: false
    task:
      brand: ''
      id: f4aa3ec3-9ccb-4ee6-8b1d-c6da48c423c6
      iscommand: false
      name: Fetched incidents
      scriptName: Print
      type: regular
      version: -1
    taskid: f4aa3ec3-9ccb-4ee6-8b1d-c6da48c423c6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 720\n  }\n}"
  '11':
    continueonerror: true
    id: '11'
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      extend-context:
        simple: ReleseEmailResult=
      id:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    task:
      brand: Builtin
      description: commands.local.cmd.get.entry
      id: 4e5aadc4-4072-43c8-8b6f-4a8d484f6883
      iscommand: true
      name: Get relese-email result
      script: Builtin|||getEntry
      type: regular
      version: -1
    taskid: 4e5aadc4-4072-43c8-8b6f-4a8d484f6883
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1070\n  }\n}"
  '12':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: PP.Released
          operator: isExists
      label: 'yes'
    id: '12'
    nexttasks:
      '#default#':
      - '13'
      'yes':
      - '15'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Check whether given entry/entries returned an error. Use ${lastCompletedTaskEntries}
        to check the previous task entries. If array is provided, will return yes
        if one of the entries returned an error.
      id: a8cfbfdf-fbc5-4bff-83e9-1cc845af9843
      iscommand: false
      name: Success?
      type: condition
      version: -1
    taskid: a8cfbfdf-fbc5-4bff-83e9-1cc845af9843
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 470,\n    \"y\": 1245\n  }\n}"
  '13':
    id: '13'
    note: false
    scriptarguments:
      attachIDs: {}
      bcc: {}
      body:
        simple: playbook failed
      cc: {}
      htmlBody: {}
      noteEntryID: {}
      replyTo: {}
      subject:
        simple: fail playbook
      to:
        simple: yotam.tayeb@perception-point.io
    separatecontext: false
    task:
      brand: Mail Sender (New)
      description: 'Send an email with the specified parameters.

        Attachments are provided as a comma-separated list of entry IDs.

        Example usage: !SendEmail subject="File from war room" body="Please see the
        attached file. --DBot" to=jane@acme.com cc=john@acme.com attachIDs=89@3,46@3'
      id: 92191202-1c83-4e82-813a-c92fec63ca70
      iscommand: false
      name: Send mail
      scriptName: SendEmail
      type: regular
      version: -1
    taskid: 92191202-1c83-4e82-813a-c92fec63ca70
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 715,\n    \"y\": 1435\n  }\n}"
  '14':
    id: '14'
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: a06c3013-1ec5-45aa-818c-072e659e84a1
      iscommand: false
      name: Delete context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: a06c3013-1ec5-45aa-818c-072e659e84a1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '15':
    id: '15'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: a5c29f41-feae-46a0-8e0f-fa7aeeaf7ca1
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: a5c29f41-feae-46a0-8e0f-fa7aeeaf7ca1
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 245,\n    \"y\": 1435\n  }\n}"
  '2':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: FetchedIncidents
          operator: isNotEmpty
      label: 'yes'
    - condition:
      - - left:
            iscontext: true
            value:
              simple: FetchedIncidents
          operator: isEmpty
      label: None
    id: '2'
    nexttasks:
      '#default#':
      - '3'
      'yes':
      - '10'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: b283e190-9aba-4409-8004-fdcd59dff95d
      iscommand: false
      name: Check if incident exists
      type: condition
      version: -1
    taskid: b283e190-9aba-4409-8004-fdcd59dff95d
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 545\n  }\n}"
  '3':
    id: '3'
    note: false
    scriptarguments:
      message:
        simple: The incidents were not fetched
    separatecontext: false
    task:
      brand: ''
      id: 9d4b53b8-fcc7-4a5e-8d71-aae19f1c0e01
      iscommand: false
      name: Incidents were not fetched
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 9d4b53b8-fcc7-4a5e-8d71-aae19f1c0e01
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '9':
    continueonerror: true
    id: '9'
    nexttasks:
      '#none#':
      - '11'
    note: false
    scriptarguments:
      scan_id:
        simple: '80052041'
    separatecontext: false
    task:
      brand: ''
      id: 91fade4a-75bf-4ff1-81ff-61871bba6ead
      iscommand: true
      name: Release the email
      script: '|||pp-release-email'
      type: regular
      version: -1
    taskid: 91fade4a-75bf-4ff1-81ff-61871bba6ead
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 470,\n    \"y\": 900\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1480,\n      \"width\": 1045,\n      \"x\": 50,\n      \"y\":\
  \ 50\n    }\n  }\n}"
