id: TCPUtils-Test
inputs: []
name: Tcpiputlis Test Playbook
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 79784982-3d32-4ed9-8906-cd8da7a7dfb8
      iscommand: false
      name: ''
      version: -1
    taskid: 79784982-3d32-4ed9-8906-cd8da7a7dfb8
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 447,\n    \"y\": -140\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
      - '4'
    note: false
    quietmode: 0
    scriptarguments:
      ip:
        simple: tcpiputils.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: TCPIPUtils
      description: get information for ip
      id: e0a74686-e777-42ef-8233-d24b739a2afa
      iscommand: true
      name: ip
      script: TCPIPUtils|||ip
      type: regular
      version: -1
    taskid: e0a74686-e777-42ef-8233-d24b739a2afa
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 230\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      expectedValue:
        simple: '"AS13335"'
      extend-context: {}
      field1:
        simple: IP.ASN
      field2:
        simple: IP.Geo.Country
      field3:
        simple: IP.Address
      field4: {}
      fields: {}
      path:
        simple: IP.ASN
      value:
        simple: ' ${IP.ASN} ${IP.Address} ${IP.Geo.Country}${IP.Geo.Description}'
      value1:
        simple: ${IP.ASN}
      value2:
        simple: ${IP.Geo.Country}
      value3:
        simple: ${IP.Address}
      value4: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: c1402d0a-75cd-458e-895e-5f8f71dfa863
      iscommand: false
      name: VerifyIPOutput
      script: VerifyContextFields
      type: regular
      version: -1
    taskid: c1402d0a-75cd-458e-895e-5f8f71dfa863
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 120,\n    \"y\": 477\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      expectedValue: {}
      fields:
        simple: Address,WHOIS,ASN
      path:
        simple: IP
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 04c5abc5-d6e2-4270-841d-9b933c325064
      iscommand: false
      name: VerifyContext
      script: VerifyContext
      type: regular
      version: -1
    taskid: 04c5abc5-d6e2-4270-841d-9b933c325064
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 1130,\n    \"y\": 477\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      key: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      id: 0bfe087f-2db5-4fe5-8558-026bec69711c
      iscommand: false
      name: DeleteContext
      script: DeleteContext
      type: regular
      version: -1
    taskid: 0bfe087f-2db5-4fe5-8558-026bec69711c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 447,\n    \"y\": 27\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 712,\n      \"width\": 1390,\n      \"x\": 120,\n      \"y\":\
  \ -140\n    }\n  }\n}"
