contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
elasticcommonfields: {}
id: Test_EDL
inputs: []
name: Test_EDL
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      elasticcommonfields: {}
      id: 3b35f8c5-ad3e-4f8e-8bd6-3ce48c140668
      iscommand: false
      name: ''
      version: -1
    taskid: 3b35f8c5-ad3e-4f8e-8bd6-3ce48c140668
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      edl_size:
        simple: '2'
      print_indicators:
        simple: 'true'
      query:
        simple: Tags:IP
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Updates values stored in the EDL (only avaialable On-Demand).
      elasticcommonfields: {}
      id: 7bd71efa-53d1-4290-8c18-673f62c99e73
      iscommand: true
      name: Check Update EDL
      script: '|||edl-update'
      type: regular
      version: -1
    taskid: 7bd71efa-53d1-4290-8c18-673f62c99e73
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 220\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 265,\n      \"width\": 380,\n      \"x\": 450,\n      \"y\": 50\n\
  \    }\n  }\n}"
