contentitemfields:
  propagationLabels:
  - all
description: Activates network lists in Staging or Production on Akamai WAF. The playbook
  finishes running when the network list is active on the requested enviorment.
fromversion: 4.1.0
id: Akamai WAF - Activate Network Lists
inputs:
- description: ' A comma-separated list of network list IDs to activate. For example:
    id_list1,id_list2. '
  key: network_list_ids
  required: true
  value: {}
- description: Enviorment type to activate the network list. Can be "STAGING" or "PRODUCTION".
  key: env
  required: true
  value: {}
- description: A comment to log when activating the network lists.
  key: comment
  required: false
  value: {}
- description: A comma-separated list of email addresses to notify when the network
    lists are activated.
  key: notify
  required: false
  value: {}
name: Akamai WAF - Activate Network Lists
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 6db69c54-1ff3-4b46-8b6c-60506443f3ef
      iscommand: false
      name: ''
      version: -1
    taskid: 6db69c54-1ff3-4b46-8b6c-60506443f3ef
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      comment:
        simple: ${inputs.comment}
      env:
        simple: ${inputs.env}
      network_list_ids:
        simple: ${inputs.network_list_ids}
      notify:
        simple: ${inputs.notify}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: fb437f2c-767d-46d7-8000-482a1b4a77c4
      iscommand: true
      name: Activate network list in selected enviorment
      script: '|||akamai-activate-network-list'
      type: regular
      version: -1
    taskid: fb437f2c-767d-46d7-8000-482a1b4a77c4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: env
      AdditionalPollingCommandArgValues:
        simple: ${inputs.env}
      Ids:
        simple: ${inputs.network_list_ids}
      Interval:
        simple: '1'
      PollingCommandArgName:
        simple: network_list_ids
      PollingCommandName:
        simple: akamai-get-network-list-activation-status
      Timeout:
        simple: '30'
      dt:
        simple: Akamai.NetworkLists.ActivationStatus(val.StagingStatus != 'ACTIVE').UniqueID
    separatecontext: true
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: e74b46f9-4d31-4520-84cf-8b05d070ab29
      iscommand: false
      name: Generic Polling
      playbookName: GenericPolling
      type: playbook
      version: -1
    taskid: e74b46f9-4d31-4520-84cf-8b05d070ab29
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '4':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.env
          operator: isEqualString
          right:
            value:
              simple: PRODUCTION
      label: 'yes'
    id: '4'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '3'
      'yes':
      - '5'
    note: false
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 0f81a60a-8b9b-4e5d-8e81-a87fa0a83372
      iscommand: false
      name: Environment Type - Staging or Production
      type: condition
      version: -1
    taskid: 0f81a60a-8b9b-4e5d-8e81-a87fa0a83372
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 370\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    loop:
      exitCondition: ''
      iscommand: false
      wait: 1
    nexttasks:
      '#none#':
      - '7'
    note: false
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: env
      AdditionalPollingCommandArgValues:
        simple: ${inputs.env}
      Ids:
        simple: ${inputs.network_list_ids}
      Interval:
        simple: '1'
      PollingCommandArgName:
        simple: network_list_ids
      PollingCommandName:
        simple: akamai-get-network-list-activation-status
      Timeout:
        simple: '30'
      dt:
        simple: Akamai.NetworkLists.ActivationStatus(val.StagingStatus != 'ACTIVE'
          ).UniqueID
    separatecontext: true
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: e406cad5-9503-498d-8595-4e64281daf62
      iscommand: false
      name: Generic Polling
      playbookName: GenericPolling
      type: playbook
      version: -1
    taskid: e406cad5-9503-498d-8595-4e64281daf62
    timertriggers: []
    type: playbook
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    note: false
    scriptarguments:
      value:
        simple: Akamai networklists - activation **${inputs.network_list_ids}** in
          **${inputs.env}** finished **succefully**
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      id: 85bfe24f-9929-4200-88d8-12da83e72e87
      iscommand: false
      name: Print
      scriptName: Print
      type: regular
      version: -1
    taskid: 85bfe24f-9929-4200-88d8-12da83e72e87
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 720\n  }\n}"
tests:
- No test
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 765,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
