description: Following a failed login event happening more than 3 times, ask user
  on Slack if she attempted a login. If no, raise the incident level to high. If yes,
  ask user if she needs a password reset and reset the password in AD.
fromversion: 2.5.0
id: Failed Login Playbook With Slack
name: Failed Login Playbook With Slack
starttaskid: '0'
system: true
tasks:
  '0':
    id: '0'
    nexttasks:
      '#none#':
      - '2'
    task:
      brand: ''
      description: ''
      id: e0772674-d7ff-43df-8075-a871655a3f9b
      iscommand: false
      name: start_task
      type: start
      version: -1
    taskid: e0772674-d7ff-43df-8075-a871655a3f9b
    type: start
    view: "{\n  \"position\": {\n    \"x\": 270,\n    \"y\": 50\n  }\n}"
  '2':
    id: '2'
    nexttasks:
      '#none#':
      - '3'
    scriptarguments:
      message: We noticed failed-login attempts with your user ID, please confirm
        it was your attempts
      option1: ''
      option2: ''
      task: '3'
      user: ${incident.labels.Email}
    task:
      brand: ''
      clonedfrom: 7a39f05d-23c9-412d-8e36-3dd1ba0dd2f2
      description: Ask user regarding his/her failed login attempts
      id: cdd77c13-ca81-4c68-8679-19d08de8fb71
      iscommand: false
      name: Confirm failed login with user
      scriptName: SlackAskUser
      type: regular
      version: -1
    taskid: cdd77c13-ca81-4c68-8679-19d08de8fb71
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 270,\n    \"y\": 200\n  }\n}"
  '3':
    id: '3'
    nexttasks:
      'no':
      - '4'
      'yes':
      - '5'
    task:
      brand: ''
      description: Answer `yes` if failed login attempt made by the user
      id: 58679e35-4e24-4d2a-89ba-22fbd161f308
      iscommand: false
      name: Was the failed login attempt by the user?
      version: -1
    taskid: 58679e35-4e24-4d2a-89ba-22fbd161f308
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 270,\n    \"y\": 370\n  }\n}"
  '4':
    id: '4'
    scriptarguments:
      addLabels: ''
      customFieldName: ''
      customFieldValue: ''
      details: ''
      labels: ''
      name: ''
      owner: ''
      playbook: ''
      severity: High
      stage: ''
      type: ''
      updatePlaybookForType: ''
    task:
      brand: ''
      description: ''
      id: ce32bc35-0679-4b9b-842f-e4b0c942a157
      iscommand: false
      name: Raise Incident Severity to High
      scriptName: IncidentSet
      type: regular
      version: -1
    taskid: ce32bc35-0679-4b9b-842f-e4b0c942a157
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 48,\n    \"y\": 545\n  }\n}"
  '5':
    id: '5'
    nexttasks:
      '#none#':
      - '6'
    scriptarguments:
      message: Should we reset your password?
      option1: ''
      option2: ''
      task: '6'
      user: ${incident.labels.Email}
    task:
      brand: ''
      description: ''
      id: 987f04ae-98f1-4e27-8ef3-1a4f459acaa2
      iscommand: false
      name: Ask user should we reset her password
      scriptName: SlackAskUser
      type: regular
      version: -1
    taskid: 987f04ae-98f1-4e27-8ef3-1a4f459acaa2
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 545\n  }\n}"
  '6':
    id: '6'
    nexttasks:
      'no':
      - '9'
      'yes':
      - '7'
    scriptarguments:
      message: Would you like us to reset your password?
      option1: ''
      option2: ''
      task: '6'
      user: ${incident.labels.Email}
    task:
      brand: ''
      description: Answer `yes` if password should be reset
      id: 6b4648d9-512a-417c-86e6-d468d05c5b63
      iscommand: false
      name: Should we reset the password?
      type: condition
      version: -1
    taskid: 6b4648d9-512a-417c-86e6-d468d05c5b63
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 720\n  }\n}"
  '7':
    id: '7'
    nexttasks:
      '#none#':
      - '8'
    scriptarguments:
      username: ${incident.labels.User}
    task:
      brand: ''
      clonedfrom: b061d5be-194d-4413-804b-ea47a7f05317
      description: Expire user password
      id: a12faaf4-cbbe-49ce-8539-f4ed61279deb
      iscommand: false
      name: Expire Password
      scriptName: ADExpirePassword
      type: regular
      version: -1
    taskid: a12faaf4-cbbe-49ce-8539-f4ed61279deb
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 732,\n    \"y\": 894\n  }\n}"
  '8':
    id: '8'
    nexttasks:
      '#none#':
      - '9'
    scriptarguments:
      IgnoreAddURL: ''
      channel: ''
      entry: ''
      group: ''
      message: Your password was reset
      to: ${incident.labels.Email}
    task:
      brand: slack
      clonedfrom: 5e3d77e5-2172-4f74-87b6-c54e0f70fa62
      description: Notify user that his/her password has been reset
      id: 0531af1c-0b85-40c8-89c3-e1d22b064ad6
      iscommand: true
      name: Notify User on Slack
      script: slack|||slack-send
      type: regular
      version: -1
    taskid: 0531af1c-0b85-40c8-89c3-e1d22b064ad6
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 732,\n    \"y\": 1069\n  }\n}"
  '9':
    id: '9'
    scriptarguments:
      notes: User verified he did the attempt
      reason: Not an attack
    task:
      brand: ''
      description: ''
      id: abd944e7-152b-4e45-8e2f-92cd19ea6bb4
      iscommand: false
      name: Close the incident
      scriptName: CloseInvestigation
      type: regular
      version: -1
    taskid: abd944e7-152b-4e45-8e2f-92cd19ea6bb4
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1245\n  }\n}"
tests:
- no test - manual task
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"6_9_no\": 0.71\n  },\n  \"paper\": {\n\
  \    \"dimensions\": {\n      \"height\": 1290,\n      \"width\": 1064,\n      \"\
  x\": 48,\n      \"y\": 50\n    }\n  }\n}"
