fromversion: 4.1.0
id: EmailReputationTest
inputs: []
name: EmailReputationTest
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 22b5220c-858e-4345-8454-eb6b491a7865
      iscommand: false
      name: ''
      version: -1
    taskid: 22b5220c-858e-4345-8454-eb6b491a7865
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 8949501b-f9eb-462a-89b6-10ec1f199b48
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 8949501b-f9eb-462a-89b6-10ec1f199b48
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 230\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      query:
        simple: salkunkel@twc.com
      whitelist: {}
    separatecontext: false
    task:
      brand: ''
      id: f6d9c061-864b-44f1-865e-cd6c936f38f0
      iscommand: false
      name: Delete Indicator
      scriptName: DeleteIndicators
      type: regular
      version: -1
    taskid: f6d9c061-864b-44f1-865e-cd6c936f38f0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 410\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    reputationcalc: 2
    scriptarguments:
      entryID: {}
      filePath: {}
      investigationID: {}
      text:
        simple: 'Email which pwned should mark as malicious: salkunkel@twc.com'
    separatecontext: false
    task:
      brand: Builtin
      id: 2a8faa66-6754-4100-8b13-f73cd945329e
      iscommand: true
      name: Extract Indicator
      script: Builtin|||extractIndicators
      type: regular
      version: -1
    taskid: 2a8faa66-6754-4100-8b13-f73cd945329e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 550\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    reputationcalc: 1
    scriptarguments:
      extend-context:
        simple: res_score=.
      indicator:
        simple: salkunkel@twc.com
    separatecontext: false
    task:
      brand: ''
      description: Add into the incident's context the system internal DBot score
        for the input indicator
      id: 200050bf-42bd-4ce1-8107-24a4c4924069
      iscommand: false
      name: Get Indicator Score
      scriptName: GetIndicatorDBotScore
      type: regular
      version: -1
    taskid: 200050bf-42bd-4ce1-8107-24a4c4924069
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 1100\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 84438d9a-be4c-4feb-82da-eb62bf79fca9
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 84438d9a-be4c-4feb-82da-eb62bf79fca9
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 705\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      seconds:
        simple: '2'
    separatecontext: false
    task:
      brand: ''
      description: Sleep for X seconds, Needed to make sure that indicator is returned
        in next step.
      id: 6c1c7aa6-bc8f-43ed-8304-0ac42d7bf552
      iscommand: false
      name: Sleep
      scriptName: Sleep
      type: regular
      version: -1
    taskid: 6c1c7aa6-bc8f-43ed-8304-0ac42d7bf552
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 910\n  }\n}"
  '7':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: res_score.DBotScore.[0].Score
          operator: isEqualString
          right:
            value:
              simple: '2'
      label: 'yes'
    id: '7'
    ignoreworker: false
    nexttasks:
      '#default#':
      - '8'
      'yes':
      - '9'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 8bcbbc02-fbc3-4df4-8815-4b4126b3b8e9
      iscommand: false
      name: Verify Score
      type: condition
      version: -1
    taskid: 8bcbbc02-fbc3-4df4-8815-4b4126b3b8e9
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 450,\n    \"y\": 1280\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    note: false
    scriptarguments:
      message:
        simple: 'Didn''t get proper score for indicator. Expected: 2, Got: ${res_score.DBotScore.[0].Score}'
    separatecontext: false
    task:
      brand: ''
      description: Prints an error entry with a given message
      id: 46aee8e6-6e57-46e9-8f19-05156909d7d4
      iscommand: false
      name: Error
      scriptName: PrintErrorEntry
      type: regular
      version: -1
    taskid: 46aee8e6-6e57-46e9-8f19-05156909d7d4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 660,\n    \"y\": 1460\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    note: false
    scriptarguments:
      value:
        simple: Success
    separatecontext: false
    task:
      brand: ''
      description: Prints text to war room (Markdown supprted)
      id: 345ae849-616a-4687-86c7-29563fca8513
      iscommand: false
      name: Success
      scriptName: Print
      type: regular
      version: -1
    taskid: 345ae849-616a-4687-86c7-29563fca8513
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 200,\n    \"y\": 1470\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 1515,\n      \"width\": 840,\n      \"x\": 200,\n      \"y\":\
  \ 50\n    }\n  }\n}"
