contentitemfields:
  propagationLabels: []
id: Pwned v2 test
inputs: []
name: Pwned v2 test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '19'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 4b82ab1e-c38c-425d-823a-a69b8dd45286
      iscommand: false
      name: ''
      version: -1
    taskid: 4b82ab1e-c38c-425d-823a-a69b8dd45286
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    scriptarguments:
      email:
        simple: example@demisto.com
    separatecontext: false
    task:
      brand: Have I Been Pwned? V2
      description: Checks if an email has been compromised, as part of previous breaches.
      id: 6c7ab62b-9537-4f4b-8cf8-ce210c14b6c0
      iscommand: true
      name: Get email
      script: Have I Been Pwned? V2|||email
      type: regular
      version: -1
    taskid: 6c7ab62b-9537-4f4b-8cf8-ce210c14b6c0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1070\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: a9d8365a-df97-403c-8195-556f06229e89
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: a9d8365a-df97-403c-8195-556f06229e89
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1420\n  }\n}"
  '11':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Indicator
          operator: isEqualString
          right:
            value:
              simple: bt53h6htyj8j57k9k=organization.org@ozzy.qwer.de
      label: 'yes'
    id: '11'
    ignoreworker: false
    nexttasks:
      'yes':
      - '20'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: ff0b5f5a-1913-406f-8052-8d5f1fe68ea2
      iscommand: false
      name: Check email with `=` in DBotScore
      type: condition
      version: -1
    taskid: ff0b5f5a-1913-406f-8052-8d5f1fe68ea2
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2820\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    scriptarguments:
      email:
        simple: joe@gmail.com
    separatecontext: false
    task:
      brand: Have I Been Pwned? V2
      description: Checks if an email has been compromised, as part of previous breaches.
      id: 546badfd-61bc-4145-825b-60558cc4bf2c
      iscommand: true
      name: Get Email2
      script: Have I Been Pwned? V2|||email
      type: regular
      version: -1
    taskid: 546badfd-61bc-4145-825b-60558cc4bf2c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1770\n  }\n}"
  '13':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: Email.Pwned-V2.Compromised.Reporters
                root: Account
          operator: containsString
          right:
            value:
              simple: 000webhost
      label: 'yes'
    id: '13'
    ignoreworker: false
    nexttasks:
      'yes':
      - '15'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: fbe135b2-d21b-417a-8f4f-897719c0a458
      iscommand: false
      name: Check email domains
      type: condition
      version: -1
    taskid: fbe135b2-d21b-417a-8f4f-897719c0a458
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1945\n  }\n}"
  '14':
    id: '14'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '18'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: 9b01bfc9-6f5f-420d-809d-e4a8f7ff21b4
      iscommand: false
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 9b01bfc9-6f5f-420d-809d-e4a8f7ff21b4
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2295\n  }\n}"
  '15':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Account.Email.Pwned-V2.Compromised.Reporters
          operator: containsString
          right:
            value:
              simple: Pastebin
      label: 'yes'
    id: '15'
    ignoreworker: false
    nexttasks:
      'yes':
      - '14'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 4331d0a8-e575-4e30-89d4-69c5f2e1f6d4
      iscommand: false
      name: Check paste
      type: condition
      version: -1
    taskid: 4331d0a8-e575-4e30-89d4-69c5f2e1f6d4
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2120\n  }\n}"
  '16':
    id: '16'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      seconds:
        simple: '2'
    separatecontext: false
    task:
      brand: ''
      description: Sleep for X seconds
      id: c53a54aa-5645-4698-8e79-a5fc4f5948f3
      iscommand: false
      name: Sleep
      scriptName: Sleep
      type: regular
      version: -1
    taskid: c53a54aa-5645-4698-8e79-a5fc4f5948f3
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 895\n  }\n}"
  '17':
    id: '17'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    scriptarguments:
      seconds:
        simple: '6'
    separatecontext: false
    task:
      brand: ''
      description: Sleep for X seconds
      id: ea7cf5c2-71bd-4200-80c1-59f2f07ceba0
      iscommand: false
      name: Sleep
      scriptName: Sleep
      type: regular
      version: -1
    taskid: ea7cf5c2-71bd-4200-80c1-59f2f07ceba0
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1595\n  }\n}"
  '18':
    id: '18'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    scriptarguments:
      seconds:
        simple: '2'
    separatecontext: false
    task:
      brand: ''
      description: Sleep for X seconds
      id: a7abdcb7-d101-46d5-815b-6f098a0e6bd6
      iscommand: false
      name: Sleep
      scriptName: Sleep
      type: regular
      version: -1
    taskid: a7abdcb7-d101-46d5-815b-6f098a0e6bd6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2470\n  }\n}"
  '19':
    id: '19'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      seconds:
        simple: '2'
    separatecontext: false
    task:
      brand: ''
      description: Sleep for X seconds
      id: b1b46e62-70b3-4369-8e2f-f47b7ec8c944
      iscommand: false
      name: Sleep
      scriptName: Sleep
      type: regular
      version: -1
    taskid: b1b46e62-70b3-4369-8e2f-f47b7ec8c944
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '20':
    id: '20'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '21'
    note: false
    scriptarguments:
      domain:
        simple: AbuseWith.Us,Acne.org
    separatecontext: false
    task:
      brand: Have I Been Pwned? V2
      description: Checks if a domain was compromised.
      id: e889b7b7-714a-4c98-8d03-051caf0f5d7a
      iscommand: true
      name: Test domain with CSV
      script: Have I Been Pwned? V2|||domain
      type: regular
      version: -1
    taskid: e889b7b7-714a-4c98-8d03-051caf0f5d7a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2995\n  }\n}"
  '21':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Domain.Name
          operator: containsGeneral
          right:
            value:
              simple: Acne.org
      - - left:
            iscontext: true
            value:
              simple: Domain.Name
          operator: isEqualString
          right:
            value:
              simple: AbuseWith.Us
      label: 'yes'
    id: '21'
    ignoreworker: false
    nexttasks:
      'yes':
      - '22'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 241dfdd5-8908-4090-8b70-cc4907832e35
      iscommand: false
      name: Verify domain with CSV outputs
      type: condition
      version: -1
    taskid: 241dfdd5-8908-4090-8b70-cc4907832e35
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3170\n  }\n}"
  '22':
    id: '22'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '26'
    note: false
    scriptarguments:
      email:
        simple: test@adobe.com,support@adobe.com
    separatecontext: false
    task:
      brand: Have I Been Pwned? V2
      description: Checks if an email address was compromised.
      id: 9511e15b-5861-4b6f-8dea-5c338d9e498b
      iscommand: true
      name: Test email with CSV
      script: Have I Been Pwned? V2|||email
      type: regular
      version: -1
    taskid: 9511e15b-5861-4b6f-8dea-5c338d9e498b
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3345\n  }\n}"
  '26':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Account.Email.Address
          operator: containsGeneral
          right:
            value:
              simple: test@adobe.com
      - - left:
            iscontext: true
            value:
              simple: Account.Email.Address
          operator: isEqualString
          right:
            value:
              simple: support@adobe.com
      label: 'yes'
    id: '26'
    ignoreworker: false
    nexttasks:
      'yes':
      - '7'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: c75e048c-3dab-466f-884e-9730829e5a07
      iscommand: false
      name: Verify email with CSV outputs
      type: condition
      version: -1
    taskid: c75e048c-3dab-466f-884e-9730829e5a07
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3520\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      domain:
        simple: adobe.com
      fullResponse: {}
      include_inactive: {}
      long: {}
      retries: {}
      sampleSize: {}
      threshold: {}
      wait: {}
    separatecontext: false
    task:
      brand: Have I Been Pwned? V2
      description: Checks if domain has been compromised.
      id: f4d26da3-251b-4be3-8fb1-f441c0a29328
      iscommand: true
      name: Get domain
      script: Have I Been Pwned? V2|||domain
      type: regular
      version: -1
    taskid: f4d26da3-251b-4be3-8fb1-f441c0a29328
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '4':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Score
          operator: isEqualNumber
          right:
            value:
              simple: '2'
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Indicator
          operator: isEqualString
          right:
            value:
              simple: adobe.com
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Type
          operator: isEqualString
          right:
            value:
              simple: domain
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Vendor
          operator: isEqualString
          right:
            value:
              simple: Have I Been Pwned? V2
      label: 'yes'
    id: '4'
    ignoreworker: false
    nexttasks:
      'yes':
      - '8'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: a2f750db-6b8c-4863-8b95-f9864acd160c
      iscommand: false
      name: Check domain dBot score
      type: condition
      version: -1
    taskid: a2f750db-6b8c-4863-8b95-f9864acd160c
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '6':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Score
          operator: isEqualNumber
          right:
            value:
              simple: '0'
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Indicator
          operator: isEqualString
          right:
            value:
              simple: example@demisto.com
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Type
          operator: isEqualString
          right:
            value:
              simple: email
      - - left:
            iscontext: true
            value:
              simple: DBotScore.Vendor
          operator: isEqualString
          right:
            value:
              simple: Have I Been Pwned? V2
      label: 'yes'
    id: '6'
    ignoreworker: false
    nexttasks:
      'yes':
      - '10'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 63c01867-7973-4bf1-8053-db39c45e9c0b
      iscommand: false
      name: Check email dBot score
      type: condition
      version: -1
    taskid: 63c01867-7973-4bf1-8053-db39c45e9c0b
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1245\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 61a828f0-70b4-47da-89f9-dcc1bef322db
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 61a828f0-70b4-47da-89f9-dcc1bef322db
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 3695\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      id: 1428d5e2-8d5f-4902-8e00-34d12cd0957e
      iscommand: false
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: 1428d5e2-8d5f-4902-8e00-34d12cd0957e
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    reputationcalc: 2
    scriptarguments:
      value:
        simple: bt53h6htyj8j57k9k=organization.org@ozzy.qwer.de
    separatecontext: false
    task:
      brand: ''
      description: Prints text to war room (Markdown supported)
      id: 1d678e6c-a3b7-43bb-84ae-87f9bbf277aa
      iscommand: false
      name: check email indicator regex (auto enrich)
      scriptName: Print
      type: regular
      version: -1
    taskid: 1d678e6c-a3b7-43bb-84ae-87f9bbf277aa
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 2645\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {\n    \"6_10_yes\": 0.89\n  },\n  \"paper\":\
  \ {\n    \"dimensions\": {\n      \"height\": 3710,\n      \"width\": 380,\n   \
  \   \"x\": 50,\n      \"y\": 50\n    }\n  }\n}"
