description: ''
elasticcommonfields: {}
id: Tanium Threat Response Test
inputs: []
name: Tanium Threat Response Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      elasticcommonfields: {}
      id: f13f7e5c-80e3-42d4-8e3e-82090b4cd9de
      iscommand: false
      name: ''
      version: -1
    taskid: f13f7e5c-80e3-42d4-8e3e-82090b4cd9de
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
      - '4'
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Delete field from context
      elasticcommonfields: {}
      id: ef23e26c-ae70-424d-826b-3088caf15921
      iscommand: false
      name: Clear context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: ef23e26c-ae70-424d-826b-3088caf15921
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 265,\n    \"y\": 195\n  }\n}"
  '10':
    id: '10'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '11'
    note: false
    quietmode: 0
    scriptarguments:
      limit: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Returns all available labels in the system.
      elasticcommonfields: {}
      id: 35bec9d6-edb7-441a-8201-d9467ae6f3d6
      iscommand: true
      name: Get labels list
      script: '|||tanium-tr-list-labels'
      type: regular
      version: -1
    taskid: 35bec9d6-edb7-441a-8201-d9467ae6f3d6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1390\n  }\n}"
  '11':
    id: '11'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      elasticcommonfields: {}
      id: 492a460d-2b05-437e-8a70-20b8a981b0a0
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 492a460d-2b05-437e-8a70-20b8a981b0a0
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1580\n  }\n}"
  '12':
    id: '12'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '14'
    note: false
    quietmode: 0
    scriptarguments:
      alert-id:
        simple: '1'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Returns alert object based on ID.
      elasticcommonfields: {}
      id: 29f777ed-0bfb-4a74-884e-2ab654b2b88a
      iscommand: true
      name: Get alert by ID
      script: '|||tanium-tr-get-alert-by-id'
      type: regular
      version: -1
    taskid: 29f777ed-0bfb-4a74-884e-2ab654b2b88a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 865\n  }\n}"
  '13':
    id: '13'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '12'
    note: false
    quietmode: 0
    scriptarguments:
      alert-id:
        simple: '1'
      state:
        simple: Resolved
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Update the state of a single alert.
      elasticcommonfields: {}
      id: 0d369dbc-2e0c-4232-8b1c-c4ad0d1bf08f
      iscommand: true
      name: Update alert state
      script: '|||tanium-tr-alert-update-state'
      type: regular
      version: -1
    taskid: 0d369dbc-2e0c-4232-8b1c-c4ad0d1bf08f
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 690\n  }\n}"
  '14':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Tanium.Alert.State
          operator: isEqualString
          right:
            value:
              simple: Resolved
      label: 'yes'
    id: '14'
    ignoreworker: false
    nexttasks:
      'yes':
      - '15'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      elasticcommonfields: {}
      id: 44c23af0-6d88-48e4-8b20-05d5261eb89e
      iscommand: false
      name: Validate alert state
      type: condition
      version: -1
    taskid: 44c23af0-6d88-48e4-8b20-05d5261eb89e
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1040\n  }\n}"
  '15':
    id: '15'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '17'
    note: false
    quietmode: 0
    scriptarguments:
      alert-id:
        simple: '1'
      state:
        simple: Unresolved
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Update the state of a single alert.
      elasticcommonfields: {}
      id: e3d49df8-cae7-45ab-8936-0d431f3fcf5d
      iscommand: true
      name: Update alert state
      script: '|||tanium-tr-alert-update-state'
      type: regular
      version: -1
    taskid: e3d49df8-cae7-45ab-8936-0d431f3fcf5d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1215\n  }\n}"
  '16':
    id: '16'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '24'
    note: false
    quietmode: 0
    scriptarguments:
      connection-name:
        simple: taniumlinux
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Returns a connection object based on name.
      elasticcommonfields: {}
      id: b9be2b4b-09ca-4b05-8123-c2e71086399a
      iscommand: true
      name: Get connection by name
      script: '|||tanium-tr-get-connection-by-name'
      type: regular
      version: -1
    taskid: b9be2b4b-09ca-4b05-8123-c2e71086399a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1565\n  }\n}"
  '17':
    id: '17'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '16'
    note: false
    quietmode: 0
    scriptarguments:
      label-id:
        simple: '1'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Returns label object based on ID.
      elasticcommonfields: {}
      id: 5d630380-5ab2-4c79-8ec9-c784d41710b1
      iscommand: true
      name: Get label by ID
      script: '|||tanium-tr-get-label-by-id'
      type: regular
      version: -1
    taskid: 5d630380-5ab2-4c79-8ec9-c784d41710b1
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1390\n  }\n}"
  '18':
    id: '18'
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      elasticcommonfields: {}
      id: 5c2a510a-acc8-4a94-8b8b-88f8bea736a8
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 5c2a510a-acc8-4a94-8b8b-88f8bea736a8
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 2090\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '13'
    note: false
    quietmode: 0
    scriptarguments:
      intel-doc-id:
        simple: '64'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Returns a intel document object based on ID.
      elasticcommonfields: {}
      id: 0ee63d3d-aaa6-4909-8875-06ac4c1b6313
      iscommand: true
      name: Get intel doc by ID
      script: '|||tanium-tr-get-intel-doc-by-id'
      type: regular
      version: -1
    taskid: 0ee63d3d-aaa6-4909-8875-06ac4c1b6313
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 515\n  }\n}"
  '23':
    id: '23'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '18'
    note: false
    quietmode: 0
    scriptarguments:
      evidence-id:
        simple: '29'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Gets evidence by evidence ID.
      elasticcommonfields: {}
      id: e0c29360-d495-4f23-8cee-88037433bc49
      iscommand: true
      name: tanium-tr-get-evidence-by-id
      script: '|||tanium-tr-get-evidence-by-id'
      type: regular
      version: -1
    taskid: e0c29360-d495-4f23-8cee-88037433bc49
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1915\n  }\n}"
  '24':
    id: '24'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '23'
    note: false
    quietmode: 0
    scriptarguments:
      connection-timeout: {}
      destination:
        simple: taniumlinux
      destination-type:
        simple: ip_address
      remote:
        simple: 'False'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Creates a local or remote connection.
      elasticcommonfields: {}
      id: fb2a3397-283d-40f7-86f7-a169a9d486ed
      iscommand: true
      name: Create connection
      script: '|||tanium-tr-create-connection'
      type: regular
      version: -1
    taskid: fb2a3397-283d-40f7-86f7-a169a9d486ed
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 1740\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '5'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      elasticcommonfields: {}
      id: eb741492-d7cd-4fbd-8082-8cfc2313d0a1
      iscommand: false
      name: Query lists commands
      type: title
      version: -1
    taskid: eb741492-d7cd-4fbd-8082-8cfc2313d0a1
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '4':
    id: '4'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: ''
      elasticcommonfields: {}
      id: f8d9222f-7163-4198-83b8-c98e27498daa
      iscommand: false
      name: Getters
      type: title
      version: -1
    taskid: f8d9222f-7163-4198-83b8-c98e27498daa
    timertriggers: []
    type: title
    view: "{\n  \"position\": {\n    \"x\": 480,\n    \"y\": 370\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '6'
    note: false
    quietmode: 0
    scriptarguments:
      limit: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Returns a list of all intel documents.
      elasticcommonfields: {}
      id: 0dc01348-06b9-480a-8d78-4d5b3874937d
      iscommand: true
      name: Get intel docs list
      script: '|||tanium-tr-list-intel-docs'
      type: regular
      version: -1
    taskid: 0dc01348-06b9-480a-8d78-4d5b3874937d
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 515\n  }\n}"
  '6':
    id: '6'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '7'
    note: false
    quietmode: 0
    scriptarguments:
      computer-ip-address: {}
      computer-name: {}
      intel-doc-id: {}
      limit: {}
      offset: {}
      priority: {}
      scan-config-id: {}
      severity: {}
      state: {}
      type: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Returns a list of all alerts.
      elasticcommonfields: {}
      id: 4b1bfe5e-cacb-4a65-8f99-8913ec05e4dc
      iscommand: true
      name: Get alerts list
      script: '|||tanium-tr-list-alerts'
      type: regular
      version: -1
    taskid: 4b1bfe5e-cacb-4a65-8f99-8913ec05e4dc
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 690\n  }\n}"
  '7':
    id: '7'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '8'
    note: false
    quietmode: 0
    scriptarguments:
      limit:
        simple: '1'
      offset: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Returns all connections.
      elasticcommonfields: {}
      id: 772d2d8e-7749-4b5c-82f6-14c10a8a12fe
      iscommand: true
      name: Get connections list
      script: '|||tanium-tr-list-connections'
      type: regular
      version: -1
    taskid: 772d2d8e-7749-4b5c-82f6-14c10a8a12fe
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 865\n  }\n}"
  '8':
    id: '8'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '9'
    note: false
    quietmode: 0
    scriptarguments:
      connection-name:
        simple: taniumlinux
      connection_name:
        complex:
          accessor: Connection.Name
          root: Tanium
          transformers:
          - operator: FirstArrayElement
      limit:
        simple: '1'
      offset: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Returns all snapshots of a single connection.
      elasticcommonfields: {}
      id: 0a11a1b1-8d05-41bd-8e4b-9f64740936d2
      iscommand: true
      name: Get snapshots list by connection
      script: '|||tanium-tr-list-snapshots-by-connection'
      type: regular
      version: -1
    taskid: 0a11a1b1-8d05-41bd-8e4b-9f64740936d2
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1040\n  }\n}"
  '9':
    id: '9'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '10'
    note: false
    quietmode: 0
    scriptarguments:
      connection-name:
        simple: taniumlinux
      connection_name:
        complex:
          accessor: Connection.Name
          root: Tanium
          transformers:
          - operator: FirstArrayElement
      limit: {}
      offset: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ''
      description: Returns all local snapshots of a single connection.
      elasticcommonfields: {}
      id: ffbfb41d-8f1f-447d-8d37-2cc2081a7c3a
      iscommand: true
      name: Get local snapshots list by connection
      script: '|||tanium-tr-list-local-snapshots-by-connection'
      type: regular
      version: -1
    taskid: ffbfb41d-8f1f-447d-8d37-2cc2081a7c3a
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 1215\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 2105,\n      \"width\": 810,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
