description: ''
id: SecBI - Test
inputs: []
name: SecBI - Test
outputs: []
starttaskid: '0'
tasks:
  '0':
    id: '0'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '2'
    note: false
    separatecontext: false
    task:
      brand: ''
      id: 02b0cf46-1242-420e-8a44-9eb49cd49a56
      iscommand: false
      name: ''
      version: -1
    taskid: 02b0cf46-1242-420e-8a44-9eb49cd49a56
    timertriggers: []
    type: start
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 50\n  }\n}"
  '1':
    id: '1'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '3'
    note: false
    scriptarguments:
      limit:
        simple: '3'
    separatecontext: false
    task:
      brand: ''
      id: ee84b2ae-a1b2-491a-803d-568cb49785d6
      iscommand: true
      name: Get Incidents by Query
      script: '|||secbi-get-incidents-list'
      type: regular
      version: -1
    taskid: ee84b2ae-a1b2-491a-803d-568cb49785d6
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 370\n  }\n}"
  '2':
    id: '2'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '1'
    note: false
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    task:
      brand: ''
      description: Delete field from context
      id: f51f7332-625c-4700-82d7-0117b5530c2c
      iscommand: false
      name: Delete context
      scriptName: DeleteContext
      type: regular
      version: -1
    taskid: f51f7332-625c-4700-82d7-0117b5530c2c
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 195\n  }\n}"
  '3':
    id: '3'
    ignoreworker: false
    nexttasks:
      '#none#':
      - '4'
    note: false
    scriptarguments:
      incident_id:
        simple: ${SecBI.IncidentsList}
    separatecontext: false
    task:
      brand: ''
      id: de3df3c5-4424-4bf8-8692-982507c0ddbb
      iscommand: true
      name: Get SecBI Incident Data
      script: '|||secbi-get-incident'
      type: regular
      version: -1
    taskid: de3df3c5-4424-4bf8-8692-982507c0ddbb
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 545\n  }\n}"
  '4':
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: SecBI.Incident.Host
          operator: isExists
      label: 'yes'
    id: '4'
    ignoreworker: false
    nexttasks:
      'yes':
      - '5'
    note: false
    separatecontext: false
    task:
      brand: ''
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      id: 5892cd5d-eabd-44c1-86a9-4910e4fe165e
      iscommand: false
      name: Check results have host
      type: condition
      version: -1
    taskid: 5892cd5d-eabd-44c1-86a9-4910e4fe165e
    timertriggers: []
    type: condition
    view: "{\n  \"position\": {\n    \"x\": 50,\n    \"y\": 720\n  }\n}"
  '5':
    id: '5'
    ignoreworker: false
    note: false
    scriptarguments:
      value:
        simple: Found Result!
    separatecontext: false
    task:
      brand: ''
      description: Prints text to war room (Markdown supported)
      id: acc6c934-3b9e-4b30-8562-a7bf7463e5a3
      iscommand: false
      name: Print
      scriptName: Print
      type: regular
      version: -1
    taskid: acc6c934-3b9e-4b30-8562-a7bf7463e5a3
    timertriggers: []
    type: regular
    view: "{\n  \"position\": {\n    \"x\": 60,\n    \"y\": 930\n  }\n}"
toversion: 4.1.9
version: -1
view: "{\n  \"linkLabelsPosition\": {},\n  \"paper\": {\n    \"dimensions\": {\n \
  \     \"height\": 975,\n      \"width\": 390,\n      \"x\": 50,\n      \"y\": 50\n\
  \    }\n  }\n}"
